### ISSUE TITLE
Who's using it?

### ISSUE THREAD

**Issue by Keats** [getzola/zola#100]
- https://vincent.is
- https://adrien.is/

**Comment by pka** [comment]
* http://t-rex.tileserver.ch (https://github.com/pka/t-rex-website/)

**Comment by crawfxrd** [comment]
* https://os.phil-opp.com

**Comment by reillysiemens** [comment]
- https://tuckersiemens.com (https://github.com/reillysiemens/tuckersiemens.com/)

**Comment by 17cupsofcoffee** [comment]
https://www.seventeencups.net (https://github.com/17cupsofcoffee/seventeencups.net) :confetti_ball:

**Comment by Keats** [comment]
@17cupsofcoffee Nice! You mention some bugs in your article, is there anything not fixed compared to the next version (0.1.4) https://github.com/Keats/gutenberg/blob/master/CHANGELOG.md?

**Comment by 17cupsofcoffee** [comment]
@Keats I had a couple of instances of stuff acting weird with the live reload (might have been when I edited and saved before another build had finished?), but I've not dug into what the issue was yet - nothing that hitting save again/restarting the server couldn't fix though. Other than that, it was pretty much plain sailing! Looking forward to trying out the new version :)

**Comment by Keats** [comment]
Yeah live reload is the part where it's most likely to have noticeable issues as I'm trying to only reload what's needed but I can't guess what's being used in the templates. Maybe it would make sense to default to a dumb reload (just rebuild the whole site - it will be fast enough for most sites) but have a way to enable the current smart reload in `config.toml` since if you have a few thousands pages, it's better than a full rebuild. 

#122 is related if someone wants to tackle it but I don't think it will be possible to write a perfect smart reload short of keeping track what variables/global functions are being used in the templates.

**Comment by sirodoht** [comment]
* https://sirodoht.xyz/ (https://github.com/sirodoht/sirodoht.xyz)

**Comment by Keats** [comment]
List is in the README and probably going to be in the site as well so this issue can be closed
