### ISSUE TITLE
Feature Request: Differentiate Subsection Pages from Section Pages

### ISSUE THREAD

**Issue by kriskeillor** [getzola/zola#1000]
Currently, Zola has a `transparent` option for sections to pass their pages upwards. That's very helpful to organize content in your filesystem without making navigation too troublesome! 

However there are some use cases for differentiating transparent child pages, passed up, from current-level child pages. They are at different levels in the hierarchies, so clearly there's some reason we're differentiating them, right? We'd like the ability to reflect that in templates. 

My use case is having a index.html that displays the most recent posts from _any_ 1st-level section. However to cut down on organization, my 1st level sections are "super sections" that display all their _top level_ pages and then _subsections_' pages, broken out by subsection titles and descriptions. 

This is working currently, but none of the subsections are transparent. Therefore none of them show up on my home page. But if I set transparent=true, the subsections pages are duplicated twice on super sections: once in their breakout, and once at the top of the supersection, being included with the top-level pages. 

**Request**
Add a separate variable **top_pages** that only includes pages directly in the same folder as an `_index.md` section. 

**Alternate Solution**
Add a `get_child_pages(Array<String>)` macro that would scrape the provided array of subsection paths for all their child pages, either as paths or objects. Obviously this approach requires very different design choices than the above choice. It's a little more niche I think. 

Thanks

**Comment by Keats** [comment]
You can use the `ancestors` of each page to know where they come from, which would solve your issue I think?

**Comment by kriskeillor** [comment]
Thanks for the pointer Keats, I'll [check that out](https://www.getzola.org/documentation/templates/pages-sections/). 

Btw, if you want to register functions in Tera with Zola, you have to edit and recompile the Zola source, right? There's no way to do it from inside a template or such?

**Comment by Keats** [comment]
> Btw, if you want to register functions in Tera with Zola, you have to edit and recompile the Zola source, right? 

Correct since it's Rust code.

**Comment by kriskeillor** [comment]
So with transparent sections, the ancestors function returns the most ancient parent directory has `transparent = false` set. Additionally it returns the file names of the section indices -- so a lot of `_index.md` that I don't know how to differentiate (didn't try). Instead I used this approach: 

``` tera
{% set_global all_pages = [] -%}
{% set_global all_sections = [] -%}

{% for p in section.subsections -%}
    {% set sub = get_section(path=p) -%}
    {% set_global all_pages = all_pages | concat(with=sub.pages) -%}
    {% set_global all_sections = all_sections | concat(with=sub.subsections) -%}
{% endfor %}

{% for p in all_sections -%}
    {% set sub = get_section(path=p) -%}
    {% set_global all_pages = all_pages | concat(with=sub.pages) %}
{% endfor %}

{% for page in all_pages | sort(attribute="date") | reverse -%}
    <!-- Your Output Here! -->
{% endfor %}
```
Cheers!
