### ISSUE TITLE
[Bug Report] render codes in fenced code block as shortcode

### ISSUE THREAD

**Issue by zombie110year** [getzola/zola#1003]
# Bug Report

I have written a note for tera's template syntax, but when I build, it throw out:

```
Error: Failed to render content of ****.md
Reason: Failed to render super shortcode
Reason: Tried to render `shortcodes/super.html` but the template wasn't found
```

the source text is

~~~markdown
We can use `super` to import content from base template:

```jinja2
{% block head %}
    {{ super() }}
{% endblock head %}
```
~~~

## Environment
Zola version: 0.10.1
## Expected Behavior

render it as a literal block.

## Current Behavior

```
Error: Failed to render content of ****.md
Reason: Failed to render super shortcode
Reason: Tried to render `shortcodes/super.html` but the template wasn't found
```

## Step to reproduce

Create a fenced code block, and write some code whose syntax is similar with shortcode, and run `zola build` or `zola serve`.

**Comment by Keats** [comment]
There is a special syntax for that to make the shortcode renderer ignore it : https://www.getzola.org/documentation/content/shortcodes/#shortcodes-without-body the last paragraph.

See https://github.com/getzola/zola/blob/master/docs/content/documentation/content/shortcodes.md for an example on how to use it.
