### ISSUE TITLE
Add syntax highlighting for scheme and/or racket

### ISSUE THREAD

**Issue by urbanslug** [getzola/zola#1006]
Zola has syntax highlighting for lisp but doesn't support neither scheme nor racket.

Edit 1:
Coming here from https://www.getzola.org/documentation/content/syntax-highlighting/
_If you want to highlight a language not on this list, please open an issue or a pull request on the Zola repo._

I'm willing to work on this if it's not too complicated

**Comment by Keats** [comment]
I'm planning to update most/all syntaxes soonish, I'll include those as well

**Comment by Keats** [comment]
I've added Racket but it seems that https://github.com/egrachev/sublime-scheme/blob/master/Scheme.tmTheme cannot be converted easily to .sublime-syntax. Is racket enough?

**Comment by urbanslug** [comment]
Sorry for the late response.
Yes I believe it's enough as far as syntax highlighting goes.

I don't know **exactly** how scheme and racket differ but I believe they differ in their underlying implementations and semantics which shouldn't affect syntax highlighting.
For more: https://stackoverflow.com/questions/3345397/how-is-racket-different-from-scheme
