### ISSUE TITLE
Feature Request: Add optional Sass compiled css subfolder

### ISSUE THREAD

**Issue by tosti007** [getzola/zola#1007]
Personally I like to have all my javascript and css in their respective `js` and `css` folders. This way I can link to them with e.g. `<script src="js/words.js"></script>`. 

Currently all compiled sass is placed under `pulic/`. So I think it would be a nice feature to have a additional configuration option to place all compiled sass in a certain folder. Ofcourse the default would be `/` to allow for non-breaking updates.

Hopefully you think this would be neat too! Thanks in advance.

**Comment by southerntofu** [comment]
Can you put your SASS files in sass/css/ folder instead of just sass/ ? It should do just what you want.

**Comment by tosti007** [comment]
True, but I thought that would be a neat feature. Reconsidering it might just add unnecessary complexity.
