### ISSUE TITLE
Show related content in page

### ISSUE THREAD

**Issue by mambisi** [getzola/zola#1012]
How to show related content to a specific page.

**Comment by Keats** [comment]
You would have to define what is a related content. Do you mean other pages similar to it?

**Comment by mambisi** [comment]
example is pages related by tag or category taxonomies

**Comment by mambisi** [comment]
check HUGO implementation [Here](https://gohugo.io/content-management/related/)

**Comment by Keats** [comment]
There's nothing like that in Zola currently.

**Comment by Keats** [comment]
Not going to happen probably or it wouldn't be super useful vs the available taxonomies functions.
