### ISSUE TITLE
Rebuild is broken by index.md file

### ISSUE THREAD

**Issue by hulufei** [getzola/zola#1014]
# Bug Report

Rebuild keep getting this error: `Error: Change on "/content/somepage.md" detected but only files named index.md with an optional language code are allowed` 

## Environment

Zola version: 0.10.1

## Expected Behavior

Rebuild should just works, and the error message should be more helpful.

## Step to reproduce

Put an `index.md` file in `content/`, create any other valid pages under `content/`, then edit one of these pages should trigger the error.

Delete `index.md` then everything is ok.

**Comment by Keats** [comment]
What is not broken by the current rebuild :(
