### ISSUE TITLE
Allow different filename for rss.xml

### ISSUE THREAD

**Issue by ad-si** [getzola/zola#1015]
I'm moving from Jekyll to Zola with an existing blog. Several hundred people already have subscribed the newsfeed at `/atom.xml`, so I need to be able to keep this URL to not break their subscriptions.
Therefore it would be call if there was a way to set the filepath.
Maybe something like

```toml
newsfeed_file = "atom.xml"
```
(I wouldn't use the term "rss", as it actually names a file format, which might not be used)

**Comment by Keats** [comment]
That's going to be the default for the next version actually, including the term rss -> feed.

**Comment by Keats** [comment]
Closing as this is already implemented in next.
