### ISSUE TITLE
Function 'get_section' not found

### ISSUE THREAD

**Issue by DusterTheFirst** [getzola/zola#1017]
# Bug Report

## Environment

Zola version: zola 0.10.1
OS: Microsoft Windows 10 Pro (10.0.18363 Build 18363)

## Expected Behavior
The page will build and the towns short code should generate a list of links to the town pages under that section

## Current Behavior
(File path truncated)
```
$ zola serve
Building site...
Error: Failed to render content of .\content\towns\_index.md
Reason: Failed to render towns shortcode
Reason: Failed to render 'shortcodes/towns.html'
Reason: Function 'get_section' not found
```

## Step to reproduce
`shortcodes/towns.md`
```html
{% set section = get_section(path="towns/_index.md", metadata_only=true) %} #}
{#{% for town in section.pages %}
<a href="{{ town.permalink }}" class="town-link">{{ town.title }}</a>
{% endfor %}
```

`.\content\towns\_index.md`
```md
+++
title = "Towns"
+++

# Towns In the program
{{ towns() }}

# Add your town
Iusto qui aliquam asperiores. Praesentium necessitatibus autem eaque illo quo quos voluptatem commodi. Dignissimos corporis repellat aperiam rerum amet. Qui et vel omnis accusamus omnis dolore. Voluptas qui inventore excepturi excepturi.

Aut voluptas nam rerum voluptatem sed a vitae. Quia amet esse soluta eveniet facilis. Illo voluptatem impedit tempore officia aut nam asperiores. Distinctio fugit consectetur sunt consequatur aut. Animi delectus cupiditate consequuntur voluptatem voluptas tenetur accusantium. Qui earum ut aperiam inventore aut dolorum eos quo.
```

`.\content\towns\wellesley.md` (should show up in the shortcode list that gets generated)
```md
+++
title = "Wellesley"
+++

## About us

## Order

## Volunteer
```

**Comment by Keats** [comment]
Remove the `library.` in front of it

**Comment by DusterTheFirst** [comment]
@Keats The issue persists without the library part. I had just put that there in hopes it would fix the problem

**Comment by Keats** [comment]
Ah sorry, I didn't notice it was in a shortcode. Shortcodes don't have access to the site data currently, including all the Tera functions.

**Comment by DusterTheFirst** [comment]
It was working at one point as a shortcode.

**Comment by DusterTheFirst** [comment]
@Keats 

Would there be any way for me to replicate the behavior of 
![image](https://user-images.githubusercontent.com/14093962/80815247-44e0db00-8b9b-11ea-9a1a-ea410bc7b981.png)
without using shortcodes so that I can have access to the **get_section** method?

EDIT: If the zola serve is already running, and I create a shortcode, that shortcode then has access to the **get_section** method. Below is an image of its output.
![image](https://user-images.githubusercontent.com/14093962/80815934-89b94180-8b9c-11ea-8b07-6a01f7bf2885.png)
This is the content of the towns shortcode
![image](https://user-images.githubusercontent.com/14093962/80816017-bbcaa380-8b9c-11ea-9ecd-243f369a41bc.png)

**Comment by Keats** [comment]
Yeah, that's because zola serve is not cleaning itself properly...
In practice, get_section is populated after rendering the content so it makes sense it's not available in a shortcode since we don't have the data yet.
