### ISSUE TITLE
extracted tags listing

### ISSUE THREAD

**Issue by ghost** [getzola/zola#1020]
Using zola 0.10.1, is there a canonical way to achieve this, specifically the list of tags on the blog page instead of only via a tags page?

```
cat templates/blog.html 
{% extends "index.html" %}

{% block description %}/b - nikita's web log{% endblock description %}

{% block content %}
{% if config.generate_rss %}
<a title="blog (rss)" href="{{ get_url(path='rss.xml') | safe }}">
  <i class="fas fa-rss"></i>
  <span class="description">blog (rss)</span>
</a>
{% endif %}

{% for name, permalink in TaxonomyTerm %}
<a href="{{ TaxonomyTerm.permalink | safe }}">{{ TaxonomyTerm.name }}</a>
{% endfor %}

<section>
  <header>
    <h1>All posts</h1>
  </header>
  {% for year, posts in section.pages | group_by(attribute="year") %}
  <h2>{{ year }}</h2>
  <ul>
    {% for post in posts %}
    <li><small><time datetime="{{ post.date }}">{{ post.date }}</time></small>: <a href="{{ post.permalink }}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>
  {% endfor %}
</section>

{% endblock content %}
```

**Comment by Keats** [comment]
You can iterate on the taxonomies from the config and call https://www.getzola.org/documentation/templates/overview/#get-taxonomy

**Comment by ghost** [comment]
I have trouble processing this coming from jinja2 and this not-completely jinja2 like templating.

I assume this would return an array with "tags", accessible as "categories" as array name?
```{% set categories = get_taxonomy(kind="tags") %}```
and I would just use the available elements of TaxonomyTerm in the loop, so categories.name would return the names?

**Comment by Keats** [comment]
I really need to update the docs it's missing a lot of things :(
`{% set categories = get_taxonomy(kind="tags") %}` will return an object with a `kind` variable with the following attributes: name, paginate_by, paginate_path, lang, feed as well as a `items` variable that is a list of objects with attributes `name`, `slug`, `permalink` and `pages`

**Comment by codeandmedia** [comment]
sorry for bothering you, but I still don't understand how to get taxonomy list to section page? I've tried 
```
 {% set types_list = get_taxonomy(kind="types") %}
    {% for item in types_list.items %}
          {% if loop.last %}
          {{ item }}
            {% else %}
          {{ item }} | 
          {% endif %}
        {% endfor %}
```
But it's definitely wrong, I'm missing something

**Comment by Keats** [comment]
The update doc is at https://github.com/getzola/zola/blob/next/docs/content/documentation/templates/overview.md#get_taxonomy 
`item` in your for loop is an object
