### ISSUE TITLE
Neither paginator.pages nor section.pages contains any pages if less than paginate_by pages exist

### ISSUE THREAD

**Issue by repomaa** [getzola/zola#1021]
# Bug Report

Neither `paginator.pages` nor `section.pages` contains any pages if less than `paginate_by` pages exist.

## Environment

Zola version: 0.10.1

## Expected Behavior

`paginator.pages` should contain all pages.

## Current Behavior

`paginator.pages` as well as `section.pages` is empty. If `paginate_by` is removed from the section `_index.md` frontmatter, `section.pages` contains the pages.

## Step to reproduce

1. Create a section with `paginate_by = 10` in the frontmatter
2. Add a page to the section: `<section>/<slug>/index.md`
3. Create a section.html template and add `{{ __tera_context }}`
4. Go to the path `/<section>`
5. See if you can find your page in the context.

**Comment by Keats** [comment]
I can't seem to reproduce it?

**Comment by Keats** [comment]
@repomaa do you have a small repository reproducing the issue?

**Comment by Keats** [comment]
Cannot reproduce.
