### ISSUE TITLE
zola fails to build when sass-rs can not find git executable in sandboxed builds

### ISSUE THREAD

**Issue by ghost** [getzola/zola#1027]
Maybe this is redundant, but the latest zola fails to build because of https://github.com/compass-rs/sass-rs/issues/69

More in the sass-rs issue, the failure log (short): https://ftp.netbsd.org/pub/pkgsrc/misc/joerg/20200514.0240/zola-0.10.1/build.log

**Comment by Keats** [comment]
That's fixed in sass-rs
