### ISSUE TITLE
Zola can't deal with custom templates and root_dir argument

### ISSUE THREAD

**Issue by satakuma** [getzola/zola#1028]
# Bug Report

Zola fails to find custom templates while building with custom `root_dir` parameter other than the current working directory. 

## Environment

Zola version: 0.10.1

## Step to reproduce

 - In `testsite/content/_index.md` put:
```
+++
template = "custom.html"
+++
```
 - Create the corresponding template file, for example `touch testsite/templates/custom.md`
 - Run `zola -r testsite build`
It outputs:
```
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
Failed to build the site
Error: Failed to render section 'testsite/content/_index.md'
Reason: Tried to render `custom.html` but the template wasn't found
```
It works perfectly fine when you call zola from `testsite` directory

**Comment by southerntofu** [comment]
Investigating this bug i realized the root CLI argument does not work with relative paths, resulting in this error. But using an absolute path works and uses the custom template as expected.

Calling from either the content folder with `-r ..` or from the parent folder with `-r testsite` produced the error. Adding a trailing slash does not seem to change anything. The watchers for serve command also expect a path relative to the current working directory and fail when calling from another folder.

**Comment by Keats** [comment]
@tmkk can you try the `next` branch?

**Comment by satakuma** [comment]
Works fine now!
