### ISSUE TITLE
Bug with directory prefix and the get_url() and resize_image() functions

### ISSUE THREAD

**Issue by Infides** [getzola/zola#1035]
# Bug Report
First of all: Thank you for Zola!
The problem:
Generating a gallery with a shortcode and the get_url() and resize_image() functions runs into the following problem: The images are resized and shown, but opening the original file does not work, as the location is wrong.
I think it is related to #788 and also to #977 
The behavior of the different path parameters do not seem to be consistent, a unification would be great as suggested in #977.

## Environment
Zola version: 0.10.1

## Expected Behavior
The get_url() function should use the prefix-less file location in the "public" directory.

## Current Behavior
Directory structure:
```bash
└── content
    ├── photography
    │   └── 2020-02-08-Snow-pictures
    │         └── index.md
    │         └── 1.jpg
    │         └── 2.jpg
    │         └── 3.jpg
    │   └── 2020-04-10-Spring-pictures
    │         └── index.md
    │         └── 1.jpg
    │         └── 2.jpg
    │         └── 3.jpg

└── public
    ├── photography
    │   └── Snow-pictures
    │         └── index.md
    │         └── 1.jpg
    │         └── 2.jpg
    │         └── 3.jpg
    │   └── Spring-pictures
    │         └── index.md
    │         └── 1.jpg
    │         └── 2.jpg
    │         └── 3.jpg
```

Shortcode used:
```jinja2
<section class="infides-photo-gallery" role="photography gallery">
{% for asset in page.assets %}
    {%- if asset is matching("\d+.(jpg|png)$") -%}
    <a href="{{ get_url(path=asset) }}">
        <img class="infides-photo" src="{{ resize_image(path=asset, width=300, op="fit_width") }}">
    </a>
    {%- endif -%}
{% endfor %}
</section>
```

## Step to reproduce
I hope that the outline above already illustrates the problem. Otherwise I think I can provide a test case.

**Comment by Keats** [comment]
Should be fixed in 0.14
