### ISSUE TITLE
Add a function to consistently resolve link URLs in templates the same way as in markown

### ISSUE THREAD

**Issue by seritools** [getzola/zola#1037]
(Related to #977)

I'm working on a small shortcode snippet to have a custom `<img>` tag output, setting the image width/height and lazy loading:

```html
{% set imgpath = get_url(path=page.path ~ src) %}
{% set imginfo = get_image_metadata(path=page.relative_path ~ "/../" ~ src) %}
<img
    alt="{{ alt }}"
    src="{{ imgpath }}"
    width="{{ imginfo.width }}"
    height="{{ imginfo.height }}"
    {% if not eager %}loading="lazy"{% endif %}/>
```

It took me an awfully long time to find a way to get the image path for both the page and the `get_image_metadata` function.

It really seems like an ugly workaround (*especially* the local path) and only works properly for non-`@/` or static right now.

I would love to have a way of resolving a path the same way as a regular link/image in markdown does, maybe something like `resolve_link(href="image.png")` returning:

```js
{
    site_path: "blog/foobar/image.png",
    fs_path: "blog/2020-05-24-foobar/image.png",
}
```

**Comment by Keats** [comment]
Yeah I think #977 should be adressed in the next version because it's a bit confusing right now.

**Comment by Keats** [comment]
This should be done in 0.14
