### ISSUE TITLE
highlight-theme seems to be getting ignored

### ISSUE THREAD

**Issue by vsbabu** [getzola/zola#1043]
# Bug Report

## Environment

Zola version: 0.11.0
Theme: even
OS: Elementary OS 5.1.2
Installation medium: Linux brew

To revert, I just downloaded 0.10.1 linux binary from releases and uninstalled the brew version.

## Expected Behavior
highlight-theme variable should've painted pre>code with the right color scheme as mentioned in config.toml

## Current Behavior

`pre` tag has the right dark background, and code (from .main post code) has this light one, making it very ugly with a 5px dark padding provided by `pre`.  `code` section is getting a background that looks like solarized-light all the time. 

I had used base16-ocean-dark; then one-dark as my highlight-theme variable before.

I downgraded to 0.10.1 and regenerated the site and behaviour is fine with that version.

## Step to reproduce
- Specify any dark highlight theme in config.toml
- Add a sample code block in a page
- `zola serve` and observe. You see a thick dark border around the code block which is in solarized light scheme

**Comment by Keats** [comment]
That's an issue with the even theme, not Zola.
