### ISSUE TITLE
undocumented breaking change in 0.11.0

### ISSUE THREAD

**Issue by bdjnk** [getzola/zola#1047]
# Documentation issue

## Summary
PR #1026 (commit 32ca1a14ed734f11fc3889b41704605d64d65c5c) is a breaking change in 0.11.0 yet it isn't mentioned in the changelog at all nor otherwise documented.

## Proposed solution
Document this change properly. Ensure any future change which alters the generated html is listed as breaking and documented appropriately.

**Comment by Keats** [comment]
Missed that one sorry :(

**Comment by bdjnk** [comment]
Sorry to continue this, but you committed against `next` instead of `master` and forgot an ending backtick. I created a PR against master if that's helpful. #1049

**Comment by Keats** [comment]
Sorry :(
