### ISSUE TITLE
Date objects from nested [extra] objects should be usable as dates from the templates

### ISSUE THREAD

**Issue by fstephany** [getzola/zola#1048]
## Environment

Zola version: 0.10.1 (Fedora 32)

## Expected Behavior

Date objects from nested `[extra]` objects should be usable as date in the template.

## Current Behavior

If we set the following extra data on a section:
```
[extra]
date_example = 2020-05-04
[[extra.questions]]
date = 2020-05-03 
name = "Who is the prime minister of Uganda?"
```

We get the following object in the template context:

```
"extra": {
    "date_example": "2020-05-04",
    "questions": [
        {
            "date": {
                "$__toml_private_datetime": "2020-05-03"
            },
            "name": "Who is the prime minister of Uganda?"
        }
    ]
}
```

We can see the that the nested `date` was passed as a TOML datetime to the template. Unfortunately, that means we cannot use the `date` filter on it. The top level `date_example` is fine though (thanks to #238 ?)

An easy workaround is to simply set the `date` field as a string (i.e., `date = "2020-05-03"`) so the template can easily parse the date string.

**Comment by Keats** [comment]
Hmm I thought I fixed that already ages ago ;(
It's due to the serialization of datetime from TOML, maybe my fix doesn't recurse enough or only cares about the top level fields?

Maybe there is a better solution now than my big hack though...

**Comment by fstephany** [comment]
I didn't dig into #238 enough but I can have a look.
To be honest, it's not that annoying (the workaround is pretty straightforward). This issue is intended for future possible users having the same issue.

**Comment by Keats** [comment]
That's fixed in `next`, I was not checking arrays in extra when fixing up the dates.

**Comment by fstephany** [comment]
Thanks!
