### ISSUE TITLE
Binary size exploded between 0.10.1 and 0.11.0

### ISSUE THREAD

**Issue by linkmauve** [getzola/zola#1061]
# Bug Report

## Environment

Zola version: 0.11.0

## Expected Behaviour
The `zola` binary should have stayed around ~16 MiB in size once `strip`ped, maybe increasing a bit or decreasing a bit.

## Current Behaviour
Instead it went up to 91 MiB, which is way heavier than it should be given the changelog.

## Step to reproduce
- Build 0.10.1
- Build 0.11.0
- Compare their binary size.

[cargo-bloat](https://crates.io/crates/cargo-bloat) could possibly help you figure what additional data is being put in the binary, or maybe a review of your dependencies.

Other than that, thanks for Zola, I just started using it and it looks super nice!

**Comment by Keats** [comment]
I think the build might have picked up some sub repos for the syntaxes :/
Sadly cargo-diet doesn't work here so it will have to be done by hand I think

**Comment by Keats** [comment]
Looks like the issue was the search engine for Japanese and/or Chinese?

**Comment by Keats** [comment]
That's fixed in the next branch, closing for now.
