### ISSUE TITLE
Can't build lindera-ipadic, zola build fails.

### ISSUE THREAD

**Issue by ncoleman** [getzola/zola#1062]
# Bug Report
Trying to build zola with `cargo build --release`, build fails at roughly step 340 with:
     `memory allocation of 805306368 bytes failed`
     `error: could not compile lindera-ipadic`.

Raspberry Pi 4B  4GB memory, debian.
Zola version:  Current git at 14 June 20

I have tried to give it more contiguous memory by rebooting and trying again with a fresh system and no user apps running.  Even then, the system apparently can't give it 800MB (!) of presumably contiguous memory.  `free -mh` shows 2.7GB free, but not contiguous, I imagine.

From googling, this is a Japanese dictionary.  I don't need translation ability, can I disable it for the build?

**Comment by Keats** [comment]
The issue is with the search index loading all languages, including support for japanese. We can disable it but thats likely a bug in https://github.com/lindera-morphology/lindera, can you report it? The build.rs seems to only download a 11MB dictionary + ungzip it, nowhere near 800MB

**Comment by ncoleman** [comment]
I'll move it upstream. Thanks for the reply.

**Comment by Keats** [comment]
(I've disabled jp for now on next since it was also blowing up the binary size)

**Comment by ncoleman** [comment]
I'm happy to report that `next` builds successfully on a 4GB Raspberry Pi 4B.  The build took 36 minutes, time spent reading the docs. Thanks.

**Comment by ncoleman** [comment]
Upstream have reported back that the dictionary build consumes a lot of memory.  They are about to alter their process so that the dictionary is pre-built and downloaded complete as part of `lindera-ipadic`.  This would solve my issue.

[Upstream comment](https://github.com/lindera-morphology/lindera/issues/62#issuecomment-645399850)

**Comment by protoCall7** [comment]
Hi @Keats 

I'm in the middle of updating the OpenBSD package to Zola 0.11.0, and wanted to let you know that I've had to pick up a patch to turn off JP support, as was done in `next`.

I set the same list of languages in `components/search/Cargo.toml`, then did a `cargo update` to generate a fresh `Cargo.lock`.

Does this work for you, or do you have another suggestion for a workaround before I submit the diff to the Porters list?

**Comment by Keats** [comment]
I think that works.
