### ISSUE TITLE
Included content on homepage is not rebuilt on change

### ISSUE THREAD

**Issue by aslowwriter** [getzola/zola#1064]
# Bug Report
When changing content on a file in the `content` folder, the direct page that contains the content is rebuilt but pages that indirectly include it don't. 

A concrete example: Imagine I have a blog and the home page is just a pagination of those posts with a title and a short summary. If I change the content of a blog post (e.g. fix a typo), the page of the post is rebuilt but the home-page is not. 

This is especially relevant if you like building websites using partials (like me). For example, for modularity, my home page is built using several {% include "partial.html" %} that pull in their own content, and every time I modify that content I have to kill `zola serve` and restart it, which is extremely annoying. 

## Environment
Zola version: 0.10.1
Local forlder: a fresh `zola init` folder
Theme: Any (I tested it with `zola-pickle`)

## Expected Behavior
Pages that include content should be rebuilt when content is changed. This is especially 

## Current Behavior
Pages that indirectly include content either through using an {% include %} block or other variables are not rebuilt

## Step to reproduce
- use `zola init` to make a new website
- install a theme (I used `zola-pickle`)
- create a content file that get's included in the homepage
- run `zola serve`
- change something in the content file that get's included
- observe that the home page is not updated. 

## final suggestions
I get that tracing these kinds of dependencies could be tricky given that you could pull in content from any page with e.g. `get_section` or something similar. Personally I think this problem would also be solved by adding a cli option to rebuild zola from scratch every time, which given the performance of zola and the scale of the projects people seem to be using it for, imo would be an acceptable solution, even if it's less elegant.

**Comment by Keats** [comment]
> Personally I think this problem would also be solved by adding a cli option to rebuild zola from scratch every time, which given the performance of zola and the scale of the projects people seem to be using it for, imo would be an acceptable solution, even if it's less elegant.

That's the plan: https://zola.discourse.group/t/virtual-file-system/415/3 which hopefully would work without needless IO but I don't have time right now to work on it. If this works, the whole `rebuild` component will be removed and we can just have a fast mode that re-renders ONLY the page/section that changed.
