### ISSUE TITLE
generate_feed vs generate_rss

### ISSUE THREAD

**Issue by 2mol** [getzola/zola#1067]
# Bug Report

## Environment

Zola version: from 0.9  to 0.10.1

## Expected Behavior

Following [https://www.getzola.org/documentation/templates/feeds/](https://www.getzola.org/documentation/templates/feeds/)

I set generate_feed to true in my config.toml. I expected to find an atom.xml at the root of my domain, however I was unable to get this to work.

## Current Behavior

No atom.xml is generated.

On the other hand, `generate_rss = true` seems to work without any problem, and all the sites I could find out in the wild also only had `generate_rss`.

## Step to reproduce

Clone my site and try building it with `generate_feed = true`. You can find the repo here: https://github.com/2mol/juricho.me

**Comment by Keats** [comment]
The documentation is not versioned and is always for the current version, 0.11, where there is only `generate_feed`
