### ISSUE TITLE
Unable to build a website with syntax highlighting enabled

### ISSUE THREAD

**Issue by zaiste** [getzola/zola#1068]
# Bug Report

## Environment

Zola version: `0.11.0`

## Expected Behavior

Generated pages have syntax highlighting

## Current Behavior

Zola compilation «doesn't» finish (in a reasonable time). Without syntax highlighting it takes around 500ms, with syntax highlighting enabled I've waited as long as 30 seconds, but the Zola process was still running. I had to stop it because the computer got loud, very hot with all the cores maxed out at 100%.

## Step to reproduce

Here's my website: https://github.com/zaiste/zaiste.net/
I run `zola serve`

**Comment by Keats** [comment]
It's probably a bad case for a regex in syntect. Which languages are you highlighting in the blog? I'll have a look later if I can isolate to a specific language

**Comment by zaiste** [comment]
@Keats Thanks for fast reply. There is probably more than 10 different languages. My websites is partly a wiki with my personal notes. 

I will try to isolate a specific case. Please, don't waste your time on it - this is a (very) low importance.

**Comment by zaiste** [comment]
@Keats I've checked each language separately and they work in isolation. It seems this may be related to a large number of snippets on my website. I've left `zola serve` for few minutes, but it didn't finish

**Comment by zaiste** [comment]
@Keats I found it! These 3 snippets make Zola struggle. But I don't see any commonalities. Would you be able to identify the cause ?

### Snippet 1
```js
function isClass(func) {
  return typeof func === 'function'
    && /^class\s/.test(Function.prototype.toString.call(func));
}
```

### Snippet 2

```js
sq.return({ authorId: 'a.id', name: 'a.last_name' })
  .distinct
  .from({ b: 'book' })
  .leftJoin({ a: 'author' }).on`b.author_id = a.id`
  .where({ title: 'Oathbringer',  genre: 'fantasy' })
  .query
```

### Snippet 3

```js
import { Selector } from 'testcafe';

fixture `My first test`
  .page `http://github.com/`;

test('Find "testcafe" repository on GitHub', async t => {
  await t
    .typeText('form[action="/search"] input[name="q"]', 'testcafe' )
    .pressKey('enter')
    .expect(Selector('.repo-list > li > div').innerText).eql('DevExpress/testcafe');
});
```

**Comment by Keats** [comment]
It's all JS x)
Can you try using `tsx` as code language? Maybe it's the JS syntax that has some issues. The TS highlighting should be the same but uses a completely different syntax file.

**Comment by zaiste** [comment]
@Keats It works with `ts` instead of `js`! :) Thanks for the tip
