### ISSUE TITLE
Themes support

### ISSUE THREAD

**Issue by Keats** [getzola/zola#107]
Superseding #91 as a general theme discussion for Gutenberg.

A few questions for theme users since I'm not one:

- Which themes do you like/use the most? I'm planning on porting a few from Hugo/Pelican etc
- How do you use themes? git clone? git submodules? unzip a folder?
- Do you ever want to update the original theme or do you use customize the themes so much it's not really possible?

**Comment by booyaa** [comment]
I take it Hugo's themes are very go html/template centric? If not, could you utilise their theme system like you did with the sublime themes for the syntax highlighting (that was a stroke of genius btw)?

**Comment by Keats** [comment]
It should be easy enough to port most of the themes from hugo, it took me about 10min to port my own site. Hugo has a separate themes directory though so I would need to be able to merge templates/static from another directory.

> you did with the sublime themes for the syntax highlighting (that was a stroke of genius btw)

That's [syntect](https://github.com/trishume/syntect), not me! Cobalt uses it as well but in a more limited fashion.

**Comment by Keats** [comment]
One command that would be nice to add is something like `gutenberg dummy-serve` that will create a fake site and serve it to help with template development. Not sure it's worth the effort though.

**Comment by Keats** [comment]
Example for other static site generators:

- http://docs.getpelican.com/en/3.6.3/pelican-themes.html
- Hugo: git clone into a themes folder
- Hexo: same as Hugo

I guess the tricky part for Gutenberg is how to watch files in a themes folder and load the right templates

**Comment by Keats** [comment]
#114 is working and the first theme is available at https://github.com/Keats/hyde

**Comment by booyaa** [comment]
schweet! will give it a go!
