### ISSUE TITLE
Footnotes do not render correctly

### ISSUE THREAD

**Issue by shumvgolove** [getzola/zola#1070]
`Zola version: 0.11.0`
## Current Behavior
Write in markdown something like this:
```md
Some footnote.[^1]

[^1]: Hello there.
```
After building the site (for example, terminimal), Zola renders `footnote-definition` in the same place as `footnote-reference`:

![1](https://user-images.githubusercontent.com/37271604/86171899-2a3ccb00-bb26-11ea-910d-62a14dbf1b4e.PNG)

Besides that:
1. In `footnote-definition` only `Hello there.` text wrapped into `<p>` so the whole footnote appears broken. 
2. `footnote-reference` doesn't wrapped into `<div>` and doesn't contain something like `href="#1ref`, so there is no way to return to `footnote-reference` from `footnote-definition`.

## Expected Behavior

Ideally, as the name implies, footnote `<div class="footnotes">` should be rendered at the bottom of the page (like Hugo and Jekyll do) and shouldn't be buggy :^)

Here is the modified, correct structure:

![2](https://user-images.githubusercontent.com/37271604/86176251-5a3b9c80-bb2d-11ea-8b6b-5597d401213b.png)

Which renders like this:

![3](https://user-images.githubusercontent.com/37271604/86176771-244ae800-bb2e-11ea-9939-3fdbca1716b6.png)
and works as expected.

**Comment by shumvgolove** [comment]
After further investigation, it appears like [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark) limitation:
- [pulldown-cmark#116](https://github.com/raphlinus/pulldown-cmark/issues/116)
- [pulldown-cmark#142](https://github.com/raphlinus/pulldown-cmark/issues/142)

Should I close this issue?

**Comment by Keats** [comment]
Let's close this

**Comment by fuzzypixelz** [comment]
At the time of writing https://github.com/raphlinus/pulldown-cmark/issues/142 is still open.

Until then, for anyone coming across this, here's some hacky JavaScript to "fix" this.

```js
// The DOMContentLoaded event fires when the initial HTML
// document has been completely loaded and parsed, without
// waiting for stylesheets, images, and subframes to finish loading.
document.addEventListener('DOMContentLoaded', (_event) => {
  const references = document.getElementsByClassName('footnote-reference')
  // For each footnote reference, set an id so we can refer to it from the definition.
  // If the definition had an id of 'some_id', then the reference has id `some_id_ref`.
  for (const reference of references) {
    const link = reference.firstChild
    const id = link.getAttribute('href').slice(1) // skip the '#'
    link.setAttribute('id', `${id}_ref`)
  }

  const footnotes = document.getElementsByClassName('footnote-definition')
  // For each footnote-definition, add an anchor element with an href to its corresponding reference.
  // The text used for the added anchor is 'Leftwards Arrow with Hook' (U+21A9).
  for (const footnote of footnotes) {
    const id = footnote.getAttribute('id')
    const backReference = document.createElement('a')
    backReference.setAttribute('href', `#${id}_ref`)
    backReference.textContent = '↩'
    footnote.append(backReference)
  }
});

```

You can put it in your `static` folder. Enjoy.

**Comment by acro5piano** [comment]
@fuzzypixelz Thank you. Your solution works like a charm.

**Comment by van-sprundel** [comment]
Wow, it's been 3 years and this issue is still open

**Comment by piegamesde** [comment]
For those who only want to fix the `<p>` looking wrong without requiring JavaScript (this won't fix the missing backlinks):

```css
.footnote-definition p {
  display: unset;
}
```
