### ISSUE TITLE
Variable `section.title` not found in context while rendering 'blog-page.html'

### ISSUE THREAD

**Issue by quanwenbo** [getzola/zola#1071]
# Bug Report

Error: Failed to render page 'C:/Users\bob\RUST\blog\content\blog\second.md'
Reason: Failed to render 'blog-page.html'
Reason: Variable `section.title` not found in context while rendering 'blog-page.html'
## Environment

Zola version:

## Expected Behavior
Tell us what should have happened.

Here is the blog-page.html --------------->
![111](https://user-images.githubusercontent.com/29365317/86503411-87fc3c00-bde0-11ea-845c-6d9c7fd44b81.png)

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  {{section.title}}
</h1>
<ul>
  {% for page in section.pages %}
  <li><a href="{{ page.permalink | safe }}">{{ page.title }}</a></li>
  {% endfor %}
</ul>
{% endblock content %}

## Current Behavior
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.

## Step to reproduce
Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.

**Comment by Keats** [comment]
This is a page template right? Then there is no `section` variable.
