### ISSUE TITLE
Make PAGE_RE (at least start/end tokens) configurable

### ISSUE THREAD

**Issue by koitsu** [getzola/zola#1072]
# Feature Request

## Environment

Zola version: 0.11.0

## Details

I'd like to propose that `PAGE_RE` -- particularly the start and end tokens (currently regexes `\+\+\+`) -- be configurable.  Code: https://github.com/getzola/zola/blob/47bd7c9e8250e227237aa3600efd02511aa54611/components/front_matter/src/lib.rs#L14-L17

This would allow a person to move to/from Zola a lot easier, without necessarily having to rewrite all their `.md` files.  

Most static site generators support some form of front matter/"metadata" block for configuring things (blog title, dates, etc.), but with Markdown most use `<!--` and `-->`.  Editors like vim expect this as well, and do proper syntax highlighting based on that.  None, to my knowledge, understand `+++`.

I propose something like this in `config.toml` as an alternate example.  I don't care what the variables are named:

```
# Start and end markers for the front matter portions of pages and content files.
# These are regular expressions, and as such must be single-quoted, not double.
# Default:
# frontmatter_start = '\+\+\+'
# frontmatter_end = '\+\+\+'
# Alternate:
# frontmatter_start = '<!--'
# frontmatter_end = '-->'
```

Thanks.

P.S. -- Purely for learning purposes: I'd like to know why `+++` was chosen as the start/end delimiter to begin with.  The only time I have seen this sequence of characters used was on Hayes-compatible modems in the 80s and 90s, requiring padding (delays) between each character, ex. `+++ATH0`.

**Comment by Keats** [comment]
`+++` comes from Hugo where the type of characters define the language used in the front-matter: https://gohugo.io/content-management/front-matter/
Jekyll uses `---` with YAML inside, which also works in Hugo. 

I would like to keep that option open and not make the separators configurable.

**Comment by koitsu** [comment]
I think that's fair.  How would you feel about this as a compromise?  I can submit a PR if asked.

```diff
diff --git a/components/front_matter/src/lib.rs b/components/front_matter/src/lib.rs
index 83f2447..897f95b 100644
--- a/components/front_matter/src/lib.rs
+++ b/components/front_matter/src/lib.rs
@@ -13,7 +13,7 @@ pub use section::SectionFrontMatter;

 lazy_static! {
     static ref PAGE_RE: Regex =
-        Regex::new(r"^[[:space:]]*\+\+\+\r?\n((?s).*?(?-s))\+\+\+\r?\n?((?s).*(?-s))$").unwrap();
+        Regex::new(r"^[[:space:]]*(?:\+\+\+|---)\r?\n((?s).*?(?-s))(?:\+\+\+|---)\r?\n?((?s).*(?-s))$").unwrap();
 }

 #[derive(Debug, Copy, Clone, PartialEq, Serialize, Deserialize)]
```

**Comment by Keats** [comment]
That would become a breaking change should we decide to add YAML support in the front-matter :/

**Comment by koitsu** [comment]
Support for YAML frontmatter was added in 4754cb5792a8864f5d808b71b9c43aee51343536 / #990 so I'm closing this.
