### ISSUE TITLE
Zola not seeing/loading shortcode?

### ISSUE THREAD

**Issue by Merovex** [getzola/zola#1074]
# Bug Report

Really not sure if this is a bug report or a documentation error. BLUF: I have a shortcode that Zola appears not to find, so it is giving me a function not found error.

## Environment

Zola version: 0.11.0 (via Brew)

## Expected Behavior

I think I added a shortcode to the `templates/shortcode` directory `merovex-zola/templates/shortcodes/book_item.html` (See https://github.com/Merovex/merovex-zola) In the example below, there are four books, so I expect it to iterate four times and render `book_item`.

```
    {% set bookshelf = get_section(path="books/_index.md") %}
    {%- for book in bookshelf.pages %}
      {{ book_item(book=book) }}
    {%- endfor %}
```

## Current Behavior

```
zola serve
Building site...
-> Creating 44 pages (0 orphan), 3 sections, and processing 0 images
Error: Failed to render section '/.../content/_index.md'
Reason: Failed to render 'merovex-zola/templates/index.html'
Reason: Function 'book_item' not found
```

## Step to reproduce

I am exploring moving from Jekyll to Zola, so this is a [separate branch](https://github.com/Merovex/merovex.github.io/tree/zola)

Problem exists whether the shortcode is called "book_item" or "bookitem"

**Comment by Keats** [comment]
Shortcodes are meant to be used in markdown files, you are looking for Tera macros: https://tera.netlify.app/docs/#macros

**Comment by Merovex** [comment]
Then there ps a problem with the documentation. I'm not using it as a macro, or in a macro. I am trying to do the equivalent of a Jekyll Include. Did you look at my repo to see what I'm talking about? And, why close this prematurely?

**Comment by Merovex** [comment]
Ah, I get it now. Shortcode in Markdown, Macro in HTML.

Well, fix the documentation because that is not obvious unless you are fluent in Zola.

**Comment by Keats** [comment]
What is missing in https://www.getzola.org/documentation/content/shortcodes/ ?
