### ISSUE TITLE
zola build freezes when some react JS code is used in a codeblock

### ISSUE THREAD

**Issue by urbanslug** [getzola/zola#1075]
# Bug Report
The below code block when used in a blog post causes `zola serve` to freeze at **Building site...**. 

## Environment
Mac OS

Zola version: 0.11.0

## Expected Behavior
zola serve should have successfully built the site.

## Current Behavior
`zola serve` freezes on **Building site...**

## Step to reproduce
1. Copy the below code block into a blog post
2. Run `zola serve`

```js
function Tild({children}) {
  const tiltRef = React.useRef();
  
  /*
    This code runs after react has updated the DOM
    Interacting with the DOM is impure so we use a useRef hook
   */
  React.useEffect(() => {
   console.log(tiltRef.current)
   // tiltNode is our DOM node with class name my-class
   tiltNode = tiltRef.current
   
   // We may need to clean up our DOM node.
   // Ran when the component is unmounted from the page
   return () => {
     tiltNode.vanillaTilt.destroy()
   }
  }, []); // the empty dependency array makes us not run useEffect between re-renders.
  
  return (
    <div ref={tiltRef} className="my-class">
    ...
    </div>
  )
}
```

**Comment by Keats** [comment]
It looks like it's an issue in the JS syntax or syntect. Use `ts` as language in the code fence for now, it will work.

**Comment by urbanslug** [comment]
Okay I see, thanks for that.
It took me a while to figure out what the problem was because zola serve was failing silently. 

So should this issue stay open?

**Comment by Keats** [comment]
I'll leave it for now to see if I can report it to people that know better than I do. What string are you using in the code fence (after the 3 backtics)? `js`?

**Comment by urbanslug** [comment]
Yes, `js`.

**Comment by bradyjoslin** [comment]
Ran into this today, as well.   Using `ts` worked, thanks for mentioning.
