### ISSUE TITLE
RSS feed options are not backwards-compatible

### ISSUE THREAD

**Issue by dreamer** [getzola/zola#1076]
# Bug Report

## Environment

Zola version: 0.11.0 and 0.10.1 (details in expected behaviour)

I am using Zola 0.10.1 installed via my package manager (Fedora 32) and deploy to GitHub pages using [shalzz/zola-deploy-action](https://github.com/shalzz/zola-deploy-action). I just noticed, that my RSS feed silently stopped working - the reason being that action upgraded to 0.11.0 while I still use 0.10.1.

I would expect, that Zola will either provide seamless upgrade experience or at least go through "deprecation" period before removing options from `config.toml` page.

*I know I could "solve" this problem via installing zola via cargo instead of my package manager… but it means I would need to install and keep zola up-to date manually on all machines I use AND force co-maintainers of the web page to do the same.*

Please note this bug will affect users who upgrade from zola 0.10.1 in Fedora 32 to zola 0.11.0 in Fedora 33.

## Expected Behavior

I have `generate_rss = true` in my config.toml.

In 0.10.1 it generates the feed as expected.

In 0.11.0 it should still generate the feed - perhaps loudly complaining about using a deprecated config option.

## Current Behavior

I can't keep using `generate_rss = true` because it won't work on deployment.

I can replace it with:
```
generate_feed = true
feed_filename = "rss.xml"
```
… but this does not work with 0.10.1, so I can't verify if my page is generating correctly offline before pushing to the repo. I would also need to instruct co-maintainers of my page to stop using older zola versions and force them to use cargo (which is suboptimal).

I tested:
```
generate_rss = true
generate_feed = true
feed_filename = "rss.xml"
```
But this makes 0.10.1 fail page compilation, so it's pointless.

Right now, the preferred solution for me would be… to stop using the feature altogether :(

*My real gripe in here is: I would prefer if feature-breaking config changes were going through the proper deprecation period, giving me and my co-maintainers a chance to adapt to the new solution.*

**Comment by dreamer** [comment]
Hmm, yesterday, I had a problem making zola 0.10.1 working correctly with following options in config file:
```
generate_feed = true
feed_filename = "rss.xml"
```
and that prompted me to create this bug report.

But today, when I started work on PR to support `generate_rss` as a deprecated fallback value - I can't reproduce this problem any more; I must've changed something different in my project since yesterday.

With new options, RSS feed works on deployment (with 0.11.0) and does not work locally (which is kind-of ok - as long as the site can be tested with zola serve).

Therefore I qualify this bug as a PEBKAC and am closing it down :)

**Comment by Keats** [comment]
> With new options, RSS feed works on deployment (with 0.11.0) and does not work locally (which is kind-of ok - as long as the site can be tested with zola serve).

What do you mean? It should work locally with 0.11 as well.

**Comment by dreamer** [comment]
Locally I have 0.10.1 installed (as this is the version distributed via Fedora repos) - that's the point, I don't want to install zola manually on all machines using cargo.

**Comment by Keats** [comment]
Ah I see. `zola` is not available on cargo and using your package manager is the recommended to install it.

Sadly I don't have the bandwidth to handle deprecations as each releases take months and there's usually no rush to upgrade even then (my personal site was on 0.9 until yesterday). I do mention breaking changes and how to upgrade in the CHANGELOG: https://github.com/getzola/zola/blob/master/CHANGELOG.md#0110-2020-05-25

https://github.com/shalzz/zola-deploy-action should probably get a ZOLA_VERSION parameter to control which version of Zola to download instead of hardcoding it in the Dockerifle.

**Comment by dreamer** [comment]
@Keats I think in this particular case handling of deprecated option would be quite easy, e.g. https://github.com/dreamer/zola/commit/b0505b2f78344b186e83299b005f5534670c3112

If you think solution like this would be acceptable, I can clean it up and send a PR.

**Comment by Keats** [comment]
The next release is not before a couple of months though, at this point I don't know if many people will still need that compatiblity.
