### ISSUE TITLE
Zola runs out of memory in a section configured with paginate_by = 0

### ISSUE THREAD

**Issue by mikolajpp** [getzola/zola#1080]
# Bug Report

`zola serve` on a specially crafted section (see below) causes zola to keep allocating memory until 
it is killed, or hangs the system. Below please use the `prlimit --as=2000000000 zola serve` to verify the bug, otherwise 
the tester runs the risk of system hang. 

## Environment
Linux

Zola version:
0.11.0

## Expected Behavior

Zola should not run out of memory

## Step to reproduce

1. Create new zola site with `zola init membug`
2. Create `_index.md` and `2020-06-30-bug.md` in the `content` folder
3. Fill the contents of the above file as follows

_index.md
```
+++
title = "Homepage"
paginate_by = 0
sort_by = "date"
insert_anchor_links = "right"
+++
```

2020-06-30-bug.md
```
+++
title = "BUG"
+++
```
4. Run zola serve with  `prlimit --as=2000000000 zola serve`.  Zola will keep allocating memory until it hits the limit set with `prlimit`.

The bug is 100% reproducible.

**Comment by Keats** [comment]
That's a bad bug, can anyone have a look? I'll be offline for some time

**Comment by justinturpin** [comment]
The offending line is https://github.com/getzola/zola/blob/master/components/site/src/sitemap.rs#L90 as there will be a division by zero error in this case, though I don't know what the logic should do, if someone could give me some help there.

**Comment by justinturpin** [comment]
I have a PR that gets builds working again here: https://github.com/getzola/zola/pull/1097
