### ISSUE TITLE
OpenBSD patch relevance?

### ISSUE THREAD

**Issue by ghost** [getzola/zola#1088]
I noticed OpenBSD has a couple patches for their package of Zola and I was curious if they were relevant to be properly included in the project? They might be something more Rust specific but I am not sure, and if so why they would be in the application package.

A link to them is [here](https://github.com/openbsd/ports/tree/master/www/zola/patches) for your review.

**Comment by Keats** [comment]
I think we're fine, those patches are not relevant for the latest version of the library. Thanks for the link!
