### ISSUE TITLE
Deployment guide for vercel.com a.k.a (zeit.co)

### ISSUE THREAD

**Issue by samyakb** [getzola/zola#1090]
# Documentation issue
There is no guide on how to deploy zola on [vercel](https://vercel.com).

## Proposed solution
So far I found this [diff](https://github.com/vercel/now-examples/commit/e27416679120b68696f0724d99956f6f067c0dbe#diff-b37f454416f67778deb180e93713718a) on vercel now-examples repo which as of now points to 404. So I checked commit diff and found this.
Aside of this diff I didn't found any documentation on how deploy zola to vercel.

**Comment by Keats** [comment]
I never used vercel so it would need to be contributed by someone.

**Comment by samyakb** [comment]
I managed to get it working on Vercel. I can do PR.
On which branch should I push documentation PR ? Contribution guide says that development is `next` branch.

**Comment by Keats** [comment]
Since it's documentation, you can do it on `master`
