### ISSUE TITLE
zola serve --watch-only ignores base_url

### ISSUE THREAD

**Issue by elbaro** [getzola/zola#1091]
# Bug Report

## Environment

Zola version: 0.11

## Expected Behavior
`zola serve --watch-only` same as `zola build`

## Current Behavior

```
zola serve --watch-only
```
generates the html files with 127.0.0.1 instead of base_url.

I have `zola serve --watch-only` + `nginx` and it serves broken htmls.

**Comment by elbaro** [comment]
Since `zola build` always builds the entire docs, I cannot use `watchexec + zola build [filename]`.

**Comment by Keats** [comment]
> zola serve --watch-only same as zola build

That's not a bug, the base_url is overriden in zola serve to ensure people cn use their site locally without issues. `zola serve` is starting a local webserver and needs interface/port. Try `zola serve --watch-only --base-url=https://my-url.com`

> Since zola build always builds the entire docs, I cannot use watchexec + zola build [filename].

It's too hard to know exactly what needs to be rebuilt given a filename (hence why half of the bug reports in that repo are about `zola serve` which attempts exactly that).
