### ISSUE TITLE
get_image_metadata doesn't work on resized image

### ISSUE THREAD

**Issue by shumvgolove** [getzola/zola#1099]
# Bug Report
This is continuation of [this thread](https://zola.discourse.group/t/how-to-get-image-metadata-of-resized-image/358).

## Environment

Zola version: 0.11.0

## Expected Behavior
Zola correctly sets resized image metadata.

## Current Behavior
Zola throws an error.

## Step to reproduce
Write in shortcode something like:
```
{% set resized_image = resize_image(path = page.path ~ image, width = 600, op = 'fit_width') %}
{% set resized_image_metadata = get_image_metadata(path = resized_image) %}
```
Then after executing `zola serve`:
```
Failed to build the site
Reason: Failed to render slider shortcode
Reason: Failed to render 'shortcodes/test.html'
Reason: `get_image_metadata`: Cannot find path: https://example.site/processed_images/838c932e793074ce00.jpg
```

**Comment by shumvgolove** [comment]
Also, is it possible to assign variable to width in `resize_image` function? Because doing so results in `Zola` infinitely processing the site.

**Comment by flother** [comment]
There's a solution to this if you know one dimension of the resized image. For example, because you know the width of the resized image (600px) you can calculate its height like this:

```jinja
{% set meta = get_image_metadata(path=asset) %}
{% set resized_width = 600 %}
{% set resized_height = meta.height * (resized_width / meta.width) %}
{% set resized_image = resize_image(path=asset, width=600, op="fit_width") %}
<img src="{{ resized_image }}" height="{{ resized_height|round }}" width="{{ resized_width }}">
```

The key is line 3 where we calculate the resized image's height, rescaling it by using the difference between the original image's width and the resized image's width.

**Comment by reivilibre** [comment]
As an adaptation of what flother said above (many thanks), this will give the dimensions if one is using `op="fit_height"`:

```tera
{% set orig_metadata = get_image_metadata(path=groot ~ "/" ~ photo.name) %}
{% set large_path = resize_image(path=groot ~ "/" ~ photo.name, op="fit_height", height=1200) %}
{% set large_height = 1200 %}
{% set large_width = orig_metadata.width * (large_height / orig_metadata.height) %}
{% set large_width = large_width | round %}

<meta itemprop="width" content="{{ large_width }}">
<meta itemprop="height" content="{{ large_height }}">
```

For reasons I don't understand (perhaps an oversight), `{% set large_width = (orig_metadata.width * (large_height / orig_metadata.height)) | round %}` is a syntactic error and `{% set large_width = orig_metadata.width * (large_height / orig_metadata.height) | round %}` seems to produce the wrong result — I think round is taking precedence over the multiplication.

**Comment by Keats** [comment]
We really need to make that better in an upcoming version.
As for the error with the `set`, it's likely a flaw in the Tera parser. I'm planning to rewrite it at some point to fix all the inconsistencies but I'm waiting on pest3 to do that.

**Comment by Keats** [comment]
It should work in 0.14
