### ISSUE TITLE
`date(format=)`-Filter is not localized

### ISSUE THREAD

**Issue by ibotty** [getzola/zola#1103]
Zola version: zola-0.10.1-1.fc32.x86_64

## Expected Behavior

in config.toml:
```
default_language = 'de'
```

```jinja
{{ "2020-07-27"  | date(format="%B") }}
```
is not localized:  It returns "July" and not "Juli".

I am certainly missing some setting to make it all work.

**Comment by Keats** [comment]
You're not missing anything, `chrono` - the underlying date library - is not localized and only supports English :/

**Comment by southerntofu** [comment]
@ibotty You can use the translation system to translate your dates.

[Personally](https://tildegit.org/southerntofu/zola-water/src/branch/master/templates/widgets.html#L100) i only "translate" the order for date numbers: 

```
{%- if page.date -%}<time class="dt-published" datetime="{{ page.date }}">📅&nbsp;{{ page.date | date(format=trans(key="dateFormat", lang=lang)) }}</time>{%- endif -%}
```

With `dateFormat = "%d/%m/%Y"` for french and `dateFormat = "%m/%d/%Y"` for english.

You could apply the same logic to translate month names. You can ask around on [the forum](https://zola.discourse.group/) if you're stuck and/or contribute [documentation](https://github.com/getzola/zola/blob/master/docs/content/documentation/content/multilingual.md) when you succeed.

Note: the translation system will undergo some major changes in a future release (#1040) so it's possible you may have to rework it slightly at some point

**Comment by ibotty** [comment]
@southerntofu, thank you for the workaround for date numbers.  That's the approach I used.  I certainly hope, that it's not decided to need month names before chronotope/chrono#453, the pull request to chrono to add locales, lands and is integrated in zola (if neccessary).

**Comment by cecton** [comment]
I did use [libc-strftime](https://crates.io/crates/libc-strftime) in the meanwhile. It's just strftime directly from the libc

**Comment by Keats** [comment]
So can something be done in Tera after that PR? I haven't followed/want to read the whole thread.

**Comment by cecton** [comment]
Ah yes it has been released for some time now. Just add the feature and don't forget to pass the `Locale`

**Comment by ZettaScript** [comment]
This issue can be closed now, unless it is about setting automatically the date locale to the website's default language? (which looks difficult and not really necessary)

**Comment by Keats** [comment]
Let's close it when the version of Zola containing it is released.

**Comment by sardemff7** [comment]
It seems that the expected `locale` parameters of Tera’s `date` filter takes a full locale specifier (e.g. `fr_FR`), so you cannot pass it `lang` directly. Would that make sense for Zola to directly provide a `locale` variable somehow?

**Comment by Keats** [comment]
It's kinda odd to have an automatic lang -> locale conversion but maybe it does not matter for dates? Anyone has some links on that?
