### ISSUE TITLE
doc: add macro in documentation

### ISSUE THREAD

**Issue by Grummfy** [getzola/zola#1104]
# Documentation issue

## Summary
When we see the doc about the shortcode, I immediately think to use it as some macro, but it's not the same. Because macro are often a solution (regarding the forum answers), why not explicitly explain it inside the zola documentation.

## Proposed solution
Add some example of macro and a link to https://tera.netlify.app/docs#macros

I know there is already a link inside the doc of shortcode to the macro, but it's too small.

thanks

**Comment by Keats** [comment]
I don't really want to duplicate doumentation if possible but the docs can be updated to be clearer
