### ISSUE TITLE
Markdown filter includes TOML head matter

### ISSUE THREAD

**Issue by tylershuster** [getzola/zola#1105]
# Documentation issue

## Summary
I have a page that needs to include another page's content. Thus I use `set content = load_data(path="")` and `{{ content | markdown }}`. It mostly works, except that the TOML head matter is also included.

## Proposed solution
I propose that the head matter is ignored in the markdown filter. If there is another way to achieve this please let me know.

**Comment by Keats** [comment]
Use `get_page` instead. Or is it in a shortcode?

**Comment by tylershuster** [comment]
It’s in a short code. It just needs to be programmatic 

T

**Comment by Keats** [comment]
You can split on `+++` then I guess?

**Comment by tylershuster** [comment]
Ok, I can manage that.
