### ISSUE TITLE
Your site was created in ...

### ISSUE THREAD

**Issue by musm** [getzola/zola#1110]
# Bug Report

`zola init`
`Done! Your site was created in "\\\\?\\C:\\Users\\Mus\\Code\\testwebsite"`

Would be nice to remove the UNC path prefix since it's unecessary.

**Comment by uggla** [comment]
Here it could be easy to fix the console message by stripping the `\\\\?\\`, but under the wood that's not a simple problem.
https://github.com/rust-lang/rust/issues/42869
@Keats, may I deal with this issue by removing `\\\\?\\` in the message ?
Something like this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=04667fa048e663affa3e162eb40b9628

**Comment by Keats** [comment]
I am not sure what's the best way to deal with it (I didn't know about UNC path prefix until this issue).
I think this is a fine change though, the corrected paths look like more Windows paths to me.

**Comment by musm** [comment]
@uggla  That doesn't seem like a good stop-gap, it seems like we just need to wait for https://github.com/rust-lang/rust/issues/42869

**Comment by Keats** [comment]
@musm are you saying https://github.com/getzola/zola/pull/1129 shouldn't be merged?

**Comment by musm** [comment]
Personally I don't find that an acceptable solution, it should be fixed by  the rust team in  e.g. https://github.com/rust-lang/rust/issues/42869 

I thought this was an issue with this library, but it looks like the rust team needs to provide canonicalization for Windows paths.
