### ISSUE TITLE
Error with index.md at root of site (content/)

### ISSUE THREAD

**Issue by Aescetic** [getzola/zola#1119]
# Bug Report

Hi, folks. This is a great project. When the bugs get ironed out, it will be a perfect diamond, I have no doubt about that.

First, some context... What I want is to have a "custom" front page. That is, at the root of my site, I want to place a page with stuff rendered from Markdown.

As I understand it, this is done by creating an `index.md` file directly under `content/` and proceeding as normal. The page is very simple, just:

```
+++
title = "Home"
+++


# A title

## A subtitle

Alpha bravo charlie delta echo foxtrot gulf hotel...
```

As expected, this page is rendered with the `index.html` template, so I attempt to override this by setting `template = "page.html"`, but this has no effect. Still, the root of the site is rendered with the `index.html` template.

Interestingly, if, *after* starting `zola serve`, I set `path = "/"`, everything works perfectly: the site root is rendered with the page template and is exactly what I want. But this is not the case if set *before* running either `zola serve` or `zola build`, in which case there is a fatal error which looks something like this:

```
Building site...
Failed to build the site
Error: Found path collisions:
- `/` from files ["index.md", "posts/one-of-the-posts.md"]
```

If Zola is compiled with lines 195 through 201 of `components/site/src/lib.rs` commented out, this collision check is skipped, and the build completes successfully, but `index.md` returns to being rendered with the `index.html` template, *not* the `page.html` template, as expected.

So perhaps this is two, or maybe even three bugs? There is the fact that the collision check is not run when `zola serve` rebuilds the page, the fact that the `template` parameter fails to set the template used, and the fact that `path = "/"` is ignored by `zola build`.

This is the situation as I understand it. If you have any questions, please ask.

## Environment

Zola version: `v0.11`, then `master`, then `next`

**Comment by Keats** [comment]
The homepage of a site is at `content/_index.md` as it is a section, not `content/index.md`. Note the `_` difference.

**Comment by Aescetic** [comment]
Okay, I see this in the documentation.

> A section is created whenever a directory (or subdirectory) in the `content` section contains an `_index.md` file. If a directory does not contain an `_index.md` file, no section will be created, but Markdown files within that directory will still create pages (known as orphan pages).
> 
> The index page (i.e., the page displayed when a user browses to your `base_url`) is a section, which is created whether or not you add an `_index.md` file at the root of your content directory. If you do not create an `_index.md` file in your content directory, this main content section will not have any content or metadata. If you would like to add content or metadata, you can add an `_index.md` file at the root of the `content` directory and edit it just as you would edit any other `_index.md` file; your `index.html` template will then have access to that content and metadata.

After moving the file from `index.md` to `_index.md`, the build fails with the following message:

```
Failed to build the site
Error: Failed to render section '/Users/me/Documents/dev/site/content/_index.md'
Reason: Failed to render 'page.html'
Reason: Variable `page` not found in context while rendering 'page.html'
```

I suppose that this is because, despite the `template` parameter, it is still considered a "section".

> After the closing `+++, you can add content, which will be parsed as Markdown and made available to your templates through the `section.content` variable.

What is the way to specify that you want the site root to be a page like any other page?

**Comment by Keats** [comment]
> I suppose that this is because, despite the template parameter, it is still considered a "section".

Yes

> What is the way to specify that you want the site root to be a page like any other page?

This is not possible but is not an issue in practice. If you don't put paginate_by on a section, a section and a page are almost the same.

**Comment by Aescetic** [comment]
Thanks, @Keats.

If any other of the seven-point-eight billion people out there are wanting to do the same as I was wanting to do, here is the workaround that is working for me and will likely work for you:

```
{% if section %}
    {% set page = section %}
{% endif %}
```

In your theme's page template, `page.html`, simply prepend this to the contents of your `content` block.

Obviously, this will be useful to you only if you are overriding `_index.md`'s template with `template = "page.html"`.

So it would be great if Zola supported this natively, by simply accepting an `index.md` at the root of `content/` and treating it as a page, but this is pretty good.

**Comment by Keats** [comment]
There is a similar discussion at https://zola.discourse.group/t/section-vs-page/522

> So it would be great if Zola supported this natively, by simply accepting an index.md at the root of content/ and treating it as a page, but this is pretty good.

That's not really possible due to the data model Zola uses. The homepage is essentially the root parent of all the sections and cannot be a page because of that. Many people also use it to order/paginate content and since it's already magic enough, I don't really want to add more.

**Comment by Aescetic** [comment]
Fair enough.
