### ISSUE TITLE
Variable `config.build_timestamp` not found in context while rendering 'index.html'

### ISSUE THREAD

**Issue by Darksonn** [getzola/zola#1130]
When attempting to test my proposed solution to [this][1], I ran into the following compile error when calling `zola build`. The error appears on the current master branch (commit 6238171), but not using `zola 0.11.0`.
```
Failed to build the site
Error: Failed to render section '/home/alice/src/ryhl.io/content/_index.md'
Reason: Failed to render 'index.html'
Reason: Variable `config.build_timestamp` not found in context while rendering 'index.html'
```
The code in question can be found [here][2].

[1]: https://zola.discourse.group/t/customize-syntax-highlighting/543
[2]: https://github.com/Darksonn/ryhl.io

**Comment by Keats** [comment]
Ah, I think `build_timestamp` might have been removed as it was only using for cachebusting (as you use it in your site) and there is a better solution now.
Use https://www.getzola.org/documentation/templates/overview/#get_url and you get robust cachebusting instead of the very naive timestamp approach.
Eg in https://github.com/Darksonn/ryhl.io/blob/master/templates/index.html#L14 , change it to `{{ get_url(path="style.css", cachebust=true) }}`

**Comment by felstormrage** [comment]
Hey sending the `cachebust=true` leads to build not compiling.

```
Failed to build the site
Error: Failed to render page '/home/nithin/Git/Blog/content/contact.md'
Reason: Failed to render 'plain.html' (error happened in a parent template)
Reason: Could not read file `styles/styles.css`. Expected location: /home/nithin/Git/Blog/content/styles/styles.css
```
The files exists in `static/styles/styles.css`
I guess it fails to colocate.

On the contrary setting the parameter to false or removing it, is working as expected and the build is passing successfully.

**Comment by Keats** [comment]
@rednithin you need to put https://github.com/rednithin/Blog/tree/master/styles in the `static` folder for the function to work

**Comment by felstormrage** [comment]
@Keats I run a node script to move the processed CSS into the static folder before invoking zola. The problem I told occurs once the CSS is processed and put inside the `static` folder.

**Comment by Darksonn** [comment]
Fixed by https://github.com/Darksonn/ryhl.io/pull/1
