### ISSUE TITLE
Adding a tag to a post while serving dynamically causes a failure

### ISSUE THREAD

**Issue by sinistersnare** [getzola/zola#1132]
# Bug Report

Hi,

while writing a post, if I add to a taxonomy, then the site refuses to render afterwards:

```
Failed to build the site
Error: Failed to render page 'H:\dev\blog\content/post\06-crates-io-will-not-be-fixed.md'
Reason: Failed to render 'sam/templates/page.html'
Reason: `get_taxonomy_url`: couldn't find `newtag` in `tags` taxonomy
Done in 53ms.
```

if i simply rerun `zola serve` then the site is happy to create the tag and render the site properly again.

## Environment

Zola version: `0.11.0`

## Expected Behavior

the site continues rendering without an issue, and the new tag is reflected in the page (or however the theme would use it).

## Current Behavior

A failure message comes and the site fails to render. If I remove the new tag then it renders properly again.

## Step to reproduce

1. Use sam Theme
2.  Make a new post, add
```
[taxonomies]
tags = ["tag0"]
```
to front matter.
3. `zola serve`, and look at the post
4. add another tag to the `tags` list. 
5. check console output for a failure message
6. Remove the new tag for the error message to disappear, or ctrl+c and rerun `zola serve` to generate the tag so it can be used.

**Comment by Keats** [comment]
That's going to be fixed in the next release! It should already be fixed in the `next` branch.
