### ISSUE TITLE
Checker panics if response is not utf-8

### ISSUE THREAD

**Issue by lightclient** [getzola/zola#1134]
# Bug Report

When running `zola check`, it panics if the external link does not return a `utf-8` encoded string due to the use of an `unwrap()`.

See the failure point here: https://github.com/getzola/zola/blob/261a2eee013112586092f728e5b41179a4a788ae/components/link_checker/src/lib.rs#L57

Zola version: 0.11.0

**Comment by Keats** [comment]
Thanks, it will be fixed in the next version

**Comment by lightclient** [comment]
Thank you!
