### ISSUE TITLE
Taxonomies with slug collision are not listed in taxonomy page

### ISSUE THREAD

**Issue by aslowwriter** [getzola/zola#1135]
# Bug Report

## Environment

Zola version: zola 0.10.1

## Expected Behavior
Taxonomy terms can be different but have the same slug/permalink. For example, the terms "test" and "Test" and "test " all have the same slug but are considered different in the current version and get their own pages. However, in the example above the taxonomy list pages for "Test" and "test " become unreachable since those URLs will redirect to the page for "test". I would expect pages with equal slugs/permalinks to get merged so the pages from both terms show up. 

## Current Behavior
As described above. 

## Step to reproduce
1. create a new website with `zola init`
2. add an `index.html` and `tags/list.html`
3. add the `tags` taxonomy to `config.toml` 
3. add two new content pages `content/first.md` and `content/second.md`
4. give `first.md` a tag of "test" and `second.md` a tag of "Test"
5. use `zola serve` and navigate to `127.0.0.1:1111/tags/test` 
6. observe that `second.md` is not listed

## Comment
As I see there are two solutions: create "test1" and "test2" taxonomy pages if there is a conflict, or simply merge them and show the pages of both "test" and "Test" on the same taxonomy page. Since the slugs of the two terms conflict, it is extremely likely that they were meant to be the same term so I think the second option is by far the best.  I have a fix that implements the second solution and has an added test for it in my own fork. I would be happy to submit a PR. It works by recording the slugified version of a term instead of the name when finding the taxonomies.

**Comment by Keats** [comment]
I think the second approach is fine, case sensitivity should not be considered when building the taxonomies.
