### ISSUE TITLE
minfying has unhelpful error messaging and breaks on html chars in inner text

### ISSUE THREAD

**Issue by aslowwriter** [getzola/zola#1152]
# Bug Report

## Environment

Zola version: 0.12.0 on `next` branch

## Expected Behavior
Tell us what should have happened.
I tried to build my own website with minification turned on. The website should get built and be minified. 

## Current Behavior
when I build my website with minification turned on I simply get this message: 
```
Error: Failed to truncate html at character: 15769
```
with no further information, making it impossible to tell what the problem is for the user. As I have my own version installed I did some extra digging and found the issue causing the crash for which I will open a separate issue, but this should be fixed in some way. At least I think the file currently being minified should be displayed, but ideally, a window around the error in the string currently being minified would also be shown. Displaying the entire string helps but is still very cumbersome as the files can be very large so displaying all of it is unhelpful. 

As for what is causing the exit, after doing some digging in my own installation I found out that it is because one of my pages containing the text `<<` (for nav buttons) so it seems that the inner HTML text is not properly escaped/encoded before it is minified. 

## Step to reproduce
```bash
mkdir bug && cd bug
zola init
sed -i  's/\[extra\]/minify_html = true \n [extra]/' config.toml # enable minification
echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html lang="en"> <head> <meta http-equiv="content-type" content="text/html; charset=utf-8"> <title>Title Goes Here</title> </head> <body> <p>This is my web page</p>
        <p> <<<<<<  </p><script src="/livereload.js?port=1024&amp;mindelay=10"></script></body> </html> 
' >> templates/index.html
zola serve
```

**Comment by Keats** [comment]
cc @augustinreille 
Since I want to do release maybe this week of Zola, I might disable minifying for the upcoming release while it's being ironed out.

**Comment by areille** [comment]
@Keats Sure

For better error messages we may have a look to [this function](https://docs.rs/minify-html/0.3.7/minify_html/fn.with_friendly_error.html).

Concerning the error with inner html chars, I opened [an issue](https://github.com/wilsonzlin/minify-html/issues/9).

**Comment by Keats** [comment]
Thanks @augustinreille 
Ideally minifying HTML should never produce an error and with many template inheritance/macros/markdown, good luck identifying exactly what's happening. I'll disable it anyway for the next release as it might not be production-ready yet and look at it again for 0.13

**Comment by areille** [comment]
`minify-html` v 0.3.8 has added support for inner html chars (see [this commit](https://github.com/wilsonzlin/minify-html/commit/9baa4c1a9ea42ffb24cac4b033dc72f6fa53087b))
However we still have to work on better error messages.

**Comment by Keats** [comment]
Let's close, I'll enable minify_html in 0.13 and we will get more feedback.
