### ISSUE TITLE
How to get url to taxonomies item?

### ISSUE THREAD

**Issue by anthonychwong** [getzola/zola#1167]
I am writing templates for a page and section which have some taxonomies, and for each taxonomy item, I want to render a link back to the list it's page listing all articles within same taxonomy item.

However, from the [page variables](https://www.getzola.org/documentation/templates/pages-sections/#page-variables), it seems don't have the link or path variable.
```
taxonomies: HashMap<String, Array<String>>;
```

Is there anyway to generate that link instead of hard-coding the taxonomies path everywhere?

**Comment by Keats** [comment]
You can use https://www.getzola.org/documentation/templates/overview/#get-taxonomy-url

**Comment by anthonychwong** [comment]
Thanks, this solved my problem.
