### ISSUE TITLE
0.12 regressions

### ISSUE THREAD

**Issue by Keats** [getzola/zola#1168]
- [x] zola serve issue: https://zola.discourse.group/t/zola-12-serv-slug-issue/595
- [x] continue reading issue: https://zola.discourse.group/t/zola-12-issue-with-continue-reading/590
- [x] RSS issue: https://zola.discourse.group/t/zola-12-rss-issues/588 (might be solved by the above)
- [x] #1172 
- [x] #1177 

Maybe for later:
- [ ] #1176

If anyone wants to pick one, please mention it before working on it.

**Comment by matthias-t** [comment]
This can be closed now, right? Thanks for the timely fixes, by the way.
