### ISSUE TITLE
New versions not on crates.io

### ISSUE THREAD

**Issue by saghm** [getzola/zola#117]
I just realized that several versions of this have come out without my noticing because I had been checking for updates on crates. Will any more current/future versions be released on crates.io, or is that no longer going to be supported?

**Comment by Keats** [comment]
New versions are not going to be released on crates.io for a few reasons (from my article at https://vincent.is/releasing-gutenberg-0.1.0/):

- package for binary crates don't use the Cargo.lock which means a dependency having breaking changes without respecting SemVer will cause the crate to compile but fail at runtime in some cases
- I moved to using a Cargo workspace with many small crates to improve iteration speed
- with Sass, building Gutenberg has become more involved and it is easier to let user install the already built binary

**Comment by saghm** [comment]
Quick follow-up, if that's all right to do on the same issue: are there any plans for introducing a way to update to newer versions without having to manually download them (e.g. with the [`self_update` crate](https://crates.io/crates/self_update))?

**Comment by Keats** [comment]
That crate is interesting, I didn't see it before!
I think I would rather leverage package managers for update though

**Comment by ctz** [comment]
Maybe yank the old versions? They currently suggest `cargo install gutenberg` as an installation method.

**Comment by Keats** [comment]
@ctz good idea! Just yanked all of them

**Comment by kohensu** [comment]
FYI: rust-lang/cargo#5654 (Publish lockfile for binary crates)

**Comment by Keats** [comment]
I've seen that but now Gutenberg is split in many subcrates to improve compile time and it doesn't make sense to publish those so it will stay ouf of crates.io I'm afraid

**Comment by michaelmior** [comment]
Found this here which was a reasonable explanation why Zola isn't available to install via Cargo as I expected. It would be helpful if this was briefly noted in the README since it's fairly unusual for a Rust project.

**Comment by michaelmior** [comment]
On second thought, it looks like the issue with not respecting lock files is resolved now, so perhaps this isn't an issue anymore?

**Comment by Keats** [comment]
There's also the fact that it is now split in multiple crates to make compilation time manageable and I have no interest in publishing all of those on crates.io.

> since it's fairly unusual for a Rust project.

I view crates.io mostly as a repository of libraries, I use my OS package manager for binaries.

**Comment by michaelmior** [comment]
I'm just speaking from my personal experience as a consumer of Rust binaries. I personally like using cargo to install them. And publishing is easier for me since I don't need to make packages for different OSes. But I understand others prefer different options. Anyway, thanks for the response and thanks for Zola!

**Comment by polyzen** [comment]
https://github.com/rust-lang/cargo/pull/7026
