### ISSUE TITLE
Remove `unwrap` in serve.rs

### ISSUE THREAD

**Issue by Keats** [getzola/zola#1170]
https://github.com/getzola/zola/blob/9f367ae7e7af33b58be8335899708ab2d80f5213/src/cmd/serve.rs#L324 can happen and the user just gets a panic.

**Comment by daretobedifferent18** [comment]
I want to solve this issue

**Comment by whizsid** [comment]
I like to work on this issue. Can you give me an approach? Are you need to display some error messege? Or return an error?

**Comment by Keats** [comment]
We just want to print an error message saying the port is already in use and exit.
