### ISSUE TITLE
HTML tag in shortcode is escaped

### ISSUE THREAD

**Issue by hannobraun** [getzola/zola#1172]
# Bug Report

## Environment

Zola version: 0.12

This is a regression. It worked with Zola 0.8. I haven't checked any versions in between.

## Expected Behavior

I expect HTML tags in shortcodes to not be escaped. For example, I have the following shortcode:
``` html
<a class="resize-image" href="/tlera-corp-gnat/gnat-with-picoblade-cable.jpg">
    <img
        src="{{ resize_image(path=path, width=width, op="fit_width") }}"
        alt="{{ alt }}">
    </img>
    <p>(click for full size)</p>
</a>
```
(this contains two mistakes I noticed today: hardcoded `href` and stray `</img>`; I left them in since they're not relevant to this issue, and this is the version that's currently deployed on my website)

Here's the call site: https://github.com/braun-embedded/braun-embedded.com/blame/ad06c3af817d1edbb4523b471ce4c9fc6cc8f3c5/content/tlera-corp-gnat/index.md#L62

And here's code that Zola 0.8 generates:
``` html
<a class="resize-image" href="/tlera-corp-gnat/gnat-with-picoblade-cable.jpg">
    <img
        src="https:&#x2F;&#x2F;braun-robotics.com&#x2F;processed_images&#x2F;e9176ef2eb5b34b300.jpg"
        alt="A Tlera Corp Gnat with soldered on PicoBlade connector, connected to a PicoBlade cable that has been soldered together with some jumper wires. The craftsmanship leaves something to be desired.">
    </img>
    <p>(click for full size)</p>
</a>
```

All is well.

## Current Behavior

Zola 0.12 generates this code instead:
``` html
<p><a class="resize-image" href="/tlera-corp-gnat/gnat-with-picoblade-cable.jpg">
    &lt;img
        src=&quot;http://127.0.0.1:1111/processed_images/e9176ef2eb5b34b300.jpg&quot;
        alt=&quot;A Tlera Corp Gnat with soldered on PicoBlade connector, connected to a PicoBlade cable that has been soldered together with some jumper wires. The craftsmanship leaves something to be desired.&quot;&gt;
    </img>
    <p>(click for full size)</p>
</a></p>
```
There are two unexpected differences:
1. The `<img>` element is escaped, which means it is displayed as text by the browser.
2. There's an additional `<p>` around the shortcode. I guess that doesn't matter.

## Step to reproduce

1. git clone https://github.com/braun-embedded/braun-embedded.com.git
2. cd braun-embedded.com; zola serve
3. Observe the issue on the `/tlera-corp-gnat` page.

## Possibly related problem

There's a possibly related problem I've seen while upgrading the same page. I suspect it's caused by the same bug, but please let me know, if you want me to open a separate issue.

I have a commented shortcode call in my site:
``` html
<!--
{% testimonial(author="Louis Thiery", org="Helium Systems", link="https://www.helium.com/") %}
<p>
    This fixed bid format was a first for me and it turned out very positive; I've otherwise tended to hear negative feedback from both contractors and clients on fixed bid engagements, so I'm glad we were able to see it "done right" with you.
</p>
{% end %}
-->
```

Zola 0.8 did what I'd expect:
``` html
<!--
<div class="testimonial">
    <blockquote>
        <p>
    This fixed bid format was a first for me and it turned out very positive; I've otherwise tended to hear negative feedback from both contractors and clients on fixed bid engagements, so I'm glad we were able to see it "done right" with you.
</p>
    </blockquote>
    <p class="testimonial-author">
        <strong>- Louis Thiery,
                <a href="https:&#x2F;&#x2F;www.helium.com&#x2F;">Helium Systems</a>
        </strong>
    </p>
</div>
-->
```

While Zola 0.12 escapes the `-->`, making the rest of the page disappear:
``` html
<!--
<div class="testimonial">
    <blockquote>
        <p>
    This fixed bid format was a first for me and it turned out very positive; I've otherwise tended to hear negative feedback from both contractors and clients on fixed bid engagements, so I'm glad we were able to see it "done right" with you.
</p>
    </blockquote>
    <p class="testimonial-author">
        <strong>- Louis Thiery,
            
                <a href="https:&#x2F;&#x2F;www.helium.com&#x2F;">Helium Systems</a>
            
        </strong>
    </p>
</div>
<p>--&gt;</p>
```

It also wraps the `-->` into a `<p></p>`, which I'm guessing is a consequence of escaping it.

**Comment by hannobraun** [comment]
I have just confirmed that both issues do not exist in 0.11. This must have been introduced in 0.12.

**Comment by Keats** [comment]
Might be caused by https://github.com/getzola/zola/pull/1085

**Comment by Keats** [comment]
The PR above should fix it.
There's another potential shortcode issue I want to check but it should get released soon.
