### ISSUE TITLE
`zola serve` deletes /public/

### ISSUE THREAD

**Issue by keysmashes** [getzola/zola#1173]
# Bug Report

## Environment

Zola version: 0.12.0

## Expected Behavior
I would expect Zola to not delete the build directory after I run `zola serve`. (imo `zola serve` should be conceptually equivalent to running `zola build` and then `cd public && python3 -m http.server`, and if it doesn't behave like that then it should be clearly documented)

## Current Behavior
Once `zola serve` exits, the /public/ directory no longer exists.

## Step to reproduce
- run `zola build`
- notice that /public/ exists
- run `zola serve`
- ctrl-c
- notice that /public/ is gone

**Comment by Keats** [comment]
That's not a bug, that's the intended behaviour. Leaving public/ around means you have some random files around the next time you run it. This is less an issue now that `zola serve` is not writing the HTML to disk but not deleting public did cause issues before.

**Comment by a8nJ** [comment]
Can this please be reopened? I version control my output files, so I cant possibly see why it would make sense to delete that folder.

**Comment by a8nJ** [comment]
Can this please be reopened? I version control my output files, so I cant
possibly see why it would make sense to delete that folder. Looks like this
evil code is here:

https://github.com/getzola/zola/blob/f5a200e64c9e629cd36db36a3637f5a86311061e/src/cmd/serve.rs#L359-L362

I might see if I can do a pull request.

**Comment by a8nJ** [comment]
https://github.com/getzola/zola/pull/1226
