### ISSUE TITLE
zola build/serve hangs for specific markdown

### ISSUE THREAD

**Issue by CSUwangj** [getzola/zola#1174]
# Bug Report

## Environment

Zola version: 0.11.0 on Windows 10

## Expected Behavior

build/serve success with seconds

## Current Behavior

zola hangs at

```
$ zola serve                                                                     
Building site...
```

## Step to reproduce

```
zola init test
```

then copy content below into content/test.md

<details>
<summary>
markdown content
</summary>

<pre>
+++
title = "2019-03-08 Daily Challenge"
path = "2019-03-08-daily-challenge"
date = 2019-03-08T00:32:00+00:00
updated = 2020-09-19T20:01:27.634309+00:00
description = "DailyChallenge"
in_search_index = true

[taxonomies]
tags = [ "CodeWars",]
categories = [ "DailyChallenge",]
archives = [ "archive",]
+++
What I've done today is *PaginationHelper* in *JavaScript*.

# CodeWars

### PaginationHelper

For this exercise you will be strengthening your page-fu mastery. 
You will complete the PaginationHelper class, which is a utility 
class helpful for querying paging information related to an array.

The class is designed to take in an array of values and an integer 
indicating how many items will be allowed per each page. The types 
of values contained within the collection/array are not relevant.

The following are some examples of how this class is used:

```javascript
var helper = new PaginationHelper(['a','b','c','d','e','f'], 4);
helper.pageCount(); //should == 2
helper.itemCount(); //should == 6
helper.pageItemCount(0); //should == 4
helper.pageItemCount(1); // last page - should == 2
helper.pageItemCount(2); // should == -1 since the page is invalid

// pageIndex takes an item index and returns the page that it belongs on
helper.pageIndex(5); //should == 1 (zero based index)
helper.pageIndex(2); //should == 0
helper.pageIndex(20); //should == -1
helper.pageIndex(-10); //should == -1
```

## Solution

```js
// TODO: complete this object/class

// The constructor takes in an array of items and a integer indicating how many
// items fit within a single page
function PaginationHelper(collection, itemsPerPage){
  this.cap = itemsPerPage;
  this.size = collection.length;
}

// returns the number of items within the entire collection
PaginationHelper.prototype.itemCount = function() {
  return this.size;
}

// returns the number of pages
PaginationHelper.prototype.pageCount = function() {
  return Math.ceil(this.size/this.cap);
}

// returns the number of items on the current page. page_index is zero based.
// this method should return -1 for pageIndex values that are out of range
PaginationHelper.prototype.pageItemCount = function(pageIndex) {
  if (pageIndex < 0 || pageIndex > Math.floor(this.size/this.cap)) return -1;
  else if (pageIndex === Math.floor(this.size/this.cap)) return this.size % this.cap;
  return this.cap;
}

// determines what page an item is on. Zero based indexes
// this method should return -1 for itemIndex values that are out of range
PaginationHelper.prototype.pageIndex = function(itemIndex) {
  if (itemIndex < 0 || itemIndex >= this.size) return -1;
  return this.size===0?-1:Math.floor(itemIndex/this.cap);
}
```

```js
// TODO: complete this object/class

// The constructor takes in an array of items and a integer indicating how many
// items fit within a single page
function PaginationHelper(collection, itemsPerPage){
  this.cap = itemsPerPage;
  this.size = collection.length;
}

// returns the number of items within the entire collection
PaginationHelper.prototype.itemCount = function() {
  return this.size;
}

// returns the number of pages
PaginationHelper.prototype.pageCount = function() {
  return Math.ceil(this.size/this.cap);
}

// returns the number of items on the current page. page_index is zero based.
// this method should return -1 for pageIndex values that are out of range
PaginationHelper.prototype.pageItemCount = function(pageIndex) {
  return pageIndex < this.pageCount()
    ? Math.min(this.itemsPerPage, this.size - pageIndex * this.cap)
    : -1;
}

// determines what page an item is on. Zero based indexes
// this method should return -1 for itemIndex values that are out of range
PaginationHelper.prototype.pageIndex = function(itemIndex) {
  return itemIndex < this.size && itemIndex >= 0
    ? Math.floor(itemIndex/this.cap)
    : -1;
}
```

</pre>
</details>

then go to zola root and `zola serve` or `zola build`

**Comment by Keats** [comment]
Try to use `jsx` rather than `js` for the type of code block. It seems the JS syntax has some issues.

**Comment by CSUwangj** [comment]
change to `jsx` fix hangs, thank you!

**Comment by codesections** [comment]
Two notes on this issue:

1.  It also causes hangs with some `html` blocks that contain inline JavaScript (I suppose it must use the `js` syntax internally? )
2.  This issue didn't occur in versions before 0.11.0.  If it's an upstream issue that won't be fixed in zola, would it be worth mentioning in the chagelog?  It's a bit disconcerting to have a working site, update zola to a new version, and break the site for reasons that aren't related to the breaking changes mentioned in the changelog?

(I've resolved my issue; so if you don't want to make any changes that won't impact me.  But I thought I'd mention this in case it's something you'd like to know about)

**Comment by Keats** [comment]
I'll update all the syntaxes for the next release, hopefully the JS syntax was fixed upstream, otherwise I'll open an issue with syntect.
I'm usually updating all the official sublime syntaxes on most releases and I (obviously) don't have time to check every languages :/
