### ISSUE TITLE
Taxonomy list and single term pages are not generated

### ISSUE THREAD

**Issue by anthonychwong** [getzola/zola#1177]
# Bug Report

## Environment

Zola version: 0.12.0 (with image `balthek/zola:0.12.0`)

## Expected Behavior
Taxonomy list and single term pages should be generated as specified in templates.

## Current Behavior
When navigate to taxonomy list and single term pages, it only shows `Not found`.

## Step to reproduce
1. Add template for taxonomy list and single term pages
2. `zola serve` runs without error

```
Building site...
-> Creating 1 pages (0 orphan), 1 sections, and processing 0 images
Done in 1.5s.

Listening for changes in /site{config.toml, content, sass, templates, themes}
Press Ctrl+C to stop

Web server is available at http://0.0.0.0:1111
```

3.  Navigate to the following pages only shows `Not found`
- Taxonomy list, e.g. http://127.0.0.1:1111/note-tags
- Single term, e.g. http://127.0.0.1:1111/note-tags/tag-2/

The repo for reproducing this issue is here https://github.com/anthonychwong/getzola-issue-1169/releases/tag/issue-1177

**Comment by Keats** [comment]
Are you on Windows? If so, that's a known issue and will be fixed soon with a 0.12.1 release.

**Comment by anthonychwong** [comment]
I'm using docker image `balthek/zola:0.12.0` on Ubuntu 20

**Comment by Keats** [comment]
Thanks for the reproduction, I'll have a look asap.

**Comment by Keats** [comment]
This is fixed in the `next` branch, thanks for the report!
