### ISSUE TITLE
Add support for webp

### ISSUE THREAD

**Issue by ctron** [getzola/zola#1178]
Currently `resize_image` supports JPEG and PNG as output. It would be great if support for WEBP could be added. As webp is supported by most browsers  80.9%  -> https://caniuse.com/webp) and provides much smaller file sizes, it is also preferred by Google PageSpeed.

**Comment by Keats** [comment]
We use https://github.com/image-rs/image which doesn't seem to support webp encoding: https://github.com/image-rs/image#21-supported-image-formats
I'll add it as soon as it gets added to image though. I don't want to add more FFI to some C library right now.

**Comment by ctron** [comment]
Wouldn't it be an option to spawn an external process, calling `cwebp`?

**Comment by Keats** [comment]
Not really, I don't want to start having external processing for assets right now otherwise that's door open to node and others, that are in much more demand than webp :/

**Comment by strohel** [comment]
For reference, webp support seems to have been added in https://github.com/getzola/zola/pull/1360
