### ISSUE TITLE
JS Package Dependency Management

### ISSUE THREAD

**Issue by anthonychwong** [getzola/zola#1180]
I am adding different features in JS to a zola site, e.g. flow charts, collapsible sections and tab, and they have different dependencies. Managing them with short code and macros is possible but sounds redundant since NPM already having all the information and mechanism.

Is there a way to manage JS dependencies in zola? Maybe invoke npm functions or retrieve data from npm?

**Comment by Keats** [comment]
You can do your JS dependencies management outside of zola, eg have your package.json at the root of the site with webpack or whatever is needed put the new assets in the static folder. Zola is not going to call out other processes though.

**Comment by anthonychwong** [comment]
Since not all pages will use all the components / widgets, the benefit of involving Zola is that the generated page can decide to load minimal set of library based on short codes called by each page.

**Comment by sburris0** [comment]
> the generated page can decide to load minimal set of library

After the first load, aren't they cached anyways?
You could make a `{% block js %}` in your parent base template and define the JS libraries you don't want on every other page inside the page templates:
```jinja2
{% block js %}
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.min.js"></script>
<!--  Only on pages with math: -->
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js"></script>
{% endblock %}

**Comment by Keats** [comment]
Closing, it's not going to be built in.
