### ISSUE TITLE
Serve command returns error with info about tokio failure

### ISSUE THREAD

**Issue by pacmancoder** [getzola/zola#1182]
# Bug Report
```zola serve``` command fails in the latest "next" branch head

## Environment
Zola version: "next" branch head, commit 664cb14ffd22bad6e0073eb27cd4dd85f4f599f0
OS: Windows 10 build 2004
Rust version: 1.46.0

## Expected Behavior
The website is served normally

## Current Behavior
`zola serve` command fails with the following output:
```
Building site...
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\io\driver\mod.rs:202:14
```

<details>
<summary>Backtrace</summary>

> stack backtrace:
>    0: backtrace::backtrace::trace_unsynchronized
>              at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
>    1: std::sys_common::backtrace::_print_fmt
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
>    2: std::sys_common::backtrace::_print::{{impl}}::fmt
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
>    3: core::fmt::write
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
>    4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537
>    5: std::sys_common::backtrace::_print
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
>    6: std::sys_common::backtrace::print
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
>    7: std::panicking::default_hook::{{closure}}
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
>    8: std::panicking::default_hook
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:217
>    9: std::panicking::rust_panic_with_hook
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
>   10: std::panicking::begin_panic_handler
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:437
>   11: core::panicking::panic_fmt
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\panicking.rs:85
>   12: core::option::expect_failed
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\option.rs:1261
>   13: core::option::Option<tokio::io::driver::Handle>::expect<tokio::io::driver::Handle>
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\option.rs:344  14: tokio::io::driver::Handle::current
>              at C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\io\driver\mod.rs:201
>   15: tokio::io::registration::Registration::new_with_ready<mio::net::tcp::TcpListener>
>              at C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\io\registration.rs:106
>   16: tokio::io::poll_evented::PollEvented<mio::net::tcp::TcpListener>::new_with_ready<mio::net::tcp::TcpListener>
>              at C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\io\poll_evented.rs:206
>   17: tokio::io::poll_evented::PollEvented<mio::net::tcp::TcpListener>::new<mio::net::tcp::TcpListener>
>              at C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\io\poll_evented.rs:178
>   18: tokio::net::tcp::listener::TcpListener::from_std
>              at C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\net\tcp\listener.rs:268
>   19: hyper::server::tcp::AddrIncoming::from_std
>              at C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.8\src\server\tcp.rs:33
>   20: hyper::server::tcp::AddrIncoming::new
>              at C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.8\src\server\tcp.rs:29
>   21: hyper::server::Server<hyper::server::tcp::AddrIncoming, tuple<>, hyper::common::exec::Exec>::try_bind
>              at C:\Users\pacmancoder\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.8\src\server\mod.rs:131
>   22: zola::cmd::serve::create_new_site
>              at .\src\cmd\serve.rs:187
>   23: zola::cmd::serve::serve
>              at .\src\cmd\serve.rs:235
>              at .\src\main.rs:86
>   25: std::rt::lang_start::{{closure}}<tuple<>>
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\rt.rs:67
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:52
>   27: std::panicking::try::do_call
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:348
>   28: std::panicking::try
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:325
>   29: std::panic::catch_unwind
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panic.rs:394
>   30: std::rt::lang_start_internal
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:51
>   31: std::rt::lang_start<tuple<>>
>              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\rt.rs:67
>   32: main
>   33: invoke_main
>              at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
>   34: __scrt_common_main_seh
>              at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
>   35: BaseThreadInitThunk
>   36: RtlUserThreadStart
</details>

## Step to reproduce
Executa command `zola serve` for any website (reproduced on my own [blog](https://github.com/pacmancoder/pacmancoder.github.io))

**Comment by pacmancoder** [comment]
FYI: Looks like I have managed to fix this issue with the following workaround:

```diff
diff --git a/src/cmd/serve.rs b/src/cmd/serve.rs
index 58ea99b..83d2dd7 100644
--- a/src/cmd/serve.rs
+++ b/src/cmd/serve.rs
@@ -26,6 +26,7 @@ use std::path::{Path, PathBuf};
 use std::sync::mpsc::channel;
 use std::thread;
 use std::time::{Duration, Instant};
+use std::net::{SocketAddrV4, TcpListener};
 
 use hyper::header;
 use hyper::service::{make_service_fn, service_fn};
@@ -184,7 +185,8 @@ fn create_new_site(
     let address = format!("{}:{}", interface, interface_port);
 
     // Stop right there if we can't bind to the address
-    if Server::try_bind(&address.parse().unwrap()).is_err() {
+    let bind_address: SocketAddrV4 = address.parse().unwrap();
+    if (TcpListener::bind(&bind_address)).is_err() {
         return Err(format!("Cannot start server on address {}.", address))?;
     }
 

```

**Comment by Keats** [comment]
Can you send that as a PR? It's weird I haven't been getting that error
