### ISSUE TITLE
Zola serve version 0.12.1 gives an error after I change a content file.

### ISSUE THREAD

**Issue by mtolk** [getzola/zola#1187]
# Bug Report
Zola serve version 0.12.1 gives an error after I change a content file.

## Environment

Zola version: 0.12.1 on windows 10

## Expected Behavior

After I make a change in a content file _zola serve_ should detect the change, generate a new page containing the change and serve that new page in it's local webserver.

## Current Behavior

When starting the local server with __zola serve__ everything works as expected. After making a change in a content markdown file there's an error on the visible on the command line. But the website is still served in it's state of before the change.

I tried running with RUST_BACKTRACE=1, but that didn't give any extra messages. Or is that not enabled in release versions.

## Step to reproduce
Start you local webserver using zola serve.

Open a page in your browser. See it all works OK.

Make a change in the corresponding md file for the page.

See zola serve pick up the change, show an error, while still showing the __old__ page in the browser even after a refresh.

```
    D:\projects\zola\temp>zola0.12.1 serve
    Building site...
    -> Creating 1 pages (0 orphan), 1 sections, and processing 0 images
    Done in 58ms.
    
    Web server is available at http://127.0.0.1:1024
    
    Listening for changes in D:\projects\zola\temp{config.toml, content, static, templates}
    Press Ctrl+C to stop
    
    Change detected @ 2020-09-28 08:47:25
    -> Content changed D:\projects\zola\temp\content\section\_index.md
    Cannot start server on address 127.0.0.1:1024.
    Done in 11ms.
```
PS this same site worked as expected using zola 0.11

**Comment by Keats** [comment]
I have the fix on `next`, I'll release in a few minutes. Sorry about that :(

**Comment by mtolk** [comment]
Wow that's fast. Thanks a lot. 👍

**Comment by mtolk** [comment]
confirmed 0.12.2 fixes this issue
