### ISSUE TITLE
0.12.1 breaks `zola serve`

### ISSUE THREAD

**Issue by 2mol** [getzola/zola#1188]
# Bug Report

## Environment

Zola version: 0.12.1

## Expected Behavior

`zola serve` starts a server on localhost, port 1111, and reloads when changes to the site source code are detected.

## Current Behavior

The server starts correctly, but when changes are made, the message is

```
Change detected @ 2020-09-28 09:16:33
-> Content changed /path/to/site/bla.md
Cannot start server on address 127.0.0.1:1111.
```

## Step to reproduce

Run `zola serve` and change any site file.

**Comment by Keats** [comment]
🤦 I guess I'll need to release 0.12.2 very soon

**Comment by 2mol** [comment]
We've all been there, no fret :)
