### ISSUE TITLE
Github-pages deployment error: incorrect procedure

### ISSUE THREAD

**Issue by tbrowder** [getzola/zola#1191]
# Documentation issue

## Summary
The documentation is incorrect. The current docs say this:

*Next we need to create the Github Action. Here we can make use of the zola-deploy-action. Go to the Actions tab of your repository, click on set up a workflow yourself to get a blank workflow file. Copy the following script into it and commit it afterwards.*

This portion is not correct as of today: *click on **set up a workflow yourself** to get a blank workflow file*

There is no such setting that I could find, and it's not clear to me as to the next step. For the moment I have copied a workflow file I found in another tutorial blog and am trying that out.

## Proposed solution

Correct the docs. If I have success with my project, I will try to incorporate it in a PR.

**Comment by Keats** [comment]
I do see it on my repo?

<img width="1165" alt="Screenshot 2020-10-02 at 17 48 35" src="https://user-images.githubusercontent.com/680355/94943097-80c7f580-04d7-11eb-89ca-e7392db0f82f.png">

**Comment by tbrowder** [comment]
Doh, I went to the "Actions" menu item in the settings section. I've done that before because I'm just not used to looking at the tabs at the top--so sorry, closing this issue.
