### ISSUE TITLE
Code blocks not rendering clearly with indents instead of back ticks (```)

### ISSUE THREAD

**Issue by tbrowder** [getzola/zola#1196]
# Bug Report

Code blocks with indentation:

    some code

Code blocks with back tics:

```
some code
```

With Zola the indented version has very faint text while the back-tick version's text is bright.

## Environment

Zola version:  0.12.2

Debian Buster (10)

Theme: Docsascode

## Expected Behavior

The code block text rendered with the indented code blocks should be the same as with the back ticks.

See the example on my Zola site at [zola-blogs.us](https://zola-blogs.us).

**Comment by Keats** [comment]
Looks like the highlighter doesn't pick up the indentend one? I really wish we could just disable indented syntax highlighting :(

**Comment by tbrowder** [comment]
The only problem I have with that is I use an iPad a lot and don't have easy access to back ticks. Could you use three tildes? 

~~~
some code
~~~

**Comment by Keats** [comment]
Yep, in theory backticks and tilde are interchangeable.

**Comment by tbrowder** [comment]
It isn't clear to me if a theme's config variables override the base config or not, specifically highlight_* variables.

**Comment by Keats** [comment]
base config should override the theme if set
