### ISSUE TITLE
Ctrl+C sometimes throws an error on Windows

### ISSUE THREAD

**Issue by dertuxmalwieder** [getzola/zola#1199]
# Bug Report

## Environment

Zola version: 0.12.2
Windows 10

## Expected Behavior
`Ctrl`+`C` should stop `zola serve` without a problem.

## Current Behavior
It usually works as expected. However, after a few recompiled changes in my theme, `zola serve` dislikes my pressing of `Ctrl`+`C`:

    Encountered an error: other os error
    Enable a logger to see more information.

At least it does really cancel the process... :-) 

I don't really know how to "enable a logger" here. `set RUST_BACKTRACE=1` does not add any output.

## Step to reproduce
Download the latest Zola release for Windows 10, run `zola serve`, make a few changes (save each time), then try to cancel.

**Comment by Keats** [comment]
See https://github.com/Detegr/rust-ctrlc/issues/61
If someone on Windows can debug it, it would be great

**Comment by dertuxmalwieder** [comment]
Oh, thank you.

My Rust is... non-existant yet, so I'm not a good debugger for that. But I'll watch this.

**Comment by Keats** [comment]
@dertuxmalwieder are you still running into that?

**Comment by dertuxmalwieder** [comment]
I am not near a Windows machine right now. I will try to reproduce that tomorrow!

**Comment by dertuxmalwieder** [comment]
I could not reproduce it today. Is it safe to assume that it has been fixed?

**Comment by Keats** [comment]
It was always very odd that it happened either way. Let's close it and hope no one gets it again.
