### ISSUE TITLE
Shortcodes are getting wrapped in `<p>`

### ISSUE THREAD

**Issue by ibraheemdev** [getzola/zola#1203]
I have a shortcode that looks like this:
```html
<span class="level-indicator level-2">
{% if level == 0 %}
  <i class="fa fa-times-circle"></i>
{% endif %}
</span>
```

It ends up getting rendered as a block level element, wrapped in a bunch of `<p>` tags:
```html
<span class="level-indicator level-2">
 <p>
  <i class="fa fa-check-circle-o"></i>
  </p>
<p></p></span>
```

I tried wrapping it in a `<div>`, as per the docs, with no change. I am calling the shortcode like this in my markdown:
```html
{{ level(level=0) }}
```

And the markdown is being rendered in a template with only the `safe` pipe.

Also, is there any specific reason that you cannot use tera templating directly in markdown? Creating a new template, or using shortcodes becomes a hassle if the logic is not repeated.

EDIT: Putting the if statements and the closing `</span>` tag on the same line seems to fix the issue???
```html
<span class="level-indicator level-2">
{% if level == 0 %} <i class="fa fa-times-circle"></i> {% endif %} </span>
```
My shortcode contains more logic than this, and putting it all on one line is kind of weird...

**Comment by Keats** [comment]
Which version of zola is that with?

**Comment by ibraheemdev** [comment]
zola 0.12.2

**Comment by Keats** [comment]
Ok so I believe this is already fixed in `next` if you want to try it.
