### ISSUE TITLE
asset links adaptation to subdirectory

### ISSUE THREAD

**Issue by Grummfy** [getzola/zola#1205]
# Bug Report
When we have static file likes image or document, I want to link it without worrying about where the static website will be deployed.

## Environment

Zola version: 0.11

## Expected Behavior
directory
/static/resources/document.odt
/static/images/some-image.png
/content/foo.md

foo.md
```
+++
title = "Some page"
+++

click [here](/resources/document.odt) to download<br />
![Alt text](/images/some-image.png)
```

The rendering is correct, except that it links to the root of the server.
So if I say that I want to deploy to my.server.com/subdirectory/, the link should be rewrite (or some option should be given to make it as internal) to 
* /resources/document.odt  -> /subdirectory/resources/document.odt 
* /images/some-image.png -> /subdirectory/images/some-image.png

It must be dynamics or based on a configuration. Like this using zola serve, will work, and deploy using gitlab/githubpage or whatever stuff that deploy inside a subdirectory will work too.

## Current Behavior

The links point to the root of the server. So if you deploy in a subdirectory like my.server.com/subdirectory/ all the link will point to my.server.com/resources/document.odt or my.server.com/images/some-image.png

## Step to reproduce
* take my example
* generate it with `zola build --base-url "https://my.server.com/subdirectory/ "`
* deploy it
* explore

link to my actual solution for static document https://zola.discourse.group/t/solved-static-files-documents-and-subdirectory-publishing/641/2

**Comment by southerntofu** [comment]
This is related to #977. Don't hesitate to read what's being discussed there and contribute your own thoughts :)

**Comment by Grummfy** [comment]
thanks, so I will close this, because it's a partial duplication of #977
