### ISSUE TITLE
Feature request: Support Tera in content

### ISSUE THREAD

**Issue by wiseman** [getzola/zola#1207]
Is there a reason that I can't use Tera templating inside a content markdown file?

**Comment by Keats** [comment]
It would be a pain to have both templates and shortcodes in the same file. There are some usecases where it would be nice to have the markdown file be a template but not worth the added complexity.

**Comment by orowith2os** [comment]
Coming back to this, four years later; is there some viable option for this? Could I  define a dedicated section where only Tera templating is allowed, with HTML, and no markdown?

**Comment by orowith2os** [comment]
It appears shortcodes are enough for my use case, but more support for Tera templating in markdown content would be useful.

https://www.getzola.org/documentation/content/shortcodes/
