### ISSUE TITLE
Deal with failure from load_data

### ISSUE THREAD

**Issue by ibraheemdev** [getzola/zola#1209]
There is currently no way to deal with failure from `load_data`, whether due to a 404 for remote data, or nonexistent files. Right now, the build just fails.

I can work on this issue. The best way I can think of is to add an optional `required` (default true to prevent breaking changes) parameter to `load_data`. If required is false and the function fails, it simply returns null (does tera have nulls?), and the user can deal with it, knowing that it failed.

We could also add an optional `default` fallback value: `load_data(path="data.json", default={...}, required=false)`

Would a PR implementing the above behaviour be accepted?

**Comment by Keats** [comment]
I think it makes sense

**Comment by southerntofu** [comment]
Hi, i really like this idea i had the same problem lately.

> We could also add an optional default fallback value: load_data(path="data.json", default={...}, required=false)

Wouldn't fallback work with `load_data(path="data.json", required=false)|default(value={...})` if load_data returns false (or None)? I'll try this and let you know :)

**Comment by southerntofu** [comment]
#1306 is my patch for this. Would this be ok for you @ibraheemdev ? It does not print warnings for missing files when required=false, not sure if that's a feature or a bug.

> load_data(path="data.json", required=false)|default(value={...})

This does not seem to work with my patch. 

```
{% set test = load_data(url="http://example.example", required=false)|default(value="TEST") %}
1{{ test }}1
<br>2{{ test|default(value="TEST") }}2
```

This produces:

```
11
2TEST2 
```

So the first default is silently discarded but the second works? Is there a difference between how tera evaluates in a condition a variable and a function result?

**Comment by ibraheemdev** [comment]
#1306 looks good :+1:

**Comment by ibraheemdev** [comment]
oops :)
