### ISSUE TITLE
`draft` variable does nothing

### ISSUE THREAD

**Issue by jeffparsons** [getzola/zola#121]
README.md mentions

> draft: whether the post is a draft or not

But I notice there's no reference to drafts in the code.

I'd like to be able to use this feature. I'd be happy enough if it was just a field that did nothing, so I could then use it like `{% if not page.draft %}` or similar in a post index, but I guess you might have had something a little more clever than that in mind.

So...

1. Are you still interested in having a draft feature in Gutenberg, and if so
2. How would it have to behave for you to merge a PR implementing it? (I.e. dumb field, or something smarter?)

**Comment by Keats** [comment]
Ah I removed it some time ago but forgot to think of the interactions with pagination so adding it back is needed imo.

2/ It would be a `Option<bool>` field on `PageFrontMatter` that is serialised. Pagination, RSS and sitemap will have to ignore drafts but that would be it I think

**Comment by Keats** [comment]
That should be fixed by https://github.com/Keats/gutenberg/commit/2d97786e676304d88eec4f571d1d823f2f189af7 if you want to try by building gutenberg from source

**Comment by Keats** [comment]
Should be fixed in 0.2.0!
