### ISSUE TITLE
Syntax Highlighting Infinite Loops

### ISSUE THREAD

**Issue by jswrenn** [getzola/zola#1211]
# Bug Report

I've encountered a few instances where attempting to highlight semi-valid syntax fragments causes `zola build` to never terminate.

## Environment

Zola version: 0.11.0

## Expected Behavior
The build should complete, although the snippet might be mis-highlighted.

## Current Behavior
[The build doesn't terminate.](https://github.com/jswrenn/site/actions/runs/316287054)

## Step to reproduce
This snippet was the latest one to trigger the problem for me:
````
```javascript
{
  ...

  /* 30 - 14 = 16 seats taken  */
  "seats": "<strong>Maximum Enrollment:</strong> <span class=\"seats_max\">30</span> / <strong>Seats Avail:</strong> <span class=\"seats_avail\">14</span>",
  /* 10 + 5 + 1 = 16 seats taken */
  "regdemog_json": "{\"FY\":10,\"So\":5,\"Oth\":1}",
  /* 16 seats taken */
  "regdemog_html": "<p class=\"enroll_demog\">Current enrollment: 16</p><div class=\"demogchart\"></div><div class=\"demogchartlegend\"><ul><li class=\"pieitem item_fy\">62.50% - First Year</li><li class=\"pieitem item_so\">31.25% - Sophomore</li><li class=\"pieitem item_oth\">6.25% - Other</li></ul></div>"

  ...
}
```
````

**Comment by Keats** [comment]
There's an issue with the js syntax, try to use the ts instead.

**Comment by gsurrel** [comment]
I got bitten by the same problem: Zola hangs (infinite loop) when there is a JSON code block labeled as JavaScript. It's going through when annotated with `ts` or `json` instead.

**Comment by Keats** [comment]
I'll try to update the JS syntax for the next release since it seems to be main culprit :/

**Comment by Keats** [comment]
Should be fixed now
