### ISSUE TITLE
zola tries to interpret templates/README.md as an actual template

### ISSUE THREAD

**Issue by yacoob** [getzola/zola#1216]
# Bug Report

## Environment

Zola version: 0.12.2

## Expected Behavior
zola ignores `README.md` in `templates` dir.

## Current Behavior
When I run `zola build` on my [repository](https://github.com/yacoob/gcu) it complains about being unable to parse `templates/README.md` as a vaild template. 

```
Error: Error parsing templates
Reason:
* Failed to parse "/home/yacoob/workarea/gcu/templates/README.md"
  --> 30:51
   |
30 | more than happy to wreck the formatting on save. `{%- foo %}` is preferred for␊
   |                                                   ^---
   |
   = unexpected tag; expected end of input or some content
```

Indeed, that file is not a template - it's a README documenting the templates :D I'm not sure why exactly does zola try to parse it. It worked fine with zola 0.9 - that is, the `README.md` file was not considered a template.

## Step to reproduce
```
$ GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/yacoob/gcu
$ cd gcu
$ zola build
```

**Comment by Keats** [comment]
That's very odd

**Comment by Keats** [comment]
I can't reproduce it with the `next` branch?

**Comment by yacoob** [comment]
Can you see this failure with 0.12.2? If yes, then the problem has been fixed somewhere between HEAD and 0.12.2. If not, then it's down to my site config, and I'll try to debug this further. :)

**Comment by Keats** [comment]
I can't see it in master either

**Comment by Keats** [comment]
Closing as cannot reproduce.
