### ISSUE TITLE
Add classes during markdown -> html conversion

### ISSUE THREAD

**Issue by matiasilva** [getzola/zola#1222]
I've been through the docs a few times and I can't find a way to customize the HTML that's generated from the Markdown. My use case is that I'm using Bulma and since it doesn't apply any default styles to `h2`s I want to add the `title` class to `##` headings, for example.

If this doesn't exist (or shouldn't), would the best way be to use a shortcode then? I presume then that Markdown files become only just for raw text that goes into `<p>`s, right?

Thanks!

EDIT: Bulma has `content` which respects styling on plain HTML tags, though I would still be interested in hearing thoughts about the original issue?

**Comment by Keats** [comment]
You can't style the Markdown output currently, unless you use shortcodes as you say

**Comment by matiasilva** [comment]
Got it!
