### ISSUE TITLE
Positional parameters

### ISSUE THREAD

**Issue by a8nJ** [getzola/zola#1225]
It seems that Zola does not currently support positional parameters. For
example, if you have a template like this:

~~~
{{ load_data(path=alfa) }}
~~~

You can call it like this:

~~~
{{ bravo(alfa="charlie.txt") }}
~~~

but if you wanted to call like this:

~~~
{{ bravo("charlie.txt") }}
~~~

it seems that is not supported, even though the function only has one argument.
Here is example of what I am talking about:

https://gohugo.io/functions/get

**Comment by Keats** [comment]
This is not supported in Tera no (it is supported actually but only for Tera filters).
More a Tera issue than a Zola one.
