### ISSUE TITLE
Serve doesnt respect base_url

### ISSUE THREAD

**Issue by a8nJ** [getzola/zola#1227]
If I have this:

~~~
base_url = "https://example.com/alfa"
~~~

and I have a files like these:

~~~
content/index.md
content/bravo/index.md
~~~

If I run `zola serve`, I expect to be able to visit these pages:

~~~
http://127.0.0.1:1111/alfa
http://127.0.0.1:1111/alfa/bravo
~~~

but neither of those work, I have to use these:

~~~
http://127.0.0.1:1111
http://127.0.0.1:1111/bravo
~~~

why is that?

**Comment by a8nJ** [comment]
Seems like other people having this problem

https://zola.discourse.group/t/relative-path-for-my-website/395

**Comment by Keats** [comment]
That's zola serve overriding the base_url and doesn't handle urls not on the root. This is only in zola serve though, the zola build will have the correct paths.

**Comment by a8nJ** [comment]
The problem is, I have links in my templates like this:

~~~
<a href="/alfa">Alfa</a>
<a href="/alfa/bravo">Bravo</a>
~~~

which are all failing

**Comment by a8nJ** [comment]
It seems the issue is that Zola does not currently support something like
`.RelPermalink`, but instead only `.Permalink`. You can tell that from these
examples:

https://github.com/getzola/zola/blob/f5a200e64c9e629cd36db36a3637f5a86311061e/docs/templates/index.html#L10-L11
https://github.com/getzola/zola/blob/f5a200e64c9e629cd36db36a3637f5a86311061e/test_site/templates/index_paginated.html#L10

which both produce something like:

~~~
<link rel="stylesheet" href="https://www.getzola.org/site.css">
~~~

instead of:

~~~
<link rel="stylesheet" href="/site.css">
~~~

**Comment by a8nJ** [comment]
As a workaround, you can set:

~~~
base_url = "/alfa"
~~~

and then use one of these:

~~~
{{ config.base_url }}
{{ get_url(path="/") }}
~~~

youll get this with `zola serve`:

~~~
http://127.0.0.1:1111
~~~

and this with `zola build`:

~~~
/alfa
~~~

So its a little confusing, but it works. Only other thing I would mention, is
that Zola is doing some invalid encoding. It turns `/alfa` into this:

~~~
<a href="&#x2F;winter">Alfa</a>
~~~

**Comment by cdstanford** [comment]
Just commenting to say that I encountered the same issue. 89z's workaround is a good idea, but I'm not sure I'll use it because I'd like the site to be generated the same locally as it is in `public`, to check consistency of everything (e.g. check that `/alfa` is being added correctly).
So, I will probably

It would be nice to have something like `zola serve --root-url` to change the root to match `base_url`. Would that be a desirable and fairly self-contained change and something a new contributor could implement?
