### ISSUE TITLE
Feature request: exclude some dir/file when copy theme's static directory for `zola build`

### ISSUE THREAD

**Issue by Folyd** [getzola/zola#1231]
When we run `zola build`, all of the dir/file located at the theme's static directory will be copied, but it's unnecessary in most cases.
```rust
    /// Copy the main `static` folder and the theme `static` folder if a theme is used
    pub fn copy_static_directories(&self) -> Result<()> {
        // The user files will overwrite the theme files
        if let Some(ref theme) = self.config.theme {
            copy_directory(
                &self.base_path.join("themes").join(theme).join("static"),
                &self.output_path,
                false,
            )?;
        }
        // We're fine with missing static folders
        if self.static_path.exists() {
            copy_directory(&self.static_path, &self.output_path, self.config.hard_link_static)?;
        }

        Ok(())
    }
```

For example, [Rust Search Extension](https://rust.extension.sh/) website based on a theme called [juice](https://juice.huhu.io/). However, the juice's [showcases directory](https://github.com/huhu/juice/tree/master/static/showcases) also got  copied to the extension website, see: https://rust.extension.sh/showcases

So, I think we can provide a rule to exclude some unnecessary dir/file, such as every dir/file which starts with **_**(underscore) will be ignored. If it is Ok, I'd love to submit a PR. :)

**Comment by Keats** [comment]
Hmm why does that theme has files that users will most likely not care about? It could/should be that the showcases folder is out of the static folder in that case. I'd rather avoid implicit ignore and keep it simple if possible (eg copy everything)

**Comment by Folyd** [comment]
You're right, explicit better than implicit. 👍
