### ISSUE TITLE
Allow specifying default locale in filenames

### ISSUE THREAD

**Issue by BasixKOR** [getzola/zola#1232]
Currently Zola doesn't recognise files with default locale specified. For instance, if I try to create a page `hello.en.md` with default_language set as `en`, Zola fails to build the site.

However many of Git-based CMS (in my case Netlify CMS) specifies its locale in all posts including default locale. Although requiring to specify the locale will be breaking change, I think there's no reason to allow users to specify file's locale.

This could be useful for:
 - CMS
 - Changing default locale to another one

**Comment by BasixKOR** [comment]
P.s. I'm willing to work on this issue, just tell me where should I look into.

**Comment by Keats** [comment]
I think this is fine as a change, go for it
