### ISSUE TITLE
Zola fails to copy files from static/ on FreeBSD

### ISSUE THREAD

**Issue by DarkKirb** [getzola/zola#1234]
# Bug Report
An (otherwise empty) Zola site with any file in the static/ directory fails to build (using zola serve or zola build) because of "Invalid Argument (OS Error 22)" on FreeBSD

## Environment
OS Version:
`FreeBSD 13.0-CURRENT #1 r367315: Wed Nov  4 09:14:32 CET 2020`

Zola version: 0.12.2 and f5a200e64c9e629cd36db36a3637f5a86311061e

## Expected Behavior
The commands should complete successfully

## Current Behavior
When running `zola serve`, it outputs
```
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
Error: Invalid argument (os error 22)
```

The error seems to occur in [`utils::fs::copy_file_if_needed`](https://github.com/getzola/zola/blob/master/components/utils/src/fs.rs#L114-L137)

## Step to reproduce
1. Create an empty zola repo
2. Put any file in the static directory (`touch static/test.js`)
3. Attempt to build the site using `zola serve` on FreeBSD

**Comment by Keats** [comment]
Someone on BSD will need to debug that.

**Comment by DarkKirb** [comment]
i found the bug in a dependency crate, `filetime`. The bug has already been fixed there and the fix is just a cargo update
