### ISSUE TITLE
Pagination article should have a clear example of how to access the variable 

### ISSUE THREAD

**Issue by colinkiama** [getzola/zola#1237]
# Documentation issue

## Summary
Documentation is unclear. To access the paginator, you simply use `paginator` instead of `object.paginator`.

## Proposed solution
Some sort of clarification in the pagination article. It's confusing when you consider how to do other things like accessing pages `section.pages` etc.

**Comment by Keats** [comment]
How would you change it? Some suggestions?

**Comment by colinkiama** [comment]
By adding a simple code snippet that uses paginator variable.

Maybe a snippet that iterates through paginator.pages and renders each page’s title in a section template?
