### ISSUE TITLE
Classed Syntax Highlighting

### ISSUE THREAD

**Issue by evan-brass** [getzola/zola#1239]
Syntect has a struct for outputting css classes instead of inline styles.  This would make it easy to have light/dark mode support for highlighted code blocks.

**Comment by Keats** [comment]
There is https://github.com/getzola/zola/pull/913 for that but last time I checked this branch, syntect was panicking when running my personal site.

**Comment by evan-brass** [comment]
Ah, I should have looked through pull requests and not just issues.  I'll start there, thank you.

**Comment by Keats** [comment]
It's in 0.14, thanks @evan-brass !
