### ISSUE TITLE
Generic error message on empty links

### ISSUE THREAD

**Issue by edmellum** [getzola/zola#1243]
# Bug Report

## Environment

Zola version: 

## Expected Behavior
A nice error message should say an empty link in the markdown was encountered.

## Current Behavior
A generic `Failed to render content of: /path/to/file.md` error is displayed.

## Step to reproduce
Create a content file containing `[Some empty link]()` and run `zola serve`.

**Comment by Keats** [comment]
I'm getting

```
Error: Failed to render content of /Users/vincentprouillet/Code/pulls/zola-test/content/bob/_index.md
Reason: There is a link that is missing a URL
```

on the `next` branch so it might be fixed already?
