### ISSUE TITLE
Live reload protocol error (emits invalid JSON due to Windows style path separator)

### ISSUE THREAD

**Issue by Aidiakapi** [getzola/zola#1247]
# Bug Report

## Environment

Zola version: 0.12.2  
Windows 10.0.18363 Build 18363

## Expected Behavior
I expect an updates to my files to automatically reload the browser window.

## Current Behavior
LiveReload logs a protocol error due to invalid JSON.
These are the errors:
```
livereload.js?port=1024&mindelay=10:1 LiveReload protocol error (unparsable JSON) after receiving data: "
                    {
                        "command": "reload",
                        "path": "/sass\main.scss",
                        "originalPath": "",
                        "liveCSS": true,
                        "liveImg": true,
                        "protocol": ["http://livereload.com/protocols/official-7"]
                    }"..
livereload.js?port=1024&mindelay=10:1 LiveReload protocol error (unparsable JSON) after receiving data: "
                    {
                        "command": "reload",
                        "path": "D:\Projects\VSC\zola-test\templates\index.html",
                        "originalPath": "",
                        "liveCSS": true,
                        "liveImg": true,
                        "protocol": ["http://livereload.com/protocols/official-7"]
                    }"..
```
The first is what occurs when modifying `sass/main.scss`, the latter is what occurs when modifying the template `templates/index.html`.

The JSON is invalid due to unescaped Windows-style path separators.

## Step to reproduce

1. Run `zola init zola-test`
2. `cd zola-test`
3. `zola serve`
4. Navigate to http://127.0.0.1:1111/
5. Open the browser's developer console
6. Create a new file at `zola-test/templates/index.html`
7. Observe the error: ```LiveReload protocol error (unparsable JSON) after receiving data: "
                    {
                        "command": "reload",
                        "path": "D:\Projects\VSC\zola-test\templates\index.html",
                        "originalPath": "",
                        "liveCSS": true,
                        "liveImg": true,
                        "protocol": ["http://livereload.com/protocols/official-7"]
                    }"..```

**Comment by Aidiakapi** [comment]
The cause seems to be using `format!(...)` for JSON serialization. https://github.com/getzola/zola/blob/84ecd2ac5e2913426ea6e6a9dc55928e81d0df25/src/cmd/serve.rs#L153-L164

I've locally made a hotfix that simply replaces `\` with `/`, but that's quite a hacky solution. If there's interest I can PR it, but perhaps a more proper JSON serialization is in order.

**Comment by Keats** [comment]
So is it the reload_path that needs fixing?

**Comment by Aidiakapi** [comment]
Yes, `\` is an escape character in JSON, so and `\P` for example is an
invalid escape sequence, so parsing the JSON fails.

The JSON value should be escaped. It fails on Windows, because the path
separator is `\`, whereas on most other operating systems, it's `/`

**Comment by Keats** [comment]
Weird that no one got it before but we should canonicalize the reload_path then

**Comment by Aidiakapi** [comment]
Yeah, but maybe it's an error with the path that gets passed in. Maybe
that's supposed to be a server relative path, not a local filesystem path.
But I'm not familiar with the live reload protocol.

Other than that I suspect people on Windows just haven't noticed, you don't
get an error anywhere, except in the browsers console, and even there it's
not colored as an error, just a notice. So they might just be manually
refreshing, thinking that that's how it's intended to work.

**Comment by Keats** [comment]
@Aidiakapi do you have time to make a PR to fix that? It's easier if it's someone on Windows checking it.

**Comment by Aidiakapi** [comment]
Sure, opened a PR #1266. It does a proper JSON encode, and I've verified that it works just fine now.

Ignore that first commit btw. I initially applied the patch to the master branch, since that's usually the lastest. I also don't know why it's not referencing the PR automatically.
