### ISSUE TITLE
Regression: Zola serve fails with Error: Can't watch `sass` for changes in folder

### ISSUE THREAD

**Issue by leotsarev** [getzola/zola#1249]
# Bug Report

## Environment

Zola version: 0.12.2 (regressed from 0.11.0)

## Step to reproduce
Clone https://github.com/leotsarev/leotsarev.ru/ with submodules
Install zola 0.12.2
`Zola build` and `zola serve`

## Expected Behavior
Zola serve works just fine

## Current Behavior
Zola serve always fails with
```
Error: Can't watch `sass` for changes in folder `C:\Users\leo\source\repos\leotsarev\leotsarev.ru`. Does it exist, and do you have correct permissions?
Reason: Input watch path is neither a file nor a directory.
```

**Comment by Keats** [comment]
Thanks for the report! You do have `compile_sass = true` in `config.toml` but no sass folder, we should just disregard the error in that case.
If anyone is interested it's an easy change

**Comment by leotsarev** [comment]
0. Thanks for answer and thanks for your project!
1. I can't disregard error — `serve` commands aborts on this error.
2.  After changing to `compile_sass = false` error still exists. 

Only adding empty `sass` folder is viable workaround.

P.S. I tried to contribute back ("learn rust" was on my todo list), but stumbled upon https://github.com/compass-rs/sass-rs/issues/76

**Comment by Keats** [comment]
1. I meant in the code, we should not abort on this error
2. That's very weird...

**Comment by leotsarev** [comment]
Sorry for late comment — I can confirm that problem is fixed for me.
Thanks!
