### ISSUE TITLE
Posts with co-located assets have to explicitly specify a URL

### ISSUE THREAD

**Issue by 17cupsofcoffee** [getzola/zola#125]
I imagine this is more a 'not implemented yet' thing than a bug, but one thing I found a little unintuitive when I was moving my blog across to Gutenberg was the fact that posts that use an `index.md` (i.e. ones with assets co-located) have to explicitly specify a URL in the front matter.

For example, I have a post in my project which looks like this:

```
posts/
    writing-an-audio-plugin-in-rust/
        index.md
        img.png
```

Without the URL specified in the front matter, the output looks like this:

```
posts/
    index/
        index.html
        img.png
```

Whereas I'd expect it to look like this:

```
posts/
    writing-an-audio-plugin-in-rust/
        index.html
        img.png
```

Looking at the code, it doesn't seem like it'd be too difficult to have the URL be inferred from the folder for `index.md` posts - would you accept a PR with this change, if I were to submit one? Or is there some reason I'm missing why it doesn't work this way?

Just wanted to check before I wrote any code 😄

**Comment by Keats** [comment]
Whoa this bug has been there for ages and for some reason the test for that had a slug so it slipped through.
Fixed it and added a couple of tests in https://github.com/Keats/gutenberg/commit/a24851790c945008a7197eb334c5364960832faa

I'll make a new release today or tomorrow but you can try building it from source in the meantime. Thanks a lot!

**Comment by 17cupsofcoffee** [comment]
Thanks :) Will give it a try this evening.

**Comment by Keats** [comment]
Let me know if that works for you, I think I got everything I wanted for 0.2.0 and I'll do a release

**Comment by 17cupsofcoffee** [comment]
Built from source and it's working as expected now :+1: Thanks again!
