### ISSUE TITLE
Can't generate language-specific feed url with get_url

### ISSUE THREAD

**Issue by bemyak** [getzola/zola#1250]
# Bug Report

## Environment

Zola version:`0.12.2`, `next`

## Expected Behavior

Calling `get_url(path=config.feed_filename, lang=lang)` for non-default language should produce `/<lang>/atom.xml`

## Current Behavior
`get_url` ignores `lang` argument and always outputs `/atom.xml`

## Step to reproduce
1. Create a new zola site
1. Setup two languages: default and non-default
1. Try calling `get_url` function for non-default language

A very simple test project can be found [here](https://gitlab.com/bemyak/zola-test). Click `Switch to "non-default" language` and verify that `Feed url` did not change.

This looks relatively easy to fix, but I'm afraid to break backward compatibility.

**Comment by Keats** [comment]
Well that's a bug so fixing it is fine. Hopefully no one relies on a bug
