### ISSUE TITLE
[Enhancement] Hidden articles

### ISSUE THREAD

**Issue by magistau** [getzola/zola#1252]
Article taxonomies could have an attribute `hidden: bool`. If set to `true`, the article is not displayed in its section but is still accessible by URL?. Defaults to `false`.
This could be set to `true` for articles that are not drafts anymore but you first want somebody to check it.

**Comment by bemyak** [comment]
@j0hnmeow , I had a similar proposal here: https://zola.discourse.group/t/solved-hidden-posts/455/10
The idea is that you can place all you "hidden" pages into a specific "hidden" section, which does not contain `_index.md` file.
Then you need to modify a RSS feed and a sitemap to exclude sections that contain "hidden" in their path.

**Comment by magistau** [comment]
So it's not going to be added?

**Comment by Keats** [comment]
Very unlikely

**Comment by lf-** [comment]
> I had a similar proposal here: https://zola.discourse.group/t/solved-hidden-posts/455/10
> The idea is that you can place all you "hidden" pages into a specific "hidden" section, which does not contain `_index.md` file.
> Then you need to modify a RSS feed and a sitemap to exclude sections that contain "hidden" in their path.

fwiw: If you remove the date from the page in the directory that doesn't have an _index.md, you don't need a custom rss feed setup. Hidden pages are still leaked in the sitemap though, so you'd have to replace that template.
