### ISSUE TITLE
GitLab CI not working

### ISSUE THREAD

**Issue by magistau** [getzola/zola#1253]
# Bug Report
GitLab Pages example script doesn't work
## Environment

Zola version: `v0.12.0`

## Expected Behavior
Zola installing correctly

## Current Behavior

```sh
 apk add --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ zola
fetch http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  zola (missing):
    required by: world[zola]
```

## Step to reproduce
https://gitlab.com/johnmeow/johnmeow.gitlab.io/-/jobs/896324493

**Comment by Keats** [comment]
I believe it has been moved to community instead of testing? The docs have been updated already: https://github.com/getzola/zola/pull/1251

**Comment by magistau** [comment]
> I believe it has been moved to community instead of testing? The docs have been updated already: #1251

Thanks, didn't notice that!
