### ISSUE TITLE
Missing Allow: / in robots.txt

### ISSUE THREAD

**Issue by pierredewilde** [getzola/zola#1257]
# Bug Report

## Environment
Mac OS 10.14.6
Zola version: 0.12.2

## Expected Behavior
Without `robots.txt` in `templates` directory, default `robots.txt` should contain
```
User-agent: *
Allow: /
Sitemap: http://example.com/sitemap.xml
```

## Current Behavior
Without `robots.txt` in `templates` directory, default `robots.txt` contains
```
User-agent: *
Sitemap: http://example.com/sitemap.xml
```
_At least one or more Disallow or Allow entries per rule._
https://developers.google.com/search/docs/advanced/robots/create-robots-txt

## Step to reproduce
`zola build` without `robots.txt` in /templates:

Please note that documentation should also reflect this change.
https://www.getzola.org/documentation/templates/robots/

**Comment by Keats** [comment]
Thanks! that's an easy fix
