### ISSUE TITLE
elasticlunr is outdated

### ISSUE THREAD

**Issue by ghost** [getzola/zola#1260]
# Bug Report

Hi,
While navigating the sources, I noticed that `elasticlunr.js`(https://github.com/getzola/zola/blob/master/components/search/src/elasticlunr.min.js) is outdated: `0.9.5` instead of `0.9.6` https://github.com/weixsong/elasticlunr.js/tags).

It may be nice to upgrade.

I can make a PR if you want.

**Comment by Keats** [comment]
Go for it!

**Comment by ghost** [comment]
closed in #1261
