### ISSUE TITLE
Github Pages instructions outdated

### ISSUE THREAD

**Issue by alice-i-cecile** [getzola/zola#1264]
# Documentation issue

## Summary
> Go to the Actions tab of your repository, click on set up a workflow yourself to get a blank workflow file.

This line of the instructions, found [here](https://www.getzola.org/documentation/deployment/github-pages/) no longer works with the new Github workflow.

I do not see any option to "set up a workflow myself", only to change my action permissions, change artifact and log retention or set up a self-hosted runner, none of which seem to be what we want to do.

## Proposed solution
I'm new to Github Actions, so I'm not currently sure how to resolve this issue. Determining that, then updating the documentation to match will resolve this issue.

**Comment by Keats** [comment]
It might be different if you're in an org with fewer permissions? I still see it on personal repos

<img width="1170" alt="Screenshot 2020-12-17 at 09 42 37" src="https://user-images.githubusercontent.com/680355/102464077-34a73e80-404c-11eb-863a-8578c3646327.png">

**Comment by alice-i-cecile** [comment]
Oh! I was looking at the Settings -> Actions section, not the Actions tab. Thanks!
