### ISSUE TITLE
Supported language Clojure is not highlighted properly

### ISSUE THREAD

**Issue by vise890** [getzola/zola#1268]
**NOTE**: I opened a PR that seems to fix the issue #1269 

# Bug Report

## Environment

Kernel: Linux 5.9.15-1-MANJARO
Zola version: zola 0.12.2

## Expected Behavior

I would like to see my Clojure code blocks highlighted properly, like in the picture below:

![image](https://user-images.githubusercontent.com/1628760/103083859-c7605400-45dd-11eb-8cb9-1cfeeff45b87.png)

## Current Behavior

Everything after the first comment character (`;`), is highlighted as a comment:
![image](https://user-images.githubusercontent.com/1628760/103083889-da732400-45dd-11eb-953f-a2f8bdcf1b77.png)

## Step to reproduce

1. in config.toml:
   ```toml
   highlight_code = true
   ```
1. In a page `.md` source, add a clojure code block:
   ![image](https://user-images.githubusercontent.com/1628760/103083911-e828a980-45dd-11eb-8792-d9997a8fc00e.png)
3. Run `zola server` and navigate to that page, you will see (roughly):
   ![image](https://user-images.githubusercontent.com/1628760/103083897-de9f4180-45dd-11eb-8fd5-8bc18a795ada.png)

## Workaround

1. in the project root
   ```bash
   mkidr syntaxes
   cd syntaxes
   git submodule add https://github.com/tonsky/sublime-clojure
   ```
1. in `config.toml`
   ```toml
   extra_syntaxes = ["syntaxes/sublime-clojure"]
   ```
1. **Edit `sublime-clojure/ClojureC.sublime-syntax`** so that 
`file-extensions` look like this:
   ```sublime-syntaxt
   file_extensions: [bloop, clj, cljs, cljc, cljx, boot]
   ```
1. in the page source:
   ![image](https://user-images.githubusercontent.com/1628760/103084238-d1368700-45de-11eb-895b-ac4da3ff4510.png)

## Notes
- I couldn't find a clojure `.sublime-syntax in [`/zola/sublime/syntaxes/`](https://github.com/getzola/zola/tree/master/sublime/syntaxes)
- **It doesn't seem to be possible to override built in short-names** [listed in the docs](https://www.getzola.org/documentation/content/syntax-highlighting/), maybe it should?

**Comment by Keats** [comment]
It's using https://github.com/sublimehq/Packages/tree/f36b8f807d5f30d2b8ef639232a9fc5960f550fa/Clojure which is probably outdated.

We should have a way to override the default Sublime syntaxes since they are pretty old at this point.

**Comment by Keats** [comment]
That should be fixed in the `next` branch
