### ISSUE TITLE
Unable to build on aarch64-apple-darwin

### ISSUE THREAD

**Issue by 0xADD1E** [getzola/zola#1270]
# Bug Report

## Environment

Zola version: master

Hardware: Apple M1

## Expected Behavior
`cargo build --release` completes

## Current Behavior
`cargo build --release` does not complete due to ring <0.16.16 lacking the required platform support

## Step to reproduce
Attempt to build the current master branch on M1, note that it does not succeed

**Comment by jlricon** [comment]
@0xADD1E Thanks for the PR!

**Comment by 0xADD1E** [comment]
With the hotfix being rejected, should this be linked to the 0.12 milestone, or will there be another small release before then that would integrate the updated lockfile?

**Comment by Keats** [comment]
There will be 0.13 released very soon (this week), I just have a couple more fixes to add. The `next` branch should already compile on M1

**Comment by 0xADD1E** [comment]
That is correct, and is what I'm currently running - I simply prefer to be running stable release where possible.

Thank you so much!

**Comment by Keats** [comment]
Should be fixed in 0.13!
