### ISSUE TITLE
`zola check` fails on GitHub links to paragraphs

### ISSUE THREAD

**Issue by vise890** [getzola/zola#1273]
# Bug Report

## Environment

Zola version:zola 0.12.2

## Expected Behavior

No errors when cheching GitHub Links with anchors

## Current Behavior

Zola fails with "Anchor not found on page"

## Step to reproduce

1. right-click on link sign next to header to copy link location, get `https://github.com/getzola/zola/#pelican-notes`
2. make a simple zola site
    ```bash
    zola init foo
    cd foo
    cat << EOF > ./content/_index.md
    +++
    title = "hi"
    +++
    
    [zola pelican notes](https://github.com/getzola/zola/#pelican-notes)
    EOF
    ```
3. run `zola check`

### Expected to see
No failures

### Saw instead

```txt
Checking site...
Checking 0 internal link(s) with an anchor.
Checking 1 external link(s).
> Checked 1 external link(s): 1 error(s) found.
Failed to check the site
Error: Dead link in /home/trenolab/code/github-anchor/foo/content/_index.md to https://github.com/getzola/zola/#pelican-notes: Anchor `#pelican-notes` not found on page
```

## This is kind-of github's fault...
There actually isn't an element with id `#pelican-notes` on the page, and the link `https://github.com/getzola/zola/#pelican-notes` does not work with JS disabled (What has the web come to :facepalm: ). 

What does work is referring to the element that actually does exist: `#user-content-pelican-notes`. Idk if there's anything zola should do about this really... I made a ticket for github support..

**Comment by Keats** [comment]
There is `https://www.getzola.org/documentation/getting-started/configuration/` (https://www.getzola.org/documentation/getting-started/configuration/) specifically for this kind of things.
