### ISSUE TITLE
discuss: vimwiki (or any other) input language support

### ISSUE THREAD

**Issue by chipsenkbeil** [getzola/zola#1276]
### vimwiki

I've been working on [vimwiki-rs](https://github.com/chipsenkbeil/vimwiki-rs) (runtime & compile-time parsing of the vimwiki language) for a little while in conjunction with formally defining a specification for the language over at https://github.com/vimwiki/vimwiki/pull/1025, which just merged. The language has single and multi-line comments, which is where I'd stuff in metadata. 

I'm fairly confident I can parse vimwiki and fit the same output that your tool needs, at least from a glance where I see what [markdown::Rendered](https://github.com/getzola/zola/blob/29b073640e26d96ab167c88ca70b18660f176cb4/components/rendering/src/markdown.rs#L26) requires. Was eyeballing [render_content](https://github.com/getzola/zola/blob/master/components/rendering/src/lib.rs#L13) to see how rendering goes and it seems fairly clean.

My interest is enabling more users, including myself, to have the option to use vimwiki as a markup language given I already use it for note taking.

### Not directly integrated

I saw that https://github.com/getzola/zola/issues/909 was not desired, so it seems like adding other languages directly into the project isn't the way to go.

Other than forking this repo to add the language support myself, is there a more collaborative direction I could take? Adding some sort of dynamic plugin support seems like overkill. Would having the ability to pipe out the files to an external process that produces the HTML be an option? It isn't the most performant, but it would enable folks to swap in other input types. That way, I could have a vimwiki binary with a mode to support Zola.

Of course, if you're open to integrating a pure-Rust parsing and output library for vimwiki, I'm more than happy to drive that as well.

 Thoughts?

**Comment by Keats** [comment]
I'm not really looking for adding more input methods directly or indirectly for the short/medium term since there are some more important stuff to do like i18n. Maybe later, but as far as direct integration in Zola I think only Asciidoc would be considered.

**Comment by chipsenkbeil** [comment]
> I'm not really looking for adding more input methods directly or indirectly for the short/medium term since there are some more important stuff to do like i18n. Maybe later, but as far as direct integration in Zola I think only Asciidoc would be considered.

Fair enough. I'll close out this task.
