### ISSUE TITLE
use front matter variables as shortcode argument

### ISSUE THREAD

**Issue by SamHasler** [getzola/zola#1277]
Is it possible to  use front matter variables as an argument to a shortcode?

E.g.:

`{{ youtube(id=page.extras.youtubeid) }}`

**Comment by Keats** [comment]
Not right now

**Comment by Keats** [comment]
That would be nice to have though.

**Comment by Keats** [comment]
I'm thinking it would be nicer to always pass the `extra` section to shortcodes rather than being explicit about it

**Comment by tulsileathers** [comment]
yes this would be good as right now in a shortcode i'm checking if either section or page exists and getting extra accordingly. would be much nicer to have an extra variable as all my shortcodes function both for sections and pages. I'd be willing to tackle this issue. any  guidance @Keats ?

**Comment by Keats** [comment]
We don't want to pass the `extra` info twice and we're already passing the full page/section though. I think doing it in the shortcodes is better.

**Comment by tulsileathers** [comment]
What if there was an additional builtin Tera funtion get_extra() that returned the extra data from either the section or page? That would solve my problem of having to repeat that check in every shortcode

**Comment by Keats** [comment]
That won't be possible

**Comment by Keats** [comment]
It's not going to be usable as arguments but the page/section arguments are automatically added to the context of the shortcodes
