### ISSUE TITLE
Improve error message on "no such file or directory" in case of broken symlinks

### ISSUE THREAD

**Issue by proycon** [getzola/zola#1278]
# Bug Report

This is a minor issue / suggestion for error feedback improvement.

## Environment

Zola version: 0.12.2

## Current Behavior

If there is a broken symlink in the ``static/`` dir, ``zola serve`` exits as follows:

```
Error: No such file or directory (os error 2)
```

## Expected Behavior

The error message when a broken symlink is encountered should be a bit clearer, at least explicitly mentioning the file that is missing/broken.

## Step to reproduce

Create a broken symlink somewhere in ``static/``

**Comment by Keats** [comment]
I've added some debug on the `next` branch already, can you try that to see if it's better?

**Comment by proycon** [comment]
Yes, that solves it! I get a clear unable top copy A to B error there now.
