### ISSUE TITLE
Some Small Questions

### ISSUE THREAD

**Issue by kneasle** [getzola/zola#1280]
Firstly thanks so much for making Zola - it's so nice to have something that just works for what I want to achieve.

## Passing Variables to Parent Templates

Is there a simple way to 'pass' variables to a parent template, e.g. I have the `<title>` tag defined in `base.html`, but it should be set to the page/section title of every page. At the moment, I have to use a `{% block %}` for this - which is fine, I just wondered if there was a simpler way to do it.  This gets a bit uglier because the title is also used twice in `base.html`, so I need _two_ blocks with different names which are always set to the same value.

I can potentially see why this wouldn't be possible, since I'm guessing that templates are rendered down the heirachy and therefore this kind of thing would be a pain to implement.  But it just feels overkill to have to use blocks for this kind of thing. 

## Instantiating templates

Suppose that I have a section of a page that might be used quite a lot (say, I have a animation play-back bar that I would like to use in multiple different pages). What I'd like to do is to declare that as a template (say `animation-bar.html`) and then inside a page instantiate `animation-bar.html`, perhaps multiple times and with some specific arguments (like whether I want a fast forward button).

I'm not sure what you'd call this, but I can't find any examples in the docs and I feel like I can't be the first to want to do it.

## Accessing the tree structure in the base template

So what I want to achieve is to have a drop-down menu at the top of every page with all of the root-level `section`s, regardless of where in the tree the current page is. I'm sure this is possible using something like `getpage(_index.md)` but I couldn't find an example in the docs, so a simple example would be great :grin:.

**Comment by Keats** [comment]
Thanks!

1. Not possible right now. Do you have an example of the template and why you need to have two blocks?
2. I think you're looking for macros: https://tera.netlify.app/docs/#macros
3. It's a bit tricky, since we can't just have the whole site while rendering the templates for perf reasons. Have a look at the templates in https://github.com/getzola/book to have a look at a menu that I think is similar to what you want.

**Comment by kneasle** [comment]
> 1. Not possible right now. Do you have an example of the template and why you need to have two blocks?

```html
<!-- snip -->
<head>
    <title>Kneasle - {% block title %} {% endblock %}</title>
    
    <!-- snip -->
</head>

<body>
    <!-- snip -->
                <div class="title-div">
                    <h1>&gt;&gt; {% block name %} {% endblock %} </h1>
                </div>
    <!-- snip -->
</body>

</html>
```

Here, `{% block title %}` and `{% block name %}` should always be set to the same thing (both with the current page's title).  I managed to make a decent fix by defining them in `section.html` and `page.html` so I don't have to define them in every page.  This solution works fine, so I'm not fussed if this just isn't possible - I was simply wondering if there was a more light-weight way to do this.

> 2. I think you're looking for macros: https://tera.netlify.app/docs/#macros

Yes! I am - I'm not sure why I didn't find these myself, but thanks nonetheless.

> 3. It's a bit tricky, since we can't just have the whole site while rendering the templates for perf reasons. Have a look at the templates in https://github.com/getzola/book to have a look at a menu that I think is similar to what you want.

I'll give that a look... if the worst comes to the worst I can put them in by hand - I don't expect the top-level sections to change that much.

**Comment by Keats** [comment]
1. That would be https://github.com/Keats/tera/issues/265 but it's not implemented

**Comment by kneasle** [comment]
Ah OK I'm kinda happy to see that someone else has encountered the same thing.  But titles are really all I see this being an issue for, so it's not too big a deal.

Thanks for being quick on answering my questions!
