### ISSUE TITLE
Markdown Footnotes are not handled correctly in Page Summary rendering

### ISSUE THREAD

**Issue by behnam** [getzola/zola#1282]
# Bug Report
Turns out the Markdown rendered used by Zola does support Footnotes. (https://www.markdownguide.org/extended-syntax/#footnotes) Awesome!

Now, when Footnotes appear in the "Summary Section" of page, causing the rendering to be (commonly) displayed under a page URL other than the actual page holding the Footnote, the target of the Footnote link becomes invalid.

(Going to submit a PR for a diff demonstrating the issue better.)

## Environment

Zola version: zola 0.12.2

## Expected Behavior
a) If we like to keep Footnote rendering enabled in Page Summary rendering, then I think we should fix the link URL to the actual page holding the Footnote target.

b) Another option is to not render Footnote links in Page Summary rendering in the first place. With that, then the URL doesn't need any special handling.

Personally, I think I would prefer to have a site-wide option for this, since it may totally make sense to keep the Footnotes, in some cases, and not render them in some other cases.

(Of course, it's also possible to hide them via CSS, but, not the best way to handle the issue, imho.)

## Current Behavior
See https://github.com/getzola/zola/pull/1283

## Step to reproduce
See https://github.com/getzola/zola/pull/1283

**Comment by behnam** [comment]
Actually, another rational towards option (b) above:

In my design, I'm using a block-displayed `<a>` tag around the `page.summary` value, to allow easy navigation to the target page. However, with Footnote Link inserting an `<a>` tag into the content, the layout breaks on the client side, causing the DOM structure to cut the outer `<a>` to right before the footnote`<a>`.

**Comment by Keats** [comment]
Hmm I thought we were handling footnotes somehow already...

It would be hard to represent a footnote in the summary though in terms of code though. As for wrapping the whole thing in `<a>`, you will need to strip all the tags of the summary to make it work since there could be any tags in there.

**Comment by digitalresistor** [comment]
One quick note, it seems that the Markdown parser used by Zola (or some post parsing) means that multi-line footnotes are not supported:

```
[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.
```

is rendered as:

```
<div class="footnote-definition" id="bignote"><sup class="footnote-definition-label">1</sup>
<p>Here's one with multiple paragraphs and code.</p>
</div>
<pre style="background-color:#2b303b;"><code>Indent paragraphs to include them in the footnote.

`{ my code }`

Add as many paragraphs as you like.
</code></pre>
```

Which is not as intended.

**Comment by behnam** [comment]
> As for wrapping the whole thing in `<a>`, you will need to strip all the tags of the summary to make it work since there could be any tags in there.

Yeah, I'm having some DOM/CSS magic (plus relying on my content not using too many random MD/HTML features) to get it work. But, for one, footnote links are totally breaking it without much I can do—unless I parse the HTML and re-gen it again. (It's kind of nice to maintain *some* of the styling, and not go with a remove-all-tags approach).

**Comment by Keats** [comment]
I think we can do both with regexes:

1. Automatically use absolute URLs for footnotes in summary
2. Remove footnotes from summaries

Which is preferable? I would tend to say 2 since you're most likely on a different page when viewing the summary and it's not clear clicking the footnote would make you leave it.

**Comment by Keats** [comment]
I went with 2 in the commit above.
