### ISSUE TITLE
Shortcode: img tag in markdown does not seem to work

### ISSUE THREAD

**Issue by nahuakang** [getzola/zola#1284]
# Bug Report

## Environment

Zola version: 0.12.0

## Expected Behavior
If I create a shortcode as follows:
```html
    <img
    src="{{src}}"
    alt="{{alt}}"
    {% if height %}
      height="{{height}}"
    {% endif %}
    {% if width %}
      width="{{width}}"
    {% endif %}
  >
```

I should get an image when I insert this short code in my markdown file:
```markdown
{{ image(src="/images/some_image.png", alt="some image", height="250px") }}
```

## Current Behavior
However, currently it would output the raw string "{{ image(src="/images/some_image.png", alt="some image", height="250px") }}" in a `p` tag on the screen.

I must wrap the `img` tag between a `div` to work properly:
```html
<div class="content__image">
  <img
    src="{{src}}"
    alt="{{alt}}"
    {% if height %}
      height="{{height}}"
    {% endif %}
    {% if width %}
      width="{{width}}"
    {% endif %}
  >
</div>
```

## Step to reproduce
Try creating a shortcode as above with an existing image and insert the shortcode into a markdown file to see if an image appears.

**Comment by Keats** [comment]
The exact shortcode (without the div) works for me?

**Comment by nahuakang** [comment]
I tried a few things but still got a `<p>{{ image(src="/images/some_image.png", alt="some image", height="250px") }}</p>` instead of an image.

Do you know any possible reasons why a shortcode might be treated as text in a `<p></p>`? Thanks again!

**Comment by Keats** [comment]
Can you paste or link to the Markdown file?

**Comment by nahuakang** [comment]
Here's [the link](https://github.com/nahuakang/nahua.dev/blob/master/content/about.md). It's in my about page and here's the [shortcode](https://github.com/nahuakang/nahua.dev/blob/master/templates/shortcodes/image.html).

**Comment by Keats** [comment]
Hmm it works for me on the `next` branch and on `master`? That's odd

**Comment by nahuakang** [comment]
That's why I wonder if I created a bug myself in my repository, but I can't think of any reason (still have a lot to learn about SSGs).

**Comment by Keats** [comment]
I just noticed you're on 0.12, try to upgrade to at least 0.12.1 there was a shortcode bug fix in that

**Comment by nahuakang** [comment]
I'll keep that in mind! I have Zola installed via snap and the latest is only 0.12.0. Let me check what I can do.

**Comment by Keats** [comment]
_Probably_ fixed now, re-open if you still have the issue in 0.14.
