### ISSUE TITLE
Extra character in front-matter led to 30 minute hunt for the extra <ul>

### ISSUE THREAD

**Issue by digitalresistor** [getzola/zola#1287]
# Enhancement

## Environment

Zola version: 0.12.2

## Expected Behavior

It'd be great if Zola warned if the front-matter fences were malformed.

## Current Behavior

Zola strips off the front-matter, and passes the file to the markdown renderer

## Step to reproduce

Create a piece of content that looks like this:

```
+++
title = "Some random title"
date = 2021-01-02
++++
```

Then look at the output of the generated content:

```
<ul><li></li></ul>
```

I will admit that I am tired, and thus it was my fault, however instead of warning me that the fence around the front-matter was malformed, zola passed the extra `+` to the markdown renderer. Leading me on a weird goose chase.

It'd be great if it were a requirement that no other text were allowed to exist on the closing line fo the front matter fence!

**Comment by xpe** [comment]
Here are the relevant pieces of code from https://github.com/getzola/zola/blob/master/components/front_matter/src/lib.rs

```rs
lazy_static! {
    static ref PAGE_RE: Regex =
        Regex::new(r"^[[:space:]]*\+\+\+(\r?\n(?s).*?(?-s))\+\+\+\r?\n?((?s).*(?-s))$").unwrap();
}
```

```rs
/// Split a file between the front matter and its content
/// Will return an error if the front matter wasn't found
fn split_content<'c>(file_path: &Path, content: &'c str) -> Result<(&'c str, &'c str)> {
    if !PAGE_RE.is_match(content) {
        bail!(
            "Couldn't find front matter in `{}`. Did you forget to add `+++`?",
            file_path.to_string_lossy()
        );
    }

    // 2. extract the front matter and the content
    let caps = PAGE_RE.captures(content).unwrap();
    // caps[0] is the full match
    // caps[1] => front matter
    // caps[2] => content
    Ok((caps.get(1).unwrap().as_str(), caps.get(2).unwrap().as_str()))
}
```

**Comment by xpe** [comment]
It seems reasonable to me require `\+\+\+\r?\n` to close the frontmatter. Would this break expectations? Some specification? Important use cases?

**Comment by Keats** [comment]
I think it would be fine

**Comment by lf-** [comment]
I got surprised by this behaviour and just patched it out on account of not having looked at the git history. The trouble that the current impl causes is that if there is not a trailing newline in an intentionally empty file, `_index.md`, for example. But I get this and I see it probably stops a bigger footgun. So it's probably fine with me.

**Comment by digitalresistor** [comment]
We could probably update the regex to allow no newline at all, but if there is more content then a newline is required. That would still save me the footgun I found, but also allow no intention trailing newline in `_index.md`.

**Comment by Keats** [comment]
I'd take a PR for it

**Comment by digitalresistor** [comment]
I need to update the other PR I did too, I will try and get one done for this too :-)

**Comment by digitalresistor** [comment]
@Keats @lf- https://github.com/getzola/zola/pull/1408 contains the updated regex/code as well as tests to validate the new changes.
