### ISSUE TITLE
Publishing crate to crates.io

### ISSUE THREAD

**Issue by simonsan** [getzola/zola#1288]
I love to build tools on my own with `cargo install`, could you publish this crate on crates.io, please?

With [cargo-update](https://github.com/nabijaczleweli/cargo-update) updating the crate would be as easy as `cargo install-update zola` for me or just for all installed tools with `cargo install-update -a`.

**Comment by Keats** [comment]
This isn't planned no. It used to be on crates.io but in the end it was not worth it.

**Comment by simonsan** [comment]
Would you mind if i publish it then on my own for the community and others? Basically just a `cargo publish` away so to say

**Comment by Keats** [comment]
You will need to publish each crate of the workspace too. It would be ok as long as you mention it's not the official way to install/use in the description.

**Comment by simonsan** [comment]
> You will need to publish each crate of the workspace too. It would be ok as long as you mention it's not the official way to install/use in the description.

Ok, let me think of a way to automate that. If it works well, I'll make a PR and you can think about adopting it as well. ;-)

**Comment by Keats** [comment]
> Ok, let me think of a way to automate that.

I didn't really want to clutter crates.io with some internal details. It would be better if it was possible to have separate workspace components but publish as one crate but it's not possible :/

**Comment by simonsan** [comment]
I understand, I'm trying 

`cargo install --git https://github.com/getzola/zola`

for now and it seems to work and clone all the submodules as well. Let me take a look if this fixes it for me. Would make a PR for the fellow Rust community for this installation routine afterwards just to state that this is also possible to install from master with `cargo`.

```
 cannot checkout to invalid path 'Preferences/Symbol List: Blocks.tmPreferences'; class=Checkout (20)
```
