### ISSUE TITLE
Slashes encoded as &#x2F; in URLs

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#129]
I just noticed that tera sanitizes all slashes (`/`) to `&#x2F;`, even in URLs. It works anyway, but [this stackoverflow thread](https://stackoverflow.com/questions/1957115/is-a-slash-equivalent-to-an-encoded-slash-2f-in-the-path-portion-of-a) seems to imply that there's a difference between `/` and `&#x2F;`. So is it recommended to use `page.permalink | safe` for links?

**Comment by Keats** [comment]
I do use the `| safe` myself. The issue is that Tera has no concept of a markup safe string so there's no way for Gutenberg to mark it as safe automatically

**Comment by phil-opp** [comment]
Ok, makes sense. Thanks!
