### ISSUE TITLE
Missing Alpine linux in the distribution list

### ISSUE THREAD

**Issue by williamdes** [getzola/zola#1295]
# Documentation issue

https://www.getzola.org/documentation/getting-started/installation/
https://github.com/getzola/zola/blob/master/docs/content/documentation/getting-started/installation.md

:warning: Only available on edge: https://pkgs.alpinelinux.org/packages?name=zola

It moved one month ago from testing into community: https://gitlab.alpinelinux.org/alpine/aports/-/commit/a8d88dedc8692fbe7b3b22a46e4309a4e38a7f2d

## Summary
Missing Alpine linux in the distribution list

## Proposed solution
Add alpine linux and warn that it is only on edge for now

## Details

Test install command line using docker: `docker run --rm -it alpine apk add zola --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community`

Command to document `apk add zola --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community`

### Proposal

![image](https://user-images.githubusercontent.com/7784660/104110264-68d1f000-52d6-11eb-91ce-cfefc232b355.png)

-------

Other question: no docker version ? Need contributions ?

**Comment by Keats** [comment]
Yep, let's add it to the docs

For docker there is https://hub.docker.com/r/balthek/zola that is built automatically on tags.

**Comment by Keats** [comment]
@williamdes can you do a PR?

**Comment by williamdes** [comment]
> @williamdes can you do a PR?

Sure!
Can you assign me this issue?

**Comment by williamdes** [comment]
Just one thought: You could add a github tag to all your repositories that are zola themes, see: https://github.com/search?q=zola&type=topics

This one seems used: https://github.com/topics/zola-theme

**Comment by williamdes** [comment]
Here it is with a bunch of cool things: https://github.com/getzola/zola/pull/1335
