### ISSUE TITLE
[Feature Request] Support Internal Links in Shortcodes

### ISSUE THREAD

**Issue by lukehsiao** [getzola/zola#1296]
# Bug Report

## Environment

Zola version: v0.13.0

## Expected Behavior
Previously, I was using a shortcode that did something like {{ body | markdown | safe }}, and it would correctly parse Internal links like `[Link](@/other_page.md)`. 

## Current Behavior
With v0.13.0, this behavior is broken, and the links that used to work now show
```
Reason: Filter call 'markdown' failed
Reason: Failed to render markdown filter: Error { kind: Msg("Relative link @/other_page.md not found."), source: None }
```
even though `contents/other_page.md` does in fact exist.

## Step to reproduce
Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.

**Comment by Keats** [comment]
I'm a bit surprised it worked... Before 0.13 it was just running pulldown_cmark directly so it shouldn't have known about internal links at all. I'll need to bisect to figure out what happened.

**Comment by lukehsiao** [comment]
@Keats Upon further inspection, I'm mistaken. On zola v0.12.2, the internal link is incorrect as well, it just didn't throw an error like it does in v0.13.0. With v0.12.2, the internal link is turned into literally `http://127.0.0.1:1111/example_post/@/other_page.md`, which, as expected, will 404.

So, rather than a bug report, this should be a feature request to support the internal link syntax in this context. I assume this is something to do with the `permalinks` passed to `resolve_internal_links()` when used in this context? 

I've updated the title to frame this as a feature request, but will need your help updating the label.

As a side note, have absolutely loved the new features in v0.13.0! Thank you to you and all the zola contributors!

**Comment by southerntofu** [comment]
Hi @lukehsiao, have you considered using a Markdown shortcode as explained [in the docs](https://www.getzola.org/documentation/content/shortcodes/) instead of a HTML shortcode? I just tried and it works for a simple case. If that doesn't work for you, could you post your templates so we can try to see what's wrong, and maybe find a workaround?

In any case, if i understand well we would like the markdown filter in the templates to support internal links, which requires inheriting the rendering context (for the `permalinks`) instead of rebuilding it from config like MarkdownFilter::filter() does? However the markdown filter is registered only once for the site so i have no idea how to do this. Any ideas @Keats ?

**Comment by lukehsiao** [comment]
Hmmm, I could explore that. I'm using an HTML shortcode because I'm using it as a caption. The template is this:

```
<figure {% if class %}class="{{ class }}"{% endif %}>
    <a href="{% if link %}{{ link }}{% else %}{{ src }}{% endif %}">
        <img src="{{ src }}" {%- if alt %}alt="{{ alt }}"{% endif %} {%- if border %}style="border:{{ border }}px solid black"{% endif %}/>
    </a>
    <figcaption>
        {% if title %}<h4>{{ title }}</h4>{% endif %}
        {{ body | markdown | safe }}
    </figcaption>
</figure>
```

Where it might be used as

```
{% figure(src="https://example.com/image.jpg") %}
Link to [other page](@/other_page.md). 
{% end %}
```

I'm not sure I can actually replace this with a markdown template.

**Comment by Keats** [comment]
We should be able to pass the permalinks to the `markdown` filter without any issues: the main difference is that we won't be able to check anchors obviously (since we're in the middle of rendering the markdown content, we don't know them all yet).
