### ISSUE TITLE
Feature: allow emoji aliases

### ISSUE THREAD

**Issue by ibotty** [getzola/zola#1297]
I frequently use some emojis that are too long for me to type all the time (and I cannot remember the long name).  It would be great to allow using an alias.  Additionally it could, if the replacement is an emoji itself, skip the lookup and use it as is.

Would you accept such a PR?  I would simply add an optional hash map `emoji_aliases` in the config file (by default empty) that translates the emoji.  It would add one lookup of the (small) hash map to the code path of emoji lookup and possibly a check whether the replacement's first character is in the astral plane.

**Comment by Keats** [comment]
I don't think it's something super common but let's see if many people have the same need
