### ISSUE TITLE
Page content needs <!-- more --> to compile

### ISSUE THREAD

**Issue by williamdes** [getzola/zola#1298]
# Bug Report

## Environment

Zola version: Docker latest

## Expected Behavior
Let me write without `<!-- more -->`

## Current Behavior

```
Filter `markdown` was called on an incorrect value: got `null` but expected a String
```

## Step to reproduce

Using https://github.com/schoenenberg/zola-paper

Remove `<!-- more -->` and the blog will not run.

```md
+++
title = "Welcome to my blog !"
date = 2020-01-01
category = "Story"

[extra]
author = "William Desportes"

[taxonomies]
tags = ["story", "other"]
+++

Some text

<!-- more -->
```

**Comment by williamdes** [comment]
And by the way if you remove the date  ```Filter `date` received an incorrect type for arg `value`: got `Null` but expected i64|u64|String``` will be thrown. This is not very user friendly and could be improved ;)

Edit: this is maybe a zola-paper issue ?

Thanks for creating Zola !

**Comment by Keats** [comment]
I think https://github.com/schoenenberg/zola-paper/blob/fe475475e5ca6c8c1cc8b56e1e7b7dc1ec427289/templates/index.html#L17 is the issue `page.summary` is null but it's not markdown anyway, it's HTML already so this filter is not doing anything anyway.
This is a zola-paper issue.

> Thanks for creating Zola !

You're welcome!

**Comment by williamdes** [comment]
Thanks, `<!-- more -->` is "obligatoire" ?

**Comment by Keats** [comment]
No, only in that template it somehow seems the summary is required but to be honest there is a if statement around so it should be ok without. In practice `<!-- more -->` isn't required by Zola itself, `page.summary` only gets filled if there was one.
