### ISSUE TITLE
crash when using a theme that doesn't exist

### ISSUE THREAD

**Issue by 2mol** [getzola/zola#1299]
# Bug Report

Zola panics when I make a mistake for the theme in config.toml. Here is the error message:

```
thread 'main' panicked at 'no entry found for key', components/rendering/src/markdown.rs:230:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Environment

Running `zola serve` locally.

Zola version: 0.13.0

## Expected Behavior

Don't crash, show error that theme doesn't exist.

## Current Behavior

Crash.

## Step to reproduce

Enter a non-existing theme in config.toml and run `zola serve`

**Comment by southerntofu** [comment]
Fixed in #1307
