### ISSUE TITLE
Add more shortcodes

### ISSUE THREAD

**Issue by Keats** [getzola/zola#130]
- [ ] Twitter
- [ ] Instagram

**Comment by iJos** [comment]
I'm trying to add more shortcodes, but they are being ignored.
I'm placing them in templates/shortcodes folder (_shortcode_.html) and calling them from the page .md file.

Am I missing something?

**Comment by Keats** [comment]
Was this a shortcode without arguments? I just noticed and fixed a bug after seeing your message in the regex where shortcodes with no arguments were ignored: https://github.com/Keats/gutenberg/commit/ca5bdc8f3c6ccb600fd5d40128bce4b8bb60949f

**Comment by iJos** [comment]
No, I have 1 required argument and some optionals (like the youtube shortcode)

**Comment by brainstorm** [comment]
I know @Keats [does not want to add to the internal shortcode collection](https://github.com/getzola/zola/issues/1758#issuecomment-1036069113), but this one might be useful for a few folks looking support for twitter... at its most basic oEmbed level (place under ./templates/shortcodes/tweet.html and call accordingly via `tweet(url="")` in your posts):

```html
<!-- As suggested on https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/set-up-twitter-for-websites -->
<!-- TODO:
            1) Add all the alignment/color modifiers in the conditional templating
            2) Handle the case where uBlock origin is in action: instead of showing just a link, perhaps fetch some small portion of the content?
-->

<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>

<div {% if class %}class="{{class}}"{% endif %}>
    <blockquote class="twitter-tweet"><a href="{{ url }}"></a></blockquote>
</div>
```
