### ISSUE TITLE
balthek/zola "latest" is not up to date

### ISSUE THREAD

**Issue by williamdes** [getzola/zola#1301]
```
docker run --name blog.williamdes.eu --rm -it balthek/zola --version
```
```
zola 0.7.0
```

That made me waste some time running after my feed not working because of https://github.com/getzola/zola/blob/master/CHANGELOG.md#breaking-1

The latest tag was not updated for 2 years..
Bug somewhere ;)

See: https://hub.docker.com/r/balthek/zola/tags?page=1&ordering=last_updated
![image](https://user-images.githubusercontent.com/7784660/104329208-fb4bdc80-54ec-11eb-932c-4c08c5d78acb.png)

**Comment by williamdes** [comment]
Also on 0.7 there was feeds by tags: https://github.com/wdesportes/blog.williamdes.eu/commit/552213effb78bd907b6fe3c7af3398815554cd71
How can I enable that back ?

**Comment by Keats** [comment]
I've removed the latest tag from docker hub, it's better to be explicit anyway.

For the feeds. you need to set feed = true. See https://www.getzola.org/documentation/getting-started/configuration/ and search for taxonomies for an example.

**Comment by williamdes** [comment]
> I've removed the latest tag from docker hub, it's better to be explicit anyway.
> 
> For the feeds. you need to set feed = true. See https://www.getzola.org/documentation/getting-started/configuration/ and search for taxonomies for an example.

Thank you, I renamed my config to match the good naming:  https://github.com/wdesportes/blog.williamdes.eu/commit/274411947565cac4a1f162ccfbf01aa4f7795f9c

Perfect then for the "latest" tag, I did not find any code occurrences so I assume it should be part of #1295 to add the example for a Docker usage.
