### ISSUE TITLE
Inconsistent inheritance when mixing include and blocks

### ISSUE THREAD

**Issue by posiczko** [getzola/zola#1303]
# Bug Report

## Environment

Zola version:

`0.13.0`

## Expected Behavior

Not 100% if this is Zola or Tera issue, or whether this is how include tags work.

When I create a partial that's included in parent html and that partial contains a block, that block is _not_ being overridden
when in a child overrides it:

1. I create a `base.html` with:
```
<!DOCTYPE html>
<html>
  {% include "header.html" %}
</html>
```

2. I create a `header.html` with:
```
<head>
  <title>{% block title %}Title in Header{% endblock title %}</title>
</head>
```

3. I create `article.html` with:
```
{% extends "base.html" %}
{% block title %}
    <title>Article Title</title>
{% endblock title %}
```
## Current Behavior
When rendering `article.html` I expect zola to override `<title>` with `Article Title`. It does not. Not sure if it's a feature due to Tera not passing custom context, or a Zola bug.

## Step to reproduce
See above.

**Comment by Keats** [comment]
It would be a Tera issue, if you can open it there. That's more a feature request though, right now Tera ignores `include`d templates when doing inheritance.
