### ISSUE TITLE
The Zola 0.13.0 server no longer provides a `content-type` for any files, leaving the browser to guess the type of all files.

### ISSUE THREAD

**Issue by michaellenaghan** [getzola/zola#1308]
# Bug Report

## Environment

Zola version: 0.13.0

## Expected Behavior

* The main page of my site loads an `.svg` file via an `<img>` tag. 
* I just switched from Zola 0.10.0 to 0.13.0. 
* In Zola 0.13.0 the `.svg` file is no longer served correctly.

## Current Behavior

* Zola 0.10.0 served the file with the correct `Content-Type`, `image/svg+xml`. 
* Zola 0.13.0 provides no `Content-Type` for `.svg` files, leaving the browser to guess. 
* Both Chrome and Safari guess `xml` rather than `svg`.

In fact, Zola 0.13.0 no longer provides the `Content-Type` for *any* files, leaving the browser to guess the type of all files.

## Step to reproduce

1. Create a basic site.
2. Add an `svg`-based `<img>` to the site's main page.
3. Serve the site in Zola 0.10.0. The `<img>` is presented correctly.
4. Serve the site in Zola 0.13.0. The `<img>` is not presented correctly.
5. Run `curl -I http://127.0.0.1:1111/<path to svg>` in Zola 0.10.0. Note the presence of a `content-type` header.
6. Run `curl -I http://127.0.0.1:1111/<path to svg>` in Zola 0.13.0. Note the absence of a `content-type` header.

**Comment by Keats** [comment]
Also mentioned in https://zola.discourse.group/t/wrong-mime-type-for-svg-files/751/4

It looks like that the latest hyper upgrade broke it? It shouldn't be too hard to figure it out if someone wants to contribute.

**Comment by michaellenaghan** [comment]
I'm not a Rust developer, but the commit that upgraded `hyper` also changed the way `hyper` was used: https://github.com/getzola/zola/commit/c4260e091db586c9e898aedb7c4f2b1b0e93086e. In particular, it eliminated the use of [`hyper-staticfile`](https://github.com/stephank/hyper-staticfile). 

* I see [here](https://github.com/stephank/hyper-staticfile/blob/3a2f1bc3ee7c48a2a02def6fff22127786f87c4d/src/resolve.rs#L3) that `hyper-staticfile` uses a package called [`mime_guess`](https://github.com/abonander/mime_guess).

* I see [here](https://github.com/stephank/hyper-staticfile/blob/3a2f1bc3ee7c48a2a02def6fff22127786f87c4d/src/resolve.rs#L106) and [here](https://github.com/stephank/hyper-staticfile/blob/3a2f1bc3ee7c48a2a02def6fff22127786f87c4d/src/resolve.rs#L123) that `hyper-staticfile` calls `MimeGuess`.

* I see [here](https://github.com/stephank/hyper-staticfile/blob/3a2f1bc3ee7c48a2a02def6fff22127786f87c4d/src/response_builder.rs#L105) that `hyper-staticfile` uses the result of that call to set `CONTENT_TYPE`.

**Comment by Keats** [comment]
Oooh I forgot about that change! I might go back to hyper-staticfile if it's been updated.

**Comment by southerntofu** [comment]
@michaellenaghan Are you happy with the patch that was merged? If so feel free to close the issue, otherwise don't hesitate to provide critical feedback

**Comment by michaellenaghan** [comment]
I'm not a Rust developer, so I can't build and test the change, but after poking around the change certainly *looks* right.

Would you rather that I close this now or after the next release?

**Comment by Keats** [comment]
Leave it open to avoid duplicates

**Comment by southerntofu** [comment]
> I'm not a Rust developer, so I can't build and test the change

If you'd like to try to build it, it doesn't have to be complicated. If you have rust installed on your machine, it's as easy as:

```
# Download the source code into zola folder
git clone https://github.com/getzola/zola
# Go into zola folder
cd zola
# Check out the latest developments
git checkout next
# Build the source code (to target/release/zola)
cargo build --release
# Copy the program somewhere you will be able to access it
cp target/release/zola /PATH/TO/zola
```

Where `/PATH/TO/zola` is the full path to where zola should be installed. On most platforms, `/usr/local/bin/` will be a good place. Note these commands only work on UNIX-based systems (including macOS), so if you're running windows you'll have to dig into it or wait for the next release :)

> Leave it open to avoid duplicates

makes sense

**Comment by nivram80** [comment]
I'm running into the same issue on Chrome 88 and Safari 14.0.2.  Based on my situation it looks like Chrome and Safari are assuming `text/plain` when the `content-type` is not set for `svg`s.  Firefox renders them correctly by assuming it is a `svg`.

**Comment by Keats** [comment]
It should be fixed in the `next` branch

**Comment by lf-** [comment]
there is a remaining bug on `next` where feeds that are generated in-memory such as rss.xml and atom.xml are served with a content-type of text/html and should be served with an xml content-type so they get rendered structurally by the browser (and thus are easier to verify)

**Comment by Keats** [comment]
Good point

**Comment by U-C-S** [comment]
Think I just got this issue in v0.13 when using Javascript modules during `zola serve`

Error: `failed to load module script: expected a javascript module script but the server responded with a mime type of "". strict mime type checking is enforced for module scripts per html spec.`

So, I tested it with **next-build**. It's Fixed thankfully

**Comment by Keats** [comment]
XML is not handled correctly in `next`

**Comment by Mazwak** [comment]
I just hit this problem. Took a while to understand it was Zola.

Could you port the patch to 0.13 and release a minor version please ?

I tried to install next with cargo install, but it fails to update submole sublime-jinja2

**Comment by kuon** [comment]
Yeah, this issue breaks things like service worker when working with dev server, also took me a while to understand what was going on.

My current work around it so server the public folder with `http` (`cargo install https`) and run `zola build` with `fswatch`.

**Comment by Keats** [comment]
> I tried to install next with cargo install

You will need to clone the repo and `cargo build --release`. I'm not sure about releasing a 0.13.1, there are others bugs in 0.13 and I can't backport all the fixes
