### ISSUE TITLE
Extra syntax conflict

### ISSUE THREAD

**Issue by tatref** [getzola/zola#1309]
# Bug Report
When defining `extra_syntaxes` in `config.toml`, standard highlighters no longer work.

## Environment
Zola version: 0.13, also tested master and next branches (2021-01-14).

This was working with the next branch some days ago (not sure about the exact date though..)

## Step to reproduce
Test article. `py3` is a standard language. `shell-session` is a custom language, defined in `syntaxes/shell-session.sublime-syntax`

    +++
    title = "highlight"
    slug = "highlight"
    
    date = 2099-01-01
    
    draft = true
    
    [taxonomies]
    tags = ["test"]
    +++
    
    ```py3
    python = "python"
    ```
    
    ```shell-session
    $ echo shell
    ```

1st test case: here I set `extra_syntaxes` in cargo.toml:

    [markdown]
    extra_syntaxes = ["syntaxes"]
    highlight_code = true

Result:
![image](https://user-images.githubusercontent.com/2582791/104659132-68fe3100-56c4-11eb-9485-49e4e241a401.png)

Note that the python code is node highlighted, that's the issue

2nd test case: `extra_syntaxes` is commented:

    [markdown]
    #extra_syntaxes = ["syntaxes"]
    highlight_code = true

![image](https://user-images.githubusercontent.com/2582791/104659200-816e4b80-56c4-11eb-8aea-fdd3627e27ba.png)

The python code is now properly highlighted.

If you want to reproduce, here is the `shell-session.sublime-syntax` (disclaimer: it's just a quick and dirty hack...)

    %YAML 1.2
    ---
    file_extensions:
      - shell-session
    scope: source.test
    
    contexts:
      main:
        - match: "^((?:\\(.*?\\) )?[^ ]*(?:\\$|#|>))( .*)?"
        #           ^^^^^^^^^^^^^^ python venv
        #                          ^^^^ user@hostname
        #                               ^^^^^^^^^^^^ last prompt character
        #                                           ^^^^^ command
          captures:
            1: constant.prompt
            2: keyword.command

**Comment by Keats** [comment]
Looks like the extra -> default syntax fallback is not working well

**Comment by southerntofu** [comment]
@tatref what do you think of [this patch](https://github.com/southerntofu/zola/commit/92e74522898856c3e7e130141d3cacaf0459e046) instead? 

I think the logical error was there: when there are some extra syntaxes, only those were looked up, not the theme.

**Comment by southerntofu** [comment]
unrelated, but there seems to be some hardcoded `config.markdown.extra_syntaxes` which could lead to unexpected issues like #1299. i'd be happy to fix those hardcoded paths (until removal of config.extra_syntaxes) on my branch there if it can help

**Comment by tatref** [comment]
Yes, your patch is semantically more correct.

Something else related to highlighting: what do you think about emitting warnings is the language is not found? (so if fallback to plaintext)

**Comment by southerntofu** [comment]
> Yes (...) emitting warnings

Ok i opened #1312 with such warnings. What do you think?

> unrelated, but there seems to be some hardcoded

My bad it looks OK actually :)

**Comment by tomholford** [comment]
Was able to checkout and build the `next` branch and successfully serve a site that has an `extra_syntaxes` key in the config 👍 

edit:
@Keats Are there any plans to ship `next` as `0.13.1` or `0.14.0`?

**Comment by Chaostheorie** [comment]
@tomholford see #1529
