### ISSUE TITLE
test-case v1.0.1 and v1.1.0 released

### ISSUE THREAD

**Issue by protoCall7** [getzola/zola#1314]
While I was putting together the OpenBSD package for test-case, I noticed that both test-case v1.1.0 and v1.0.1 have been released. The OpenBSD ports system is set up to fetch all crates from crates.io (not github commits), so I bumped the version of test-case to v1.1.0 when it was released to enable the build to complete.

Since then, v1.0.1 has been tagged. This tag only fixes the issue that was causing it to be held at a specific commit, and is missing a few features that were released with v1.1.0:

https://github.com/frondeus/test-case/issues/62#issuecomment-758581709

@Keats for Zola v0.13.0 should the package be pulling in test-case v1.0.1 or test-case v1.1.0?

**Comment by Keats** [comment]
I think just v1.0.1 is ok, the issue was it not building due to some syn exports.
