### ISSUE TITLE
Docker image: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by src386** [getzola/zola#1319]
It seems like it is currently not possible to build any Docker images `FROM balthek/zola`.

Dockerfile:
```
FROM balthek/zola:0.13.0 AS builder
COPY . .
RUN zola build

FROM nginx:latest
COPY --from=builder /workdir .
```

Build:
```bash
$ docker build -t mycustomimage .
Sending build context to Docker daemon  73.65MB
Step 1/5 : FROM balthek/zola:0.13.0 AS builder
 ---> 59e24c2db347
Step 2/5 : COPY . .
 ---> 1bc09f3100c4
Step 3/5 : RUN zola build
 ---> Running in 8b4ab29b3984
OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

The `balthek/zola` image uses `FROM: scratch`as a base layer : https://github.com/getzola/zola/blob/9444b920d2e5a1bb3943edb49a71003c0020774c/Dockerfile#L19 so there is no shell, no binary, nothing except `zola`. It is possible to use `docker run` with volume mounts to execute `zola`, but it is currently not possible to build another image based on `balthek/zola`.

**Comment by src386** [comment]
Workaround:
```
FROM debian:buster-slim
COPY --from=balthek/zola:0.13.0 /usr/bin/zola /usr/bin/zola
ADD . .
RUN zola build
```

**Comment by Keats** [comment]
Isn't that the point of a Docker image for a specific tool? The leanest possible and you can still `COPY` if needed.

**Comment by src386** [comment]
> Isn't that the point of a Docker image for a specific tool? The leanest possible and you can still `COPY` if needed.

IMO `scratch` based images are a pain because it makes troubleshoot harder when something does not work.

The workaround is good enough for me so I will close this issue.

**Comment by oleastre** [comment]
For info, there is now an example how to use the zola image in a multi stage build without any work around.
