### ISSUE TITLE
Multi-dimensional/arrays of arrays as shortcode parameters?

### ISSUE THREAD

**Issue by colinkiama** [getzola/zola#1320]
What's the viability of adding multi-dimensional arrays being used as a shortcode parameter type?

Or at least dictionary/map types being supported as parameters?

**Comment by Keats** [comment]
Multi-dimensional arrays should be easy to add. I dont think we want to add map definitions in shortcode parameters though

**Comment by colinkiama** [comment]
Yes, agreed. Multi-dimensional arrays will be a very welcomed feature, especially for the project I'm currently working on.

Currently,  I create arrays in front-matter and access them via the page.extra variable.

I would love to contribute code to this feature however my knowledge of rust is zero.

**Comment by Keats** [comment]
Most of the changes will be done in a parser DSL: https://github.com/getzola/zola/blob/master/components/rendering/src/content.pest and a bit in https://github.com/getzola/zola/blob/master/components/rendering/src/shortcode.rs
