### ISSUE TITLE
Secondary language homepage shows primary language homepage

### ISSUE THREAD

**Issue by yhoiseth** [getzola/zola#1322]
# Bug Report

Thank you for Zola.

It is not entirely clear to me whether this is a bug, a missing feature, a documentation problem or me making a mistake.

## Environment

Zola version: 0.13.0

OS: macOS Big Sur 11.1 (20C69)

## Expected Behavior

I see “This is the Italian version of my blog made with Zola.”

## Current Behavior

I see “This is my blog made with Zola.”

## Step to reproduce

Check out https://github.com/yhoiseth/zola-myblog-multilanguage, run `zola serve`, visit http://127.0.0.1:1111/it and look at the heading.

Or do the following:

First, follow the steps on https://www.getzola.org/documentation/getting-started/overview/ (accepting all defaults), up to and including https://www.getzola.org/documentation/getting-started/overview/#home-page.

You now have this website:

<img width="686" alt="Screenshot 2021-01-23 at 20 02 21" src="https://user-images.githubusercontent.com/8469540/105611483-f3761d00-5db5-11eb-8c7a-7146445d6198.png">

Second, add some of the suggested configuration on https://www.getzola.org/documentation/content/multilingual/#configuration (Italian only to keep this example minimal):

```toml
languages = [
    {code = "it"}, # there won't be a feed for Italian content
]
```

Third, copy `templates/index.html` to `templates/index.it.html` and, in the new file, change “This is my blog made with Zola.” to “This is the Italian version of my blog made with Zola.” I think this should work based on https://www.getzola.org/documentation/content/multilingual/#content.

Fourth, restart your server.

Fifth, visit http://127.0.0.1:1111/it and look at the heading:

<img width="686" alt="Screenshot 2021-01-23 at 20 01 44" src="https://user-images.githubusercontent.com/8469540/105611469-dccfc600-5db5-11eb-9583-4c706c737e39.png">

**Comment by southerntofu** [comment]
Hello, i just took a look at your repository and there is no `content` folder. Index page is defined in `content/_index.LANG.md` (or `content/_index.md` for the default language). This is explained in the [multilingual docs](https://www.getzola.org/documentation/content/multilingual/).

There is no such system however for templates. So you cannot have a template per language. Technically, you could do something like `{% include "index." ~ lang ~ ".html" %}`, but this is not usually what we do. We translate content in the `content/` folder, and if some stuff is not loaded from there (some template parts such as a menu), you can use the [trans function](https://www.getzola.org/documentation/templates/overview/#trans) in the templates.

Currently, this `trans` function loads translations from `config.translations.LANG`. However, please be aware this will change a lot in the next zola version, where multilingual support will be greatly improved (this is priority for the next release).

Do you have more questions? I don't believe this is a bug so feel free to close it, and if you need more support, don't hesitate to go to the [forums](https://zola.discourse.group/) and ask around :)

**Comment by yhoiseth** [comment]
Thanks! Using `_index.LANG.md` works well.

**Comment by Propfend** [comment]
> this will change a lot in the next zola version, where multilingual support will be greatly improved (this is priority for the next release).

Trying here to have template `index.fr.html` and still not working. Any solution?

**Comment by Keats** [comment]
> Trying here to have template index.fr.html and still not working. Any solution?

It should be _index.fr.md in your content folder, not the template itself.
