### ISSUE TITLE
zola serve doesn't pick up directory rename

### ISSUE THREAD

**Issue by yissachar** [getzola/zola#1324]
# Bug Report

## Environment

Zola version: 0.13.0 (Windows)

## Expected Behavior
zola serve should pick up a renamed directory and serve it correctly

## Current Behavior
If you rename a directory while zola serve is running it will not pick up the new name of the directory and will continue to serve from the previous name

## Step to reproduce
1. Create a directory with content (e.g. the sample blog)
2. Run zola serve
3. Navigate to the content (e.g. http://127.0.0.1:1111/blog/) and verify it is being served correctly
4. Rename the directory (e.g. blog -> foobar)
5. Navigate to the new location ( http://127.0.0.1:1111/foobar/) and you will get a 404 - the old location will still be serving even though the content has moved
6. Stop zola serve
7. Run zola serve
8. Now the content will show up at the renamed location correctly

Note I see that this was mentioned in the changelog as an improvement way back in 0.5.0: https://github.com/getzola/zola/blob/master/CHANGELOG.md#others. Not sure if this is a regression or some specific case that wasn't handled with the 0.5.0 improvements.

**Comment by Keats** [comment]
Looks like a regression
