### ISSUE TITLE
‘resize_image’ working w/ static path locally but not on netlify deploy

### ISSUE THREAD

**Issue by Ssloto** [getzola/zola#1325]
# Bug Report

Using the shortcode resize_image() works for me locally, with a relative path from the site root pointing to the static dir, e.g. `../static/myImage.jpg`, but I get an image not found error when I deploy this locally. I tried a number of paths to no avail.

## Environment
Netlify

Zola version: 0.1.2

## Expected Behavior

This is similar to the various cans of worms about parsing different paths, but may also be distinct in some way.

I have a macro/template that resizes a large list of images, all of which are stored under /static. Locally, within the for loop, I can add {% set image_path = ‘…/static/’ ~ image_path %}, and we’re able to get the image paths.

I’m currently building with 0.12.2 locally, and have NETLIFY_VERSION set to the same remotely. I added an environment variable so that I could modify the paths for the remote build separately from the local one, but so far everything I’ve tried has failed.

    10:31:35 PM: Reason: Function call ‘resize_image’ failed
    10:31:35 PM: Reason: resize_image: Cannot find path: pa/fallingwater/f-9.jpg

I’ve tried using a leading slash, not using a leading slash, using …/static, and using /opt/build/repo/static/

## Current Behavior
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.

## Step to reproduce
Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.

**Comment by Keats** [comment]
Another issue caused by paths: https://github.com/getzola/zola/issues?q=is%3Aissue+is%3Aopen+unify

I'm not sure why it would work locally but not on netlify though...

**Comment by Ssloto** [comment]
yeah, I've been super confused by it. I can try changing the netlfiy version to the latest / adding the backtrace variable to get more info.

**Comment by Keats** [comment]
I'm using it in https://github.com/getzola/zola/blob/master/docs/templates/shortcodes/resize_image.html and it's hosted on netlify :/

**Comment by Ssloto** [comment]
hmmm... maybe it's an interaction with git lfs? That's the only difference that comes to my mind on how things might be different on the server side for where the images are originally stored.

Are you using lfs for your netlify site?

**Comment by Keats** [comment]
Nope, but is Netlify actually checking out git lfs objects?

**Comment by Ssloto** [comment]
No, actually they're just uploading them elsewhere to their server, and referencing them somehow at build time.

Quote:
`Files tracked with Large Media are uploaded directly to the Netlify Large Media storage service on push, completely bypassing the site build. This saves build time, but also means that the files are not available to tools that process asset files during the build, such as Hugo’s image processing or the gatsby-image plugin. Depending on your needs, you may be able to replace this functionality with Netlify’s image transformation service.`

[Netlify: large-media requirements and limitations](https://docs.netlify.com/large-media/requirements-and-limitations/)

Totally missed that detail when I first setup the large media. 

Thanks for the responses!
