### ISSUE TITLE
Shortcode at start of line breaks Markdown parsing

### ISSUE THREAD

**Issue by xpe** [getzola/zola#1326]
# Bug Report

Using a shortcode at start of a line breaks Markdown parsing.

## Environment

macOS 11.1

Zola version: zola 0.13.0

## Expected Behavior

I expect these two Tera markdown lines to render similarly, except for one word:
* `Oh, {{ hello() }} *Basil*.`
* `{{ hello() }} *Basil*.`

## Current Behavior

`Yes, {{ hello() }} *Basil*.` correctly becomes `<p>Yes, hello <em>Basil</em>.</p>`.

However, `{{ hello() }} *Basil*.` becomes ` hello *Basil*. `. Note the Markdown was not processed -- as seen by the unprocessed asterisks and lack of `<p>` tag.

## Step to reproduce

Put the above lines in a Zola Markdown file.

Create a file named `/templates/shortcodes/hello.html` with the contents `hello`.

**Comment by Keats** [comment]
Ah that's a tricky one.
Basically when having the shortcode at the start of the line, it is converted to `<pre data-shortcode>hello</pre> *Basil*.` and since it starts with HTML it will not start a paragraph.

I'm not entirely sure how to fix that right now.
