### ISSUE TITLE
Store Sass generated files with Hash as Filename

### ISSUE THREAD

**Issue by vbrandl** [getzola/zola#1328]
It would be a cool feature to store Sass generated files using the hash of the file contents as a filename like `e5fa44f2b31c1fb553b6021e7360d07d5d91ff5e.css` or maybe `<filename>.<hash>.css`. This way you could cache `css` assets for all time in the browsers and don't have to care about invalidating the cache.

This would require some mechanism to get the hashed filename in the template in a dynamic fashion. Maybe a macro `hashed_filename(name = foo.css)` would be enough?

**Comment by Keats** [comment]
It already exists, but not as part of the filename: https://www.getzola.org/documentation/templates/overview/#get-file-hash
It's also built-in the `get_url` function: https://www.getzola.org/documentation/templates/overview/#get-url with the cachebust argument.

**Comment by vbrandl** [comment]
This solves the second part of my request but would it be possible to generate CSS files from sass with the hash in the filename?

Also a kinda off topic question concerning one example of the `get_file_hash` macro:

```
<script src="{{ get_url(path="js/app.js") }}"
        integrity="sha384-{{ get_file_hash(path="js/app.js", sha_type=384) }}"></script>
```

My understanding is, that the `integrity` attribute ensures that resources (e.g. from a CDN) are actually the resources, the author of the document intended, since the CDN could in theory replace the file with malicious code. What kind of attacks can be mitigated by using the `integrity` attribute for files on the same server? When visiting a website, you are already kinda trusting the server owner not to serve you malicious code. If the server owner wanted to, she could just replace `app.js` and the `integrity` value...

**Comment by Keats** [comment]
Putting it as part of the query param does the cache invalidation already, I don't think there will be a method to make it as part of the filename.

> When visiting a website, you are already kinda trusting the server owner not to serve you malicious code. If the server owner wanted to, she could just replace app.js and the integrity value...

Sure but do you trust the ISP or a CDN to not replace the files? https://en.wikipedia.org/wiki/Subresource_Integrity

**Comment by vbrandl** [comment]
Is there a reason, why the `cachebust` argument for `get_url` only works for non-internal resources?

**Comment by TonioGela** [comment]
+1 on this
