### ISSUE TITLE
serve: MIME type of CSS and SVG files

### ISSUE THREAD

**Issue by behnam** [getzola/zola#1331]
# Bug Report

## Environment

Zola version: 0.13.0

## Expected Behavior
Not get this warning in the Chrome console:
```
Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://127.0.0.1:1111/site.css".
```

Also, get SVG files served as `image/svg+xml`, so that they get rendered when used with HTML `img` tag.

## Current Behavior
HTTP-Header mime-type for CSS files cause the warning.

SVG Images do not get rendered b/c of the improper mime-type.

## Step to reproduce
It should be easy to test with any site with CSS and SVG files.

**Comment by behnam** [comment]
Fwiw, both of these (CSS and SVG) used to be served with proper mime-types on 0.12.2.

**Comment by Keats** [comment]
Its already fixed in the `next` branch.
