### ISSUE TITLE
Cannot split string, except with pattern

### ISSUE THREAD

**Issue by southerntofu** [getzola/zola#1334]
Not sure if that's exactly a feature a request or a bug. That's related to tera, but since the usecase is definitely related to zola i thought to open a ticket here.

I have some very long strings to display, preceded by an image. I would like to introduce [wbr tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) within the string to give browser hints they should introduce line breaks within this word, instead of between the image and the start of the string.

Why i opened a bug:

- `slice` filter does not accept strings
- `for` loop does not iterate on strings
- `split` only takes a pattern, and cannot split at a given position

So unless i'm missing something it's technically impossible for me to do that just yet. It may be qualified as a feature request, but i tend to consider it's a bug because &str is a string slice, so slicing/iterating should be supported. Let me know if i should relabel the ticket or bring my concerns elsewhere (eg. tera).

**Comment by Keats** [comment]
Let's move the issue to Tera since it's not related to Zola.
