### ISSUE TITLE
Tables data in [extra] keeps its order in _index.md but not in config.toml 

### ISSUE THREAD

**Issue by yaymalaga** [getzola/zola#1338]
# Bug Report

## Environment

Zola version:
Zola version: 0.13

## Step to reproduce
I was just displaying a list of values from [extra], using a for loop in a template:
```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    {% for i,j in section.extra %}
        <h1>{{i}}</h1>
        <p>{{j}}</p>
    {% endfor %}
</body>

</html>
```

If you declare these values on a **_index.md** file, you will see a list in the exact same order as declared below:
```
+++
template = "test.html"
title="test"

[extra.x]
data = "x"
[extra.y]
data = "y"
[extra.a]
data = "a"
[extra.b]
data = "b"
+++
```

However, if you declare the sames values directly in **config.toml** and you change the for to ```{% for i,j in config.extra %}```, you will get a random order each time you serve the page.

## Expected Behavior
I was expecting the exact same behavior when accessing the [extra] data from both config.toml and _index.md, as at the end of the day I was using the TOML syntax in both files.

## Current Behavior
In one case the elements always keep the declaration order while in the other it is totally random.  Ideally, I would like the order to be kept in both scenarios.

**Comment by Keats** [comment]
That's an easy one if someone wants to contribute: just look at how page/section frontmatter handle the extra field and reproduce it for the config.

**Comment by yaymalaga** [comment]
I can take a look to it :)

**Comment by yaymalaga** [comment]
The main difference is that in page/section the extra value is a Map<String, Tera::Value> while in config it is a HashMap<String, Toml::Value>. The former is defined by serde_json and it has a property for preserving order (#[cfg(feature = "preserve_order")]), which explains the current behaviour. 

However, I had some issues for changing the HashMap in config to a Map, as all the default impl are generated for Map<String, Tera::Value> and we would need to keep using Toml::Value because of the as_table() calls made inside the merge() function.

Do you have any ideas about how to continue here?

**Comment by Keats** [comment]
Ah it's not as easy as I thought then. I'll have a look when I have some time to check what needs to be done.

**Comment by yaymalaga** [comment]
Well, to be fair it seems that the [table section in TOML specification ](https://toml.io/en/v1.0.0#table) warns that "Key/value pairs within tables are not guaranteed to be in any specific order.".

Therefore, if we want the order to be preserved, we should use Array of Tables, so the previous example would be converted to:
```
+++
template = "test.html"
title="test"

[[extra]]
data = "x"
[[extra]]
data = "y"
[[extra]]
data = "a"
[[extra]]
data = "b"
+++
```

I tried the array of tables in my local project and both sections/config are now preserving the order as expected. I guess we can close the issue :)
