### ISSUE TITLE
Add completed file tree to overview docs

### ISSUE THREAD

**Issue by bbkane** [getzola/zola#1341]
# Documentation issue

## Summary

The [overview](https://www.getzola.org/documentation/getting-started/overview/) demonstrates how to create a simple blog. If you don't read it carefully, you can get lost as to which files need to be created where.

## Proposed solution

At the end of the overview, include a diagram showing the final directories and files created:

```
$ tree myblog/ -F
myblog/
├── config.toml
├── content/
│   └── blog/
│       ├── _index.md
│       └── first.md
├── sass/
├── static/
├── templates/
│   ├── base.html
│   ├── blog-page.html
│   ├── blog.html
│   └── index.html
└── themes/
```

Also consider adding the completed site in a new "examples" directory in the zola Git repo.

I'm happy to make a PR for this if you think it's a good idea

**Comment by Keats** [comment]
Go for the docs update. I don't think i want the example in the repo itself though.
