### ISSUE TITLE
Can't find shortcode when parsing string with markdown filter

### ISSUE THREAD

**Issue by hannobraun** [getzola/zola#1350]
# Bug Report

## Environment

Zola version: 0.13.0

## Expected Behavior

In a template, I'm trying to parse a string that contains a shortcode as markdown and insert it into the page:
```
{{ section.extra.header | markdown | safe }}
```

I expect this work like it would with normal section/page content.

## Current Behavior

I get an error that the shortcode isn't found:
```
Failed to build the site
Error: Failed to render section '/home/hanno/Projects/braun-embedded/braun-embedded.com/content/_index.md'
Reason: Failed to render 'index.html'
Reason: Filter call 'markdown' failed
Reason: Failed to render markdown filter: Error { kind: Msg("Failed to render testimonial shortcode"), source: Some(Error { kind: Msg("Tried to render `shortcodes/testimonial.html` but the template wasn\'t found"), source: None }) }
```

I did some digging and I think this line is the culprit: https://github.com/getzola/zola/blob/def95886fb086261a7218e9d5b9f92d71d27f68c/components/templates/src/filters.rs#L22

This call creates a `RenderContext` with a default `Tera` instance, which doesn't know anything about Zola's templates.

For comparison, here's how `Site` creates its `Tera` instance: https://github.com/getzola/zola/blob/def95886fb086261a7218e9d5b9f92d71d27f68c/components/site/src/lib.rs#L83

This requires a path though, and that isn't available in `MarkdownFilter`. I'll do some more digging, maybe I can find a way to fix this.

## Step to reproduce

1. Add a string containing Markdown with a reference to a shortcode to a section's frontmatter, under `[extra]`. Presumably it works the same with a page, but I haven't verified this.
2. In the section's template, try to parse that string using the `markdown` filter.
3. You should see the error when building the page.

**Comment by hannobraun** [comment]
Okay, I got a fix. Preview here: https://github.com/hannobraun/zola/tree/filter-shortcode

Unfortunately I made my changes against `master`, not `next`, and my changes conflict with the changes there. I'll figure that out next week and will open a pull request then.

**Comment by hannobraun** [comment]
@Keats I think this issue needs a `done` label, according to `CONTRIBUTING.md`.

**Comment by pkgw** [comment]
I have a follow-up question about this change. I'm passing some text into the `markdown` filter and invoking a shortcode named `ulink`, which invokes the function `get_url`. It's causing this error:

```
Reason: Filter call 'markdown' failed
Reason: Failed to render markdown filter:
  Error { kind: Msg("Failed to render ulink shortcode"), source: Some(
    Error { kind: Tera(Error { kind: Msg("Failed to render \'shortcodes/ulink.html\'"), source: Some(
      Error { kind: FunctionNotFound("get_url"), source: None }) }), source: None }) }
```

Does this `get_url` failure relate to the way that the current rendering context isn't available to the `markdown` filter, as mentioned in the docs modified in #1358?

If so, I'll note that the error message is not super helpful ... but I know that these things are tricky to wire up, and from a quick skim of #1358 it looks like maybe this system will be seeing some bigger changes anyway.

**Comment by Keats** [comment]
The Tera error chaining is not great indeed!

> Does this get_url failure relate to the way that the current rendering context isn't available to the markdown filter, as mentioned in the docs modified in #1358?

Kinda, right now we are not passing any of the Tera functions to the markdown filter. We could pass the ones that don't require the content to the `markdown` filter to support functions in shortcodes, it's just that no one has requested it so far.
