### ISSUE TITLE
Bibtex not converted

### ISSUE THREAD

**Issue by netzdoktor** [getzola/zola#1354]
# Bug Report

## Environment

Zola version: 0.13.0

## Expected Behavior
The bibtex should be converted to JSON and accessible using, e.g., `data.bibliographies[0].tags` as stated in the documentation.

## Current Behavior

Currently, the `data` is output verbatim and if using data access with `.`, the build fails.

## Step to reproduce

Consider the documentation example: https://www.getzola.org/documentation/templates/overview/

Use the bibtex from there and put it into `content/publications.bib`:

```bibtex
@preamble{"A bibtex preamble" # " this is."}

@Comment{
    Here is a comment.
}

Another comment!

@string(name = "Vincent Prouillet")
@string(github = "https://github.com/getzola/zola")

@misc {my_citation_key,
    author= name,
    title = "Zola",
    note = "github: " # github
}                                                    }
``` 

In `templates/index.html` put:

```html
{% set data = load_data(path="content/publications.bib", type="bibtex") %}
{% set tags = data.bibliographies[0].tags %}
This was generated using {{ tags.title }}, authored by {{ tags.author }}.
```

 `zola serve` fails with:

```sh
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
Error: Failed to render section 'C:/Data/Personal/netzdoktor.eu/content/_index.md'
Reason: Failed to render 'index.html'
Reason: Variable `data.bibliographies[0].tags` not found in context while rendering 'index.html': the evaluated version was `data.bibliographies.0.tags`. Maybe the index is out of bounds?
```

**Comment by Keats** [comment]
cc @rmsc

**Comment by rmsc** [comment]
I can confirm that indexing isn't working. I'll have a look.

In the meantime, maybe you can work around that by using a for loop:
```
{% for bib in data.bibliographies %}
{% set tags = bib.tags %}
This was generated using {{ tags.title }}, authored by {{ tags.author }}.
{% endfor %}
```

**Comment by rmsc** [comment]
Strangely enough, this works fine:
```
{% set data = load_data(path="content/publications.bib", format="bibtex") %}
{{ data.bibliographies[0].tags.author }}
```

**Comment by rmsc** [comment]
I think I figured it out. Where you have `type="bibtex"`, it should have been `format="bibtex"`. Can you please try it out and report back?

@Keats load_data() accepted `type` as a parameter and did not complain. Perhaps we should test for that somehow?

**Comment by Keats** [comment]
We only validate expected parameters. It would be nice to error on unknown arguments but it isn't super important imo.

**Comment by netzdoktor** [comment]
Thanks a lot @rmsc. The `type` vs. `format` was my mistake, it works now.

What do we do with the other issues you discovered? Shall I close this one?

**Comment by Keats** [comment]
We can close this one. I don't know if the other is something we want to fix yet.
