### ISSUE TITLE
Markdown list combine with shortcode more than 2 lines will break the style

### ISSUE THREAD

**Issue by wdv4758h** [getzola/zola#1355]
# Bug Report

## Environment

Zola version: 0.13.0

## Expected Behavior

Things should render as usual.

## Current Behavior

Assuming we have this markdown file:

```md
* a
* b
    {{ youtube(id="") }}
* c
    {{ youtube(id="") }}
```

With current codebase, the `youtube` shortcode has 3 lines, which cause the parser end the list way too early.

So it generates the HTML like this:

```html
<ul> <li>a</li> <li>b<div > <iframe src="https://www.youtube-nocookie.com/embed/" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> </li> </ul> </div> * c <div > <iframe src="https://www.youtube-nocookie.com/embed/" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> </div> 
```

The `</li></ul>` got insert into the shortcode HTML. This cause a bad HTML that leave a `</div>` from shortcode behind. And that `</div>` will match the `<div>` in upper level. Depends on the base HTML for the page, it breaks following styles in arbitrary ways.

If we get rid of all the new lines in shortcude and convert it to single line, then stuffs won't break. For example, adding `let res = res.replace("\n", "");` to `render_shortcode` function will fix the issue. But I'm not sure if this is the best solution or not.

The problem won't happen if the shortcode template is 1 or 2 lines.

## Step to reproduce

1. write a markdown file like previous section
2. run zola serve to see the page
3. will see the page is not rendered correctly

**Comment by Keats** [comment]
> If we get rid of all the new lines in shortcude and convert it to single line, then stuffs won't break. For example, adding let res = res.replace("\n", ""); to render_shortcode function will fix the issue.

That would break some shortcodes that want to use newlines. The newlines in shortcode <-> Markdown issues is not new and I can't really find a better way than it is currently. It does break for some usecases like your example but works the majority of the time.

**Comment by wdv4758h** [comment]
You are right, some shortcode might want the newlines.

I guess the quickest workaround is to reimplement whatever shortcode I need there as single line.

**Comment by cpg314** [comment]
Sorry to comment on this old issue, but I think this is still a problem:

content/_index.md
```markdown
+++
template = "index.html"
+++

Test

- A
  {{image()}}
- B
- C

```

template/index.html
```html
{{ section.content | safe }}
```

template/shortcodes/image.md
```markdown
<div>
</div>
```

The generated code is:
```html
<p>Test</p>
<ul>
<li>A<div>
</li>
</ul>
</div>
<ul>
<li>B</li>
<li>C</li>
</ul>
```
Note the `</ul>` closing too early.

If the shortcode is put on a single line, like @wdv4758h suggests, then the generated code is correct:
```html
<p>Test</p>
<ul>
<li>
<p>A</p>
<div> </div>
</li>
<li>
<p>B</p>
</li>
<li>
<p>C</p>
</li>
</ul>
```

This is with Zola 0.19.2

**Comment by Keats** [comment]
Can you make a new issue?
