### ISSUE TITLE
Add syntax highlighting support for `sh` and `zsh`

### ISSUE THREAD

**Issue by throwaway1037** [getzola/zola#1369]
https://www.getzola.org/documentation/content/syntax-highlighting/ does not list POSIX-compliant shell (`sh`) or ZSH (the Z shell, `zsh`).

**Comment by Keats** [comment]
It uses the same syntax highlighting as Bash in Sublime, both `sh` and `zsh` are in the `Bourne Again Shell (bash)` syntax declaration.

**Comment by throwaway1037** [comment]
Would it make sense to add them to the supported list, and allow code blocks to begin with them, or is this already implemented?

**Comment by Keats** [comment]
This is already the case

**Comment by throwaway1037** [comment]
The documentation does not list them, this may confuse people. Should I make a pull request adding them?

**Comment by Keats** [comment]
They are listed in the brackets (search for zsh for example). This part of
the documentation is auto-generated so a PR would not help.

**Comment by throwaway1037** [comment]
I think it needs to be explicit in user-facing documentation.

**Comment by Keats** [comment]
It's already listed, I'm not sure what else to do?

**Comment by throwaway1037** [comment]
My fault, the long line did not wrap in my editor.
