### ISSUE TITLE
Add Nim syntax highlight

### ISSUE THREAD

**Issue by andreaferretti** [getzola/zola#137]
A syntax highlight could be added for [Nim](https://nim-lang.org/)

**Comment by Keats** [comment]
Looks like https://github.com/Varriount/NimLime would work, I'll add it tomorrow

**Comment by Keats** [comment]
Looks like the `tmLanguage` cannot be converted to the new syntax automatically so that's not going to be a 10 second work.

**Comment by andreaferretti** [comment]
What kind of syntax format do you need? There is also https://github.com/pragmagic/vscode-nim/tree/master/syntaxes

**Comment by Keats** [comment]
I need a `.sublime-syntax` format, which is the new format ST3 uses

**Comment by Varriount** [comment]
Hm, that's a problem. Unfortunately Github uses the existing syntax file to highlight Nim code throughout their site, so I would need to split the existing highlighter definitions off into another repository.

**Comment by Keats** [comment]
The highlighting done by the `.sublime-syntax` I generated looks decent so I think I'll ship this one for now
