### ISSUE TITLE
Add GFM support

### ISSUE THREAD

**Issue by throwaway1037** [getzola/zola#1371]
[GitHub Flavored Markdown](https://github.github.com/gfm/) (GFM) is an extended version of markdown with a minimal number (5) of genuinely useful extensions. I often use these extensions and think it would be useful to have an option in Zola to enable them, whilst keeping CommonMark the default for backwards compatability and speed (I presume processing GFM is marginally slowed than processing CommonMark).

**Comment by Keats** [comment]
Pulldown-cmark implements some of the GFM extensions (enabled in Zola):

> Further, it optionally supports parsing footnotes, Github flavored tables, Github flavored task lists and strikethrough.

**Comment by throwaway1037** [comment]
The documentation (from what I've read) only states CommonMark support so I think it needs updating.

**Comment by southerntofu** [comment]
@throwaway1037 You're welcome to improve the documentation but if a specific feature of GFM is missing for you don't hesitate to comment here! :)

**Comment by throwaway1037** [comment]
I will ask upstream about GFM support.

**Comment by Keats** [comment]
Closing as it's more a pulldown-cmark request than Zola.
