### ISSUE TITLE
How to dump __tera_context in macros?

### ISSUE THREAD

**Issue by tempbottle** [getzola/zola#1372]
Can not dump `__tera_context` in macros. 

This code work in index.html template, but not work in macros:
```jinja
{% if config.extra.dump_tera_context %}
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', () => {
  var text = {{ __tera_context }};
  console.log(text);
});
</script>
{% endif %}
```

Neither do this:
```jinja
{% macro dump_var() %}
<!-- we can't dump {{ __tera_context }} in macros -->
{% if config.extra.dump_tera_context %}
{{ __tera_context }} 
{% endif %}
{% endmacro dump_var %}
```

**Comment by Keats** [comment]
It looks like it works as expected? `__tera_context` dumps the current context and in that macro it's empty

**Comment by tempbottle** [comment]
Oh, `__tera_context` is empty in macros.
 I just want a view component, something like `debug::dump_var()`, that can reuse in every html template. Is there anyway for this?

**Comment by Keats** [comment]
> Oh, __tera_context is empty in macros.

No, it's just that macros do not share the rendering context, they only get their variables. As this macro doesn't have any arguments, the context is empty.

**Comment by tempbottle** [comment]
OK,  for passing named arguments, this code works for me.

in *.html template:
```jinja
{% import "debug_macros.html" as debug_macros %}
.....
{% if config.extra.dump_tera_context %}
{{ debug_macros::dump_var(ctx=__tera_context) }}
{% endif %}
```

and in debug_macros.html:
```jinja
{% macro dump_var(ctx) %}
{{ ctx }} 
{% endmacro dump_var %}
```
