### ISSUE TITLE
Versioning the documentation

### ISSUE THREAD

**Issue by southerntofu** [getzola/zola#1374]
Currently the documentation at getzola.org is only for the latest released version. To my knowledge, there is no simple way to access documentation for a previous version and/or documentation for the next branch.

Could we maybe version the documentation into different subsections, with a `latest` symlink linking to always the latest public version? This way we could have documentation published from the next branch:

- `/documentation/next` contains documentation for the upcoming release
- `/documentation/latest` contains documentation for the current release
- `/documentation/v0.13.0` contains documentation for version 0.13.0
- etc..

This would allow:

- people who use an old version (for backwards-compatibility) or because they distribution's package hasn't been updated yet to have documentation about their version without having to build it themselves
- links on every documentation page for the same page across releases (for the last N releases)
- links to the repository for a diff view between specified version and latest/next

So during the release process, we would just `cp -R docs/content/documentation/{next,v0.14.0};ln -sf docs/content/documentation/{v0.14.0,latest}`

Is it a good idea?

**Comment by Keats** [comment]
I only want to have the latest version of the docs online.
We don't do huge amounts of breaking changes in each release so the docs would be 99% identical and I *want* people to use the latest version. Most of the current documentation changes are clarifications and improvements which helps everyone.
