### ISSUE TITLE
zola build --output-dir Document Deleting Behavior

### ISSUE THREAD

**Issue by gatoWololo** [getzola/zola#1378]
# Documentation issue

## Summary
`zola build` has a helpful `--output-dir` flag. However the documentation from the `--help` command:

> -o, --output-dir <output_dir>    Outputs the generated site in the given path [default: public]

Doesn't make it clear that the target directory contents will be deleted. I accidentally wiped out my entire Zola project by specifying `--output-dir ../ZolaProject/`. (Thankfully it was all saved on Github). 

## Proposed solution
- Document fact flag will delete contents of target directory.
- Maybe if target directory is something other than `public/` give a warning if the directory is non-empty?

**Comment by Keats** [comment]
It is documented in the `zola build` command:

```
zola-build 
Deletes the output directory if there is one and builds the site
```

since it's a behaviour of zola build/server and not the flag

**Comment by gatoWololo** [comment]
Agh, I see it now. Thanks for pointing it out. Admittedly, I skipped reading the command description.

**Comment by southerntofu** [comment]
> I skipped reading the command description.

It's also happened to me before, and that was annoying! I'm not sure performing a destructive operation by default is a good ideas. Some notes:

- now that `serve` doesn't write HTML pages to public/ anymore, maybe we could use a temp folder instead of basedir/public/ so we don't override the wrong folder by mistake? (public/ was useful for debugging output paths but since we can't do it anymore..)
- build command could by default not override things, and have an additional flag or config setting to delete the output folder

**Comment by Keats** [comment]
> now that serve doesn't write HTML pages to public/ anymore, maybe we could use a temp folder instead of basedir/public/ so we don't override the wrong folder by mistake? (public/ was useful for debugging output paths but since we can't do it anymore..)

It would make debugging assets harder :/

> build command could by default not override things, and have an additional flag or config setting to delete the output folder

Maybe only add a warning/confirmation when `output-dir` is not the default? I do want the default `zola build` to delete the public folder, otherwise you can end up with tons of crap.

**Comment by gatoWololo** [comment]
> Maybe only add a warning/confirmation when output-dir is not the default?

This would be good I think. Or at least add that the target directory will be deleted to the flag description.

**Comment by Be-ing** [comment]
I got confused by this behavior because it deleted the build directory's `.git` subdirectory.

**Comment by Be-ing** [comment]
Thanks for fixing this @coastalwhite!
