### ISSUE TITLE
Failed to build zola with released code of v0.13

### ISSUE THREAD

**Issue by CliffHan** [getzola/zola#1379]
When I tried to build zola 0.13, I met 2 problems. My cargo/rustc is v1.49.

1. According to https://www.getzola.org/documentation/content/multilingual/#configuration , it tells that I should use `cargo build --features search/indexing-zh` to enable Chinese indexing. So I just tried and got this error:
```
error: package `zola v0.13.0 (/home/cliff/Workspace/zola-0.13.0)` does not have a dependency named `search`
```
I'm not very sure why I got this error. Then I just set indexing-zh feature as default with directly code change in `components/search/Cargo.toml`. Maybe the document need to be updated here.

2. After I enabled indexing-zh feature, I met another compile error:
```
error[E0252]: the name `Deserialize` is defined multiple times
 --> components/utils/src/de.rs:2:5
  |
1 | use serde::{Deserialize, Deserializer};
  |             ----------- previous import of the macro `Deserialize` here
2 | use serde_derive::Deserialize;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ `Deserialize` reimported here
  |
  = note: `Deserialize` must be defined only once in the macro namespace of this module
```
I just removed the error line and build passed.

Not sure if that's because I didn't setup my environment well. Please let me know if I need to do some extra setup for this.
Hope my report could help.

**Comment by CresLeaf** [comment]
I met the same problem, and I add one line to `src/Cargo.toml`:
````
[dependency]
...
search = { path = "components/search" }
````
then it built with nothing wrong
