### ISSUE TITLE
No error if Toml table contains trailing commas

### ISSUE THREAD

**Issue by ad-si** [getzola/zola#1380]
# Bug Report

## Environment

Zola version: 0.13.0

## Expected Behavior

I have a section file like

```txt
 content/
├── faq/
│  └── _index.md
```
 with following content:
 
 ```md
+++
title = "FAQs"

[extra]
faqs = [{ question = "What is this?", }]
+++
```

Since trailing commas aren't allowed in Toml tables, I'd expect to get an error message about it.

## Current Behavior

It simply doesn't build that section, but there is no error message or warning whatsoever.

**Comment by Keats** [comment]
It's an error on the `next` branch
