### ISSUE TITLE
Feature Request: sort section by "updated"

### ISSUE THREAD

**Issue by bbkane** [getzola/zola#1384]
Hello,

https://www.getzola.org/documentation/content/section/#sorting describes how to sort by "date" within a section. pages also have an "[updated](https://www.getzola.org/documentation/content/page/#front-matter)" variable in the front matter that I'd like to sort my section by. Would it be difficult to add that as an option?

**Comment by Keats** [comment]
It looks like it would make more sense to include updated when sorting by date?

**Comment by bbkane** [comment]
I think adding a new keyword ("updated") to sort by make sense because:

- incorporating "updated" into sort by "date" changes what people already have deployed.
- Even if that isn't important (I'm not sure how much people care), I think some people might want to sort strictly by "created" date and others might want to sort by "max(created, updated)" date. 

I feel like it's more clear to folks to give the "updated" page variable a default value of the page "date" (it might already have this?) and then allow sorting  by "updated".  That gives the sort by "max(created, updated)" semantics for people who want it without affecting people who are happy now with the current state.

**Comment by bbkane** [comment]
I'm (very) new to Rust, but if you think this would be easy to implement (whichever implementation you choose), I would be happy to take a stab at it (modulo real life time, which never seems to get less busy...).

**Comment by Keats** [comment]
I think your reasoning makes sense. It should be very easy to implement, go for it!

**Comment by bbkane** [comment]
Great! I'll try to work on it this weekend and set myself some calendar alerts to give progress updates on this issue every week (even if it's no progress/no time to work on it) :) . That'll keep me honest about my ability to actually do this.

**Comment by bbkane** [comment]
OK some thoughts so far:

I used `rustup` to install Stable Rust and installed the Rust extension in VSCode, then uninstalled it and installed the rust-analyzer extension (it seems to be the hip new thing based on Reddit :) ). It shows the following errors, despite the fact that `cargo build` runs just fine (there's also some warnings about the code I'm adding not being used yet, which I expect).

![image](https://user-images.githubusercontent.com/6081085/110259272-a57b3a00-7f5b-11eb-8469-8a420d702bbb.png)

This made me think that I should use nightly rust. `rustup install nightly && rustup default nightly`. That gets rid of some of the errors from rust-analyzer:

![image](https://user-images.githubusercontent.com/6081085/110259361-17ec1a00-7f5c-11eb-8584-5c2260418416.png)

Do you use rust-analyzer / VSCode combo or Rust nightly? I see a sublime folder in the project, but that looks like it might be to embed syntax highlighting within the generated HTML.

**Comment by Keats** [comment]
I use PyCharm, I have never used rust-analyzer. Looks like all the errors on the benches, which I haven't ran in a few changes. Don't worry about those, I'll fix them later.

**Comment by bbkane** [comment]
Ok thanks! It could also be a bug in rust-analyzer I suppose. 

Status update:

I made the changes I thought were necessary at https://github.com/bbkane/zola/tree/sort_by_updated . Then when I tried to make them work on my blog ( `~/Git/zola/target/debug/zola build` ), I got the warning `67 page(s) ignored (missing date or weight in a sorted section):` . Oops. Must have missed something.

So this week/weekend I'm hoping get time to grep for that error or learn to use a debugger well enough to find what's going on. I'm having fun - really feel like I'm learning more Rust despite mostly copy/pasting! If I try those and can't make it work I'll be back to ask for help when you have time. Thanks :)

**Comment by bbkane** [comment]
Status update: no progress. My wife discovered Minecraft and I've been watching her get adorably frightened as she explores caves and adorably delighted as she builds farms and trade with villagers. We're moving today and tomorrow zo next week might be busy as well.

**Comment by bbkane** [comment]
Well... life got busy. I'm going to go ahead and close this, and I'll reopen it if I get time or learn more Rust
