### ISSUE TITLE
[feature request] Option to strip HTML comments from Markdown

### ISSUE THREAD

**Issue by GoldsteinE** [getzola/zola#1386]
I sometimes leave HTML comments in Markdown that are only relevant when reading raw markup. For example:
```markdown
Please, look at this [site].
Other text

<!-- Links -->
[site]: https://example.com
```
I don't want for these comments to be present in resulting HTML. I do want to preserve HTML comments from templates, so stripping them with external tools after HTML is generated is not an option.
It would be cool to have an option like `markdown.strip_comments` to remove Markdown comments from resulting HTML.
Optionally, there could be an option to specify that particular comment should not be removed, like this:
```markdown
<!-- This comment would be removed -->
<!--- This one would be left in HTML -->
```

**Comment by GoldsteinE** [comment]
It seems like it would be easily enough to add here:
https://github.com/getzola/zola/blob/master/components/rendering/src/markdown.rs#L312-L330
I'm willing to implement this change should it be accepted

**Comment by Keats** [comment]
It wouldn't be accepted, it seems like a super niche case where we would change the meaning of CommonMark arbitrarily.

**Comment by Jieiku** [comment]
This works for leaving comments in your markdown and Zola will skip rendering it:
source: https://stackoverflow.com/a/57310297
```


[This is a note/comment to myself in the markdown file, it is skipped during zola build/serve]::
```

Also just found this:

https://zola.discourse.group/t/tera-comments-in-markdown/450
