### ISSUE TITLE
How fast is it compared to other SSG?

### ISSUE THREAD

**Issue by bitcoinvsalts** [getzola/zola#1387]
# Bug Report

## Environment

Zola version:

## Expected Behavior
Tell us what should have happened.

## Current Behavior
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.

## Step to reproduce
Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.

**Comment by Keats** [comment]
Probably slower than Hugo and faster than the JS/Python ones. I haven't benchmarked it against others in a very long time

**Comment by bitcoinvsalts** [comment]
Ok thank you. I wish you the best for your project.
