### ISSUE TITLE
staticDir option to include the static dir within the content dir

### ISSUE THREAD

**Issue by nbari** [getzola/zola#1388]
Hello, sorry if a GitHub issue is not the correct place to raise this.

I want to simplify contributions by only having a repository with the `content` of the site so that if anyone contributing could easily within a single repo upload any static content if required, but for this, I need to have the `static` dir within the  `content` dir.

With other similar tools like `hugo` I can manage to do so by using the `staticDir` option for example:

```
staticDir:
  - content/static
```

For example, the repo could be named `content`, and use a template with a footer that adds something like:

[Suggest edit ✍️]( https://github.com/<project>/content/edit/master/page.md) -> `https://github.com/<project>/content/edit/master/page.md`

Any ideas?

**Comment by Keats** [comment]
It's not going to be supported.
