### ISSUE TITLE
Add deploy page

### ISSUE THREAD

**Issue by Keats** [getzola/zola#139]
Explaining how to deploy to netlify, s3 etc

**Comment by Keats** [comment]
netlify now has `gutenberg` binary available out of the box I believe so it should be easy to test/write

**Comment by ootoovak** [comment]
Hi @Keats, I just tried this out again using the Netlify web interface to set the build command settings [as noted in the docs](https://www.getgutenberg.io/documentation/deployment/netlify/). The deploy failed for me so I have either missed something or Netlify does not have the `gutenberg` binary (anymore?).

Instead I am using `curl -sL https://github.com/Keats/gutenberg/releases/download/v0.3.3/gutenberg-v0.3.3-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./gutenberg build` which seem to work fine. This is more an FYI if you didn't know and/or if anyone else comes across the same issue and needs a fix.

**Comment by Keats** [comment]
@ootoovak what was the error? The tera doc last deploy was 2 days ago and it worked fine

**Comment by ootoovak** [comment]
@Keats sorry it has taken me a very long time to get back to you. I just tried to follow the deploy docs again `GUTENBERG_VERSION=0.4.2 gutenberg build` and still got a deploy failure from Netlify. I even tried to relink the repo in hope that would make a difference. Still no luck.
```
1:54:51 PM: Build ready to start
1:54:54 PM: build-image version: 42bca793ccd33055023c56c4ca8510463a56d317
1:54:54 PM: buildbot version: 15854c92f1b74f9c77ad951b5536193c76eff25e
1:54:54 PM: Fetching cached dependencies
1:54:54 PM: Failed to fetch cache, continuing with build
1:54:54 PM: Starting to prepare the repo for build
1:54:55 PM: No cached dependencies found. Cloning fresh repo
1:54:55 PM: git clone git@gitlab.com:ootoovak/forefrontprojects
1:55:00 PM: Preparing Git Reference refs/heads/master
1:55:02 PM: Starting build script
1:55:02 PM: Installing dependencies
1:55:03 PM: Downloading and installing node v8.12.0...
1:55:03 PM: Downloading https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.xz...
1:55:03 PM: 
#
1:55:03 PM:                 1.6%
1:55:03 PM: #
1:55:04 PM: ############################                                             41.4%
1:55:04 PM: 
############################################
1:55:04 PM: ############################ 100.0%
1:55:04 PM: Computing checksum with sha256sum
1:55:04 PM: Checksums matched!
1:55:06 PM: Now using node v8.12.0 (npm v6.4.1)
1:55:06 PM: Attempting ruby version 2.3.6, read from environment
1:55:07 PM: Using ruby version 2.3.6
1:55:07 PM: Using PHP version 5.6
1:55:07 PM: Started restoring cached go cache
1:55:08 PM: Finished restoring cached go cache
1:55:08 PM: unset GOOS;
1:55:08 PM: unset GOARCH;
1:55:08 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
1:55:08 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
1:55:08 PM: go version >&2;
1:55:08 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
1:55:08 PM: go version go1.10 linux/amd64
1:55:08 PM: Installing missing commands
1:55:08 PM: Verify run directory
1:55:08 PM: Executing user command: GUTENBERG_VERSION=0.4.2 gutenberg build
1:55:08 PM: /usr/local/bin/build: line 32: gutenberg: command not found
1:55:08 PM: Caching artifacts
1:55:08 PM: Started saving pip cache
1:55:08 PM: Finished saving pip cache
1:55:08 PM: Started saving emacs cask dependencies
1:55:08 PM: Finished saving emacs cask dependencies
1:55:08 PM: Started saving maven dependencies
1:55:08 PM: Finished saving maven dependencies
1:55:08 PM: Started saving boot dependencies
1:55:08 PM: Finished saving boot dependencies
1:55:08 PM: Started saving go dependencies
1:55:08 PM: Finished saving go dependencies
1:55:08 PM: Cached node version v8.12.0
1:55:08 PM: Error running command: Build script returned non-zero exit code: 127
1:55:08 PM: Failing build: Failed to build site
1:55:08 PM: failed during stage 'building site': Build script returned non-zero exit code: 127
1:55:08 PM: Finished processing build request in 14.542982039s
```
This might be out of the scope of your project so I'm ok using the old way that worked for me for now `curl -sL https://github.com/Keats/gutenberg/releases/download/v0.4.2/gutenberg-v0.4.2-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./gutenberg build` but I just wanted to report back in case you get the same issue from anyone else.

**Comment by ootoovak** [comment]
BUT!!! Adding the `.netlify.toml` file from the Gutenberg docs to my project did make the deploy work! I wonder if Netlify uses this to identify Gutenberg projects and trigger the install hook for the `gutenberg` binary. 🤔

**Comment by Keats** [comment]
I believe it's because Netlify is looking for env variables but not in the build command itself.
