### ISSUE TITLE
Zola serve doesn't give detailed error information

### ISSUE THREAD

**Issue by lf-** [getzola/zola#1398]
# Bug Report

## Environment

Zola version: next 51644a79e31a9ffaf54c5447c79c13dbc4171c6e

## Expected Behavior

I'd like to get full error details such as when I call `zola serve` and it builds initially, or when I call `zola build`:

```
dev/zlog - [main●] » ~/dev/zola/target/debug/zola serve
Building site...
Error: Error parsing templates
Reason: 
* Failed to parse "/home/jade/dev/zlog/templates/shortcodes/image.html"
 --> 4:25
  |
4 |     <a href="{{ get_url("images/{{ name }}") }}"␊
  |                         ^---
  |
  = expected an identifier (must start with a-z)
```

## Current Behavior

I got this error without details of where exactly it failed.

```
Change detected @ 2021-03-09 01:45:51
-> Template changed /home/jade/dev/zlog/templates/shortcodes/image.html
Error parsing templates
Done in 18ms.
```

## Step to reproduce

Break something in a template while `zola serve` is running, then save. The error message will not include the reason.

**Comment by Keats** [comment]
Looks like the reloaded site need to call the `unravel_errors` function as well.

**Comment by alice-i-cecile** [comment]
For others who encounter this thread: calling `zola build` from scratch will give you much better error messages, which is an extremely helpful workaround.

**Comment by Keats** [comment]
It's fixed in the commit above, will be released this weekend if I don't forget about it
