### ISSUE TITLE
MDX Support?

### ISSUE THREAD

**Issue by karlhorky** [getzola/zola#1399]
Hi there, thanks for this project! Really great to see more movement in the static site generation space!

How do you feel about also supporting [MDX](https://mdxjs.com/), in addition to Markdown? This would allow for inclusion of interactive components in static pages.

**Comment by Keats** [comment]
That doesn't seem doable, we would need to need to ship node and write a MDX parser in Rust as it doesn't exist.

Shortcodes solve the same, but only with template components - no js.
