### ISSUE TITLE
two failing tests when testing on local windows machine, the test work on the build server.

### ISSUE THREAD

**Issue by mtolk** [getzola/zola#1401]
# Bug Report
There are hardcoded strings in 2 testcases: src/comd/init.rs (fn strip_unc_required_test() and strip_unc_test() ).

They reference "C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\new_project".

this will fail when attempting to test the project locally on windows.

## Environment
local windows machine

Zola version:
0.14 next branch

## Expected Behavior
Test should run on any machine. In this case all windows machines not just 

## Current Behavior
running `cargo test --all` fails on my local machine because the temp path used in the tests is hardcoded to work when running tests as VssAdministrator user.

## Step to reproduce
running `cargo test --all`

I tried fixing this by replacing the hardcoded path with `dir.to_str().unwrap().to_string()` however I then start running into issues
with 8.3 short filenames, still causing the tests to fail.

**Comment by Keats** [comment]
I would love some more Windows eyes. https://github.com/getzola/zola/pull/1333 had failing Windows tests as well.

**Comment by mtolk** [comment]
Hi @Keats. I can have a look at #1333 and see what fails on my machine.
