### ISSUE TITLE
Base16 Atelier Dune Light syntax highlighting theme

### ISSUE THREAD

**Issue by tlgs** [getzola/zola#1402]
This is a request to add the `Base16 Atelier Dune Light`  syntax highlighting theme by Bram de Haan - [project site](https://atelierbram.github.io/syntax-highlighting/atelier-schemes/dune/).

See the relevant Sublime Text theme file [here](https://github.com/atelierbram/syntax-highlighting/blob/master/docs/archive/atelier-schemes/output/textmate/base16-atelierdune.light.tmTheme).

For reference, this ~is~ was the deafult theme used by mdBook ([see here](https://github.com/rust-lang/mdBook/blob/master/src/theme/highlight.css)).

**Comment by Keats** [comment]
Shouldn't be hard to add if someone wants to contribute

**Comment by tlgs** [comment]
I went ahead and created a pull request.

It's been a while since I touched a Rust project so I stuck to the Contributing guidelines and looked up other similar PRs; 
let me know if this okay or if I need to alter anything else.
