### ISSUE TITLE
zola serve panicks while serving

### ISSUE THREAD

**Issue by pasniak** [getzola/zola#1407]
# Bug Report

I am new to static generation and so far looked at hugo (which would never exit the serving loop).

## Environment
Zola version: 0.13.0

## Expected Behavior
Catch, report error, and serve waiting for user to fix. Do not force me to restart.

## Current Behavior
```
-> Content changed .......site/content/sections/index.md
thread 'main' panicked at 'error deserialising page: Error { kind: Msg("Couldn\'t find front matter in `......./site/content/sections/index.md`. Did you forget to add `+++` or `---`?"), source: None }', components/site/src/lib.rs:264:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Keats** [comment]
This is fixed in the `next` already

**Comment by pasniak** [comment]
ok, I built `next` it complained on
```
Error: Couldn't find front matter in `........./site/content/sections/_index.md`. Did you forget to add `+++` or `---`?
```
and it was fixed by adding carriage return on the last line (with +++)
