### ISSUE TITLE
Use get_url in css

### ISSUE THREAD

**Issue by rileyshahar** [getzola/zola#1409]
Hey! Is it possible to use the tera `get_url` function in (s)css? For instance:
```scss
background-image: {{ get_url(path='images/img.png') }};
```
Adding a frontmatter (like in Jekyll) to the .scss file doesn't seem to work. I gather from the docs that only templates in the `templates/` directory are processed by tera; in that case, what's the recommended way to handle something like this?

Thanks! Migrating from Jekyll and really enjoying the experience; just this one issue so far that's tripping me up.

**Comment by Keats** [comment]
This is not possible currently, you will need to hardcode the path.
Jekyll has frontmatter for scss?

**Comment by rileyshahar** [comment]
Shame, but I understand. Do you have any clue where it might be worth looking to start a PR, or does it require deep changes to the template processing? I have some free time and might play around with it if it's something you're interested in merging, I'm getting a lot of value from this project vs jekyll so I'd be interested in contributing back, especially in a way that also helps my workflow.

> Jekyll has frontmatter for scss?

Yes: see https://jekyllrb.com/docs/assets/. AFAIK the frontmatter just tells jekyll to process the file through its assets pipeline, but importantly that also includes processing any liquid in the file.

**Comment by Keats** [comment]
>  Do you have any clue where it might be worth looking to start a PR, or does it require deep changes to the template processing? 

I don't know, you're the first person to ask for that! I wouldn't start working on that until we see more people asking for this feature. Since the CSS file and the static assets end up in the same folder, I'm guessing relative paths work well enough.

**Comment by radekmie** [comment]
I vote for this feature as well. In general, relative URLs are fine, but if the base URL is not a top-level path (`https://example.com`) but a sub route (`https://example.com/blog`) you have to adjust the code for local development and the deployed page.

Another case would be to have some parts of the styles be configurable based on the `[extra]` variables, like the accent color or the font URL itself.

**Comment by Kekun** [comment]
That's a feature I need too, to ensure `url()`s in my CSS work as expected. They currently don't. :(

**Comment by xmh0511** [comment]
@Keats  This feature is demanded. Think of the scenario where the base_path is not "/" but "/subdirectory", in which, the URL in the CSS file needs to be `/subdirectory/file` rather than `/file`

**Comment by ebkalderon** [comment]
I think I've arrived at a workable implementation of this feature in https://github.com/getzola/zola/issues/3061#issuecomment-3707448514. It seems to work well enough for the above use cases, more or less. Anyone who is still interested in the ability to template SCSS/SASS files, please feel free to leave your feedback over there! 🤗
