### ISSUE TITLE
Different rendered page in different version

### ISSUE THREAD

**Issue by thang-qt** [getzola/zola#1410]
I'm on Fedora and using Zola version 0.11.0 on their official repo. However, I use Vercel  to deploy my site, and it's using the latest version which is 0.13.0.
I'm trying to translate my site into English. I also added a link at the top of every page to the translated content if available.
On my machine, this is what I've done, and it's what I expected:
![Screenshot_2021-03-15 Quang Thắng-ex ](https://user-images.githubusercontent.com/35835961/111113106-28eaeb80-8559-11eb-9927-eb609058ade6.jpg)
But on latest Zola, here is what I receive:
![Screenshot_2021-03-15 Quang Thắng ](https://user-images.githubusercontent.com/35835961/111113142-3d2ee880-8559-11eb-92ae-9a1a41b708ec.jpg)
I know that I can easily change version on Vercel to 0.11.0. Nonetheless, it means that I can't use the latest version.
Is this something changed on the latest version?

**Comment by Keats** [comment]
Hard to say which change caused that without seeing the template code.

**Comment by thang-qt** [comment]
> Hard to say which change caused that without seeing the template code.

https://github.com/thangisme/personal/blob/main/templates/base.html
Can you check it?

**Comment by thang-qt** [comment]
Anything new?

**Comment by Keats** [comment]
Sorry, haven't looked yet.

**Comment by Keats** [comment]
That should be fixed in the `next` branch! The list of translations was not excluding the current page/section.

**Comment by Keats** [comment]
Hmm maybe I was too zealous with that commit, there are tests to make sure we do have all translations including itself in the `translations` array so maybe I should revert it and note in the docs it contains itself.
I think the idea was if you have many languages, you can do a dropdown that has the current language selected. In your case, it means you would have to add a `if` in the translation look to check if we're already in this page.
