### ISSUE TITLE
`zola serve` ignores port 1111

### ISSUE THREAD

**Issue by ralfbiedert** [getzola/zola#1412]
# Bug Report

## Environment
 
Zola version: 0.13

## Expected Behavior
When running `zola serve -p 1111` I'd expect it to use port `1111`. 

## Current Behavior
When running `zola serve -p 1111` it listens on port `1024`. 

Other ports seem to work as expected, e.g., `zola serve -p 3333` listens on port `3333`. Also, according to Process Hacker the local port `1111` should be available:

![image](https://user-images.githubusercontent.com/301288/111336822-d9e6a880-8675-11eb-98b7-6a8de9c10f68.png)

**Comment by Keats** [comment]
Works on my machine ™️ 
Maybe it's a Windows difference?

**Comment by ralfbiedert** [comment]
Hm, yeah, I feared this won't reproduce :) 

FWIW, I use `Windows 10 - 10.0.18363 Build 18363`

**Comment by iEverX** [comment]
maybe because of windows dynamic tcp port range, try this command
`netsh interface ipv4 show excludedportrange protocol=tcp`

ref: https://github.com/docker/for-win/issues/3171#issuecomment-554587817

**Comment by ralfbiedert** [comment]
> maybe because of windows dynamic tcp port range, try this command

Hah, thanks a lot! Yes, port `1111` got excluded for some reason:

```
Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      1041        1140
      1241        1340
...
```

Closing this one, since it's really nothing Zola can or should try to fix.
