### ISSUE TITLE
Themes you'd like to see ported

### ISSUE THREAD

**Issue by Keats** [getzola/zola#143]
Can be from any static site generator, they need to have a licence allowing it ofc

In progress:

- [x] after-dark: https://github.com/Keats/after-dark
- [x] gitbook 

Next:
- vida: https://github.com/syaning/vida

**Comment by caemor** [comment]
https://themes.gohugo.io/hugo-tranquilpeak-theme/
Thats the theme I use with hugo. What i really about it are the following two points:
- Configurable menu of the sidebar
- Pages to filter tags, categories and archives

But basically any theme with sections, tags and categories additionally to the page and index that hyde "only" offers would be really great for starters who don't want to build their own theme. (basically the things gutenberg offers ;-) )

**Comment by TheSirC** [comment]
If we want to port some themes to Gutenberg, where should we make a pull-request for the files of the theme ? [Here](https://github.com/Keats/gutenberg-themes) ?

**Comment by Keats** [comment]
> If we want to port some themes to Gutenberg, where should we make a pull-request for the files of the theme ? Here ?

So that's something I didn't think through yet but I think a PR to this repo adding/updating submodules is the best idea so far, that's how Hugo and Pelican do it. I'll try to setup the repo today or tomorrow

**Comment by Keats** [comment]
@Caemor This theme looks nice (minus the unreadable white text on yellow pic in the menu but that can be fixed). I see it has many issues with `0.4.2-beta` and `0.5` so it seems a bit in flux. I might port the original hexo theme instead or something similar

**Comment by pka** [comment]
https://github.com/mixu/markdown-styles ?

**Comment by Keats** [comment]
I ported a few themes to get the ball rolling, I might port more myself but more on a "this-looks-cool" basis
