### ISSUE TITLE
Docker-based environment closes immidiately

### ISSUE THREAD

**Issue by alicika** [getzola/zola#1434]
## Environment

Zola version: 0.13.0

## Expected Behavior

I want it to keep a shell attached to a newly-created container, but it shuts down a moment after launch.
How do I let the container remain waking up with an interactive shell? 
Or anyone knows a good idea to use zola using docker?

## Current Behavior and Step to reproduce

I tried as shown in the [doc](https://www.getzola.org/documentation/getting-started/installation/#docker),
```
$ docker pull balthek/zola:0.13.0
$ docker run balthek/zola:0.13.0 --version
```
then get:
```
zola 0.13.0
Vincent Prouillet <hello@vincentprouillet.com>
A fast static site generator with everything built-in

USAGE:

< omitted lines below >

```
however, it instantly closes the container and forcibly gets me back to a shell working in my local environment.
If I worked around to make the container up, I still see an error like this:

`$ docker container run -it --entrypoint /usr/bin/sh balthek/zola:0.13.0`
```
0dd409092b198c0aae37bca8c82272386786758aadc94c53ea216a586f3c2868
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/usr/bin/sh": stat /usr/bin/sh: no such file or directory: unknown.
```

**Comment by Keats** [comment]
The docker image only contains the binary, no shell

**Comment by alicika** [comment]
I appreciate your explanation, but unfortunately, I want to use Zola in a container, not in a locally installed development environment.
However, I intended to avoid immediate termination after starting the container and let the container stay awake with
`$ docker container run -it --entrypoint /usr/bin/sh balthek/zola:0.13.0`.
Is there a preferred way to develop a static site using Zola on Docker?
I want to use `zola init` and persist the volume containing the generated files...

**Comment by Keats** [comment]
I'm not sure, I'm using Docker for Zola. The [Dockerfile](https://github.com/getzola/zola/blob/master/Dockerfile) is pretty small though so it should be easy to customise for what you want.
