### ISSUE TITLE
Add orphan page to search index

### ISSUE THREAD

**Issue by kuon** [getzola/zola#1438]
I have a website where all pages are hierarchical in a tree, thus no section. Everything works properly, except the search index which is empty.

Zola seems to ignore pages not in a section from the index.

Is there a way to index orphan pages?

**Comment by Keats** [comment]
Right now the search index is created by sections since you can toggle search on/off for specific sections. What's the layout of your file? Any reasons those pages could not be sections with only them as content?

**Comment by kuon** [comment]
I guess I could convert everything to sections, I haven't thought of that.

My layout is like: (path, url)

```
/foo/index.md -> /foo
/foo/bar/index.md -> /foo/bar
```

It is imported from another CMS, but I can rename everything to `_index.md`.

I'll try that, and if it works I'll close this.
-- 
Nicolas Goy

**Comment by kuon** [comment]
Having only sections and no page solved my problem.
