### ISSUE TITLE
theme.toml not found

### ISSUE THREAD

**Issue by keyganker** [getzola/zola#144]
An error occur when I use the theme:
```
Failed to build the site
Error: No `theme.toml` file found. Are you in the right directory?
Reason: No such file or directory (os error 2)
```

what I do:
1. clone the theme "hyde" and place it under folder themes
2. add theme config in config.toml

**Comment by Keats** [comment]
I can't reproduce that on a new site (`gutenberg init, cd themes, git clone https://github.com/Keats/hyde.git, cd .., gutenberg build`) on my laptop.
Can you push a reproduction on GitHub so I can have a look?

**Comment by keyganker** [comment]
I just clone the wrong theme rep from `https://github.com/poole/hyde`, sorry...
I replace it with the right one `https://github.com/Keats/hyde.git` and it works fine, it's cool!
Thank you~
