### ISSUE TITLE
Problem with `config.default_language` variable (as seen in RSS template)

### ISSUE THREAD

**Issue by pkgw** [getzola/zola#1442]
# Bug Report

## Environment

Zola version: 0.14.0 (`next` branch as of a few days ago)

## Expected Behavior

I should be able to build a site with an rss.xml using the default configuration.

## Current Behavior

I get an error about a missing `config.default_language` variable, even though I have defined it in `config.toml`:

```
Failed to build the site
Error: Failed to render '__zola_builtins/rss.xml'
Reason: Variable `config.default_language` not found in context while rendering '__zola_builtins/rss.xml'
```

## Step to reproduce

First, create a new site with `zola init`.

Then add RSS to the `config.toml`: 

```
generate_feed = true
feed_filename = "rss.xml"
default_language = "en"
```

Then create a content page so that there's something to build:

```
cat <<'EOF' >content/mypage.md
+++
date = 2010-08-18T21:13:01Z
title = "Test"
+++

test
```

Then `zola build`.

**Comment by pkgw** [comment]
Looking at the `atom.xml` template, does `rss.xml` need to be update to use `{{ lang }}`?

**Comment by Keats** [comment]
Exactly, I'm surprised nothing was testing that...

**Comment by Bauxitedev** [comment]
This isn't fixed yet, it seems. I still get this error on Zola 0.14.1. 

When I try compiling the [Rust gamedev newsletter](https://github.com/rust-gamedev/rust-gamedev.github.io) on Windows 10, I get this error:
```
Error: Failed to render section '[...]\rust-gamedev.github.io\content\_index.md'
Reason: Failed to render 'index.html'
Reason: Variable `config.default_language` not found in context while rendering 'index.html'   
```

Even though the "default_language" is clearly present in config.toml:
```
title = "Rust GameDev WG"
description = "Stay up to date with the progress and recent developments in the Rust Game Development Working Group."
base_url = "https://gamedev.rs/"
default_language = "en"
compile_sass = true
highlight_code = true
generate_feed = true
feed_filename = "rss.xml"
...
```

Is this a Zola issue? Or an issue with the newsletter?

**Comment by gschup** [comment]
> Is this a Zola issue? Or an issue with the newsletter?

I think this is a Zola version issue. On some of my zola projects, I had to replace `config.default_language` with `lang` in order to make it work.

**Comment by Bauxitedev** [comment]
> 
> 
> > Is this a Zola issue? Or an issue with the newsletter?
> 
> I think this is a Zola version issue. On some of my zola projects, I had to replace `config.default_language` with `lang` in order to make it work.

Ah, I see. It indeed fixes the issue, so I guess this is an issue with the newsletter then.

**Comment by id027102** [comment]
Closed  yes , solved ?
I installed yesterday (03/11/2021) the latest debian unstable package  0.14 and has the same problem.
I had to go back to : https://github.com/barnumbirr/zola-debian/releases/download/v0.13.0/zola_0.13.0-1_amd64_debian_unstable.deb , to get it solved .

**Comment by Keats** [comment]
It's fixed in the next branch, the `default_language` was not being passed in 0.14

**Comment by Grelot** [comment]
Just to signal I got this error too, I go back to 0.13 waiting the next release ^^

**Comment by Keats** [comment]
https://github.com/getzola/zola/pull/1640 is the main issue left before the next release but it will take some time to review/fix/benchmakr
