### ISSUE TITLE
Image processing does not respect `--output-dir`

### ISSUE THREAD

**Issue by scriptis** [getzola/zola#1444]
# Bug Report

## Environment

Zola version: 0.13.0

## Expected Behavior
Zola should provide a way to change the output directory of processed images. If `$src/static/processed_images` is read-only, the site build will fail.

Ideally, you would be able to configure the output directory either via CLI flag or through a field in `config.toml`. Or, if possible, respect the existing `--output-dir` flag (write to `$output_dir/processed_images`).

I'd love to implement this and open a PR (I've been using Zola for two-odd years now), just let me know.

## Current Behavior
If `$src` is read-only (e.g., a `ro` mount in a Docker container), the build will fail.

## Step to reproduce
Attempt to build any site using `resize_image` in a read-only directory or mount with the `--output-dir` flag specified.

**Comment by Keats** [comment]
Hmm so the fact that it is building it in `static` is intended since we don't want to re-process the images every time. The images will end up in `output-dir` at the end of the build when `static` is copied. I don't think it makes sense to change that behaviour with the `output-dir` flag since I expect most people do want to keep processed assets in static

**Comment by scriptis** [comment]
Sure. How about a new CLI flag/an option in `config.toml` then?

**Comment by Keats** [comment]
Honestly I'm not sure I want to include that. It's a worse solution that really is unusable for `zola serve` so unless there are a few more people wanting that, it's probably not going to happen.

**Comment by scriptis** [comment]
Mm, alright. I'll post a workaround here if I can find one, then. Thanks for considering!

**Comment by scriptis** [comment]
As a workaround on Docker, I just mounted `static/processed_images` into a read/write volume that isn't mounted back to the host. Docker doesn't seem to have any issues with an RW mount inside of a RO mount.
