### ISSUE TITLE
[Feature Request] Asciinema Shortcode

### ISSUE THREAD

**Issue by SkypLabs** [getzola/zola#1451]
Hi there,

[asciinema](https://asciinema.org/) is a popular tool/service when it comes to recording and sharing screencasts. I was about to add an asciinema shortcode to my own Zola blog and I thought that it could definitely find its place in Zola itself as a built-in shortcode.

If you agree with me, I would be happy to create the appropriate PR.

Thanks.

PS: I know the contributing guide says to share feature request ideas on the forum but I preferred not to create another online account just for that. I hope you understand and don't mind.

**Comment by Keats** [comment]
I'm trying to not add more built-in shortcodes as they can get out of date and you almost always want to customise them in some ways.
I'm wondering if we could have a repository of example shortcodes though.

**Comment by SkypLabs** [comment]
Makes sense. I close this issue in this case.

Let me know if you create a such repository for shortcodes. I would be happy to contribute to it.
