### ISSUE TITLE
Random panics when modifiying hmtl templates

### ISSUE THREAD

**Issue by TheSirC** [getzola/zola#146]
Hello,

When I serve file via `gutenberg.exe serve` I get panics when I update html templates in the `templates/` folder. The behavior is however not consistent.  I will add more precise information in this issue as soon I find them.

Here is the error message :
```
thread '<unnamed>' panicked at 'this crate accidentally accepted 0-sized slices originally but this was since discovered as a soundness hole, it's recommended to use the `from_bytes` function instead', src\libcore\o
ption.rs:819:4
```

I am using Windows 10 64 bits Creators' Update

**Comment by Keats** [comment]
Looks like it's an issue from the `ws` crate (from `mio` actually): https://github.com/housleyjk/ws-rs/issues/177 and it's fixed in mio already so I guess we need to wait a new `mio` release and the next release of Gutenberg should work

**Comment by Keats** [comment]
I'll reopen it so I don't forget it
