### ISSUE TITLE
Modify CSS classes of generated output

### ISSUE THREAD

**Issue by pinpox** [getzola/zola#1462]
# Documentation issue

## Summary
I'm trying to figure out how to add css classes to the generated html output, but can't find anything regarding it in the documentation. Here is an example:

I'm using [Pure CSS](https://purecss.io/base/), which I imported in the `head` of my template. To have responsive images, I have to add a class to the `<img>` tags, like so:

```html
<img class="pure-img" src="...">
```

The mardown content includes images, e.g.
```markdown
![outside](/img/electronics/amp/outside_front.jpg "Outside view")
```
Which is rendered to 
```html
<p><img src="/img/electronics/amp/outside_front.jpg" alt="outside" title="Outside view" /></p>
```

Is it possible to modify the html generated from markdown directives like images?
How can I add `pure-img` to the generated output?

## Proposed solution
Documentation on how to modify the generated output or how to include css classes in it.

**Comment by Keats** [comment]
There's no way to set classes on generated elements. You can either write in HTML directly in the Markdown file or make a shortcode that will do what you need.
