### ISSUE TITLE
Why use and not change political example on documentation?

### ISSUE THREAD

**Issue by iozcelik** [getzola/zola#1463]
I comment twice about political message on documentation. However you cannot change. Why? This is an open source project. What is idea of that?
In documentation "Le mouvement des Femmes Libres, à la tête de la libération kurde" in French. Why there is a specific nation? 

An open source project, must be care this, of course it want to grow. I plan to use Zola and start to develop my site. However this example pushed away. 

If you want to give an example with non-ASCII chars. Write simpel text "Örnek bir blog yazısı" (An example blog post). This is simple and most beautiful way.

**Comment by Keats** [comment]
> Why there is a specific nation? 

Because the user that added the example took an example from their site. At this point it's more a knee-jerk reaction, if you had made an honest first PR it would have been merged without any issues but then it came off as dishonest. I'll probably change it anyway though.
