### ISSUE TITLE
`zola serve` should delete the generated output dir even in the case of exit due to any error

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1465]
# Bug Report

## Environment

Zola version: zola 0.13.0

## Expected Behavior
`zola serve` should revert to initial filesystem by deleting the generated output dir even in the case of exit due to any error

## Current Behavior
Currently, if `zola serve` exits due to error it doesn't delete the output dir it generated leaving the output dir cluttering user file structure

## Step to reproduce
```
$ ls | grep public
$ zola serve 
Building site...
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 24ms.

Listening for changes in blog{config.toml, content, sass, static, templates}
Press Ctrl+C to stop

Web server is available at http://127.0.0.1:1111

^C$ ls | grep public
$ zola serve -i 1.2.3.4
Building site...
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 26ms.

Error: Cannot start server on address 1.2.3.4:1111.
$ ls | grep public
public/
$ rm -rf public/
$ ls | grep public
$ zola serve -i foo.com
Building site...
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 25ms.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(())', src/cmd/serve.rs:263:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ ls | grep public
public/
$
```
Above 2 are some of the possible errors for `serve`. `serve` should delete generated output dir when it exits (cleanly or due to any error).

**Comment by Keats** [comment]
Sounds good to me

**Comment by Keats** [comment]
Actually unless you are catching panics it's going to be tricky to do. I'll fix that particular panic though.

**Comment by Keats** [comment]
The panic is fixed. Unless there are other panics, let's not catch them all so they pop up in issues.
