### ISSUE TITLE
Some limit for loops and sorting for arrays would be great

### ISSUE THREAD

**Issue by caemor** [getzola/zola#147]
1. When i want to only show the first 3 Pages of a Section for example, it would be great to have sth like 
```
{% for page in subsection.pages | limit = 3 %}
   {{ page.title }} {% if not loop.last %},{% endif %}
{% endfor %}
```
That should give me up to 3 pages (or less if only 2 or less are in that section).
At the moment you would need to do sth like: 
```
{% set limit = 3 %}
{% for page in subsection.pages %}
   {% if loop.index <= limit %}
       {{ page.title }}
       {% if not loop.index == limit %},{% endif %}
    {% endif %}
{% endfor %}
```

2. Some sorting for Arrays would also be helpful e.g. for sorting the Tags after the amount of elements.

**Comment by Keats** [comment]
(This is more a Tera issue actually: https://github.com/Keats/tera/)

1. It's not in Tera because it can be written easily that way:
```jinja2
{% for page in subsection.pages | limit = 3 %}
   {% if loop.index <= 3 %}{{ page.title }}{% endif %}
{% endfor %
```

2. Agreed. This is a filter I wanted to add to Tera for a long time (still in the list https://github.com/Keats/tera/issues/46) but didn't really find a good solution yet.

**Comment by caemor** [comment]
to 1.: Maybe it would also possible to only make a 'improved' join which works on arrays of variables with multiple fields :
```
{% subsection.pages | join(sep=", ", limit=3, field="title") %}
```

**Comment by caemor** [comment]
Oh sorry. I was editing it once more for a long time and didn't see that you already had answered my questions. But yes, it's more of an shorter, 'better' looking code improvement and maybe it's better to make my own macro for it ;-)
```
{% macro section_pages_title(limit, section)  %}    
    {% for page in section.pages %}
       {% if loop.index <= limit %}
           {{ page.title }}
           {% if not loop.index == limit %},{% endif %}
        {% endif %}
    {% endfor %}
{% endmacro section_pages_title %}
```

Thanks for your answers :-)

**Comment by caemor** [comment]
3. Is it possible to get all posts in a section including subsections (sorted from new to old)? I am using folders to seperate the different categories/... to not have too many files in the main post section.
4. Is there a way to set the default for things like sort_by for sections in the config.toml (or elsewhere)?

**Comment by Keats** [comment]
3. No. How many files do you have?
4. No, it's only per section.

**Comment by caemor** [comment]
Okay. Thanks :-)
To 3.: Not that many yet. It's like 5 or 6 folders with ~5 to 10 files. I am just gonna put them all in one folder now :-)
