### ISSUE TITLE
Docs: Add missing subcommand `help`

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1470]
# Documentation issue

## Summary
`zola --help` shows 5 subcommands but https://www.getzola.org/documentation/getting-started/cli-usage/ says "Zola only has 4 commands: init, build, serve and check."

## Proposed solution
I'm aware that the `help` subcommand is added by `clap` but to anyone using `zola` on commandline `zola --help` shows 5 subcommands so `zola` has 5 subcommands.

```
$ zola --help
zola 0.13.0
Vincent Prouillet <hello@vincentprouillet.com>
A fast static site generator with everything built-in

USAGE:
    zola [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -c, --config <config>    Path to a config file other than config.toml in the root of project
    -r, --root <root>        Directory to use as root of project [default: .]

SUBCOMMANDS:
    build    Deletes the output directory if there is one and builds the site
    check    Try building the project without rendering it. Checks links
    help     Prints this message or the help of the given subcommand(s)
    init     Create a new Zola project
    serve    Serve the site. Rebuild and reload on change automatically
$
```

Maybe we should add `help` subcommand on https://www.getzola.org/documentation/getting-started/cli-usage/ ?

Thanks!

**Comment by rootkea** [comment]
Or alternatively we can disable the `help` subcommand (if `clap` allows) since there is already `--help` flag which does the same.

**Comment by Keats** [comment]
I'm not sure I would bother documenting it, it's something people will find organically. Maybe just mention they can add `--help` for help on each command.

**Comment by rootkea** [comment]
> Maybe just mention they can add --help for help on each command.

The immediate next line on https://www.getzola.org/documentation/getting-started/cli-usage/ says "You can view the help for the whole program by running `zola --help` and that for a specific command by running `zola <cmd> --help`." So I guess we are done with this issue.

Closing.
