### ISSUE TITLE
zola serve: Default output directory should be different than `public`

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1473]
Hello!

Please consider this use-case:

1. User builds the large site which takes a considerable time
```
$ zola build
Building site...
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 29ms.                                                         # assume large site so considerable time

$ ls | grep public
public/
$
```

2. Now, she wants to see how will the homepage look if `background-color` is changed so she makes that change and does:
```
$ zola serve
Building site...
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 113ms.

Listening for changes in blog{config.toml, content, sass, static, templates}
Press Ctrl+C to stop

Web server is available at http://127.0.0.1:1111

^C$
```

3. Not happy with the change she undoes the css file reverting `background-color` change.
4. But now the build is gone!
```
$ ls | grep public
$
```
And she has to `zola build` again even though site source is still the same!

This happens because `zola serve` by default uses `public` directory as an output directory.

How about making `zola serve` use some other directory (e.g. `public-serve`) as output directory by default? And so the site build directory `public` will only be overwritten by the next build (`zola build`) which is what user wants and not by `zola serve`.

**Comment by rootkea** [comment]
And then maybe we should also warn user if she tries to build the site in output directory project_root/`public-serve` (unaware of project_root/`public-serve` being used by `zola serve` by default).

```
$ zola init
...
$ zola build -o public-serve
Warning: By default 'public-serve' directory in project root is used by `zola serve` so next invocation of serve might delete the `public-serve` directory. Consider building site in any other output directory.
Building site...
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 29ms.

$ ls | grep public-serve
public-serve/
$ 
```

**Comment by rootkea** [comment]
> How about making `zola serve` use some other directory (e.g. `public-serve`) as output directory by default?

I think a temporary directory on tmpfs `/tmp` will be a better candidate to use as output directory by default. This also nullifies the need for warning as suggested in previous comment.

**Comment by Keats** [comment]
I still need to think about it, having `zola serve` in tmp makes sense, more than having it on another folder in the site directory imo.

**Comment by doamatto** [comment]
I would argue it would be better to keep it in the site directory for purely the reason of cross-platform. On macOS and Linux, `/tmp` is fine as they have this directory, where as Windows has an equivalent. It would make sense, similar to that of other frameworks, to do something such as `.zola/` where the served files are inside that folder, and then encourage users to `.gitignore` that folder.

**Comment by Keats** [comment]
I won't change that in the end.
