### ISSUE TITLE
config.toml: Shouldn't `build_search_index` be under `[search]` section?

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1476]
Hello!

On page https://www.getzola.org/documentation/getting-started/configuration/ shouldn't `build_search_index` be under `[search]` section like this:
```
...
[search]
# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = false
# Whether to include the title of the page/section in the index
include_title = true
...
```

If yes, then I can send the PR right away. :)

Thanks!

**Comment by rootkea** [comment]
The PR will also include a fix to `zola init` at https://github.com/getzola/zola/blob/master/src/cmd/init.rs#L18 moving `build_search_index` under `[search]` section.

**Comment by Keats** [comment]
ah it becomes a philosophical question ;)
My thinking was the switch on/off is at the root level and you can configure it further in the search section. It wouldn't work to put it in the `search` section in practice as it can also be defined on a per-language basis.

**Comment by rootkea** [comment]
I see. But on https://www.getzola.org/documentation/getting-started/configuration/ `build_search_index` is under `[slugify]` section. It should be moved under root.

**Comment by Keats** [comment]
Oh, that is definitely an issue

**Comment by rootkea** [comment]
I am confused regarding where to put it at root level so not sending a PR. :)

**Comment by Keats** [comment]
Ah, welcome to TOML ;)

**Comment by rootkea** [comment]
No, TOML is easy! I'm just not sure whether to put `build_search_index` just above the `[markdown]` section right after `extra_syntaxes` or someplace above... :)

**Comment by Keats** [comment]
Just above markdown is fine
