### ISSUE TITLE
Is `insert_anchor_links` a valid config.toml variable?

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1477]
Hello!
 
I see `insert_anchor_links` vaibale in config.toml of docs https://github.com/getzola/zola/blob/master/docs/config.toml but the variable has no mention on https://www.getzola.org/documentation/getting-started/configuration/

Is it a valid config.toml variable?

If yes, then I can send the PR adding `insert_anchor_links` to https://www.getzola.org/documentation/getting-started/configuration/ :)

Thanks!

**Comment by rootkea** [comment]
Looking at the code may be `insert_anchor_links` is not a valid config.toml variable and so should be removed from docs config.toml https://github.com/getzola/zola/blob/master/docs/config.toml

**Comment by Keats** [comment]
Cheers, not sure why it was there.
