### ISSUE TITLE
Docs: The rss_feed.png image should be resized/scaled to fit the screen

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1478]
Hello!

On page https://www.getzola.org/documentation/templates/feeds/:

![zola](https://user-images.githubusercontent.com/2694559/119253210-afe2c280-bb9f-11eb-8314-deeab2582b60.png)

https://www.getzola.org/documentation/templates/feeds/rss_feed.png needs to be scaled/resized horizontally to fit the screen.

Thanks!

**Comment by RhnSharma** [comment]
I would like to take this one.
