### ISSUE TITLE
Create test setup for Library

### ISSUE THREAD

**Issue by Keats** [getzola/zola#1480]
The main issue is that it's painful to get a real library loaded without just creating some files and commit them. Ideally there would be a function/macro that can be used to create pages/sections.
The other files in the `library` component create whatever is needed manually but it makes tests very verbose/long where 90% of the test is actually setup. 
The `library.rs` really needs some more testing and to rely less on integration tests.

**Comment by aslowwriter** [comment]
Am looking into creating some more ergonomic setup functions for the library component to help with the benchmarking, so I might as well look into this one too. Are there specific tests that you want to see? they might be a bit verbose as you say but the component seems tested well enough to me

**Comment by Keats** [comment]
Probably just replace the current tests for now. I had some ideas when I wrote that issue but I forgot them.
Essentially, we have lots of tests in `site/tests` that might be able to be unit-tested instead
