### ISSUE TITLE
Include path in the search index

### ISSUE THREAD

**Issue by timakro** [getzola/zola#1481]
Would be useful on my wiki as pages don't have a title, instead the path serves as the replacement for a title. I'd be willing to PR if you agree to add this feature (in form of a `search/include_path` switch).

**Comment by Keats** [comment]
There's already the permalink added to the search index, can you not use that?

**Comment by timakro** [comment]
The permalink is only added as the key that's returned with the search results. It's not indexed and isn't matched in a search request, unfortunately.

**Comment by timakro** [comment]
We would need to replace `'/'` by `' '` before indexing, as the elasticlunr tokenizer only splits on whitespace and hyphens.

**Comment by timakro** [comment]
I see the replacement solution would be ugly and unfortunately the elasticlunr crate doesn't support different tokenizers for multiple fields. Also I suppose this wouldn't be useful to many so I'm closing this and working around it in javascript.

**Comment by timakro** [comment]
I changed my mind and would like to see this in zola after all. I [added the possibility to use different tokenizers per field](https://github.com/mattico/elasticlunr-rs/pull/38) to elasticlunr-rs. Because the PR template says to discuss before opening a PR I'm reopening this issue. Here's my proposed implementation: https://github.com/timakro/zola/commit/123c73df53bf695d1ec6619838cb1592bcd47427. The title, description and body fields are using the same tokenizer as before, but the path field is using a special tokenizer which splits on `/`. This way URLs can be searched conveniently on wiki- / knowledge base- / docs-style sites. E.g. the path `/documentation/getting-started/overview/` at https://getzola.org would be matched by queries like "documentation" or "getting started".
