### ISSUE TITLE
Help wanted : walking down a tree

### ISSUE THREAD

**Issue by TheSirC** [getzola/zola#149]
Hello,
I have trouble figuring out how to catch each "sections" (folders in the `pages/` directory) with a for loop. Could somebody help me wrap my head around it ? 

The goal is to be able to execute instructions on each of the `_index.md` in `blog/`, `gallery/`, ...

The directory structure : 
```
content/
├── home
│   └── _index.md
└── pages
    ├── blog
    │   ├── _index.md
    │   └── test.md
    ├── gallery
    │   └── _index.md
    ├── _index.md
    └── projects
        └── _index.md
```

**Comment by Keats** [comment]
Do you mean in a template or somewhere else?
Unrelated but if your `home/_index.md` is meant to be your homepage, you can just put a `_index.md` directly in the `content` folder and it will represent the index page

**Comment by TheSirC** [comment]
Thank you for taking the time to answer !

> Do you mean in a template or somewhere else?

Yes in the template ! 

> you can just put a _index.md directly in the content folder and it will represent the index page

Yes I actually saw that and I corrected it 😅  👍

**Comment by Keats** [comment]
If the sections don't need to be dynamic, you can get the sections directly using `get_section` global function: https://www.getgutenberg.io/documentation/templates/overview/#get-section

Another way if it's a bit dynamic is like I'm doing for the doc pages:
https://github.com/Keats/gutenberg/blob/master/docs/templates/documentation.html#L7-L30 where any new subsection will appear automatically. If you have many levels of section nesting, you can probably write a recursive macro
