### ISSUE TITLE
Docs: class-based CSS framework Bulma and Markdown

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1494]
Hello!

In "Overview" section https://www.getzola.org/documentation/getting-started/overview/ CSS framework Bulma is used in `base.html`.

Bulma is a class-based CSS framework which removes all of the styles of naked HTML elements (e.g. h1, h2 etc) and then uses classes to style those elements.

This makes following md file to display all headings as normal text:
```
Hello
# Foo

## Bar
```

Unaware of this Bulma behavior I spent a considerable time debugging why the markdown headings weren't getting rendered wondering whether I was violating CommonMark spec etc.

Possible solutions:
1. Continue suggesting Bulma but add a note saying user has to put `{{ page.content | safe }}` and `{{ section.content | safe }}` in `div` with class `content` for markdown to get rendered as expected. Ref: https://github.com/jgthms/bulma/issues/1603

    Also, making the same change in `blog-page.html` on that same page:
    ```
    <div class="content">
        {{ page.content | safe }}
    </div>
    ```
2. Suggest any other CSS framework than Bulma which doesn't remove the default styles of naked HTML elements.
3. Just don't suggest/use any CSS framework

**Comment by Keats** [comment]
I think 3 is probably the right move.

**Comment by rootkea** [comment]
Okay. Sending a PR fixing this one. :)
