### ISSUE TITLE
How to change base_url?

### ISSUE THREAD

**Issue by tripleo1** [getzola/zola#1497]
My zola site is/will be deployed in a subdirectory of my main site. How can I reflect this without prefixing all my internal links?

**Comment by Keats** [comment]
When you say internal links, do you mean `@/...`?

**Comment by tripleo1** [comment]
I really meant links prefixed by `/`.  I haven't studied enough to know what `@/...` means yet.

But what I really mean is all links generated by `zola`.

Edit: Ok, just read it and I'm not using internal link syntax as you have described it.

**Comment by timakro** [comment]
Unrelated to the issue, but I'm curious. I didn't really understand the point of writing `@/foobar.md` over `/foobar` from the docs. Does it enable the link checker? If so, is that the only thing it does?

**Comment by Keats** [comment]
> Does it enable the link checker? If so, is that the only thing it does?

It enables the link checker and you don't have to remember the url of each page (if they have a `path` attribute in the front-matter, aliases etc), you just link to the file.
This will also enable backlinks in a future version.

**Comment by Keats** [comment]
Let's close this one to continue on #1513
