### ISSUE TITLE
Allow picking a different template directory in the config

### ISSUE THREAD

**Issue by Keats** [getzola/zola#15]
Combined with using several config files, that allows doing a/b testing easily without having to duplicate the content around.
That raises the problem of a different static folder too. Maybe make both of them configurable?

**Comment by JabZuda** [comment]
> That raises the problem of a different static folder too.

What about adding support for "config includes" to switch sets of variables, eg from ```includes = ["templates-dev.toml"]``` to ```includes = ["templates-prod.toml"]```?

**Comment by Keats** [comment]
Not too keen on having includes like that. 
I don't think `config.toml` are going to be huge so I think just having multiple config.toml and allowing to override some `template_dir` and `static_dir` settings would be enough. It might get a bit messy if you have a few versions going on though so I'm not entirely sure it's better than just `cp -r folder folder2` and editing there

**Comment by JabZuda** [comment]
I remember now that [config.rs](https://github.com/mehcode/config-rs) has overrides.

**Comment by Keats** [comment]
I'm adding a `sass` folder now to gutenberg so that would be 3 things to change - not convinced at all it's worth doing vs just `cp` the site in the end.
