### ISSUE TITLE
HTML comments should be ignored while parsing any .html file

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1503]
Hello!

Steps to reproduce:
1. Place sunset.jpg at `content/foo`
2. Create an HTML template containing this HTML comment
  ```
  <!-- <img src="{{resize_image(path="foo/sunset.jpg", width=150, height=150, op="scale")}}" /> -->
  ``` 
3. `zola build`
4. You'll see a jpg image generated at `static/processed_images/`

I'm not sure if this affects `resize_image` function only but in general HTML comments should be ignored while parsing any HTML file.

**Comment by Keats** [comment]
>  in general HTML comments should be ignored while parsing any HTML file.

No, that would require parsing HTML. If you want something to be ignored, use Tera comments `{# ... #}`

**Comment by rootkea** [comment]
Makes sense. Thanks!
