### ISSUE TITLE
Shortcode being ignored

### ISSUE THREAD

**Issue by Keats** [getzola/zola#151]
Moving from #130 to here.

@iJos what's the filename and can you paste the snippet of the .md file where you are using it?

**Comment by iJos** [comment]
Sure, this is a test, for embedding the Twitch player, the template is almost the same as the Youtube shortcode.

> twitch.html

```html
<div {% if class %}class="{{class}}"{% endif %}>
    <iframe
        src="https://player.twitch.tv/?channel={{channel}}" 
        frameborder="0" 
        allowfullscreen="true"
        height="{% if height %}{{height}}{% endif %}"
        width="{% if width %}{{width}}{% endif %}">  
    </iframe>
</div>
```

> page.md

`{{ twitch(channel="**channel-name**") }}`

I think I've just found the bug pasting the code here, I'm trying to reproduce.

**Comment by iJos** [comment]
The shortcode is being ignored when the variable I'm passing as "channel" contains an underscore.
For example, when trying to use the shortcode with the official twitch channel (/twitch) the shortcode is being parsed and the html is generated.

When using a name with underscore symbol (the first username I've found in the homepage is "rhobalas_lol") the shortcode is ignored and the output is the plain text "{{ twitch(channel="rhobalas_lol") }}"

**Comment by Keats** [comment]
Another regex issue :(
I'll fix it and add tons of test for it I guess

**Comment by iJos** [comment]
At least we know the issue.

I will create a PR with the twitch shortcode, do you want me to wait the fix of this issue?

**Comment by Keats** [comment]
The issue is the markdown parser splitting the text on the underscore. Looks like more hacks are required!

You can submit the PR for now, i'll work on a fix

**Comment by Keats** [comment]
This should be fixed in master now if you want to try building it from source

**Comment by iJos** [comment]
Nice! I'll check it!
