### ISSUE TITLE
`section.assets` paths start with `/` unlike `page.assets`

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1510]
Hello!

As per https://www.getzola.org/documentation/templates/pages-sections/#section-variables, `section.assets` paths are relative to the `content` dir like `page.assets` but that's not the case.

```
{% if page %}
  {% set post = page %}
{% elif section %}
  {% set post = section %}
{% endif %}

{% for asset in post.assets -%}
  {{ asset }}
{%- endfor %}
```
You'll see for page `content/foo/bar/index.md`urls like `foo/bar/abcd.jpg` are printed while for section `content/foo/_index.md`urls like `/foo/xyz.png` are printed. (Notice the `/` prefix)

One downside of this is that while `page.assets` can be used with `resize_image()`, `section.assets` can't be since `resize_image()` takes path relative to `content` dir.

**Comment by Keats** [comment]
After path unifications they will both work but it should really be the same. I'll make both start with `/`.
