### ISSUE TITLE
HTML minification removes double quotes from HTML content attribute

### ISSUE THREAD

**Issue by benbro** [getzola/zola#1511]
# Bug Report
HTML minification removes double quotes from HTML attributes.

## Environment
Ubuntu 20.04

Zola version: v0.13.0

## Expected Behavior
HTML minification should preserve double quotes.

## Current Behavior
Original template:
```html
<meta property="og:type" content="website">
```
Ffter minification becomes:
```html
<meta property=og:type content=website>
```
## Step to reproduce
1. create a template with double quotes in html: <meta property="og:type" content="website">
2. set "minify_html = true" in the settings.
3. zola build
4. check double quotes in the content attribute.

**Comment by skyfaller** [comment]
This seems fine to me. [Those quotes are optional](https://meiert.com/en/blog/optional-html/#toc-quotes).

If the minifier doesn't deal correctly with forbidden values like equal signs and spaces in unquoted values, that would result in invalid HTML, and that would be a problem. The example you gave is still valid HTML, however.

**Comment by benbro** [comment]
Thank you

**Comment by Leon0824** [comment]
The minifier removes double quotes from a value with equal signs and makes the output HTML invalid:

Original:

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow:wght@200;400;500;800&display=swap">
```

Minified
```html
<link rel=stylesheet href=https://fonts.googleapis.com/css2?family=Barlow:wght@200;400;500;800&display=swap>
```

**Comment by Keats** [comment]
@Leon0824 can you report it upstream to https://github.com/wilsonzlin/minify-html ?

**Comment by Leon0824** [comment]
@Keats Yes, I use minify-html CLI to minify index.html build by Zola. The same thing happens.
