### ISSUE TITLE
Incorrect values in `__tera_context`

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1512]
# Bug Report

## Environment

Zola version: zola next branch

## Expected Behavior
I should have seen correct values in `__tera_context` like in the case of 0.13.0

## Current Behavior
Some values in `__tera_context` are incorrect like `title`, `description` (says `null` but I've set to strings in config.toml). Also `generate_feed`, `build_search_index` (says `false` but I've set to `true` in config.toml)

## Step to reproduce
1. Set appropriate values in config.toml
2. Put `{{ __tera_context }}` in template

Thanks!

**Comment by Keats** [comment]
The rendered config in the `next` branch is now language aware so it will show the values for the current language

**Comment by rootkea** [comment]
I already have `default_language = "en"` in config.toml. I still don't understand why `__tera_context` is reporting incorrect values for variables like `generate_feed`, `build_search_index`, `title` etc.

I don't have `languages = [...]` variable in config.toml

**Comment by Keats** [comment]
Issue found, very nice catch!
