### ISSUE TITLE
How to escape or not render shortcodes in Markdown code blocks?

### ISSUE THREAD

**Issue by oubiwann** [getzola/zola#1514]
# Documentation issue

I suspect this is a documentation issue and not a bug? But it might also be an unsupported feature ...

## Summary

I am attempting to document some custom shortcodes in a post. When I create a code block like the following in my markdown:

```jinja2
{{ soundcloud(
       track_id="1041500689",
       track_name="Chopin, Op. 28 No. 20 (C Minor) - Choir",
       track_url_name="chopin-op-28-no-20-c-minor-choir",
       user_id="oubiwann",
       user_name="Duncan McGreggor",
       colour="2d6072",
       auto_play="false",
       show_comments="false",
       hide_related="true") }}
```

it renders on the page as a code block with the shortcode fully expanded/converted to HTML.

Is there a way around this? 

So far I've only found an ugly hack that prevents the rendering of the shortcode and preserves the syntax highlighting, but would also prevent users from cleanly copying and pasting:

```jinja2
{{` soundcloud(
       track_id="1041500689",
       track_name="Chopin, Op. 28 No. 20 (C Minor) - Choir",
       track_url_name="chopin-op-28-no-20-c-minor-choir",
       user_id="oubiwann",
       user_name="Duncan McGreggor",
       colour="2d6072",
       auto_play="false",
       show_comments="false",
       hide_related="true") }}
```

**Comment by oubiwann** [comment]
I noticed your docs don't have this issue, but likely due to the fact that the Zola docs don't include shortcodes that are used as examples in the docs ;-)

**Comment by Keats** [comment]
It does actually in https://www.getzola.org/documentation/content/shortcodes/

There is a magical syntax to make it not render the shortcodes, see the last paragraph of https://www.getzola.org/documentation/content/shortcodes/#shortcodes-without-body 

> Note that if you want to have some content that looks like a shortcode but not have Zola try to render it, you will need to escape it by using {{/* and */}} instead of {{ and }}.

**Comment by oubiwann** [comment]
Ah-ha! Just what I was looking for!! Thanks SO MUCH!!!

(Also, how did I _miss_ that?!)
