### ISSUE TITLE
Publish zola to crates.io

### ISSUE THREAD

**Issue by barnumbirr** [getzola/zola#1518]
For `zola` to be included in the official Debian repositories, releases would need to be published to crates.io as the Debian Rust team uses debcargo to package rust crates. (see [debcargo README](https://salsa.debian.org/rust-team/debcargo/)).
I'd be willing to work on packaging and maintenance, [other people have already expressed interest in the past](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976052).

**Comment by Keats** [comment]
There's no plan to have any code to upload Zola to crates.io in this repo. It would need to be done as a fork probably. That seems odd to package only for crates.io though, I don't expect applications to be available from there.

**Comment by barnumbirr** [comment]
I don't think a fork is viable as a Debian packaging option. Guess I'll keep maintaining my package on the side then.

**Comment by Keats** [comment]
Not going to happen by me at least.

**Comment by dbr** [comment]
> That seems odd to package only for crates.io though, I don't expect applications to be available from there

FWIW it seems quite common for Rust-developed applications to be posted on crates.io - ignoring cargo-specific tools, ones that spring to mind I use via `cargo install`:

- https://crates.io/crates/ripgrep
- https://crates.io/crates/gitui
- https://crates.io/crates/ocy

I personally quite like this as an option as it is cross-platform, not requiring anyone to maintain platform-specific packages (which, at least with packages less popular than Zola, can sometimes become outdated or abandoned)

However it's understandable not wanting to add more steps to releases

I realized while writing this that `cargo install` can work directly from a git repo, so at least for my purposes I can install zola with:

    cargo install --git https://github.com/getzola/zola.git --tag v0.14.0

**Comment by jhpratt** [comment]
To add to the aforementioned, I would like to note a number of non-cargo tools that I have installed from crates.io, and would very much like to see zola added to this list.

- bat
- dua
- eva
- exa
- fd
- mdbook
- resvg
- rg
- star-history
- tokei

Some like star-history are more "fun" than anything else, but bat, fd, rg? I use those dozens/hundreds of times a day. It's nice being able to do `cargo install-update -a` and have binaries "just update". This is unfortunately not possible with zola as it currently stands.

**Comment by Keats** [comment]
Someone can do it but that's not going to be me. Package managers take care of the dependencies and when zola (gutenberg at the time) was on crates.io, a good number of problems encountered were `cargo install` not working because of the libsass build. It still is the case on a build from master, especially on Windows.
On top of that, the crate is now split in 11 sub-crates for better compile times so pushing to crates.io would be pushing 12 inter-dependent crates.
