### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by vitaly-zdanevich** [getzola/zola#1521]
During build I got this error message: 

`Failed to convert bytes to string : invalid utf-8 sequence of 1 bytes from index 50582`

Looks like this is about HTML minification.

Please show file path and line number.

Zola version: 0.13.0-r0

**Comment by vitaly-zdanevich** [comment]
Related to https://github.com/getzola/zola/issues/1304

**Comment by Keats** [comment]
That's already fixed on `next` and there shouldn't be an error anymore if it's related to CJK minification. There are no file/lines in that case since the issue was in the minified output, in memory.
