### ISSUE TITLE
Allow pages without front matter

### ISSUE THREAD

**Issue by tv42** [getzola/zola#1528]
# Bug Report

I copied some markdown files from elsewhere and ran `zola build`.
Zola both gave me an ugly error message 

## Environment

Zola version: 0.13.0

## Expected Behavior
Tell us what should have happened.

Markdown content is served, without needing to edit every single file to add front matter.

## Current Behavior
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.

```
$ RUST_BACKTRACE=1 zola build
Building site...
thread 'main' panicked at 'error deserialising page: Error { kind: Msg("Couldn\'t find front matter in `/blah/content/blah.md`. Did you forget to add `+++` or `---`?"), source: None }', components/site/src/lib.rs:264:22
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: site::Site::load
   4: zola::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://github.com/getzola/zola/issues/1327 may make that message friendlier, but I argue it should not happen in the first place.

A title can be implicitly extracted from the first block of the file.

## Step to reproduce
Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.

Put a simple markdown file as *.md anywhere under content/

**Comment by Keats** [comment]
There's no plan to allow files without front-matter but it should definitely not panic.

**Comment by tv42** [comment]
Well then this adds nothing on top of the linked issue.

This makes me sad, though. I guess https://news.ycombinator.com/item?id=26357962 was prescient.
