### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Chaostheorie** [getzola/zola#1529]
Hey! Thank you for your work on zola. Coming from pelican, I really appreciated the easy way of setting up the application and the good integration with tools like sass and templates.

The 'latest' release is from the start of January and after taking a look at the next branch I wondered if it would be possible to make a new release? Since the last release, a lot of features have been refined and bugs have been fixed, and I would love to employ the new updates and play around with the new features.

**Comment by Keats** [comment]
It's going to happen soon, after I get https://github.com/getzola/zola/pull/1242 in it. Probably a couple of weeks to test and then release. So probably early July?

**Comment by Chaostheorie** [comment]
Thank you for the quick response. I'll close this issue then.
