### ISSUE TITLE
Empty Static Folder and Git

### ISSUE THREAD

**Issue by caemor** [getzola/zola#153]
If the static folder is empty it doesn't synchronized with git, would it be possible to let gutenberg handle a missing static folder the same way as an empty static folder?

Another solution would be that i'll just add an empty .gitkeep file to static. But then that would be also accessible on my website under mydomain/.gitkeep.

**Comment by Keats** [comment]
Makes sense I think

**Comment by Keats** [comment]
It's in master if you want to try it (https://github.com/Keats/gutenberg/commit/1d8df5774f3da829b2d2ca15a3de795f4fd361dc)

**Comment by caemor** [comment]
Okay, thanks :-) It's working
