### ISSUE TITLE
Treat page only as a content holder, ignore in any other case

### ISSUE THREAD

**Issue by ivan770** [getzola/zola#1533]
Hi! Is it possible for Zola to ignore page while outputting HTML files and generating sitemap?
Main use case is rendering a particular page as an index page on `/` path by using `get_page` in index template.
It works fine, however, page also gets generated second time, with a separate path (slugged name).
I'd like to ignore page in any context, except for when its used in `get_page` calls.

This behaviour can be partially achieved even now by using `path = "//"` or `path = "."` in page front matter, but sitemap generator still treats page as a separate entity (even though paths can be unified):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://example.com/</loc>
    </url>
    <url>
        <loc>https://example.com//</loc>
    </url>
...
```
I know that Zola supports custom sitemap templates, but I'm also satisfied with a built-in one, except for this particular matter.

**Comment by ivan770** [comment]
Also worth mentioning that Zola panics on empty path string, which is rather unexpected in any case.

**Comment by Keats** [comment]
If you were using sections instead of pages to organise things, they have `render = true|false` attribute in the front-matter.
Is it possible to use a section instead of a page in your case?

> Also worth mentioning that Zola panics on empty path string, which is rather unexpected in any case.

Definitely a bug.

**Comment by ivan770** [comment]
> If you were using sections instead of pages to organise things, they have `render = true|false` attribute in the front-matter.
> Is it possible to use a section instead of a page in your case?
> 
> > Also worth mentioning that Zola panics on empty path string, which is rather unexpected in any case.
> 
> Definitely a bug.

Thanks! Looks like I just wanted a section with custom template.

**Comment by Keats** [comment]
Ok the empty is already fixed in `next` actually: I get `path can't be empty if present` on it.
