### ISSUE TITLE
Switch from Libsass to supported Sass implementation

### ISSUE THREAD

**Issue by doamatto** [getzola/zola#1535]
Libsass is deprecated, and only gets maintenance updates. The Sass team recommends people move to Dart Sass instead. It's still fast, compiles to one binary, and, as aforementioned, is being supported and updated. It would be a nice thing to consider

**Comment by Keats** [comment]
I'm following https://github.com/kaj/rsass and https://github.com/connorskees/grass to replace libsass but grass doesn't seem very active so most likely I'll switch to rsass once it can compile bootstrap. If it can compile bootstrap it's probably good enough for 99% of the sites.

**Comment by awulkan** [comment]
Is there any reason for wanting to use a rust based compiler instead of one based on dart? It feels like the rust based compilers will always be playing catch up with dart-sass.
Anyway it appears that the grass compiler is being worked on again. If it's better than LibSass it might be a good idea to transition to that one while waiting for rsass. Unless you feel like it would introduce too many breaking changes.

**Comment by Keats** [comment]
> Is there any reason for wanting to use a rust based compiler instead of one based on dart?

There's no way to FFI with Dart from Rust I believe? You would have to ship the dart-sass binary along with it and then there's no point doing that, people can just do npm install themselves.
In practice I don't think many people are using the new features of Sass present in dart-sass or are even aware they exist. As long as it can compile some common frameworks like Bootstrap it should be fine.

**Comment by awulkan** [comment]
> There's no way to FFI with Dart from Rust I believe?

I've seen a lot of articles published about FFI between Dart/Flutter and Rust lately, but I haven't looked into it. I'm not here to convince you to use dart-sass though. I was just a bit curious. :)

Side note:
While looking up Rust <-> Dart FFI I came across this site, built with Zola, which I thought was pretty cool.
https://thlorenz.com/rid-site/

**Comment by doamatto** [comment]
> While looking up Rust <-> Dart FFI I came across this site, built with Zola, which I thought was pretty cool.

As far as I can see, this is just for Rust to be used in Flutter, which wouldn't be the scope of Zola; correct me if I'm wrong, of course.

> There's no way to FFI with Dart from Rust I believe?

> I've seen a lot of articles published about FFI between Dart/Flutter and Rust lately,

Flutter is just a framework for a slew of platforms built on Dart; not all Dart or Flutter packages work on the opposite scope, actually. Afaik, Dart is in theory capable of being used in Rust (see [`dart:ffi`](https://api.dart.dev/stable/2.13.4/dart-ffi/dart-ffi-library.html)) Also see: [`dart-sys`](https://lib.rs/crates/dart-sys) and [`ffigen`](https://pub.dev/packages/ffigen)

> people can just do npm install themselves.

Fun fact: the version of Dart Sass on NPM is different from Dart Sass; it's compiled to JavaScript, instead of being a native bin. This would make build times (at least from my experience) considerably slower.

I think using the native libraries are the best bet, with `grass` supporting Bootstrap (see [connorskees/grass/issues/4](https://github.com/connorskees/grass/issues/4#issuecomment-673103660).

**Comment by 89z** [comment]
I think all the people trying to push Dart Sass need to stop. The whole point of this issue and the linked issue is to switch to a **Rust** Sass implementation. The current C Sass usage has been painful, where even in some cases (certain Windows configurations) even being impossible. So to move from a C Sass to Dart Sass isnt solving anything.

I get that people want this done, I do too. But people just need to be patient, and wait for a proper Rust Sass. As @Keats said, the Rust Sass doesnt need to be perfect, just good enough, but no package is even good enough yet.

**Comment by Keats** [comment]
Has anyone compared grass and rsass? grass can compile bootstrap which is a huge plus in terms of general support.
Libsass is deprecated so we should move to one of them soon-ish.

**Comment by tempbottle** [comment]
I vote for `grass`, as I use `bulma-scss` with it and it works fine. But it take almost 3 secs on my laptop for a whole process.

**Comment by mikekasprzak** [comment]
There seems to be conflicting reports about the deprecation of libsass. Officially it's deprecated, but contrary to "only doing maintenance" releases, one of the maintainers has been actively back-porting Dart-Sass, and sharing progress reports in the release notes.

https://github.com/sass/libsass/releases/

Like everything there's no timeline for the 4.0 release, but it appears word of libsass's death may have been premature.

**Comment by Keats** [comment]
Yeah I've seen those updates but libsass is also a huge pain to build, especially on Windows - not to mention a very long compile time. Moving to grass/rsass would solve those issues while probably getting more features.
I need to have a look at both to see how mature they are and whether they can already replace libsass or not

**Comment by rlee287** [comment]
If anyone is interested, I made a fork at https://github.com/rlee287/zola/tree/rsass where I switched to rsass, and which I chose because it was easier to port the existing code to use it. I was successfully able to use the "zhuia" theme with this fork, along with customizing it a bit using `sass.color` features unsupported by sass-rs.

I can open a PR with this module change if you'd like that.

**Comment by Keats** [comment]
Sweet, it seems pretty straightforward. I probably need to look at rsass and see if i can reduce the deps a bit, so probably for 0.17

**Comment by pinpox** [comment]
Will this allow to use the built-in sass modules like `sass:color`? I'm trying to do color manipulation as described here https://sass-lang.com/documentation/modules/color

**Comment by Keats** [comment]
I don't know if there's a list of missing features compared to the original impl

**Comment by Keats** [comment]
It looks like https://github.com/connorskees/grass now supports the indented syntax and has a good coverage of dart-sass features.

**Comment by Keats** [comment]
I've pushed grass support replacing libsass to the `next` branch. Can people try it?

**Comment by focusaurus** [comment]
I tried it and it works fine for me. I was able to remove all my uses of `unquote()`.

**Comment by tempbottle** [comment]
it works fine, great!

**Comment by kamoshi** [comment]
I've just tried using it for a website I'm trying to port to Zola and it does seem to support Sass very well. It even supports the new `@use` rule syntax for importing modules which is supposed to supersede the `@import` syntax. The libsass implementation doesn't support it at all
