### ISSUE TITLE
Error message is missing line numbers and points to the wrong file

### ISSUE THREAD

**Issue by jyn514** [getzola/zola#1536]
# Bug Report

I got the following error message:

```
$ zola serve
Building site...
-> Creating 0 pages (0 orphan), 1 sections, and processing 0 images
Error: Failed to render section '/home/joshua/src/third-website/content/_index.md'
Reason: Failed to render 'index.html' (error happened in 'default.html').
Reason: Filter call 'escape' failed
Reason: Filter `escape_html` was called on an incorrect value: got `null` but expected a String
```

This cannot possibly be accurate, `escape` does not appear once in default.html. It does *include* a bunch of files that use `escape`, but I don't know which one of them is the error. Zola should traverse included files when reporting errors.

## Environment

Zola version: zola 0.13.0

## Expected Behavior

Zola should give a more useful error, like it does for parse errors:
```
Error: 
* Failed to parse "/home/joshua/src/third-website/templates/includes/head.html"
  --> 12:75
   |
12 |   <link rel="icon" type="image/x-icon" href="{{ site.baseurl }}{{ get_url("/assets/favicon.ico") }}">␊
   |                                                                           ^---
   |
   = expected an identifier (must start with a-z)
```

## Current Behavior
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.

## Step to reproduce
Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.

```
$ zola init
$ echo '{% include "head.html" %}' > templates/index.html
$ echo '{{ section.title | escape }}' > templates/head.html
$ zola serve
Error: Failed to render section '/home/joshua/src/third-website/zola-example/content/_index.md'
Reason: Failed to render 'index.html'
Reason: Filter call 'escape' failed
Reason: Filter `escape_html` was called on an incorrect value: got `null` but expected a String
```

**Comment by jyn514** [comment]
It looks like this might be a bug in tera itself. https://github.com/Keats/tera/blob/50c56ff8581587631ad8eb8fc2924ef2f0e2049a/src/renderer/processor.rs#L1037-L1055

**Comment by Keats** [comment]
Closing that since it's a Tera issue rather than Zola, you can open it in Tera repo instead.
I think Tera v2 will have better error reporting but it's unlikely anything will change until then.
