### ISSUE TITLE
Building on Windows Linux subsystem (WSL) fails on lexical-core

### ISSUE THREAD

**Issue by simp4t7** [getzola/zola#1537]
# Bug Report

## Environment

Zola version: 312ffcb

## Current Behavior
While building from source on my Windows Linux subsystem (Ubuntu 20.04) the build fails with a bunch of errors in lexical-core (mostly about usize / u32 discrepancies). I was able to build fine on a VM running Ubuntu 20.04 without the issue. I was able to fix the issue by running

` cargo update --package lexical-core`

which updated lexical-core from 0.74 to 0.76 and allowed the build to finish without issue. 

Running cargo tree and following the dependencies showed lexical-core -> nom -> nom-bibtex -> templates. This may be an easy fix updating dependencies although I'm not exactly sure. I just wanted to give a heads up for other people that may run into this error and a quick fix for solving it (or at least what worked for me).

**Comment by Keats** [comment]
Can you try the `next` branch? Dependencies have been updated there.

**Comment by simp4t7** [comment]
Yeah, building on the `next` branch worked fine, thanks!

**Comment by Jieiku** [comment]
Was just about to open a similar issue, using next branch worked for me as well.

Installing on Ubuntu 20.04.2 was a breeze:

```
apt update && apt upgrade
apt install -y curl gnupg2 build-essential libssl-dev git

curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
  1
reboot
rustup update
rustc --version && cargo --version && rustup --version

git clone https://github.com/getzola/zola --branch next
cd zola
cargo build --release

ln -s /root/zola/target/release/zola /usr/local/bin/zola
```

Very excited to start using Zola (switching from hugo)

**Comment by ghost** [comment]
Can we get a release that incorporates this? The 0.13.0 release doesn't build because of this breakage, and it happens on several platforms (macOS, Linux, FreeBSD).

**Comment by Keats** [comment]
Next version is going to be released very soon, just needs some testing.
