### ISSUE TITLE
load_data loading file stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by 0xAF** [getzola/zola#1539]
# Bug Report
As the title says.  
Trying to load a file with `load_data(path="...", format="plain")` fails with error about file not being a valid UTF-8.

Zola version: 0.13.0

## Expected Behavior
I expect it to load the file.

## Current Behavior
```
Reason: Function call 'load_data' failed
Reason: `load_data`: error ... loading file stream did not contain valid UTF-8
```

## Step to reproduce
Try to load a non-utf8 file with load_data.

**Comment by Keats** [comment]
`load_data` only supports UTF-8, it should probably be added to the docs.

**Comment by 0xAF** [comment]
Ok, thanks for the quick answer. Any idea if it is possible to convert the data beforehand?
Like pipe to iconv and reading the stdin? Or any other way to get the filedata into a variable?

**Comment by Keats** [comment]
Not built-in Zola no as it would have to work on all OSes. Is it not possible to convert before loading it in Zola? Is it a remote call?

**Comment by 0xAF** [comment]
No, it's a local file. It's not a big deal to convert it, but I need to keep the original too. Not too much of hassle though.
I was surprised it's not working with non-utf8 files, so I though it's sort of bug or something, but later I dug a bit more in Rust's read_file() and saw the reason.

**Comment by Keats** [comment]
Yep, Rust std pretty much assumes UTF-8 everywhere.

**Comment by 0xAF** [comment]
I guess you can close this now. Unless you have any plans to implement it as feature someday. Thanks to you and all the contributors for the time and this great tool. I'm still learning it, but it already eases my life.
