### ISSUE TITLE
Template question: Equivalent of page.content in index.md?

### ISSUE THREAD

**Issue by tomcam** [getzola/zola#154]
Trying to understand templates, and am stripping everything down to the basics. This is a valid page.html template:

```
<h1>page.html template</h1>
{% block content %}
	{{ page.content | safe }}
{% endblock content %}

```
I want to create an index.html template that will insert the contents of index.md. But if I copy page.html to index.html then this line fails with  the error **Field `page.content` not found in context while rendering 'index.html'**
```
	{{ page.content | safe }}
```

How can I insert the contents of index.md into the block? And how else does an index template differ from a page template? Thanks much. I shall write this  up in tutorial form when I get a handle on it.

**Comment by Keats** [comment]
The index is a section so the variable is `section`. Replace your snippet by `{{ section.content | safe }}` and it should work

**Comment by tomcam** [comment]
Thanks! That seems to have led me in the right direction but a minor issue. I created a brand new site adding just the following 2 files:

`/templates/index.html:`

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<h1>index.html template 1</h1>
	{% block content %}
		{{ section.content | safe }}
	{% endblock content %}
</body>

```

`/content/index.md:`

```
+++
+++

# This file is /content/_index.md 

hello, world.

```

It works but only if the file is named `_index.md` not `index.md`. If I name it `index.md` without the underscore, the `hello, world.` doesn't appear in the generated index.html Why must it be named `_index.md`? This seems to be the opposite of what one is supposed to do with `_index.md`.

I'm so close, I just know it! Really appreciate the help and plan to pay it forward.

**Comment by Keats** [comment]
That's because Gutenberg only looks for file named `_index.md` for sections. More details on https://www.getgutenberg.io/documentation/content/section/

**Comment by tomcam** [comment]
Thank you SO SO MUCH! Really impressed with Gutenberg & dying to contribute.
