### ISSUE TITLE
[Documentation] Fix gallery and resize_image shortcodes

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1542]
Now that `resize_image()` return value has changed from url to object the shortcodes at https://github.com/getzola/zola/tree/next/docs/templates/shortcodes need to be updated.

**Comment by Keats** [comment]
@vojtechkral do you have time? I'll do it soon otherwise.

**Comment by vojtechkral** [comment]
@Keats I'll try tomorrow or the day after and if I can't make it by then feel free to go ahead if that's ok...

**Comment by rootkea** [comment]
I took the liberty to submit PR fixing this issue. Not sure if the approach is correct though.

Everything works as expected except `fit` operation. For the same shortcode invocation `fit` op now produces much larger image.

```
{{ resize_image(path="documentation/content/image-processing/01-zola.png", width=5000, height=5000, op="fit") }}
```

Has `fit` been changed too?

**Comment by Keats** [comment]
You mean it's bigger than 500x500? Or the size on disk is bigger?

**Comment by rootkea** [comment]
The image for `fit` op with the same shortcode call as that of `master` appears much larger in dimension panning multiple scrolls horizontally and vertically.

Ref: see http://127.0.0.1:1111/documentation/content/image-processing/ after checking out #1543

**Comment by Keats** [comment]
The whole image processing got rewritten so it's possible a bug snuck in, let's fix that before release.

**Comment by rootkea** [comment]
Just have a look at the http://127.0.0.1:1111/documentation/content/image-processing/ after checking out https://github.com/getzola/zola/pull/1543

**Comment by vojtechkral** [comment]
@rootkea what are the dimensions of your original image?

**Comment by vojtechkral** [comment]
Ah, I think I know what the problem is, I didn't transfer the logic where `fit` wouldn't resize if the original image was smaller. Will fix.
Edit: PR at #1545
