### ISSUE TITLE
Why the directory /content/content?

### ISSUE THREAD

**Issue by tomcam** [getzola/zola#155]
Trying to understand why the example at [https://www.getgutenberg.io/documentation/content/overview/](https://www.getgutenberg.io/documentation/content/overview/) shows a /content directory with a /content/content subdirectory that does the heavy lifting? Why not just put in all in /content?

thx!

**Comment by Keats** [comment]
The first `content` is the one required by gutenberg, the second being the name of a section under documentation, pure coincidence that they have the same name
