### ISSUE TITLE
Documentation on building from source

### ISSUE THREAD

**Issue by micahcantor** [getzola/zola#1552]
I can't find any documentation on how to build zola from source, which makes it difficult to start contributing. It would be great if there was a page to help with this either on the website or here on github.

For example, I tried building zola yesterday, but `cargo build` failed to compile a dependency, I assume this is because I either have a version of Rust that is too new or an outdated version of the dependency.

A page for building from source would help with an issue like this.

**Comment by Keats** [comment]
You actually ran into a bug in a dependency: https://github.com/Alexhuszagh/rust-lexical/issues/65

In practice building should just be `cargo build --release`, there is https://www.getzola.org/documentation/getting-started/installation/#from-source for some additional dependencies that you might need.

It should work just fine when the `next` branch is merged into master this weekend.

**Comment by micahcantor** [comment]
Thanks, I missed that section of the installation page. That's all I really needed.
