### ISSUE TITLE
<Person> in code block vanishes as it is rendered as an HTML tag

### ISSUE THREAD

**Issue by alice-i-cecile** [getzola/zola#1555]
# Bug Report

## Environment

Zola version: 0.13

## Expected Behavior
```rs 
fn greet_people(query: Query<&Name, With<Person>>) {
    for name in query.iter() {
        println!("hello {}!", name.0);
    }
}
```
Should render properly.

## Current Behavior

As reported in https://github.com/bevyengine/bevy/discussions/2512, `<Person>` disappears
![image](https://user-images.githubusercontent.com/3579909/126526558-fd3394ae-a8bc-40d6-8976-f0fc8f6e1d3f.png)

However, this seems to work fine while building the page locally.
![image](https://user-images.githubusercontent.com/3579909/126526596-64841e41-b0df-42a5-b2b4-9e7e80d34a2d.png)

Credit to @minersebas for investigation.

## Step to reproduce
1. Pull https://github.com/bevyengine/bevy-website.
2. Build it locally.
3. Compare it with https://bevyengine.org/learn/book/getting-started/ecs/

**Comment by mockersf** [comment]
issue from bevy website that was using a deprecated config to setup code highlighting, fixed by fixing the config

**Comment by alice-i-cecile** [comment]
https://github.com/bevyengine/bevy-website/pull/191 was the PR in question that should solve this issue for us.
