### ISSUE TITLE
Rewriting shortcode logic

### ISSUE THREAD

**Issue by coastalwhite** [getzola/zola#1559]
In #1500 it came to light that there are a considerable amount of cases in which the current pipeline for inserting shortcodes shows UB. Because of this is was the conclusion to rewrite this area of the codebase.

This issue aims to discuss what this rewrite might look like.

# Current problems

Currently, many problems arise from the fact that multiline shortcodes are hard to handle. Especially in a inline or HTML context. It is very difficult to known when the codebase will or will not insert `<p>` tags and where it will insert these tags.

It is also awkward at the moment how these shortcodes are divided into two categories –namely markdown and html shortcodes – and these are handled by entirely the same code. This is awkward because in the end these have quite different behaviour.

# Proposed solution

My proposed solution is divided into three parts:

1. Have a look at ironing out some of the specifics of shortcodes. For example, question such as the following
   * What does an inline multiline markdown shortcode evaluate to?
   * When specifically will html shortcodes have `<p>` tags around them.
   * Will shortcodes in markdown shortcodes be evaluated?
   * Probably some more…
2. Following from step 1, write a set of tests this new rewrite should pass.
3. Discuss the structure of this rewrite.
4. Actually rewrite this piece of code.

**Comment by coastalwhite** [comment]
To leave my own two cents:

I personally think shortcodes should act almost a `{% include ‘…’ %}` with variables. This means that all the markdown will be evaluated after the shortcodes are inserted. 

As a consequence everything that has no whiteline between in it after the shortcodes are inserted will be inline. With the exception of div tags which span from the beginning to the end of a paragraph.

To give some examples.

First some shortcodes to define:
*shortcodes/world.html*
```html
<span>World</span>
```

*shortcodes/multiline.html*
```html
Hello

World
```

*shortcodes/divmultiline.html*
```html
<div>
Hello

World
</div>
```

Then the following content:
```markdown
Hello {{ world() }}

Hello
{{ world() }}

Hello

{{ world() }}

{{ multiline() }}

{{ divmultiline() }}
```

Will evaluate too:
```html
<p>
Hello <span>World</span>
</p>

<p>
Hello
<span>World</span>
</p>

<p>
Hello
</p>

<p>
<span>World</span>
</p>

<p>
Hello
</p>

<p>
<span>World</span>
</p>

<div>
Hello

World
</div>
```

I also think recursive shortcodes in markdown shortcodes should be possible.

**Comment by Keats** [comment]
> I personally think shortcodes should act almost a {% include ‘…’ %} with variables. This means that all the markdown will be evaluated after the shortcodes are inserted.

That was the first version. In practice, Markdown will convert anything with 4 spaces indentation to a codeblock which explains why it is currently wrapping in a `pre` to avoid that. In practice most of the shortcode shortcomings are due to those 4 damn spaces.

I'm also thinking of rewriting the shortcodes parser to just use https://github.com/maciejhirsz/logos + manual parsing but that's not even close to a priority, just for fun.

For recursive shortcodes, there is https://github.com/getzola/zola/pull/1475

**Comment by meithecatte** [comment]
If we owned all the code involved, the best course of action would be to modify the commonmark parser to handle shortcodes, and either insert the result of their evaluation into the output stream, or output a new `Event::Shortcode`. Anything else is inherently hacky, and, as we can see, explodes occasionally.

I see four possible solutions:
1. Fork `pulldown-cmark`, with no intention of using the upstream directly in the future.
2. Same as above, but attempt to convince upstream to merge a parser extension for shortcodes.
3. Propose an extension of `pulldown-cmark`'s API that allows generic extensions of the parser.
4. Design a more resilient hack. For example, instead of putting the entire contents of the shortcode back into the markdown, we could insert placeholders such as `ZOLA-SHORTCODE-01234567someuuidhere` and fish them out of the HTML output.

**Comment by coastalwhite** [comment]
I think 1-3 are either not very practical or most likely not going to happen. I think if we agree on the syntax then I can look into writing the test scenarios. Afterwards, I will attempt rewrite the parser using Logos in the following structure:

1. Filter and insert all `*.md` shortcodes and create them recursively.
2. Convert all markdown into html. Here you also form the summary and such.
3. Insert all html shortcodes, (compensating the summary etc.)
Here `*.md` and `*.html` can be recursively inserted.

This seems the most doable to me, but maybe someone sees problems with this. One alteration I can possibly see is to remove all summary, TOC, external/internal reference parsing in 2 and add a step 4 to parse the html, but that is possibly more difficult.

@Keats does that seem like something you would be interested in?

**Comment by Keats** [comment]
> I think 1-3 are either not very practical or most likely not going to happen.

I agree.

> Afterwards, I will attempt rewrite the parser using Logos in the following structure:

Logos was just a nice thing to have, it's orthogonal to the actual shortcode logic and can be done on a later work.

> add a step 4 to parse the html, but that is possibly more difficult.

We don't really want to be parsing HTML so I would rely on the markdown for the TOC and not consider HTML.

Replace after processing the markdown probably makes sense and should be easy to implement.

**Comment by coastalwhite** [comment]
> The Markdown renderer will wrap an inline HTML node such as `<a>` or `<span>` into a paragraph. If you want to disable this behaviour, wrap your shortcode in a `<div>`.

Was this behaviour intentional when first conceptualizing the shortcodes? If so, why was this specific behaviour chosen? If not, is there maybe some more desirable behaviour now that I am basically rewriting the entire shortcode parser and inserter?

I am not quite sure what the behaviour should look like, but I think it is a good question to ask now. I, for example, think it maybe a bit weird to wrap inline `<a>` tags automatically in `<p>` tags, but thinking about all the tags in this way is going to be overly complicated. Maybe more logical behaviour would be that all inline shortcodes don't have `<p>` tags around them and others do except if they are html shortcodes with `<div>` as an outer tag.

**Comment by Keats** [comment]
> Was this behaviour intentional when first conceptualizing the shortcodes? 

~Nope, pretty much all weird hacks around shortcodes where dealing with various bugs found.~

Ah wait, I think this is just normal commonmark behaviour but I can't remember for sure.

**Comment by Keats** [comment]
List of shortcode related issues for testcases:

- https://github.com/getzola/zola/issues/1500
- https://github.com/getzola/zola/issues/1355
- https://github.com/getzola/zola/issues/1326
- https://github.com/getzola/zola/issues/515
- https://github.com/getzola/zola/issues/1418

And wishlist items:
- https://github.com/getzola/zola/issues/1320
- https://github.com/getzola/zola/issues/1277
