### ISSUE TITLE
Omitting .md in markdown links?

### ISSUE THREAD

**Issue by tomcam** [getzola/zola#156]
With many markdown dialects, including Github's and this one, the following two lines of source generate the same links. Can I use and/or recommend  the latter `.md`-less version in a tutorial?

```
[c](/c)
[c](/c.md)
```

**Comment by Keats** [comment]
We need a way to recognise this is an internal markdown link. How do you know `[c](/c)` does not refer to an image or another asset otherwise?

**Comment by tomcam** [comment]
Doh! Thank you.
