### ISSUE TITLE
Running zola serve behind an nginx reverse proxy

### ISSUE THREAD

**Issue by timakro** [getzola/zola#1560]
I'm figuring out how to run `zola serve` behind an nginx reverse proxy with live reload. There's a few things that need sorting out before this becomes practical.

(a) Currently `zola serve --base-url https://example.com` is adding a `http://` prefix and port suffix so the base URL becomes a nonsensical `http://https//example.com:1111/`. I understand this makes sense in the context of a local development server, but I'm suggesting to completely remove this logic and keep the base URL as-is. This would make it consistent with the behavior of `zola build --base-url` and give users more flexibility.

(b) An option to set a fixed port for the livereload websocket would be helpful. I suggest `--live-reload-port`.

(c) In a typical reverse proxy setup both the site and the livereload websocket would be exposed to the internet on the same port (80 or 443). The port zola opens the websocket on (1024 or whatever) is different from the port the javascript needs to connect to from the outside (80 or 443). So I'm suggesting to add an additional `--live-reload-port-external` option that's merely controlling the port in the `<script src="/livereload.js?port=1024&amp;mindelay=10"></script>` tag.

This all seems quite easy to do and I can open a PR if the changes are welcome.

Maybe if other people are interested in this setup I could add a section to the documentation explaining it. What do you think?

The nginx configuration is really simple.

```
server {
    …
    location / {
        proxy_pass http://127.0.0.1:1111;
    }
    location = /livereload {
        proxy_pass http://127.0.0.1:1024;
    }
}
```

**Comment by Keats** [comment]
a) It would make sense to not prefix with http if it already starts with `http(s)://`

b and c are not happening, `zola serve` is not meant to be used outside of a local machine so no changes to facilitate that will be merged

**Comment by timakro** [comment]
Okay, I respect that decision. You don't even have to keep reading here, @Keats, I feel bad enough for wasting your time with this thing I'm probably the only one interested in.

Should anyone find this thread in the future, here's how I worked around those issues.

(a) Turns out I can go without relying on a base URL. Instead of using the special `@` syntax for links I write them as regular relative links. This way I don't benefit from the link checker but you can't have everything in life. :smile: 

(b) Just pray that port 1024 is free and zola grabs that. Should be rather unlikely it's taken as it's [listed as reserved](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Registered_ports), and who would have the audacity to bind to reserved ports? :thinking: 

(c) [Put this into your master template](https://github.com/livereload/livereload-js#options). Magic.
```
<head>
  …
  <script>
    window.LiveReloadOptions = {
      https: true,
      host: 'yoursite.example.com',
      port: 443,
    };
  </script>
</head>
```
The `https` option is not documented but it works!

**Comment by timakro** [comment]
@Keats Sorry to bother you again but it turns out I can't always work around (1). We could say that zola doesn't append http/https if it's already there and doesn't append a port if it's already there so I could just put :443 in the base URL. Can I PR that?

**Comment by stellarpower** [comment]
@timakro thanks for this! Personally, I have the site set up to use relative URLs (always use e.g. page.path rather than page.url) so that it should be ambiguous if it's a live preview or being built for deployment to one of several domains. The snippet you had plus the proxy_pass and [these nginx settings](https://stackoverflow.com/a/14969925/4235856) seems to have done it.

**Comment by EvanCarroll** [comment]
This patch #3048 may help matters. There was no reason for Zola to ever use a different port, nor random port for websockets. It can simply upgrade the current port.
