### ISSUE TITLE
`serve` doesn't respect paths to configs

### ISSUE THREAD

**Issue by cognivore** [getzola/zola#1563]
# Bug Report

`zola -c ./settings/zola_localhost.toml serve` shouldn't fail with

```
> ./zola -c settings/zola_localhost.toml serve

Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 0 pages (0 orphan), 3 sections, and processing 0 images
Done in 14ms.

Error: Can't watch `zola_localhost.toml` for changes in folder `/home/apollo/doma.dev`. Does it exist, and do you have correct permissions?
Reason: entity not found
```

## Environment

Ubuntu LTS

Zola version: 0.14.0 (github binary release)

## Expected Behavior

Zola would watch changes of the configuration file provided.

## Current Behavior

Zole doesn't watch changes of the configuration file provided because it drops path to it.

## Step to reproduce

```
cd /tmp
mkdir serve_bug
cd serve_bug
wget https://github.com/getzola/zola/releases/download/v0.14.0/zola-v0.14.0-x86_64-unknown-linux-gnu.tar.gz -O zola.tar.gz && tar xzvf zola.tar.gz && rm zola.tar.gz
mv zola ../
printf "\n\n\n\n\n\n\n" | ../zola init
mkdir f
mv config.toml f
zola -c f/config.toml serve || echo fail
```

**Comment by Keats** [comment]
Likely cause: https://github.com/getzola/zola/blob/master/src/cmd/serve.rs#L297

**Comment by cognivore** [comment]
Locally, what we did to work around this issue is simply `ln -s settings/zola_localhost.toml 1563_workaround.toml` and then use `1563_workaround.toml` where it matters.
