### ISSUE TITLE
Expected a map for key 'languages'

### ISSUE THREAD

**Issue by zachbellay** [getzola/zola#1567]
# Documentation issue

## Summary

I recently upgraded from zola 0.13.0 to 0.14.0, and was ran into the error:

`Error: invalid type: sequence, expected a map for key 'languages' at line 73 column 1`

After some inspection, I found that this was by design a breaking change as specified in the [CHANGELOG.md](https://github.com/getzola/zola/blob/master/CHANGELOG.md#breaking). However, the docs do not seem to reflect the new hashmap data structure that is expected by 0.14.0, instead, it shows the list expected in 0.13.0 ([docs](https://www.getzola.org/documentation/content/multilingual/#configuration)).

In my current config, I have the following language settings:
```toml
default_language = "en"

languages = [
    {code = "jp"},
    {code = "es"},
]
```

## Proposed solution

- Add updated languages change to relevant docs.

Any guidance on how to fix my `config.toml` would be appreciated. Thanks!

**Comment by coastalwhite** [comment]
So from #1391, these settings were indeed changed to have a different structure. I guess the documentation was not updated back then. I will look into updating it.

For your language settings, the following should work:

```toml
default_language = "en"

[languages.en]
[languages.jp]
[languages.es]
```

But I am not 100% sure. Will update the thread when I have some relevant documentation.
You can look at the *test_site_i18n/config.toml* for an example.

**Comment by Keats** [comment]
Oops looks like I forgot to update the docs :(

**Comment by joesan** [comment]
Is this resolved? by adding to the documentation Even I had to face the same issue but managed to fix it based on the description here.

**Comment by Keats** [comment]
I've just pushed a small thing to at least remove the wrong information
