### ISSUE TITLE
Provide a Flatpak as software package for Linux systems

### ISSUE THREAD

**Issue by Ayush1325** [getzola/zola#1572]
Flatpak like snaps are containerized software packages that are simple to create and install. It also works on all major Linux 
systems without modification.

The one major area where flatpak and snap differ is that snap needs to create a symlink in root filesystem which is not possible in immutable OS like [Fedora Silverblue](https://silverblue.fedoraproject.org/) or MicroOS. See [here](https://github.com/coreos/rpm-ostree/issues/1711) for more information. This pretty much renders usage of snaps impossible. Also, the Fedora package is also currently at 0.12.2 version in Fedora 34, which is about 10 months old at this point. So I think a Flatpak version would be a good idea.

I have a basic version of the manifest file [here](https://github.com/Ayush1325/zola/blob/21889805f84e7808ad2630f978485011020f0c26/flatpak/org.getzola.zola.yml) which works for the most part but has a few problems with git submodules in this project (so syntax highlighting not working yet).

If having a flatpak version is acceptable to everyone, then I can create a Draft pull request and iron out the problems with submodules? 

Also, I am not an expert on flatpak. This is my first attempt at creating a flatpak so it would be great if there was someone already familiar with it and can catch mistakes and problems which might not be obvious to me.

**Comment by doamatto** [comment]
Imo, a Flatpak version isn't necessary per-say. It's already a one bin solution that has your main binaries pre-built in the releases (x64), with it being a simple one command to build (bar installing things like MSVC, g++, make, et al).

In other words, I don't know if a Flatpak would really be used, but I wouldn't be opposed to it, either. Kind of a could take it or leave it opinion. That, and its possible sandboxing could cause issues, not to mention having to use `flatpak run org.getzola.zola [command]` for everything (afaik).

**Comment by Ayush1325** [comment]
Well, in my current flatpak build, all commands seem to be working in the blog. 
The only thing that doesn't work is syntax highlighting since flatpak-builder was having some problem with downloading git submodules.

The reason I prefer flatpak is because I am using Fedora silverblue as my daily driver. I started off with using Zola inside a toolbox (they are just fancy containers if u haven't used silverblue). Anyway, as I said, the snap isn't an option in silverblue and the version in Fedora repo is old. So I thought if there was a snap, we can have a flatpak too.

As for the flatpak run thing, I'm kinda used to at this point, so don't really find it problematic, I mostly just create alias when required, but yeah, that's why I thought creating an issue might be better to see if a flatpak version is helpful.

I won't mind maintaing the flatpak version.

**Comment by Keats** [comment]
Can it be maintained outside of the repo? I already forget to update the snap file half of the time and would prefer not putting more "things to do" in the repo.

Re: submodules
you don't need them to build Zola, the compiled assets are already stored in git

**Comment by Ayush1325** [comment]
> Can it be maintained outside of the repo? I already forget to update the snap file half of the time and would prefer not putting more "things to do" in the repo.

Yup, Currently, the flatpack file directly downloads and builds from the git. So there is no need to have them in the same repository.

> you don't need them to build Zola, the compiled assets are already stored in git

Huh, that solves the submodules issue then.

**Comment by Ayush1325** [comment]
[Here](https://github.com/Ayush1325/flathub/tree/org.getzola.zola) is my initial attempt at creating the flatpak. 
All the commands seem to work fine.

**Comment by Keats** [comment]
So the path to resolve this issue is to add the installation method to the docs right?

**Comment by Ayush1325** [comment]
Well, I haven't merged to flathub yet since I didn't get any response but I can open the pull request if there are no objections. However, it does seem that there is some friction about CLI apps in the flatpak community so I'm not sure about the usefulness of a flatpak right now, to be honest. But the flatpak definitely works fine without any modification to the main zola code, so there is not any reason to be opposed to it either.
Also flathub does not list CLI applications in the main store, so it will only be available through flatpak CLI.

**Comment by Newbytee** [comment]
I would like to see this packaged on Flathub. Will you submit a pull request there?

**Comment by Ayush1325** [comment]
> I would like to see this packaged on Flathub. Will you submit a pull request there?

Ok, I will submit a pull request after updating the flatpak to the latest Zola version.

**Comment by roke-julian-lockhart** [comment]
@Ayush1325, please notify us when you have. I want to monitor the pull-request.

**Comment by Newbytee** [comment]
> Ok, I will submit a pull request after updating the flatpak to the latest Zola version.

Sounds good. if you don't mind, I could co-maintain it with you (just mention that you want them to invite me when you make the PR to Flathub).

**Comment by Newbytee** [comment]
> @Ayush1325, please notify us when you have. I want to monitor the pull-request.

See https://github.com/flathub/flathub/pull/3273

**Comment by Ayush1325** [comment]
@Newbytee it seems that providing at least 1 screenshot is necessary. So any idea for the screenshot? Maybe the zola website?

**Comment by Newbytee** [comment]
> @Newbytee it seems that providing at least 1 screenshot is necessary. So any idea for the screenshot? Maybe the zola website?

I think you just add this property to flathub.json: https://github.com/flathub/org.flathub.flatpak-external-data-checker/blob/master/flathub.json#L4

**Comment by Ayush1325** [comment]
@Newbytee The flatpak build is succeeding now

**Comment by Ayush1325** [comment]
The flathub repository for zola is live now: https://github.com/flathub/org.getzola.zola

**Comment by Ayush1325** [comment]
Zola is now availabe in flathub stable
![Screenshot from 2022-06-21 19-09-57](https://user-images.githubusercontent.com/22546812/174813840-7b489359-8f5d-477a-9bd9-f9cf936d61fa.png)

**Comment by Keats** [comment]
Sweet, does that mean that the PR can be closed?

**Comment by Ayush1325** [comment]
I think so. Should I update the docs to include the flatpak install and usage as well?

**Comment by Keats** [comment]
Yep that would be great!
