### ISSUE TITLE
Provide path segment array in variables of sections and pages

### ISSUE THREAD

**Issue by upsuper** [getzola/zola#158]
For example, for a page in `a/b/c/x.md`, provide a variable with value
```
['a', 'b', 'c', 'x']
```

This is more useful than a complete string, since we can always use it to generate the string path, but there is no way to split a string path into segments at the moment.

Even if there is a function usable in templates to split path, it would still be nice to have this directly.

**Comment by Keats** [comment]
I can add `page.components` and `section.components`

**Comment by Keats** [comment]
Does https://github.com/Keats/gutenberg/commit/791fbe685bc435da7b68b1524d97088a8bd4bdb0 work for you?

**Comment by upsuper** [comment]
Yeah, it looks good. I guess we can close this now. Thanks!
