### ISSUE TITLE
Access content from other sections

### ISSUE THREAD

**Issue by kytta** [getzola/zola#1583]
# Documentation issue

## Summary
I don't know whether I just misread/misunderstood the docs, or this feature is not present at all. I want to create a website, where I have various content categories and thus folders (for example, `content/blog` and `content/recipes`). I know I can host the lists of articles on the respective index pages (`/blog/` and `/recipes/`), yet I also want to display the posts on the main index (`/`) as well (for example, "5 latest blog posts").

## Proposed solution
I expected the index page template to export the `sections` variable or similar, so I could access the posts of it.

----

In the end, what I want to achieve:

- `example.com/` has a list of N latest blog posts and links to `example.com/blog/`
- `example.com/blog/` has a list of all blog posts
- all blog posts are stored in `./content/blog/`, separately from other pages
- path to the blog post `abc` is `./content/blog/abc.md` and `https://example.com/blog/abc` respectively

**Comment by Keats** [comment]
It should have a `subsections` variable, see https://www.getzola.org/documentation/templates/pages-sections/#section-variables

**Comment by kytta** [comment]
I was able to achieve what I need with `get_section()`:

```tera
{% set blog_section = get_section(path="blog/_index.md") %}
{% for year, posts in blog_section.pages | group_by(attribute="year") %}
<h2>{{ year }}</h2>
<ul>
    {% for post in posts %}
    <li><a href="{{ post.permalink }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
{% endfor %}
```
