### ISSUE TITLE
Per-section page template

### ISSUE THREAD

**Issue by upsuper** [getzola/zola#159]
It can be useful if people can use different page template for different section, and subsection can inherit the page template from its parent when such field is lack. Page's `template` field would override anything.

Probably add a new `page_template` can do the trick.

**Comment by Keats** [comment]
Makes sense

Edit: Actually I'm not 100% sure I want to add it now that I think about the interactions between subsections  where sub-sub-sub section would get the same `page_template` as the parent if not filled would be a bit magical imo.
I'll think about it a bit more

**Comment by Keats** [comment]
Warming up to the idea, especially if you want to mix completely different context like a blog/gitbook etc. Maybe even having per-section themes could be nice

**Comment by Keats** [comment]
Closed in favour of #397 which is a bit more detailed.
