### ISSUE TITLE
Unexpected URL path slug defaults broke all internal and external links

### ISSUE THREAD

**Issue by focusaurus** [getzola/zola#1591]
# Bug Report

## Environment

Zola version: 0.7.0 upgrading to 0.13.0

## Expected Behavior

I just want to report as a user that I casually upgraded from 0.7.0 to 0.13.0 and the new default of slugging everything especially paths in my case changed the URL for every blog post. I have many internal links between posts and of course many links out there on the web and they all broke.

This should in my opinion be considered a major, breaking change if an upgrade changes URLs. Especially if defaults change.

I fixed it by adding 

```toml
[slugify]
path = "off"
```
To my config.toml so ultimately not a big deal, but not before having links to my site broken across the web for a while before people reported 404s and I figured out what happened.

## Summary of breaking URL change

- `0.7.0` I manually specify a slug in each file's frontmatter:  like `slug = "2021/04/squeezebox-keyboard/"`
  - I've had this structure for many years across many tech stacks and need to maintain it
- `0.13.0` suddenly it sluggified those paths to `2021-04-squeezebox-keyboard` and all my inbound links broke

OK to close this immediately as I don't need a software change. I just wanted to report to emphasize the importance of changes to URL logic.

**Comment by Keats** [comment]
Hm it's odd that this was missed in the changelog as this is a big change but I can't find it in there :/
Sorry about that!
