### ISSUE TITLE
Calling `get_taxonomy` with empty taxonomies

### ISSUE THREAD

**Issue by acheronfail** [getzola/zola#1593]
# Feature Request

## Environment

Zola version: `0.14.1`

## Expected Behavior

Different solutions:

* Calling `get_taxonomy` with a `kind` that doesn't exist should return null (or `tera`'s equivalent); or
* Calling `get_taxonomy` with a `kind` that does exist, but has no content should not throw; or
* Have an option in `config.toml` to create all taxonomies, even if there's no content associated with them

A similar concept of this has been discussed here: https://github.com/getzola/zola/issues/992.

## Current Behavior

The underlying issue is that taxonomies are not generated if there's no content tagged with them.
This means that if a call to `get_taxonomy` occurs with a `kind` value without any content associated with it (even if it's defined in the config) it will throw.

## Why I want this

My use case is that I want to have a page which links to all taxonomies, think of it like a site-map that only applies to the taxonomies.

Boiled down, my template looks a little like this:

```tera
{% for t in config.taxonomies %}
  {% set taxonomy = get_taxonomy(kind=t.name) %}
  {# ... do something with the taxonomies here ... #}
{% endfor %}
```

If I could do something like this (have the return value of `get_taxonomy` be nullable), that could be a nice quick solution:

```tera
{% for t in config.taxonomies %}
  {% set taxonomy = get_taxonomy(kind=t.name) %}
  {% if taxonomy %}
    {# ... do something with the taxonomies here ... #}
  {% endif %}
{% endfor %}
```

## Step to reproduce

1. Add `taxonomies = [{ name = "categories" }]` to `config.toml`
2. Do not add any pages/content that uses the `categories` taxonomy
3. Attempt to call `get_taxonomy(kind="categories")` in a template (this will throw, even if the taxonomy exists)

**Comment by Keats** [comment]
We could add a param like `required` from `load_data` that returns `null` instead of erroring if it doesn't work

**Comment by timharek** [comment]
This has been added #1598 and from the [docs](https://www.getzola.org/documentation/templates/overview/#get-taxonomy) @Keats 😄
