### ISSUE TITLE
Shortcodes with body containing code blocks are broken

### ISSUE THREAD

**Issue by optozorax** [getzola/zola#1601]
# Bug Report

## Environment

Zola version: 0.14.0

I have shortcode `details.html`:
```html
<details>
<summary>{{summary | markdown(inline=true) | safe}}</summary>
<div class="details-content">
{{ body | markdown | safe}}
</div>
</details>
```

Then I have its usage:
~~~
{% details(summary="my code") %}

```
some code
```

{% end %}
~~~

## Expected Behavior

```html
<details>
<summary>my code</summary>
<div class="details-content">
<pre><code>
some code
</code></pre>
</div>
</details>
```

## Current Behavior

```html
<details>
<summary>my code</summary>
<div class="details-content">
<pre><code>
some code
</code>
</div>
</details></pre>
```

**Comment by optozorax** [comment]
On version `0.14.0` zola returns error to this situation when minification is applied, but in `0.14.1` it just minifies to error position silently, and html brokes.

**Comment by Keats** [comment]
cc @coastalwhite 

0.14.1 contains an updated version of the minifier that doesn't error anymore. The issue is that the `</pre>` is inserted in some random place.
