### ISSUE TITLE
Broken json key access

### ISSUE THREAD

**Issue by ejiektpobehuk** [getzola/zola#1605]
# Bug Report
There is no way to access json fields with `-` symbol in the name.

`load_data` loads json just fine.
`{{ __tera_context }}` shows that fields are there.

Nevertheless while accessing `json_object.bro-ken` zola attempts to access `json_object.bro`.

## Environment

Zola version: 0.14.1

## Expected Behavior

Zola should be able to access json field with `-` sign.

## Current Behavior
Zola loads json but unable to access field where key has `-` sign in it

## Step to reproduce

[MVP repository](https://github.com/ejiek/zola-broken-json)

**Comment by Keats** [comment]
You have to use the array access in that case: `json_object['bro-ken']`

**Comment by ejiektpobehuk** [comment]
It woks, but that seems strange because key `broken` doesn't need array type access.

Is there a good reason why it doesn't work the regular way?
I think this is issue should be resolved by making it work like regular keys or adding documentation to the [load_data section](https://www.getzola.org/documentation/templates/overview/#load-data).

I can handle documentation MR if we are going this route.

**Comment by Keats** [comment]
This cannot work the regular way.
Is it `json_object["bro-ken"]` or `json_object.bro - ken` the math operation? That's the same reason most languages require ascii idents, you cannot know when parsing.
It can be added to the docs though.
