### ISSUE TITLE
Katex cannot switch to a new line and does not render %

### ISSUE THREAD

**Issue by kogeletey** [getzola/zola#1612]
# Bug Report

## Environment

Zola version: 0.14.1

## Expected Behavior
When using the symbol `\\` at the end of the line the elements should be arranged in a column, but due to the peculiarities of zola generation they are arranged in a line.Since zola cleans `\`, there is this problem.

## Step to reproduce
You can view the rendering on my website: [hhttps://fmatch.org/karzok/meta/markdown-syntax/#katex](https://fmatch.org/karzok/meta/markdown-syntax/#katex)
The original file [https://raw.githubusercontent.com/kogeletey/karzok/develop/content/meta/markdown-syntax.md#katex](https://raw.githubusercontent.com/kogeletey/karzok/develop/content/meta/markdown-syntax.md#katex)

**Comment by Keats** [comment]
It looks like anything done to those lines would be done by pulldown-cmark, not by Zola?

**Comment by kogeletey** [comment]
Well, then I will write to the author of the library about this)
