### ISSUE TITLE
`page.updated` get null value, conflict with document

### ISSUE THREAD

**Issue by isunjn** [getzola/zola#1641]
# Bug Report

## Environment

Zola version: 0.14.1

## Expected Behavior
In docs, `page.updated` get the same value with `page.date` if it's not specified:
```
// `updated` will be the same as `date` if `date` is specified but `updated` is not in front-matter
updated: String?;
```

## Current Behavior
But i got a `null` value:
```
"updated": null, "date": "2021-03-30T08:00:00+08:00",
```

## Step to reproduce
Just don't write `updated` in front-matter.

**Comment by Keats** [comment]
Hmm it would make sense to be `null` if it's not set so I think the docs are wrong
