### ISSUE TITLE
[Feature Request] Add CLI option to `build` command to exclude future posts

### ISSUE THREAD

**Issue by koenwoortman** [getzola/zola#1645]
# Feature Request

I'd like to **exclude** pages with a date in the future in my site builds. The use-case I have for this is that I write a page in advance and publish it using a webhook (to Netlify for example).

Zola version: 0.14.1

**Comment by rweir** [comment]
sorry for the necroposting, @koenwoortman, but could you point me to how to use this feature?  `zola build` doesn't seem to have a flag for this, though it does for drafts.

**Comment by koenwoortman** [comment]
Hi @rweir, that's no problem. I haven't had the need for this feature lately. What I meant was something similar to what Hugo is doing by default with excluding content that has a publishing date in the future: https://gohugo.io/getting-started/usage/#draft-future-and-expired-content
