### ISSUE TITLE
[Feature Request] Config flag for checking whether Zola runs in development

### ISSUE THREAD

**Issue by koenwoortman** [getzola/zola#1646]
In my HTML templates there are certain portions of code that I would like to either exclude or include based on whether I am running Zola in development or in production.

A solution that would cover my use-case would be a simple global variable such as `current_path` and `current_url` on which I can check in an if/else statement.

Zola version: 0.14.1

**Comment by Keats** [comment]
You should be able to check `config.mode` for that. It doesn't seem documented though

**Comment by koenwoortman** [comment]
Thanks! That's exactly what I was looking for. I'll close the issue :+1:

What would be a logical place to include this in the docs? I was looking to send a PR, but the docs related to config I could find were more related to options in the config.toml file.

**Comment by Keats** [comment]
I'm not entirely sure, not in the config definition since it's not something user can define. Probably https://www.getzola.org/documentation/templates/overview/ I would say?

**Comment by janopae** [comment]
How does Zola know whether it runs in production or development? Is `config.mode` determined on whether `zola serve` is being used?

Maybe this issue should be reopened until this feature is documented?

**Comment by Keats** [comment]
> Is config.mode determined on whether zola serve is being used?

Yes.
I'll document it tomorrow

**Comment by Keats** [comment]
> Is config.mode determined on whether zola serve is being used?

It depends on the command ran, check/serve/build.
I've added it to the docs in the next branch.
