### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by andreaferretti** [getzola/zola#166]
When trying a simple Gutenberg site generated with `gutenberg init` I get the warning `There is no built-in theme so you will see a white page.`. In fact, I do see a white page.

This warning gives no clue whatsoever how to install a theme. Apparently, [here](https://www.getgutenberg.io/documentation/themes/installing-and-using-themes/) is documented how to install new themes, while [this](https://github.com/Keats/hyde) is the only available theme.

I guess the first start experience could be streamlined, at least by adding the instructions to add the Hyde theme in the warning message

**Comment by Keats** [comment]
Good point, this message was written when Gutenberg didn't have a theme system at all. I'll update it once I've ported a few more themes so it doesn't look a bit ridiculous with only one

**Comment by Keats** [comment]
I've added default templates in the `next` branch so you get information on what to do the first time you run `gutenberg serve` and load the site.

**Comment by Keats** [comment]
Fixed in 0.3.0 that is currently building in travis/appveyor
