### ISSUE TITLE
Add logging to `serve`

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#176]
Going off of this #166, it's a little difficult even with the available theme as to how to actually use themes.  I'm making my own site with a theme that I'd like to eventually publish, but I'm having a bit of difficulty getting started (still getting a white page for some reason).  Unfortunately, the given examples aren't of much help since they all just use templates instead of the theming system.  I'm 99% sure it's user error but debugging is a little difficult!  

It would be nice if `gutenberg serve` could display a little more information (either optionally or all the time) - for instance, when getting a request / rendering a page if it could say what template it was rendering from, etc, to make debugging stuff easier.  Right now, I just get a blank page and I'm lost on what is happening behind the scenes.  Perhaps there's a better way to do this that I haven't found, so let me know!

**Comment by Keats** [comment]
There are only 3 default templates which result in white pages: `index.html`, `page.html` and `section.html`. If you create files with these 3 names in your `templates` directory, there shouldn't be any whitepages anymore.

I could put a `println` when that happens but that would be one warning per page which would fill the terminal if you have many pages.

**Comment by piedoom** [comment]
Okay, thanks!  I guess in that case logging would be a bit overkill.
