### ISSUE TITLE
`serve` should also listen for changes in config.toml

### ISSUE THREAD

**Issue by tvincent2** [getzola/zola#178]
Hello,

The `serve` command currently listens for changes to _content_, _templates_, _static_ and _sass_ directories.
When making changes to _config.toml_, I need to manually restart `serve`, which is a bit annoying. Adding it to the list of watched files would be really convenient.

If you think this idea is interesting, I can try to implement it and propose a PR.

Thanks for making gutenberg!
Thomas

**Comment by piedoom** [comment]
Similar to this request, is there a way to listen for changes while developing a theme? Right now I have to restart every time I make a change.

**Comment by Keats** [comment]
For `config.toml`, I'm less against it than before so a PR implementing it properly would be accepted I think.

For themes, no need for that: just treat a theme as a site. For example https://github.com/Keats/hyde is actually a site on my disk where I'm just not committing markdown/config.toml (see the `.gitignore`). Live reload works as expected in that case, the only thing being different from a theme is the `theme.toml`

**Comment by tvincent2** [comment]
Should the PR be for `master` or `next`?

**Comment by Keats** [comment]
On `next` please

**Comment by Keats** [comment]
@tvincent2 are you managing?

**Comment by tvincent2** [comment]
Hello @Keats ,

Adding `config.toml` to the list of watched files was easy, but I ran into some issues for the rebuild part and I've had no time to work on it in the last month.

Hopefully I should have some time next week so expect either something to review or a call for help. :)

Thomas

**Comment by Keats** [comment]
Let me know if i can help!

**Comment by tvincent2** [comment]
Hello,

I have made some progress but:

- Event detection only works the first time I modify `config.toml`, afterwards nothing happens.
- The rebuild part seems ok but I had to duplicate a lot of code from `Site::new` (all the config/template merge) so that would need some refactoring.
- Livereload does not work, but I honestly did not spend time to look into how it is supposed to work and just copy-pasted blindly. :)

Once I have updated my branch with `next`, I will submit a WIP PR if it is ok. Probably tomorrow.

**Comment by Keats** [comment]
Is there any reason you cannot just create a new `Site` instance? Live reload can't work by design as a change in config.toml will need to reload/re-render the whole site anyway

**Comment by tvincent2** [comment]
Of course I just needed to create a new `Site` instance! Thanks a lot @Keats, I was trying to do overcomplicated things.

It all works a lot better now, all I need to do is to test it a little more and rebase my code with `next`.

**Comment by tvincent2** [comment]
Closing as #206 has been merged. Thanks!
