### ISSUE TITLE
Blocking waiting for file lock on build directory

### ISSUE THREAD

**Issue by NuLL3rr0r** [getzola/zola#179]
I tried to checkout the source code of gutenberg and build it from source using:

    $ cd /opt/
    $ sudo git clone https://github.com/Keats/gutenberg.git
    $ sudo chown -R babaei:babaei gutenberg
    $ cd gutenberg
    $ git submodule update --init
    $ cargo build --release

But, cargo stucks with the following message:

    Blocking waiting for file lock on build directory

I left it alone for half an hour or so, but it won't do anything. Furthermore, the CPU usage is very very low on my system (2 or 3 percent) which indicates it's not build anything.

This is the system I'm building it on (Funtoo Linux):

    $ uname -a
    Linux babaei-pc 4.9.63 #82 SMP Sat Nov 18 18:36:33 +0330 2017 x86_64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz GenuineIntel GNU/Linux

    $ cargo --version
    cargo 0.21.0

    $ rustc --version
    rustc 1.19.0

**Comment by Keats** [comment]
Are you using Cargo from your IDE/text editors? That's usually the cause of that issue: https://stackoverflow.com/questions/39335774/cargo-always-starts-with-blocking-waiting-for-file-lock-on-build-directory

**Comment by NuLL3rr0r** [comment]
I don't. I do it from command-line.

**Comment by Keats** [comment]
Hmm maybe it's worth opening a Cargo issue if you don't have any other tools that could call Cargo. If you close the terminal, `cargo clean && cargo build --release` does it still hang?

**Comment by NuLL3rr0r** [comment]
Aha thanks. That did it. It starts compiling now. But, I face an error soon after in one of the crates. My distribution ships with rustc v1.19.0. Is it compatible or I should install a different version?

    $ cargo clean && cargo build --release
     Downloading num_cpus v1.7.0
     Downloading hyper v0.10.13
     Downloading percent-encoding v1.0.1
     Downloading base64 v0.6.0
     Downloading byteorder v1.1.0
     Downloading safemem v0.2.0
     Downloading sequence_trie v0.2.1
     Downloading base64 v0.7.0
     Downloading pulldown-cmark v0.1.0
     Downloading getopts v0.2.15
     Downloading syntect v1.8.1
     Downloading walkdir v1.0.7
     Downloading bincode v0.8.0
     Downloading fnv v1.0.6
     Downloading plist v0.2.3
     Downloading flate2 v0.2.20
     Downloading onig v1.6.1
     Downloading bitflags v1.0.1
     Downloading yaml-rust v0.3.5
     Downloading same-file v0.1.3
     Downloading xml-rs v0.6.1
     Downloading num v0.1.40
     Downloading num-integer v0.1.35
     Downloading num-iter v0.1.34
     Downloading miniz-sys v0.1.10
     Downloading cc v1.0.3
     Downloading rayon-core v1.3.0
     Downloading rand v0.3.18
     Downloading coco v0.1.1
     Downloading scopeguard v0.3.3
     Downloading either v1.3.0
     Downloading sass-sys v0.4.1
     Downloading pkg-config v0.3.9
     Downloading same-file v1.0.0
     Downloading atty v0.2.3
     Downloading textwrap v0.9.0
     Downloading sha1 v0.2.0
     Downloading slab v0.3.0
     Downloading mio v0.6.11
     Downloading bytes v0.4.5
     Downloading iovec v0.1.1
     Downloading lazycell v0.5.1
     Downloading net2 v0.2.31
     Downloading onig_sys v65.0.1
     Downloading cmake v0.1.27
     Downloading backtrace-sys v0.1.16
     Downloading inotify v0.3.0
     Downloading mio v0.5.1
     Downloading slab v0.1.3
     Downloading bytes v0.3.0
     Downloading nix v0.5.1
     Downloading miow v0.1.5
     Downloading bitflags v0.4.0
     Downloading ws2_32-sys v0.2.1
       Compiling rustc-serialize v0.3.24
       Compiling winapi v0.2.8
       Compiling quote v0.3.15
       Compiling sha1 v0.2.0
       Compiling matches v0.1.6
       Compiling bytes v0.3.0
       Compiling safemem v0.2.0
       Compiling itoa v0.3.4
       Compiling scopeguard v0.3.3
       Compiling unidecode v0.2.0
       Compiling traitobject v0.1.0
       Compiling pkg-config v0.3.9
       Compiling either v1.3.0
       Compiling language-tags v0.2.2
       Compiling yaml-rust v0.3.5
       Compiling unicode-xid v0.0.4
       Compiling percent-encoding v1.0.1
       Compiling fnv v1.0.6
       Compiling version_check v0.1.3
       Compiling modifier v0.1.0
       Compiling bitflags v0.4.0
       Compiling bitflags v0.7.0
       Compiling typeable v0.1.2
       Compiling pest v0.4.1
       Compiling serde v1.0.20
       Compiling libc v0.2.33
       Compiling utf8-ranges v1.0.0
       Compiling humansize v1.0.1
       Compiling slab v0.3.0
       Compiling sequence_trie v0.2.1
       Compiling strsim v0.6.0
       Compiling pulldown-cmark v0.1.0
       Compiling rayon-core v1.3.0
       Compiling regex-syntax v0.4.1
       Compiling log v0.3.8
       Compiling httparse v1.2.3
       Compiling cc v1.0.3
       Compiling getopts v0.2.15
       Compiling term v0.4.6
       Compiling slab v0.1.3
       Compiling void v1.0.2
       Compiling glob v0.2.11
       Compiling lazy_static v0.2.10
       Compiling ansi_term v0.9.0
       Compiling byteorder v1.1.0
       Compiling unicode-normalization v0.1.5
       Compiling cfg-if v0.1.2
       Compiling dtoa v0.4.2
       Compiling unicode-width v0.1.4
       Compiling same-file v0.1.3
       Compiling plist v0.2.3
       Compiling vec_map v0.8.0
       Compiling winapi-build v0.1.1
       Compiling same-file v1.0.0
       Compiling bitflags v0.9.1
       Compiling rustc-demangle v0.1.5
       Compiling num-traits v0.1.40
       Compiling lazycell v0.5.1
       Compiling bitflags v1.0.1
    error: expected ident, found #
       --> /home/babaei/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/lib.rs:423:29
        |
    423 |                               #[allow(deprecated)]
        |                               ^
        | 
       ::: /home/babaei/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/example_generated.rs
        |
    4   | / bitflags! {
    5   | |     /// This is the same `Flags` struct defined in the [crate level example](../index.html#example).
    6   | |     /// Note that this struct is just for documentation purposes only, it must not be used outside
    7   | |     /// this crate.
    ...   |
    13  | |     }
    14  | | }
        | |_- in this macro invocation

    error: Could not compile `bitflags`.
    warning: build failed, waiting for other jobs to finish...
    error: build failed

**Comment by Keats** [comment]
Looks like the minimum version of bitflags is 1.20 :/ (https://github.com/rust-lang-nursery/bitflags#rust-version-support).
Nothing I can do here sadly as it's a sub-dependency (or sub-sub dependency). I should download all releases of rust starting from 1.20 to see what is the minimum version required version though.

**Comment by NuLL3rr0r** [comment]
Thanks, I uninstalled my current version which was shipped with the distro and installed the latest stable (1.21.0) and that solved the issue. I can now happily utilize Gutenberg to build my new website :)

Thanks for this awesome piece of software. Keep up the good work!

**Comment by Keats** [comment]
Thanks a lot!
