### ISSUE TITLE
Live Reload not working when static content is changed

### ISSUE THREAD

**Issue by vikigenius** [getzola/zola#1824]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior
I have an SVG file that I am editing in the static directory. And loading it in my macros like this

`{{ load_data(path="static/icon/github.svg") | safe}}`

When I edit my SVG and save, live reload should happen and I should be able to see my changed SVG without restarting the server.

## Current Behavior
Live reload does seem to happen, but I am still seeing my old SVG with no change

```
Change detected @ 2022-04-12 03:14:35
-> Static file changed /home/void/Library/Documents/void/static/icon/github.svg
Done in 0ms.
```
Restarting the server allows me to see the change.

## Step to reproduce
1. Create SVG and put it in static directory
2. Load the SVG using `load_data` mechanism.
3. Start the server
4. Edit the SVG

**EDIT** Updated the version to 0.15.3 since I could reproduce there as well

**Comment by Keats** [comment]
It's normal: on static changes only the static files are reloaded. Your usecase would require re-rendering all the templates to re-evaluate the Tera fn. If you load them through HTML instead, it should work.

**Comment by vikigenius** [comment]
Ah makes sense. I will try to use the "svg use" and load it instead

**Comment by pinpox** [comment]
> If you load them through HTML instead, it should work.

What do you mean by loading them through html? Is it not possible to keep the svg image in a separate file?
@vikigenius Did you find out how to do it with use? I can't get it to work in combination with css to style the elements

**Comment by Keats** [comment]
> What do you mean by loading them through html? Is it not possible to keep the svg image in a separate file?

Sure, but not through the Tera fn like above. If you load through a normal link/get_url it should work

**Comment by pinpox** [comment]
Sorry, but I don't get it, this is what I'm trying:
```html
<div class="flex-col-md-12">
  <svg>
    <use xlink:href="{{ get_url(path="/img/front.svg") }}"></use>
  </svg>
</div>
```
