### ISSUE TITLE
Show something other than a blank page when no templates/themes configured

### ISSUE THREAD

**Issue by neunenak** [getzola/zola#183]
It's confusing that the default behavior when nothing is configured with Gutenberg is to show a blank page without any text at all, corresponding to the created <name>.md files in content. It would be good if the default behavior was at least to show that text with minimal formatting.

**Comment by Keats** [comment]
I agree, I actually started something similar to the Phoenix/Django page when you first install but I wasn't satisfied with how it looks so I got rid of it.

I'm not entiretly sure if we want a single page for all pages where only the template to overwrite is different ("Create a page.html template in the templates directory to overwrite this template") or render the page content in a basic way? I'm afraid if we actually render the content, this will become basically a default theme that was people would use and want to improve.

If anyone is willing to work on that, the easiest way to add some default templates is to add builtins templates in https://github.com/Keats/gutenberg/tree/master/components/templates/src and register them before there https://github.com/Keats/gutenberg/blob/master/components/templates/src/lib.rs#L27
Lastly, you can remove the lines at https://github.com/Keats/gutenberg/blob/master/components/utils/src/templates.rs#L22-L24
No JS and all CSS should be in the `<head>` tag, no external files

**Comment by BharatKalluri** [comment]
Hello @Keats! I would love to contribute to Gutenberg. How do you like the start page to look like?

I am thinking of making a simple page with a heading which says "Welcome to Gutenberg!" and a link to the docs and gitter room under that. Do you have any suggestions?

**Comment by Keats** [comment]
The gitter room is not active but hopefully we'll get a discourse soon but otherwise yes that's pretty much it.

It would also say a sentence like 

> To modify this template, create a file named `blabla.html` in the templates directory. You will then be able to use the following variables: LINK TO PAGE IN THE DOCS

If you work on that, please do the PR on the `next` branch
