### ISSUE TITLE
Better defaults and conventions

### ISSUE THREAD

**Issue by prasannavl** [getzola/zola#186]
Currently, if either `.md` or `.html` file is inside the `content` without a front-matter, it ends up in an error. I suggest the following to provide a more natural and intuitive experience:

- add `new` command that adds `title`, and `date` with current date. 
- in the absence of front matter, allow the usage of documents without a date, and using the file name as title (with a default formatter for it in `config.toml` - a title cased converting loose [-_] into spaces would be a reasonable default).
- in the absence of front matter on `.html/.htm` files do not process them, instead just copy them - this allows nice colocation, but behavior similar to `static`, which is nicer is many cases, where you want custom html files - but creating a directory tree for just one or two html files that don't need processing is painful. 
- also adding an option in the front matter, on whether or not regular `.md`, and `.html` with front-matter should be processed or not, might be worth giving a though to. (In case of no processing, the front-matter can be stripped). 

I like how simple gutenberg is compared to something like `hugo` that became a monster over time with  documentation that'll take hours to even glance through. Would love to see gutenberg remain with current simplicity.

**Comment by Keats** [comment]
Thanks! Regarding your comments:

- `new` command: this is a rabbit hole I don't really want to go into, `touch` or `cp existing-post.md` is simpler. Most of my usage of Gutenberg is not for blogs so I don't care for the date for example.
- I would argue the filename is very rarely the title of the document,  I'm using the filename for the url mostly and even then I often manually change the url in the front-matter if it would be too long as a filename or want some fancy url scheme
- there's already [assets colocation](https://www.getgutenberg.io/documentation/content/overview/#assets-colocation), do you mean being able to have some random HTML files anywhere in the `content` folder instead?
- can you detail the usecase?

**Comment by prasannavl** [comment]
@Keats, after reading your comments, how about these:

- I do like your approach to not go down the `new` rabbit hole. However, the problem I see is without `date`, building ends up in an error. So, alternatively, how about just using the file creation date to fill up the date automatically, when there is not provided through the front-matter? The idea is just to have defaults that are nice. It doesn't matter if it's a blog or not - the usage of these depends on the templates anyway.
- My rationale with filename is just to have something reasonably ok to fallback on, when there isn't one. (I didn't see if it compiles without one, if it does, then that's fine too)
- Assets colocation - yes. Currently, unprocessed html files work when they go into `static`. However, it's easier to maintain it in the content directory, instead of creating a directory tree for just one or few files. (As long as it doesn't become confusing) - So, as long as the default is to process them with the same pipeline, it shouldn't be confusing. However, a front-matter config to allow bypassing that would make this possible optionally. 
- Same as above. Just for `html`. I don't suppose it makes a lot of sense of md.

**Comment by Keats** [comment]
> However, the problem I see is without date, building ends up in an error. 

It shouldn't be the case, most of my pages don't have dates: https://github.com/Keats/gutenberg/blob/master/docs/content/documentation/content/linking.md for example
Do you have a reproduction for that?

> I didn't see if it compiles without one, if it does, then that's fine too

It does, there is no required field in the front matter, a `+++\n+++` is a valid one

> Assets colocation - yes. Currently, unprocessed html files work when they go into static. However, it's easier to maintain it in the content directory, instead of creating a directory tree for just one or few files. (As long as it doesn't become confusing) - So, as long as the default is to process them with the same pipeline, it shouldn't be confusing. However, a front-matter config to allow bypassing that would make this possible optionally.

That would be a HTML file that doesn't use Tera at all then? I don't really see the use vs just having a almost empty .md file in `content` that has `template = "my.html"` in the front-matter so it fits better in the rest of the site or as co-located assets if you really want your .html to be in the `content` folder (still requires a .md file though)

**Comment by prasannavl** [comment]
> It does, there is no required field in the front matter, a `+++\n+++` is a valid one

Sorry, my bad! It just doesn't compile without a front matter, an empty one at the least. Is there any specific reason why no front-matter isn't allowed? I suppose it would be nicer, if it's just simple `touch x.md`, and have it just work, without adding an empty front matter.

**Comment by Keats** [comment]
> Is there any specific reason why no front-matter isn't allowed?

Precisely to avoid having some random `.md` files being rendered without explicitely asking for it. I sometimes `mv` or `touch` a file at the wrong location and I like that it just doesn't silently try to render it

**Comment by prasannavl** [comment]
Ok, thanks. I suppose, you do prefer to keep it separate in favor of clean separation, against the small convenience of colocating without adding an extra `md` file. Closing.
