### ISSUE TITLE
YAML Front Matter Support

### ISSUE THREAD

**Issue by arjun-menon** [getzola/zola#189]
According to the documentation, the on the [configuration](https://www.getgutenberg.io/documentation/getting-started/configuration/) has to be in TOML, and [page](https://www.getgutenberg.io/documentation/content/page/) files also have to use TOML front matter.

I understand Gutengerg is an "_opinionated_ static site generator", but I think it would be really helpful to have YAML front matter support in Gutenberg. For a lot of people coming from other systems, YAML might be more familiar and comfortable. They are also put through less hassle while migrating to Gutenberg.

I'm new to Rust, but I'd be happy to [learn Rust](https://doc.rust-lang.org/book/second-edition/), and implement this feature and create a PR for it. The [yaml-rust](https://github.com/chyh1990/yaml-rust) library seems like the best fit for the job. What do you think, @Keats?

**Comment by Keats** [comment]
Hey,

TOML-only is definitely one of the opinion of the `opinionated static site generator` as you mention. 
I only want one language to configure things and YAML/JSON are definitely not suited for that imo (and I'm still unsure what YAML is good for, certainly not being human readable).

So while this won't be acceptd in Gutenberg, you should definitely learn Rust, it's a great experience!

**Comment by arjun-menon** [comment]
Are you sure YAML is less readable? I find that there are more extraneous characters I need to type.

Just a quick example.

In TOML:
```toml
name = "Arjun Menon"
```

In YAML:
```yaml
name: Arjun Menon
```

For strings fields, YAML seems more natural and clean. The absence of the string `"` quotes and the choice of `: ` over ` = ` is nice. TOML is a bit more reminiscent of code.

And we should keep in mind that most front matter is composed of string fields.

What do you think?

**Comment by arjun-menon** [comment]
If Gutenberg is really only going to support TOML it might be good to provide a migration that tool that converts YAML to TOML. (If one doesn't exist already.) I could whip one up in Python very quickly.

Another idea I would throw out there is supporting external transformation plugins. If users can keep all their Markdown files changes, and configure a tool that converts YAML to TOML to be transparently run before the file is passed on for processing by Tera & Gutenberg, that would be cool.

**Comment by piedoom** [comment]
Coming from a Ruby background, I have to respectfully disagree.  YAML and TOML used in these situations are so similar that it isn't difficult to learn a new syntax.  While I might like YAML, I think TOML is just fine, and I think it's preferable since it's used elsewhere in Rust.  

As an individual and manual tool, I don't see a great use of a YAML => TOML generator.  However, it could be neat to make some sort of fully automated theme conversion tool.

**Comment by arjun-menon** [comment]
They are indeed both very similar, @piedoom. Maybe that is an argument in favor of supporting it? One significant issue (which I forgot to mention) is that certain Markdown word processors (like [Texts](http://www.texts.io/features/)) only supports YAML front matter. (With **Texts**, there's no easy way to work with TOML. If you open a file containing TOML, and re-save it with no changes, the TOML front matter gets corrupted.)  This obviously isn't Gutenberg's fault, but people using these word processors would have to wait until they're updated to support TOML before considering switching to Gutenberg. Hugo and Jekyll both come with YAML support, and a lot of people might be used to it by now. I don't see any huge positives in religiously/dogmatically dictating very subjective choices like the front matter format.

**Comment by Keats** [comment]
> Are you sure YAML is less readable?

Definitely. I was working on syntect this week, trying to make some new features of the sublime format work and the Sublime syntaxes use YAML: https://github.com/sublimehq/Packages/blob/master/LaTeX/LaTeX.sublime-syntax for example.
As soon as you have non-trivial objects, it becomes very hard to write correctly. We spent a good 1h trying to debug something in syntect that was actually working but it was just missing some space in the testcase.

**Comment by cup** [comment]
https://github.com/getzola/zola/issues/189
https://github.com/getzola/zola/issues/317
https://github.com/getzola/zola/issues/498
