### ISSUE TITLE
Internal Links/Cross References

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#19]
Thanks for this great project!

Is there a way to do internal links similar to hugo's [`ref` and `relref`](https://gohugo.io/extras/crossreferences/)?

**Comment by Keats** [comment]
Thanks!

I was actually looking at that page this morning. It's not doable in Gutenberg yet but is something I want to add. It seems like it would be a 2 separate steps process:

- Add anchors to titles: is it necessary to allow setting a custom anchor or can we just slugify the text
- Add the actual shortcode (#9 tracks the shortcode idea)

I want to do #9 next week but can't promise anything there.

I'll also need to have a look at how other tools like Pelican/Jekyll/etc handle that to see other approaches

**Comment by Keats** [comment]
So I got some apparently working shortcodes in #24.
The current implementation makes shortcode their own block outside of paragraphs though.

One alternative for linking could be using markdown itself and have links like:
```
[a normal link](http://google.com)
[a relative link](./pages/article.md)  <- starting with ./ and pointing to a .md file
```

What do you think?

**Comment by phil-opp** [comment]
> So I got some apparently working shortcodes in #24.

So I could create an `ref` shortcut and then create an internal link through e.g.:

```md
Lorem [ipsum] dolor

{{ ref(id="ipsum", page="pages/test.md") }}
```

which then generates something like:

```md
Lorem [ipsum] dolor

[ipsum]: "/pages/test.html"
```

Or am I understanding something wrong?

> One alternative for linking could be using markdown itself and have links like: […]

I really like it! I always have to look up hugo's `{{% relref "xyz.md" %}}` syntax, so just reusing the existing markdown syntax seems like an awesome idea.

**Comment by Keats** [comment]
For the first case, the shortcode generate HTML, so:
```
{{ ref(id="ipsum", text="My link" page="pages/test.md") }}
expands to
<a href="/my-page-url id="ipsum">My link</a>
```
The issue is that currently you can't have inline shortcodes with my branch: before rendering a shortcode it closes the paragraph it's in, which wouldn't work in the case of links. I'm not sure it's worth making shortcodes work inline, most of the shortcode I can think of outside of links will use their own block (pictures, quotes, videos etc).

I do prefer using markdown links themselves though, so I'll probably go for that

**Comment by Keats** [comment]
The `[a relative link](./pages/article.md)` is in master now.
Do you need the headers anchors? I'm not sure how that works in Hugo, I checked and don't have any anchors whatsoever in my articles.

**Comment by Keats** [comment]
Note that relative links are in 0.0.3

**Comment by Keats** [comment]
@phil-opp I just checked your blog and you use https://github.com/bryanbraun/anchorjs

Adding the id to the headers shouldn't be too hard,  I'm not sure how to handle duplicates though. I don't want to go the Hugo route of adding more non-markdown things in markdown so I'm leaning towards adding a `-1`, `-2`, etc if necessary.

I think we can also make it render a template optionally so if you turn on a `render_title_anchor` (name TBD) in config.toml, it would do what anchorjs is currently doing, but without needing JS. The template itself would be easily replaceable as well.

**Comment by Keats** [comment]
(Sorry for the spam)

Everything in my previous post is implemented in https://github.com/Keats/gutenberg/pull/31
I'm not too sure on the template for the anchor links yet since it will need to be replaced or CSS will need to be written. On the other hand, it means that you can build something like your blog or Github READMEs just by editing a template and adding a bit of CSS, without relying on JS.

What do you think?

**Comment by phil-opp** [comment]
Thanks for keeping me updated!

> Note that relative links are in 0.0.3

Awesome! I'll try to test it in the next few days.

> it means that you can build something like your blog or Github READMEs just by editing a template and adding a bit of CSS, without relying on JS. What do you think?

Sounds great! Automatic anchors are important to me, because I often want to link to a specific section of a post. Does `[a relative link](./pages/article.md#some-anchor)` work?

**Comment by Keats** [comment]
> Sounds great! Automatic anchors are important to me, because I often want to link to a specific section of a post. Does [a relative link](./pages/article.md#some-anchor) work?

If you use #31 yes.

**Comment by Keats** [comment]
(I merged it for now so you'll have to use master to try)

**Comment by phil-opp** [comment]
I finally had time to test it and it works great! Two things that I noticed:

- The link looks like it's relative to the current directory but it's absolute. For example, to link from `content/posts/a.md` to `content/posts/b.md`, the link has to be `./posts/b.md` and not `./b.md`.
- When linking to an internal anchor (e.g. `./posts/b.md#some-anchor`), we could also check if the anchor `some-anchor` exists. (this is just an idea and not really important to me)

Thanks a lot for your work!

**Comment by Keats** [comment]
> The link looks like it's relative to the current directory but it's absolute. For example, to link from content/posts/a.md to content/posts/b.md, the link has to be ./posts/b.md and not ./b.md.

That's intended, I think it makes more sense that way: you can move the file around but the links will stay valid.

> When linking to an internal anchor (e.g. ./posts/b.md#some-anchor), we could also check if the anchor some-anchor exists. (this is just an idea and not really important to me)
Could do, I'll keep it in mind

Thanks!
