### ISSUE TITLE
Multi-User blog support?

### ISSUE THREAD

**Issue by sinistersnare** [getzola/zola#190]
Hi, I currently have an idea for a site, and I was wondering if Gutenberg was able to support such a use-case.

I would like to build a site for me and others, such that we can all have our own blog sub-directories, where we make posts for ourselves, and each blog is separated, and independently viewable.

Would I be able to nest Gutenberg sites, or is this wanted functionality by anyone else?

**Comment by Keats** [comment]
You could use a section per user but there can only be one index page so I'm not sure it would work well if you want a custom index page for each. Would it be different domain name as well? If not you could have something like:

```bash
- content
  - author1
     _index.md  << the index page for author1
     blog-post-1.md << some content
  etc
```
And use the `_index.md` has their index page. You could then do a subdomain redirect from `https://domain-name.com/author1` to `https://author1.domain-name.com` or something similar in nginx for example so the URL feels a bit more like their own site.

**Comment by sinistersnare** [comment]
This would be a shared blog, so they would be under `https://domain-name.tld/blog/authorname`

I want to be able to have regular pages, like an index page, and other subpages outside of the blogs, and I want blogs to be like their own mini-sites, with their own index pages and subpages.

Should that be possible using the directory structure you mentioned? The method for people adding blog-posts and pages will be through Github PR's, so I am not worried about it being a complicated directory structure. In fact, if the directory structure was equal to the page structure ( + _index.md pages), then I would be very happy.

Looking at the content table, it looks possible, but I was mostly wondering about multiple-author support, as I dont see anything about that in the docs. Something like a code in the Front-Matter, or I am not sure :p

**Comment by Keats** [comment]
Yeah then you can just create a section for each author and that should
work without any issues

**Comment by sinistersnare** [comment]
Great, Ill let you know if there are any issues along the way!
