### ISSUE TITLE
Problem with macro usage in themes

### ISSUE THREAD

**Issue by verpeteren** [getzola/zola#192]
I have encountered the following situation while using a theme with macro's.

File: `./theme/something/template/index.html`

```html
{% import "macros.html" as macros %}
<!-- html code goes here, the details of the macro is not important -->
```
File: `./theme/something/template/macro.html`

```html
<!-- macro code goes here, the details of the macro is not important -->
```

```bash
$ gutenberg build
Building site...
-> Creating 5 pages (1 orphan) and 1 sections
Failed to build the site
Error: Failed to render section ''
Reason: Failed to render 'something/templates/index.html'
Reason: Template 'macros.html' not found
```

When I create empty file directly in the templates folder:

```
$ touch templates/macros.html
$ gutenberg build
Building site...
-> Creating 5 pages (1 orphan) and 1 sections
Failed to build the site
Error: Failed to render section ''
Reason: Failed to render 'something/templates/index.html'
Reason: Template 'macros.html' not found
```

However, It seems to work when I duplicate the file directly into the templates directories:

```bash
$ cp themes/something/templates/macros.html  templates/macros.html
$ gutenberg build
Building site...
-> Creating 5 pages (1 orphan) and 1 sections
Done in 50ms.
```

This is a work around, but I would like to distribute the macros together with the theme.
What am I doing wrong or what can I do to solve this problem?

**Comment by Keats** [comment]
Try the next branch, I believe this is already fixed.

**Comment by verpeteren** [comment]
Indeed, it is working fine in the next branch.

My apologies: somehow I overlooked these two issues:

[X] https://github.com/Keats/tera/issues/235
[X] https://github.com/Keats/gutenberg/issues/185

I'll close this issue. Thanks
