### ISSUE TITLE
Implementing custom Tera filters

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#193]
I'm creating a theme, and I need a truncate filter.  The issue on Tera [shows it is in progress](https://github.com/Keats/tera/issues/46#issuecomment-346877065).  In the meantime, is there a way one can create a custom Tera filter for Gutenberg without needing to modify and rebuild Gutenberg?

Edit:  I experimented by simply writing in `trucate` as I would any filter and it seems to be implemented, although the documentation has not yet been updated to my knowledge.

**Comment by Keats** [comment]
Not possible no as it would require a Rust compiler along with Gutenberg. The best way would be to add the `truncate` filter to Tera as the next release of Gutenberg will get the next version of Tera.

**Comment by piedoom** [comment]
I'm sorry if I'm mistaken, but it seems the truncate filter already works with Gutenberg.

**Comment by Keats** [comment]
It is actually, I forgot to add it to the docs though. I added the docs in the `0.11` branch

**Comment by piedoom** [comment]
Great!  Thanks.  I'll close assuming docs will be updated soon.

**Comment by lukehsiao** [comment]
Is it still the case that custom tera filters must be directly compiled into zola?

**Comment by Keats** [comment]
Yep, filters have to be written in Rust.
