### ISSUE TITLE
Inline Markdown filter?

### ISSUE THREAD

**Issue by remexre** [getzola/zola#197]
I'm trying to port a site from hugo to gutenberg, and I'm encountering a difference between hugo's `markdownify` and gutenberg's `markdown` -- `markdown` wraps the text in a `<p>`. I'm trying to create a list of items whose names are in Markdown, so I want it without. I'm trying to turn

```
"Using `map`, `filter`, and `fold` instead of `for`"
```

 into

```html
Using <code>map</code>, <code>filter</code>, and <code>fold</code> instead of <code>for</code>
```

rather than

```html
<p>Using <code>map</code>, <code>filter</code>, and <code>fold</code> instead of <code>for</code></p>
```

**Comment by Keats** [comment]
I would say wrapping in a `<p>` is the correct behaviour here, and is what https://github.com/google/pulldown-cmark does.
There could be an option added to remove the trailing/leading `<p></p>` though, I'd take a PR for that

**Comment by piedoom** [comment]
This would be a very nice addition, IMO.  In my theme, I currently have to strip `<p>` tags from images in order to remove padding.

**Comment by Keats** [comment]
Just to be sure, we are only talking about the `markdown` filter used in templates and not the content right?

**Comment by remexre** [comment]
Yep (on my end, at least)

**Comment by Keats** [comment]
@remexre @piedoom does the commit above gives what you need?

**Comment by Keats** [comment]
Another ping as I can't find any `markdown` filter call in https://github.com/piedoom/feather @piedoom @remexre
