### ISSUE TITLE
Cleanup output folder when stopping gutenberg serve

### ISSUE THREAD

**Issue by Keats** [getzola/zola#199]
It currently leaves the output folder behind which can cause people to publish the local dev version instead of the actual one.

**Comment by BharatKalluri** [comment]
Do you mean, Gutenberg should delete the public folder after stopping serve?

**Comment by Keats** [comment]
Yes, to somehow listen for CTRL+C and rm the public folder when it happens

**Comment by Keats** [comment]
@BharatKalluri are you working on that?

**Comment by BharatKalluri** [comment]
Sorry , but I could not find any way to catch a quit event for clap.rs

**Comment by Keats** [comment]
I believe something like https://github.com/Detegr/rust-ctrlc can be used rather than going through clap.

**Comment by BharatKalluri** [comment]
Hey @Keats ,
I am sorry, but I am still not able to figure how to handle it. I still need to read a bit about threads. Please feel free to assign this issue to somebody else :-)

**Comment by Keats** [comment]
@BharatKalluri the commit above implements it, where did you have an issue? AFAIK there's nothing thread related.
It still needs to be tested on windows though
