### ISSUE TITLE
Improve the experience when developing a theme

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#202]
I have a couple issues with the current methods of theme development.  You gave a [suggestion in another thread](https://github.com/Keats/gutenberg/issues/178#issuecomment-345507821) of a workaround you developed, but I have some concerns.  Because we're adding stuff to a `.gitignore`, that theme-ing process isn't super reproducible for contributors.  Several markdown content files also need to be reproduced.  I eventually gave up on this method, as I often work on new/different computers with different setups, and it got bothersome.  

Currently, I'm recursively cloning my main site [vaporsoft](https://github.com/piedoom/vaporsoft) and editing the theme git submodule, and restarting the server every time I make a change to the theme.  That's admittedly kind of a dumb method, but it was easier for my workflow.  

I think this is important as - out of all the sites listed so far with custom styles - only mine actually uses themes instead of just hardcoding templates (which are difficult for others to extract and use).  I think the community behind this project can thrive more if greater attention is paid towards theme development.

I don't have specific answers that are right or wrong, but I have a couple of ideas to consider:

- It would be nice if there was a subcommand for creating a theme framework.  I understand it's just as simple as renaming and deleting a few files from `gutenberg new`, but that first barrier of effort might deter a lot of potential theme developers.   Maybe just `gutenberg new --theme mytheme` could work.

- It would be nice if after creating a theme, the user can just navigate to the root directory and run `gutenberg serve`, without need for any extra files.  In place of `page.content` and other similar variables,
placeholder content with all markdown elements could exist.  Perhaps these variables could be overridden too?

These ideas might be totally against what you're trying to achieve here, but I thought I might as well share my two cents!

**Comment by Keats** [comment]
The suggestion to add things to gitignore was actually bad as you can safely commit content/config.toml as these will be ignored by gutenberg when used as a theme. Committing everything should solve the reproducible aspect.

The only difference between a theme and a site are the creation of a `theme.toml` file, which I don't think is worth a new command. It could potentially be added as part of the questions in `gutenberg new` though.

For the second point, do you mean having fake pages with fake markdown content? The issue with that is that gutenberg doesn't know the kind of site you are trying to make so if you are making a gitbook theme for example (which I'm doing), the structure/content/front-matter will be very different from a blog.

**Comment by piedoom** [comment]
> Committing everything should solve the reproducible aspect.

Okay!  That solves a lot of problems, and I'll probably end up doing that in my own repo.  

> For the second point, do you mean having fake pages with fake markdown content?

That's true - I'm not sure there's a good method for that other than the first solution you mentioned.

I think expanded docs on themeing instead would be a welcome addition, as it's a little vague right now. I'm not sure what the progress/changes are for the site in `next` but I'll take a look.

**Comment by Keats** [comment]
> Okay! That solves a lot of problems, and I'll probably end up doing that in my own repo.

I ended up committing everything for my themes and I confirm it's much nicer if someone else want to pick it up. This way you can also have test pages with accurate things rather than lorem ipsum: a photo gallery content for example will be very different from a gitbook.

I'll write a bit more in the docs about that either way

**Comment by piedoom** [comment]
Sounds good!  If any assistance is needed with docs I would be happy to help, too.

**Comment by Keats** [comment]
I've created a `docs-udpate` branch where I'm planning to fix the issues in https://github.com/Keats/gutenberg/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Improved+docs%22

I'd be happy with help on the themes page or the deploy one as you already wrote an article about it

**Comment by Keats** [comment]
A bit improved in the current site but I welcome any improvements.
