### ISSUE TITLE
Serve: Updating short codes does not re-render shortcode users

### ISSUE THREAD

**Issue by FreeMasen** [getzola/zola#204]
If we started out with something like this.
## content/blog/hello_world.md
```markdown
+++
+++
{{ hello_world() }}
```

## templates/shortcodes/hello_world.html
```html
<div id="hello-world">
  <h1>Hello World></h1>
</div>
```

If I update `hello_world.html`, the page generated by hello_world.md is not updated.

**Comment by Keats** [comment]
Somewhat related to https://github.com/Keats/gutenberg/issues/122

It's a bit hard to test though so looking for ideas. Global functions have the same issue afaik but looking at the code in `rebuild.rs`, a change in `hello_world.html` should re-render everything.

Thanks for the report

**Comment by Keats** [comment]
I have it fixed locally but I noticed another issue while fixing it. It will be in the next version either way
