### ISSUE TITLE
Make content::Section hold references

### ISSUE THREAD

**Issue by Keats** [getzola/zola#205]
For `Section::pages`, `Section::ignored_pages` and `Section::subsections`.

This is to avoid having to clone the pages/section everytime a change is made in some cases, when `populate_section` is called.
Note that this might require a significant refactoring and the `get_section` global fn will not work with references due to lifetime issues so I'm not entirely sure what to do there. I think using `Cow` instead of references could help there.

**Comment by Nazek42** [comment]
I'll take a crack at it. This does seem like a job for `Cow`.

**Comment by Keats** [comment]
Just for everyone reference (including mine): Tera global fn types return a `Sync+Send` (https://github.com/Keats/tera/blob/master/src/builtins/global_functions.rs#L9) that was there to work with hyper (https://github.com/Keats/tera/blob/7725a6e71862361d48e58e47b4251c79396956f2/examples/http.rs). 

I didn't really follow the development of web servers/framework so maybe there are ways around it and `Sync+Send` is not actually needed (TODO: see how Rocket/actix/gotham/plain hyper etc work/would work with Tera). If it turns out to be unneeded we can change that in a major version in Tera. I'm thinking maybe just Sync is enough?

**Comment by Keats** [comment]
@Nazek42 did you make some progress?
