### ISSUE TITLE
Support custom templates per section and categories

### ISSUE THREAD

**Issue by sebasmagri** [getzola/zola#21]
I want to use a combination of sections and categories to create a custom taxonomy with different types of pages, each one using it's own layout/template.

**Comment by Keats** [comment]
Sections will use `section.html` as default template but you can change it by setting the `template` attribute in a `_index.md` front-matter.
Do you have an example of what you want to do? I'm not entirely sure I understand

**Comment by sebasmagri** [comment]
@Keats will posts that belong to a section use the `section.html` template? Can I have one `section.html` per section?

I want to have different kind of posts with different `[extra]` metadata and different layout and styles, so I was wondering I could use different sections for them having different templates for each section.

**Comment by Keats** [comment]
Pages are separate from sections, you can't automatically apply a template to all pages in a section right now. All the data you put in the front-matter of a `_index.md` file only applies to the index page of that section. This might change once sorting per section etc is added but not right now.

You can have as many templates as you want, for example the following:

```
tutorials
|- _index.md  // could have tutorials.html as template for the index
help
|- _index.md // could have help.html as template for the index
```

All pages will default to `page.html` as template but you can override it on a case by case basis by setting the `template` variable in their frontmatter

**Comment by sebasmagri** [comment]
Got it. Sorted it out this way.
