### ISSUE TITLE
incorrect date value leads to an unhelpful panic

### ISSUE THREAD

**Issue by jsdw** [getzola/zola#210]
First off, thank you for gutenberg - I have been using it to build my personal site and it's been a pleasure to work with!

Something I have just noticed - if you enter a date in an incorrect way in the front matter for a page, you get a panic which does not point you in the direction of the issue at all.

I accidentally got the month and day the wrong way around and so in my attempt to write todays date I put:

```
date = "2018-14-01"
```

This leads to (with RUST_BACKTRACE enabled):

```
Building site...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:335:20
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: rayon::slice::quicksort::partition
  10: rayon::slice::quicksort::recurse
  11: content::sorting::sort_pages
  12: site::Site::sort_sections_pages
  13: site::Site::populate_sections
  14: site::Site::load
  15: gutenberg::cmd::serve::serve
  16: gutenberg::main
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start
```

Fortunately it did not take me long to notice my error, but it could have been much worse :)

**Comment by Keats** [comment]
Woops thanks for the report, I'll have a look

**Comment by Keats** [comment]
The commit above solves the issue by using actual TOML dates instead of string. I don't know why it was using strings in the first place but that will be rectified in the next version since it's a breaking change (ie remove quotes from all dates in the front-matter if you are using the `next` branch)
