### ISSUE TITLE
Add Proxy config variable

### ISSUE THREAD

**Issue by FreeMasen** [getzola/zola#213]
To allow for an easier time developing a solution that might use a static file server and REST endpoints, it would be nice to have the serve command proxy requests that don't match on the static route to a configurable port.

A good use for this would be for developing a contact page, that would need to handle a HTTP Post request with the form's contents. Currently these need to be debugged separately, to avoid CORS issues with the REST request. It would be nice to have a config variable or "proxy_port" that would forward requests/responses to/from that port on the localhost.

**Comment by Keats** [comment]
Hmm that seems like it's easier to add CORS when needed on your server for localhost no?

**Comment by FreeMasen** [comment]
In the past I have had a difficult time setting up CORS that works in Chrome/Firefox, it would also mean that the form `action` attribute would need to be modified from debug to release builds. I have spent a little time over the past few months trying to get some kind of proxy behavior out of hyper and the complexity seems much greater than the scope of this project.

Maybe a better route would be to have a `watch` sub-command that just builds on file change, essentially the same behavior as `serve` but no server needs to start and no script needs to be injected. While it is still two processes, it would reduce the need for making changes from debug to release.
