### ISSUE TITLE
move "Example sites" section to dedicated area

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#214]
With the growing amount of sites using Gutenberg (yay!) the README.md section is getting a bit long.  It might be a good idea to create a separate `md` file or wiki for listing all the sites so the main readme doesn't become cluttered.

**Comment by Keats** [comment]
I think I'll make a page for that in the docs to avoid that (Showcase or something), thanks for the issue

**Comment by ozkriff** [comment]
> I think I'll make a page for that in the docs to avoid that (Showcase or something), thanks for the issue

Was this implemented? This file is hard to find on both https://getzola.org and the GitHub repo.

**Comment by Keats** [comment]
No, I ended up moving it to a separate .md in the repo but not in the site itself
