### ISSUE TITLE
Build error with nightly Rust

### ISSUE THREAD

**Issue by Calinou** [getzola/zola#215]
**OS:** Fedora 27
**rustc version:** `rustc 1.25.0-nightly (97520ccb1 2018-01-21)`
**Gutenberg version:** Git https://github.com/Keats/gutenberg/commit/038fc31233cb3afd1caf6dd43b768ff474f8623e

The following build error occurs when running `cargo build` or `cargo build --release`:

```
error[E0619]: the type of this value must be known in this context
  --> components/content/src/file_info.rs:11:42
   |
11 |         let component = section.as_ref().to_string_lossy();
   |                                          ^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `content`.
```

Stable rustc (`rustc 1.23.0 (766bd11c8 2018-01-01)`) does not have this issue and builds Gutenberg successfully.

**Comment by Keats** [comment]
That's https://github.com/rust-lang/rust/issues/47451
I keep the current code around to test if it's fixed in an upcoming nightly

**Comment by Keats** [comment]
Looks like the change is here to stay, I pushed a fix to the `next` branch
