### ISSUE TITLE
Networking/Docker issues regarding interface & base_url

### ISSUE THREAD

**Issue by andrewzah** [getzola/zola#221]
When running in docker, I need to use --interface 0.0.0.0 to access the site from outside the container, but that also overrides base_url.

If you look at src/cmd/serve.rs - [create_new_site](https://github.com/Keats/gutenberg/blob/master/src/cmd/serve.rs#L84) - one overrides the other.

---

Ergo when running serve for example, it should be possible to set both the interface and the base url.

Something like `gutenberg serve --interface 0.0.0.0 --base-url 127.0.0.1` should be available, or some option within `config.toml`.

**Comment by Keats** [comment]
Hmm I didn't think about that usecase but that's definitely something to fix.
Happy to get a PR for that or i'll take a look next week.

**Comment by andrewzah** [comment]
I can take a crack at it.
Yesterday I [made a (testing) commit](https://github.com/azah/gutenberg/commit/4c8bdfd3e7297311f1fb5de336ebca0f634a7139) changing a few things and adding a `--base-url` flag to `serve`.

It made the generated links follow the base_url, but then in Docker it became unreachable.

**Comment by andrewzah** [comment]
Actually nevermind, I just didn't change the base_url in create_new_site.

So it's reachable via docker (0.0.0.0), but links get set to 127.0.0.1.

**Comment by andrewzah** [comment]
I'll work on a proper PR now - if there's anything I should keep in mind regarding this, let me know.

**Comment by Keats** [comment]
Thanks for that! I believe only the serve command needs to be updated and if you the change should be documented in https://github.com/Keats/gutenberg/blob/master/docs/content/documentation/getting-started/cli-usage.md

**Comment by azah** [comment]
So if I make base_url optional as a flag (in cli.rs), is it possible to read from the config.toml there?
Otherwise I would have to supply a default address, rendering the config.toml's base_url useless.

**Comment by Keats** [comment]
It's in 0.3.1
