### ISSUE TITLE
feature request: permalink without port and/or be able to specify port in permalink

### ISSUE THREAD

**Issue by andrewzah** [getzola/zola#224]
Again regarding docker, permalinking breaks if one uses a proxy.
E.g. I proxy :80 -> :1111, but `page.permalink` will return `http://baseurl.com:1111/`.

I can submit a PR if you let me know the relevant file(s), or I can find it myself ~tomorrow ish.

**Comment by Keats** [comment]
Hmm that doesn't sound trivial to use from a user pov.

Maybe it it could check whether the `base_url` given ends with a number (like --base-url 127.0.0.1:80) and if tit's the case doesn't append the port to the base_url in `src/cmd/serve.rs:86`. This way everything works with almost no changes in Gutenberg code and there aren't 2 `port` options

**Comment by andrewzah** [comment]
That seems better, yeah, if it just checked for a port and supplied a default if there wasn’t one.
Although I realized that this is a relatively obscure use case. Not sure if anyone might find it particularly useful. 
		
		

		
	




On Fri, Feb 2, 2018 at 12:17 PM -0500, "Vincent Prouillet" <notifications@github.com> wrote:












Hmm that doesn't sound trivial to use from a user pov.


Maybe it it could check whether the base_url given ends with a number (like --base-url 127.0.0.1:80) and if tit's the case doesn't append the port to the base_url in src/cmd/serve.rs:86. This way everything works with almost no changes in Gutenberg code and there aren't 2 port options

**Comment by Keats** [comment]
I think it's a fairly simple change that only affects people looking for that so it should be safe to add, otherwise using Gutenberg in a Docker image might not work right? It's fairly niche as you say though so no hurry

**Comment by Keats** [comment]
Thinking about it, it could be nice to streamline `interface` and `base_url` the same way, aka to take optional ports and remove the `port` argument.
I'll leave it here to think for the next major release

**Comment by Keats** [comment]
Hmm completely forgot about that and released 0.4.0
Is that still an issue?

**Comment by andrewzah** [comment]
Nah. I was being dumb and using gutenberg serve in Docker, instead of just hosting the generated files with Nginx or Caddy.
