### ISSUE TITLE
Allow code highlighting in templates

### ISSUE THREAD

**Issue by svenstaro** [getzola/zola#226]
I would really like to use code highlighting in templates but I don't think that's currently possible. Consider this a feature request.

**Comment by Keats** [comment]
We discussed it on Gitter and in the end it worked without it by putting the code in the `_index.md` for the landing page.
I think it's still useful though, mostly in a shortcode if you want to customise the output a bit.

**Comment by Keats** [comment]
Doesn't seem to be much need for that apparently, closing.
