### ISSUE TITLE
Incorrect parsing of shortcodes with blank lines

### ISSUE THREAD

**Issue by mdaffin** [getzola/zola#229]
The following content file parses as expected:

```
+++
+++

djsalndbjahf jshfj hsf jkhds k fhds sd

{{ youtube(id="dQw4w9WgXcQ",
           autoplay=true) }}

djsalndbjahf jshfj hsf jkhds k fhds sd

{{ youtube(id="dQw4w9WgXcQ",
           autoplay=true) }}

djsalndbjahf jshfj hsf jkhds k fhds sd
```

But if you add a blank line in the shortcode like so:

```
+++
+++

djsalndbjahf jshfj hsf jkhds k fhds sd

{{ youtube(id="dQw4w9WgXcQ",

           autoplay=true) }}

djsalndbjahf jshfj hsf jkhds k fhds sd

{{ youtube(id="dQw4w9WgXcQ",
           autoplay=true) }}

djsalndbjahf jshfj hsf jkhds k fhds sd
```

It causes the parser to incorrectly parse to skip the first `autoplay=true) }}` and instead see the following as the shortcode:

```
{{ youtube(id=\"dQw4w9WgXcQ\",djsalndbjahf jshfj hsf jkhds k fhds sd{{ youtube(id=\"dQw4w9WgXcQ\",autoplay=true) }}"
Match { text: "{{ youtube(id=\"dQw4w9WgXcQ\",djsalndbjahf jshfj hsf jkhds k fhds sd{{ youtube(id=\"dQw4w9WgXcQ\",autoplay=true) }}
```

*from a `println!("{:?}", &text);` added to line 137 in `components/rendering/src/markdown.rs`*.

I expected it to simply ignore the blank lines.

**Comment by Keats** [comment]
The markdown rendering (including shortcodes, see #165) will be rewritten for the next major version which should be soonish, I'll add that to the test cases.

Thanks for the report!
