### ISSUE TITLE
Get section content by tag?

### ISSUE THREAD

**Issue by swsnr** [getzola/zola#230]
Hello,

in the root "_index.md", can I somehow get content of a specific section by a specific tag?  I'd like to have a "featured content" list, filled with articles from the "stories" section which have the "featured" tag.

Is this possible in gutenberg?

**Comment by Keats** [comment]
Not by tag directly but you can use the get_section global fn to get the
desired section and then iterate on its pages looking for pages that have a
featured tag

**Comment by swsnr** [comment]
@Keats Thanks, that's sufficient enough for me :)

**Comment by swsnr** [comment]
@Keats I had time to continue on this, and got stuck at the next step:  I have a macro to render a list of posts; the macro takes the list of posts to render as single argument.  

I can now get the list of posts from `get_section(name="stories").pages`, but how to I filter the list of pages I get by a specific tag to pass it to my "list of posts" macro?  I haven't found anything in the gutenberg/teal documentation to help me with this task.

**Comment by Keats** [comment]
is it not possible to pass the tag you want to show as arg to the macro and iterate?

Something like:

```jinja2
{% macro featured render_pages_with_tag(pages, tag) %}
    {% for p in pages %}
        {% if p.tags is containing(tag) %}
          Render the page, could be another macro if it needs to be reused elsewhere
        {% endif %}
    {% endfor %}
{% endmacro %}
```

**Comment by swsnr** [comment]
I must admit I hadn't thought of this, thanks.

Still, I don't like this approach; it doesn't seem to compose well… what if I'd like to filter by category instead?  Or by date?  In each case I'd need to extend the macro; if I could just filter a list of items I wouldn't need to touch the macro at all to add a new way of filtering pages.
