### ISSUE TITLE
Syntax highlighting: line numbers

### ISSUE THREAD

**Issue by PhilipDaniels** [getzola/zola#232]
It would be nice to have an option to turn on line numbering for the syntax highlighting.

**Comment by Keats** [comment]
Definitely something I'd like to have but needs to #160 and #165 first

**Comment by Keats** [comment]
A tricky thing is finding a way to make the line numbers match the theme being used

**Comment by PhilipDaniels** [comment]
Yes, I was a bit surprised to see there are no css classes used for the code, it's all inline styles. Makes me think that this should actually be implemented upstream, in syntect. I did a quick search in that repo and there are no issues about it.

**Comment by Keats** [comment]
Closing in favour of the discourse post https://zola.discourse.group/t/highlighting-improvements/19
