### ISSUE TITLE
Themes folder is not monitored

### ISSUE THREAD

**Issue by PhilipDaniels** [getzola/zola#233]
I am developing a new theme. I have forked a theme and cloned it directly into my themes folder. When I tweak the sass etc, the changes are not picked up automatically so I have to restart gutenberg.

Not a show-stopper, but a bit of a time-waster.

**Comment by piedoom** [comment]
Check out my repo - https://github.com/piedoom/feather

Keats recommends treating a theme as a blog so files can easily be reloaded.  Also check out this issue - https://github.com/Keats/gutenberg/issues/202

**Comment by Keats** [comment]
What @piedoom said. 
Themes are intentionally not watched. If you want to modify a theme, you should overwrite a theme file by creating it in your templates directory. If you really want to edit in the themes directory, you should be able to `cd` in it and run `gutenberg serve` if the themes is set up like recommended (going to write a page about that soon)
