### ISSUE TITLE
Saving files into the content directory can generate build errors

### ISSUE THREAD

**Issue by PhilipDaniels** [getzola/zola#235]
I'm using the [yEd](https://www.yworks.com/products/yed) program to generate some diagrams for my website (using the colocated assets, which is working great by the way!).

The original editable diagram is in a format called `graphml`. I export this to PNG to make an image for my website. I'm storing the original `.graphml` file in the content directory along with the PNG image, since it's best to keep everything together.

Saving a new graph into the directory while Gutenberg is watching can generate errors:

```
-> Content changed C:\Users\Phil\repos\rsforcs\site\content/introduction\major_differences\rust_tree.graphml
Failed to build the site
Error: Couldn't find front matter in `C:\Users\Phil\repos\rsforcs\site\content/introduction\major_differences\rust_tree.graphml`. Did you forget to add `+++`?
Done in 0ms.

Change detected @ 2018-02-20 20:44:24
-> Content changed C:\Users\Phil\repos\rsforcs\site\content/introduction\major_differences\rust_tree.png
Failed to build the site
Error: stream did not contain valid UTF-8
Done in 0ms.
```

Restarting Gutenberg does perform a successful site build and no errors are reported.

I really want the ability to ignore certain file types during the build, but I will log another issue for that.

**Comment by Keats** [comment]
Looks like a bug and it should be an easy fix!
