### ISSUE TITLE
Option to ignore certain file types in the content directory

### ISSUE THREAD

**Issue by PhilipDaniels** [getzola/zola#236]
It would be nice to have an option whereby I could specify a file pattern(s) for files to be ignored in the content directory. A glob would probably be sufficient, full regex support would be overkill. Ignored would mean "do not try to copy to the public directory, parse or process in any way".

For example

    IgnoredContent=["*.graphml", "*.iso", "*.whatever"]

This would mean I could co-locate primary files and exported content in the same directory - good for source control and maintainability purposes.

**Comment by Keats** [comment]
Good idea!

**Comment by PhilipDaniels** [comment]
Here, right? https://github.com/Keats/gutenberg/blob/24fad7a5e8f97b053a8188c65bf11b3f9e465d41/components/utils/src/fs.rs#L44

**Comment by Keats** [comment]
I would rather keep that as is and filter the results in https://github.com/Keats/gutenberg/blob/master/components/content/src/page.rs#L134 as we have access to the `Config` struct where the ignored patterns would be.

**Comment by PhilipDaniels** [comment]
OK! I will take a bash at this this weekend, life permitting.

**Comment by Keats** [comment]
Cool! If you do it, please do the PR on the `next` branch.

**Comment by PhilipDaniels** [comment]
Closing, since you merged my PR. Thanks!
