### ISSUE TITLE
Default Sorting is None

### ISSUE THREAD

**Issue by CaptainKraft** [getzola/zola#237]
I believe #47 made it so that the default sort is none rather than by date. Perhaps the default should be date? It threw me off when my posts weren't in "correct" blog order by default.

**Comment by CaptainKraft** [comment]
I just found out that after `gutenberg build` my posts are out of order. If I `gutenberg serve` they get put into correct order.

**Comment by Keats** [comment]
> Perhaps the default should be date?

I don't think there should be a default, and if there was one that would probably be based on the filename as it's the only default sorting that would work regardless of content/front-matter.

> I just found out that after gutenberg build my posts are out of order. If I gutenberg serve they get put into correct order.

Are you sure it's not just random ordering? Ie try starting `gutenberg serve` a few time. `build` and `serve` call the exact same methods to load/render the site so I can't see how one of them would sort without being asked to.

**Comment by CaptainKraft** [comment]
Looks like you're right, it is random. How do I force sorting by date?

**Comment by Keats** [comment]
Set the `sort_by` of your section to date: https://www.getgutenberg.io/documentation/content/section/#sorting

**Comment by CaptainKraft** [comment]
Alright, I think I finally get it. I've added `_index.md` to my content directory alongside all my blog posts. That file contains
```
+++
sort_by = "date"
+++
```

Which tells Gutenberg to sort all the posts in the content directory by date.

Do I understand this correctly now?

**Comment by Keats** [comment]
Yep exactly!

**Comment by CaptainKraft** [comment]
Thanks for the help.
