### ISSUE TITLE
Pagination of set section

### ISSUE THREAD

**Issue by Libbum** [getzola/zola#245]
A number of the blogs in [EXAMPLES.md](https://github.com/Keats/gutenberg/blob/master/EXAMPLES.md) (as well as my current attempts) follow a format of having 

```
content
- about.md
- posts
  - _index.html
  - blog1.md
  - blog2.md
```
or similar, then in `templates/index.html` move the `posts` section to the forefront and loop over the result to print summaries. For example:

```django
{% set section = get_section(path="posts/_index.md") %}
{% for page in section.pages %}
    <li>{{ page.title }}</li>
{% endfor %}
```

Is it possible to paginate the results of `section` here? As far as I can tell this isn't possible at the moment with this kind of file layout, but perhaps I'm missing something.

**Comment by Keats** [comment]
It is indeed not doable as the pagination is only added when rendering the section itself, which is not the case when calling `get_section` in the index template. If you want pagination on the index page, you will need to have your posts at the root of content like in https://github.com/Keats/even

**Comment by Libbum** [comment]
Sure thing! Thanks for the details.
