### ISSUE TITLE
Consider changing the summary line in the readme?

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#248]
The summary in the README.md is "An opinionated static site generator written in Rust", which is what appears at https://www.staticgen.com/ .

I don't know how many people use that site to shortlist the static generators that they take a closer look at, but I did, and I initially omitted Gutenberg from my shortlist (my mistake!) because summaries like "A Fast and Flexible Static Site Generator" (Hugo's) seem more appealing. Only the recent post to r/rust caused me to look at Gutenberg.

I'm curious; in what sense is Gutenberg "opinionated" relative to Jekyll, Hugo, (maybe Cobalt?) etc.?

Would something like "A fast, flexible and easily installed static site generator written in Rust" make sense as the focus of that summary line? To me (and others I've noticed) having only a single binary executable to install is hugely appealing and seems worth calling out. It seems to me to be one of your unique strengths, and is highly desirable for small orgs who need to get fairly non-tech content authors set up to create content for a site.

**Comment by Keats** [comment]
Good point.
The current taglines of the site are:
```
Your one-stop static site engine
Forget dependencies. Everything you need in one binary.
```

which emphasizes the single binary as well.
I should update the README and the github description

**Comment by piedoom** [comment]
I agree, single binary was the initial selling point for me as well

**Comment by Keats** [comment]
I updated the Github description, if someone can think of a better one for the README otherwise I'll take the same

**Comment by jwatt** [comment]
I think having "fast" in there would be nice too, since that's another very important feature IMO.

**Comment by Keats** [comment]
A fast static site generator in a single binary with everything built-in. ?

**Comment by jwatt** [comment]
Heh. It's kinda hard to get all the points into a nice neat, succinct summary. That sounds like a good improvement to me though.

**Comment by jwatt** [comment]
Related: you might consider adding some/all of the following github "topics" to make it more findable?:

static-site-generator blog-engine cms content-management-system documentation-tool markdown markdown-to-html

**Comment by Keats** [comment]
Updated the tagline.
I'll update the topics later, I'm still not sure what they are used for honestly

**Comment by Keats** [comment]
Done, thanks for that!

**Comment by jwatt** [comment]
I assumed that staticgen.com was pulling the data they show from the projects they list, and that it would update automatically. But it looks like this file in their repo needs updating:

https://github.com/netlify/staticgen/blob/master/source/projects/gutenberg.md
