### ISSUE TITLE
Some characters break shortcodes

### ISSUE THREAD

**Issue by NuLL3rr0r** [getzola/zola#249]
Let's say I have a shortcode named quote:

```
<blockquote>
    <p>
        {{ body }}
    </p>

    -- {% if href %}<a href="{{ href }}">{% endif %}{{ author }}{% if href %}</a>{% endif %}
</blockquote>
```

If I call this short code like this:

```
{% quote(author="C++ Standard Core Language Defect Reports and Accepted Issues, Revision 82, delete and user-written deallocation function") %}
...if the value of the operand of delete is the null pointer the operation has no effect.
{% end %}
```

I'll get this on the terminal when I try to run Gutenberg:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', /checkout/src/liballoc/vec.rs:1551:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

If I replace those commas, with something else or remove them it works. It seems it parses those commas as separators for other arguments or something like that.

Now, If I call my shortcode like this:

```
{% quote(author="C++ Standard Core Language Defect Reports and Accepted Issues; Revision 82; delete and user-written deallocation function", href="http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#348") %}
...if the value of the operand of delete is the null pointer the operation has no effect.
{% end %}
```

The generated html code is going to be like this:

    <p>{% quote(author="C++ Standard Core Language Defect Reports and Accepted Issues; Revision 82; delete and user-written deallocation function", href="http://www.open-std.org/jtc1/sc22/wg21/docs/cwg</p><blockquote>
        <p>
        ...if the value of the operand of delete is the null pointer the operation has no effect.
        </p>
    
        -- <a href="http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#348">C++ Standard Core Language Defect Reports and Accepted Issues; Revision 82; delete and user-written deallocation function</a>
    </blockquote>

Which obviously should not output the part before opening blockquote tag. It happens due to the underscore character in the url. If I change cwg_defects.html to cwgdefects.html for example, it works.

It has been tested with v0.3.2.

**Comment by Keats** [comment]
That's a known issue (dup of #165). There is an ongoing rewrite of the markdown/shortcode renderer by @reillysiemens and @RadicalZephyr that should fix that for 0.4

I might fix the faulty regex in the next minor version at least though

**Comment by NuLL3rr0r** [comment]
OK, thank you so much for the info. Is there any estimation on when 0.4 will be released?

**Comment by Keats** [comment]
None, I'm not the one working on it.

**Comment by Keats** [comment]
So the shortcode parse will now parse the arguments as expected in the `next` branch but it will still fail with markdown characters like `_`. I'm probably going to release 0.3.3 tomorrow and focus on the markdown issue right after as I consider that the problem number one in current Gutenberg.

**Comment by NuLL3rr0r** [comment]
Great news! Thank you so much!
