### ISSUE TITLE
Feature Request: Broader control of configuration -- Command line flag for config / Environment vars as extras?

### ISSUE THREAD

**Issue by theashguy** [getzola/zola#254]
I'm using Gutenberg as part of the core build chain for my app and its surrounding website which means that in different environments I need to use different settings. Am thinking it would be nice to have a -c switch for setting the config file on run, both for my case but also in general for testing config options etc. 

Incidentally my current work around is just to copy (for example) the config_staging.toml over config.toml during the build process, but this is difficult to work with locally as I like to have config.toml stable in my dev environment.

An alternative would be to be able to pass environment vars in as extras?

(I may have a look to see if I can raise a PR for this in the future, but I wanted to get it into the open in case it was something other folks wanted that we can start to discuss).

**Comment by Keats** [comment]
>  Am thinking it would be nice to have a -c switch for setting the config file on run, both for my case but also in general for testing config options etc.

Looks like I forgot to document it but it's already there: https://github.com/Keats/gutenberg/blob/master/src/cli.rs#L9-L14 or you can type `gutenberg` to see the help in the binary

**Comment by Keats** [comment]
It looks like it's broken as well :/

**Comment by Keats** [comment]
It's fixed in the commit above and will be in the next version

**Comment by theashguy** [comment]
Awesome.
