### ISSUE TITLE
Non-predictable public/sitemap.xml (random order of <url></url>)

### ISSUE THREAD

**Issue by pandark** [getzola/zola#257]
Running `gutenberg build` several times doesn't give the same `public/sitemap.xml` every time.
The order of `<url></url>` seems to be random.

**Comment by Keats** [comment]
Do the sitemap urls even need to be predictable?

**Comment by pandark** [comment]
Probably not… It's just that the file is changing for no reason (which is polluting my diffs :grin:).
That's not a major issue, just a possible enhancement :slightly_smiling_face:

**Comment by Keats** [comment]
> (which is polluting my diffs grin).

Good enough reason!
