### ISSUE TITLE
How do I access content [extra] fields in section.html

### ISSUE THREAD

**Issue by autoferrit** [getzola/zola#258]
in my section.html, I am trying to get a field from the `extra` field. Here is the content
```markdown
+++
title = "Some article"
date = 2017-09-24
tags = ["foo", "bar"]
[extra]
image = "/img/jakku.jpg"
+++

Lorem ipsum
```

I am trying to access the `image` field so I can show an image for my post. in `/templates/section.html` I have this:

```jinja2
{% set ex = page.extra %}
{{ ex | safe | json_encode(pretty=true) }}
```

which spits out this on the page:
```
{ "image": "/img/jakku.jpg" }
```

i have tried everything i read on both the gutenberg and tera documentation and nothing seems to be able to access it. when i refer to it, i see it called an `[object]` but if I do

```jinja2
{{ ex | get(key="image") }}
```
it tells me 
```
Reason: Filter `get` was used on a value that isn't an object
```
So I cant figure out how to access this. Or any of the `extra` fields. If I am doing this wrong I am ll ears, but the docs dont say at all how to access it except the `section` part of the docs say its a HashMap. but i dont see anything else showing how I can access that in the template.

**Comment by pandark** [comment]
`page.extra.image` :slightly_smiling_face:

**Comment by Keats** [comment]
What @pandark said. You mention `section.html` twice but use the `page` variable though. If you are really rendering a section, the variable will be called `section`, not `page`.

**Comment by autoferrit** [comment]
You are right, it is `page.extra.image` but i was trying to get at it incorrectly from a `section`

**Comment by Keats** [comment]
Cool!
