### ISSUE TITLE
Non-predictable sort for several (order) equal values

### ISSUE THREAD

**Issue by pandark** [getzola/zola#259]
I have a section with `sort_by = "order"`
In this section, I have several pages with the same order value and other pages with different order values.
The pages with lesser order values are lower than the ones with higher order values, which is correct.
The pages with an equal order value are sorted randomly, in a different order each time `gutenberg build` is run, which is not very good.

Maybe they could be sorted alphabetically by slug (since their slug must be different from each other)?

**Comment by Keats** [comment]
We could add it but what's the usecase for having several items with the same order? That kinda defeats any sorting mechanism

**Comment by pandark** [comment]
I have people who wrote their solution to a game (and how they found them).
They earn some points for each correct answer.
I'd like to list them (their solutions) from the best score to the worst, so I put their score in the order variable.

**Comment by Keats** [comment]
You can try the `next` branch, that should be fixed
