### ISSUE TITLE
Runtime Syntax Loading 

### ISSUE THREAD

**Issue by remexre** [getzola/zola#262]
It'd be nice not to have to recompile gutenberg each time I update a syntax.

**Comment by Keats** [comment]
Which syntax?

**Comment by remexre** [comment]
In my case it's a custom one -- I do language design, so I'm going to have
a few that aren't generally useful.

**Comment by Keats** [comment]
I see. Something to consider is that the syntax used is the same one as Sublime Text so it's just easier to use ST for quick changes and compile Gutenberg once when you're done.

I don't think it makes sense to allow loading custom language syntaxes  otherwise though, it's very niche

**Comment by remexre** [comment]
I already do prototype in ST, but having to compile Gutenberg myself and set up Travis to do it too is rather annoying.

Is this a "I'm not going to write it," or "I wouldn't accept a PR"? For me, this is kind of a killer feature, so I might write up a PR when I have time, if it's something you'd merge.

**Comment by Keats** [comment]
That would depend on the size of the diff and whether the changes impact anyone else

**Comment by ErichDonGubler** [comment]
@remexre: The actual call to highlight code blocks using `syntect` is [here](https://github.com/Keats/gutenberg/blob/master/components/rendering/src/markdown.rs#L107). Most of the changes you'd make would probably be in that module and in the [`Config`](https://github.com/Keats/gutenberg/blob/master/components/config/src/lib.rs#L33) struct that represents a Gutenberg `config.toml`. See how the syntax set that Gutenberg uses is constructed [here](https://github.com/Keats/gutenberg/blob/master/components/rendering/src/markdown.rs#L191) and then passed to the [`HighlightLines`](https://docs.rs/syntect/2.0.0/syntect/easy/struct.HighlightLines.html) API that `syntect` provides.

Hope that helps! :)

**Comment by Keats** [comment]
@ErichDonGubler Note that the markdown rendering is going to be refactored for the next version so it should be less hacky as well

**Comment by ErichDonGubler** [comment]
@Keats: Oh, right..maybe I should point him towards the `next` branch...

**Comment by Keats** [comment]
which doesn't exist yet, taking a small break before continuing!

**Comment by Keats** [comment]
0.4.0 is in the process of being released so if you're still interested in that. The easiest way would be to have a new config field for `additional_syntaxes` or something and load them on startup. We can't modify the built-in static so it's probably going to be a bit hacky but should be doable.

**Comment by remexre** [comment]
Okay, sure. This kinda fell off my plate; I've got some a work deadline
coming up, but I should have more free time starting next weekend.

**Comment by Keats** [comment]
No worries, take your time
