### ISSUE TITLE
Comparison with other static site generator : differentiate native and plugin features

### ISSUE THREAD

**Issue by mothsART** [getzola/zola#265]
I'm using Pelican from a long time and several features come from plugins.

With a little experience, i can affirm than plugins needs sometimes bigger effort to integrate than a native feature. (icompatible with all version, incomplete documentation...)

On Pelican, i18n and search engine are plugins... I think, it would be wise to precise on the README.

**Comment by Keats** [comment]
I do find the Pelican approach more flexible than native though. If you want to change anything (including bugfixes), you can just edit some Python files to do the exact behaviour you want. It's hard to beat as a user
