### ISSUE TITLE
Build error when using draft and a new tag

### ISSUE THREAD

**Issue by Libbum** [getzola/zola#266]
Think I've found a bug. Here's the steps to recreate it:

1. Make new content
2. Add a tag which currently has no contents (e.g. Algorithms)
3. Set `draft=true`
4. Build page

> Reason: Failed to render 'page.html'
 Reason: `get_taxonomy_url`: couldn't find `Algorithms` in `tag` taxonomy

5. Remove draft flag

> Normal build

Skimming through the codebase for where draft is listed, it looks like these posts are filtered out when pagination is enabled (this is the case with my set up); but may not be handled in the taxonomy section.

Is this by design or an oversight? I'm happy to work on a fix for this, although I haven't read through too much of the inners of gutenberg just yet, so it'd be great if you could point me to where you think the best place for a patch would be here.

**Comment by Keats** [comment]
>  it looks like these posts are filtered out when pagination is enabled (this is the case with my set up); but may not be handled in the taxonomy section.

Is it handled: https://github.com/Keats/gutenberg/blob/master/components/site/src/lib.rs#L390

Whether or not this is a bug depends on if an empty taxonomy should result in a page as taxonomies are created only when there is at least one page. My first instinct would say this is not a bug as there wouldn't be anything to display on it; what do you think?

**Comment by Libbum** [comment]
I certainly agree there shouldn't be a page for an empty taxonomy.

But perhaps I'm missing the point of what a `draft` is here. My assumption of what draft would do is enable you to write content, and show it locally (using `serve`), but not turn up on the final output (using `build`). Looking deeper into the code, that doesn't seem to be the case in your implementation:

> A draft page will not be present in prev/next pagination

Can you give me an example use case for filtering drafts out of pagination, as opposed to everything?

**Comment by Keats** [comment]
> But perhaps I'm missing the point of what a draft is here.

Perhaps it's me! I'm not using drafts so my implementation might not be what people expects. My thoughts were the following: a draft post is simply an existing post not referenced anywhere, ie not findable manually or by sitemap unless you know the URL.
This ensures you can have staging servers to preview drafts: if `build` was not rendering the drafts, you would need another option in the CLI to still publish draft for those cases and that would change all of pagination/taxonomies generation to include them.

> Can you give me an example use case for filtering drafts out of pagination, as opposed to everything?

Drafts are filtered out of pretty much everything (sitemap, taxonomies, pagination, rss).

**Comment by Libbum** [comment]
Right, OK I follow your reasoning - thanks. In that sense my use case may be out of scope. 

I'll close this issue then since what's occurring for me is therefore expected behaviour, but I'll add a few details about my setup for anyone investigating this in the future:

In page.html:
```htmldjango
<ul class="stats">                                                                                                                             
    {% for tag in page.tags %}                                                                                                                 
    <li><a href="{{ get_taxonomy_url(kind="tag", name=tag) }}">{{ tag }}</a></li>                                                              
    {% endfor %}                                                                                                                               
</ul>    
```
Since your `draft` page is hidden, the 'new' tag you assign it will not be rendered and this would fail.
Thus, you should wrap this in an `if` such that it fails gracefully.

**Comment by Keats** [comment]
Hmm I see. In that case yes it should be wrapped in a `if not page.draft`
