### ISSUE TITLE
Structure of a simple brochure site??

### ISSUE THREAD

**Issue by tomcam** [getzola/zola#267]
Imagine a traditional site index.html that links to about.html and faq.html, all in the same root directory (which would presumably be /content with Gutenberg). For the life of me I can't figure out the .md file equivalent for index.html, because index.md and _index.md both have special meanings.

How do I do that with Gutenberg? Going insane reading the Hugo/Jinja2 docs on this apparently simple matter.

**Comment by Keats** [comment]
The .md file for the index page is `content/_index.md`. In your case the structure would probably be:

```bash
content
  - _index.md
  - about.md
  - faq.md
```

**Comment by tomcam** [comment]
OK I'm still not getting it. I'm doing this using the Book theme with the following files. Result is a "Welcome to Gutenberg" page when I visit http://127.0.0.1:1111:

content/_index.md:
```
+++
title="index?"
template="index.html"
+++
# Home?
[About](about.md)

[FAQ](faq.md)
```

content/about.md:
```
+++
title="Aboutness"
+++
# About.md
This is certainly the About page
```
content/faq.md
```
+++
title="FAQness"
+++
# FAQ
Do people frequently ask if this is the FAQ page? Yes.
```

**Comment by Keats** [comment]
The `_index.md` would be:

```
+++
title="index?"
+++
# Home?
[About](./about.md)

[FAQ](./faq.md)
```
`index.html` is the default for `content/_index.md` so no need to specify it.

If you are still seeing the default pages, that means you don't have any files in the `templates` directory. Try to create `index.html` and `page.html` in there, you should now see a white page since the templates are empty.
