### ISSUE TITLE
allow array type for shortcodes

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#270]
I'm creating an album shortcode that contains an arbitrary amount of images.  It'd be very nice to be able to just go something like:

```html
{{ album(paths=["file1.jpg", "file2.jpg", "file3.jpg"]) }}
```

Because arrays are ignored, the next best solution that I can imagine is something like defining manually different amounts for different shortcodes, i.e. `album2`, `album3`, `album4`, and so on.

**Comment by Keats** [comment]
Yep definitely something I want, just need to fix the markdown renderer first!

**Comment by asaaki** [comment]
Another workaround should be to provide a splittable string and an optionally overridable separator.

```rust
{{ album(paths="file1.jpg,file2.jpg,file3.jpg", sep=",") }}
```

But I'd also agree that we need self-definable arrays (not only in shortcodes, but supported by tera in general).

**Comment by Jieiku** [comment]
Anyone know of an example Shortcode that takes an array as an argument?

I have a super neat idea for a shortcode, and passing an array to it will make things much easier.

**Comment by Keats** [comment]
It should work as expected in the original comment?

**Comment by Jieiku** [comment]
YEP! it works, I made an image hover comparison shortcode: [imghover](https://github.com/Jieiku/abridge/blob/master/templates/shortcodes/imghover.html)

https://abridge.netlify.app/overview-images/
