### ISSUE TITLE
Allow theme specific shortcodes

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#272]
I'm creating a theme and I've dropped some shortcodes in my theme's `templates/shortcodes` directory.  It works fine when I'm developing the theme, but in actual usage Gutenberg does not check the theme's shortcode directory and spits out an error.  It would be super nice to allow themes to make custom shortcodes available.

**Comment by Keats** [comment]
Woops I thought it was already working somehow, should be an easy fix to add to the next version though
