### ISSUE TITLE
Why is `base_url` required?

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#273]
Why exactly is the `base_url` required?  I feel as though it would be more ergonomic to simply use absolute paths, e.g. `/` for the root directory.  That would eliminate some issues / caveats with CI as well, for example `command = "gutenberg build --base-url $DEPLOY_PRIME_URL"` for netlify could omit the `--base-url` parameter.

**Comment by Keats** [comment]
Relative paths can cause issues if you are hosting the site not on the root domain: let's say you have a gutenberg blog at mydomain.com/blog
Using `/blog.css` for example will look at `mydomain.com/blog.css` rather than `mydomain.com/blog/blog.css` like it should. Requiring `base_url` eliminates those issues

**Comment by piedoom** [comment]
Couldn't there be an optional `subdir` variable or something in that case that could be prepended before links?  Including the whole domain + http(s) means I have to re-commit if I change my domain or if I get SSL

**Comment by Keats** [comment]
> Couldn't there be an optional subdir variable or something in that case that could be prepended before links?

That wouldn't help for the sitemap or the RSS feed where it requires the full URL

**Comment by piedoom** [comment]
That's true.  I'm not sure if I'm totally convinced that it should remain mandatory, but I agree in that it would break RSS (though couldn't one provide absolute links for the sitemap?).  In my opinion, a better option might be to provide an optional `subdir` and `domain` variable.  For instance, a site located at `https://mysite.com/blog/` might look like this:

```toml
domain = "mysite.com"
subdir = "blog"
```

Perhaps it's unwise to build off of my own use-case, but I don't use RSS, sitemaps, and I force SSL.  I imagine this is the same story for a good majority of websites.  Deploying to GH or Netlify without making sure `https` is used over `http`, etc. would be nice.  This is most likely a preference of mine, though - so I'll close.
