### ISSUE TITLE
Get the categories in the main index

### ISSUE THREAD

**Issue by caemor** [getzola/zola#274]
So i want to have all my posts as blog posts on my feed on the main index site. That works well if they are all in one section e.g. "blog". But additionally i would like to have some additional direct links to all "categories/subsections" inside my navigation.
I think there are 2 ways to do that:

1. Using subsections of blog. The navigation wouldn't be a problem as the blog section has access to all the subsections. But i can't access all the posts in a certain order as i would need to go though all subsections and so on to get all the posts out there and then they would be out of order

2. Using categories would be the other solution. That works on the /categories.html page but nowhere else as the categories aren't accessible anywhere also so i can't use that on my main landing page. 

There is a hard coded solution for 2, where i enter the permalinks to the categories directly into the navigation but then i would always need to update it per hand.

So is there a better way to do this or am i just thinking the wrong way?

**Comment by Keats** [comment]
You're correct, there's currently no way to get them.
If we go through with https://github.com/Keats/gutenberg/issues/246 (please comment if you have any input on that!), we could expose taxonomies via global functions

**Comment by caemor** [comment]
I think this can be closed than as #246 will solve the problem.
