### ISSUE TITLE
Internal links only work on .md entries in folders

### ISSUE THREAD

**Issue by Libbum** [getzola/zola#275]
[Internal links](https://www.getgutenberg.io/documentation/content/linking/#internal-links) function when you reference a markdown file if it's within a folder like `[about](./pages/about.md)`, but fail if the file is in the content directory directly: `[another post](./post.md)`.

Ultimately, this is because [`resolve_internal_link`](https://github.com/Keats/gutenberg/blob/e858c2dfdb963c23a40ce418293bd302097f1734/components/utils/src/site.rs#L16-L32) strips the `./` of the URI but then attempts to match against the `permalink` hashmap, which stores a leading slash on all elements found in the root of the content directory.

| stripped URI | permalink key |
|:----------------- |:------------------ |
| pages/about.md | pages/about.md |
| post.md | /post.md |

I'm not sure which way you'd like to approach fixing this, hence the issue rather than a PR.
If the leading forward slash isn't used anywhere for anther reason, then my suggestion would just be to drop that when building the hashmap. Otherwise we could add an additional parsing check in `resolve_internal_link` to resolve content in the root directory which prepends this slash.

**Comment by Keats** [comment]
Ah interesting bug! Should be an easy fix though, a bit surprised I didn't have a test for that
