### ISSUE TITLE
Syntax highlighting for CMake

### ISSUE THREAD

**Issue by NuLL3rr0r** [getzola/zola#277]
Could you please add syntax highlighting support for CMake? I need it quite often and cannot find it [here](https://www.getgutenberg.io/documentation/content/syntax-highlighting/).

Thank you!

**Comment by ErichDonGubler** [comment]
Hmm...@keats, if you decide to supoprt this, perhaps you might be interested in using the syntax definition provided [here](https://packagecontrol.io/packages/CMake)?

**Comment by Keats** [comment]
Yep @ErichDonGubler, looks like it will work and be easy to add
