### ISSUE TITLE
running two servers at once

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#282]
I'm running two servers (one for theme development, the other is my own site using the theme).  I tried doing this by specifying two different ports.  However, it seems like there's a hardcoded WS server that prevents this from happening.  Here's the error:

```
Listening for changes in C:\Users\doomy\Documents\code\portfolio\themes\gutenberg-portfolio/{content, templates, config.toml, static, sass}
Web server is available at http://127.0.0.1:3000
Press Ctrl+C to stop

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WS Error <Io(Os { code: 10048, kind:
AddrInUse, message: "Only one usage of each socket address (protocol/network address/port) is normally permitted." })>', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I know this use-case isn't exactly typical so I won't be upset if this is a `wontfix`, but thought I might as well report.

**Comment by Serkan-devel** [comment]
Maybe containerization could help, or the process IDs should be separated.

**Comment by Keats** [comment]
The issue is that the WS port for live reload is static in the code so running 2 instances will clash. 
Maybe something dumb like `server port - 1` instead. Ideally it would just find a free port but I'm not sure it's worth the effort.

I will happily take a PR for that though!
