### ISSUE TITLE
listening for changes is not working if templates are missing

### ISSUE THREAD

**Issue by jachin** [getzola/zola#287]
I'm running on a macOS 10.13.4

gutenberg 0.3.3 (installed via homebrew).

When I run `gutenberg serve` the web server works, but if I make changes (to a markdown file in `content` for instance) nothing happens, I need restart `gutenberg serve` and reload the browser page to see my changes.

I think I figured out what was going on, when I run `gutenberg build` I was getting the following error.

```
remote: Failed to build the site
remote: Error: Failed to render categories page.
remote: Reason: Template 'hyde/templates/categories.html' not found
```

After I added those missing templates, the listening for file changes started working again. My guess is the `gutenberg serve` is not passing along build errors to the console and it would great if it did.

Let me know if I can provide any additional context or debugging information.

(I really like how fast gutenberg is, nice work)

**Comment by Keats** [comment]
> My guess is the gutenberg serve is not passing along build errors to the console and it would great if it did.

Hmm that's weird, `gutenberg serve` literally calls the same code as the build (https://github.com/Keats/gutenberg/blob/master/src/cmd/serve.rs#L101) and the errors are bubbled up.
I will have a look later

**Comment by Keats** [comment]
I tried again now and I do get the same error on build and serve, any chance you can get a repo reproducing the issue?

**Comment by Keats** [comment]
ping @jachin

**Comment by jachin** [comment]
Sorry, it's taken me so long to get back to you... anyway... I'm afraid I haven't got a repo reproducing the issue... I just have the version I installed via homebrew.

```
gutenberg --version
gutenberg 0.3.3
```

Anyway, I just did a little playing around to try to come up with some better steps to reproduce the error, which is hopefully helpful enough.

 1. Create a new site
 2. Install the Hyde theme.
 3. Set Hyde as the theme for the site.
 4. Run `gutenberg serve`
 5. Create a article with a category in it.
 6. Look at the output of the `serve` command.

```
<bla bla bla>my_site/content/sweet.md
Failed to build the site
Error: Failed to render categories page.
Reason: Template 'hyde/templates/categories.html' not found
Done in 5ms.
```

And the server is still running, I don't think the page refreshes automatically though, and refreshing it, it doesn't have any styles.

As I keep making changes the running server keeps acting like things are fine. I think when I initially reported this error I must have overlooked the error message. Although, I have to admit, what I'm seeing here is not what I reported.

When I restart `gutenberg serve` I see the error I'd expect.

I think I'm not re-creating the issue I initially reported, and I'm not sure how to get there, but I think my steps still get to an error (all be it a more minor one).

I think if `build` fails, the server should stop too. Or if it doesn't stop, instead of showing the site it should show the error message.

Maybe this is more of an enhancement than a bug (you'll be the judge of that I guess). 😄 

Anyway, if I can figure out how to recreate the issue I described initially, I'll let you know.

**Comment by Keats** [comment]
Hyde doesn't have categories so that error is expected, what happens if you create a `categories.html` in the templates directory? It should detect it and refreshing the page should show the newly created page

**Comment by jachin** [comment]
That's true, it does do that, but there isn't any console output. The page refreshes but the console (terminal) acts like nothing has happened.

**Comment by Keats** [comment]
Hum sometimes editors do weird things while editing files: my PyCharm will not trigger some watcher events while Sublime will. Wondering if that's related

**Comment by Keats** [comment]
Cannot reproduce so closing for now, re-open if it's still an issue with 0.4.0
