### ISSUE TITLE
Best way to achieve multiple shortcode "body" content items

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#289]
I'm currently trying to create a generic X-column shortcode for use with a portfolio theme.  Here's an idea of what I'm looking to create:

![image](https://user-images.githubusercontent.com/8846211/38711076-80baaea2-3e91-11e8-9e23-2b53c11a4612.png)

Both columns should be completely arbitrary in content and numbers.  I tried to attempt to do this with pure shortcodes - 

```
{% grid(columns=2) %}
    {% column %}
        This is a small test
    {% end %}
    {% column %}
        This is a small test
    {% end %}
{% end %}
```

However, it doesn't seem as though shortcodes render recursively.  They also do not allow for an HTML body, even with the `safe` filter.  Even if I could, I would preferably not need to use HTML within the markdown file (even though the solution above is just about as verbose; however I like how shortcodes keep the user from writing their own code/styles that often break designs.  It's also nice to have MD rendering available inside the shortcode).

HTML only versions also do not render shortcodes unfortunately.  The following could be a workaround, but the image shortcode doesn't render.

```
<div class="grid col-2">
    <div>
        <p>This is a small test of something</p>
    </div>
    <div>
        {{ image(path="resamplr/screenshot.png") }}
    </div>
</div>
```

Is there a better way to achieve my desired effect without manually writing HTML or creating a JS function?

**Comment by Keats** [comment]
Shortcodes can't call themselves, unlike macros.
I don't get what you're trying to do there though:

```
    {% column %}
        This is a small test
    {% end %}
```

I think this is a bit beyond what shortcodes are for sadly, you could have more specialised shortcodes like `sign_in` where the user could customise the strings but not much more than that

**Comment by piedoom** [comment]
Alright!  Sounds good, I think I was trying to be a little too clever here.  I ended up just hardcoding a 2-column shortcode that takes an image, but allows for a `{{body}}` to describe text.  While I can't use it everywhere as a generic template, that probably wasn't the best idea in the first place ;)
