### ISSUE TITLE
Serving JSON

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#293]
For some elements on a page, it might be useful to serve a JSON file instead of HTML.  For example, this would allow me to load a page within a page (often called a quickview element).  I'm not sure if something like this is already implemented (besides maybe parsing the RSS feed?)

It would be great to allow a flag to `serve_json` or something similar, and then serve a JSON file with encoded front matter when the path is displayed with a json extension, e.g. `mysite.com/products/something.json`

```json
{
  "date": 12345678,
  "category": "my category",

  ...

  "body": "<div>... content ...</div>"
}
```

**Comment by Keats** [comment]
can it not be just an asset file or am I missing something? I have never heard of quickview elements

**Comment by piedoom** [comment]
Sorry, let me explain it better.
As an example, Amazon has something like this - 

![image](https://user-images.githubusercontent.com/8846211/39270433-0f63aa5c-48a4-11e8-9eb2-ee1da3c65c2b.png)
![image](https://user-images.githubusercontent.com/8846211/39270440-14e6c75c-48a4-11e8-88c0-0d4867209207.png)

It opens a view of something in a modal without actually changing the page.  I guess one could just set a `data` attribute on the HTML and build a modal without JSON.  However, JSON support would also allow users to use SPA frameworks like Elm or React while still retaining the nice organization that a static site generator allows.

**Comment by Keats** [comment]
It might be worth looking into what those graphql static site gen like gatsby are doing or is it completely unrelated?

**Comment by piedoom** [comment]
I can't speak for the likes of Gatsby since I haven't used it, but IMO a whole GraphQL implementation seems like overkill for most use cases.  I'd like for others to weigh in on this but a simple JSON file per content would be perfect (that would just serialize all the variables available to Tera), and perhaps a list of content links/titles/descriptions per taxonomy.  I have yet to dive into the internals of Gutenberg, but I would assume it wouldn't be dissimilar to encoding for RSS feeds, etc.

**Comment by piedoom** [comment]
#365 is a much more cohesive and well-written proposal than this issue, so this should be considered a duplicate and closed.
