### ISSUE TITLE
Outputting web server config instead of HTML redirects

### ISSUE THREAD

**Issue by clarfonthey** [getzola/zola#295]
It would be really cool if we had the option of either outputting a .htaccess file or an nginx config instead of static HTML redirects.

I personally use nginx, so, having a blurb I could copy-paste into my server config would be preferable. That said, people who use Apache could have the option to output a .htaccess instead, and with that you could also include an htaccess to merge with the generated rules.

**Comment by Keats** [comment]
Hmm I don't really have a need for that but I'm not opposed to it.
I guess there could be a new field called `redirect_webserver = "nginx" | "apache" | "caddy"` defaulting to `None` (name found in 2s so there can be a better one I suppose) that would generate a file to be included in the `public` dir.

I'm unlikely to implement this myself but it shouldn't be too hard to add

**Comment by fbruetting** [comment]
I created a `.htaccess` file by myself, but `gutenberg serve` sadly doesn’t respect it, while it works perfectly fine on my webserver.

**Comment by Keats** [comment]
That's normal, `gutenberg serve` doesn't know anything about `.htaccess` and that is not going to change. The best way to develop locally if you want your own webserver would be using https://github.com/Keats/gutenberg/pull/450  when it is merged.

**Comment by fbruetting** [comment]
Ok, will do that. Thanks!

Or is there an idiomatic way of showing / switching to one category or one article by default when a user browses my site?

**Comment by Keats** [comment]
you could set the `redirect_to` field of the `content/_index.md` file to the path you want users to see like https://raw.githubusercontent.com/Keats/gutenberg/master/docs/content/documentation/content/_index.md

**Comment by Keats** [comment]
@paulcmal could that somehow be related to custom output formats?

**Comment by Keats** [comment]
Not enough activity.

**Comment by jtojnar** [comment]
Would pull requests for this be considered? I would like to add at least support for [Netlify’s `_redirects` format](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file), which is also supported by [GitLab pages](https://docs.gitlab.com/ee/user/project/pages/redirects.html) and [Cloudflare pages](https://developers.cloudflare.com/pages/platform/redirects/).

**Comment by Keats** [comment]
It's probably not a feature needed enough to be worth adding
