### ISSUE TITLE
Can't have links in headers

### ISSUE THREAD

**Issue by clarfonthey** [getzola/zola#297]
Very simple example: `# [Rust](https://rust-lang.org)` gets rendered as just `<h1 id="rust">Rust</h1>`, when it should be `<h1 id="rust"><a href="https://rust-lang.org">Rust</a></h1>`.

I took a look at the code and it appears that links in headers are intentionally ignored in Gutenberg, despite being parsed (correctly) by `pulldown-cmark`. Why is that?

(link to line in question: https://github.com/Keats/gutenberg/blob/master/components/rendering/src/markdown.rs#L213)

**Comment by Keats** [comment]
The markdown rendering is going to get rewritten for the next version, I can fix it at that point
