### ISSUE TITLE
Colocated images break when accessing page.content

### ISSUE THREAD

**Issue by cormac-obrien** [getzola/zola#298]
`content` folder:

```
content/
|-example-page/
  |-index.md
  \-some-image.jpg
```

`index.md`:
```
+++
title = "example"
date = 2018-04-26
template = "page.html"
+++

This is an example page

![An image][1]

Some more text

[1]: some-image.jpg
```

I modified the `hyde` theme slightly to show this, adding `{{ page.content }}` under the per-post date `<span>` tags.

On the actual `page-1` page, the image displays fine:

![screenshot 10](https://user-images.githubusercontent.com/5809282/39340432-c2df06e0-4993-11e8-8d32-12218f1849fd.png)

However, the generated `index.html` does not get the right link:

![screenshot 12](https://user-images.githubusercontent.com/5809282/39340508-228402a8-4994-11e8-8afc-76108ab91f10.png)

It seems to me like Gutenberg should resolve this link correctly regardless of where `{{ page.content }}` is accessed instead of only for the HTML generated for that markdown file. Is this possible?

**Comment by Keats** [comment]
Hmm I'm not sure how in your markdown example it could prepend the permalink automatically unless we go and add it to every asset if it's relative

**Comment by Keats** [comment]
Looking at it now, it also needs to be done for links, not only images but it should be doable
