### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by dustinmatlock** [getzola/zola#301]
Is there a particular way to get the commands working? The documentation doesn't specify a directory or how to configure this. Thanks.

**Comment by Keats** [comment]
What do you mean? Did you create a new site using `gutenberg init`? The commands works in the directory where the `config.toml` file is

**Comment by dustinmatlock** [comment]
There's no initial `config.toml` file except in the `test_site` and `docs` directories.

**Comment by Keats** [comment]
I'm a bit confused, what are you trying to do?

**Comment by dustinmatlock** [comment]
On Ubuntu, I run `cargo build --release`, everything installs fine, and then I try the commands in the root folder and it tells me: `gutenberg: command not found`. I'm not sure what I'm missing.

**Comment by Keats** [comment]
`cargo build` creates the executable in the `target` folder (`target/debug` or `target/release` on release mode), which is probably not in your PATH.

**Comment by dustinmatlock** [comment]
What’s the best way to install on Ubuntu? I didn’t see instructions for that. Thanks.

**Comment by Keats** [comment]
I believe Ubuntu uses snap, there is an issue for that (https://github.com/Keats/gutenberg/issues/227) as well as a PR.

In the meantime, the easiest way is to grab the latest archive from https://github.com/Keats/gutenberg/releases and put the executable in your `PATH`
