### ISSUE TITLE
Search does not work with subsections

### ISSUE THREAD

**Issue by sheganinans** [getzola/zola#303]
It seems that pages inside of subsections do not seem to be added to the search index.

I have a project with the following content directory

* section_one/
    * _index.md
    * one/
        * _index.md
        * one_one/
            * page.md
        * one_two/
    * two/
    * three/
* section_two
    * _index.md

The search will add all the _index.md files to the index, but it does not add page.md

**Comment by Keats** [comment]
That's odd, the search code doesn't care about subsections, it just adds all sections to the search index. I'll have a look later

**Comment by sheganinans** [comment]
I'll see if i can get a minimal example of what I'm encountering

**Comment by Keats** [comment]
Did you manage to get one?

**Comment by Keats** [comment]
Closing for now, re-open if it's still an issue with 0.4.0 and have a repro
