### ISSUE TITLE
SASS Source maps

### ISSUE THREAD

**Issue by clarfonthey** [getzola/zola#306]
It would be very helpful if there were a config flag to turn on source maps for SASS compilation, as it's very useful for debugging. Outputting inline source maps should be fine; if anyone wants anything more interesting, they can compile stuff themself.

(I will probably make a PR for this within a few days if no one else does.)

**Comment by Keats** [comment]
I don't think I've ever used Sass source maps, the CSS beautifier of firefox/chrome being enough for me.
I'm not against it though, would that be only for `gutenberg serve`?
I'm not even sure I added the sourcemap support in https://github.com/compass-rs/sass-rs tbh

**Comment by clarfonthey** [comment]
@Keats I'll probably start with looking at sass-rs to at least add inline sourcemap support.

As far as where it's supported, I was initially thinking of just adding a setting to `config.toml` but selectively enabling it for `gutenberg serve` sounds like a better idea.

**Comment by Keats** [comment]
@clarcharr are you still planning to add sourcemap support to sass-rs?

**Comment by clarfonthey** [comment]
I had honestly completely forgotten about this issue. I can take a look at it over the weekend.

**Comment by Keats** [comment]
Closing that for now since it needs some implementation upstream. This can be re-opened when `sass-rs` supports sourcemaps.

**Comment by piedoom** [comment]
FWIW I've never used sourcemaps for CSS.  I don't mean to say it's not a usecase, I'm just unsure as to why it would be useful (e.g. isn't looking up the class/ID enough to figure out what is happening?)

**Comment by clarfonthey** [comment]
If you're just using basic nesting then yeah, it's pretty easy to go without. If you add in some level of minification, inheritance, variable expansion, or otherwise, then it's a lot harder to figure out where a rule came from.
