### ISSUE TITLE
Shortcodes are not loaded

### ISSUE THREAD

**Issue by elahn** [getzola/zola#308]
Shortcodes are not loaded from `templates/shortcodes`. e.g.

`templates/shortcodes/scode.html`:
```html
<p>arg = {{ arg }}</p>
```

`templates/index.html`:
```html
<p>{{ scode(arg="hello shortcode test") }}</p>
```

Output from `gutenberg build`:
```
Failed to build the site
Error: Failed to render section ''
Reason: Failed to render 'index.html'
Reason: Global function 'scode' not found
```

**Comment by Keats** [comment]
Shortcodes are meant to be used in the content (ie in a .md file). Note that there are currently a few bugs with them but they should already be fixed in `next` branch.

If you want re-usable bits of code in the template, you can use [macros](https://tera.netlify.com/docs/templates/#macros)

**Comment by ghost** [comment]
@Keats might want to mention this in the Shortcodes docs! Went round in circles for quite some time trying to figure this out.

**Comment by ghost** [comment]
@elahn I was able to achieve the result I wanted by creating both a macro and a shortcode.

In **templates/macros.html** (usable in templates/*.html files):

```
{% macro artwork(path, title, medium) %}
<div class="artwork">
	<img src="{{ path }}">
	<div class="imgTitle">{{ title }}</div>
	<div class="imgDescription">{{ medium }}</div>
</div>
{% endmacro %}
```

In **templates/shortcodes/artwork.html** (usable in markdown):
```
{% import "macros.html" as macros %}
{{ macros::artwork(path=path, title=title, medium=medium) }}
```

**Comment by Keats** [comment]
I have just pushed https://github.com/Keats/gutenberg/pull/398/commits/f920b873b8d5f77c426586fb1feeff6fea551df8 to clarify that
