### ISSUE TITLE
Custom RSS feeds

### ISSUE THREAD

**Issue by onelson** [getzola/zola#309]
I was watching as there was an barrage of rust related blogs being offered up for https://github.com/rayascott/fearless-rust-bloggers and got to thinking about how I could add a custom rss.xml that filtered by tag (since I don't plan to blog exclusively about rust).

Musing, it seems like I might be able to build a custom section and page with custom templates that look like plain xml, in combination with using a custom path (with a .xml suffix) but I'm not sure this is even possible.

Any advice for me?

**Comment by piedoom** [comment]
According to [the docs I read](https://www.getgutenberg.io/documentation/templates/rss/), per-category/per-tag rss feeds are not yet implemented.  I would like to see this feature as well for the same reason.

**Comment by onelson** [comment]
Maybe I should not be looking for a workaround and instead try to work up a PR in this case.

**Comment by Keats** [comment]
I was actually thinking of per-taxonomy rss feed just yesterday evening. I think it makes sense but imo https://github.com/Keats/gutenberg/issues/246 has to be done first, so you can choose which taxonomy to enable and is not tied in to tag/categories

**Comment by naturallymitchell** [comment]
This could be done with template logic, see https://github.com/getpelican/pelican/issues/1162

**Comment by onelson** [comment]
I will say, it would be nice to be able to customize the feed content, like setting a max word count for a summary, and adding a link back to the site.

**Comment by Keats** [comment]
The rss.xml is a template, you can overwrite it by create a rss.xml file in your templates directory and change what you want

**Comment by naturallymitchell** [comment]
[`rss.xml`](https://github.com/Keats/gutenberg/blob/c165c17c2fd7993bdff65dda5c727f21e7416738/components/templates/src/builtins/rss.xml) template
