### ISSUE TITLE
Also support antisymmetric relationships

### ISSUE THREAD

**Issue by naturallymitchell** [getzola/zola#314]
Currently, in order to represent data relationships, users can only use [quasiordered sets](https://en.wikipedia.org/wiki/Preorder), ie taxonomies or sections, with predefined structure. Support for more intuitive relationships and with ease of ad-hoc structuring could come with [partial ordered sets](https://en.wikipedia.org/wiki/Partially_ordered_set), using references.  Hierarchies would still work using a common codebase, simply by continuing to model data types without their [antisymmetric relation](https://en.m.wikipedia.org/wiki/Antisymmetric_relation) and using similar template logic.

This provides a deep fix for #246.

**Comment by Keats** [comment]
I don't believe this would fix #246 as you won't be able to paginate the taxonomies pages or provide a different RSS feed for each?

**Comment by naturallymitchell** [comment]
I don't know about the pagination, but for RSS feeds, it works the same as the page template right?  So, instead of outputting a page, you would output a feed with all pages that reference a term.

Here's the relevant Tera code:
https://github.com/3Dcube/gutenberg-references-demo/blob/master/templates/page.html#L12

Taxonomy terms would need to become like regular, user editable pages.  See albums for example:
https://github.com/3Dcube/gutenberg-references-demo/tree/master/content

**Comment by Keats** [comment]
The issue with that afaik is that the reference pages (including RSS) will need to be created manually . That was my first suggestion for custom taxonomies but I can see how having the pages be set-up automatically would be a big advantage

**Comment by Keats** [comment]
@mitchtbaum did I miss something or is my last post correct?

**Comment by naturallymitchell** [comment]
@Keats I'm not sure what you mean by reference pages.  References are fields, so pages that have them would reuse the same template.

**Comment by Keats** [comment]
You are saying it fixes the #246 issue, which contains auto-generated RSS and list/individual taxonomies pages but I don't see how #315 would fix that. It seems to be kind of orthogonal to me, you would use references if you want to mention some other related articles/pages on a page but it doesn't do the same job as taxonomies

**Comment by Keats** [comment]
@naturallymitchell reviving this issue and the PR associated with it.
Do you still have this issue with the more recent versions of Zola or did you find a workaround?
