### ISSUE TITLE
Cannot compile with musl as target

### ISSUE THREAD

**Issue by nbigaouette** [getzola/zola#316]
I'm trying to build a docker image providing a statically linked musl binary of gutenberg (v0.3.3). This way the final docker image could contain only the static binary by using `FROM scratch`.

Here's the dockerfile:
```dockerfile
ARG RUSTC_VERSION=1.26.2

FROM rust:${RUSTC_VERSION}-slim-stretch as builder

ENV GUTENBERG_VERSION 0.3.3

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
    wget \
    tar \
    cmake \
    build-essential \
    musl-dev \
    musl-tools \
    libpq-dev \
    libsqlite-dev \
    libssl-dev \
    pkgconf \
    xutils-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/Keats/gutenberg/archive/v${GUTENBERG_VERSION}.tar.gz && \
    tar -zxvf v${GUTENBERG_VERSION}.tar.gz && \
    rm -f v${GUTENBERG_VERSION}.tar.gz

RUN rustup target add x86_64-unknown-linux-musl

WORKDIR gutenberg-${GUTENBERG_VERSION}

ENV RUST_BACKTRACE=1

RUN cargo build --release

FROM rust:${RUSTC_VERSION}-slim-stretch as runner
COPY --from=builder /gutenberg-${GUTENBERG_VERSION}/target/release/gutenberg .
CMD ["./gutenberg", "serve"]
```

Built and ran like this: `docker build . -t gutenberg:v0.3.3 && docker run -it --rm gutenberg:v0.3.3`

Right now it does not work. I've facing some issues.

First issue is the following:
```
error[E0518]: attribute should be applied to function
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.11.6/src/parser/mod.rs:13:10
   |
13 | #[derive(Parser)]
   |          ^^^^^^ not a function
```
I'm not sure to understand this error. I was able to bypass it by running `cargo update`. Here's the resulting lock file: [Cargo.lock.txt](https://github.com/Keats/gutenberg/files/2086562/Cargo.lock.txt)
Could a release be done with updated dependencies? I guess that should fix this problem.

Secondly, I get a linking error if I try to link to musl (`cargo build --release --target=x86_64-unknown-linux-musl`):
```
  = note: /gutenberg-0.3.3/target/x86_64-unknown-linux-musl/release/deps/libsass_sys-e5c815c30709cae7.rlib(sass_context.o): In fun
ction `_GLOBAL__sub_I_sass_context.cpp':
          sass_context.cpp:(.text.startup+0x1c): undefined reference to `__dso_handle'
          sass_context.cpp:(.text.startup+0x4e): undefined reference to `__dso_handle'
          sass_context.cpp:(.text.startup+0xc9): undefined reference to `__dso_handle'
          sass_context.cpp:(.text.startup+0xef): undefined reference to `__dso_handle'
          sass_context.cpp:(.text.startup+0x118): undefined reference to `__dso_handle'
          /gutenberg-0.3.3/target/x86_64-unknown-linux-musl/release/deps/libsass_sys-e5c815c30709cae7.rlib(sass_context.o):sass_co
ntext.cpp:(.text.startup+0x141): more undefined references to `__dso_handle' follow
          /usr/bin/ld: /gutenberg-0.3.3/target/x86_64-unknown-linux-musl/release/deps/gutenberg-55708b3e089522b3: hidden symbol `_
_dso_handle' isn't defined
          /usr/bin/ld: final link failed: Bad value
          collect2: error: ld returned 1 exit status
```

Could https://github.com/rust-lang/rust/pull/50105 be related?

Thanks!

**Comment by onelson** [comment]
I ran into this same error for a project I have which depends on tera. I think the specific crate that needed updating was `pest_derive` and maybe one other I can't remember.

**Comment by ilovezfs** [comment]
@Keats yes we're now seeing this failure on Homebrew's CI as well.

**Comment by Keats** [comment]
Doing a 0.3.4 release after `cargo update` is not an issue but we should ensure sass-rs works with musl first, would it be possible to make a PR to https://github.com/compass-rs/sass-rs to add the musl target in travis?

**Comment by Keats** [comment]
@nbigaouette can you try to run the Dockerfile on nightly? If it compiles fine than we can leave it as is and I'll just release a 0.3.4 version

**Comment by Keats** [comment]
I tried with the Dockerfile using nightly rust but the issue is still there.

Root issue: https://github.com/rust-lang/rust/issues/36710
Related (?) RFC: https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md
Current merged solution: https://github.com/rust-lang/rust/pull/51063

**Comment by Keats** [comment]
In the meantime I published 0.3.4 which is a cargo updated version only

**Comment by ilovezfs** [comment]
Awesome! Thank you @Keats. 0.3.4 shipped in Homebrew https://github.com/Homebrew/homebrew-core/pull/29331

**Comment by Keats** [comment]
So I believe the issue is *only* with https://github.com/compass-rs/sass-rs as libsass uses global, which Rust seems to have issues with. Should we move this issue there?

**Comment by Keats** [comment]
Closing in favour of the issue in sass-rs linked above
