### ISSUE TITLE
[feature request] Add config option for template filename suffix

### ISSUE THREAD

**Issue by sebtombs** [getzola/zola#320]
Rather than always having templates as .html, could we have a config option to set it to something else (e.g. .tera) as this is beneficial for some use cases?
Mine is two-fold, I'm used to distinguishing .twig from .html, and also my preferred editor has intelligence based on the file suffix.

**Comment by Keats** [comment]
Escaping in Tera depends on the files extension so I don't think it would be safe to do that change. Can you not set your editor to use Jinja2 for .html for a specific project?

**Comment by sebtombs** [comment]
Ah - I think I see. So we could in principle, for example, have a .md file with Tera syntax in it, and Tera uses the suffix to determine it is dealing with Markdown rather than HTML, and therefore what to escape? In that case, I agree. Please ditch this request. My workaround is to symlink .tera to .html for each file which is not too painful.

One question though - why does the template code look for *.*ml, whereas for a theme it is explicitly *.html (site/src/lib.rs tpl_glob and theme_tpl_glob)?

**Comment by Keats** [comment]
> Ah - I think I see. So we could in principle, for example, have a .md file with Tera syntax in it, and Tera uses the suffix to determine it is dealing with Markdown rather than HTML, and therefore what to escape? 

Yes, although Gutenberg only uses template for HTML/XML so everything is escaped basically.

> One question though - why does the template code look for *.*ml, whereas for a theme it is explicitly *.html (site/src/lib.rs tpl_glob and theme_tpl_glob)?

It should look for the same thing actually so that's a bug :o thanks for noticing it!
Ideally it will use something like `*.*{html|xml}` but that requires updating Tera to use the `globset` crate rather than the `glob` one
