### ISSUE TITLE
Way of mapping permalinks to different URL for shortlinks

### ISSUE THREAD

**Issue by clarfonthey** [getzola/zola#321]
Right now, my website is hosted at `clar.charr.xyz`, and I have a separate section for my blog at `clar.charr.xyz/blog/`. One thing that I do is map `b.charr.xyz` to `clar.charr.xyz/blog/`, so that for example `clar.charr.xyz/blog/post/` becomes `b.charr.xyz/post` as a shortlink. Right now, I accomplish this in templates with:

```
{%- set shortlink =
    page.permalink |
    replace(from=config.base_url, to='') |
    replace(from='blog/', to='') |
    replace(from='/', to='')
-%}
```

Which admittedly is kind of of hack. It'd be nice if we could configure sections with a `shortlink_base_url` which would then basically replace the base URL (e.g. `https://your-site.tld/section/path`) with a string (e.g. `short.tld`, and not output a trailing slash. Also, if a shortlink is available, use that in the RSS feed as well.

I'd be cool implementing something like this (it doesn't seem very hard) if it seems like something reasonable. I feel like I'm not the only person with this kind of use case, although it's worth asking anyway.

**Comment by Keats** [comment]
Hmm that does seem a bit niche though and can already be solved with a small hack so I would wait to see if more people want this feature

**Comment by Keats** [comment]
It doesn't look like a lot of people want that, closing.
