### ISSUE TITLE
Syntax highlighting causes panic

### ISSUE THREAD

**Issue by codesections** [getzola/zola#326]
Attempting to apply highlighting to certain code causes a panic that prevents the site from building.

For example, writing 

\```js
function addTwo(number) {
  return number * 2;
}
\```

results in the following error:

```bash
$ gutenberg serve
Building site...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(-114, target of repeat operator is invalid)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

(That wasn't the actual code I wanted to highlight; it's a simplified example that I found after playing around.  In that simple example, the `return` keyword seems to trigger the bug.  However, the full text I wanted to highlight (shown below) still exhibited the bug even after removing all uses of `return`.)

Using backticks without syntax highlighting didn't trigger the bug.

Here's the full text I was attempting to highlight:

```
```js
(window.NREUM||(NREUM={})).loader_config={
  xpid:"UQ8EUVRACQAFVVdbAQk="
};
window.NREUM||(NREUM={})
,__nr_require=function(t,n,e){
  function r(e){if(!n[e]){var o=n[e]={exports:
    {}};t[e][0].call(o.exports,function(n){
      var o=t[e][1][n];return r(o||n)},o,o.exports)
    }return n[e].exports}if("function"==typeof __nr_require)
    return __nr_require;for(var o=0;o<e.length;o++)r(e[o]);
    return r}
\```

**Comment by Keats** [comment]
Which version are you using? This kind of error means that syntect doesn't understand some part of the sublime syntax files, which happens sometimes when the syntaxes get updated and needs to be fixed upstream.

**Comment by codesections** [comment]
I'm using 0.3.4, which I cloned from GitHub and built from source earlier today, so it should be up-to-date.

**Comment by codesections** [comment]
You were absolutely correct; the issue was upstream and had already been resolved.  I fixed it by downloading the AUR package instead of building from source.  That's what I get for building from source when I apparently don't (yet!) understand the Rust package system well enough to upgrade all the dependencies.  Sorry for taking up your time with this.
