### ISSUE TITLE
Completion file generated, but not installed automatically in AUR (gutenberg-bin)

### ISSUE THREAD

**Issue by codesections** [getzola/zola#327]
After installing Gutenberg, I did not have completions for either Zsh or Bash.  This was true whether I installed the package from the AUR or built it from source.  However, after building it from source, I noticed that the `_gutenberg` file was present in the completion directory; copying that file manually to a directory in my $fpath enabled completions.  Maybe something to copy that file automatically should be added to the install script?

**Comment by Keats** [comment]
Did you use `gutenberg` or `gutenberg-bin` from the AUR? I'm not too sure what's the best way to ship the completions with `gutenberg-bin` (which is the one I maintain) but it shouldn't be too hard with `gutenberg` as it has the completions already generated in the tar.gz
One solution would be to add a command to generate completions to gutenberg itself adding 1 command just to get completions on 3 commands that are very basic feels a bit icky

**Comment by codesections** [comment]
This was with gutenberg-bin from the AUR.  I don't (yet) know enough about makepkg to know how gutenberg could ship completions in that format, but it seems like there has to be a way.

**Comment by Keats** [comment]
The AUR package is now called `zola-bin` but the issue still stands.
Anyone has an idea on how to package it without adding a separate command to Zola?

**Comment by Keats** [comment]
Closing. There are only 3 commands in Zola so it's a very low priority
