### ISSUE TITLE
Live demos of themes?

### ISSUE THREAD

**Issue by codesections** [getzola/zola#332]
Are there any live site demos of the varrious Gutenberg themes?  I looked on the [theme page](https://www.getgutenberg.io/themes/) and did not see any links.

If there are not, will would be happy to create a demo for each theme with lorum ibsum content and submitt a pull request to add links to the demo site to the theme page.

**Comment by Keats** [comment]
As mentioned in a PR, that would definitely be something I'm interested in

**Comment by codesections** [comment]
Thanks!  Demos of the current themes are avalible at <https://gutenberg-theme-demo.netlify.com/>.  I haven't publisized this yet because I'm waiting on the resolution of Keats/book#1—the live demo of the Book theme incorporates my changes to that theme, because I could not get the theme to work as it was written.  Once that issue is resolved, I'll share this externally.

After 0.4 is released, I'll check these demos for compatibility issues, resolve any issues, and then submitt a pull request to add the links to the main theme site in the documentation.

**Comment by codesections** [comment]
Now that the issues with Book have been resolved, the theme demo site is ready to go.  As discussed, I'll hold off on submitting a pull request for links from the docs until after I've tested for compatibility with v0.4, but the site is live now:

https://gutenbergthemes.codesections.com/

**Comment by Keats** [comment]
I added demos of themes directly to each theme repo through netlify, this way they get updated immediately and it only took me ~1 min per theme.
We could have better quality demos though in terms of content

**Comment by codesections** [comment]
I've submitted a pull request to update Even with the demo content I put together.  keats/Even#5 If that looks good, I can submit similar pull requests with similar demo content for the other themes.

**Comment by Keats** [comment]
There are live demos of themes now so closing this. Getting better default data can be an issues on individual theme repos
