### ISSUE TITLE
`index.subsections` array always sorted by weight (random if no weight)

### ISSUE THREAD

**Issue by codesections** [getzola/zola#335]
The `index.subsections` array is always sorted by weight, regardless of whether the page/section is set to sort by weight or order.  Worse, if no weight is set, the sorting is random, leading to non-deterministic builds.

Relatedly, `index.subsections` does not expose an `order` or `weight` field, which prevents using the Tera `sort(attribute="order")` filter as a workaround.  It seems like it should expose those two fields (it already exposes `date`).

**Comment by Keats** [comment]
> The index.subsections array is always sorted by weight, regardless of whether the page/section is set to sort by weight or order.

That's intended, there is *only* a `weight` field on the section frontmatter: https://www.getgutenberg.io/documentation/content/section/#front-matter and otherwise we don't really have a way to sort. We could default to a-z but I'm not sure it makes much sense since that's pretty much never what you want  if you are looking at subsections.

> Relatedly, index.subsections does not expose an order or weight field.

The `weight` could be exposed but it should already be started while serializing, what would be the use in the template?

**Comment by codesections** [comment]
Interesting.  It seems like the code draws a strong conceptual distinction between pages and subsections, which might well be justified for reasons that I'm not understanding but that is not at all intuative. 

For instance, someone might have the following directory structure:

```
/blog
    /blog/post1.md
    /blog/post2.md
    /blog/post3.md
```

Someone else might have a very similar structure using sub-directories:
```
/blog
   /blog/post1
      /blog/post1/index.md
   /blog/post2
      /blog/post2/index.md
   /blog/post3
      /blog/post3/index.md
```

(The second person might have that stucture to be able to take advantage of asset co-location).  I would have thought that you would want both structures to support sorting by date, order, or weight.  Is it the intended behavior that the intended behavior is for the second structure to *only* be sortable by weight?

In cases where the intended behavior is for sections to only be sorted by weight, it may make sense to have a deterministic way of resolving ties (alphabetical by slug?).  The behavior I was encountering when working on my pull request for Keats/book#1 was that when sections weren't given a weight, they were presented in a random order—and that order was **different** on each build of the site.  This lead to non-deterministic builds, and seems like it could raise significant issues.  I would think that there either needs to be a deterministic way of resolving ties, or ties in weight need to present the user with an error message/warning.

**Comment by Keats** [comment]
The second example doesn't really make much sense, you can use colocated assets without creating a new section. It would look like that:


```
/blog
   post1.md
   post2/
      index.md
  post3.md
```
Only one section (`blog`) would be created, co-locating assets does not create a new section. No need to create a section per post.

Regarding a-z ordering, I'm still not entirely sure it makes sense to have that for subsections since a-z is never what you want and having a deterministic ordering could hide the problem for a bit while random order makes it obvious.

**Comment by codesections** [comment]
Picking this back up again now in light of the discussion in #338.

Is there a reason for sorting sections to work so differently from sorting pages?  Pages can be sorted by `date`, `order`, and `weight` and (per the docs) break any ties based on alphabetical order of the permalink.   

Sections can only be sorted by `weight`, and do not break ties at all but instead randomize the order at build time.  

I'm not sure which of those approaches is *better*, but they're clearly **different**.  If there's a reason that they're different, I'd like to put it in the docs to reduce confusion.  If there's no reason for them to be different, maybe they should be standardized so that pages and sections can be sorted similarly.

(This doesn't come up that much in blog/personal site use cases, because those sites tend to have many pages but very few sections.  But it could easily come up more in more advanced use cases, and it seems like one of Gutenberg's real strengths is that it isn't focused just on blogs the way some other static site generators might be.)

**Comment by Keats** [comment]
Sections can only really have order by order or weight, date doesn't really make sense.
As mentioned in the other thread, `order` and `weight` are just opposite of each other so I put only one way to sort to keep it simple and `weight` makes the most sense to me. I don't think it makes much sense to try to imitate the pages there, the only times you want to order sections are for menus/index

**Comment by Keats** [comment]
I think this can be closed now that there is only weight? Re-open if it's not the case
