### ISSUE TITLE
config variable not found in macro

### ISSUE THREAD

**Issue by jsdw** [getzola/zola#336]
Hello,

I ran into this issue when trying to use `config.base_url` from a macro:

```
Failed to build the site
Error: Failed to render section '/path/to/project/content/_index.md'
Reason: Failed to render 'home.html': error while rendering a macro from the `macros` namespace
Reason: Variable `config.base_url` not found in context while rendering 'home.html'
```

home.html extends index.html, which itself has no issues using context.base_url.

My attempted usage looked like:

```
<img src="{{ config.base_url }}/icons/view_source.svg" />
```

Offhand I can't see why this wouldn't work; is it a bug or am I being silly?

Thanks!

**Comment by Keats** [comment]
Did you pass the `config` variable to the macro containing that line? The only context macros get is from their arguments

**Comment by jsdw** [comment]
Aah ok, I did not! I had wondered whether that was the case, but I suppose I had the impression that config was somewhat global :)

Thanks for the super quick response!

**Comment by Keats** [comment]
`config` is global to the templates but macros are like pure functions that can't access the global context.
Don't hesitate if you have another question!
