### ISSUE TITLE
Sections are not automatically created as said in the docs.

### ISSUE THREAD

**Issue by itsfarseen** [getzola/zola#339]
According to docs:
> A section is automatically created when a folder is found in the content section, unless it only contains a index.md file and is actually a page with assets.

But a section is not created unless it contains a `_index.md`.

__Steps to reproduce__
```bash
gutenberg init test
cd test
mkdir content/section1
echo -e '+++\n+++\n#Hello World' >./content/section1/post1.md
gutenberg serve
```
__Expected output__
```bash
Building site...
-> Creating 1 pages and 1 sections
... snip ...
```

__Actual output__
```bash
Building site...
-> Creating 1 pages (1 orphan) and 0 sections
... snip ...
```

**Comment by codesections** [comment]
It seems to me that the current behavior is correct, and that the docs ought to be updated to reflect that behaviour.  Do you agree?  

That is, I  think that a section should only be created if the folder contains an `_index.md`.  I think this has two advantages:
 * It creates better semantics for seeing if a folder is a section: if it has an `_index.md` file, then it's guarenteed to be a section; if it lacks an `_index.md` file, it is guarenteed *not* to be a section.
 *  It allows for easier creation of orphan pages, which might be desierable in some use-cases.  For example, an ecomerce site might want to have `/products/product1` and `products/product2` as pages without having `/products` as a section.  (I note that the user could achieve a similar effect by creating the `/products` section and then setting `render = false` in its front matter.  But it seems less intuative to create a section and then prevent it from rendering than to just not create it.  Plus, Gutenberg will correctly note that the section was created (but not rendered) and will thus not classify the pages within that section as orphans, which seems less useful).

If you agree that the current behaviour is correct, then I'd be happy to submit a pull request updating the docs.

**Comment by Keats** [comment]
Looks like it's a documentation issue, only the index section is automatically created.
I'll take a PR for it, thanks!
