### ISSUE TITLE
Cannot use asset colocation inside section content

### ISSUE THREAD

**Issue by codesections** [getzola/zola#340]
Consider a site with the following directory structure:

```
└── content/
    ├── about.md
    └── blog/
        ├── _index.md
        ├── blog_header_image.jpg
        ├── post1.md
        └── post2.md
```

Based on the [documentation regarding asset colocation](https://www.getgutenberg.io/documentation/content/overview/#assets-colocation), I would expect to be able to access `blog_header_image.jpg` with a relative link from `_index.md`.  Instead, it seems that there is not a way to access `blog_header_image.jpg`.

**Comment by Keats** [comment]
Colocation is only for pages currently. No particular reason other than I didn't think it would be that useful

**Comment by codesections** [comment]
Makes sense.  I guess that puts this in the "feature request" category, then.  I don't think it should be a high priority, but I think there is a use case for it.  I tried to gesture towards one use case with my example above, where a site owner might have images that are specific to a particular section (like a header or background image for a blog).  I don't think this is that big of a deal—asset colocation is a convience feature, and definitly possible to get the same result using the `static` folder.  But it does seem like a nice-to-have-but-not-need-to-have feature for one day.

**Comment by paulcmal** [comment]
I wrote some PR for this. Hopefully it makes sense! :D

Thanks for labeling this issue `good first issue`. I stumbled upon it but would never have dared to take a look at the code otherwise :)

**Comment by piedoom** [comment]
I'm somewhat in agreement with Keats here... how would asset colocation within a section be useful?  There is no organization within the folder and assets will be jumbled just like in the static folder.  

I'm not saying that it's not a nice feature, but I think it will require more thought than just plopping the feature as-is for collections.  e.g., if posts were organized in directories along with their media (or if media was listed in a directory with the same name as the `.md` post) it would be much more organized and useful IMO.

**Comment by codesections** [comment]
I'm a bit confused by your comment, @piedoom.  You wrote:

>  e.g., if posts were organized in directories along with their media … it would be much more organized and useful IMO.

But, unless I'm misunderstanding something (always possible!) this is exactly how things *already* work with the existing version of Gutenberg, before pull request #364.

For example, consider a site with a homepage, an `about` page, and a `blog` section, with three pages in the `blog` section.  Further assume that they want to co locate assets with the blog pages.  They'd thus have an directory structure like this:

```
└── content/
    ├── about.md
    └── blog/
        ├── _index.md
        ├── post1/
             ├── index.md
             └── image_for_post1.jpg
        ├── post2/
             ├── index.md
             └── image_for_post2.jpg
        └── post3/
             ├── index.md
             └── image_for_post3.jpg
```

Isn't' that having "posts organized in directories along with their media"?  If so, that's already supported now.  Or did you have something else in mind?

**Comment by paulcmal** [comment]
> Or did you have something else in mind?

They were referring to the discussion taking place in #364 (the PR) and more specifically Keats' comment:

> This PR loads all non-md files in the same folder as a _index.md file as this section's asset. When you start having a few .md files in a directory like in https://github.com/Keats/vincentprouillet/tree/master/content/blog, the assets files will be spread around the directory based on their filename instead of being neatly co-located with the related _index.md.file
>
> My idea was to use the same system the pages use: if we see a _index.md file, we don't load any assets. However if we find a _index folder in the content directory, we assume that it's equivalent to the _index.md file with the difference it has some co-located assets and load the index.md inside this folder.

Personally, i was arguing for supporting both workflows.

Maybe the conversation can continue here? it's probably more appropriate, sorry for bringing it over there ^^

**Comment by codesections** [comment]
Thanks.  I understood that Doomy was referencing to the discussion in PR #364—I referenced that PR in my comment.  But I took Doomy to be saying that the behavior added by PR #364 wouldn't be useful because Gutenberg doesn't support "post organized in directories"—but it already does, even before your PR. 

Anyway, I agree that the discussion makes more sense in that PR.  I have further thoughts that I'll post there.

**Comment by piedoom** [comment]
I was unaware of that feature @codesections, I thought Keats was saying it didn't exist but I misunderstood.  Thanks for pointing it out.

My thought process is that both the markdown file and its assets in the same folder would be recognized as a separate collection but apparently that is not the case.

While I wouldn't want to organize my assets in the way currently being proposed, I think the option is a nice one to have :)

**Comment by Keats** [comment]
This is in 0.4.2 (currently being built).
