### ISSUE TITLE
`matching()` test appears to be broken

### ISSUE THREAD

**Issue by codesections** [getzola/zola#342]
I attempted to duplicate the matching example from the [tera documentation](https://tera.netlify.com/docs/templates/#built-in-tests).  Based on my testing, I believe that the `matching()` test does not work correctly.

If you would prefer that I close this issue here and reopen it in Tera, I can do so.  I opened it here because I encountered the issue in Gutenberg and I do not have a good way to test Tera other than through Gutenberg. 

## Steps to reproduce:
Set the following as `index.html`
```jinja2
{% set name = "Queen" %}

{% if name is matching("^[Qq]ueen") %}
    Her Royal Highness, {{ name }}
{% elif name is matching("^[Kk]ing") %}
    His Royal Highness, {{ name }}
{% else %}
    {{ name }}
{% endif %}
```
run `gutenberg serve` and navigate to `http://127.0.0.1:1111/`.

## Expected output
`Her Royal Highness, Queen`

## Actual output
`Queen`

**Comment by Keats** [comment]
A copy/paste of the reproduction yields the correct output for me. The `matching` test is new so unless you build gutenberg from source, it won't be there and you will fall in the else branch
