### ISSUE TITLE
Gutenberg 0.3.4 panics when building site

### ISSUE THREAD

**Issue by codesections** [getzola/zola#344]
I have discovered that version 0.3.4 will not build my site, and provides a non-helpful error message:

```
Building site...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(-114, target of repeat operator is invalid)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(-114, target of repeat operator is invalid)', libcore/result.rs:945:5
```

0.3.3 work, and 0.4.0 (built from source from the `next` branch) work.  It also seems like at least some other sites work with 0.3.4 on my local machine, so it doesn't seem to be an issue with my local environment. 

Not a high priority issue since I can use other versions, but one that I wanted to raise—especially because I'm not sure how widespread the issue might be.

**Comment by codesections** [comment]
I did further testing and realized that the issue is related to the syntax highlighting feature.  Although I didn't remember initially, it was the same error I initially encountered in #326, which was caused by building from source without updating the submodules.  Is it possible that the 0.3.4 release did not include the latest upstream changes to submodules that are in 0.3.3?

**Comment by Keats** [comment]
There was probably a faulty syntax in 0.3.4 that has been fixed since then. I need to make sure I run all the syntect tests when I update the Sublime submodule
