### ISSUE TITLE
Consider adding `page.parent_section` varriable

### ISSUE THREAD

**Issue by codesections** [getzola/zola#350]
Every page belongs to exactly one section.  Could the section to which the page belongs be exposed as a `page` variable?  It could be called `parent_section` or `containing_section` or something along those lines.

This would greatly simplify several use cases.  Most obviously, in the Book theme, there is currently a fairly long nested loop to figure out the parent section:

```jinja2
        {% set index = get_section(path="_index.md") %}
        {% for subsection in index.subsections %}
            {% for p in subsection.pages %}
                {% if p.permalink == page.permalink %}
                    <a class="previous" href="{{ subsection.permalink }}"><</a>
                {% endif %}
            {% endfor %}
        {% endfor %}
```

If we had access to a `parent_section` variable, this could be replaced by 
```jinja2
<a class="previous" href="{{ page.parent_section }}"><</a>
```

It would also be useful for easily checking `[extra]` variables that could be set in the `_index.md` file so that users could set section-wide settings that apply to all pages in the section (without creating a separate page template for pages in that section).

**Comment by Keats** [comment]
I can see the use but I want to have more benchmarks before adding too many things to each variables

**Comment by Keats** [comment]
That is basically done in the `next` branch, you get all of the ancestors of a page.
