### ISSUE TITLE
Code doesn't seem to work in Markdown filter

### ISSUE THREAD

**Issue by keysmashes** [getzola/zola#354]
I have a template that includes this line:

```
{{ "foo *bar* `baz` quux" | markdown }}
```

but when rendered, it looks like this:

![image](https://user-images.githubusercontent.com/9433472/43358133-ca8d231a-9284-11e8-9aed-8e18736b179f.png)

i.e. the backticks aren't turning into a `<code>` block. Using `inline=True` doesn't seem to make a difference.

I'm using Gutenberg 0.3.4 from the GitHub releases.

**Comment by Keats** [comment]
The issue is that the backticks get escaped. 
```
{{ "foo *bar* `baz` quux" | safe | markdown }}
```
 will work

**Comment by keysmashes** [comment]
Ahh, thank you!
