### ISSUE TITLE
Consider explicit error handling in templates?

### ISSUE THREAD

**Issue by codesections** [getzola/zola#355]
I was wondering whether it would be worth including a way for templates to explicitly panic/refuse to build.  The way this has come up for me is with the `<!-- more -->` tag—I constantly forget to include it, and it would be great if I set a template to error out when I haven't set it.  I wish I could write
```jinja2
        {% if page.summary %}
          {{ page.summary | safe }}
        {% else %}
          {% panic("Error: " ~ page.title ~ " did not include a summary") %}
        {% endif %}
```

As a hackish workaround, I currently have 
```jinja2
        {% if page.summary %}
          {{ page.summary | safe }}
        {% else %}
          {# hackish way to throw an error #}
          {{ please_include_a_summary }}
        {% endif %}
```
Because there I don't have a `please_include_a_summary` variable, this throws an error, but isn't elegant at all.  I can think of a few other cases where a template might depend on variables (either built-in or `extra` variables) being set in front matter and would benefit from being able to panic if those variables aren't set.

**Comment by sebtombs** [comment]
I support the concept, but wonder if something like "fail" or "throw" may be better than "panic"?

**Comment by piedoom** [comment]
I think `panic` is because Gutenberg is written in Rust - but if this feature is considered it may be a good idea to see if Rust users are the *main* users of Gutenberg.  Otherwise `fail` or `throw` might be more familiar.  Though I'm being nit-picky for something that might not even be a good fit :)

However, I see a lot of value in what @codesections has proposed and can see the feature being very useful in making sure my themes always spit back useful information.

**Comment by codesections** [comment]
Yeah, I'm not tied to the `panic` syntax—@piedom is right that I only suggested it because of the Rust tie.  But any of the `panic`/`throw`/`fail` options would accomplish the same objective.

**Comment by Keats** [comment]
That is something that can/should be in Tera directly so I opened an issue there

**Comment by Keats** [comment]
See https://github.com/Keats/tera/pull/310 for an implementation, let me know if you have any feedback before I merge & release

**Comment by Keats** [comment]
It's in the next branch, which should be released today unless something goes wrong

**Comment by piedoom** [comment]
@Keats you're awesome!

**Comment by Keats** [comment]
> you're awesome!

Thanks!

>  should be released today unless something goes wrong

and it did! failure update is currently breaking the build so waiting for dependencies using failure to release new versions...
