### ISSUE TITLE
Some Tera features do not seem to be working in Gutenberg

### ISSUE THREAD

**Issue by sebtombs** [getzola/zola#356]
Concatenation of strings using the ~ operator, as per the Tera documentation, does not seem to be implemented in Gutenberg templates. This is not urgent as a work-around is possible using replace:

`{% set workingstring = "^_<second string>" %}`
`{% set result = workingstring | replace (from="^", to=<first string>) %}
`
Choose some character other than ^ if your strings could contain ^.

The date(format="<blah>") filter also does not seem to be implemented.

This is puzzling, as Tera seems to have not changed since February with the 0.11.3 release.

**Comment by codesections** [comment]
Both of these features are working in the `next` branch and will be working in the upcoming 0.4.0 release.

String concatenation also should work in version 0.3.4, but not with 0.3.3; I'm not sure about the `date(format="")` filter. 

There unfortunately seem to be a few documented features that aren't working in the release version; I ran into a similar problem in #342.

**Comment by Keats** [comment]
Tera and Gutenberg are two separate projects. 
The Tera site always contains the docs for the latest released version and Gutenberg might not have had a release since then so there can be a lag between the doc site and what is usable
