### ISSUE TITLE
Equivalent to setcontent

### ISSUE THREAD

**Issue by sebtombs** [getzola/zola#357]
In Twig for Bolt, content can explicitly be set using "setcontent" inside the template. This is useful for common blocks which are used in asides, footers, etc, without having to change the template itself.

I haven't managed to work out a way of getting similar behaviour in Gutenberg. Is this currently possible?

**Comment by codesections** [comment]
I'm not familiar with Twig/Bolt but, if I understand `setcontent` correctly, then I think you can accomplish the same thing with the `set` Tera filter (perhaps combined with other Gutenberg features to get a particular target value). 

For example, the first `setcontent` example in [Twig's docs](https://docs.bolt.cm/3.5/templating/twig-functionality#setcontent) is 

```twig
{% setcontent about = 'page/about' %}
<h3>{{ about.title }}</h3>
{{ about.introduction|raw }}
<a href="{{ about.link }}">link</a>
```

I believe you can do the same thing in Gutenberg with:
```jinja2
{% set about = get_page(path="about.md") %}
<h3>{{ about.title }}</h3>
{{ about.summary | safe }}
<a href="{{ about.permalink }}">link</a>
```

Would that do what you're looking for, or did I misunderstand what you're asking?

**Comment by Keats** [comment]
Do you have a usage example? Looking at the docs https://docs.bolt.cm/3.5/cheatsheet#the-setcontent-tag it seems equivalent to calling one of the available global functions as @codesections showed.

**Comment by sebtombs** [comment]
Thanks both - get_page does indeed do exactly what I was trying to do.
