### ISSUE TITLE
Upgrade serve to use actix 0.7

### ISSUE THREAD

**Issue by onelson** [getzola/zola#358]
As per #310 I think we should be able to ditch the direct dependency on `actix` by relying on the re-export in `actix-web`. It wasn't available at the time, but it's there now.

Not sure where this fits in in terms of the release gutenberg cycle, but I'd be happy to look at the the upgrade this week, aiming to complete the work by the weekend.

**Comment by Keats** [comment]
It is actually already updated in the [next](https://github.com/Keats/gutenberg/blob/next/Cargo.toml#L27) branch!

**Comment by onelson** [comment]
Whoops!
