### ISSUE TITLE
Page path collisions

### ISSUE THREAD

**Issue by paulcmal** [getzola/zola#366]
While implementing section assets, i encountered an edge case where two pages try to render to the same path and one overwrites the other silently. I believe there should be some kind of runtime warning in such situations even though that should not happen often.

Otherwise, we should add in the content docs explanations about when collisions may happen (i'm guessing it's because of slugification?) and how to avoid them. Maybe it's already somewhere in the docs? I just didn't see ^^

Content tree:
```
└── content/
    ├── _index.md
    └── blog/
        ├── _index.md
        ├── capitalism.jpg
        ├── _index/
             ├── index.md
             └── capitalism.jpg ← (not the same one as in blog/, i was trying to force collisions)
        ├── index/
             ├── index.md
```

Here _index/index.md gets rendered to /blog/index and index does not get rendered (or at least not copied to public). Renaming either _index/ or index/ enables both to get rendered properly.

Debug info:

```
Parsing page from file "/home/user/Sites/Gutenberg/content/blog/_index/index.md"
Parsing page from file "/home/user/Sites/Gutenberg/content/blog/index/index.md"
Now pages:
[Ok(Page { file: FileInfo { path: "/home/user/Sites/Gutenberg/content/blog/_index/index.md", name: "index", relative: "blog/_index/index.md", parent: "/home/user/Sites/Gutenberg/content/blog", grand_parent: None, components: ["blog"] }, meta: PageFrontMatter { title: Some("Bloggity blog"), description: None, date: Some("2018-03-01"), draft: false, slug: None, path: None, taxonomies: {}, order: None, weight: None, aliases: [], template: None, in_search_index: true, extra: {} }, raw_content: "\n![](capitalism.jpg)\n", assets: ["/home/user/Sites/Gutenberg/content/blog/_index/capitalism.jpg"], content: "", slug: "index", path: "blog/index/", components: ["blog", "index"], permalink: "http://127.0.0.1:1111/blog/index/", summary: None, earlier: None, later: None, lighter: None, heavier: None, toc: [] }), Ok(Page { file: FileInfo { path: "/home/user/Sites/Gutenberg/content/blog/index/index.md", name: "index", relative: "blog/index/index.md", parent: "/home/user/Sites/Gutenberg/content/blog", grand_parent: None, components: ["blog"] }, meta: PageFrontMatter { title: Some("fucking page"), description: None, date: Some("2018-03-01"), draft: false, slug: None, path: None, taxonomies: {}, order: None, weight: None, aliases: [], template: None, in_search_index: true, extra: {} }, raw_content: "", assets: [], content: "", slug: "index", path: "blog/index/", components: ["blog", "index"], permalink: "http://127.0.0.1:1111/blog/index/", summary: None, earlier: None, later: None, lighter: None, heavier: None, toc: [] })
```

**Comment by Keats** [comment]
I agree there should be some mention in the docs, and it should maybe even be an error if two pages get rendered at the same end path

**Comment by Keats** [comment]
That's going to be checked with the upcoming `zola check` subcommand

**Comment by phil-opp** [comment]
Any updates on this? The `zola check` command exists now, but I'm not sure if this is included.

It would be also very useful to have this error also on `zola build` since I can't use `zola check` right now because of https://github.com/getzola/zola/issues/805.

**Comment by Keats** [comment]
I did forget about this. It should be easy to implement if anyone is looking an easy issue and as mentioned should happen in `zola` build as well as `zola check` as it is likely an issue in a site that needs to be fixed.

**Comment by Keats** [comment]
It's in `next` with some pretty ugly code but it does the job.

**Comment by phil-opp** [comment]
Great, thanks!
