### ISSUE TITLE
Q: How to pass custom keys in front matter to template?

### ISSUE THREAD

**Issue by marvinhagemeister** [getzola/zola#371]
Just installed gutenberg and playing around with it so this may be more of a question than an issue: I'm currently trying to pass custom defined key-value pairs from front-matter to my template, but I'm failing to do so.

`/content/foo/index.md`:

```md
+++
title = "Foo"
description = ""
weight = 0
draft = false
template = "page.html"
foo="bar"
+++

Hello I am Foo
```

`/templates/page.html`

```html
{% extends "index.html" %}

{% block content %}
   <div>{{ page.foo }}</div>
  {{ page.content | safe }}
{% endblock content %}
```

The `page.foo` variable doesn't exist and this is confirmed by dumping all variables in the current context with `{{__tera_context }}`. Maybe I'm just missing something. How do you pass variables from front matter to a template?

**Comment by adamhammes** [comment]
Have you tried putting the `foo` key in the `extra` hash? [From the docs:](https://www.getgutenberg.io/documentation/content/page/#front-matter)

```toml
# Your own data
[extra]
```
So in your case I think you could do

```toml
[extra]
foo = "bar"
```
And then access it in the template with

```
{{ page.extra.foo }}
```

**Comment by marvinhagemeister** [comment]
@adamhammes Ohh right, I knew I was missing something trivial. Thanks for clearing it up 👍

**Comment by zachbellay** [comment]
Here is an updated link to the docs that @adamhammes linked: [https://www.getzola.org/documentation/content/page/#front-matter](https://www.getzola.org/documentation/content/page/#front-matter)

**Comment by andrienko** [comment]
Is there any optioni to use the `[extra]` secion with YAML?

**UPD:** For everyone guessing - just do
```
extra:
  yourKey: Whatever
```
