### ISSUE TITLE
including seperate html/md in a content file

### ISSUE THREAD

**Issue by bdjnk** [getzola/zola#375]
I have html generated by [ansi2html](https://github.com/ralphbean/ansi2html).

I'd like to keep it outside my markdown for cleanliness, but include in the final output.

I attempted to include it via a shortcode and ran into this issue.

`content/page.md`
```
{{ ansi(content="output.html") }}
```

`templates/shortcodes/ansi.html`
```
{% include content %}
```

`gutenberg serve`
```
* Failed to parse "/.../templates/shortcodes/ansi.html"
 --> 1:12
  |
1 | {% include content %}
  |            ^---
  |
  = expected a string
```

I've raised a request at the Tera repository asking that [include should accept an ident resolvable to a string](https://github.com/Keats/tera/issues/320).

Is there a workaround other than include the html output directly in my markdown?

**Comment by Keats** [comment]
This is more about Tera than Zola. Closing in favour of the open issue in Tera.

**Comment by eugenesvk** [comment]
fyi there seems to be an available workaround to include where you can load the prebuilt files and add their content instead, check out this comment https://github.com/getzola/zola/issues/2175#issuecomment-1503385601

(unless it's more complicated and you have some templating logic in the file, afaik)
