### ISSUE TITLE
Summaries break reference-style Markdown links

### ISSUE THREAD

**Issue by Freaky** [getzola/zola#376]
Because `<!-- more -->` handling is done on the raw Markdown document, this breaks:

```markdown
[Foo][foo]
<!-- more -->
[foo]: http://foo.example
```

The reference gets split off from the content when the summary is rendered, leaving the links rendering literally.

While it's far from a satisfying fix, this works:

```rust
--- components/content/src/page.rs
+++ components/content/src/page.rs
@@ -191,13 +191,8 @@ impl Page {
         ).chain_err(|| format!("Failed to render content of {}", self.file.path.display()))?;
         self.content = res.0;
         self.toc = res.1;
-        if self.raw_content.contains("<!-- more -->") {
-            self.summary = Some({
-                let summary = self.raw_content.splitn(2, "<!-- more -->").collect::<Vec<&str>>()[0];
-                render_content(summary, &context)
-                    .chain_err(|| format!("Failed to render content of {}", self.file.path.display()))?.0
-            })
-        }
+        self.summary = self.content.find("<p><a name=\"continue-reading\"></a></p>")
+                                   .map(|pos| self.content[0..pos].to_owned());

         Ok(())
     }
```

**Comment by Keats** [comment]
What would be a satisfying fix for you? Looking at it, I don't see a much better solution than your patch

**Comment by Freaky** [comment]
Pushing it into rendering seems more appropriate, seeing as it's basically all about how raw content is parsed and depends on how it's rendered.

**Comment by Freaky** [comment]
As an aside, most of the `Owned()` bits in the Markdown parser should really be `Borrowed()`.  e.g. `Owned(String::new())` &rarr; `Borrowed("")`.
