### ISSUE TITLE
Renaming the project

### ISSUE THREAD

**Issue by Keats** [getzola/zola#377]
With WordPress starting to heavily promote their Gutenberg editor, SEO will become impossible for this project.

I'm open to changing the name, the current requirements are:

- simple to type, binary name must not exist in windows/linux/osx already
- a cheap domain name for the docs must be available
- no significant open-source project with the same name
- no obvious weird meaning in languages

Current ideas:

- **zola**: from Emile Zola, a french writer - 4 letters is pretty good. Downside is Hugo is also a french writer
- **kuo**: https://en.wikipedia.org/wiki/Shen_Kuo

Changing the name means also changing every package manager + netlify

**Comment by onelson** [comment]
I cannot stress enough that this is a joke, but what about **Mahoney** (as per the Steve Guttenberg role in the Police Academy movies)?

**Comment by Freaky** [comment]
How about a Chinese writer?  [Shen Kuo](https://en.wikipedia.org/wiki/Shen_Kuo) wrote extensively about movable type printing, amongst many, many other things, and while Shen is a [programming language](https://github.com/Shen-Language), `kuo` looks free.  Wordsafety.com warns about a similarity to Portuguease "cu" (asshole).

[Bi Sheng](https://en.wikipedia.org/wiki/Bi_Sheng) invented the first movable type printer.  `sheng` seems free.

[Wang Zhen](https://en.wikipedia.org/wiki/Wang_Zhen_\(inventor\)) improved on movable type. `zhen` seems free, and is also closely resembles "Zen".

**Comment by Keats** [comment]
I like Kuo but this guy makes me feel a bit inadequate:

> Excelling in many fields of study and statecraft, he was a mathematician, astronomer, meteorologist, geologist, zoologist, botanist, pharmacologist, agronomist, archaeologist, ethnographer, cartographer, encyclopedist, general, diplomat, hydraulic engineer, inventor, academy chancellor, finance minister, governmental state inspector, poet, and musician.

`sheng` and `zhen` sound good as well.

I also like `vin`, the name of the main character of the Mistborn serie but people might think I'm naming it after myself..

**Comment by RealOrangeOne** [comment]
> I also like vin

I worry people may typo this as `vim`, and get very confused why their site looks like a text editor :joy:

**Comment by Keats** [comment]
I forgot the existence of vim :( Disregard vin

**Comment by piedoom** [comment]
i like zola :) easy to type, easy to read, and gophers shouldn't have a monopoly on french writers.  kuo is nice too.  I might think more about sheng and zhen as they could be difficult to translate from spoken -> type. (e.g., "download 'zhen'! it's great" - "Okay! X-E-N, right?")

I'm not sure if you listen to the new rustacean podcast, but they recently namedropped gutenberg in their community update as well.

I would support a rename, though.  Gutenberg already has difficulty appearing in search engines with Wordpress, and since they both exist in the same domain (writing/software) it's a good idea to change it IMO.

**Comment by Keats** [comment]
> I'm not sure if you listen to the new rustacean podcast, but they recently namedropped gutenberg in their community update as well.

Thanks for the warning, I'll listen to it tomorrow!

> I would support a rename, though. Gutenberg already has difficulty appearing in search engines with Wordpress, and since they both exist in the same domain (writing/software) it's a good idea to change it IMO.

Since no one seemed to like WordPress Gutenberg, I was kinda hoping they would rebrand it :p


Added `kuo` to the main list as I like it a lot but `zola` is still my favourite so far

**Comment by piedoom** [comment]
I forgot to [include the page mentioned](https://newrustacean.com/show_notes/news/rust_1_28/index.html).  AFAIK it's fairly popular for Rust-peeps but I don't think that it should be a problem - I would just recommend opening up a PR to the show notes I listed if you end up changing the name/link :).  And Zola is my favorite as well!

**Comment by Keats** [comment]
cc people related to having gutenberg in package managers so they are in the loop:

@ilovezfs @Calinou @r15ch13 @bfontaine

**Comment by Calinou** [comment]
I like Zola, it's short but is still related to its origin (a static site generator).

**Comment by Keats** [comment]
From [reddit](https://www.reddit.com/r/rust/comments/9amiyx/whats_everyone_working_on_this_week_352018/e4x01fc/): `alois`

> Alois Senefelder invented lithography. There is no crate called "alois" and also no stuff related to static sites that I could find. Just saying.

I'm not too sure how to pronounce it though, I can think of at least 3 different ways

**Comment by Freaky** [comment]
https://en.wiktionary.org/wiki/Alois has a sample of it being pronounced.

**Comment by bdjnk** [comment]
Speaking of lithography, the name **`lith`** is short, used by no one and for nothing (that I could find), and has an unambiguous pronunciation (in English).

**Comment by Keats** [comment]
I got another suggestion in this thread email notification that is somehow not appearing in the issue:

> Speaking of lithography, the name lith is short, used by no one and for nothing (that I could find), and has an unambiguous pronunciation (in English).

Just to be clear, it would be pronounced as leet right? Not leaf? (You never know with english pronunciations...)

**Comment by bdjnk** [comment]
That was me, before I realized I'd forgotten to check the domain availability, which was one of the requirements. Regarding pronunciation, lith would rhyme with pith.

**Comment by Keats** [comment]
A `.com` is not that important and we can always do `getX` like right now. So many TLDs as well that as long as it's not something famous like [nissan.com](http://nissan.com/) we should be fine

**Comment by andrewzah** [comment]
Keeping with the movable metal type theme:
```
In 1234 the first books known to have been printed in metallic type set were published in Goryeo Dynasty Korea. They form a set of ritual books, Sangjeong Gogeum Yemun, compiled by Choe Yun-ui.  [0]

 While these books have not survived, the oldest book in the world printed in metallic movable types is Jikji, printed in Korea in 1377 [0].
```

So some possible names are:
* Yunui
* Yemun (예문 例文) Meaning: Example sentence.
* Jikji
* Gyubo (Yi Gyu-bo wrote postscript on behalf of Choi Yi which show how this book [Sangjeong Gogeum Yemun] was published with movable metal type. [2])

Using domai.nr [1], all of these have available gtlds.

[0]: https://en.wikipedia.org/wiki/Movable_type#Metal_movable_type_in_Korea
[1]: https://domainr.com/
[2]: https://en.wikipedia.org/wiki/Choe_Yun-ui

**Comment by codesections** [comment]
One additional suggestion: `zum` (from the full name of the most famous Gutenberg, "Johannes Gensfleisch zur Laden zum Gutenberg").

This has a few advantages:
  * It keeps the tie to the previous/current name
  * It's shorter/as short as any of the other names on the list
  * It has good connotations/associations:
    - In German, it means "to or for"—this fits with a static site's role in transforming content from Markdown to generated HTML
    - In Portuguese, it's an onomatopoeia for the sound something makes as it rushes by, connoting speed
    - It sounds like the English word "Zoom", also connoting speed

**Comment by codesections** [comment]
@piedoom, I heard that on New Rustacean and was pretty surprised.  I was the one who emailed him about Gutenberg, but I hadn't thought anything would come of it, so I was surprised when I heard my name while listening to the podcast!  Hope that brings some more people to the project :+1:

**Comment by j1mc** [comment]
I thought of "truss" which is a framework, typically consisting of rafters, posts, and struts, supporting a roof, bridge, or other structure.
I also like, "rustic", as a combination of 'rust' with 'static'. Rustic is defined as, "relating to the countryside; rural."
Thanks for your work, and best of luck in choosing a new project name!

**Comment by reillysiemens** [comment]
Personally I'd enjoy either `zola` or `zum` with maybe a slight preference for `zola`.

**Comment by Freaky** [comment]
@j1mc [`truss`](https://en.wikipedia.org/wiki/Truss_\(Unix\)) is taken :)

`rustic` is too like [`restic`](https://restic.net/) IMO.

**Comment by Keats** [comment]
I like zum but it would be pronounced the same way as zoom the conference
software which has an executable named zoom.

Rustic reminds me of
https://img.coopathome.ch/produkte/300_300/RGB/3081056_001.jpg?_=1505115194922

**Comment by codesections** [comment]
I was imagining "zum" as being pronounced to rhyme with "from" or "hum", but maybe that doesn't match how the name would have been pronounced?

**Comment by Keats** [comment]
Ah i was thinking more in Italian when I replied where zum would be
pronounced the same as zoom. In English I would probably pronounce it the
same as sum but with a z.
I don't pronounce from and hum the same way though so it might be a
difference of accent.

**Comment by Keats** [comment]
For `rustic` it took a non-Rust developer friend to realize it is too close to `rustc`!

Someone suggested `emile` as well which is available and is the first name of Zola. A downside is that it is a somehow common first name in French, althought the female version Emilie is way more common nowadays.

**Comment by Freaky** [comment]
`emile` should totally be reserved for some cool email-oriented project :)

**Comment by piedoom** [comment]
Emile is cool!  I like the idea but yeah, I think it possibly could be harder since it's more of a common name.  imo zola is still my favorite.

**Comment by Keats** [comment]
Looks like it is going to be `zola`!

I created https://github.com/assomoir (https://en.wikipedia.org/wiki/L%27Assommoir not much inspiration eh) for the org.

TODO list:

- [x] Rename everything in the `next` branch from Gutenberg to Zola
- [x] Get a domain name (@keats): getzola.org
- [ ] Update https://github.com/netlify/binrc to add the new zola binary and see if there is a way to make it work with previous versions after the repo move (@keats)
- [x] Update all official themes for zola (@keats)
- [x] Move repo to `getzola` org (@keats)
- [x] Update CI tokens of travis/appveyor for the new repo location (@keats)
- [x] Release 0.5.0 (@keats)
- [x] Create a snap, if snapcraft ever manages to build a Rust project (@keats)
- [x] Upload new binary to AUR (@keats)
- [x] Change the from source AUR package (@svenstaro)
- [x] Change the homebrew package (@ilovezfs)
- [x] Change the scoop package (@Calinou)
- [x] Change the void-linux package (@memchk)
- [x] Change the chocolatey package (@gsomix)

Let me know if I incorrectly tagged you.

Sadly I think the people using the built-in Gutenberg netlify support will need to update their setup.

**Comment by Freaky** [comment]
I'll hold off on submitting the [FreeBSD port](https://github.com/Freaky/ports/tree/master/www/gutenberg) until this is complete.

**Comment by paulcmal** [comment]
I'm really happy with zola, but i'd like to suggest [proudhon](https://en.wikipedia.org/wiki/Pierre-Joseph_Proudhon#Entrance_into_the_printing_trade) for the record. Also, i feel like most static site generators (hugo, nikola, gutenberg) and CLI tools generally bear names of important male persons, while pretty bots and UIs usually get meaningless female names. I don't feel so comfortable with this situation, given that many women had very influental writings, too. **Would you people be willing to reconsider the decision, focusing on finding a woman philosopher/writer to pay tribute to?**

----

Proudhon was a worker of the printing industry and became a world-famous economist and philosopher. He was the first self-proclaimed anarchist, coined the famous « Property is theft », and was already in the 19th century a cooperative economy theorist (and practitioner). As such, I'd consider his economic contributions are the basis of the free software movement.

On the downside, he was a misogynist antisemitic hence the fact most people in (inclusive) anarchist circles including myself don't really advertise him anymore. Zola on the other hand was less radical about many things, but depicted strong female characters fighting the patriarchal capitalist system, and is famous for his [J'accuse](https://en.wikipedia.org/wiki/J%27accuse) letter denouncing the systemic antisemitism plaguing French society (and the government and bourgeoisie ties with (ethno-)nationalist circles) way before the second world war.

**Comment by piedoom** [comment]
Woo!  @paulcmal I knew nothing about all that, really cool stuff :)

On a more childish note, am I the only one reading the group as Ass-oh-moire, or is that just my American brain and not a real problem?

**Comment by bdjnk** [comment]
Most Americans, including myself, will find **assomoir** difficult, not only because it starts with **ass**, which feels awkward, but also because pronunciation is a complete mystery. How is **moir** said?

**Comment by Keats** [comment]
https://www.youtube.com/watch?v=bvaUDohrODc roughly 2 seconds into the video

I didn't think about starting with *ass* to be a problem since English has many words like assembly, association, assistance etc

Keep in mind this is only the name of the org though, pretty much no one is going to notice it. Since GitHub has the same namespace for users and orgs it's a bit limited in choices. `getzola` is available though if that's better

**Comment by piedoom** [comment]
I think the words you mentioned are pronounced like uh-sembly, uh-ssociation, uh-ssistance since they're common place - the syllable break is after the first "A", instead of ass-embly, etc.  Since Assomoir is unknown to purely english speakers, we tend to try phonetics, which leads to "ass-oh-moyre".  It's really up to you, though - I just thought I might air a potential issue.   The guy in the video really makes things seem more eloquent :)

**Comment by Keats** [comment]
I renamed it to `getzola` to avoid issues.

**Comment by naturallymitchell** [comment]
Good pick with zola! :+1:

**Comment by Keats** [comment]
Looks like repo moves doesn't break links to releases (https://github.com/Keats/test-move-repo-moved) archive, which is good news!  I don't think zola will be supported straight from 0.5 on Netlify but at least gutenberg will still work.

**Comment by Keats** [comment]
I think 0.5 is ready to go but I'll leave the `next` branch there for a couple of days if people want to beta test it a bit

**Comment by gsomix** [comment]
Chocolatey package for zola, awaiting moderation

https://chocolatey.org/packages/zola/0.5.0

**Comment by Keats** [comment]
That was fast :o 
I'm still trying to figure out why the website is not working :p

**Comment by Keats** [comment]
Currently missing:

- homebrew (@ilovezfs)
- void-linux (@memchk)
- zola from src on AUR (@svenstaro)

and we're back to the previous state, except we also have snap now!

**Comment by j1mc** [comment]
FWIW, I've created a docker image for Zola. It's updated for 0.5.0, and I'll update it for subsequent releases: https://hub.docker.com/r/j1mc/docker-zola/
If you'd rather have the zola image build included as part of the zola project namespace, feel free to take from my github repo / docker hub setup. Cheers.  : )

**Comment by caemor** [comment]
I already made an issue for void-linux today: https://github.com/void-linux/void-packages/issues/4909#issuecomment-439981969 / https://github.com/void-linux/void-packages/pull/4917

**Comment by svenstaro** [comment]
Arch package is renamed.

**Comment by j1mc** [comment]
I've also submitted a pull-request for the project rename on the 'staticgen' website repo:  https://github.com/netlify/staticgen/pull/454

**Comment by Keats** [comment]
Thank you all for the updates!

**Comment by swiftcoder** [comment]
I guess this ship has sailed, but I'd argue Zola has possibly even worse SEO than Gutenberg, given that zola.com is an extremely popular website building tool for weddings...

**Comment by dixonge** [comment]
> I like zum but it would be pronounced the same way as zoom the conference software which has an executable named zoom.

Dodged a bullet on *that* one!

**Comment by dixonge** [comment]
> * Update https://github.com/netlify/binrc to add the new zola binary and see if there is a way to make it work with previous versions after the repo move (@Keats)

This was done, right?

**Comment by RealOrangeOne** [comment]
@dixonge https://github.com/netlify/binrc/pull/19
