### ISSUE TITLE
Not all `Page` fields serialized

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#38]
The [`Page` struct](https://github.com/Keats/gutenberg/blob/32e8c07272056bc9c67ced2ef7d3ae1e66b0f142/src/page.rs#L44-L87) contains lots of useful fields such as `summary` or `previous`/`next` that are not available in templates because they're [not serialized](https://github.com/Keats/gutenberg/blob/32e8c07272056bc9c67ced2ef7d3ae1e66b0f142/src/page.rs#L225-L242). Is there a reason for this or is this just an oversight?

Also, it would probably make sense to change the type of the `summary` field to `Option<String>` instead of defaulting to an empty summary.

**Comment by Keats** [comment]
That's an oversight, https://github.com/Keats/gutenberg/pull/40 should fix it. Thanks!

**Comment by phil-opp** [comment]
Thanks!
