### ISSUE TITLE
Blank lines in generated html in place of code

### ISSUE THREAD

**Issue by Ristovski** [getzola/zola#382]
Example:

```
<ul class="posts">
  {% set posts = get_section(path="posts/_index.md") %}
  {% for page in posts.pages %}
    {% if page.date %}
      <li><span class="post-meta">{{ page.date | date(format="%Y-%m-%d") }}</span><a href="{{ page.permalink }}">{{ page.title }}</a></li>
    {% endif %}
  {% endfor %}
</ul>
```

Generates the following html:

```
<ul class="posts">
  
  
    
      <li><span class="post-meta">DATE</span><a href="LINK">TITLE</a></li>
    
  
</ul>
```

At first I thought this was because the generated html kept the indentation, but this happens even without any indentation/whitespace in the template html.

Is this intended? If not, is there a way for gutenberg to fix the whitespace/blank lines?

**Comment by Freaky** [comment]
See https://tera.netlify.com/docs/templates/#whitespace-control

The newlines after each `%}` are being rendered.  You can strip them using `-%}`.

**Comment by Ristovski** [comment]
Thanks, closing!
