### ISSUE TITLE
Bug in rendering ignored shortcode with body inside code block

### ISSUE THREAD

**Issue by johansigfrids** [getzola/zola#383]
When a ignored shortcode with body is rendered inside a code block the first line inside the body of the short code gets rendered on the same line as the opening tag of the ignored shortcode. There is an example of this in the docs. It uses the following code to give an example of the use of shortcode with body:

    ```
    As someone said:
    
    {%/* quote(author="Vincent") */%}
    A quote
    {%/* end */%}
    ```

It gets rendered as

```html
<pre style="background-color:#383838">
  <span style="background-color:#383838;color:#e6e1dc;">As someone said:</span>
  <span style="background-color:#383838;color:#e6e1dc;"></span>
  <span style="background-color:#383838;color:#e6e1dc;">{% quote(author="Vincent") %}A quote</span>
  <span style="background-color:#383838;color:#e6e1dc;">{% end %}</span>
</pre>
```

Notice that `{% quote(author="Vincent") %}A quote` rendered inside the same span, even though the `A quote` part should be on its in its own span on its own line.

**Comment by Keats** [comment]
I remember seeing that bug but I don't remember why I didn't fix it. Probably some kind of whitespace being swallowed in the shortcode parser and me not thinking it was important enough to fix
