### ISSUE TITLE
Serve does not handle directory renaming

### ISSUE THREAD

**Issue by paulcmal** [getzola/zola#385]
I have my articles as folders in a `blog` folder. I wanted to rename an article to change its slug so i renamed the folder but i had no "Change detected". I took a look at the code and noticed it [skips the processing](https://github.com/Keats/gutenberg/blob/master/src/cmd/serve.rs#L251) if the affected path is a folder.

What was the initial purpose of ignoring folder changes? This could be desirable in some cases, eg. when i'm creating a new empty folder, but i don't think it's good for all cases. Should renaming be handled in a different manner? :)

**Comment by Keats** [comment]
I found this issue: https://github.com/Keats/gutenberg/issues/118

I'm guessing it's because there wasn't a full-site reload doable at that time. The main issue is that we can't really know what changed like for files so we would have to rebuild the whole thing for renames and for just creating an empty folder

**Comment by paulcmal** [comment]
> we would have to rebuild the whole thing for renames and for just creating an empty folder

As far as i could see from trying to debug this i think directory renaming brings up only two events (only one of which needs to be processed), but does not trigger an event per file inside the folder (because that's not what happens on the filesystem level from my understanding). So i'm guessing the folder upon rename event already has files within. Maybe we could indeed rebuild everything we have a rename event, but ignore empty folders? I'll try this approach :)

EDIT: After investigating a bit, it seems that `is_temp_file()` considers any path temporary when it doesn't have an extension. After addressing this, i'm now facing what seems to be that `after_content_change` doesn't handle ending up with a section change when the path doesn't end with `_index.md` (it tries to find an `index.md` in that case). I'll try to mess around a bit more :)

EDIT2: Okay so i figured `after_content_change` should only be called with the actual files so i'll try to deal with this in the notify loop

**Comment by paulcmal** [comment]
I got something to compile which handles renames more or less. However, i'm far from happy with the current state of it. First of all because I'm not very comfortable yet with the filter/map/reduce pattern (i'm learning so code is a bit verbose), but mostly because `after_content_change` (and probably others of its kind) is designed to receive a single file, i'd have to do some recursion within the notify loop to get children sections/pages rendered first in case of directory renames. ([in my hack](https://framabin.org/p/?264a0fda7e6cec4b#JUDfLC8El0sIy+Bii4oVz1nx+JP9s3IbIS25to5AGXg=) section gets rendered before children pages)

I think having `after_content_change` handle directories as well would solve this issue, if `handle_section_editing` would take an additional `render_pages` boolean to override (only if true) the value passed to `render_section` (to enable rendering of children pages). There's a lot of stress-cases when handling file changes, and i feel we'll need more unit tests to avoid breaking more things. Does that sounds like a program to you, or am i headed in the wrong direction?

A few notes on the current gutenberg implementation of `after_content_change()`:
  - content file being removed only gets removed is it's a markdown file
  - the function [unwraps](https://github.com/Keats/gutenberg/blob/master/components/rebuild/src/lib.rs#L260) the file extension directly, but it's `None` in some cases (such as a file added/modified that doesn't have an extension)  
- index should check for `_index.md` as well to match section assets

I guess there's probably similar edge cases when dealing with templates and other change kinds but i'd like your feedback on content changes first because that's what i was testing with and started looking into :)

**Comment by Keats** [comment]
I'm not entirely sure if the events differ by OS but we get a Rename(old_path, new_path) event on Linux at least. We could just reload the whole thing in that case to be honest: we don't know what would need to be changed and renaming a folder is a pretty rare thing...

**Comment by paulcmal** [comment]
> We could just reload the whole thing in that case to be honest

Sounds fair enough. However to be honest I feel like there's a lot of corner cases to handle with events. I agree garbage collection in `gutenberg serve` is less of a problem because it's not meant to be used as a long-lived process, however i don't see a reason not to implement it either.

Would you take a PR for a dedicated Server struct with a few helper methods? I've started hacking on this as a learning experience in Rust programming. It has a `dispatch_event` method that lets each path kind (content/templates/sass…) deal with different events in their own way, and returns a result of a bool to `serve` to indicate error dealing with the change, and whether the whole site should be reloaded. Also i moved path kind detection and enum to `utils/src/fs.rs` as this could be reused in other places.

The code is not that different but i've decoupled things for imo better maintainability. I'll try to polish this on a dedicated branch and let you see whether it's worth pursuing :) Also i'd be interested to see if other people can reproduce what i believe to be a notify bug, that editing the `config.toml` raises a `Remove` event on my setup ?????????

**Comment by Keats** [comment]
> I've started hacking on this as a learning experience in Rust programming. It has a dispatch_event method that lets each path kind (content/templates/sass…) deal with different events in their own way, and returns a result of a bool to serve to indicate error dealing with the change, and whether the whole site should be reloaded.

Isn't that basically the loop of the `serve` command and the `rebuild` component? To be honest I would rather make Gutenberg faster so we re-render more things in the same amount of milliseconds. There are currently a few too many `clone` in `components/site` that I didn't manage to get rid of that would make reloading everything super fast and avoid having to pick.

**Comment by Keats** [comment]
The `next` branch is much more efficient when it comes to loading the site so it should be possible to just rebuild on directory renaming

**Comment by Keats** [comment]
@paulcmal I ended up adding that in the `next` branch. Much easier now that the code has been cleaned up and rebuilds are easy to test
