### ISSUE TITLE
Image on Docker Hub

### ISSUE THREAD

**Issue by mtsr** [getzola/zola#386]
Would there be interest in having a automatically built, "official", image on Docker Hub?

I found a number of images on Docker Hub and I made my own on my private GitLab Registry, but it might be good to make one really good image for general use.

For extra points, we could do a second FROM scratch, static rust-musl-build one for the smallest image size possible.

**Comment by Keats** [comment]
It's a good idea I think but I would wait on #377 for the name first

**Comment by Keats** [comment]
> For extra points, we could do a second FROM scratch, static rust-musl-build one for the smallest image size possible.

I think `musl` will not work because of https://github.com/compass-rs/sass-rs/issues/30
If you have any experience with musl and Rust, I would love some help on that

**Comment by fbruetting** [comment]
With Gutenberg just being a build tool, I don’t think that size should be treated against stability (because of unusual build and compiler environments), as this container wouldn’t be deployed thousands of times but rather just a single time per server.

Rust for example takes 1,6 GB by default, which is pretty enormous – in contrast to spending time on shrinking a few megabytes.

**Comment by Keats** [comment]
The name has been changed now so you can go ahead if you want

**Comment by Keats** [comment]
There is one at https://hub.docker.com/r/j1mc/docker-zola/

It would be easier to collaborate on that directly, closing the issue

**Comment by fbruetting** [comment]
Is this an official one from you, or do you at least supervise that?

**Comment by caemor** [comment]
it is an inofficial one mentioned here afaik: https://github.com/getzola/zola/issues/377#issuecomment-439994701

**Comment by j1mc** [comment]
FWIW, I am the maintainer of that docker-zola repo (both on github and docker hub). I know it's unofficial, but I'll keep it up-to-date.

**Comment by j1mc** [comment]
As a note, I've pushed an update which bases the container off of Alpine Linux, reducing the container size down to 35.4mb.

**Comment by leiserfg** [comment]
https://github.com/leiserfg/docker-zola

**Comment by xneomac** [comment]
Is there any chance that this repo can be linked to an official docker image under getzola/zola ? Using the automated build available on docker hub and the dockerfile of @leiserfg, I hope you can automate the work of publishing the docker image and also keep a track of the version with docker tag.

**Comment by leiserfg** [comment]
I moved my work to the repository of @j1mc  cause it's more "famous" but I think is better to make it official.

**Comment by Keats** [comment]
What would official mean here, having the getzola/zola namespace?
I'm a bit wary about adding one more automated build system, the last one added in the repo (snapcraft) is still now working properly. Is it as simple as adding the Dockerfile and setting up the release on tag in some UI?

**Comment by leiserfg** [comment]
The dockerfile is using the version from an environment variable, so it can even use the realese tag for that.

**Comment by xneomac** [comment]
Yeah I guess having the docker under getzola/zola will make it official. 

Adding this feature should not add too much complexity to the build system because docker hub have is own automate build system (https://docs.docker.com/docker-hub/builds/) and it can be linked to a Github repository. 
Like you said it should be as easy as adding the Dockerfile and setting up the release in Docker Hub UI.

**Comment by leiserfg** [comment]
Actually I noticed that you can use the tag from github as a docker tag and dockerhub will pass that variable `DOCKER_TAG` into the docker environment so I can use that for automatic builds, so you just need to mimic my settings, and let it *hands free*

**Comment by Keats** [comment]
Can someone do a PR with the Dockerfile on the `next` branch? I'll have a look at the dockerhub setup afterwards

**Comment by leiserfg** [comment]
For sure

**Comment by Keats** [comment]
Ok balthek/zola is on dockerhub. I couldn't get the name zola and I can't seem to change the username, oh well
