### ISSUE TITLE
Slash at the end of generated image urls

### ISSUE THREAD

**Issue by faebser** [getzola/zola#388]
The urls for the generated images have a trailing slash. See https://www.getgutenberg.io/documentation/content/image-processing/ for examples.

As far as I understand 
**https://www.getgutenberg.io/documentation/content/image-processing/gutenberg.jpg/** -> refers to a folder called **gutenberg.jpg** and the browser/server will look for a index.html in that folder
and
**https://www.getgutenberg.io/documentation/content/image-processing/gutenberg.jpg** -> refers to the actual file

It seems that that the server you use (I think it's netlify) strips the trailing slashes by itself, we sadly ran into a case where we could not change the configuration of the server and were forced to fix the urls with js.

What do you think about this? Would you consider this a bug?

**Comment by Keats** [comment]
The shortcode used in the gallery doesn't use the `trailing_slash` argument for the `get_url` call.
You can specify whether you want one or not: https://www.getgutenberg.io/documentation/templates/overview/#get-url

I'm wondering whether it should be the default for `get_url` to not have trailing slash though, it causes more issues having them than not.

**Comment by faebser** [comment]
I would prefer if the shortcode would return an string without a slash at the end as the default. Maybe there is a way to detect if a slash is needed or not?

I can look into this and send you a pull request in the following days

**Comment by Keats** [comment]
>  Maybe there is a way to detect if a slash is needed or not?

The issue only arises in `get_url` global function I believe which is mostly used for assets so inverting the default should be fine

**Comment by porglezomp** [comment]
Maybe the default should be "smart," rather than true, so it adds a slash only if there's no file extension?

**Comment by Keats** [comment]
> Maybe the default should be "smart," rather than true, so it adds a slash only if there's no file extension?

`get_url` is called pretty much only for assets so I think it's safe to default to not having a trailing slash
