### ISSUE TITLE
Retrieve page from file name in template files

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#39]
I want to order my posts manually, so the default `Page::previous/next` fields don't work for me (they order by date). Instead, I want to specify the next/previous relations explicitly.

Currently, I try to use the front matter for this, e.g. `extra = {prev = "a.md", next = "c.md"}`. In the template, I then want to automatically create prev/next links with the page titles:

```html
{% if page.extra.prev %}
    {% prev = get_page(page.extra.prev) %}
    <a class="prev" href="{{ prev.path }}">&laquo; {{ prev.title }}</a>
{% endif %}
{% if page.extra.next %}
     {% next = get_page(page.extra.next) %}
    <a class="next" href="{{ next.path }}">{{ next.title }} &raquo;</a>
{% endif %}
```

So I need some working replacement for my `{% prev = get_page(page.extra.prev) %}` strawman syntax. Is this possible somehow or is there an alternative way to achieve manual page ordering?

**Comment by Keats** [comment]
I was thinking to allow ordering/paginate by weight (https://github.com/Keats/gutenberg/issues/14) or order.

Would that solve the issue?

**Comment by phil-opp** [comment]
A `get_page` function might be useful in other cases, too. But for my use case, the weight/order solution would be perfect.

**Comment by Keats** [comment]
Yeah I can see how it can be useful but Tera doesn't support global functions like that yet

**Comment by Keats** [comment]
#56 does that but cannot really be used without the `{% set ... %}` tag existing

**Comment by Keats** [comment]
Now possible on master
