### ISSUE TITLE
Taxonomies documentation incorrect.

### ISSUE THREAD

**Issue by cldershem** [getzola/zola#390]
I believe the [documentation](https://www.getgutenberg.io/documentation/getting-started/configuration/) for the new taxonomies configuration to be incorrect. The docs and the blog post both state that the format in `config.toml` should be:

```rust
taxonomies = [
    # each tag will have its own RSS feed
    {name: "tags", rss: true},
    # 5 items per page for a term, you can also customise the pagination path
    # like for the rest of the paginated content
    {name: "categories", paginate_by: 5},
    # Basic definition: no RSS or pagination
    {name: "authors"},
]
```
However, this is not valid `toml` which requires `=` instead of `:` for key/value pairs.  You can see this reflected in `gutenberg`'s own [tests](https://github.com/Keats/gutenberg/blob/742987144c0b70137fe715a3b4a4d05d01c38220/test_site/config.toml#L10):

```rust
taxonomies = [
    {name = "categories", rss = true},
]
``` 
I can send a PR if this can be confirmed by anyone else.

**Comment by Keats** [comment]
That's a bug, I'll take a PR!

**Comment by cldershem** [comment]
The 0.4.0 release blog should also get updated, https://github.com/Keats/vincentprouillet/pull/1

**Comment by kellpossible** [comment]
oh dear haha thanks for fixing this, I was scratching my head for ages trying to figure out why that example didn't work

**Comment by JeanMertz** [comment]
Related, but on a different page.

I was reading the ["rss" documentation](https://www.getgutenberg.io/documentation/templates/rss/) at getgutenberg.io, and it mentions

> Currently it is only possible to have one RSS feed for the whole site; you cannot create a RSS feed per section or taxonomy.

I had already read other parts of the documentation that mentioned creating separate RSS feeds per taxonomy, so one of the two is wrong (going by this issue, I'm assuming it's the rss documentation that's wrong).

**Comment by Keats** [comment]
Woops, forgot to update that bit thanks!
