### ISSUE TITLE
Why is it not published on crates.io?

### ISSUE THREAD

**Issue by icefoxen** [getzola/zola#392]
Sorry if this is a common question, but I couldn't find it in the issue tracker.  It seems like publishing on crates.io would make gutenberg a lot easier to install from source, since you would just have to do `cargo install gutenberg` to get the latest version.

**Comment by caemor** [comment]
See #117 and https://www.vincentprouillet.com/blog/releasing-gutenberg-0-1-0/

afaik his main reasons were:
- the inclusion of sass makes compiling a little bit more difficult
- usage of a cargo workspace with many small packages so he would need to upload many small additional packages to crates.io

**Comment by Keats** [comment]
Exactly what @Caemor said. 
Cargo now ships Cargo.lock for binaries so it would break less than before but it isn't trivial to build on Windows due to 2 C/C++ dependencies (libsass and oniguruma).

The main reason though is the use of cargo workspaces to speed up compilation and I don't want to upload/maintain ~10 crates (and increasing) for `cargo install` just to have it work. An ideal solution would be to have a way to tell Cargo to ignore workspaces when publishing and just put everything into one crate somehow.

**Comment by icefoxen** [comment]
Thank you! That makes sense. Though my bias forces me to say "you know if it was all one crate life would be simpler all around..." Multiple subcrates for compilation speed is a hack that *should* be made obsolete by incremental compilation. In a perfect world. :sigh:

C dependencies is a bit more of a mixed bag, but I can definitely sympathize with not wanting to deal with that either.

**Comment by icefoxen** [comment]
Actually I was pointed at an interesting proposal lately: https://internals.rust-lang.org/t/multiple-libraries-in-a-cargo-project/8259

**Comment by Keats** [comment]
> Multiple subcrates for compilation speed is a hack that should be made obsolete by incremental compilation. In a perfect world. :sigh:

Incremental compilation is definitely an improvement but with a somewhat old machine like mine it is still too slow. If the compiler gets fasted, I might move back subcrates as modules instead though.

For the C libraries, hopefully `syntect` will have an option to use `fancy-regex` soon (https://github.com/trishume/syntect/pull/34). That still leaves `libsass` (which also seems to prevent having a musl target for gutenberg apparently) but I have big hopes for https://github.com/kaj/rsass

**Comment by Keats** [comment]
This is not going to happen for a while so closing it.
