### ISSUE TITLE
[0.4.1] {{ get_url(path="hyde.css", trailing_slash=false) }} returns escaped string.

### ISSUE THREAD

**Issue by zoosky** [getzola/zola#393]
returns with `gutenberg build`

 `<link rel="stylesheet" href="https:&#x2F;&#x2F;gutenberg-hyde.netlify.com&#x2F;hyde.css">`.

Workaround, somehow unexpected:

```html
{% set cssurl  = get_url( path="css/main.css", trailing_slash=false)   %}

<link rel="stylesheet" href="//{{ cssurl | safe }}" />
       
```
See https://github.com/zoosky/striped/blob/master/templates/base.html

**Comment by Keats** [comment]
That's the normal behaviour of Tera, everything is escaped by default including the return values of global functions.

**Comment by zoosky** [comment]
OK. But what is the recomended way to reference resources like 

```html
<link rel="stylesheet" href="/assets/css/main.css" />
```
when it is nested in folders as in most HTML setups?

**Comment by Keats** [comment]
Roughly what you had your original post:

```j2
<link rel="stylesheet" href="{{ get_url( path="css/main.css", trailing_slash=false) | safe }}" />
```

**Comment by zoosky** [comment]
Thx!!!
