### ISSUE TITLE
If a site template or a confg.toml has an error, `gutenberg serve` exits

### ISSUE THREAD

**Issue by zoosky** [getzola/zola#394]
Expected behavior: `gutenberg serve` displays the error and continues to run.

**Comment by Keats** [comment]
That's the current behaviour. It only exits if there is an error during the initial run AFAIK

**Comment by Keats** [comment]
Did it happen after the initial run in your case?

**Comment by zoosky** [comment]
Yes. I'm trying to port a template to Gutenberg. Since there are errors, it exits after each serve:

```bash
Creating 9 pages (0 orphan), 1 sections, and processing 0 images
Error: Failed to render section ''
Reason: Failed to render 'index.html' (error happened in 'default.html').
Reason: Variable `page.content` not found in context while rendering 'index.html'
➜  gutenberg-editorial git:(master) ✗ gutenberg serve
Building site...
-> Creating 9 pages (0 orphan), 1 sections, and processing 0 images
Error: Failed to render section ''
Reason: Failed to render 'index.html' (error happened in 'default.html').
Reason: Variable `page.content` not found in context while rendering 'index.html'
```
The repo is here https://github.com/zoosky/gutenberg-editorial

**Comment by Keats** [comment]
It's normal to exit during the initial run, if there isn't at least one successful run we don't really know what content we can serve.

For your error, in `index.html` you should use `section.content`, not `page.content`
