### ISSUE TITLE
content/_index.md not displayed on home page?

### ISSUE THREAD

**Issue by devurandom** [getzola/zola#395]
From reading the [documentation on sections](https://www.getgutenberg.io/documentation/content/section/) I understand that creating `content/_index.md` should contain the root section and be displayed on the home page. However, with the Hyde template this root section is not displayed, even if I have a `section.html` template as in [my hyde-with-section fork](https://github.com/devurandom/gutenberg-hyde-with-sections). It appears that Gutenberg does not use the `section.html` template for the home page, but instead uses the plain `index.html`.

**Comment by Keats** [comment]
That is explained in https://www.getgutenberg.io/documentation/templates/pages-sections/#section-variables

The index page is a bit special and uses `index.html` instead of `section.html` like the others.

**Comment by devurandom** [comment]
Should this information be added to the documentation of sections?

**Comment by ghost** [comment]
> Should this information be added to the documentation of sections?

Should a new issue be opened regarding this?

**Comment by Keats** [comment]
It is already mentioned in https://www.getgutenberg.io/documentation/content/section/
