### ISSUE TITLE
Parse date from filename

### ISSUE THREAD

**Issue by devurandom** [getzola/zola#396]
It would be great if Gutenberg would parse the date from filenames such as `2018-09-03-slug.md` (filename starts with the date). If the front matter would also contain a `date` field, that one would override the date found in the filename.

**Comment by Keats** [comment]
That's a great idea, as long as we keep it limited to `yyyy-mm-dd` format and don't allow things like `yyyymmdd`.

That should be fairly easy to add, just check if the filename starts with `20` and try to get the date from the filename if so.

**Comment by devurandom** [comment]
I would not check for `20`, but rather just try to match the filename against `^(\d\d\d\d)-(\d\d)-(\d\d)-`. Or better yet: Just run it through the data parser (assuming it works like C's `strtol()`) and if that comes up with a anything it is a match.

**Comment by Keats** [comment]
@remexre I noticed you were usign dates as filenames for some of your content - it's probably coming for the next version

**Comment by Keats** [comment]
I pushed a first conservative version that looks for `yyyy-mm-dd{-,_}` so it will not work currently for files with ONLY dates. I'm not too sure how to make that work, should it check for the current + if the filename is only the date and use that date as slug in addition to the date in that case?
