### ISSUE TITLE
Hosting with HTTPS?

### ISSUE THREAD

**Issue by saghm** [getzola/zola#399]
Hi! I have a gutenberg instance running on a DigitalOcean droplet, and I'm looking to use a LetsEncrypt certificate with it to provide HTTPS. I've successfully obtained the certificate, but I can't find a documented way to enable HTTPS on the server that gutenberg spins up. Is this supported?

**Comment by RealOrangeOne** [comment]
The idea of the server is to be a local development server, it's not designed to actually be run in production. I suggest using it to output to a file, and setting up something like Nginx to actually serve the files.

**Comment by saghm** [comment]
Understood. Thanks!

**Comment by piedoom** [comment]
I'm sure you already considered this, but just for posterity sake (and for any other viewers) I'd like to point out that netlify offers free hosting + easy ssl through letsencrypt, so if you're just looking for a static site host and nothing else, it's a good option over a VPS.

**Comment by Keats** [comment]
As others have mentioned `gutenberg serve` is only meant for local use.
If you want to have a site on a VPS with HTTPS, the easiest way is to use [Caddy](https://caddyserver.com/)
