### ISSUE TITLE
Trigger different 'syntax highlight' behavior

### ISSUE THREAD

**Issue by ghost** [getzola/zola#402]
How difficult do you estimate it would be to implement this:

Render a block of [svgbob][1] delimited code-block into an SVG. (Using svgbob of course)

Ideally, this could also be used with other 'processors', and even be used for other syntax triggers.

[1]: https://github.com/ivanceras/svgbob/blob/master/spec.md

**Comment by Keats** [comment]
I wouldn't use code blocks for that as there is already syntax for extension: shortcodes.
All you need to have svg rendering is adding a `svgbob` filter to Gutenberg as far as I can see

**Comment by ghost** [comment]
On a tour of unusual markdown specs, I looked at [markdeep][1] which uses a `*` rectangle delimiter to put ASCII diagrams in. Being able to draw some readable diagrams directly in markdown that also render to nice SVGs using some kind of standard is quite neat. I'll try what you suggested for now thanks. Maybe this is really a feature for the markdown parser (to support 'markdeep' features for ex)?

[1]: http://casual-effects.com/markdeep/

**Comment by Keats** [comment]
I believe there are too many markdown extensions and the library we're using is only supporting [CommonMark](https://commonmark.org/). I don't think they will be open to adding unrelated extensions

**Comment by ghost** [comment]
Moved/morphed into #482
