### ISSUE TITLE
No example of embedding image without resizing

### ISSUE THREAD

**Issue by jclinton** [getzola/zola#404]
The image resizing section of the documentation is a bit advanced for someone just starting with Gutenberg. There's no example in the documentation of the straightforward image embedding:

```
![Some image](some_image.jpg)
```

It would be nice to have a small paragraph about how the alt text is used and how images larger than the content frame are handled in such a case.

**Comment by Keats** [comment]
That would be a Markdown explanation no? Not really much to do with Gutenberg

**Comment by jclinton** [comment]
Is it exclusively Markdown, though? Isn't Gutenberg handing the resource relative and absolute path handling? When is the alt text used? Is the template exclusively in control of the image width?

**Comment by Keats** [comment]
Everything related to images and path are done by Markdown.

> Is the template exclusively in control of the image width?

Yes
