### ISSUE TITLE
gutenberg parses static files

### ISSUE THREAD

**Issue by ccoors** [getzola/zola#412]
I use gutenberg 0.4.2. I have a custom theme 'cuervo' which includes MathJax for Math typesetting installed via Bower in its `static` dir. After updating to the current version of MathJax I get an error trying to build my site using gutenberg:

```
$ gutenberg build
Building site...
Failed to build the site
Error: Error parsing templates from themes
Reason: 
* Failed to parse "[...]/themes/cuervo/static/components/MathJax/test/localization.html"
   --> 266:41
    |
266 | <li>IllegalMacroParam: \( \def\mymacro#1{#2} \mymacro{x} \) </li>
    |                                         ^---
    |
    = expected some content
* Failed to parse "[...]/themes/cuervo/static/components/MathJax/test/sample-macros.html"
  --> 22:27
   |
22 |       bold: ['\\boldsymbol{#1}',1]   // this macro has one parameter
   |                           ^---
   |
   = expected some content
```

Why is gutenberg trying to parse the static files in my theme? It's supposed to just copy them to the output dir.

**Comment by Keats** [comment]
The glob loading theme templates was too generic and was looking for `.html` files but not just in the `templates` folder.
This should be fixed in the `next` branch by the commit above, please try it if you have time!

**Comment by ccoors** [comment]
Just tried it and it works :) Thanks!

**Comment by ErichDonGubler** [comment]
Should this issue be closed if the problem has been resolved?

**Comment by Keats** [comment]
it's only done in the next branch, not released yet. I'm leaving those open until release to avoid duplicates (see the `done` label)
