### ISSUE TITLE
Is there a way to make a section appear on the root path?

### ISSUE THREAD

**Issue by tshepang** [getzola/zola#413]
Say you have `content/blog/{foo,bar}.md`, and you want them to appear at `http://example.net/{foo,bar}.html`. Only way I found how do do this is modifying front matter of each page (via the `path` variable), which is rather cumbersome.

**Comment by porglezomp** [comment]
This is supported by my "transparent sections," (#408) can you try out building your site with the code from https://github.com/Keats/gutenberg/pull/411 and see if adding `transparent = true` in the blog section's `_index.md` and see that's a good solution to your problem?

I'm still trying to figure out what the best general solution, so I'd appreciate feedback if this is a good/bad solution for you.

**Comment by Keats** [comment]
>  Is there a way to make a section appear on the root path? 

> Say you hav content/blog/{foo,bar}.md, 

Do you mean pages instead of sections?

**Comment by tshepang** [comment]
I mean all pages of a section

**Comment by tshepang** [comment]
@porglezomp I tried your PR, and am failing to find a theme that lets me easily test that. What is your setup?

**Comment by porglezomp** [comment]
@tshepang I've got a site set up in https://github.com/porglezomp/www.calebjones.net/tree/gutenberg.

Using that as a theme will render anything under `content` as long as all of the sections are marked `transparent = true`, in your case probably just `content/blog/_index.md` will need that.

**Comment by tshepang** [comment]
Aah, just saw it in action. BTW, how do I use your site as a theme?

**Comment by Keats** [comment]
You can `git clone` the repo in your `themes` folder, add a `theme.toml` with a `name` field and use that theme name in your `config.toml`.
You will need to match the way posts are written though or you can just edit the bits you want to change in the `themes/THEME_NAME/templates` directory

**Comment by tshepang** [comment]
That's powerful, thank you @Keats.

**Comment by Keats** [comment]
You can use `get_section` to get a particular section from the template: https://www.getgutenberg.io/documentation/templates/overview/#get-section

This works, as long as you don't want to use pagination on it.

**Comment by Keats** [comment]
I have pushed transparent sections to the `next` branch, would be useful to get feedback.
