### ISSUE TITLE
Thumbnail urls not working on Github pages

### ISSUE THREAD

**Issue by mre** [getzola/zola#414]
I'm in the process of moving the ["Hello, Rust!" website](https://hello-rust.show) from Jekyll to Gutenberg.
Things went quite smoothly, but after I deployed the site, I get a 404 when loading the thumbnails.

I'm using the [image processing](https://www.getgutenberg.io/documentation/content/image-processing/) feature in my `index.html` template like so:

```liquid
{% set thumb = page.extra.number ~ "/thumb.jpg" %}
<img src="{{ resize_image(path=thumb, width=160, height=160, quality=100) }}" />
```

It works locally and the `src` is generated as http://127.0.0.1:1111/_processed_images/02d7ec015323740f00.jpg.

When deploying to Github pages however, I get a 404 for all thumbnails. The generated URL is https://hello-rust.show/_processed_images/02d7ec015323740f00.jpg.

I'm not sure if the URL is correct. On my other website, I use paths without the domain, e.g. `/images/hello.jpg`.

Here's what I tried:

* Check that the thumbnail names are correct
* Check that the thumbnail folder name on Github is correct
* Check that the CNAME is correct (`hello-rust.show`)
* Clear the Cloudflare Cache
* Wait
* Set the default branch of Github pages to `master`, which contains the rendered files.
* Try to retrieve the thumbnail from http://hello-rust.github.io/_processed_images/02d7ec015323740f00.jpg. I just get redirected to https://hello-rust.show/_processed_images/02d7ec015323740f00.jpg however.

Running out of ideas here. 😅 Any help appreciated.

**Comment by Keats** [comment]
Do you have the source somewhere? I can have a look tomorrow

A classic issue with github pages is assets having a trailing `/` 404 but that doesn't seem to be the case here

**Comment by mre** [comment]
Thanks. Yes, the sources are here: 

https://github.com/hello-rust/hello-rust.github.io/blob/source/themes/feather/templates/index.html

**Comment by Keats** [comment]
This works on Netlify (https://fervent-thompson-c8af43.netlify.com/) so it looks like it's a specific issue with Github as the image paths are identical except for the domain name. The usual suspect for images not showing in Github is case sensitivity but that's not the case here.

The other assets like the JS files work so I'm at a loss as well :/ My only idea is whether Github ignores folders starting with `_` because of some reasons but it would be worth asking GitHub support.

**Comment by mre** [comment]
Strange indeed. I'll try to check back with Github support on this. If I ever come up with a fix, I'll try to remember to update the issue here. Since this is not strictly Gutenberg related, I'm fine with closing the issue now. Thanks for the quick support and your investigations. 😉

As a workaround, I could simply strip the domain name from the URLs I guess.

**Comment by Keats** [comment]
You can try editing the `master` branch directly and renaming `_processed_images` to `processed_images` and replace `_processed_images` to `processed_images` in `index.html` to test the `_` hypothesis.

**Comment by mre** [comment]
Gave it a shot, but [it didn't work](https://hello-rust.show/). 🤔

**Comment by Keats** [comment]
No idea then. Let me know what they reply and whether gutenberg needs to
change something.

**Comment by mre** [comment]
I think you were onto something when you said that it could be related to the underscore and Github pages. There is a suspiciously large number of issues around that topic:
* https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
* https://stackoverflow.com/questions/6397780/names-starting-with-underscore-shows-errors-page-doesnot-exists-for-gh-pages-bra
* https://github.community/t5/GitHub-Pages/gitHub-pages-URL-404/td-p/4466

At least the folder name without the underscore should work, though. Investigating.

**Comment by mre** [comment]
As a workaround, I removed the domain name from the links for now like this:

```
<img src="{{ resize_image(path=thumb, width=160, height=160, quality=100) | replace(from='https://hello-rust.show', to='') }}" />
```

This worked, but it wasn't beautiful.

Then I tried the following: I added a `.nojekyll` file to the `public` folder, removed the branch for the rendered files (`gh-pages` for user pages, `master` for organizations) and pushed the branch again. I think this reset the "ignore" flag for files that start with an underscore as described [here](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/).

It works now. Yay!

**Comment by mre** [comment]
Oh, and of course thanks for your help @Keats. The reason why I use your projects (apart from the nice documentation) is that you care about your users and help out whenever you can. Thanks! 🌈

**Comment by Keats** [comment]
Hmm having to have a specific `.nojekyll` file sucks, I didn't think of that. I'll rename the folder in the next version so it doesn't start with an underscore to avoid issues: https://github.com/Keats/gutenberg/pull/398/commits/62b89d0c72fc3f67166fe516d47f2576f375c029

> The reason why I use your projects (apart from the nice documentation) is that you care about your users and help out whenever you can. 

Thank you!
