### ISSUE TITLE
Tables don't seem to work with markdown filters

### ISSUE THREAD

**Issue by XepherX** [getzola/zola#417]
I have defined a shortcode `dbtable`. The entirety of the file looks like such:

`{{body | safe | markdown(inline=true)}}`

my markdown looks like this:

```
{% dbtable() %}
|id|author_id|       timestamp_created|title                 |content           |  
|-:|--------:|-----------------------:|:---------------------|:-----------------|  
| 1|        1|2018-09-05 08:03:43.141Z|How to train your ORM |Badly written blog|  
| 2|        1|2018-08-22 13:11:50.050Z|How to bake a nice pie|Badly written blog|  
{% end %}
```

the generated HTML looks like this.
```
<p>
|id|author_id|       timestamp_created|title                 |content          |
<br>
|-:|--------:|-----------------------:|:---------------------|:-----------------|
<br>
| 1|        1|2018-09-05 08:03:43.141Z|How to train your ORM |Badly written blog|
<br>
| 2|        1|2018-08-22 13:11:50.050Z|How to bake a nice pie|Badly written blog|
</p>
```

![image](https://user-images.githubusercontent.com/1978472/45297373-765bed00-b505-11e8-8c1a-147e3b2b206a.png)

**Comment by XepherX** [comment]
adding `striptags` to my filters didn't work.

dbtable.html:
```
{{body | striptags | safe | markdown(inline=true)}}
```

HTML-Output is the same as above.

**Comment by Keats** [comment]
Looks like I forgot to enable markdown extensions for the `markdown` filter. Easy fix and will be done for the next release.

Any reason you are using a shortcode to render tables instead of doing it in the content directly?

**Comment by XepherX** [comment]
Hi there @Keats! thanks for the quick reply.

The main reason I'm doing tables inside a shortcode is styling. I would like to have a "title", or some sort of heading for my tables. Also, my dbtables would probably have a different styling than, say, some excel-esque spreadsheet table.

**Comment by Keats** [comment]
Should be working with the commit above, you can try by compiling the `next` branch

**Comment by XepherX** [comment]
sass-sys v0.4.7 fails to build on my system using rustc 1.30.0-nightly (2d4e34ca8 2018-09-09), but that's hardly your fault :)

just means I sadly cannot verify it right now :(

**Comment by Keats** [comment]
Ah well I do maintain sass-sys as well :)
Can you open an issue on https://github.com/compass-rs/sass-rs ? If it's on Windows, it's usually a bit tricky to compile it :/

**Comment by XepherX** [comment]
To the regret of many, I am on windows, currently :(

@Keats, I have opened an issue as requested. Thank you for your help!
