### ISSUE TITLE
Site that builds on 0.4.1 fails on 0.4.2

### ISSUE THREAD

**Issue by remexre** [getzola/zola#421]
The site in question is https://github.com/acmumn/website; we currently get:
```
Error: Failed to render page '/home/nathan/Projects/website/content/meeting-minutes/2018-09-10.md'
Reason: Failed to render 'post.html'
Reason: Macro namespace `layout` was not found in template `post.html`. Have you maybe forgotten to import it, or misspelled it?
```

**Comment by Keats** [comment]
Can you try with a build from the next branch? 0.4.2 contained a new
version of Tera that had some bugs that have been fixed since then.

**Comment by remexre** [comment]
As of `00b6aee`, I get the same error.

**Comment by Keats** [comment]
Sorry, I meant the `next` branch not `master`. I cloned your site and it works fine with it, so it should be fixed for the next release!

**Comment by remexre** [comment]
Oh, whoops, looks like I was using `next` from my fork, not from this repo. The dangers of already having a clone in my Projects directory... 😅
