### ISSUE TITLE
`ignored_content` pattern didn't work if the pattern also match file ended with .md

### ISSUE THREAD

**Issue by matematikaadit** [getzola/zola#422]
So, I have this line in the `config.toml`
```
ignored_content = [".*"]
```
Which I expect to make gutenberg ignore file that starts with dot in it's name. Since usually my editor creates such file for autosave purpose.

But it seems that if the file ended with `.md` for example, `.foo.md`, gutenberg won't ignore it.

**Comment by Keats** [comment]
`ignored_content` is checked after loading the `.md` files for finding section/page assets. I *think* is it behaving as intended

cc @PhilipDaniels who implemented it

**Comment by matematikaadit** [comment]
I believe it can be considered bug.
My case is like this:

0. I'm running `gutenberg serve`
1. Then editing file `simple.md`
2. My editor (Emacs) create the file `.#simple.md` for autobackup purpose
3. gutenberg detect new file and compile the `.#simple.md` into public.
4. I save the `simple.md` file
5. The editor deleting the backup file since it's no longer needed
6. gutenberg complaining that `.#simple.md` didn't exist and stopped further compilation

```
-> Content changed .../content/.#simple.md
Failed to build the site
Error: Failed to open '".../content/.#simple.md"'
Reason: No such file or directory (os error 2)
```

In the first place, `.#simple.md` should not be compiled since it's only a temporary file created by the editor. Hence thinking that's the case, I put `ignored_content = [".*"]` on `config.toml`

Currently, my hacky solution is by not running `gutenberg serve` if there's a file being edited. And running it if I'm sure all file that being edited already saved into the disk. Which I think defeat the purpose of `gutenberg serve` command itself.

**Comment by matematikaadit** [comment]
Tho, if it's not considered a bug. I think a way to inform the builder not to compile some autobackup file regardless it's extension is another good alternative.

**Comment by Keats** [comment]
I think a markdown file starting by `.` should never be loaded as a page in the first place, I can't think of a valid usecase for that. That would solve the issue at hand but still needs to think if it wouldn't be better to check the markdown filename against the glob of ignored content.

There is some temp file detection in `gutenberg serve` https://github.com/Keats/gutenberg/blob/master/src/cmd/serve.rs#L295-L319 but I didn't think emacs backup files would start with a `.`, I guess I need to update it?

**Comment by matematikaadit** [comment]
> I think a markdown file starting by `.` should never be loaded as a page in the first place, I can't think of a valid usecase for that.

I'm with you on this.

> [...] but I didn't think emacs backup files would start with a ., I guess I need to update it?

After researching some more, here the list of temp file created by Emacs:

- `#file#` for autosave purpose
- `file~` for backup purpose (`file.~1~`, `file.~2~`, `file.~3~`, etc for numbered backup)
- `.#file` for locking purpose

All temp file above created in the same directory as the original (unless the default setting changed).

**Comment by Keats** [comment]
I pushed 2 commits for the `next` branch: one for ignoring the `.#kind` files and another one to not look at markdown files starting with `.`.

**Comment by matematikaadit** [comment]
nice :smiley:
