### ISSUE TITLE
Add a --no-color CLI option

### ISSUE THREAD

**Issue by ianare** [getzola/zola#425]
In certain use cases the color formatting when running Gutenberg causes display problems in the terminal or for certain automated tools and processes (Jenkins, Python subprocess, awk, etc).

Please add an option to disable color output in the console (suggest the standard `--no-color`).

Thanks!

**Comment by Keats** [comment]
I'm currently using https://github.com/LukasKalbertodt/term-painter which is not maintained anymore apparently. Anyone knows another cross-platform crate for that? 

There seems to also be some activities with NO_COLOR or CLICOLOR as environment variables to control that and I seem to remember a discussion about that in Rust somewhere.

**Comment by sondr3** [comment]
https://github.com/BurntSushi/termcolor might be of interest, I came upon it while finding a library for coloring output myself too but I just needed something easy (I used [colored](https://github.com/mackwic/colored) but it doesn't support Windows).

**Comment by Keats** [comment]
Looks like `termcolor` does what we need. If anyone want to work on that, please do it on the `next` branch. It should be fairly easy as all the term coloring happens in `src/console.rs`.
Maybe we can match what `ripgrep` does as cli flag but I have no strong feeling about it, an env variable does seem cleaner to me
