### ISSUE TITLE
How to use `page.next`/`page.previous` fields?

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#43]
I still can't get the `next`/`previous` fields to work. All of the following lead to zero output:

```jinga2
{{ page.next }}
{{ page.next_in_section }}
{{ page.prev }}
{{ page.prev_in_section }}
```

The pages all have a `date` field in their front matter, e.g. `date = "2015-08-25"`. Is there something I'm doing wrong?

**Comment by Keats** [comment]
Hmm I was sure I had tests for that but no so it might be broken. Going to write some now and see why it doesn't work.

I juste realised there might some ambiguity having both `next|prev` and `(next|prev)_in_section`: if you're rendering a section, you're expecting `next` and `prev` to refer to pages in the current section, and if you're rendering the index page for example you're expecting it to be global (I think). I can't think of a moment where you're rendering a section and want to access the global prev/next that might not be in the section?

**Comment by Keats** [comment]
I think I'll do it at the same time as #14 
Curious to see your feedback on the last comment there too!

**Comment by Keats** [comment]
That should be fixed in master!

**Comment by phil-opp** [comment]
Thanks!
