### ISSUE TITLE
Markdown rendering paragraph munging

### ISSUE THREAD

**Issue by Freaky** [getzola/zola#430]
I'm a bit unclear as to the purpose of this line:

```rust
html = html.replace("<p></p>", "").replace("</p></p>", "</p>");
```

There aren't any tests covering it, it's just kind of... *there*.

Some [digging through history](https://github.com/Keats/gutenberg/commit/e662f734381a773dd4124f51444e7a61fc58c1a2) finds:

```rust
                        // TERRIBLE HORRIBLE NO GOOD VERY BAD HACK
                        Ok(s) => return Event::Html(Owned(format!("</p>{}<p>", s))),
```

This seems to have [gone away](https://github.com/Keats/gutenberg/commit/85e13483ebc0514d7f577546de96a16ae15fb222) with the new shortcode parser.

Further digging finds [this](https://github.com/Keats/gutenberg/commit/d03974270d55f153b17868a843ca7b4aed2b5464) adding the empty paragraph replacement along with some default shortcodes, but I'm still unclear where the empty paragraphs would be coming from.

I suspect the line can be removed entirely, which will save some allocation and copying.

**Comment by Keats** [comment]
I honestly can't remember. I'll remove that and try to build the docs to see if there is any differences
