### ISSUE TITLE
error[E0658]: use of unstable library feature 'fs_read_write' (see issue #46588)

### ISSUE THREAD

**Issue by MayanMisfit** [getzola/zola#432]
```

error[E0658]: use of unstable library feature 'fs_read_write' (see issue #46588)
  --> /home/digitalmisfit/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-68.2.0/build.rs:95:9
   |
95 |         fs::write(config_h, format!("
   |         ^^^^^^^^^

error: aborting due to previous error

error: Could not compile `onig_sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I'm fairly new to this so I don't know what's going on here, any help would be appreciated

**Comment by tshepang** [comment]
You have a too-old version of rustc.

**Comment by piedoom** [comment]
You can resolve that with `rustup update`

**Comment by MayanMisfit** [comment]
Hey guys, I managed to get it compiled finally, but I'm not sure if I've missed a step or something because I try to run the Gutenberg command at the terminal says the command doesn't exist.

**Comment by Keats** [comment]
I'll clarify a bit more the installation instructions. After running `cargo build --release`, the binary is available in the target/release/ folder. You need to put it somewhere in your $PATH if you want to use `gutenberg` in the terminal

**Comment by MayanMisfit** [comment]
Awesome, thanks for the help
