### ISSUE TITLE
Custom anchor links

### ISSUE THREAD

**Issue by zayenz** [getzola/zola#433]
While it is very useful to get automatic anchor links from the title, in some cases it is nice to choose anchor links that give nice URLs.

Given suitable configuraton in Hugo, a header can be annotated with `{#foobar}` to insert as an anchor. This feels quite simple when authoring content for internal linking IMHO.

**Comment by Keats** [comment]
I am not 100% against the idea but is it really worth adding some custom syntax to Markdown just for that? Generated ones work for 99% of the cases and I think adding custom Markdown syntax should have a pretty high bar of utility to quality

**Comment by zayenz** [comment]
Maybe it is just that I like to design my links, and I understand if it is a burden to add a custom extension. It is very much in the nice-to-have feature category.

**Comment by chris-morgan** [comment]
Here’s a good real-world use case for this feature: migrating from another system where you either manually specified IDs or where it automatically generated IDs with a different algorithm, and wanting to keep links working, including links to sections inside the page.

You can very roughly get around it with the likes of `<p id=…></p>` immediately above the heading, but that’s awful.

**Comment by chris-morgan** [comment]
Personally, I think that it’s more important to allow manual header ID specification than automatic: automatic heading links are just about the most fragile links in the world, because rewording breaks them, and switching CMS often breaks them. Even upgrading version may change the algorithm.

**Comment by zayenz** [comment]
I agree that migrating from another SSG to Zola was less than ideal, with most of the issues being anchor links.
