### ISSUE TITLE
Getting flat, sorted, and paginated list of all pages current section and all subsections

### ISSUE THREAD

**Issue by zayenz** [getzola/zola#435]
Perhaps this is already possible, but anyway.

Consider a blog with many sub-sections among the posts. In the front-page of the blog I would like to display all the posts in among all the subsections and the blog section in an order defined there.

```
blog
 -> posts
     -> foo
           -> a
              b
        bar
           -> c
              d
              e 
```

For `blog/posts/foo/` I might like to display all the pages in date order, and in `blog/posts/bar` I might like to display all the pages in alphabetical order, both with no pagination. For `blog` however, reverse data order with pagination might be the option I prefer. As far as I can tell, this is not possible currently?

When considering how to write the template (without regards for implementation), I think a new section variable `pages_recursive` (or similar name) that just takes all pages from the current and all subsections and orders them in the same manner as the pages in `pages` would be ordered would be great.

**Comment by Keats** [comment]
> As far as I can tell, this is not possible currently?
 
That is not possible no. https://github.com/Keats/gutenberg/issues/408 is a proposal for something a bit similar though.

Currently pagination is tied to a specific section, you say you want to paginate `foo` or `bar` or both but you can't mix them and it only affects direct descendant pages. How would you sort pages with different sorting method or would you have a `date` in your `bar` pages anyway?

Do you have a concrete example of a blog you would setup that way? I didn't consider this usecase.

**Comment by zayenz** [comment]
My idea would be that for a certain section, the sort order for the full pages list would be the order defined for that section, i.e., sorting is a property of the section, not of the individual pages. It is what I believe I would expect of the feature if I read about it.

My specific use-case is that I would like to group some pages that are part of a series of posts (say, trip reports, tutorial on topic a, recipes, and so on). For the top-level blog page a reverse-date order of all posts is relevant as a way to show what is new. The section for a certain series of post probably wants a different sorting, probably in non-reverse date order or similar. 

In addition, this would also allow grouping of related posts in a hierarchy simplifying organising and naming, even when the local section pages might not be interesting. For example, putting pages in date folders.

**Comment by zayenz** [comment]
And yes, after reading #408, this proposal would solve that use-case also.

**Comment by zayenz** [comment]
Regarding the question about pagination, I realize that the question is a bit more involved than I first thought (since it is not a feature local to the template).

Perhaps a setting that say `paginate_on` with a default value `pages` indicating what `Array` among the template variables should drive paginatation. Possible values could be `pages`, `subsections`, the new `pages_recursive`, and perhaps for consistency `subsections_recursive` (not sure abotu the use-case for the latter though).

**Comment by Keats** [comment]
You can't drive pagination from a template sadly :/
I believe the usecases you mentioned would be fixed by having the `transparent` attributes and only paginating the top one

**Comment by Keats** [comment]
I have added the `transparent` attribute to the `next` branch if you want to try before it gets released

**Comment by peterbabic** [comment]
So is it now possible to use two different `_index.md` files for one set of posts, as was OP asking?

- One for paginated posts (the default the visitor sees)
- One for all posts (a kind of index)

**Comment by Keats** [comment]
It should be possible yes but a bit hackish

**Comment by peterbabic** [comment]
@Keats any hint about how to do it, please? No matter how many `transparent` options I use, it always stops at the common denominator (root) `_index.md` that has only single possible template (either paginated or not).

**Comment by mayo** [comment]
@Keats As the previous poster asked, is there an example for this use case? I don't believe it's currently possible to paginate top level section that is `transparent`. Or rather, paginating it will yield only pages from the section itself, and not subsections, contrary to how `transparent` and iterating over `section.pages` works.

**Comment by grilledwindow** [comment]
Hello, I've been creating my own blog and ran into this problem. I'm not sure if there is a better method for this, but here's what I did:

- create taxonomy `tags`: `{ name = "tags", paginate_by = 20 }`
- in pages that need to be paginated, add `tags = ["all"]` in frontmatter
- use template `tags/single.html` for paginating. rendered page is at `/tags/all`
