### ISSUE TITLE
Move word_count & reading time to a global function?

### ISSUE THREAD

**Issue by Keats** [getzola/zola#436]
Right now, they are both generated for all pages and sections whether they are used or not.

It's not a big deal for small sites but when you start having thousands of pages, it can represent a sizable chunk of time: about 1/10th of the whole build time for a site with 10k pages.

The solution would be to create a `get_reading_analytics(text)` Tera function that takes the raw content as input and gives back a tuple/hashmap with `word_count` and `reading_time`. Since we don't serialize the raw content, we need to use the content and strip tags.

This would be a breaking change however so only for 0.5 if it happens so this is only filed as a reminder.

**Comment by RealOrangeOne** [comment]
Is there any way we could lazy evaluate this instead? It'd mean we could do it without a breaking change. Rather than a fixed property, if it's a callable, with a cache, then we could only calculate it when we actually need it. I know this is how Hugo does it behind the scenes.

(Not sure if Tera supports callables as context?)

**Comment by Keats** [comment]
> (Not sure if Tera supports callables as context?)

Only as defined global functions.

**Comment by paulcmal** [comment]
Excellent idea! What about summary and table of contents then? I guess they, too, could be run on the template side only when needed, because most pages don't need that. Both can be accomplished with the `content` variable.

Also, is there an advantage of declaring a function and not a filter?

**Comment by Keats** [comment]
summary is only ran if you have a `<!-- more -->` tag so that makes sense to do it while loading the page.

Table of content is done while rendering the markdown so it isn't slow and you need some of the data you get during parsing.

**Comment by Keats** [comment]
> Also, is there an advantage of declaring a function and not a filter?

Not really it could be a filter as well

**Comment by Keats** [comment]
Looks like it isn't THAT slow in the end so we can keep it as it for now.
