### ISSUE TITLE
Gutenberg overlooks sass-file?

### ISSUE THREAD

**Issue by senden9** [getzola/zola#439]
I am not sure if I overlook something or if I triggered a bug in Gutenberg. I try to build a site with a `main.scss` but i doesn't get get converted into a css nor I get an error. It is just not there. I use gutenberg 0.4.2.
```
$ exa --tree      
.
├── config.toml
├── content
│  ├── example.md
│  └── with-code.md
├── sass
│  └── main.scss  # <== style sheet here
├── static
├── templates
│  ├── base.html
│  ├── index.html
│  ├── page.html
│  └── section.html
└── theme.toml

$ gutenberg build && exa --tree public
Building site...
-> Creating 2 pages (0 orphan), 0 sections, and processing 0 images
Done in 72ms.  # <== No error

public  # <== but also no main.css
├── 404.html
├── example
│  └── index.html
├── index.html
├── robots.txt
├── sitemap.xml
└── with-code
   └── index.html

```

**Comment by Keats** [comment]
Do you have `compile_sass = true` in your config.toml?

**Comment by senden9** [comment]
I just need to set `compile_sass = true` in the config. At the time of filling this report i didn't had this option in my `config.toml`. Sorry for the noise. But thanks for the really quick response!
