### ISSUE TITLE
Rebuild on `config.toml` changes

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#44]
Currently one has to restart `gutenberg serve` after one changed something in the `config.toml` (e.g. the `highlight_theme`).

**Comment by Keats** [comment]
I'm not sure it's worth it, that would take the same time as restarting manually since you will need to do a full build after modifying the config. Docs with visual example would probably be a better solution imo, config is not changed often

**Comment by Keats** [comment]
I don't think I'll add that

**Comment by caemor** [comment]
I expected the same behaviour as phil-opp. Maybe it would nice to add some short comment to the config.toml file or even better a short description in the gutenberg wiki which files are getting refreshed without a restart and which not. (and sorry for bringing up this old issue :-D )

**Comment by Keats** [comment]
It does say the following when you start up `gutenberg serve`:

`Listening for changes in /home/vincent/Code/gutenberg-hyde/{content, static, templates, sass}`
