### ISSUE TITLE
Ability to use gutenberg as a crate

### ISSUE THREAD

**Issue by Moxinilian** [getzola/zola#440]
It would be an excellent feature to be able to use gutenberg as a crate to:
- Pass data generated on the fly by an outer program to the template engine's context and other environment dependent configuration
- Automate deployment processes more easily, without needing to install gutenberg in a CI/CD setup
- Have it be installed by cargo, so that contributing to a gutenberg website is easy (currently it's a bit complicated to install and setup gutenberg)

**Comment by Keats** [comment]
You can also use it as a crate as the gutenberg cli is a thin layer over ~15 subcrates. It's extremely unlikely that it will be put on crates.io though, I have no interest in having the subcrates be in crates.io

> contributing to a gutenberg website is easy (currently it's a bit complicated to install and setup gutenberg)

You can just drop the binary in the site repository if you want. I think OS package managers are also better than Cargo for that and Gutenberg is available in many of them.
