### ISSUE TITLE
Provide default templates and test post

### ISSUE THREAD

**Issue by casey** [getzola/zola#441]
Currently, `gutenberg init` doesn't provide any templates, which means that additional non-trivial work is needed to go from `gutenberg init`, to a page with posts.

I'd suggest adding very, very simple bare-bones template files and an example post, so that it works immediately out of the box. Optionally, `gutenberg init` could take a `--create-skeleton` flag, or something like that, which would produce this behavior.

In addition  to getting of the ground faster, it could provide a good starting place for theme authors by showing what's available in each template's context.

**Comment by Keats** [comment]
There is default page already telling you what file you need to create and pointing you to the right docs if you don't have any templates.
I don't want to have a default template as there are many usecases for a static site other than a blog and I don't want to focus on one specifically.

> In addition to getting of the ground faster, it could provide a good starting place for theme authors by showing what's available in each template's context.

It is unlikely you would be able to make a template showing all of https://www.getgutenberg.io/documentation/templates/pages-sections/ since some options are exclusive of each others and the docs are going to be clearer.

**Comment by casey** [comment]
> There is default page already telling you what file you need to create and pointing you to the right docs if you don't have any templates.

The instructions are non trivial, and involve a few config options. I tried to get the after dark theme working, but got errors. I assumed that I had gotten something wrong, but it turns out that they were caused by https://github.com/Keats/after-dark/issues/9.

Having a default template that is known to work would without further configuration would have prevented this.

> I don't want to have a default template as there are many use-cases for a static site other than a blog and I don't want to focus on one specifically.

All static sites will have a `page.html`. That could be included without specializing.

A generic `index.html` template could contain a directory of pages and nothing more. This would still be very useful.

> It is unlikely you would be able to make a template showing all of https://www.getgutenberg.io/documentation/templates/pages-sections/ since some options are exclusive of each others and the docs are going to be clearer.

That's certainly true. However, learning by seeing and modifying a working example is useful.
