### ISSUE TITLE
Math formula support

### ISSUE THREAD

**Issue by ghost** [getzola/zola#442]
It would be nice if Gutenberg would support math formulas, e.g. using [KaTeX](https://katex.org/).

**Comment by realcr** [comment]
I am also very interested in this feature. I currently use some kind of mathjax hack with my current Pelican setup. If no built in support for math rendering is expected, what would be the recommended way to do it?

**Comment by ghost** [comment]
I would expect KaTeX code wrapped in [Gutenberg shortcodes](https://www.getgutenberg.io/documentation/content/shortcodes/).

**Comment by piedoom** [comment]
Seems like a lot of javascript (in other words, probably better used as some clientside js since gutenberg/Zola is a single binary, doubly so since I don't want the horrors of NPM anywhere near me).   LaTeX seems like a good feature, though, I wonder if there's some more portable/rust versions?

**Comment by ghost** [comment]
Maybe Gutenberg could just generate the HTML `<script src="..." integrity="..."/>` tag to load KaTeX and wrap the raw code it finds inside `{% katex %}...{% end %}` shortcode blocks in `<script type="math/tex">...</script>` HTML elements? There exists a KaTeX [custom script type extension](https://github.com/Khan/KaTeX/tree/master/contrib/mathtex-script-type) that can deal with this kind of element.

**Comment by piedoom** [comment]
If you're using it clientside, I would just put the script in your template files since it's just a few lines.

**Comment by realcr** [comment]
To expand on what @piedoom says, I added this to the head of my `base.md` template:
```html
<!-- Math rendering -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML' async></script>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
</script>
```
It's client side and it has the cloudflare dependency, but I can live with it for now until I find a workaround. It is probably possible to get an offline version of Mathjax, and I might be able to put it at the `static` dir as a static resource.

**Comment by piedoom** [comment]
Could you download the JS file from cloudflare and include it in the static folder?

**Comment by realcr** [comment]
I'm not sure. I tried to download the file and it seemed too small (About 65kb). My guess is that this file possibly later downloads other files.
There is probably some streamlined way to build a full file. In the few minutes I was searching, I couldn't find any quick way to do that.

**Comment by devurandom** [comment]
Adding support to my fork of the "even" theme was very easy, thanks to the good documentation on [shortcodes](https://www.getgutenberg.io/documentation/content/shortcodes/#shortcodes-with-body) and [templates](https://www.getgutenberg.io/documentation/templates/overview/) and your hints and examples. Thanks!

Result: devurandom/gutenberg-even@c9ce4721c66531f183779e17a4bd56de19cccca2

**Comment by Keats** [comment]
I think pretty much all math rendering is done in JavaScript so it looks like adding the JS files in the static directory is the way to go.

Note: I have never needed to do math rendering in Markdown so not sure exactly what tools exist

**Comment by piedoom** [comment]
@realcr did you try DLing it from the releases page here?  https://github.com/Khan/KaTeX/releases . I think you need to include all of those files.

**Comment by realcr** [comment]
I will try it out. I only tried working with Mathjax before, maybe KaTex will be easier to get as a static file. Thanks!

**Comment by ghost** [comment]
Currently the "even" theme does not come with a local copy of certain JavaScript resources, either: https://github.com/Keats/even/blob/e1352ba1ed8180fc9701970eba0b520a6f81d1b5/templates/index.html#L18-L20

Thus I think it may also not be necessary to bundle KaTeX.

**Comment by piedoom** [comment]
Generally, many sites will use a CDN instead of serving their own files.  This has the benefit in that 1. a user may have already downloaded that file for another site, so using a common CDN lets them just used the cached version, 2. Since CDNs are localized, they *should* be faster in most cases.  It's definitely not necessary to bundle any JS if it is hosted elsewhere - but many people like to provide their own copies regardless so they are in complete control.  Hopefully I made some sense there!  Forgive me if I misunderstood and you know this already.

**Comment by Keats** [comment]
I think this can be closed? Unless a Rust library exists that can parse those at compile time instead of JS I don't think gutenberg can do much

**Comment by jasikpark** [comment]
Would it be possible to add support for post-processing server-side with KaTeX? or MathJax?
https://katex.org/docs/api.html

So the website would not require Javascript, though the build process now would.
