### ISSUE TITLE
Shortcodes without arguments are ignored

### ISSUE THREAD

**Issue by devurandom** [getzola/zola#444]
I tried to implement a [shortcode with body](https://www.getgutenberg.io/documentation/content/shortcodes/#shortcodes-with-body), but without an argument. I tried to call it like this:
```
{% mycode %}
...
{% end %}
```

This text will be copied literally into the output. To prevent that, I have to write is as follows:
```
{% mycode() %}
...
{% end %}

I would prefer if the first variant also worked.

**Comment by Keats** [comment]
That is mirroring the Tera syntax for macros so that is not going to change unless it changes in Tera as well
