### ISSUE TITLE
Accept non-existent templates/ directory for serve command

### ISSUE THREAD

**Issue by ghost** [getzola/zola#445]
Currently a `templates/` directory has to exist when running `gutenberg serve`, even if it is empty:
```
$ gutenberg serve
Building site...
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 93ms.

Error: Can't watch the `templates` folder. Does it exist?
Reason: entity not found
Reason: No such file or directory (os error 2)
```

It would be nice if Gutenberg would just ignore this error and instead watch the parent directory for the `templates` directory to be created.

**Comment by Keats** [comment]
We do that for static, makes sense to add it to the templates directory as well. Super easy fix in `serve.rs` if anyone wants to grab it

**Comment by devurandom** [comment]
Working on it.
