### ISSUE TITLE
subsections seem to be empty on first run

### ISSUE THREAD

**Issue by NyxCode** [getzola/zola#446]
I just wrote a template (used as both `index.html` and `section.html`) which should display the content of sub-sections:

```
{% for section in section.subsections %}
        {%- if section.subsections -%}
            {% if section.pages %}
                {{ section.pages | length }} Pages, {{section.subsections | length}} Sections
            {% else %}
                {{ section.subsections | length }} Sections
            {% endif %}
        {%- elif section.pages -%}
            {{ section.pages | length }} Pages
        {%- else -%}
            Empty
        {% endif %}
{% endfor %}
```

My current directory structure looks like this:
```
content/
   section1/
        section2/
        page1.md
```
When I open the root of the page in a browser, I would expect to see that `section1` contains 1 page and 1 sub-section. Strangely, this is not what happens. Gutenberg doesn't seem to recognize the sub-section `section2` until a random change is made in the template (a newline somewhere in the file will do) and the files are re-compiled. When that happens, the page correctly displays the content of the section.

I have absolutely no idea why this is happening and, since I'm new to Gutenberg, how to track the issue down. So any help would be appreciated!

#### To reproduce:
`git clone https://github.com/NyxCode/hyde`
`cd hyde`
`git checkout sub-sections`
`gutenberg serve`
`# go to localhost:1111 - you should see "1 Pages" below "some-section"`
`# now, add a newline in `templates/section.html` between line 72 and 73 to trigger a re-build`
`# refresh the page - you should see "1 Pages, 1 Sections" now`

Again, I'm sorry I haven't got the knowledge to find the cause of this bug.

**Comment by Keats** [comment]
That's an interesting bug! Not sure what is happening, maybe a bit of https://github.com/Keats/tera/issues/342 but that doesn't explain everything

**Comment by NyxCode** [comment]
I don't know if this has something to do with the issue, but it seems a bit strange to me how `Site` stores sections. When having this directory structure:

```
content/
   outer/
       inner/
```
`Site.sections` contains these 3 key/value pairs after running `create_new_site`:

```
/content/_index.md  =>  Section(path = /, subsections = [Section(path = outer/, subsections = [])])
```

```
/content/outer/_index.md  =>  Section(path = outer, subsections = [Section(path = outer/inner/, subsections = [])])
```

```
/content/outer/inner/_index.md  =>  Section(path = outer/inner/, subsections = [])  
```

**Comment by Keats** [comment]
What is weird about that?

**Comment by NyxCode** [comment]
Again, I may be wrong here, but I would have expected a tree-like structure, something like this:
```
 /content/_index.md  => Section(
    path = /, 
    subsections = [
        Section(
            path = outer/, 
            subsections = [
                Section(
                    path = outer/inner/, 
                    subsections=[]
                ) 
            ]
        )
    ]
)

...
```

**Comment by NyxCode** [comment]
Look, these are the 3 value/key pairs from `Site.sections` after running `after_template_change`:
```
content/_index.md => Section(
    path = /, 
    subsections = [
        Section(
            path = some-section/, 
            subsections = [
                Section(
                    path = some-section/another-section/, 
                    subsections = []
                )
            ]
        )
    ]
),
content/some-section/_index.md => Section(
    path = some_section/, 
    subsections = [
        Section(
            path = some-section/another-section/, 
            subsections = []
        )
    ]
),
content/some-section/another-section/_index.m => Section(
    path = some-section/another-section/, 
    subsections = []
)
```

**Comment by NyxCode** [comment]
There is a bug somewhere in the `populate_sections` function which causes it to only do what it's supposed to after invoking it twice. It's somewhere in here:
```
        for page in self.pages.values() {
            let parent_section_path = page.file.parent.join("_index.md");
            if self.sections.contains_key(&parent_section_path) {
                // TODO: use references instead of cloning to avoid having to call populate_section on
                // content change
                self.sections.get_mut(&parent_section_path).unwrap().pages.push(page.clone());
            }
        }

        self.sort_sections_pages(None);
        // TODO: remove this clone
        let sections = self.sections.clone();

        for section in self.sections.values_mut() {
            if let Some(paths) = grandparent_paths.get(&section.file.parent) {
                section.subsections = paths
                    .iter()
                    .map(|p| sections[p].clone())
                    .collect::<Vec<_>>();
                section.subsections
                    .sort_by(|a, b| a.meta.weight.cmp(&b.meta.weight));
            }
        }
```

**Comment by NyxCode** [comment]
I got it :tada:, it was so obvious though :slightly_smiling_face: 
Took me far too long

**Comment by Keats** [comment]
@NyxCode see #480 which would allow that and more with no performance issues

**Comment by jwatt** [comment]
> Again, I may be wrong here, but I would have expected a tree-like structure, something like this:

Hmm, yes, that would be my expectation too, and seems like more desirable behavior. Is the reason for the flat list because writing recursing code [to arbitrary depth] is not possible with templates?

**Comment by jwatt** [comment]
According to the [Tera Macros](https://tera.netlify.com/docs/templates/#macros) docs template macros are a thing and recursion is supported.

**Comment by Keats** [comment]
> Hmm, yes, that would be my expectation too, and seems like more desirable behavior.

What does a tree gets us over a flat layout? I am not seeing a specific advantage to it.

**Comment by Keats** [comment]
See #484 for a solution to that issue. The approach is different as it now only stores ids to the subsections and therefore shouldn't have issues with nesting.

**Comment by Keats** [comment]
This is fixed in the `next` branch

**Comment by NyxCode** [comment]
:tada: :balloon: great work!

![my usecase](https://i.imgur.com/73G5bJV.png)
