### ISSUE TITLE
Default config values in themes

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#448]
Not sure if this is a bug or not, but I'm wondering how this is supposed to work. 

Say I have a theme.toml file:

```toml
[extra]
my_var = "hello world"
```

and then an HTML theme template file:

```html
<p>{{ config.extra.my_var }}</p>
```

I would expect the theme.toml file to conain default values:

```
<p>hello world</p>
```

However, I get a panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("Failed to render section \'C:/Users\\doomy\\Documents\\code\\web\\themes\\newsletter\\content\\_index.md\'"), State { next_error: Some(Error(Tera(Msg("Failed to render \'index.html\'")), State { next_error: Some(Error(Msg("Variable `config.extra.my_var` not found in context while rendering \'index.html\'"), State { next_error: None,
backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

this issue is only resolved when I provide the values in my theme.toml *and* config.toml files.

config.toml **and** theme.toml
```
[extra]
my_var = "hello world"
```

**Comment by Keats** [comment]
Well the panic is definitely a bug.
I vaguely remember not merging `extra` I think but I could be wrong. It should work in my mind though so that's another bug.

**Comment by NyxCode** [comment]
Yes, `[extra]` is not being merged when having a `config.toml` and `theme.toml` in the same project

**Comment by piedoom** [comment]
yall are awesome!  Will close (the standard is to close when merged into a release, right?)

**Comment by Keats** [comment]
Hm sorry I think I misread after looking at the PR. If you are working on a theme, `config.toml` and `theme.toml` are separate things and I don't want to add some logic to merge them, the theme should still work if I delete `theme.toml` as a normal gutenberg site.

@piedoom can you reproduce easily the panic?

**Comment by NyxCode** [comment]
@Keats
If you delete `theme.toml` the site still works. 
  
If you are creating a theme (which is a normal site too) it's implicitly using itself as theme (even though there is no theme set in the config.toml). That means though that the default configuration in `theme.toml` is not used.

**Comment by Keats** [comment]
> If you delete theme.toml the site still works.

How would it work if the default data is only in `theme.toml` when you're developing a theme? For example in your PR we would have needed  to add the same bit of code in the `build` command afaik.
I'm reluctant to add special behaviour if there is a theme.toml file in the directory tbh

**Comment by Keats** [comment]
@piedoom can you run it with `RUST_BACKTRACE=1` on to see the backtrace of the panic? Are you using the next branch or a gutenberg from a package management?

**Comment by NyxCode** [comment]
> How would it work if the default data is only in `theme.toml` when you're developing a theme?

I don't understand. The defaults from `theme.toml` would be merged with the settings from `config.toml` and everything would be fine.

>  For example in your PR we would have needed to add the same bit of code in the build command afaik.

Right, completely forgot about that. The logic should go in `Site::new`. But it's not that crucial I guess.. Even though I agree with piedoom that the behavior is unexpected.

**Comment by piedoom** [comment]
> How would it work if the default data is only in theme.toml when you're developing a theme?

I thought this was intended behavior?  When developing themes I provide a lot of different options for more granular control, and having to redefine all of them in a `config.toml` seems redundant.  I might be wrong, but I thought this is how themes used to work.

**Comment by Keats** [comment]
Ok maybe there's some confusion on my end. 
The PR was making it so running `gutenberg serve` in a theme directory would automatically merge the data from `theme.toml` into `config.toml`.
Right now, merging only happens when `config.toml` has a `theme` variable.

Is the goal to merge it automatically as well when developing a theme?

Unrelated: @piedoom any chance you can replicate that panic?

**Comment by NyxCode** [comment]
@Keats yes

**Comment by Keats** [comment]
I got it incorrectly then! I think it would be fine to add

**Comment by Keats** [comment]
If one of you has the time to do a PR (for both serve and build), I'll take it.

Another ping to @piedoom for the panic since a release is coming very soon and would like to fix that

**Comment by piedoom** [comment]
Apologies on that, I'll get a MWE to you later today on the panic.

**Comment by piedoom** [comment]
For whatever reason I'm having difficulty reproducing the panic.  I've tried multiple versions of Gutenberg, but it seems to be giving me the correct error now instead of panicking (though I believe this issue was on 0.4.1 as defined in my theme.toml, though I don't see how 0.4.2 would change anything).  I may have been using a Linux box at the time?  I'm not sure.  I'll go into some more depth when I have access to that computer, as Mac and Windows are fine so far.

**Comment by Keats** [comment]
Maybe it got fixed then since the original testcase sounds like it should error only and not panic. Thanks for checking

**Comment by piedoom** [comment]
Closing as I can't reproduce so hopefully everything is good and fixed
