### ISSUE TITLE
Cannot install multiple themes

### ISSUE THREAD

**Issue by fbruetting** [getzola/zola#460]
```
v0.4.2
```

I pulled `book` and `after-dark` into the themes folder.

* When I set `theme = book` in `config.toml`, I get:
```
Building site...
Error: Template `after-dark/templates/index.html` loads macros from `book/templates/post_macros.html` which isn't present in Tera
```

* When I set `theme = after-dark`, I **sometimes** get:
```
Building site...
-> Creating 1 pages (0 orphan), 1 sections, and processing 0 images
Error: Failed to render page '/var/home/frank/Projekte/BB-Music-Webseite/BB-Music/content/Bilder/beispiel.md'
Reason: Failed to render 'after-dark/templates/page.html': error while rendering macro `post_macros::meta`
Reason: Filter `date` received an incorrect type for arg `value`: got `Null` but expected i64|u64|String
```

When I delete the respective other theme, both variants work. The last variant seems to depend on the previous history (which actions I did before and which content the files had before), as it sometimes works and sometimes not. So this seems to build upon a previous state, instead of everything being redone in a clean way…?

**Comment by Keats** [comment]
It should already be fixed in the `next` branch I believe.

**Comment by fbruetting** [comment]
Is this branch usable or more like in an alpha state?

**Comment by piedoom** [comment]
the next branch is every commit that will be merged upon a new release so it should be fine to use iirc
