### ISSUE TITLE
Markdown italics not working properly

### ISSUE THREAD

**Issue by andradei** [getzola/zola#461]
I'm writing in a `content/some_page.md` and 80% of the uses of `_` to italicize text result in the literal `_` character being printed. The other 20% it is italicizing two blocks into one, something like:

\_text\_ and some more \_text_

becoming:

_text and some more text_

instead of:

_text_ and some more _text_

I'm rendering the markdown text with:

`{{ page.content | safe | markdown(inline=true) }}`

**Comment by Keats** [comment]
That sounds like an upstream issue for https://github.com/raphlinus/pulldown-cmark
Might be the same root issue as https://github.com/raphlinus/pulldown-cmark/issues/146

**Comment by andradei** [comment]
Let's hope that gets fixed soon.
