### ISSUE TITLE
Newlines entirely chomped in shortcodes with multi-line bodies

### ISSUE THREAD

**Issue by pkgw** [getzola/zola#462]
Consider a shortcode invocation like this:

```
{% myshortcode() %}
Here is
some text
{% end %}
```

I would expect the `{{ body }}` of this shortcode to be `Here is some text`. But right now, it seems that Gutenberg *entirely* chomps the newline, such that the body become `Here issome text`. Perhaps there's a justification for this, but in my opinion, at least, the current behavior is undesirable.

I looked into the relevant code and I couldn't figure out where exactly the problem was. However, I can say the following test case can be appended to `components/rendering/src/shortcode.rs` to demonstrate the problem:

```rust
    #[test]
    fn can_render_multiline_shortcode_body() {
        let mut tera = Tera::default();
        tera.add_raw_template("shortcodes/youtube.html", "{{body}}").unwrap();
        let res = render_shortcodes("{% youtube() %}First\nSecond{% end %}", &tera);
        assert_eq!(res, "First Second");
    }
```

**Comment by Keats** [comment]
> I would expect the {{ body }} of this shortcode to be Here is some text

I'm guessing Github is eating the newline character?
It is definitely a bug, thanks for reporting it!

**Comment by pkgw** [comment]
Apologies, I was sloppy about internal newlines at the beginning and the end there.

I also noticed that the same thing seems to happen if I have a shortcode that invokes the Tera `include` directive — the included template seems to get processed and squashed onto one line, with the same sort of loss of whitespace between lines.

**Edit**: Or even if the shortcode template just contains plain text. If the content of the shortcode template HTML file is

```
Some
text
```

Its expansion in a page seems to become `Sometext`.

**Comment by Keats** [comment]
Looks like the shortcode parse is eating all the newlines, shouldn't be too hard to fix

**Comment by Keats** [comment]
Fixed in the commit above, turns out it was doing that intentionally but I can't really remember the issue even with the comment/git log

**Comment by pkgw** [comment]
Thanks! Shall I close this issue or do you not want to do that just yet? (Waiting until the fix makes it into a release?)

**Comment by Keats** [comment]
Leave it open to avoid duplicate issues until release, thanks!
