### ISSUE TITLE
Unsupported syntax highlighting languages: F♯ and ReasonML

### ISSUE THREAD

**Issue by chriskrycho** [getzola/zola#467]
I'm about to start building a new version of my website, and I have an ongoing series *now* and may also in the future which involves Rust, Elm, F♯, and ReasonML. As such, it'd be great to have syntax highlighting for F♯ and ReasonML!

I'll happily just use the `extra_syntaxes` option in the meantime, of course.

**Comment by Keats** [comment]
Did you find good syntaxes for those? I had a look and they all seem to be a couple of years old

**Comment by chriskrycho** [comment]
I started looking around for a ReasonML one, and the [tmLanguage](https://github.com/reasonml-editor/sublime-reason/blob/master/Reason.tmLanguage) that ships with the Sublime package and the [JSON grammar](https://github.com/reasonml-editor/language-reason/blob/master/grammars/reason.json) used by Atom and VS Code are it. Looks like the *best* option (which I'm not asking you to do, to be clear!) would probably be writing a new `.sublime-syntax` and upstreaming it to the Reason package.

I haven't had a chance to poke at F♯ syntaxes yet. Will report back with more details on what I find once I have.

**Comment by Keats** [comment]
I found the same tmLanguage for ReasonML but I thought it was not up to date as I believed the language was changing a lot and the last commit was a year ago but it looks like the JSON grammar is the same. Sublime can automatically convert tmLanguage to `.sublime-syntax` so that should be easy

For F#, that might be trickier indeed I don't think many people use Sublime for it!

**Comment by Keats** [comment]
Reason syntax highlighting added to the `next` branch

**Comment by chriskrycho** [comment]
1. Awesome re: Reason!
2. It looks like the most up-to-date syntax-highlighting grammar for F♯ is probably [the ones from the Ionide project](https://github.com/ionide/ionide-fsgrammar/blob/master/grammar/fsharp.json). I'll poke around a bit and see if I can get it/them converted to a `.sublime-syntax`.
