### ISSUE TITLE
Docs: how to do "all" for RSS feed?

### ISSUE THREAD

**Issue by chriskrycho** [getzola/zola#468]
Reading the docs, the only info I see on setting number of items to include in the RSS feed is:

```toml
# The number of articles to include in the RSS feed
rss_limit = 20
```

In my case, I prefer never to truncate. Should the value be set to blank (null), 0, -1, an absurdly large number I'll never hit…?

(I'm happy to open a docs PR to clarify this.)

**Comment by Keats** [comment]
Right now it's absurdly large number. If it isn't set explicitely in the config.toml, it defaults to 10000 so the docs are actually incorrect!
I will take a PR for fixing the docs :+1:

**Comment by chriskrycho** [comment]
Thanks!

**Comment by chriskrycho** [comment]
FWIW, I'd also be happy to submit a PR for handling it with an `Option<u32>` or whatever it should be here if you point me to the right spot in the code!

**Comment by Keats** [comment]
It is already working: https://github.com/Keats/gutenberg/blob/next/components/config/src/lib.rs#L64-L90

**Comment by chriskrycho** [comment]
Right, sorry. What I meant was: we could update that to be `Option<usize>` and return all entries in the case the value is `None` or the specified limit if it's `Some(usize)`, I'd be happy to update it to support that.

If you *don't* want that, I'll just update the docs, but If figured that'd be the more robust solution.
