### ISSUE TITLE
The "Shortcode with body" example in the docs doesn't work

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#469]
The [Shortcodes with body](https://www.getgutenberg.io/documentation/content/shortcodes/#shortcodes-with-body) example in the docs does not work. It seems that the body must be on a new line, otherwise gutenberg does not recognize the shortcode reference. Specifically, it only works if I change:

    {% quote(author="Vincent") %}A quote
    {% end %}

to:

    {% quote(author="Vincent") %}
    A quote
    {% end %}

It's worth noting that the following (inserting non-line breaking white space between the "}" and "A quote" does **NOT** work either (the body must start on a new line):

    {% quote(author="Vincent") %} A quote
    {% end %}

I'm guessing that this is a bug in the shortcode handling, but if this is expected behavior then at the very least it's a bug in the docs where the example should be changed and the fact that the body needs to be on a new line flagged clearly.

One other thing to note is that the shortcode tests in the repo only seem to test shortcode-without-body type shortcodes.

**Comment by Keats** [comment]
It should work even on a single line so that's definitely a bug. Should be easy enough to fix if anyone wants to try!

**Comment by jwatt** [comment]
I think I've figured out what's wrong. I'll put up a pull request a bit later.

**Comment by jwatt** [comment]
Ugh. Turns out the gutenberg build that I was creating when rebuilding wasn't the one my script was installing (release/debug confusion). So this particular issue seems to be an old bug that is fixed in current master.

That said!...

The references to `sc_body_start` and `ignored_sc_body_start` at the following line seems wrong:

https://github.com/Keats/gutenberg/blob/b12075486272/components/rendering/src/content.pest#L61

I believe that that line should be referencing `shortcode_with_body` and `ignored_shortcode_with_body` instead.

I also don't understand why there is a reference to `Rule::text_in_ignored_body_sc` and `Rule::text_in_body_sc` here:

https://github.com/Keats/gutenberg/blob/e0291cec654f/components/rendering/src/shortcode.rs#L138

I think that line should just match `Rule::text`.

Or am I misunderstanding the code, Vincent?

**Comment by Keats** [comment]
That first one looks like a potential issue yes.
Not entirely sure about the second one, from a quick look they do seem needed

**Comment by Keats** [comment]
Can this be closed @jwatt ?

**Comment by jwatt** [comment]
For the second one, it seemed that `p` at that point could only be one of the five top level types that will be output by pest: text, or one of the four shortcode types. So I didn't understand (and meant to look into) why you thought `Rule::text_in_ignored_body_sc` and `Rule::text_in_body_sc` were needed there first.

**Comment by Keats** [comment]
> So I didn't understand (and meant to look into) why you thought Rule::text_in_ignored_body_sc and Rule::text_in_body_sc were needed there first.

I have no idea. My best guess is I wrote some tests, wrote the grammar and tweaked it until it passed the tests

**Comment by jwatt** [comment]
Nothing fails for me running `cargo test` and it is confusing to have those rules there since it looks like they can never be matched. I'll put up a PR and you can decide if you want to accept it or not. :)

**Comment by jwatt** [comment]
> Can this be closed @jwatt ?

With #489 landed everything I brought up here has been addressed. Thank you!
