### ISSUE TITLE
Rendering of shortcodes with underscores in their names is broken

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#470]
The [Using shortcodes](https://www.getgutenberg.io/documentation/content/shortcodes/#using-shortcodes) section in the docs says:

> Lastly, a shortcode name (and thus the corresponding .html file) as well as the arguments name can only contain numbers, letters and underscores, or in Regex terms the following: [0-9A-Za-z_].

Taking the 'quote' shortcode example from that page, putting the body on a new line to work around issues #469, and then renaming the shortcode to "quote_a_human", I then get the output:

    As someone said:
    
    {% quote_a
    
    A quote
    -- Vincent 

This is a bit weird because the shortcode does work...it just also outputs some of the shortcode markup itself, up to and including the last underscore in the shortcode name, into the rendering.

Furthermore, if I insert a line break into the shortcode reference as so:

    {% quote_a_human(
        author="Vincent") %}
    A quote
    {% end %}

Then the output becomes:

    As someone said:
    
    {% quote_a_human(
    
    A quote
    -- Vincent 

(I'd like to be able to put line breaks in because in the actual shortcode I'm writing there are several arguments to the shortcode with long values, and it makes the shortcode reference in the markdown file easier to read.)

**Comment by Keats** [comment]
Looks like the shortcode parser still has lots of bugs :(

**Comment by jwatt** [comment]
Bah. See [issues 469](https://github.com/Keats/gutenberg/issues/469#issuecomment-428193865). Turns out the gutenberg build that I was creating when rebuilding wasn't the one my script was installing (release/debug confusion). So this particular issue seems to be an old bug that is fixed in current master.

Appologies for wasting your time.
