### ISSUE TITLE
Treating the body of a shortcode as markdown content

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#473]
It seems like when the `body` of a shortcode is referenced using `{{ body }}` that it is treated as HTML. I'd like to treat it as markdown, so I tried referencing it using `{{ body | markdown }}`. That sorta works, but is mostly broken. For example:

    {% myshortcode() %}
    <https://github.com>
    
        This should be a
        multi-line "code" block
    {% end %}

I would expect that to become:

--
[\<https://github.com>](https://github.com)

    This should be a
    multi-line "code" block
--

But instead it becomes:

--
\<https\://github.com>

    This should be amulti-line &quot;code&quot; block
--

That is, the [automatic linking](https://daringfireball.net/projects/markdown/syntax#autolink) is not working, multi-line code blocks are wrapped to a single line, and certain characters in the multi-line code blocks are over-escaped.

**Comment by Keats** [comment]
Try to do `{{ body | safe | markdown }}`, it's probably trying to render escaped markdown

**Comment by Keats** [comment]
Keep in mind the shortcode bodies were a bit broken as well until a commit on `next` a few minutes ago

**Comment by jwatt** [comment]
Using the `safe` filter fixes all the issues except for the code block thing.

I did actually find and modify the same line that you modified in 7ecdc47b9173, but I just removed the `.map(|s| s.trim_left())` (leaving `Ok(res.lines().collect())`) which didn't fix the bug with the code block being wrapped to one line. I suppose the output from `lines()` doesn't include line break characters as  I assumed (and `collect()` doesn't reinsert them). At any rate it's working now, and TIL. Thank you!

**Comment by jwatt** [comment]
Except I think that I know what you were trying to say in the comment that documented the code that you removed in 7ecdc47. The issue is with markup in the definition of shortcodes (it's not an issue with the body where the shortcodes are referenced). Consider a shortcode file containing:

    <div>
      {# If the following p is indented to 4 spaces it becomes a code block! #}
      <p>My para</p>
    </div>

However, perhaps the only reasonable way to handle that is to clearly flag in the shortcode documentation that shortcode files are also treated as markdown and therefore indentation matters.

**Comment by jwatt** [comment]
Hmm, strange. If I remove the {# ... #} comment from the shortcode file then the indentation of the `<p>` no longer seems to matter...

**Comment by jwatt** [comment]
Vincent, what do you think about the above? Does a separate issues need to be filed?

**Comment by Keats** [comment]
The documentation already mentions that you should wrap in a `div` to avoid some issues.
No clue what is happening with the indentation of the `p`... it looks like the adding tons of tests for shortcodes and rendering would be worthwile

**Comment by jwatt** [comment]
Okay, it sounds like there should be an issue for this then. I've filed #479 

I guess this can be closed again.

**Comment by oovm** [comment]
Sorry, I still don't understand this:

### Shortcode

```html
<blockquote {% if type %} class="fancyquote {{type}}"{% else %} class="fancyquote info" {% endif %}>
    {{ body | safe | trim | markdown }}
</blockquote>
```

### Markdown

```markdown
{% quote(type = "danger") %}

## Danger

This is a **danger** message!

{% end %}
```

### Output

```html
<blockquote class="fancyquote danger">
    &lt;h2&gt;Danger&lt;/h2&gt;
&lt;p&gt;This is a &lt;strong&gt;danger&lt;/strong&gt; message!&lt;/p&gt;
</blockquote>
```

Why I've got only strings

![image](https://user-images.githubusercontent.com/17541209/74584183-5f7acd80-500a-11ea-84fb-6d35e99835de.png)

**Comment by Keats** [comment]
Put safe at the end of the filter chain
