### ISSUE TITLE
Integrate rustfmt?

### ISSUE THREAD

**Issue by chriskrycho** [getzola/zola#475]
I have the RLS running in VS Code, so it wants to auto-format on save. I worked around that by doing a save-without-formatting, and can definitely continue doing that… but I will say that rustfmt is *great*. Obviously your call on the project, so no hard feelings if you opt not to.

**Comment by Keats** [comment]
That's the plan before the next version release, to avoid breaking PRs. The config file will be the same as https://github.com/Keats/tera/blob/master/rustfmt.toml

**Comment by chriskrycho** [comment]
Excellent!
