### ISSUE TITLE
Issues with iterating over grandchild content

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#478]
I haven't tested this myself, but just reporting this so it's on file:

@fvsch in the blog post [About static site generators](https://fvsch.com/static-site-generators/) claims that:

> [gutenberg allows] listing a page’s children or “resources”, but [has] bugs when dealing with more than one level

**Comment by fvsch** [comment]
I don’t have my test code around anymore, sadly, but I think it was something similar to:
https://github.com/Keats/gutenberg/issues/446

Though I'm not sure it was a "first run" thing, I think I never managed to get grandchild content. With two nested loops in a template, I could list grandchildren and get their URL maybe, but couldn't access their content or metadata.

**Comment by Keats** [comment]
> I think I never managed to get grandchild content.

Yeah that's the same as #446 (with a PR in #451). 

The main issue with that is that Tera converts the data to JSON so if the index page will need to serialise every single page/section of the site (or more if you something like https://github.com/Keats/gutenberg/pull/411 is merged) even if they are not used at all in the template. Serialization is already the bottleneck of gutenberg. Part of me is thinking that it is nice to have it all filled automatically but the other part thinks it would be better to have `subsections` be a list of indices and let people call `get_section(path=path)` if they need to.

I don't believe it will be possible to do lazy loading with Tera (but would be very happy to be proven wrong). Another route could be https://github.com/Keats/tera/issues/340 but I don't really see how that would look like.

**Comment by Keats** [comment]
I opened https://github.com/Keats/gutenberg/issues/480 for that second part of me to think about it

**Comment by Keats** [comment]
@fvsch I liked the article!
I agree that for most people, a CMS web interface will be better. There is https://forestry.io/ for example but it was pretty terrible the last time I checked. A friend also runs https://www.pulsecms.com/ which is nice.

For your points specifically:

1. Agreed
2. Agreed as well for rebuild, not for initial build. It doesn't scale to more than a few pages, you don't want a 5k lines dump/5k notifications when building a bite site.
3. i'm not entirely sure what you mean by that?
4. Agreed
5. Haven't found anything better than having a front matter :/
6. Agreed despite Gutenberg having one :p I never use themes myself but it's by far the number 1 request you get when people start using a new SSG. Either you build one and get users or you don't and you get very few. Most people want to focus on the content and not deal with the UI.

How did you find Gutenberg other than the nested subsections issue?

**Comment by jwatt** [comment]
> @fvsch I liked the article!
>     2. Agreed as well for rebuild, not for initial build. It doesn't scale to more than a few pages, you don't want a 5k lines dump/5k notifications when building a bite site.

I agree this probably isn't a good default, but having a --verbose flag that outputs that info seems reasonable and a widely understood mechanism for getting more info like that.

>     3. i'm not entirely sure what you mean by that?

Part of this point seems to be in reference to the earlier complaint that "you have to write some configuration code that populates “Collections” ahead of build time". I don't think Gutenberg does that though.

>     4. Agreed

Glad to hear that. ;-)

**Comment by fvsch** [comment]
> 2. Agreed as well for rebuild, not for initial build. It doesn't scale to more than a few pages, you don't want a 5k lines dump/5k notifications when building a bite site.

That's why I suggested using a graphical UI for that, maybe inspired by what Fractal does. It's probably not a good match for Gutenberg and other tools that don't want to invest in that kind of UI.
I think a few command-line tools have a debug command where you can ask:

```sh
$ some-builder info path/to/content/file.md
```
to show the final metadata (when there are metadata overrides), template used (when there is a template inheritance or lookup system), URL, output path or reason why a file is not picked up or transformed.

**Comment by Keats** [comment]
The nested issue is fixed in the `next` branch
