### ISSUE TITLE
Template expressions/statements/comments in shortcode files can break surrounding markdown

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#479]
As noted in the following tera template comment, gutenberg's understanding of the indentation can go wrong despite the content of the shortcode being wrapped in a `<div>` with no indentation.

    <div>
        {# This comment causes the following line to become a code block! #}
        <p>Paragraph indented by four spaces</p>
    </div>

Perhaps the content before and after the template comment is passed to the markdown processor separately?

**Comment by Keats** [comment]
Shortcode rendering happens before markdown so it shouldn't be the case. Shortcode parser doesn't have comments as well so that's pretty weird.

**Comment by jwatt** [comment]
I should note that I only tested with a tera comment, and just assumed that expressions or statements would trigger the same issue. I should have said that up front.

**Comment by Keats** [comment]
Any chance you can do a PR with some tests for that in the `rendering` subcrate?

**Comment by jwatt** [comment]
I want to say yes, but given my work and non-work time commitments at the moment I can just say that I'll try. Let's see how I get on with things this weekend. :)

**Comment by Keats** [comment]
No worries, take your time :)

**Comment by Keats** [comment]
If you don't have time for a PR, i will also take a paste of the markdown/shortcode

**Comment by Keats** [comment]
@jwatt ping for a testcase when you can
