### ISSUE TITLE
Make description optional?

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#48]
I'm not quite sure what the `description` field in the front matter is needed for, so I use `description = ""` everywhere. Maybe we can make that field optional (and default to `""`)?

**Comment by Keats** [comment]
It's the description in `meta` but I guess it should be optional.

**Comment by Keats** [comment]
Actually `title` can be optional too when you think about it, so an empty front matter would be valid!

**Comment by Keats** [comment]
`title` and `description` are now optional in master!
