### ISSUE TITLE
Fill section.subsections with relative paths

### ISSUE THREAD

**Issue by Keats** [getzola/zola#480]
Instead of the actual sections.

That gives us a few things:

- much better performance since we don't need to serialize all the pages and nested subsections
- allow 2 ways "linking": a section could have its subsections but also its parent or ancestors which could fix https://github.com/Keats/gutenberg/issues/284

And some cons:

- slightly harder template writing for people wanting to use subsections, basically adding one `{% set subsection=get_section(path=path) %}` line in the forloop
- worse UX: as mentioned above you need to go through one more step to access the data

Slightly unrelated but we could fix #260 now by adding the path of the parent section to each page as well.

**Comment by RealOrangeOne** [comment]
Would removing the subsections pages instead help the issue? This would give the benefit of drastically reducing the amount of serialization, but still allow subsections to be easily read. It does mean you'd still need to use `get_page` to get the nested pages, but hopefully that's a smaller percentage of the userbase.

**Comment by Keats** [comment]
I could be in the minority but every single use of `section.subsections` I have is to do some kind of menu where I need to fetch display subsections titles and their pages names/links (tera/gutenberg docs and https://github.com/Keats/book) so that would be the same result performance wise. It would also be a bit inconsistent to have `section.pages` be an array of `Page` while `subsection.pages` be an array of `Path` in my mind.

Does anyone use subsections for something *other* than a menu? I don't have other examples on hand other than the ones listed above.

**Comment by RealOrangeOne** [comment]
I've used the concept of subsections before with other generators to generate flat-looking section pages. Merging subsections and pages into 1 single list. This doens't require the sub pages to be rendered, but I could easily see how people would want to.

**Comment by Keats** [comment]
When you say flat-looking, do you mean something like https://github.com/Keats/gutenberg/issues/408 ?

**Comment by RealOrangeOne** [comment]
Exactly, but only traversing 1 level. So it means on a section page I could list all the pages and subsections. Clicking on one of them would either take me to a page, or another index page listing the pages / sections underneath _those_

**Comment by Keats** [comment]
PR at https://github.com/Keats/gutenberg/pull/484

Name for the field `parent_section` open to bikeshedding, I'm thinking of `parent`
