### ISSUE TITLE
ignore_content glob for subfolders

### ISSUE THREAD

**Issue by ghost** [getzola/zola#481]
The following works:

```
ignore_content = ["*.jpg"]
```

But let's say I want to ignore content in a content sub-folder like so:

```
ignore_content = ["gallery/*.jpg"]
```

This doesn't work. The .jpg files are included in the public build. The use-case here is that my site is using only resized and cropped images generated by gutenberg, and I do not want to be uploading the full-resolution originals, but there are originals in other places that I *do* want in the public build (e.g. outside of the `gallery` directory).

**Comment by Keats** [comment]
Looks like the globs are only ran on the filenames right now. What's the structure of your site?

**Comment by ghost** [comment]
In the example above...

```
.
├── config.toml
├── content
│   ├── bio.jpg
│   ├── bio.md
│   ├── gallery
│   │   ├── ancient-dwellers.jpg
│   │   ├── ancient-dwellers.md
│   │   ├── aspen-reflections.jpg
│   │   └── aspen-reflections.md
│   └── _index.md
├── sass
│   └── main.scss
├── static
├── templates
│   ├── index.html
│   ├── macros.html
│   └── page.html
└── themes
```

In which I would like to specify `ignore_content = ["gallery/*.jpg"]` in my config in order to achieve this result:

- `content/bio.jpg` is copied to the public directory as normal. This is a regular co-located asset that I would like placed in the final build.
- `content/gallery/ancient-dwellers.jpg` and `content/gallery/aspen-reflections.jpg` are very large images. I would like them to be available for image processing and ultimately placed in the `_processed_images` directory, but NOT have the original large images from `content/gallery/*.jpg` copied to the public directory.

So effectively I would like to be able to specify only some *.jpg files to be excluded. Make sense? My use case is an artist's portfolio, where the high-resolution final images placed in `gallery` will always need to be resized, but the rest of the content should be left as-is.

**Comment by Keats** [comment]
@PhilipDaniels you implemented the ignored content feature, any opinion on it? Can we change what is mentioned in https://github.com/Keats/gutenberg/blob/next/components/library/src/content/page.rs#L275-L281without any repercussions?

**Comment by PhilipDaniels** [comment]
Seems that was a prescient comment :-) The globset library which is being used appears to support the functionality that @winduptoy would like https://docs.rs/globset/0.4.2/globset/. I don't know enough about how Gutenberg walks the source folder to know whether changing `find_related_assets` to do a recursive scan would be OK - my concern would be whether it would introduce unnecessary disk IO (by finding files at level A, then level A.B, then level A.B.C etc.)

**Comment by Keats** [comment]
I'm wondering if checking the blog on both the filename first and then the full path could work. It might require users to do `ignore_content = ["**/gallery/*.jpg"]` though

**Comment by ghost** [comment]
@Keats That worked for me in 0.4.2!

**EDIT:** Nevermind, I spoke too soon, my file browser sorts directories first and I didn't see that the images were still there.

**Comment by Keats** [comment]
Hmm I didn't expect it to actually work without changing the code? :open_mouth:

**Comment by ghost** [comment]
Yeah my bad, got too excited. It doesn't work.

**Comment by Keats** [comment]
@winduptoy are you interested in trying to add that feature?

**Comment by ghost** [comment]
I would love to attempt it, but trying to `cargo build`  d3bd22c on `next` branch is giving me this:

```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> components/front_matter/src/page.rs:20:41
   |
20 |     #[serde(default, deserialize_with = "utils::de::from_toml_datetime")]
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `serde::Deserialize`
 --> components/front_matter/src/page.rs:4:5
  |
4 | use serde::Deserialize;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: aborting due to previous error
```

rustc 1.29.2
cargo 1.29.0

Any tips?

**Comment by Keats** [comment]
I thought I fixed that already. Use nightly for now to have the issue go
away

**Comment by Keats** [comment]
That is now properly fixed and should work again on stable.
