### ISSUE TITLE
Structured Data (TOML) instead of markdown

### ISSUE THREAD

**Issue by ghost** [getzola/zola#482]
Background: The original idea was to use the markdown to derive structured data (front-matter).

New idea: It would be much better instead to simply give structured-only data to the generator.
example:
```TOML
title = "Lithos Containers"
date = 2018-10-13
type = post

[Lithos-containers]
  body = """
    Lithos provides a modern rust library to launch and supervise processes on linux.
    It is quite heavy on storage space; the last build produced a series of executables
    which totalled over 250mb of space. Certainly a lot of them could reuse a shared library,
    so it should be able to minimize this problem. Nevertheless, it is the most promising
    way to create secure processes under a linux system without too much hassle and overhead.
  """
  yuml-chart = """
    [Lithos Config]->[Limited Ressources (namespace)]
    [Namespace]->[Supervised Process]
  """
```

The final idea is to replace text editors with scructured data editors, and store/read from binary format (CBOR?). Then, modify browser engines to use a sane subset of html+css converted to this structured binary. I guess javascript already has a bytecode.
I'v seen at least one markdown2json [converter](https://github.com/stonecircle/broccoli-static-site-json); those could be used to port over 'legacy' markdown files, while reusing/augmenting the 'frontmatter'.

Since `gutenberg` already uses TOML for the front-matter, it should be able to (relatively) easily use it for content, and that would probably reduce the complexity quite a lot (moving it elsewhere of course). So, what do you think?

Edit: looks like others have the same [idea](https://github.com/gohugoio/hugo/issues/5193)

**Comment by Keats** [comment]
This is already possible by putting everything in `extra` but you will not get the niceties of the gutenberg rendered like shortcodes/relative links and syntax highlighting.

**Comment by ghost** [comment]
Sounds like I have a place to start. Would you like me to close the issue? I could document my progress elsewhere. I'm no github wizard. Just let me know. I can already feel the quality of gutenberg, given how easily I can start on this. Thanks again!

**Comment by Keats** [comment]
I'll close this one for now but I will still get notified if you post something, don't hesitate
