### ISSUE TITLE
Template variable for relative filesystem location of page/section

### ISSUE THREAD

**Issue by pkgw** [getzola/zola#485]
This is a proposal/request for a small feature. When rendering pages and sections, could a Tera variable be added that gave the filesystem path of the content being rendered? For instance, if the file was at `content/mysection/mypage/index.html`, the variable would be set to something like `mysection/mypage/index.html`.

My motivating use case is admittedly quite specialized: I maintain my site in a Git repository that's also available on GitHub, and I'd like to include a link from each rendered page back to its source on GitHub, so that people can propose edits to the pages with just a handful of clicks.

**Comment by Keats** [comment]
Sounds like a common enough usecase I've seen, that will be in the next release

**Comment by Keats** [comment]
It's in the `next` branch if you want to try it.

**Comment by pkgw** [comment]
Looks great, thanks! [Here's an example using the functionality](https://newton.cx/~peter/howto/correctly-cancel-python-shell/) — note the GitHub links at the bottom of the page. [Here's the relevant template](https://github.com/pkgw/website/blob/master/templates/howto.html#L17).
