### ISSUE TITLE
The <atom:link> tag's href in rss.xml erroneously has a trailing slash

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#486]
The rss.xml contains a link to itself, but with a forward slash appended which causes 404 errors. I.e. it looks like this:

    <atom:link href="https://example.com/rss.xml/" rel="self" type="application/rss+xml"/>

It seems that `render_rss_feed` calls `make_permalink`, and `make_permalink` ensures that the link always ends with a trailing "/" unless the value passed in is the empty string.

I'm not sure how you'd prefer this to be fixed, Vincent. I'd probably fix it by adding an optional argument to `make_permalink` to indicate whether a trailing slash should be appended or not. Maybe you have other ideas though.

**Comment by Keats** [comment]
hmm interesting. I think make_permalink should probably check whether the page ends by something with an extension and not add a trailing slash if it's the case

**Comment by Keats** [comment]
Turns out it's only used for pages and rss.xml so just adding a special rule for rss.xml fixes it, no need to be fancy.
It should be fixed in the `next` branch
