### ISSUE TITLE
tags in headers results in unexpected behaviors in table of contents

### ISSUE THREAD

**Issue by bdjnk** [getzola/zola#487]
This is really two and a half problems.

Regardless of the tag, the header `id` (and the hash portion of the permalink) is truncated. Either to the content of the tag, if the tag is appears before before any text, or to the text preceding the first tag.

Certain tags appear in the toc titles, like `a` or `code` tags, while others, like `strong` and `em`, don't.

Bonus potential Tera bug, `striptags` doesn't work to strip the appearing tags.

**Comment by Keats** [comment]
Any chance you can do a PR some failing tests or just pasting examples in this issue?

**Comment by bdjnk** [comment]
I'll take a look at creating a PR if time becomes available.

Regarding examples, create a page with the following markdown content.

```markdown
## header with `code`
`id` will be "header-with"
`title` will be "header with <code>code</code>"

## [anchor](google.com) in header
`id` will be "anchor"
`title` will be (approximately) "<a href='google.com'>anchor</a> in header"

## **bold** and *italics*
`id` will be "bold"
`title` will be "bold and italics"
```

**Comment by bdjnk** [comment]
Additional information, and a question.

The following added to `components/rendering/tests/markdown.rs` in a new test

```rust
    let res = render_content(r#"
## header with `code`

## [anchor](https://duckduckgo.com/) in header

## **bold** and *italics*
    "#, &context).unwrap();

    let toc = res.toc;
    println!("{:#?}", toc);
```

Running `cargo test -- --nocapture` from `components/rendering` produces

```
[
    Header {
        level: 2,
        id: "header-with",
        title: "header with <code>code</code>",
        permalink: "https://mysite.com/something#header-with",
        children: []
    },
    Header {
        level: 2,
        id: "anchor",
        title: "<a href=\"https://duckduckgo.com/\">anchor</a> in header",
        permalink: "https://mysite.com/something#anchor",
        children: []
    },
    Header {
        level: 2,
        id: "bold",
        title: "bold and italics",
        permalink: "https://mysite.com/something#bold",
        children: []
    }
]
```

Clearly the permalinks are broken, but here's the question. What is the expected behavior of the `title`?

On further consideration retaining HTML tags might be the more sane behavior. In which case is the last example the one behaving incorrectly?

**Comment by Keats** [comment]
I think removing the HTML tags would be the saner option for the TOC.  For example, if you have a link wrapped in a link like the second one, it's not going to work well.

**Comment by bdjnk** [comment]
You're right about nested anchors, and although it might be reasonable for TOC links to retain header tags, it's probably much simpler to strip them, and not excessively surprising.

I'd like to try a PR to fix this issue if you haven't started working on it.

p.s. There is no Tera bug, `striptags` does work as expected if you first use `safe`.

**Comment by Keats** [comment]
> I'd like to try a PR to fix this issue if you haven't started working on it.

Go for it! Don't forget to do the PR on the `next` branch.
