### ISSUE TITLE
Shortcodes don't work

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#49]
When I try to call a shortcode, the following error occurs:

```
Failed to build the site
Error: Error parsing templates
Reason: 
* Failed to parse '"/home/…/templates/index.html"'
-- Invalid Tera syntax at line 32, column 8
```

Line 32 of `index.html` looks like this:

```
{{ gist(url="https://gist.github.com/Keats/32d26f699dcc13ebd41b") }}
```

**Comment by Keats** [comment]
Shortcodes are called from inside `.md` files, not inside html files. The equivalent of shortcodes in templates would be macros

**Comment by phil-opp** [comment]
Oh ok, I'll try macros then
