### ISSUE TITLE
redirect_to value in front matter cannot be None

### ISSUE THREAD

**Issue by corentin-cres** [getzola/zola#490]
I'm having an issue giving the `None` value to redirect_to in a front matter, as described in the docs :

> 
> ```
> # Whether to redirect when landing on that section. Defaults to `None`.
> # Useful for the same reason as `render` but when you don't want a 404 when
> # landing on the root section page
> redirect_to = ""
> ```
> 

I tried `redirect_to = "None"`, `redirect_to = None`, `redirect_to = ""`, ...

If a string value is supplied ("None", "", ...), my browser will get redirected to `http://mydomain.com/{STRING_SUPPLIED}/`
If I supply any value that is not a string, the `gutenberg build` command will fail and complains that an `invalid number` was found, or that it cannot parse my front matter.

The only workaround I found is to not have `redirect_to` entry in my front matter.
But from my understanding of the docs, I should be able to give a redirect_to that is None.

**Comment by Keats** [comment]
That's what happens when you copy/paste the comment of the struct :(
I clarified in the commit above: it needs to either be not present or have a string value.

**Comment by corentin-cres** [comment]
Much clearer, thanks !
