### ISSUE TITLE
A directory per post

### ISSUE THREAD

**Issue by realcr** [getzola/zola#491]
Hi, thank you for this project!

Whenever I write a new post, besides the text itself I also want to keep a few assets next to the markdown file. Therefore it is important to me to have one directory per post, where I put all the files together. I don't want to put the asset files in the static directory, because then they are scattered, and it is hard to see which one belongs to which post.

My current workaround is to have every post as a "section", as follows:
```
├── chord_stabilize
│   ├── floor_ceil.svg
│   ├── _index.md
│   ├── ring_2.svg
│   ├── single_vs_doube_link.svg
│   ├── single_vs_double_link.svg
│   ├── y_disconnected_stb1.svg
│   ├── y_disconnected_stb_all.svg
│   └── y_disconnected.svg
├── connectivity_towers
│   ├── _index.md
│   └── towers_and_nodes.svg
├── dht_basic_security
│   ├── _index.md
│   ├── riddle_exchange.svg
│   ├── riddle_redirection.svg
│   └── wanted_interval_floor_k.svg
```
Note that each post comes with a few assets. As mentioned above, I don't want to put the static assets at the static directory, because then they will be scattered. I want them to be together with the text file.

In the example above, `chord_stabilize/_index.md` is considered to be a section instead of a page (Because it is named _index.md). One thing for example that I can not do with sections is use the `config.date` variable. In addition, the `section.html` template is applied instead of the `page.html`.

I wonder if there is a workaround that will still allow me to have one post per directory, but at the same time have the post page be rendered using the "page.html" template.

**Comment by Keats** [comment]
You are looking for https://www.getgutenberg.io/documentation/content/overview/#assets-colocation I think?

**Comment by caemor** [comment]
Using `index.md` instead of `_index.md` should solve your problem I believe

**Comment by realcr** [comment]
I just tried what you suggested and it worked! Thank you for your quick replies, sorry to bother you with a question I should have read about in the documentation. I don't know how I missed it the first time I read it.
