### ISSUE TITLE
Front matter not found.

### ISSUE THREAD

**Issue by cedws** [getzola/zola#493]
I've just set up a fresh site with a single file called `hello-world.md` in `content`. The file looks like this:
```
+++ +++

# Hello World
This is a test page.
```

When I run `gutenberg serve`, it outputs `Error: Couldn't find front matter`, even though it's there.

**Comment by Keats** [comment]
You need a newline in between the 2 +++ I believe

**Comment by cedws** [comment]
I've also tried that, and I get the same error.

**Comment by piedoom** [comment]
Assuming you don't have any special required variables, try copy and pasting this into your file:

```
+++
+++
# Hello
this is a test
```

And seeing if that works.

Otherwise what does your directory of files look like?

**Comment by cedws** [comment]
It seems it was a problem with the Hyde theme rather than Gutenberg. It expected a `date` to be defined and wouldn't render anything otherwise. I should mention that the [hello.md](https://github.com/Keats/gutenberg/blob/master/test_site/content/hello.md) shows `+++ +++` for some reason, unless you view the raw file. I will close this now, thanks for your help.

**Comment by hollisticated-horse** [comment]
I have had a similar problem, but it was two spaces behind the first `+++` that triggered the error. Even one space throws an error. 

Incorrect:

```
+++  <-- two spaces

+++
```
Correct: 

```
+++

+++
```
