### ISSUE TITLE
Paginator includes drafts

### ISSUE THREAD

**Issue by maghoff** [getzola/zola#495]
According to [the documentation of Page front matter][1],

>A draft page will not be present in prev/next pagination

[1]: https://www.getgutenberg.io/documentation/content/page/

However, in my experience this is not true. For my example gutenberg site at <https://github.com/maghoff/gutenberg-draft-bug>, the draft post _does_ appear in the render output.

This problem appears in the current master, v0.4.2 and v.0.3.4.

**Comment by Keats** [comment]
Looks like a big bug, but pretty easy to fix thankfully

**Comment by Keats** [comment]
Should be fixed in the `next` branch!
