### ISSUE TITLE
multipy "static" directory like pathes

### ISSUE THREAD

**Issue by mash-graz** [getzola/zola#499]
gutenberg only supports one single directory, which has to be named "static" for the inclusion of media assets and similar stuff.

if you utilize via git web frontends like GitLab, this doesn't work very well, because the image src locations resp. path relations in the source tree are never the same as in the final generated pages. on local machines you can work around this issue by utilizing symbolic links, but this approach doesn't work very well with multiplatform oriented git CI/CD workflows. in this case you have to utilize very inefficient and unpleasant copy instructions in the CI scripts as a last resort. 

a configuration option to specify additional source/target directory pairs, which will work otherwise just like the `static` directory mechanism, would provide a much nicer solution to make e.g. the `/images` location accessible even in the source tree just like in the finally generated pages.

**Comment by Keats** [comment]
You can have assets next to content: https://www.getgutenberg.io/documentation/content/overview/#assets-colocation

**Comment by mash-graz** [comment]
yes -- that's another workaround, which i was thinking about, but it doesn't work very well for tools like [netlify-cms](https://www.netlifycms.org), which want to upload all assets to one location.

**Comment by Keats** [comment]
> but it doesn't work very well for tools like netlify-cms, which want to upload all assets to one location.

That looks like a limitation of netlify-cms, but Hugo has a similar one folder static and I expect netlify-cms work with it?

**Comment by mash-graz** [comment]
netlify-cms allows [two variants of media_folder setup](https://www.netlifycms.org/docs/add-to-your-site/#media-and-public-folders):

 * image folder relative to the project root (Jekyll, GitBook, ...)
 * image folder located inside the `static` hierachy (Hugo, Hexo, Middleman)

although the latter variant works well, if you only want to use netlify-cms web-frontent, it isn't compatible with markdown previews/rendering in GitLab and similar setups, because of the changing path reference. i think, that's also the reason, why most popular GitHub SGGs prefer the other variant.

the third variant -- i.e. puting the images inside the content folder --, doesn't work with netlify-cms if you use more than one `collection` (=`section`).

well -- it's indeed only a minor issue, because it's rather easy to utilize GitLabs CI system capabilities or other batch processing scripts to copy pictures around or create links etc. before finally calling gutenberg, but a simple configuration option for this purpose, still looks like a more desirable solution to me.

**Comment by JadedBlueEyes** [comment]
My issue is that I have a giant pile of image files, from RFG, that need to go into my project root. I don’t want these cluttering up my static directory. When I used Jekyll, I created a collection called favicons, and changed some majic config to copy it to the root. It’d be nice if there was some way to configure copying one folder of static files to a specific position in the output.

**Comment by Keats** [comment]
Probably not going to happen in the short term and doesn't seem like a feature requested by many.
