### ISSUE TITLE
Allow utf-8 bom in .md files

### ISSUE THREAD

**Issue by getreu** [getzola/zola#501]
Many modern editors prepend the bytes `EF BB BF` to indicate, that the present text-file is encoded in UTF-8.

`gutenberg` does not tolerate this and exists with 

    Failed to build the site
    Error: Couldn't find front matter in `/usr/local/bak/WEB-SERVER-CONTENT/blog.getreu.net/blog2/content/20181027-bash-scripts-blog.md`. Did you forget to add `+++`?

**Comment by Keats** [comment]
That happens because it uses a regex (in front_matter/lib.rs). I'll take a PR on the `next` branch for that!

**Comment by Keats** [comment]
Turns out it was easy to fix, it's done in the `next` branch
