### ISSUE TITLE
Empowering `gutenberg serve` to handle PHP files

### ISSUE THREAD

**Issue by fbruetting** [getzola/zola#502]
I just have one small PHP file which I need to be run. This works perfectly fine on my server, but `gutenberg serve` doesn’t handle this at all and instead Firefox shows me a dialog for downloading the file. Would be cool if that could be handled in the “simulator”.

**Comment by Keats** [comment]
That would mean embedding a PHP interpreter in Gutenberg, which is definitely not something that belongs in Gutenberg imo. As mentioned in the other thread, that sounds like you should use the upcoming watch feature and use your webserver locally.

**Comment by RealOrangeOne** [comment]
All HTML files are valid PHP, they just don't have any templating. If you get Gutenberg to copy the file into your output directory, and serve that output directory with a PHP server, such as Apache2, you should get the functionality you need.
