### ISSUE TITLE
Conflict with files in root of `content`?

### ISSUE THREAD

**Issue by chriskrycho** [getzola/zola#504]
I'm slowly building out a site, and have an `index.md` and an example post stolen from the current version of my blog named `true-myth-22.md`, both in the root of the `content` directory. Gutenberg seems to be treating them as the same for some reason, though: I see this whenever I am doing `gutenberg serve` and make a change to `true-myth-22.md`:

```
Change detected @ 2018-10-29 06:53:42
-> Content changed /Users/chris/Sites/chriskrycho.com/v4/content/true-myth-22.md
Failed to build the site
Error: Change on "/Users/chris/Sites/chriskrycho.com/v4/content/true-myth-22.md" detected but there is already an `index.md` in the same folder
Done in 0ms.
```

This happens no matter what the content of the TOML metadata block for `true-myth-22.md` is – it can even be empty. I feel I must be doing something incredibly dumb!

**Comment by Keats** [comment]
That is weird, can you try with the `next` branch to see if it happens as well?

**Comment by chriskrycho** [comment]
@Keats I will take a look! However, changing `index.md` to `_index.md` solved the immediate problem. I'll see if I can come up with a PR later this week to clarify this and a few other pieces of the docs that stumped me a little over the weekend!

Related: is there a Netlify preview or similar for the docs for the next branch? If not, that would be a great help.

(The experience with this so far has been really great, by the way!)

**Comment by Keats** [comment]
`index.md` should only be used for folders with co-located assets so that will not work in `content`.

No Netlify preview for the `next` branch as it changes name to Zola and has some breaking change that require a released version first. Sadly I don't think zola 0.5 will be available immediately on Netlify for its release and I can't get the PR to add it merged (https://github.com/netlify/binrc/pull/19)

**Comment by chriskrycho** [comment]
Thanks; that's a helpful clarification and if I can get that docs PR together I'll make sure that is even clearer than it is now.

I'll be watching that issue in hopes they get back to it soon!

I'm happy to close this now that I understand what's up; thanks for the quick responses.
