### ISSUE TITLE
Is there an easy way to redirect an old url?

### ISSUE THREAD

**Issue by MaikKlein** [getzola/zola#507]
For example I have some old links to blog posts that look like this `myblog.com/posts/some-blog-post` but now it is located at `myblog.com/some-blog-post`.

Is there a way so that I can easily fix up all the old urls?

**Comment by Keats** [comment]
You can use `aliases`: https://www.getgutenberg.io/documentation/content/page/

**Comment by Keats** [comment]
Is it working for you?

**Comment by MaikKlein** [comment]
Would that require me to change all the headers of my posts? I think that should work, I guess I have to learn some sed :).

**Comment by Keats** [comment]
> Would that require me to change all the headers of my posts? 

If you are not using a server, yes.
