### ISSUE TITLE
Get time when processed

### ISSUE THREAD

**Issue by piedoom** [getzola/zola#510]
It may be useful to gather the time whenever the page is built.  For instance, the "©2018 by Etc" can be dynamically generated so it updates whenever a page is redeployed.  It also may be useful to show the last time the blog was active.  I don't believe this is yet something that can be done outside of getting the latest page date.

**Comment by Keats** [comment]
Tera has a `now` function (https://tera.netlify.com/docs/templates/#built-in-functions) that should do what you want

**Comment by piedoom** [comment]
Ah! I always forget to check the Tera docs.  Thanks.
