### ISSUE TITLE
Allow shortcodes to behave differently in page/list context

### ISSUE THREAD

**Issue by bkhl** [getzola/zola#513]
I would like to have images in pages link to themselves if you are looking at them on the page itself, but to the page if they appear in on list pages (like the front page).

For now I've got a shortcode file named `image.html` with this content:

```
<div>
    <a href="/{% if page.path != current_path %}{{ page.path }}{% else %}{{ page.path }}{{ filename }}{% endif %}">
        <img src="/{{ page.path }}{{ filename }}" {% if description %} alt="{{ description }}" {% endif %} />
    </a>
</div>

```

This example without the link to the image 

However, `current_path` is not available to the shortcode. Should this be fixed, or is there some more elegant way of achieving the same thing?

**Comment by Keats** [comment]
Markdown are only rendered once and the renderer doesn't have any way of
knowing the current_path. I don't see any way of doing that.

**Comment by bkhl** [comment]
Would you be appreciative of patches if I came up with some elegant way of doing this?

I'm thinking either some way to hook into the Markdown rendering to customize how image links are rendered, or some way to enter a macro in the markdown and then be it processed first after the rendering from Markdown is done. Is the latter already possible in some way maybe?

**Comment by Keats** [comment]
I can't think of a way to do it that won't kill performances, as that will require you to render the markdown many times.
You could have the whole page on the list template be in a `<a>` linking to the page itself

**Comment by bkhl** [comment]
Actually that might work out alright in the theme I'm working on. Thanks for the idea.

**Comment by bkhl** [comment]
Actually that didn't work, at least not without some hack like an invisible element covering the whole article entry.

I'm not sure I understand the problem anyway. Would it not be possible to allow some syntax that passes through the Markdown processing unmodified, and gets expanded at a later stage?

**Comment by Keats** [comment]
> Would it not be possible to allow some syntax that passes through the Markdown processing unmodified, and gets expanded at a later stage?

Which stage would that be? You can only know how and where pages are used by looking in the templates so which version should go into the `get_page` Tera function or for rendering taxonomies/sitemap?
For your case if wrapping everything in a `<a>` is too much, I would probably rewrite the URLs in Javascript

**Comment by bkhl** [comment]
I'll admit I didn't check the code very carefully. I posted this issue to check if it was a wanted feature and thus worth making an effort. Otherwise I can as you say do that myself later, though I think I'll go with `xmlstarlet` or something, to remove any links that point to the same page that they are in (which will cover my case).

**Comment by bkhl** [comment]
Just went back to this now, and for reference if someone is looking for a solution for this, what I ended up doing was to put the image in the content metadata instead, like this:

```
+++
…

[extra.image]
filename = "foo.jpeg"
title = "Alt text"
description = "Some text that goes as a caption if defined"
+++
```

Then on pages:

```
{% if page.extra.image %}
    {{ macros::featured_image(page=page, filename=page.extra.image.filename, data=page.extra.image) }}
{% endif %}
```

And in lists:

```
{% if page.extra.image %}
    {{ macros::linked_featured_image(page=page, filename=page.extra.image.filename, data=page.extra.image) }}
{% endif %}
```
