### ISSUE TITLE
0.4.3 release with recent Tera fixes?

### ISSUE THREAD

**Issue by chriskrycho** [getzola/zola#514]
Hey, working on a site between now and the next release and ran into a bug that was fixed by Tera 0.11.15 (the unreachable `Cow::Owned` issue). Would you consider releasing a point version that just bumped Gutenberg to use the latest Tera?

**Comment by Keats** [comment]
I was holding on releasing 0.5 for Netlify but it doesn't seem like that is going to happen anytime soon so I'll probably just release this week or early next week
