### ISSUE TITLE
Provide Table of Contents Length / Header Count

### ISSUE THREAD

**Issue by bdjnk** [getzola/zola#518]
It would be helpful for deciding in post templates whether or not to include the table of contents to have a total header count.

**Comment by Keats** [comment]
How do you calculate it? It is total number of headers or at a certain depth?

**Comment by bdjnk** [comment]
The total number of headers for my use case.

Currently I don't calculate it, because it wasn't apparent how to do so using Tera given the nested arrays data structure of `page.toc`.

**Comment by Keats** [comment]
I *think* you can do something like

```jinja2
{% set num_headers = 0 %}
{% for h1 in page.toc %}
 {% set_global num_headers = num_headers + 1 %}
 {% for h2 in h1.children %}
    {# stopping at h3 but you can go lower if you need #}
    {% set_global num_headers = num_headers + 1 + children | length %}
 {% endfor %}
{% %}
```
I haven't ran it but it should work in theory, minus typos and prettiness of the solution.

**Comment by bdjnk** [comment]
Thanks, that pattern works. If this isn't something other folks need or want I can close this.
