### ISSUE TITLE
Editing content files breaks rendering by gutenberg serve

### ISSUE THREAD

**Issue by AdrienLemaire** [getzola/zola#52]
Since a picture is worth a thousand words:
![demo](https://i.imgur.com/TsUtJxn.gif)

Somehow, `gutenberg serve` finds the edit unacceptable and delete all the generated html for that article.

**Comment by Keats** [comment]
I'm pretty sure I already fixed this bug, we'll debug it together next week

**Comment by AdrienLemaire** [comment]
Verified, fixed in master, thanks.
