### ISSUE TITLE
RFC: Generic file assets

### ISSUE THREAD

**Issue by RealOrangeOne** [getzola/zola#520]
There's currently 2 main types of content: Pages and static files. Copying off a design pattern from Jekyll, i'd like to add a 3rd, which i'll refer to _assets_.

Given an additional subdirectory in the project root, `assets/`, all files inside are copied to the output directory as-is, as with static files, but are passed through the template engine first. 

Internally, this could be used to remove special casing for files such as `robots.txt` and `sitemap.xml`, as these could both be implemented as assets. Assets would need resolving after pages, as they'll likely want / need the rendered pages as context.

**Comment by Keats** [comment]
> this could be used to remove special casing for files such as robots.txt and sitemap.xml,

It isn't that easy sadly. sitemap also gets all taxonomies and this issue made me realise it is missing the pager pages for both sections and taxonomies in case it is paginated :(

**Comment by RealOrangeOne** [comment]
The taxonomy data would still be available though right? If we stored the taxonomy data on the site, and passed that through the context, it could still be used. I think these issues are separate (although it's probably best to fix the sitemap before moving it, so everything is considered

**Comment by Keats** [comment]
That would slow down the overall rendering of the site to pass all that data for more files though. The sitemap only gets the URLs for example but it is pretty slow to render when you have 10k pages

**Comment by Keats** [comment]
Can we move the discussion to the feature request section of https://zola.discourse.group/ ?

**Comment by RealOrangeOne** [comment]
Added, awaiting moderation. I'll close this post once that's live.

**Comment by Keats** [comment]
I didn't realise there was moderation, I'll need to remove it
