### ISSUE TITLE
after zola upgrade: failed to parse datetime for key `date

### ISSUE THREAD

**Issue by getreu** [getzola/zola#525]
After upgrade to zola my build fails:

```
zola build
Building site...
Failed to build the site
Error: Error when parsing front matter of page `[.]/blog2/content/20170307-restructuredtext-notetaking-blog.md`
Reason: failed to parse datetime for key `date
```
This file has the the following front matter:

```
+++
title = "Note taking with reStructuredText"
date = 2017-03-07

[taxonomies]
categories = ["technical documentation", "software"]
tags = ["notetaking", "reStructuredText", "reST", "bash",]
+++
```

**Comment by Keats** [comment]
Looks like the regex for dates in filenames might be accepting too much, I'll have a look later.

In the meantime, you can rename the files like so `2017-03-07-restructuredtext-notetaking-blog.md` and remove the date from the front-matter.

**Comment by Keats** [comment]
Actually this combination of filename + frontmatter works for me :o 
Any chance you can set up a small reproduction?

**Comment by getreu** [comment]
Test case:

[blog3.zip](https://github.com/getzola/zola/files/2597045/blog3.zip)

Result:

```bash
$ zola build
Building site...
Failed to build the site
Error: Error when parsing front matter of page `./blog.getreu.net/blog2/content/20170308-stringsext-blog.md`
Reason: failed to parse datetime for key `date`
```

**Comment by getreu** [comment]
I found it: All problematic files had a trailing space after the date, like in `date = 2018-03-14 `. After removal of trailing whitespaces, the site compiles again.
There is a trim missing before parsing the date.

**Comment by Keats** [comment]
That's apparently correct according to the spec? No whitespace allowed after a date part because it is expecting nothing or a `T`.
The Rust impl (https://github.com/alexcrichton/toml-rs) seems to apply it strictly but it might be worth asking it to add a trim

**Comment by getreu** [comment]
Yes definately. In the meantime, it would be nice to have a more detailed error message to tell the user what to do. When you run into this, this is a show-stopper.

**Comment by Keats** [comment]
This is done by the toml parser though and you don't get info on what raised the error so you can't differentiate between a legit one and a bad one like this.

**Comment by getreu** [comment]
Maybe it is possible to trim() all lines before feeding them into the toml parser?

**Comment by Keats** [comment]
The toml lib has been updated so it should be fixed in the next zola release!
