### ISSUE TITLE
Broken links in titles

### ISSUE THREAD

**Issue by AdrienLemaire** [getzola/zola#53]
# Issue

When adding the following markdown code:

```
# [](#configure-solarized-with)Configure Solarized with ...

## [](#xresources)Xresources

> **Xresources** is a user-level configuration dotfile, used to set X resources
> used by X client applications.
....
```

I get the following code:

![2017-05-01_15-02-50](https://cloud.githubusercontent.com/assets/260983/25573316/45f0ba64-2e7f-11e7-90f9-1e2f9554f7a7.png)

# Expected behavior
There should be an empty link created before the title, not visible on the page.

**Comment by Keats** [comment]
Not perfect but I'm now ignoring links in headers. Since gutenberg has anchors built-in, I don't think there's a reason for links in headers
