### ISSUE TITLE
Zola init hangs

### ISSUE THREAD

**Issue by BojanKogoj** [getzola/zola#530]
As a first time user, I installed 0.5.0 with scoop

After that I tried to init, but it hangs
```
PS C:\Users\Bojan\projects\prototypes> zola init testzola
Welcome to Zola!
```
It stays like that, and there is nothing inside the folder it creates.

I am using Windows 10, and finding anything online is difficult because of www.zolawindows.com

**Comment by Keats** [comment]
Hmm, can anyone on Windows try it?
It works on Linux so I am guessing the `colorize` https://github.com/getzola/zola/blob/master/src/console.rs#L41-L46 fails to lock stdout on Windows?

**Comment by BojanKogoj** [comment]
I managed to build it from source, and now init worked.

**Comment by BojanKogoj** [comment]
As it turns out the issue is with PowerShell ISE, not Zola.

**Comment by Keats** [comment]
Let's leave it open, it still sounds like a bug

**Comment by caemor** [comment]
I tested it right now in windows. It seems to be a specific problem of Powershell **ISE** (see screenshot). It worked as expected on the normal powershell
![grafik](https://user-images.githubusercontent.com/11088935/48727840-a32e2e00-ec33-11e8-9c37-b0f70f3c7397.png)

**Comment by Keats** [comment]
I am guessing `zola build` or serve on an existing zola site hangs as well?

**Comment by caemor** [comment]
nope, thats somehow working as it should and the content is served 🤔.
and yes thats the ps ise (I got unsure myself for a second :-D )

![grafik](https://user-images.githubusercontent.com/11088935/48728234-b1c91500-ec34-11e8-872c-5b15d063836c.png)

**Comment by Keats** [comment]
It might be the `read_line` function in `src/prompt.rs` then if it's not due to the colors

**Comment by lzybkr** [comment]
If a console application is interactive, it will hang in the PowerShell ISE. This will likely never be fixed.

You could possibly check if the parent process is powershell_ise and report an error.

**Comment by Keats** [comment]
> If a console application is interactive, it will hang in the PowerShell ISE. This will likely never be fixed.

Oh :(

I guess I will add a note about that in the documentation and close that issue.
