### ISSUE TITLE
Paginating taxonomy term pages

### ISSUE THREAD

**Issue by bkhl** [getzola/zola#533]
I have an issue which I'm not sure to call a bug or a missing feature, as this doesn't look to have been documented [here](https://www.getzola.org/documentation/templates/taxonomies/) yet.

I added a taxonomy like this:

```toml
taxonomies = [
    { name = "categories", rss = true, paginate_by = 10 },
]
```

Then, in my `single.html` template, I have:

```
{% for page in paginator.pages %}
    {{ post_macros::page_in_list(page=page) }}
{% endfor %}
```

I have used a category called `Photos`, so I would expect this to generate pages such as `public/categories/photos/page/1` etc.

Instead, `public/categories/photos` contains only an RSS file, and the pages I would expect appear as `public/categories/pages/1` etc.

Also, the `single.html` template does not receive any `term`, so I'm not sure how to set a title reflecting the category I'm paging through.

**Comment by Keats** [comment]
That's not good :(
I will have a look later this week but the missing documentation is particularly odd.

> Also, the single.html template does not receive any term

It comes as `taxonomy` I believe

**Comment by bkhl** [comment]
I tried using `taxonomy.name`, but that gave me the name of the taxonomy (`categories`), not the particular term. That may be connected to it not creating individual pages for each term, of course.

**Comment by Keats** [comment]
Ah yes the issue is with `single` terms. I'll have a look when I get some time

**Comment by Keats** [comment]
Can you try the `next` branch with the commit above?

**Comment by bkhl** [comment]
Works for me, I can now use `paginator` in `single.html`.

Thanks for the fix, and general thanks for creating this neat tool.
