### ISSUE TITLE
date get's stripped from url

### ISSUE THREAD

**Issue by vintagesucks** [getzola/zola#537]
After upgrading from `gutenberg 0.4.2` to `zola 0.5.0` I noticed this change in behavior and I am not sure if this is a bug or a misconfiguration on my end.

`2018-10-02-a-friendly-reminder.md`:
```
+++
date = 2018-10-02T15:00:00Z
title = "a friendly reminder"
draft = false
+++

...
```

Old behavior: `http://127.0.0.1:1111/2018-10-02-a-friendly-reminder/`
New behavior: `http://127.0.0.1:1111/a-friendly-reminder/`

I'd like to keep the date in the URL.

**Comment by Keats** [comment]
That's due to the fact that since 0.5 the dates can be parsed from the filename. 
For a filename like `yyyy-mm-dd{-,_}...`, the date is extracted and the slug is made from the rest of the filename. If you want to keep the date in, you will need to set the `slug` bit of the frontmatter. You can also remove the `date` from it.

**Comment by vintagesucks** [comment]
Thanks, using the `slug` should work to keep my url scheme. 

I can't remove the `date` from the frontmatter since I have a time in my `date` and my posts are sorted by date and time. Removing the `date` would remove sorting by time if I have multiple posts on the same day. 

Am I missing something that would make this easier without having to maintain the date in three places (filename, `date`, `slug`)?

**Comment by Keats** [comment]
> Am I missing something that would make this easier without having to maintain the date in three places (filename, date, slug)?

Right now no :(
I didn't think of the case where you need the time when I implemented this feature, it could be extended to support having a `T15:00:00Z` bit after the dates like in the TOML spec.


@vintagesucks would it be fine having the time in your filename?

**Comment by vintagesucks** [comment]
> @vintagesucks would it be fine having the time in your filename?

That would be fine by me.

**Comment by Keats** [comment]
I added it to the `next` branch if you want to give it a try

**Comment by vintagesucks** [comment]
Hi @Keats! Sorry, I hadn't found the time (and local Rust environment) to try it yet. Thanks for the implementation! 

> > @vintagesucks would it be fine having the time in your filename?
>
> That would be fine by me.

Had I tested it, I would have noticed the following before: This doesn't work under Windows because I can't have a colon in the filename. :stuck_out_tongue:

You don't have to think about a solution if I'm the only one with this problem, I wanted to rework my blogging workflow anyway so that I could do without Windows.

**Comment by Keats** [comment]
> This doesn't work under Windows because I can't have a colon in the filename.

Damn didn't think of that :(
I don't think I want to invent a new date formatting standard though so it will probably stay like that and only work for non-Windows. I need to update the docs to mention that
