### ISSUE TITLE
`check_external_links` should check and list all links, not fail on first.

### ISSUE THREAD

**Issue by ralfbiedert** [getzola/zola#538]
As the title says, it looks as if links are checked one-by-one with an error emitted on the first failed link. 

For efficiency reasons I would prefer if all broken links are reported in one run instead.

**Comment by Keats** [comment]
Totally agree. This should be fairly easy if someone wants to get started with zola

Semi-duplicate of #381

**Comment by sarathsoma** [comment]
I like the project, would like contribute, can i take this up ?

**Comment by Keats** [comment]
@sarathsoma go for it! Let me know if you need any help.
Make sure to check out https://github.com/getzola/zola/issues/381 to make it a `zola check` command as well

**Comment by sarathsoma** [comment]
sure!

**Comment by codesections** [comment]
@sarathsoma, I would also be happy to help with this.  Let me know if there's any way I can be helpful, whether it's with code review or a discreet part of the functionality you'd like me to work on.  (Or, if you don't need any help, no worries at all—just thought I'd offer :) )

**Comment by Keats** [comment]
@sarathsoma @codesections are you still working on it?

**Comment by codesections** [comment]
I haven't done any work on this so far but would be happy to do so if needed.

**Comment by Keats** [comment]
I think you can get started @codesections

**Comment by Keats** [comment]
Anyone working on that?

**Comment by marcusklaas** [comment]
I think I could pick this up if it is still available. Maybe it makes sense to collect all URLs per page/ section and then go through them with a parallel iterator? That should solve this issue and also speed up significantly the checking of pages with many links.

**Comment by Keats** [comment]
> Maybe it makes sense to collect all URLs per page/ section and then go through them with a parallel iterator?

Definitely!
Do you want to continue working on #663 ?

**Comment by marcusklaas** [comment]
Sure, I can wrap it in there :-)

**Comment by Keats** [comment]
Copying what I wrote on #539 about having a check for anchors for internal links. I have it working locally but not sure what's the best way to integrate it

> The only question left is whether this check should be by default or only in `zola check`...
Since we can't catch every anchors, it could fail valid sites since there's no way to turn it off. I do wonder if having links to anchors generated in shortcodes or raw HTML in the markdown is common enough though

Feedback appreciated!

**Comment by marcusklaas** [comment]
That's a tough one. Don't think I have any particularly insightful thoughts here. It will likely be fine in most cases for the reason you state, but having it fail when it shouldn't is particularly annoying..

**Comment by Keats** [comment]
I think let's roll with enabled by default - the checks only happen if a person is using an internal link `@/` structure so they have a way out of it by putting a permalink if needed for now.
