### ISSUE TITLE
Processed images not generated with serve

### ISSUE THREAD

**Issue by marvinhagemeister** [getzola/zola#543]
During development I use the command `zola serve` to fire up the development server. This works perfectly fine, except for processed images. These will error with a `404 - Not Found` message.

As a workaround one can always create them via `zola build`. It'd be nice if the serve command would write those processed images to disk, too.

**Comment by Keats** [comment]
It should be generated and served in `zola serve`, sounds like a bug

**Comment by Keats** [comment]
I just tried with the zola docs that does use processed images and it worked - do you have a small reproduction I can test?

**Comment by Keats** [comment]
@marvinhagemeister ping

**Comment by marvinhagemeister** [comment]
Somehow I can't reproduce this anymore, closing. Thangs for the ping 👍

**Comment by callahad** [comment]
I can reproduce this bug with Zola 0.6.0

Using the [same minimal site](https://github.com/callahad/zola-testcases/tree/master/resize-image-in-template) from #669:

1. `cd resize-image-in-template`
2. `zola serve`
3. Open http://127.0.0.1:1111
4. Edit `content/_index.md`, changing the desired height or width of the image.

Observations:

- The filename is updated correctly, but new images are not generated.
- The 64x64 PNG (`20a70c3e1ed4429f00.png`) remains in `./static/processed_images/` and `./public/processed_images/`
