### ISSUE TITLE
Low quality of resized images

### ISSUE THREAD

**Issue by BojanKogoj** [getzola/zola#546]
Currently, all resized images are JPEG (according to [docs](https://www.getzola.org/documentation/content/image-processing/)), which doesn't really work well with computer-generated images, such as screenshots. There is also no transparency which makes it even worse.

For example, the following image
![orbtk-calculator](https://user-images.githubusercontent.com/634075/49333210-0c5e5b80-f5bb-11e8-918b-d390a9704703.png)
becomes (at 100% quality)
![70659a75198d41ac00](https://user-images.githubusercontent.com/634075/49333207-02d4f380-f5bb-11e8-9cad-81b266a8d942.jpg)

Any way to create PNGs in the future?

**Comment by Keats** [comment]
Looks like it should keep jpeg/png if possible yes.

**Comment by MatteoGgl** [comment]
I'd be willing to try working on this, but beware: I'm a Rust beginner with a day job as a PHP developer.  :smiley: 

I was thinking of a possible implementation in two steps: the `resize_image` function should keep the format of the images it's fed by default, so if I try to process a PNG it'll keep the format. As a second step, we could add an optional argument to `resize_image` that specifies the desired extension, like `ext=jpg`.

Thoughts?

**Comment by Keats** [comment]
Go for it! 
What you said does make sense to me, although I don't know the support of images outside of jpeg in Rust :/

cc @vojtechkral who wrote the original code for feedback as well.

**Comment by MatteoGgl** [comment]
I'll look at the `image` crate and we'll see if something can be done then!

**Comment by vojtechkral** [comment]
`image` AFAIK does support encoding of PNGs, so that sould not be a problem. As for preserving the format, I'm not sure you'd really want to do that. For example, making a `bmp` thumb for a `bmp` image doesn't make much sense to me, you most likely want `png`. Perhaps the best way would be to create jpgs for lossy formats and png for lossless formats.

I think the best way would be to have a `format` option with possible choices `"auto"` (which would do the above), `"png"` and `"jpeg"`, defaulting to `"auto"`. Should not be difficult to implement...

**Comment by BojanKogoj** [comment]
I agree with @vojtechkral 
Having options `jpeg`, `png` and `auto` (with default to auto) would be really nice.

**Comment by vojtechkral** [comment]
Btw. what's with the project rename? :) I must've missed that. Should we also replace pictures of Gutenberg with those of Émile Zola in the documentation? :)

**Comment by Keats** [comment]
Explained here: https://www.vincentprouillet.com/blog/releasing-zola-0-5-0/#a-bit-of-history-and-changing-name-to-zola

No need to change the pictures

**Comment by MatteoGgl** [comment]
@vojtechkral I like this implementation, that's in the same general direction of what I was going for, just more polished :grin:

**Comment by bdjnk** [comment]
The essential problem here is not, so far as I understand it, the encoding, but rather the resize filter. `Gaussian`, which is what is currently used, is producing unexpected blur. For reducing image size, which I believe is the common use case being targeted, `Lanczos3` will almost always produce better results (certainly sharper). Switching should be a one line fix.

**Comment by bdjnk** [comment]
I just ran some tests, and changing the filter doesn't seem to have made a whit of difference, but I could have done it wrong.

**Comment by vojtechkral** [comment]
I created a pull request. The same thumbnail using PNG looks like this:

![d65da6df13fee0b000](https://user-images.githubusercontent.com/424891/50498737-aba03280-0a43-11e9-9f85-790099a74a97.png)

Transparency seems to be preserved as far as I can tell.
