### ISSUE TITLE
Add Cropping function for image manipulation. 

### ISSUE THREAD

**Issue by Muzz** [getzola/zola#548]
Resizing is a great start to image generation, but to truly be useful there will need to be more features added. 

I think the different functions in grav, for image cropping are a good example of the implementations i'd want. Long term it would also be awesome to have image colorization and blurring.
https://learn.getgrav.org/content/media#image-actions

I'm currently trying to port over a site i wrote in grav to Zola, but this will be a stumbling block. (no content, just test content atm) http://hardround.org/home/about
All my images in the header are auto generated from images in the articles. 

Thanks!

**Comment by piedoom** [comment]
[You can get a cropping effect by resizing with fill](https://www.getzola.org/documentation/content/image-processing/#fill) - I think that's what you were referring to?  In any case, +1 to more features.  Colorization/color overlays would be very useful for generating ograph images.

**Comment by Muzz** [comment]
That's only the zoom crop functionality, it doesn't let me arbitrarily crop. And unless I'm mistaken, I can't also resize at the same time, which would be required for making thumbnails.

**Comment by Keats** [comment]
How would the cropping work? The example in https://learn.getgrav.org/content/media#crop-x-y-width-height gives a pretty terrible result and it seems unlikely you want to set the box manually for each image. 
Is there a crate in Rust to pick the most "interesting" crop for the given size?

**Comment by Muzz** [comment]
What you say is unlikely is exactly what i need. It's not unlikely at all to want to modify a thumbnail through short code, it's way way faster to do that than to manually make thumbnails, and in fact is what i was doing in my original site. (facebook, twitter, artstation ect all have tools to allow manual editing of thumbnails)

If you have an image you want to make a thumbnail of often you want to focus on say a face or other feature. if it's a picture of a person, i have no choice but end up with an unfortunate crotch close up if all i have is a zoom crop.

**Comment by Muzz** [comment]
In terms of interesting crates that could give an interesting crop. I know that facebook and twitter use face detection algorithms, to make sure thumbnails by default focus on the face. A quick cursory look gives me this library. 

https://github.com/atomashpolskiy/rustface

But really i don't think that's that necessary, but could be fun!

**Comment by Keats** [comment]
cc @vojtechkral that has done 100% of the work on image processing

**Comment by vojtechkral** [comment]
I recall Hugo uses [smartcrop](https://github.com/jwagner/smartcrop.js) (there's a [Go port](https://github.com/muesli/smartcrop)). It actually looks quite neat, a Rust equivalent would be nice (but personally I'd have to do some soul searching to see if I have the time to do it).

Other than that, this question is pretty vague and I'm not sure I follow on what is actually being requested here... Also I'm not sure how general should Zola be in terms of image processing, feature-completeness is nice but feature-creep is a thing too...

If we really wanted to go all in for general image processing, I believe there's a Rust binding to ImageMagick/MagickWand which I believe can take arbitrary imagemagick commands in strings (unless I recall wrong).

**Comment by Keats** [comment]
> I recall Hugo uses smartcrop (there's a Go port). It actually looks quite neat, a Rust equivalent would be nice (but personally I'd have to do some soul searching to see if I have the time to do it).

I did something similar in Python, it isn't too hard.

I agree however that we need to scope well what features we want to add with image manipulation (another one being https://github.com/getzola/zola/issues/632) to avoid feature creep
