### ISSUE TITLE
Multiple markdown content blocks/sections per page

### ISSUE THREAD

**Issue by happenslol** [getzola/zola#552]
I'm currently making/remaking a page using zola, consisting of multiple static pages as well as a blog. The blog pages are all zola `page`s rendered from markdown files, while for the static pages there are empty markdown files in the `content` directory, containing only the template path in the frontmatter. Consequently, the content for the static pages is entirely contained within the html templates.

Now, I think one of the plus points of static site generators is that you can basically outsource all your content to markdown, while the templates just contain representational information. My static pages consist of more than just rendered markdown though, and the text content is split up over several sections and elements, which makes it impossible to use markdown for these (since the markdown would just get rendered out as one block of consecutive paragraphs).

The only idea I've had to somehow get around this would be to define my sections in the `[extra]` section of the frontmatter, like this:

```toml
template = "static_page_1.html"

[extra]
section1 = """
This is one *content* __section__!
"""
section2 = """
Another section goes ~~here~~!
"""
```

And then rendering these out as markdown manually in my html:

```html
<section class="section1">
    {{ page.extra.section1 | markdown(inline=true) }}
</section>
<section class="section2">
    {{ page.extra.section2 | markdown(inline=true) }}
</section>
```

This doesn't really feel idiomatic to me though, as I'm just abusing the extra fields. (And I wouldn't get markdown highlighting/preview in any editors, either.) I think a good way to handle this would be to provide a way of defining multiple "blocks" of content in `page` markdown files, by letting the user add multiple front matter sections:

```
+++
template = "some_template.html"
+++

Everything that goes here gets rendered out as normal,
and if a user doesn't do anything else, he wouldn't notice the feature.

+++
block = "section1"
+++

Everything that goes here would be in
page.blocks.section1, but also rendered out as markdown.
```

Is there another way to do this that I'm not seeing, or is this not something you're looking to provide? I think this would be a sensible feature, as the case of applications with static pages as well as a blog often comes up.

**Comment by Keats** [comment]
Would using shortcodes with a body solve the issue? They currently don't render markdown but you could call the markdown filter manually in the shortcode.

I ran into the same thing when I was still using Hugo but the problem I had was each page had its own design elements, some not really making sense in markdown like a HTML div with 3 columns of advantages or tabs.

**Comment by happenslol** [comment]
That's another solution, but that would require me to pull out every design element/component into an additional file, making my html very fragmented.

And I do understand what you mean, but I think it would make a lot of sense if it was possible to pull out arbitrary blocks of content, even in a scenario with something like tabs or columns. Specifically for that, it would be possible to allow arrays of blocks that could then be iterated over.

In general though, I think it's about giving developers the tools to pull out as much content as possible, so that marketing texts and descriptions can be switched out and edited without touching the actual code. None of the static site generators I've used are very friendly in this regard, most of them do not even have workaround like using the `extra` section in zola (e.g. hugo, as you mentioned). I just thought this could be a nice feature to have, but I would understand if you think this overcomplicates the markdown "api".

**Comment by happenslol** [comment]
Maybe as a sort of disclaimer: I'd totally be up for making a PR for this. I've already looked at the relevant parts of the project and I think I have a good idea of how this can be implemented.
The workaround I mentioned in my first post works for me though, so I wouldn't want to do any extra work if you don't think this is a good idea in the end.

**Comment by Keats** [comment]
I'm not against adding this feature (maybe not in this form I don't know).

I really want to focus on [i18n](https://zola.discourse.group/t/rfc-i18n/13) first though so I will probably freeze new features until this is implemented since otherwise it's never going to be done. It won't take too much time hopefully.

**Comment by happenslol** [comment]
I see, makes sense. I'll keep using the workaround for now then, and check back later =)

**Comment by xpe** [comment]
I see value here, too.

@happenslol Are you still interested in this?

**Comment by Inspirateur** [comment]
Up, please consider this ! I'm making a static site for a friend who is not HTML literate, 
and breaking down the content of 1 HTML page into little .md files that they can edit would be really useful !

**Comment by charlot-shaw** [comment]
I also am working on hacking my way around this issue. Would love to see this supported.

**Comment by Leandros** [comment]
Same here, this would be incredibly helpful for some more complex designs.

**Comment by JonHurst** [comment]
Was any progress made on this? If not I might have a go at implementing it myself.

I was thinking of a slightly simpler syntax than the OP:

```
+++
template = "some_template.html"
shard_marker = "+*+"
+++

Everything that goes here gets rendered out as normal.
If shard_marker is not specified everything else gets rendered as normal too. 

If a user doesn't opt in, they wouldn't notice the feature.

+*+ foo

Everything that goes here would be in
page.shards.foo[0], but also rendered out as markdown.

+*+ foo

Everything that goes here would be in
page.shards.foo[1], but also rendered out as markdown.

+*+ bar

Everything that goes here would be in
page.shards.bar[0], but also rendered out as markdown.

```

A default shard_marker could also be specified in the config file so you don't have to add it to the header of every page.

I'm open to a different name for "shard"; "block" seems to me to have too much meaning in HTML to be appropriate, and similarly "section" has too much meaning to zola itself.

Any thoughts?

**Comment by JonHurst** [comment]
[Rough implementation here]( https://github.com/JonHurst/zola/tree/shards)

**Comment by Keats** [comment]
Would you still get the full page rendered without the "shards" markers?

**Comment by JonHurst** [comment]
Yes. Without the `shard_marker="..."` in the front matter, the code path is exactly as it was. I've written up a more formal proposal at [https://zola.discourse.group/t/proposal-for-sharding-of-markdown-content/2664](https://zola.discourse.group/t/proposal-for-sharding-of-markdown-content/2664).
