### ISSUE TITLE
zola missing files on alpine:3.8 in docker, won't run

### ISSUE THREAD

**Issue by focusaurus** [getzola/zola#553]
# Bug Report

## Environment

Zola version: 0.5.0

## Expected Behavior
zola should run normally 

## Current Behavior
Zola won't run at all. Here's the shell output:

```sh
# /usr/local/bin/zola --help
sh: /usr/local/bin/zola: not found
/ 
```

## Step to reproduce

I found this trying to run zola inside a docker container built from the `alpine:3.8` base image. I can **not** reproduce in `debian:9.6` - zola works fine there. So something must be missing in `alpine:3.8` that zola needs, but I don't know exactly what that might be.

Here's a script to reproduce with docker:

```sh
dockerfile=$(cat <<'EOF'
from alpine:3.8
RUN wget -q -O - \
"https://github.com/getzola/zola/releases/download/v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz" \
| tar xzf - -C /usr/local/bin
EOF
)
echo "${dockerfile}" | docker build --tag zola -
docker run zola sh
```

Once in the container, although the output of `file /usr/local/bin/zola` looks reasonable, the linking seems busted and it won't run.

**Comment by Keats** [comment]
In theory, the archive should be self-contained. It might be `reqwest` needing openssl maybe? I don't really have another idea though, so I hope it's that :D

Is it not possible to get some log on what is happening?

**Comment by focusaurus** [comment]
I can get logs but would need the specific commands to run to generate them. Your hunch matches my understanding that I thought rust binaries were fully statically linked and wouldn't expect this type of error, but I think your hunch may be correct.

Here's [a gist with the ldd output](https://gist.github.com/focusaurus/46a5e87f930bfb4524cce6d10d6fd768)

**Comment by focusaurus** [comment]
Oh the other thing it could be is alpine is build upon musl lib c I think and sometimes that causes trouble.

**Comment by Keats** [comment]
almost everything is statically linked in Rust, openssl is the exception mostly https://github.com/seanmonstar/reqwest#requirements

> Oh the other thing it could be is alpine is build upon musl lib c I think and sometimes that causes trouble.

That is very possible. I remember people having issues compiling https://github.com/compass-rs/sass-rs with musl: https://github.com/compass-rs/sass-rs/issues/30

**Comment by Keats** [comment]
@focusaurus did you manage to make it work?

**Comment by focusaurus** [comment]
Not sure exactly what to try but I tried installing openssl and openssl-dev and that doesn't seem to fix it.

```sh
╰○ drun alpine sh
/ # apk add openssl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libcrypto1.0 (1.0.2q-r0)
(2/3) Installing libssl1.0 (1.0.2q-r0)
(3/3) Installing openssl (1.0.2q-r0)
Executing busybox-1.28.4-r1.trigger
OK: 8 MiB in 16 packages
/ # export ZOLA_VERSION=0.5.0
/ # wget -q -O - \
>   "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
>   | tar xzf - -C /usr/local/bin \
>   && chmod 755 /usr/local/bin/zola
/ # /usr/local/bin/zola --help
sh: /usr/local/bin/zola: not found
/ # apk add openssl-dev
(1/3) Installing pkgconf (1.5.3-r0)
(2/3) Installing zlib-dev (1.2.11-r1)
(3/3) Installing openssl-dev (1.0.2q-r0)
Executing busybox-1.28.4-r1.trigger
OK: 26 MiB in 19 packages
/ # /usr/local/bin/zola --help
sh: /usr/local/bin/zola: not found
```

**Comment by greizgh** [comment]
When using the standard library, rust will always dynamically link to the local libc (see [the rust2018 edition guide](https://rust-lang-nursery.github.io/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html)).

Building zola for a musl target will indeed require openssl.
I used https://github.com/messense/rust-musl-cross (the readme mentions adding the build to travis, which might be useful later):
```
docker pull messense/rust-musl-cross:x86_64-musl
alias rust-musl-builder='docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:x86_64-musl'
rust-musl-builder cargo build --release
```
However, I still ran into the compass-rs/sass-rs#30 issue.

**Comment by Keats** [comment]
Anyone with musl experience has an idea why https://github.com/compass-rs/sass-rs/issues/30 is an issue? libsass can be compiled on musl so that's likely an issue on the Rust side.

**Comment by Keats** [comment]
I believe this is cause by the upstream sass-rs issue, closing this one in the meantime

**Comment by leiserfg** [comment]
I'm making my own docker image:
https://hub.docker.com/r/leiserfg/zola
I'm using https://github.com/larsks/dockerize and the `zola` binary from arch.
