### ISSUE TITLE
Livereload latency

### ISSUE THREAD

**Issue by alexkehayias** [getzola/zola#554]
## Summary
Just getting started, but in setting up a new site I noticed livereload can take 2+ seconds before triggering the browser refresh. The output of `zola serve` says the time to rebuild after a change to `index.html` took ~1ms so it seems like the livereload waits a long time before triggering the browser refresh. Is there a way to configure it to pick up the changes faster? 

## Proposed solution
Document (or potentially introduce) a way to decrease the latency between file changes and a browser refresh.

**Comment by Keats** [comment]
There is https://github.com/getzola/zola/blob/master/src/cmd/serve.rs#L179 but it is more about the filesystem notification, maybe it's the reason it feels slow? We can try with 1 and see if anything bad happens.

**Comment by alexkehayias** [comment]
Yes I think that might be it. My frame of reference is `hugo` which uses the `fsnotify` package to do livereload. Digging in a bit more, `hugo` sets up the file watcher with an interval of 1 second https://github.com/gohugoio/hugo/blob/7829474088f835251f04caa1121d47e35fe89f7e/commands/hugo.go#L706. What do you think about changing it to 1s or making it configurable?

**Comment by Keats** [comment]
If you can build zola from source, you can try now. Otherwise I'll  probably try myself with 1 second and if it works well set it to 1 from the next release on.
