### ISSUE TITLE
Allow to use public as a git submodule

### ISSUE THREAD

**Issue by barlog-m** [getzola/zola#560]
I want to deploy built site on github pages as i read in [Hugo documentation](https://gohugo.io/hosting-and-deployment/hosting-on-github/#github-user-or-organization-pages)

Just use `public` directory as git submodule. But zola on build completely recreate public directory, it's destroy `public/.git` directory

May be it better to not to recreate public directory, just delete everything what not a git files?

**Comment by Keats** [comment]
I'm not a big fan of the approach on the Hugo docs, too manual for my taste.
The recommended way is https://www.getzola.org/documentation/deployment/github-pages/ for Zola.

For the` public` deletion, I am not sure as it makes something more complex but not much gain.

**Comment by barlog-m** [comment]
Thank you for your answer.

It is good to choose simple way, that way always contains less bugs.
But use Travis CI for deployment personal blog is too complex, as for me.

**Comment by Keats** [comment]
Agreed, I use [netlify](https://www.getzola.org/documentation/deployment/netlify/#automatic-deploys-for-zola) myself and it is as using as having a file in the root dir: https://github.com/getzola/zola/blob/master/netlify.toml

It will be even easier once netlify updates their docker image and zola is built-in netlify

**Comment by Keats** [comment]
Closing in favour of https://github.com/getzola/zola/issues/765 which is the same thing I think.
