### ISSUE TITLE
sort_by = "date" does not seem to work with with transparent sections

### ISSUE THREAD

**Issue by jonas-schievink** [getzola/zola#561]
# Bug Report

## Environment

Zola version: zola 0.5.1

## Expected Behavior
Having a single section with `transparent = true` and `sort_by = "date"` should sort all pages in that section by their date, with the most recent page at the top.

According to the docs about [sorting](https://www.getzola.org/documentation/content/section/#sorting-pages):
> This will sort all pages by their date field, from the most recent (at the top of the list) to the oldest (at the bottom of the list).

## Current Behavior
`sort_by` seems to be ignored, the pages are sorted somewhat randomly and get pulled to the top when touched.

## Step to reproduce
Make a section with `transparent = true` and `sort_by = "date"`. Put 2 pages with dates in there. Change the dates while `zola serve` is running.

**Comment by jonas-schievink** [comment]
~~Nevermind, the theme has `| reverse`d the ordering. Sorry for the noise :/~~

**Comment by jonas-schievink** [comment]
This does actually seem to be a real bug. The pages are ordered incorrectly ~~by their folder names~~ (depends on edits made while zola is running?) instead of their dates. Reproduction: https://github.com/jonas-schievink/zolarepro

To reproduce:
* `zola serve`
* "Post 1" is at the bottom of the page
* Edit the date of "Post 1" to be `2019-01-30`
* "Post 1" is now at the top of the page
* Edit the date of "Post 1" to be `2019-01-20` again
* "Post 1" is still at the top of the page, while it should have gone back to the bottom

**Comment by Keats** [comment]
This looks like a rebuild bug. If you restart `zola serve` it will display the correct order

**Comment by Keats** [comment]
@jonas-schievink are you interested in debugging this one or should I pick it up later this week?

**Comment by jonas-schievink** [comment]
@Keats I don't think I'll find the time to fix this, so please go ahead

**Comment by Keats** [comment]
I think the issue is that in your sample is that the index section doesn't have a sort setup, only the `post` one does. 
Passing pages to parent of transparent sections is done before sorting so when sorting sections, it sees that the index section doesn't have a sort setup and thus skips it. 
Creating a base `_index.md` file with:

```
+++
sort_by = "date"
+++
```
has the behaviour you want. You can drop the sorting in `post/_index.md` if you don't want to display that page too

**Comment by jonas-schievink** [comment]
Yep, that fixes it, thanks! Would be nice to make `sort_by` work in both (or at least report an error if it's in the wrong place).

**Comment by Keats** [comment]
I don't think it would make sense for a child section to be able to override its parent. 
I don't think it should be an error either, it is a weird but valid usage.

**Comment by jonas-schievink** [comment]
I thought the combination of `transparent` and `sort_by` at the same level practically ignores the `sort_by`? Shouldn't that be an error?

**Comment by Keats** [comment]
Not really, you can still render that section if you want so `sort_by` is still respected. The only thing `transparent` does is pass the pages to the parent section in addition.
