### ISSUE TITLE
Be able to split sitemaps

### ISSUE THREAD

**Issue by corentin-cres** [getzola/zola#562]
In case of large site generation (100k pages), sitemaps get huge and robots (for example, Google crawler) is not able to parse it all.

From the [Google guidelines](https://support.google.com/webmasters/answer/183668?hl=en),

> All formats limit a single sitemap to 50MB (uncompressed) and 50,000 URLs. If you have a larger file or more URLs, you will have to break your list into multiple sitemaps. You can optionally create a sitemap index file (a file that points to a list of sitemaps) and submit that single index file to Google.

It would be great that Zola limits the maximum number of URLs in a single sitemap (for example, defaulted to 20k) and splits the sitemap in multiple sitemaps if we reach this value ; and maybe be able to configure this value somewhere.

-----------

Another solution would be to give the `pages`, `sections`, `tags`, `categories` (https://www.getzola.org/documentation/templates/sitemap/) to any page named `sitemap*.xml` (with the wildcard, and not only `sitemap.xml`), so that we can implement some logic ourselves to be able to count the number of URLs displayed in each sitemap.
This solution has the advantage to allow custom logic, and not only the maximum number of URLs, to be implemented. However, this logic has to be written for every project, and is not implemented by default.

**Comment by Keats** [comment]
I didn't know this was a thing :o

I'm wondering if there is some overlap with https://github.com/getzola/zola/issues/365 and your second solution.
The logic to implement that in Zola automatically would be fairly simple I think and has the advantage of doing the right thing automatically.

**Comment by corentin-cres** [comment]
Thanks for your reply !

Agreed, I think the first solution is better too.
Should I create "New issue" from this post or something ?

**Comment by Keats** [comment]
Do you mean to create a pull request? Fork the repository, select the `next` branch and start adding some code

**Comment by JadedBlueEyes** [comment]
Can I just add, whilst we’re here, that the sitemap should be automatically added to (at least the default) robots.txt file.
https://www.sitemaps.org/protocol.html#submit_robots

**Comment by Keats** [comment]
Ah, didn't know that. It makes the sitemap splitting a bit more complex then

**Comment by JadedBlueEyes** [comment]
No, just the root one that links to the others. Just add `Sitemap: {{ get_url(path="/sitemap.xml") }}` to the start of the default robots.txt template, or something more robust probably.

**Comment by paulcmal** [comment]
> I'm wondering if there is some overlap with #365 and your second solution.

That's a very interesting usecase for custom output formats, thanks for bringing it up! So the obvious way is to have your index (with an `xml` template) render a sitemap pointing to each section's own sitemap, and splitting (actually easy thanks to content pagination support :sun_with_face:) these section's sitemaps when they're too big. Then of course if you want to get fancy you can imagine some more complex logic but i think that would do the trick.

If somebody wants to document this use-case in the [draft](https://lite1.infini.fr/p/gutenberg-cof) for custom output formats i've recently resumed working on, feel free to :)

BTW thanks for bringing this issue up, it's a really interesting stress case that most of us with small websites will remain unaware of :)

**Comment by Keats** [comment]
This is implemented in the `next` branch, as well as the sitemap url in `robots.txt`.

I am not really sure how custom output formats would handle that though? What if you have 100 sections with 350 pages each let's say? You need to know all the possibles links about the site and that includes multi-lingual pages/sections, taxonomies etc. We can continue the discussion on the discourse forum
