### ISSUE TITLE
Literate Programming Support

### ISSUE THREAD

**Issue by remexre** [getzola/zola#563]
It'd be nice to support literate programming in some form, something like:

    +++
    [literate]
    line = "--$"
    block = ["{-$", "$-}"]
    +++
    
    Blah blah this goes above the code
    
    ```haskell
    --$ First some convenience imports.
    import Foo (Bar(..), frob)
    import Baz (Quux(..))
    
    --$ One may think of frobbing the bars using quuxes; bazzing them is important
    --$ to do first, because of Frobenius' Collorary to Cooper's Theorem.
    performXyzzification :: Traversable t => t Quux -> Quux
    performXyzzification = undefined -- you get the point
    ```
    
    Blah blah this goes below the code

Ideally this would generate some HTML such that it'd be easy to write CSS that would either display the code and comments aligned side-by-side or stacked, alternating between code and prose (like [here](https://yager.io/CPU/CPU1.html)). I think it should be possible to do the appropriate styling with flexbox and `<div class="literate-code">` vs. `<div class="literate-prose">`, but I haven't tried it.

**Comment by Keats** [comment]
That does look like it would need a completely custom markdown renderer :/

Probably unlikely to happen anytime soon

**Comment by remexre** [comment]
Hm, I might try adding an "external command as a filter" and see if I can
implement this like that.

**Comment by remexre** [comment]
okay, external command implementation is in as https://github.com/remexre/zola/commit/11ff0a12b8d58f24414aef0a5356e550eb9becc0; as noted in the commit message, testing for this is blocked on https://github.com/getzola/zola/issues/879.

does this look OK to you, though? (if so, I'll add docs+tests)

---


**EDIT**: Okay, I can build in an Alpine docker ctr, and it seems to work there.

**Comment by Keats** [comment]
Not going to happen. I've looked at tree-sitter again recently but sadly still too few syntaxes and adding one is not trivial :(
