### ISSUE TITLE
Deploy to github pages.

### ISSUE THREAD

**Issue by ghost** [getzola/zola#564]
# Documentation issue

## Summary
What is the issue? Is the documentation unclear? Is it missing information?
Current deploy instructions for github pages are quite limited since the tutorial on the official page
only covers the usage of TravisCI, I can see a problem in here because we depend on another
service to make our pages public and currently there's no other documented way to export our
projects, also some themes load improperly when published to gh-pages (view hyde theme for example).

## Proposed solution
Just as an Idea, some static site generators have included commands to export their builds to
github pages or maybe propose an alternative way for users that cannot / don't want to use TravisCI services

Thanks in advance :)

**Comment by RealOrangeOne** [comment]
The GitHub Pages instructions only tell you how to push the `public/` directory to the `gh-pages` branch, they could easily be adapted for another CI, or just run manually from the shell. 

Adding commands to the generator itself would be unnecessary, as they're very specific to how GitHub Pages works. You just take the `public/` directory, and push it to a new branch.

**Comment by ghost** [comment]
It seems that my ideas were flawed, maybe I got used to the other tools :sweat_smile: , though I think a PR explaining how to deploy "manually" to the `gh-pages` branch could be useful, thanks for your input :)

**Comment by Keats** [comment]
I would take a PR for that!

**Comment by ghost** [comment]
I will work on clear instructions on how to deploy manually in these days. :+1:

**Comment by Keats** [comment]
Thanks! 
Closing this issue in the meantime as it is a bit different from docs
