### ISSUE TITLE
Footnote in title don't work as expected

### ISSUE THREAD

**Issue by peng1999** [getzola/zola#569]
# Bug Report
Footnote link in header will appear prior to header.

## Environment
``` bash
❯ uname -srmo
Linux 4.14.90-1-MANJARO x86_64 GNU/Linux
❯ zola --version
zola 0.5.1
```

## Step to reproduce
content/test.md:
```markdown
+++
template = "page.html"
+++
# header[^1]

another[^2] footnote.

[^1]: footnote one
[^2]: footnote two
```
template/page.md:
```jinja
{{ page.content | safe }}
```
build command: `zola build`

## Expected Behavior
Output should be same as what `pulldown-cmark` out:
```html
<h1>header<sup class="footnote-reference"><a href="#1">1</a></sup></h1>
<p>another<sup class="footnote-reference"><a href="#2">2</a></sup> footnote.</p>
<div class="footnote-definition" id="1"><sup class="footnote-definition-label">1</sup>
<p>footnote one
<sup class="footnote-reference"><a href="#2">2</a></sup>: footnote two</p>
</div>
```

## Current Behavior
```html
<sup class="footnote-reference"><a href="#1">1</a></sup><h1 id="header">header</h1>
<p>another<sup class="footnote-reference"><a href="#2">2</a></sup> footnote.</p>
<div class="footnote-definition" id="1"><sup class="footnote-definition-label">1</sup>
<p>footnote one
<sup class="footnote-reference"><a href="#2">2</a></sup>: footnote two</p>
</div>
```

**Comment by Keats** [comment]
Seems that the `sup` gets added before even the `h1`? That looks like it's because the markdown renderer does not handle Footnotes in headers currently, shouldn't be too hard to fix if someone wants to try!

**Comment by peng1999** [comment]
I studyed the html generating code and found that it holds up everything in header until header ends. But IMO it is not scalable and don't follow DRY rules. If we want full CommonMark support, we must handle every tags (links, footnotes, emphasize, etc.) inside header ourselves. It's completely a duplication of `pulldown-cmark`'s html renderer.

I'm trying refactoring `rendering::markdown::markdown_to_html` to avoid delaying header content being rendered.

**Comment by Keats** [comment]
I don't think it's possible, Zola lets you insert anchors at the beginning or at the end of the header. You can't insert it at the beginning of the HTML if you haven't read the header yet since you need to make up an anchor.

i might be wrong though!

**Comment by peng1999** [comment]
I'm still investigating the code. But is it possible to keep the location of anchors and render them in a extra pass, like `render_shortcodes`?

**Comment by Keats** [comment]
It would be a bit tricky, you need to insert HTML into HTML in a post-processing phase but then you might have some titles in a code block for example where you don't want to insert an anchor and without the pulldown_cmark parser you don't really know whether you can or not,

**Comment by peng1999** [comment]
`pulldown-cmark`'s current pull api is very limited. I've tried implementing missing markup in headers, but footnote is rather tricky. The pull api desn't provide footnote number so we should handle every footnote(inside and outside headers) ourselves to get it right.

**Comment by Keats** [comment]
They are working on improving pulldown-cmark, maybe open an issue there to explain what is missing?

**Comment by peng1999** [comment]
In `pulldown-cmark`'s [README](https://github.com/raphlinus/pulldown-cmark#using-rust-idiomatically):
> Pull parsers are at heart an iterator of events (start and end tags, text, and other bits and pieces). The parser data structure implements the Rust Iterator trait directly, and Event is an enum. Thus, you can use the full power and expressivity of Rust's iterator infrastructure, including for loops and map (as in the examples above), collecting the events into a vector (for recording, playback, and manipulation), and more.

Maybe we can collect the events into a `Vec` and insert the anchors?

**Comment by Keats** [comment]
If that works sure. Do you want to continue on your PR or do a separate one?

**Comment by peng1999** [comment]
I think we can have #578 merged first and I'll do a separate PR for further work.

**Comment by peng1999** [comment]
@Keats I'm still working on this and a piece of the code can be a bit shorter if I use [`itertools::join`](https://docs.rs/itertools/0.8/itertools/trait.Itertools.html#method.join). But is it ok to add this new dependency, or I just keep my own implementation?

**Comment by Keats** [comment]
Is https://doc.rust-lang.org/std/slice/trait.SliceConcatExt.html not doing the job?

**Comment by peng1999** [comment]
No. `SliceConcatExt` only implements `array`s, but `itertools::join` can work on iterators. I can collect iterator to use `SliceConcatExt`, but this is an unecessary cost.

Currently I write like this:

```rust
fn get_text(parser_slice: &[Event]) -> String {
    let mut title = String::new();

    for event in parser_slice.iter() {
        if let Event::Text(text) = event {
            title += text;
        }
    }

    title
}
```
With `itertoos::Itertools::join` I can write something like this:
```rust
parser_slice.iter().map(|event| {
    if let Event::Text(text) = event { text } else { "" }
}).join()
```
and get rid of a separate function.

**Comment by Keats** [comment]
Hmm doesn't seem worth it to pull a dependency considering how small it is

**Comment by peng1999** [comment]
This should be marked as `done` since #581 has been merged.
