### ISSUE TITLE
404 page provided by the theme is not used

### ISSUE THREAD

**Issue by Areiser** [getzola/zola#571]
# Bug Report

## Environment

Zola version: zola 0.5.1

## Expected Behavior
I wanted to add the same 404 error page to the hyde theme that the original jekyll theme has. After creating the correct template in the hyde theme (it works for the theme itself, see https://github.com/Areiser/hyde) I used this theme for my blog.

I would expect the 404 page from the theme to be used unless I create my own one in the local templates folder

## Current Behavior
The default 404 page is used

## Step to reproduce
Create a zola page that uses the hyde theme from https://github.com/Areiser/hyde and call a broken link. Compare the page to a broken link when directly running https://github.com/Areiser/hyde

**Comment by Keats** [comment]
Thanks for the report, should be an easy fix if anyone wants to get started with Zola.
