### ISSUE TITLE
post.permalink points to 127.0.0.1:1111 instead of base_url.

### ISSUE THREAD

**Issue by alishir** [getzola/zola#573]
# Bug Report

## Environment
Ubuntu 16.04

Zola version: 0.5.1

## Expected Behavior
`{{ post.permalink }}` should use `base_url`.

## Current Behavior
`{{ post.permalink }}` points to `http://127.0.0.1:1111/`.

## Step to reproduce
You can see the problem at this page: https://alishir.github.io/blog/fa/ if you click on the link it points to local host.
The source file of that section is:
```
{% extends "blog_fa.html" %}

{% block content %} 
{% for post in section.pages %}
	<h1><a href="{{ post.permalink }}">{{ post.title }}</a></h1>
{% endfor %}
{% endblock content %}

```

**Comment by Keats** [comment]
It points me to to https://alishir.github.io/blog/fa/salam-post/
`base_url` is only replaced when running `zola serve`, are you you are looking at the right tab? Happens to me all the time...

**Comment by alishir** [comment]
I just opened that url in private browsing mode and it is correct. I'm
sorry I test it multiple times before submitting the issue.

**Comment by Keats** [comment]
No worries, it happens to me all the time
