### ISSUE TITLE
Support for Incremental Builds?

### ISSUE THREAD

**Issue by ryanmcgrath** [getzola/zola#574]
# Documentation issue
It's not immediately clear that Zola blows away directory contents on build. I'm unclear why this is necessary.

## Summary
You really, really should state somewhere that the output directory is deleted or pruned on each build. Or just don't do this, and rsync it over to the target directory or something instead.

## Proposed solution
Some reasoning as to why this is the default behavior would be welcome. Otherwise, see summary above.

**Comment by polyzen** [comment]
Perhaps this should be renamed to request incremental builds.

**Comment by ryanmcgrath** [comment]
Noted, yeah. My annoyed state from losing some files wore off and I can see why that previous title was bad.

Changed~

**Comment by Keats** [comment]
The main reason as mentioned is that Zola doesn't have incremental builds so without clearing the folder you would end up with things deleted in the content but still in your public folder. I will add a note to the docs to mention what happens.

Incremental build is not on the roadmap at all right now, how big is your site that it is needed?

**Comment by ryanmcgrath** [comment]
I think a note would do enough right now, yeah.

Site I was using it on wasn't so big I needed it, moreso that I didn't think it'd blow away a directory by specifying an existing one as the output directory for the build command. A note about destructive behavior might be all that's needed here.

(Love the project and your other crates, by the way!)

**Comment by Keats** [comment]
I have added a note https://github.com/getzola/zola/pull/567/commits/0f0304d7edb8f6d942789835c4c2f8b43b921d6b and in the CLI help. Just remembered I need to add it to `serve` as well.

**Comment by ryanmcgrath** [comment]
Cool! Should this be closed in an effort to reduce clutter, or kept open to track potential interest? Dunno what your protocol is here...

**Comment by Keats** [comment]
The feature is not implemented so let's leave it open for people to comment on

**Comment by haheute** [comment]
Maybe a nice feature... With many photos, I could rsync only newer files, then..

**Comment by niklasf** [comment]
Meanwhile build times with many/large static assets can be improved considerably by using a filesystem that supports CoW, like btrfs. (For example 7 GB in 20948 mostly static files, 1 minute on ext4, 1 second on btrfs).

**Comment by Keats** [comment]
It's not going to be supported in Zola itself.
It's very hard to know what changed without rendering everything due to the various Tera functions available in templates.
