### ISSUE TITLE
`load_data` in shortcode crashes the daemon

### ISSUE THREAD

**Issue by fbruetting** [getzola/zola#582]
# Bug Report

## Environment

Zola version: v0.5.0

## Current Behavior
When I create a shortcode with `{% set data = load_data(path="xyz.csv") %}` , the daemon handles it fine when it is already running. But as soon as I start the daemon with that content, it instantly crashes:
```
$ ./zola serve
Building site...
Error: Failed to render content of /var/home/*…*/content/repertoire/_index.md
Reason: Failed to render repertoire shortcode
Reason: Failed to render 'shortcodes/repertoire.html'
Reason: Global function 'load_data' not found
```

**Comment by Keats** [comment]
Looks like `load_data` should be a early Tera function, that's an easy fix. Thanks for the report!

**Comment by Keats** [comment]
It should be fixed in the `next` branch if you want to try it
