### ISSUE TITLE
Not rendering content inside `__tera_context`

### ISSUE THREAD

**Issue by fbruetting** [getzola/zola#583]
# Bug Report

## Environment

Zola version: v0.5.0

## Expected Behavior
This command should (in my opinion) give a *compact* overview of the available data. As the page content is already visible, I don’t think that this should be rendered (superfluously) inside the generated structure.

## Current Behavior
Inside the produced output, the whole page content is contained, so we see the page content (from the generated `__tera_context` output) embedded into the regular page content. I don’t think that this is useful, as for bigger pages, the overview gets lost. Additionally, when the page gets reloaded, this whole thing works recursively and renders the whole content a third/fourth/… time inside the page. A better way could be to just omit the rendered page content inside the `__tera_context` structure.

**Comment by Keats** [comment]
`__tera_context` is a [Tera](https://github.com/Keats/tera/) feature, it doesn't know anything about Zola

**Comment by fbruetting** [comment]
Is there some way to at least avoid recursion?

**Comment by Keats** [comment]
I don't think it will be possible no

**Comment by Keats** [comment]
Closing this as it isn't a Zola issue but a Tera one
