### ISSUE TITLE
Multiple footnotes do not work.

### ISSUE THREAD

**Issue by shalzz** [getzola/zola#585]
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior
More than one footnotes should work.

## Current Behavior
Only the first footnote works, i.e. links and formats properly

## Step to reproduce
Changing the even theme content/markdown-overview.md to something like this:
```md
Testing every `elements` you can find in [CommonMark](http://commonmark.org).
<!-- more -->

Quisque viverra a eros id auctor.[^1]
Proin id nibh ut nisl dignissim[^2]
pellentesque et ac mi. Nullam mattis urna quis consequat bibendum. Donec pretium dui elit, a semper purus tristique et. Mauris euismod nisl eu vehicula facilisis. Maecenas facilisis non massa non scelerisque. Integer malesuada cursus erat eu viverra. Duis ligula mi, eleifend vel justo id, laoreet porttitor ex. Etiam ultricies lacus lorem, sed aliquam nulla blandit in. Maecenas vel facilisis neque, vitae fringilla eros. In justo nibh, pellentesque sed faucibus nec, varius sit amet risus.

[^1]: footnote 1
[^2]: footnote 2
```

Gives this output: https://public-nvv5nztcu.now.sh/markdown-overview/#2

Here only the first footnote links and is formatted properly. Also AFAIK footnotes should automatically appear at the end of the markdown not where you have the links defined and should have a back link?

**Comment by Keats** [comment]
cc @peng1999 that is currently doing some work on the footnotes (https://github.com/getzola/zola/pull/581)

**Comment by peng1999** [comment]
It's irrelevant to zola. `pulldown-cmark` will give the same result. And you can just add a blank line between the two footnote definitions to fix this.

Maybe you can open an issue in `pulldown-cmark` if you think this behaviour is not right.

**Comment by Keats** [comment]
Had a check as well and it confirm what @peng1999 said. If it is a bug then it is a bug upstream
