### ISSUE TITLE
current_path and current_url not available in 404.html

### ISSUE THREAD

**Issue by shalzz** [getzola/zola#586]
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior
`current_url` and `current_path` should be available in 404.html.

## Current Behavior
According to this [documentation][1] `current_url` and `current_path` should be available in every template excluding RSS and sitemap.xml. Which is not true for 404.html

## Step to reproduce
Use `{{ current_url }}` in a 404.html template

[1]: https://www.getzola.org/documentation/templates/overview/

**Comment by Keats** [comment]
The docs should be updated, Zola has no way of knowing the `current_url`/`current_path` in advance and they shouldn't be set to arbitrary values like in #587 imo

**Comment by andreacfromtheapp** [comment]
@Keats would it be possible to have at least the engine ignore `404.html` completely when it comes to this?

**Comment by Keats** [comment]
What do you mean? Ignore the rendering errors?

**Comment by andreacfromtheapp** [comment]
> What do you mean? Ignore the rendering errors?

I'm not a programmer nor an expert, but what I mean is to skip 404.html entirely (to not have the error at all). Something along these lines:

IF the current_url error for 404.html is thrown by a function checking all templates for current_url validity, then it should be possible to entirely skip the check for the `404.html` template. Not sure how the code works, but assuming each template is fed to this check a condition would solve this issue while retaining the underlying logic and no need to apply the proposed solution by @shalzz 

pseudo-code:

```
fn check_template(current_url, template) {
if template == 404.html; then pass; fi
checks here
}
```

I hope this makes sense.

**Comment by Keats** [comment]
If you don't have a 404.html file in the templates folder we won't render it already

**Comment by andreacfromtheapp** [comment]
> If you don't have a 404.html file in the templates folder we won't render it already

the problem is that I do have a 404.html and I'm having the issue with current_url checks. Thus, my crazy idea suggesstion.

**Comment by Keats** [comment]
You can just do something like `{% if current_url %}{{ current_url }}{% endif %}`

**Comment by andreacfromtheapp** [comment]
I would do something like this IF it was possible, but 404 doesn't get [current_url not current_path](https://www.getzola.org/documentation/templates/overview/).

```{% if current_url != "404" %} <link rel="canonical" href="{{ current_url | safe }}" />{% endif %}```

**Comment by Keats** [comment]
`{% if current_url  %} <link rel="canonical" href="{{ current_url | safe }}" />{% endif %}` should work

**Comment by andreacfromtheapp** [comment]
> `{% if current_url %} <link rel="canonical" href="{{ current_url | safe }}" />{% endif %}` should work

🥳 🥳 🥳 🥳 🥳 🥳 

you are my hero 🥇
