### ISSUE TITLE
load_data crashes zola when CSV files have non-consistent column counts

### ISSUE THREAD

**Issue by fbruetting** [getzola/zola#588]
# Bug Report

## Environment

Zola version: v0.5.0

## Expected Behavior
When something isn’t right, I expect Zola to mock me and not build the site, but not to give up and quit.

## Current Behavior
When I create a sample CSV file with one two-column row and one three-column row and try `load_data` on it, it causes Zola to immediately crash completely.

**Comment by kellpossible** [comment]
I'll have a look into it this week if I get the time, it's a good first issue however for anyone else interested.

**Comment by mziter** [comment]
I have fixed this error locally. The result row from csv crate was calling `.unwrap()` and didn't check for error. I now have error bubbling up and a unit test for bad csv. Currently `tera::Error` is manually created but our own custom Errror wrapper would be better long-term.

However, I am unsure of the impact of this at the application level. Something higher up in the stack could be blindly unwrapping as well. Could someone instruct me on how to replicate the .csv load functionality locally so I can do a manual integration test?

**Comment by Keats** [comment]
> However, I am unsure of the impact of this at the application level. Something higher up in the stack could be blindly unwrapping as well.

All of the load_data code is in `templates/src/global_fns/load_data.rs`, nothing higher up the stack there. There are tests in that file, that's a good spot to put them

**Comment by mziter** [comment]
Ok. I have added a "bad csv" to the test data and have added a corresponding test as well. I have figured out how to setup a template to test load_data with bad csv. Before Zola would panic when it tried to process the file, now it catches the error and displayes it in console, but it appears as though it doesn't continue to load and serve anything up. Should I be looking into that too, or would you like me to submit PR with what I have now?

Here is what is displayed now in console when bad csv is used
```
Error: Failed to render section '/home/matt/zola-test/content/_index.md'
Reason: Failed to render 'index.html'
Reason: error encountered when parsing csv records
Reason: CSV error: record 2 (line: 3, byte: 8): found record with 3 fields, but the previous record has 2 fields
```

**Comment by Keats** [comment]
> Before Zola would panic when it tried to process the file, now it catches the error and displayes it in console, but it appears as though it doesn't continue to load and serve anything up

That's the normal behaviour.

For the test, you don't even need to load a template, the call to `load_data` is a simple function so you can test it as a normal Rust function, check the `can_load_csv` test for example.

Just to be sure, are you basing your patch on the `next` branch? You will need to do so for the PR

**Comment by mziter** [comment]
Yea, I copied the existing can_load_csv test, pointed to a new bad_csv, and then asserted the error result and contents, just like you suggested.

I am working off of master. Sorry I didn't read the contributing readme well enough. I will make change on that branch and the put in PR.

**Comment by fbruetting** [comment]
Thank you so much for your help!
