### ISSUE TITLE
Toplevel .md files should be pages, not sections

### ISSUE THREAD

**Issue by rocallahan** [getzola/zola#592]
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior
A file `content/manifesto.md` should be treated as a page whose generated file is `manifesto.html` under the root.

## Current Behavior
A file `content/manifesto.md` turns into a "manifesto" section where the generated page is `manifesto/index.html`.

It seems to be impossible to generate a `manifesto.html` page under the root. If `content/manifesto.md` generated `manifesto.html`, it would still be possible to create a `manifesto` section using `content/manifesto/_index.md`.

**Comment by polyzen** [comment]
`manifesto/index.html` and such are good for having pages without `.html` in the URL.

**Comment by rocallahan** [comment]
Yeah, I misunderstood zola completely. Apparently it wants EVERY page to be an index.html in some directory. Not really what I want, but this is by design.
