### ISSUE TITLE
earlier/later or heavier/lighter of a Page are always null when using a paginator

### ISSUE THREAD

**Issue by shalzz** [getzola/zola#595]
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior
earlier/later or heavier/lighter of a Page should be not null when paginating a section using `paginate_by` even when `sort_by` is set to `date` or `weight`

## Current Behavior
earlier/later or heavier/lighter are always null when using a paginator.

## Step to reproduce
Paginate a section with  `paginate_by=5` and `sort_by="date"` and in a template while iterating through `paginator.pages` use `page.earlier`. For every Page these fields will be null.

**Comment by Keats** [comment]
That is the normal behaviour, `earlier/later/lighter/heavier` is only added when rendering the page itself, nowhere else.

**Comment by shalzz** [comment]
I see. These values where available when not using a paginator and just iterating through a sections pages. When switching to a paginator they suddenly disappeared.

So seemed like a bug the behaviour between the two is different.
Anyway closing if indeed its not a bug.

**Comment by Keats** [comment]
Looks like I forgot to remove it when it is not a paginator then, I'll have a look. Thanks!
