### ISSUE TITLE
Unrendered sections get added to sitemap.xml

### ISSUE THREAD

**Issue by Follpvosten** [getzola/zola#604]
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior
Sections with `render` set to `false` should not get added to the sitemap.

## Current Behavior
Those sections get added to sitemap.xml (and Google Search Console complains about that because it cannot load the URL). I don't see a config option to change this.

## Step to reproduce
This is the `_index.md` for the section:

```toml
+++
title = "Pages"
render = false
redirect_to = ""
+++
```

I use it to contain pages which are listed in my footer, not not anywhere else, so I don't need it rendered and there are no links to it.

**Comment by Keats** [comment]
Thanks for the report! It should be fixed by the commit above in the next release
