### ISSUE TITLE
Allow datetime prefix on colocated section paths

### ISSUE THREAD

**Issue by jonblack** [getzola/zola#607]
Zola version: 0.5.1

Given the following filesystem layout:

```
..
├── 2013
│   ├── 2013-06-02_example-post
│   │   ├── image1.png
│   │   ├── image2.png
│   │   └── index.md
│   └── _index.md
└── _index.md
```

I'd like the URL for the above page to be `https://example.blog/2013/example-post`. Instead it's `https://example.blog/2013/2013-06-02-example-page/`.

So the datetime prefix for pages only works on markdown files, not on pages with collocated assets.

In general, it would be nice to have a front page matter option to mark a section to not be included in the URL. Subfolders for years and months are useful for organising on disk, but I don't necessarily need them in the URL.

**Comment by jonblack** [comment]
Added #608 for the last remark above :smile:

**Comment by Keats** [comment]
Definitely a bug, the code setting the data should be looking at the folder name instead in the case of colocated dir
Easy to fix if someone wants to get started on it!

**Comment by Keats** [comment]
Should be fixed in the next branch if you want to try
