### ISSUE TITLE
Alternative page "views"

### ISSUE THREAD

**Issue by theduke** [getzola/zola#615]
I'd love to have a way to create multiple kinds of "views" for a page, that all get built to a different file.

Example:

* Regular, full page html
* html that only contains the page content, without header/footer, ... - used for javascript based loading to avoid full page reload
* JSON containing all the the metadata, for use by Javascript in whatever fashion
* ...

Is there a way to do this with zola right now? Otherwise, is that a feature you would support?

It could be implemented like this

Zola checks for existence of a `page.(extension)` templates. 
If additional page templates are found, each template is rendered to the inferred file path: (page_path).(extension) templates.

So my "partial" html template could be rendered with a template file `page.article.html`, which would result in a `a/b/c/my-page.article.html` file (for `a/b/c/my-page.md`).

**Comment by Keats** [comment]
i believe this is the same as https://github.com/getzola/zola/issues/365 ?

**Comment by theduke** [comment]
@Keats true.
