### ISSUE TITLE
proposed documentation and shell.nix for building on nixos

### ISSUE THREAD

**Issue by ghost** [getzola/zola#616]
# Documentation issue
I needed to add a `shell.nix` with the following contents to successfully build zola on nixos.
```nix
with import <nixpkgs> {};

pkgs.mkShell {
  buildInputs = [
    libsass
    openssl
    pkgconfig
  ];
}
```
## Summary
Needed to add this file, then run `nix-shell` in the cloned directory in order to run `cargo build --release`.

## Proposed solution
I would like to include this `shell.nix`, and update the documentation for nixos users. This will make it easier for anyone who wants to build zola in a nix environment. I can PR for this if you are on board.

**Comment by Keats** [comment]
Please do a PR!
