### ISSUE TITLE
Absolute URL Function

### ISSUE THREAD

**Issue by JadedBlueEyes** [getzola/zola#621]
# Feature

## Current Problem
When users wish to create an absolute URL, that they do not have a permalink for in their templates, it is rather hard. they have to use the config.base_url option, but this is a probem, as it the base url does not have a protocol on front of it, it will become a relative url, and if it is followed by a slash, `//localhost/` + `/sitemap.xml`: `//localhost//sitemap.xml`.

## Description
This feature should, in some capacity, let users turn a relative URL into an absolute URL witin a template, similar to Jekyl's liquid filter `absolute_url`. Idealy, this should be as easy as `{{ absolute("sitemap.xml" }}` or `{{ "sitemap.xml" | absolute }}`

**Comment by Keats** [comment]
Have you seen https://www.getzola.org/documentation/templates/overview/#get-url ?

**Comment by JadedBlueEyes** [comment]
No! Thanks! Sorry for the inconvenience. Works amazingly.
```jinja2
{{ get_url(path="/sitemap.xml") }}: http://localhost:8080/sitemap.xml
```
