### ISSUE TITLE
[feature request] pagination by date (year, month, day…)

### ISSUE THREAD

**Issue by pandark** [getzola/zola#624]
To go a step further than #307, it could be nice to be able to paginate by year or month (or day), instead of paginating by number of _posts_.
For example, instead of `/archive`, there would be `/archive/2018/` and `/archive/2019/`, or `/archive/2018/12` and `/archive/2019/02` (if there were _posts_ in November and January, but not in December).

**Comment by Keats** [comment]
There was a similar request for blog posts url instead of archives but that's very unlikely to be built in.
Monthly archives is pretty niche and yearly ones are easy to do manually.

**Comment by pandark** [comment]
Well, I was thinking about the _taxonomy_ pages too, so it's not necessary that easy.

**Comment by JadedBlueEyes** [comment]
It's not something that anyone would want to do manualy, and people (especialy organisations) can pump out enough content to warrant monthly archives.
