### ISSUE TITLE
get_section doesn't return date and slug, and ignore metadata_only=true

### ISSUE THREAD

**Issue by pandark** [getzola/zola#625]
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior

The section date and its slog should be available through `{{ subsection.date | date(format="%F") }}` and `{{ subsection.slug }}`.

The content shouldn't be available if `metadata_only=true` is passed.

## Current Behavior

It fails with an error when trying to use `date`:

```
Error: Failed to render section '…/content/xxx/_index.md'
Reason: Failed to render 'section.html'
Reason: Variable `subsection.date` not found in context while rendering 'section.html'
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.
```

Also, `subsection.content` is available even if `metadata_only=true` is passed to `get_section()`.

## Step to reproduce

Render this template:

```
{% set section = get_section(path="/path/to/section_with_a_date_and-slug/_index.md", metadata_only=true) %}
{{ section.path }}: slug[ {{ section.slug }} ], date[ {{ section.date | date(format="%F") }} ], content[ {{ section.content }} ]
```

**Comment by Keats** [comment]
Looks like that was a case of copy/paste mistake in the docs. A section doesn't have `slug`/`date` so the behaviour is expected, I updated the docs in the `next` branch to reflect that.
