### ISSUE TITLE
a paragraph is created inside each markdown list element

### ISSUE THREAD

**Issue by pandark** [getzola/zola#626]
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior

```
- 1
- 2
  - 2.1
```

should render

```
<ul>
<li>1</li>
<li>2
<ul>
<li>2.1</li>
</ul>
</ul>
```

## Current Behavior

Instead, it renders

```
<ul>
<li>
<p>1</p>
</li>
<li>
<p>2</p>
<ul>
<li>
<p>2</p>
</li>
</ul>
</ul>
```

## Step to reproduce

Make a markdown list in a page/section.

**Comment by Keats** [comment]
We don't do anything fancy with lists when rendering so that's likely coming from `pulldown-cmark`. They are working on a new version so hopefully it will be working fine when it is released.

**Comment by Keats** [comment]
I just tried with the next version of pulldown-cmark and that works as expected!

**Comment by pandark** [comment]
I'm not sure what triggers this, but it's not actually solved…

If I have only one list, it's fine, but if I have two lists, or if I use a shortcode in one of the elements, the `<p>`s are back :confused: 

@Keats Should I open a new issue or keep using this one?

**Comment by Keats** [comment]
If you can create a new issue with some samples that would be great

**Comment by pandark** [comment]
Ok, so it was actually two different things : #647 (shortcode adding a newline) and #648 (consecutive lists rendering a single messed-up one). :smiley:
