### ISSUE TITLE
access to section

### ISSUE THREAD

**Issue by tcurdt** [getzola/zola#628]
# Documentation issue

## Summary
There is not enough explanation around the access and context of sections and taxonomies.

## Proposed solution
A simple example setup demonstrating common use cases and then referencing those from the documentation.

This [taxonomy page](https://www.getzola.org/documentation/content/taxonomies/) does not mention how `terms` or `terms` at all. It took a while to figure out these templates:

```
{% extends "index.html" %}
{% block content %}
    <h1>{{term.name}}</h1>
    <ul>
    {% for page in term.pages %}
        <li>
            <span>{{ page.date | date(format="%F") }}</span>
            <span><a href="{{ page.permalink }}">{{ page.title }}</a></span>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}
```

```
{% extends "index.html" %}
{% block content %}
    <h1>{{ terms | length }} tags in total</h1>            
    <ul>
    {% for tag in terms %}
        <li>
            <a href="{{ tag.permalink }}">
                {{ tag.name }}
                <span class="count">({{ tag.pages | length }})</span>
            </a>        
        </li>
    {% endfor %}
    </ul>
{% endblock content %}
```

IMO it be worth having this in the docs or at least referenced.

Accessing sections is not covered either. I am still at a loss how to list the last 5 pages of section `posts` on my index page. A not successful try:

```
    {% block content %}
      <ul>
        {% set section = get_section(path="posts") %}
        {% for page in section.pages %}
        <li>
            <a href="{{ page.permalink }}">{{ page.title }}</a>
            {{ page.date | date(format="%Y-%m-%d") }}
        </li>
        {% endfor %}
      </ul>
    {% endblock content %}
```

...and that's still missing a `reverse` and a limit to 5.

**Comment by tcurdt** [comment]
Is there a way to print out all information/variables available in a block of a template? That could help.

**Comment by Keats** [comment]
Have you seen the `Templates` section of the documentation?
For example https://www.getzola.org/documentation/templates/taxonomies/ for taxonomies and https://www.getzola.org/documentation/templates/pages-sections/ for sections & pages

**Comment by tcurdt** [comment]
@Keats Thanks for the links. I saw them. With the knowledge I have now it make sense - but IMO that's not good enough to get started. Adding/referencing the above snippets will make it much easier when new to zola.

And I am still stuck at listing pages from arbitrary sections in my index page. I can't find anything on that either.

**Comment by tcurdt** [comment]
https://www.getzola.org/documentation/content/section/ does not even mention `get_section`

**Comment by Keats** [comment]
Yeah the Tera functions are detailed in https://www.getzola.org/documentation/templates/overview/#built-in-global-functions

The current layout makes sense to me but I am looking for feedback on that: https://zola.discourse.group/t/improve-documentation-first-time-experience/24

**Comment by tcurdt** [comment]
> Yeah the Tera functions are detailed in https://www.getzola.org/documentation/templates/overview/#built-in-global-functions

Yes, that's where I found them - but there is no reference from the section page.

> The current layout makes sense to me but I am looking for feedback on that: https://zola.discourse.group/t/improve-documentation-first-time-experience/24

I am happy to give more detailed feedback or even provide some PR for the documentation (if there is interest) but first I need to get it working :) and if you could point me into the right direction to show the last 5 posts on my index.html - that would be great.

**Comment by tcurdt** [comment]
The part that is quite confusing is that the `index.html` seems to be some sort of section, too(?).
And I just don't get how to get access to other sections to list their pages.

**Comment by Keats** [comment]
```
    {% block content %}
      <ul>
        {% set s = get_section(path="posts/_index.md") %}
        {% for page in s.pages | reverse  | slice(end=5) %}
        <li>
            <a href="{{ page.permalink }}">{{ page.title }}</a>
            {{ page.date | date(format="%Y-%m-%d") }}
        </li>
        {% endfor %}
      </ul>
    {% endblock content %}
```

Something like that maybe? I haven't tried it, I'll have a look in the evening if it doesn't work.

**Comment by tcurdt** [comment]
@Keats Thanks, that does indeed work. So I was almost there.

The bit where I got it wrong was`get_section(path="posts/_index.md")` instead of just `get_section(path="posts")`. And frankly speaking I don't quite get why it needs to be that way (yet).

**Comment by Keats** [comment]
>  And frankly speaking I don't quite get why it needs to be that way (yet)
 
I can't remember either tbh but I think it was like to be symmetric with `get_page` that requires a path to the .md file.

**Comment by tcurdt** [comment]
Just came across another issue that isn't really a bug - but where should this be discussed best?

Is this really the best way to list tags?
```
            {% for key, values in post.taxonomies %}
            {% if key == "tags" %}
                {% for tag in values %}
                <li><a href="{{get_taxonomy_url(kind=key, name=tag)}}">{{tag}}</a></li>
                {% endfor %}
            {% endif %}
            {% endfor %}
```
TBH I am wondering if there really are use cases of other taxonomies in the real world.
Because accessing them as `post.tags` and `post.categories` would be so much easier.
That would also get rid of the awkwardness in the TOML front matter.
```
[taxonomies]
tags = [ "javascript" ]
+++
```
I am also wondering why the type is `HashMap<String, Array<String>>` instead of  `HashMap<String, Array<TaxonomyTerm>>`.

**Comment by Keats** [comment]
You can iterate on `page.taxonomies.tags`:
```
{% if page.taxonomies.tags %}
  Tags: {% for tag in page.taxonomies.tags %}<a href="{{ get_taxonomy_url(kind="tags", name=tag) }}">{{ tag }}</a> {% endfor %}
{% endif %}
```
It's wrapped in a `if` in case you don't always set a tag to a page.

> TBH I am wondering if there really are use cases of other taxonomies in the real world.

This was like that before but people wanted custom taxonomies and there are plenty of them: authors, albums, places, animals etc
Not to forget just being able to name tags/categories in your own language as well

> I am also wondering why the type is `HashMap<String, Array<String>>` instead of `HashMap<String, Array<TaxonomyTerm>>`.

`TaxonomyTerm` contains all the pages for that term, which is not really what most people want when rendering a page. It is usually just to list the name of the taxonomy and link to it.
It could be extended to pass something like `{name, permalink}` though instead of just the string.

**Comment by tcurdt** [comment]
Odd - I thought I tried `page.taxonomies.tags`. Will give that another go then. Thanks.
The rest makes sense now.

One other thing:  Is there a way to reverse the order of a map traversal?

`for year, posts in section.pages | group_by(attribute="year")`

It seems `reverse` just works on arrays.

**Comment by Keats** [comment]
> It seems `reverse` just works on arrays.

It also works on strings. The issue is that filters in Tera operates on value so your example will try to do `for year, posts in (section.pages | group_by(attribute="year"))` and it doesn't really make sense to reverse a hashmap.

I don't really know how to reverse a map iteration to be honest

**Comment by tcurdt** [comment]
Well, order is usually not defined for a hashmap - but here iteration is allowed anyway. So that implies an order. Be it order of insertion or natural order of the keys. If there is order it should also be reversible. So from that perspective it does make sense given iteration is allowed. `reverse' would essentially re-order the keys.

The natural approach to a work around would be to get the keys as array, order them as wanted and then iterate and lookup by key.

**Comment by Keats** [comment]
@tcurdt can this be closed?

**Comment by tcurdt** [comment]
@Keats We could maybe turn this into a new issue - but grouping posts by years in reverse order is not solved yet.

**Comment by Keats** [comment]
I'm thinking having a way to build an archive automatically (with optional pagination) would be a better way to do that (assuming your usecase is an archive-like page).

**Comment by tcurdt** [comment]
It is indeed for an archive page - but I really don't want pagination.

**Comment by tcurdt** [comment]
@Keats the group by year with reverse order issue is still open.
Should I create a new issue for that?
Is that a Documentation or a Bug issue?

**Comment by Keats** [comment]
It's a missing feature issue but not a priority. It would probably be better to close this one and create a new issue or post in https://zola.discourse.group/ to discuss it.

**Comment by tcurdt** [comment]
I've asked in the group.

**Comment by tcurdt** [comment]
https://zola.discourse.group/t/group-by-year-time-order/192
