### ISSUE TITLE
Duplicates in sitemap

### ISSUE THREAD

**Issue by JadedBlueEyes** [getzola/zola#633]
# Bug Report

## Environment

Zola version: `0.5.1`

## Expected Behavior
Tell us what should have happened.
Sitemap.xml should've outputted:
```xml
<urlset>
  <url>
    <loc>http://localhost:8080/blog/test-2/</loc>
    <lastmod>2019-03-10</lastmod>
  </url>
  <url>
    <loc>http://localhost:8080/blog/test/</loc>
    <lastmod>2019-03-09</lastmod>
  </url>
  <url>
    <loc>http://localhost:8080/</loc>
  </url>
  <url>
    <loc>http://localhost:8080/blog/</loc>
  </url>
</urlset>
```
with only one link to the root page.
## Current Behavior
However, currently, it is producing this:
```xml
<urlset>
  <url>
    <loc>http://localhost:8080/</loc>
  </url>
  <url>
    <loc>http://localhost:8080/blog/test-2/</loc>
    <lastmod>2019-03-10</lastmod>
  </url>
  <url>
    <loc>http://localhost:8080/blog/test/</loc>
    <lastmod>2019-03-09</lastmod>
  </url>
  <url>
    <loc>http://localhost:8080/</loc>
  </url>
  <url>
    <loc>http://localhost:8080/blog/</loc>
  </url>
</urlset>
```
With two links to the root. 
## Step to reproduce
It seems to be a bit weird, but it's only affected by what's in the content folder.
I have an example repo at [derpmarine168/zola-sitemap-test](https://github.com/derpmarine168/zola-sitemap-test).

**Comment by Keats** [comment]
Should be fixed by the commit above, thanks for the report!
