### ISSUE TITLE
[Documentation] get_taxonomy example

### ISSUE THREAD

**Issue by senden9** [getzola/zola#636]
# Documentation issue

## Summary
The function `get-taxonomy` ([doc link](https://www.getzola.org/documentation/templates/overview/#get-taxonomy)) has a invalid example. Namely:
```
{% set categories = get_taxonomy_url(kind="categories") %}
 ``` 
`get_taxonomy_url`-command in the `get_taxonomy`example

**Comment by Keats** [comment]
Thanks!
