### ISSUE TITLE
How to reverse `sort_by`?

### ISSUE THREAD

**Issue by kkshinkai** [getzola/zola#640]
I've tried the filter `paginator.pages | reverse` in template.

For example, I think a blog paginate by 3, sort by date with filter “reverse” should go like this:

Page 1 = 1: 2018-3-15   2: 2018-3-14  3: 2018-3-13
Page 2 = 1: 2018-3-12   2: 2018-3-11  3: 2018-3-10

So the resent post is on the top of the first page, but in fact, Zola generate it like this:

Page 1 = 1: 2018-3-12   2: 2018-3-11  3: 2018-3-10
Page 2 = 1: 2018-3-15   2: 2018-3-14  3: 2018-3-13

I don't know how to fix it just use template, perhaps we need a filter choise in Config.toml

**Comment by Keats** [comment]
Which version of Zola are you using? Sounds like a bug, it should be generated like your first example.

Do you have a repo I can use to find the issue?

**Comment by kkshinkai** [comment]
I've built the latest Zola from source, and make a example
[zola_demo.zip](https://github.com/getzola/zola/files/3003653/zola_demo.zip)

filter in template can only deal with the posts in the single page.
so.
`1 2 3 | 4 5 6 | 7 8 9` became
`3 2 1 | 6 5 4 | 9 8 7` with `reverse`, it's reasonable.
but we expect
`9 8 7 | 6 5 4 | 3 2 1`

**Comment by Keats** [comment]
Ah I found the issue.
In the section front-matter it should be `sort_by` and not `sorted_by`. It works as expected afterwards

**Comment by kkshinkai** [comment]
Oh I see it, I didn't read the document carefully. So sorry for that.

**Comment by Keats** [comment]
No worries!
