### ISSUE TITLE
Syntax highlighting for rust

### ISSUE THREAD

**Issue by hanckmann** [getzola/zola#642]
# Bug Report
There is no syntax highlighting for the rust programming language.

## Environment
Zola version: 0.6.0

**Comment by Keats** [comment]
Have you enabled syntax highlighting in the config.toml by setting `highlight_code = true`? It might also depend on the theme you are using.

I do get it on my site, eg: https://www.vincentprouillet.com/blog/trying-rust-for-web-services/#pattern-matching

**Comment by hanckmann** [comment]
Oops... sorry for wasting your time :-(
