### ISSUE TITLE
Import from wordress

### ISSUE THREAD

**Issue by TatriX** [getzola/zola#646]
Hi. I'm trying to move my old blog from wordress to a static site generator.
Zola looks very interesting. And in order to move I'd like to import data from wordress.

Let's take a look on how [hugo solves this issues](https://gohugo.io/tools/migrations/#wordpress).
I've tried [this tool](https://github.com/wooni005/exitwp-for-hugo)  and after some struggle with installation of the dependencies I've successfully generated markdown files. I can't use them to populate my zola setup, because it generated yaml front-matter instead of toml. Also files should be renamed, but it's not a big deal.

So I'm thinking about making my own tool in rust to do the import from wordress xml. Anything I should consider before diving in?

**Comment by Keats** [comment]
If WP exports standard XML, it should be fairly straightforward.
I would recommend playing with Zola first with some dummy data to ensure it covers all your usecases. If that works and you build the tool, I would probably feature it in the docs as part of https://github.com/getzola/zola/issues/611

**Comment by TatriX** [comment]
I made a tool. I'll publish initial version soon.

**Comment by TatriX** [comment]
https://github.com/TatriX/wordpress-to-zola

**Comment by Keats** [comment]
https://github.com/TatriX/wordpress-to-zola/blob/master/src/main.rs#L163 really depends on your site structure. Same for pagination/sort_by.
Other than that, it looks nice - very short!

**Comment by TatriX** [comment]
Sure, I wanted to first handle my use-case. I will make it configurable.

**Comment by dertuxmalwieder** [comment]
Is that still planned? I’m looking at options to migrate again and Zola looks promising, if only it was easier to bring thousands of articles with me.

**Comment by TatriX** [comment]
I won't be able to work an that anytime soon, sorry.
