### ISSUE TITLE
The ending newline in shortcode files isn't ignored

### ISSUE THREAD

**Issue by pandark** [getzola/zola#647]
Most text editors automatically add a newline at the end of each file (and don't show it).
In shortcodes, it is treated as a regular newline (usually displayed as an additional space in the resulting HTML but can be more problematic in a list or in preformatted text, for example).
Maybe #462 was fixed too well? :stuck_out_tongue: 

It is possible to circumvent the problem by specifically removing the ending newline in shortcode files, but that newline should probably be ignored by zola to make things simpler.

**Comment by Keats** [comment]
Thanks, I guess we should probably remove it. If anyone wants to try, it should be easy enough

**Comment by bdjnk** [comment]
I'll look into fixing this. I should have a PR for it fairly quickly.
