### ISSUE TITLE
Two consecutive markdown lists are rendered incorrectly

### ISSUE THREAD

**Issue by pandark** [getzola/zola#648]
# Bug Report

## Environment

Zola version: 0.6.0

## Expected Behavior

```
- list 1 element 1
- list 1 element 2

- list 2 element 1
- list 2 element 2
```

should render

```
<ul>
<li>list 1 element 1</li>
<li>list 1 element 2</li>
</ul>
<ul>
<li>list 2 element 1</li>
<li>list 2 element 2</li>
</ul>
```

## Current Behavior

Instead, it renders

```
<ul>
<li>
<p>list 1 element 1</p>
</li>
<li>
<p>list 1 element 2</p>
</li>
<li>
<p>list 2 element 1</p>
</li>
<li>
<p>list 2 element 2</p>
</li>
</ul>
```

## Step to reproduce

Make more than one markdown list in a page/section with only empty lines between them.

**Comment by Keats** [comment]
According to the CommonMark spec this is the correct behaviour: https://spec.commonmark.org/dingus/?text=-%20list%201%20element%201%0A-%20list%201%20element%202%0A%0A-%20list%202%20element%201%0A-%20list%202%20element%202

**Comment by pandark** [comment]
This is a very confusing behavior, but I guess if the spec says so… :sweat_smile:

**Comment by bdjnk** [comment]
Evidently you make two consecutive lists by adding an html comment, [described here](https://spec.commonmark.org/0.28/#example-271), like so.

```markdown
- one
- two  
<!---->
- new
```

```html
<ul>
<li>one</li>
<li>two</li>
</ul>
<!---->
<ul>
<li>new</li>
</ul>
```
