### ISSUE TITLE
ToC not generated

### ISSUE THREAD

**Issue by kgadek** [getzola/zola#651]
# Bug Report

## Environment

Problematic versions: 0.6.0 & current master (`b443be2`).

ToC generation _works_ in v0.5.1.

## Expected Behavior
ToC should be generated.

## Current Behavior
The `page.toc` is empty. 

## Step to reproduce

    git clone https://github.com/getzola/even.git
    cd even
    zola serve

Open http://127.0.0.1:1111/markdown-overview/ in web browser. Depending which `zola` version was used, the ToC was generated or not.

**Comment by Keats** [comment]
It is a breaking change of 0.6.0: the `toc` variable is now global at the page level rather than being in `page.toc` https://github.com/getzola/zola/blob/master/CHANGELOG.md#breaking
