### ISSUE TITLE
Add subcomand for making new pages `zola new`

### ISSUE THREAD

**Issue by TatriX** [getzola/zola#656]
It would be nice to have an ability to do something like:
```sh
zola new blog/hello "Hi there"
```
to generate a `./content/blog/hello.md` with
```
+++
title = "Hi there"
date = <...>
+++
Put content here.
```

**Comment by tshepang** [comment]
I use this https://github.com/tshepang/post, documented here https://bitbucket.org/tshepang/blog.

**Comment by Keats** [comment]
That is very unlikely to be built-in Zola itself, it can be replaced more effectively with a `cp` call if you already have at least a page

**Comment by zimmi** [comment]
I agree: The file system is the API.
Workflow goodies are better written as editor plugins in my opinion.
