### ISSUE TITLE
Snapcraft still serves 0.5

### ISSUE THREAD

**Issue by marcusklaas** [getzola/zola#657]
Has the 0.6 release been added to Snapcraft yet?

**Comment by Keats** [comment]
I triggered a build by changing the version in snapcraft.yml but all the builds are failing.

Looks like the Rust plugin for snapcraft is broken again? This issue: https://forum.snapcraft.io/t/rustup-sh-does-not-support-channel-argument/10224 specifically

**Comment by Ihsahn** [comment]
Just checked: 
```
$ snap list | grep zola
zola                    0.7.0                   57     edge       keats
```

**Comment by marcusklaas** [comment]
Awesome! I'll close this then :-)

Thanks for the update.
