### ISSUE TITLE
Markdown documentation

### ISSUE THREAD

**Issue by nuxeh** [getzola/zola#658]
# Documentation issue

## Summary

I can't seem to find documentation on the markdown format. Particularly pages i create which use headings ## ### etc don't render very nicely, with the page being rendered almost exactly as the original text.

Should markdown features, such as headings, and bullet lists, etc. work in Zola?

**Comment by Keats** [comment]
It it using https://commonmark.org/
Most markdown features do work in Zola, it might depend on your CSS?

**Comment by nuxeh** [comment]
Looking at the page source, headings are `<h1>` etc, and lists are `<li>`, i guess it must be my theme making it look like markdown again, indeed. I'm using the after dark theme, so i guess that makes some sense.

**Comment by Keats** [comment]
Ah yes that's the unique look of the after-dark theme!
