### ISSUE TITLE
get_url returning 127.0.0.1

### ISSUE THREAD

**Issue by nuxeh** [getzola/zola#665]
Hi, i'm hosting a site with zola, proxied through nginx, the `get_url` call used to get the paths to the theme CSS files are returning 127.0.0.1 this way, is there something i can do about this?

Ideally i'd like to be able to test locally, too, as well as when hosted.

EDIT: The path used is `"{{ get_url(path="print.css", trailing_slash=false) }}"`

Thanks.

**Comment by Keats** [comment]
Are you using `zola serve` to host the site? If so you have to use `zola build` instead, `serve` is only used for development

**Comment by nuxeh** [comment]
I am indeed.

But, interesting, I did wonder if that was the case. Thanks!
