### ISSUE TITLE
Allow shortcodes to be escaped

### ISSUE THREAD

**Issue by li-kai** [getzola/zola#668]
# Bug Report

## Environment

Zola version: 0.6.0

## Expected Behavior

There either should be a way for shortcodes to be escaped, or to disable them from triggering in markdown code blocks.

## Current Behavior

Given the markdown
```
`<link rel="stylesheet" href="{{ get_url(path="index.css", trailing_slash=false) }}">`
```
Zola will attempt to run the get_url shortcode, which makes it impossible to write a blog post about setting up Zola in Zola because it will encounter the error "Reason: Failed to render get_url shortcode".

## Step to reproduce

Create a markdown file in /content with the following:
```
+++
title = "Creating a blog with Zola"
date = 2019-01-01
+++

`<link rel="stylesheet" href="{{ get_url(path="index.css", trailing_slash=false) }}">`
```

**Comment by Keats** [comment]
See the escape sentence in https://www.getzola.org/documentation/content/shortcodes/#shortcodes-without-body

> Note that if you want to have some content that looks like a shortcode but not have Zola try to render it, you will need to escape it by using {{/* and */}} instead of {{ and }}.

> If you want to have some content that looks like a shortcode but not have Zola try to render it, you will need to escape it by using {%/* and */%} instead of {% and %}.

**Comment by li-kai** [comment]
That solves the problem. Thank you!
