### ISSUE TITLE
Iterating over all files of all terms instead of just the taxonomy terms in list.html and over all taxonomy terms in single.html of a taxonomy?

### ISSUE THREAD

**Issue by hardcodepunk** [getzola/zola#671]
## How to?

Iterating over all files with taxonomies in list.html, not just the different taxonomy terms?
Iterating over all taxonomy terms in single.html of a taxonomy? 

Or probably more precisely, how can I reach certain variables globally like 'terms' or my custom 'posts'?

## Current problems
When I try to iterate over all files I get an error 'Failed to render' in posts/list.html
When I try to iterate over the taxonomy terms it says the variable 'terms' is not found in context while rendering 'posts/single.html'

**Comment by hardcodepunk** [comment]
## Iterate over all files of all terms in list.html
In posts/list.html:

````
<ul>
{% set posts = get_section(path="posts/_index.md") %}
{% for page in posts.pages %}
  <li>
    <a href="{{ page.permalink }}">{{ page.title }}</a>
    {{ page.date | date(format="%Y-%m-%d") }}
  </li>
{% endfor %}
</ul>
````

**Comment by hardcodepunk** [comment]
I've found out you can use

`{% set posts = get_taxonomy(kind="posts") %}`

to retrieve a taxonomy but I'm clueless how to iterate over the terms of the taxonomy in for example single.html of this taxonomy.

**Comment by Keats** [comment]
`list.html` is for a list of terms, it doesn't have the pages associated with each. `single.html` is for a single taxonomy term so it doesn't have access to the other terms/taxonomies.

What are you trying to accomplish in the page?

**Comment by hardcodepunk** [comment]
On the page I would have all 'posts' listed and on top all the 'post' categories linking to the page with all the 'posts' of the clicked category. And on this page I also need on top all the 'post' categories listed linking to the other categories.

I have everything working now but the 'post' categories listed on top of the sole category page listing the 'posts' of this category.

**Comment by Keats** [comment]
It's a bit hard to visualize, do you have a screenshot/sketch of what you would like to have?

**Comment by hardcodepunk** [comment]
https://urbit.org/posts/

**Comment by Keats** [comment]
It looks like it would be better done with transparent sections.

You would have something like

```
posts/
   updates/
   essays/
   medias/
```

In the `_index.md` file of each subcategories, you put `transparent = true` and it should work like in the link out of box

**Comment by hardcodepunk** [comment]
How would I then display the article's category or in this case parent folder's name with it's permalink attached?
Now I was able to call its category with the following line in templates/posts/single.html

```
{% if page.taxonomies.posts %}
  {% for post in page.taxonomies.posts %}<a href="{{ get_taxonomy_url(kind="posts", name=post) }}">{{ post }}</a> {% endfor %}
{% endif %}
```

How would I iterate in the posts page over all subfolder's files?

**Comment by Keats** [comment]
By setting `transparent = true`, the pages will be passed to the parent section, `posts` in this case. You would iterate it like any section

**Comment by hardcodepunk** [comment]
Amazing, I'll try it out.

**Comment by Keats** [comment]
Did it work?

**Comment by hardcodepunk** [comment]
I just hardcoded it likes this and it seems to work for now.

```
<li class="list__item content-nav__item">
  <a href="/posts/">
    All
  </a>
</li>
<li class="list__item content-nav__item">
  <a href="/essays/">
    Essays
  </a>
</li>
          
```

And so on for each taxonomy.
