### ISSUE TITLE
date filter bug in page.html

### ISSUE THREAD

**Issue by hardcodepunk** [getzola/zola#673]
# Bug Report

## Expected Behavior

Display date as commanded: {{ page.date | date(format="%Y.%m.%d") }}
For example: 2017.04.16

## Current Behavior

Failed to build the site
Error: Failed to render page
Reason: Failed to render 'page.html'
Reason: Filter `date` received an incorrect type for arg `value`: got `Null` but expected i64|u64|String

## Step to reproduce

{{ page.date | date(format="%Y.%m.%d") }} in page.html

**Comment by Keats** [comment]
Looks like `page.date` is null in that error?

**Comment by hardcodepunk** [comment]
> Looks like `page.date` is null in that error?

It displays correctly without filter, so I think that's not the issue?

**Comment by Keats** [comment]
This is really odd, this error only happens when the value (`page.date` here) is not a number or a string... https://github.com/Keats/tera/blob/v1/src/builtins/filters/common.rs#L97-L102
Not sure what's going on

**Comment by hardcodepunk** [comment]
The design's with dots in between the numbers, but in list.html and single.html it worked out. Just not in page.html it seems. I tried it with '-' in between now, but I got the same error.

**Comment by Keats** [comment]
The format is not the issue, the value the filter is used on is. Maybe not all pages have a date? Try to wrap it in a `{% if page.date %}{{ page.date | date(format="%Y.%m.%d") }}{% endif %}`

**Comment by hardcodepunk** [comment]
That was it. Fixed it, thank you!
