### ISSUE TITLE
Galleries example not working if the directory name contains _

### ISSUE THREAD

**Issue by pandark** [getzola/zola#674]
## Summary
The [galleries example](https://www.getzola.org/documentation/content/image-processing/#creating-picture-galleries) is not working if filenames contain `_`.

If there is a file `content/some_stuff/some_file.png`, there will be an error (notice the `_` replaced by `-` on the last line):
```
Failed to build the site
Error: Failed to render content of /home/user/website/content/some_stuff/index.md
Reason: Failed to render gallery shortcode
Reason: Failed to render 'shortcodes/gallery.html'
Reason: `resize_image`: Cannot find path: some-stuff/some-file.png
```

## Proposed solution
I don't know whether it's something to fix in the example or in zola.

**Comment by Keats** [comment]
Hmm I've just tried in the docs example to add a file with `_` and it worked fine.
The code itself doesn't do any string replacement as far as I can see so it might be a `serve` bug?

**Comment by pandark** [comment]
My bad. Apparently the problem is a `_` in the directory name, not the one in the filename.
I was misled by the fact that `_` were replaced by `-` in both the directory name and the file name in the error message.
(I changed the first comment to reflect the actual problem)

**Comment by Keats** [comment]
So the `-` comes from the slugify method. The assets should use the file path rather than the page path to avoid that. An easy fix if someone wants to have a go at it

**Comment by Keats** [comment]
It should be fixed in the commit above on the `next` branch
