### ISSUE TITLE
Syntax highlighting theme

### ISSUE THREAD

**Issue by nuxeh** [getzola/zola#675]
Hi,

I'm curious whether Zola is intended to work with tmLanguage syntax highlighting schemes, for example this one:

https://github.com/wmertens/sublime-nix

I cloned this repo into `syntaxes/sublime-nix` in my Zola project, and added `extra_syntaxes = ["syntaxes/sublime-nix"]` to my `config.toml`. `zola build` produces no errors, but the syntax highlighting doesn't seem to work, for code blocks such as:

```
```nix
```

or

```
```Nix
```

**Comment by Keats** [comment]
The library Zola uses only supports .sublime-syntax
You can easily convert a .tmLanguage to a sublime-syntax by opening the
file in Sublime

**Comment by nuxeh** [comment]
Thanks, I also found https://github.com/aziz/SublimeSyntaxConvertor, which seems to have done the job.

Made a PR adding Nix to Zola, #676
