### ISSUE TITLE
Dividing by zero in a template segfaults

### ISSUE THREAD

**Issue by creikey** [getzola/zola#679]
# Bug Report

When dividing by zero in a template, zola segfaults

## Environment

Arch Linux

Zola version: zola 0.6.0

## Expected Behavior
A warning to print out to stderr explaining how a division by zero is undefined, then the program continuing

## Current Behavior
```➜  bug RUST_BACKTRACE=1 zola build
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: main
  22: __libc_start_main
  23: <unknown>
```

## Step to reproduce
1. Create a new zola project
2. Create and `_index.md` and add the simple `+++` front matter title of `bug`
3. create an `index.html` template with the following contents:
```
<body>
        <p>Invalid division: {{ 100 / 0 }}</p>
</body>
```
Here is an example:
[bug.zip](https://github.com/getzola/zola/files/3145902/bug.zip)

**Comment by Keats** [comment]
Can you update to 0.7.0? I think this should be fixed there.

**Comment by Keats** [comment]
Closing, should be already fixed in the current version.
