### ISSUE TITLE
Ignore README.md in git submodule

### ISSUE THREAD

**Issue by flowerornament** [getzola/zola#682]
## Environment

Zola version: 0.5.1

## Problem

We have a submodule in our content directory, which has its own README, so:

```
zola/
  content/
    submodule/
      README.md
      _index.md
```

The README.md file does not, and should not, have TOML front-matter, so zola build fails. Adding README.md to `ignored_content` in the config does nothing, because zola attempts to parse the file before potentially ignoring it.

## Proposed Solution

There should be a way to ignore markdown files with an `.md` extension that don't have TOML front-matter.

A hack that works for now is to name `README` to `README.markdown`, so Github sees it as a markdown file, but zola ignores it.

**Comment by Keats** [comment]
`ignored_content` (I assume it was what you meant by `ignored_files`).
Looking at the docs, it should work with `.md` file but since it was originally meant for assets never implemented. 

It should be an easy fix though, it just needs to filter any matching pages (not sections) in `Site::load` before creating a `Page` to see if it's a match. It also needs to handle it in the rebuild.

**Comment by flowerornament** [comment]
Thanks @Keats!

**Comment by lootsy** [comment]
@Keats Is this issue solved by the merged PR #759 by pkova?

**Comment by Keats** [comment]
I haven't tried it but it *should* work

**Comment by lootsy** [comment]
Thank you for your quick reply! Apologize if I disturbed you...

I was looking for a "good first issue" and wanted to know wether there is something to do or not.

What do you think about tagging this issue / PR with something like "solved", "not-tested-yet", "solved-but-untested"  or "claims-to-be-solved"?
Thx again!

**Comment by Keats** [comment]
I think this one can be closed.
If you are looking for some good first issue I think https://github.com/getzola/zola/issues/782 or https://github.com/getzola/zola/issues/789 would be interesting. I am probably going to add some more / go through existing issues next week, or when users report bugs :p

**Comment by mikekasprzak** [comment]
I'm not sure if this is a regression, but with this in my `config.toml` (main section):

```
ignored_content = ["README.md"]
```

It doesn't seem to be working.

```
Error: Couldn't find front matter in `/home/mike/Work/website.com/content/games/README.md`. Did you forget to add `+++` or `---`?
```

**Comment by Keats** [comment]
Can you open a new issue @mikekasprzak ?
