### ISSUE TITLE
A test is failing because it depends on the ordering of std::fs::read_dir output

### ISSUE THREAD

**Issue by chris-morgan** [getzola/zola#688]
e.g. in #685, unrelated test failure, https://travis-ci.com/getzola/zola/jobs/201011899:

```
---- content::page::tests::page_with_assets_uses_filepath_for_assets stdout ----
thread 'content::page::tests::page_with_assets_uses_filepath_for_assets' panicked at 'assertion failed: `(left == right)`
  left: `"posts/with_assets/example.js"`,
 right: `"posts/with_assets/graph.jpg"`', components/library/src/content/page.rs:582:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

The offending line:

```rust
assert_eq!(page.serialized_assets[0], "posts/with_assets/graph.jpg");
```

If the ordering does not matter, this should be changed to `assert!(page.serialized_assets.contains("posts/with_assets/graph.jpg"));`.

If the ordering does matter, `utils::fs::find_related_assets` should sort the output of `std::fs::read_dir`.

I have not looked to see if any other tests are similarly fragile.

**Comment by Keats** [comment]
ha I knew this one would break ;( I pushed it early in the morning and meant to fix it later. Other tests do not rely on ordering so should be fine

**Comment by Keats** [comment]
Fixed
