### ISSUE TITLE
thread '<unnamed>' panicked at 'unexpected node in tree: Header(2)'

### ISSUE THREAD

**Issue by jsdw** [getzola/zola#690]
# Bug Report

Trying to upgrade my site from 0.3.3 to 0.7, I first run into an issue re "order" not being present any more. On changing that to "weight" and trying to build again, I hit this panic:

```
james@jam-xps:~/Programming/jsdw.me$ RUST_BACKTRACE=1 zola build
Building site...
thread '<unnamed>' panicked at 'unexpected node in tree: Header(2)', /cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.4.1/src/parse.rs:1019:29
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   4: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   5: pulldown_cmark::parse::FirstPass::scan_containers
   6: pulldown_cmark::parse::FirstPass::parse_line
   7: pulldown_cmark::parse::FirstPass::parse_block
   8: pulldown_cmark::parse::Parser::new_ext
   9: rendering::markdown::markdown_to_html
  10: library::content::page::Page::render_markdown
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute
  13: rayon_core::registry::WorkerThread::wait_until_cold
  14: rayon::iter::plumbing::bridge_producer_consumer::helper
  15: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute
  16: rayon_core::registry::WorkerThread::wait_until_cold
```

## Environment

Zola version: 0.7

## Expected Behavior
An informative error rather than a panic

## Step to reproduce

```
git clone https://github.com/jsdw/jsdw.me
git checkout 94a72cf68b7e447c4fb5b305e17ff1fbbfdb65f1
zola build
```
You'd need to fix the first issue that zola reports (change "order" to "weight" in the file it points to), then on building again this error occurs.

**Comment by Keats** [comment]
The stack trace seems to be all in pulldown_cmark.. Thanks for the easy reproduction, I'll have a look soon

**Comment by jsdw** [comment]
Thanks, let me know if I can be of assistance! I'm looking forward to getting myself up to date again :)

**Comment by Keats** [comment]
Using the `next` branch I don't run into the panic so I think the pulldown_cmark update fixed it. The only issue is that you need to change the toc macro since that changed (see https://github.com/getzola/zola/issues/694 in case your usecase doesn't work in the recent versions)

**Comment by flowerornament** [comment]
@Keats we ran into the same issue trying to build https://github.com/urbit/urbit.org with zola@0.7.0. Also worth noting it doesn't seem to be possible to install zola@0.5.1 with `brew`.

**Comment by flowerornament** [comment]
@Keats is there an ETA for `next` release?

**Comment by Keats** [comment]
None, maybe this week or the following one.
