### ISSUE TITLE
link labels for ref-style links are broken

### ISSUE THREAD

**Issue by tollyx** [getzola/zola#693]
# Bug Report

## Environment

Zola version: 0.7.0, windows

## Expected Behavior
[link labels](https://spec.commonmark.org/0.29/#link-label) for [reference-syle links](https://spec.commonmark.org/0.29/#full-reference-link) should be able to be placed anywhere in the document and produce a working link.

## Current Behavior
Only a single link label at the end of the document (no newline at EOF) and with a blank line preceding it will produce a working link.

This:
```md
[Foo][1] [Bar][2] [Baz][3]

[1]: foo
[2]: bar
[3]: baz
```
Produces:
```html
<p>[Foo][1] [Bar][2] [Baz][3]</p>
<p>[1]: foo
[2]: bar
[3]: baz</p>
```
----
This:
```md
[Foo][1] [Bar][2] [Baz][3]

[1]: foo
[2]: bar

[3]: baz
```
(there is no newline after `[3]: baz`)  
Produces:
```html
<p>[Foo][1] [Bar][2] <a href="http://127.0.0.1:1111/posts/reflink-test/baz">Baz</a></p>
<p>[1]: foo
[2]: bar</p>
```
----
This:
```md
[Foo][1] [Bar][2] [Baz][3]

[1]: foo
[2]: bar

[3]: baz

```
(there is a newline after `[3]: baz`)  
Produces:
```html
<p>[Foo][1] [Bar][2] [Baz][3]</p>
<p>[1]: foo
[2]: bar</p>
<p>[3]: baz</p>
```
----

All the markdown was outputted with `{{ page.content | safe }}` in a very basic template.

I tried to build and check if this also happened on the latest master but couldn't due to libsass failing to build (I'll put some info about that in the issue in the sass-rs repo when I've had the time to look further into it)

**Comment by Keats** [comment]
Looks like it might be a bug in [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark). I'll update the next branch to the latest version when I get some time and try it.
Any chance you can create some testcases in the `next` branch in `components/rendering/`?

**Comment by tollyx** [comment]
> Looks like it might be a bug in [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark). I'll update the next branch to the latest version when I get some time and try it.

Investigated it a bit and it seems like it was and it has already been fixed: raphlinus/pulldown-cmark#285  
Switched my examples from CRLF to LF and they work.

> Any chance you can create some testcases in the `next` branch in `components/rendering/`?

I would, but I'd prefer to solve the whole sass-not-building-on-windows thing so I actually can run the tests first.

**Comment by Keats** [comment]
There are tons of other markdown fixes in https://github.com/raphlinus/pulldown-cmark/pull/325 as well, waiting for that to land before updating the `next` branch in case there are breaking changes.

> I would, but I'd prefer to solve the whole sass-not-building-on-windows thing so I actually can run the tests first.

This is really a pain :( I'm hoping https://github.com/kaj/rsass gets to parity but that's a huge amount of work.

**Comment by marcusklaas** [comment]
The pull request has been merged and we're now preparing a bug fixing release (0.5.2). Shouldn't be more than a day or two.

**Comment by marcusklaas** [comment]
0.5.2 has been released!
