### ISSUE TITLE
Feature Request: rel="noopener/noreferrer/nofollow" option on external links

### ISSUE THREAD

**Issue by lukehsiao** [getzola/zola#695]
# Feature Request

This feature request is similar to #681.  In Hugo, we can [configure the markdown parser](https://gohugo.io/getting-started/configuration/#configure-blackfriday) (blackfriday) to include `rel` attributes like `nofollow` and `noreferrer` in order to inform crawlers or prevent leaking referrer information. It has also [been shown](https://mathiasbynens.github.io/rel-noopener/) that `rel="noopener"` can be useful in preventing websites from manipulating the `window` object of a document. 

It would be great to be able to include flags to enable or disable the inclusion of these `rel` attributes for markdown links, similar to how #681 seeks to enable or disable including `target="_blank"` with these markdown links.

I'd also point out that Hugo currently does not support `rel="noopener"` (it is supported by blackfriday v2, but hugo is still using blackfriday v1), so adding this support would be a nice advantage for zola.

**Comment by Keats** [comment]
Good idea! I've linked to it from #681, I'll leave this open for now but ideally it will be built in the same PR as 681

**Comment by flatlandy** [comment]
Does the "external_links_no_follow" variable apply to external URL's specified within the frontmatter redirect_to variable?

I am using the redirect_to functionality to create "pretty" outbound links similar to website.com/out/amazon which would redirect to amazon.com/[affiliate code]. As you can imagine, it would be best to have these set to nofollow.

**Comment by Keats** [comment]
No it doesn't because we are using HTML redirects for that
