### ISSUE TITLE
Live reload doesn't update inline css style tag

### ISSUE THREAD

**Issue by foray1010** [getzola/zola#696]
# Bug Report

## Environment

Zola version: 0.7.0

## Expected Behavior
Live reload should update inline css style tag

## Current Behavior
It does reload, but inline css style tag doesn't update its content

## Step to reproduce
put the following code in `structure.html` and try updating the corresponding scss in `sass` folder

```html
{% set css = load_data(path="public/style.css") %}
<style>
  {{css | safe}}
</style>
```

**Comment by Keats** [comment]
That's because only the CSS files are reloaded on Sass changes, the templates are not re-rendered. I don't think that is going to change

**Comment by Keats** [comment]
The only way to fix that would be the re-render templates on CSS change but that's not going to happen as it would slow down things a lot and hot reloading inline CSS is pretty niche.

**Comment by xSke** [comment]
Is there a way to detect whether you're using live reload or not from a template? In that case, could use an external reference if you're live reloading, and then inline it when doing a full build?

**Comment by Keats** [comment]
If you have the network tab of the browser open, you should see some websocket activity if there is live reload enabled and a change. 
As for inlining some CSS file, I'm not against it but I don't know how it could be implemented easily (eg pick which file to inline etc)

**Comment by xSke** [comment]
Oh, I just meant as a template function. That way you can use the non-inlined version when you're just messing around and need fast reloading (`zola serve`), and inline things for speed/size when you need things compact and finalized (`zola build`). eg:

```html
{% if zola.is_live_reloading %}
<link href="{{ get_url(path="style.css") | safe }}" rel="stylesheet">
{% else %}
<style>{{ load_data(path="public/style.css") | safe }}</style>
{% end_if %}
```

Unsure where such a variable would live in the template context (just a global?) but doesn't seem *too* hard, maybe?

**Comment by rslabbert** [comment]
For future reference, I was able to solve this through the following snippet which works for the default `zola serve` setup:
```html
{% macro css(path) %}
    {% if current_url is starting_with("http://127.0.0.1:1111/") %}
        <link rel="stylesheet" href="{{path}}">
    {% else %}
        <style>{{ load_data(path="public/" ~ path) | trim | safe }}</style>
    {% endif %}
{% endmacro input %}
```

**Comment by tilleryd** [comment]
The solution by @rslabbert is just what I needed to boost my sites Lighthouse performance score. Some CSS files, like main.css, are render-blocking resources and greatly impacted the performance score.
