### ISSUE TITLE
no comparison to Jekyll in README

### ISSUE THREAD

**Issue by todrobbins** [getzola/zola#704]
# Documentation issue

## Summary
I was hoping to see Jekyll in the comparison chart, but was surprised it's not listed. Any reason why not?

## Proposed solution
Add a comparison of Zola to Jekyll within the comparison chart in the README.

Cheers!

**Comment by Keats** [comment]
I have never used Jekyll and I limited the comparison to the 2 SSG I've
used + cobalt (since it's in Rust) as well.
If anyone wants to add Jekyll, I'll be able to merge it.

**Comment by todrobbins** [comment]
Cool. I may take a jab at it then. 👍🏻

Just installed Zola, BTW. 😄

**Comment by Keats** [comment]
Go for it!

**Comment by kawpii** [comment]
@Keats missing [gatsby.js](gatsbyjs.org) too.

Other than that, any plan to support front-end frameworks? If you do so go for [Svelte](https://svelte.dev), react.js also seems like a good choice given the community, ecosystem.

**Comment by Keats** [comment]
I don't want to add frontend dependencies to Zola. Maybe in the future, there could be a way to use Zola as a headless CMS but not yet.

For the comparison with Gatsby, I haven't used it but it seems extremely different from the other tools. Having to know and use React/GraphQL is a big hurdle, and I say that as someone doing a lot of that for work.

**Comment by kawpii** [comment]
@Keats thanks for response. Adding front-end dependencies like reactjs will make front-end development easier and will be able to build [JAMStack](https://jamstack.org/) websites quickly.

Current problem with the Gatsby.js is higher build times, but  it have reactjs which is something front-end devs are already familiar with.

Currently Zola is good solution for to building simple static sites. If you get something like reactjs to work with a Zola, it will be a huge win.

**Comment by CheshireSwift** [comment]
> If you get something like reactjs to work with a Zola, it will be a huge win.

This feels like a situation where just using a different tool would make more sense.

**Comment by Keats** [comment]
Closing this issue for now. I'll take a PR if someone has used Jekyll and can add the comparison still.
