### ISSUE TITLE
Invalid sitemap XML

### ISSUE THREAD

**Issue by ianare** [getzola/zola#705]
# Bug Report

## Environment
Debian 9

Zola version:
0.7.0

## Expected Behavior
Sitemaps should use URL-encoded strings for paths.

## Current Behavior
Creates errors like so when opening the sitemap:
```
XML Parsing Error: not well-formed
Line Number 64, Column 38:            
<loc>https://www.example.org/apples-&-oranges/</loc>
------------------------------------^
```

## Step to reproduce
Create a page with a '&' in the slug.

**Comment by Keats** [comment]
I guess we should mark the URLs as safe in the template, didn't think of that. Another reason to implement https://github.com/Keats/tera/issues/368 so we can have a url_safe or whatever

**Comment by ianare** [comment]
Sorry I don't follow (maybe I was a bit vague).
It seems like the problem here is that '&' is not valid in the XML, it should be encoded as '%26'.
I don't see how marking the variable as safe would fix that.

**Comment by Keats** [comment]
I was the one wasn't clear :p 
The current template marks URLs as safe (https://github.com/getzola/zola/blob/master/components/templates/src/builtins/sitemap.xml#L4) which is obviously wrong as you can see it.
The fix would be to have a `url_safe` filter as mentioned in the Tera issue that escapes fewer things, including &.

**Comment by Keats** [comment]
Nevermind, I completely forgot Tera already has a `urlencode` filter. It should use that...

**Comment by Keats** [comment]
Should be fixed on the `next` branch!

**Comment by Keats** [comment]
It seems that url encoding causes issues in other tools. 
Did you specify the slug for that page directly? If so, we probably need to check that the slug is a valid slug otherwise you can get special characters in.
