### ISSUE TITLE
Can zola hard link files from static/?

### ISSUE THREAD

**Issue by yacoob** [getzola/zola#710]
It's a feature request, not a bug :) I'm considering zola for a site that's graphic-heavy - right now it's about 1GB of images. Preferably, I'd like to keep them in `static/`. My current bespoke generator hardlinks the images to save time, as most of the time my input and output directories are siblings on the same filesystem. Is there any chance zola could hardlink files as well when asked for in `config.toml`?

My plan B would be to run `zola build` and hardlink the images outside of zola.

Thanks for considering this!

**Comment by yacoob** [comment]
FWIW, with ~1GB of images, first build with `zola serve` took ~15s, subsequent builds ~2s. Disk cache? :D Funnily enough, this optimization is important primarily for local development - Netlify (which I use) keeps images in LFS and doesn't check them out during build, so the speedup would be minimal there.

**Comment by Keats** [comment]
What would be the configuration? Specify which files/directories to hard link? It seems a bit niche to me

**Comment by yacoob** [comment]
I'd see it as `hard_link_static = true` in `config.toml`. It'd make a hard link in `public` for every file in `static`, leaving the directories as they were. There'd need to be a same fs check, or good failure handling. Yup, it's a bit niche, in a sense it'd only be useful for people with non-trivially sized `static/` directory. It'd help preserve the speed of the generator though :)

**Comment by yacoob** [comment]
This looks straightforward enough - I can take a stab at a PR. Are you interested, or do you consider this too niche for inclusion?
