### ISSUE TITLE
Add an option for get_url to return a relative URL

### ISSUE THREAD

**Issue by yacoob** [getzola/zola#711]
Hopefully you don't mind more feature requests :)

I prefer to use relative URLs wherever possible, just to make the generated HTML cleaner and more concise. As far as I can tell, `get_url` always returns an absolute url (using base_url, etc.). Would it be possible to add a parameter to make `get_url` return a relative URL? For example, `get_url(path="./about/_index.md")` returns `http://127.0.0.1:1111/about/` when served via `zola serve`. Can it return `/about/`?

Thanks for considering this! :)

**Comment by yacoob** [comment]
Hmm, this might be doable by doing `get_section`/`get_page` and grabbing its `current_path`.

**Comment by yacoob** [comment]
Ah, almost. `current_path` is present on a page, but not in a `section` object. Is `section.path` the correct equivalent?

**Comment by Keats** [comment]
`current_path` is just present on each page/section as a variable, it's not part of the page/section variable itself. As you mentioned, page.path and section.path are what you're looking for

**Comment by yacoob** [comment]
Allright, so this turns into a request for a syntactic sugar.
```
{{ get_url(path=foo,relative=true) }}
```
vs
```
{% set s = get_section(path=foo) %}
{{ s.path|safe }}
```

I leave it up to you whether it's worth implementing. :>

**Comment by Keats** [comment]
it's not as simple, you also need to pass the current_path to the get_url fn explicitely

**Comment by sermuns** [comment]
Is this implemented?

**Comment by MaxIhlenfeldt** [comment]
Looking at https://github.com/getzola/zola/blob/master/components/templates/src/global_fns/files.rs#L65, I don't think so. I also don't think the workarounds mentioned in this issue work for every case. I'd like to have a way to build a site that's independent of the URL it's being served at, which I think would be possible if `get_url` could return relative paths.
