### ISSUE TITLE
The requested port is not available in watch-only mode

### ISSUE THREAD

**Issue by Kaperstone** [getzola/zola#712]
# Bug Report
Trying to use Zola to watch and build, while having a web server running.

## Environment
Ubuntu 19.04

Zola version: latest

## Expected Behavior
To watch & build on changes made, without checking whether it the web server can start with the provided information.
I am trying to use Zola to build only, without serving.

## Current Behavior
Can only use `zola build --output-dir /var/www/html -u https://example.com -p 80` but cannot use it in combination with watch ( `zola serve --watch-only --output-dir /var/www/html -u https://example.com -p 80` ) because it will check if the port is available and output
```
The requested port is not available
```
because I have a web server already running on the port to serve those files.

## Step to reproduce
Run a web server on port 80 and attempt to run this line.
```
zola serve --watch-only --output-dir /var/www/html --base-url https://example.com -p 80
```

**Comment by Keats** [comment]
Use `zola serve --watch-only` to not start the webserver

**Comment by Kaperstone** [comment]
Have tried it with `--output-dir`, but it still requests from the wrong url, in my `config.toml` file I've set the `base_url` to my domain, but on the web files it requests resources and links to 127.0.0.1:1111
```
GET https://127.0.0.1:1111/site.css net::ERR_CONNECTION_REFUSED
```

P.S. I'm using Using `after-dark` theme, if it contributes anything.

**Comment by Keats** [comment]
I'm not sure I follow. You have a webserver running and you want to have your zola site displayed in it while having the live reload working?

**Comment by Kaperstone** [comment]
Okay, I have tested it in a complete clean scene
I have created a new file:
`zola-project/templates/index.html`
```
{{ get_url(path="site.css", trailing_slash=false) | safe }}
```
my config file `zola-project/config.toml`
```
base_url = "https://example.com"
compile_sass = false
highlight_code = false
build_search_index = false
[extra]
```
running command `zola build` produces
(content of `zola-project/public/index.html`)
```
https://example.com/site.css
```
running command `zola serve --watch-only` produces
(content of `zola-project/public/index.html`)
```
http://127.0.0.1:1111/site.css
```

so both modes use different base_url, although base_url is the same in the config.toml, and isn't provided as argument in the commandline.

EDIT:
> I'm not sure I follow. You have a webserver running and you want to have your zola site displayed in it while having the live reload working?

I do not want it to live-reload or have the web server, I only want it to re-build as I edit the files.

**Comment by Keats** [comment]
It seems like we can just ignore the port checking in watch-only mode and it should work as expected.

**Comment by Keats** [comment]
I've pushed a commit to the `next` branch that should fix it

**Comment by Kaperstone** [comment]
I've jumped on and recompiled and it finally works! Although, the output of the url is:
command: `zola serve --watch-only --base-url https://example.com -80 --output-dir /var/www/html`

```
http://https://example.com:80/site.css
```
Port 80 can be omitted and I use ssl.

content of `zola-project/templates/index.html`
```
{{ get_url(path="site.css", trailing_slash=false) | safe }}
```

content of `zola-project/config.toml`
```
base_url = "https://example.com"
compile_sass = true
title = "after-dark theme"
description = ""
[extra]
```

EDIT: got around that, it still outputs the port, but works 😄 
```
zola serve --watch-only --base-url example.com -p 443 --output-dir /var/www/html
```

**Comment by Keats** [comment]
Are you running the zola serve command on a server? It's only meant for local development

**Comment by Kaperstone** [comment]
I am running on a server, but not using the web server on Zola or its live reload for production mode, thus why I output it to a different folder, where my own production web server picks up the static files and serves them.
As I said before, I use Zola to build the files only, because I found Zola to be pretty easy and comfortable to build a personal website.

**Comment by Keats** [comment]
It's unlikely that the serve command will be modified to allow that since people would think it's fine to run it as a server, which is definitely not the case. Especially since the serve reload can miss some changes as the reload checking is not 100% perfect.

**Comment by Kaperstone** [comment]
Yeah, I am not implying to make a change to the serve command, but it would be nice if the `build` option had its own option to watch for file changes and rebuild automatically.

No live reload, no web server, just `watch` and `build` on changes.
