### ISSUE TITLE
live reload themes 

### ISSUE THREAD

**Issue by iEverX** [getzola/zola#713]
I think it would be nice if live reload would listen to changes of themes directory.

Motivation: 
I use git submodule to manage my theme. Now, when I changed the theme, I must restart zola to make it take effect, which is not interesting

**Comment by Keats** [comment]
I am not going to work on that myself but would take a PR.

**Comment by iEverX** [comment]
thanks

**Comment by awulkan** [comment]
This is the most wanted feature for me. If anyone could solve this I'd be very happy!

On top of this, in the current state of Zola, if you restart the server it ends up serving on a different port as well. So you have to stop the server, open the new page and close the previous one every time you make a small change to the template.
