### ISSUE TITLE
build site failed when reach

### ISSUE THREAD

**Issue by iEverX** [getzola/zola#714]
# Bug Report

## Environment

Win 10 build 1903

Zola version: 0.7.0

## Expected Behavior
build should success

## Current Behavior
```
thread 'main' panicked at 'unexpected node in tree: Header(1)', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\pulldown-cmark-0.4.1\src\parse.rs:1019:29
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: onig_get_encoding
  17: <unknown>
  18: onig_get_encoding
  19: onig_unicode_define_user_property
  20: BaseThreadInitThunk
  21: RtlUserThreadStart
```

## Step to reproduce

1. zola init site
2. create a file post/hello-world.md in content directory, file content is 
```
+++
title = "hello world"
date = 2019-06-22
+++

# |

```
Note that there is anewline after `# |` line.
3. zola serve or zola build

Other information:
1. if no newline after `# |` line, it would be no error
2. if put a `'\'` just before `'|'`, that is make `# |` to `# \|`, it would be no error

**Comment by Keats** [comment]
It should be already fixed in the `next` branch if you want to give it a try! I *think* i'll release 0.8.0 tomorrow unless something unexpected comes up
