### ISSUE TITLE
livereload.js version?

### ISSUE THREAD

**Issue by igor-raits** [getzola/zola#716]
Hello,

I've packaged zola for Fedora, however since livereload.js is bundled, I need to find out version which zola ships.. It seems like it is 2.2.1, but I am not sure...

If you could keep in some readme list of those bundled things with their versions, would be awesome.

Also 3.0.0 is out, so you might want to upgrade :)

**Comment by Keats** [comment]
I don't remember, at the time the generated js was not working so I git cloned and built my own version. Probably 2.2.1 since I remembered the repo not having received any commit for years at the time

**Comment by samford** [comment]
For what it's worth, I did a quick test to swap the current livereload.js with version 3.0.0 and it appears to work fine without any modifications.  Just to be clear, I used the minified file (dist/livereload.min.js) from the 3.0.0 release archive.

Feel free to test out my [livereload-3 branch](https://github.com/samford/zola/tree/livereload-3) and I'll create a pull request if you have any interest in updating this.

**Comment by Keats** [comment]
Please do the PR yes!

**Comment by awulkan** [comment]
This can be closed now since it's merged, right?

**Comment by Keats** [comment]
I'll close it when the next version is released
