### ISSUE TITLE
Is there a way to get pages variable containing all pages?

### ISSUE THREAD

**Issue by yacoob** [getzola/zola#717]
I'd like to put links to newest 3 pages on my main page. It'd be very convenient to get my hands on `pages` variable that RSS feed receives. I've tried naively different variations of `get_page(path="/rss.xml")` but without much luck. Judging by the [code](https://github.com/getzola/zola/blob/master/components/site/src/lib.rs#L985) of `render_rss_feed` it's a special case and you don't normally have any way of getting list of all pages.

I can sweep through all sections that I care about, extract all pages and sort them. Any nicer way? :)

I'm really enjoying zola so far, it's just so much nicer to work with than hugo :D Thanks! ❤️

**Comment by Keats** [comment]
That won't be possible sadly as it would kill performance on big sites. If all the pages you care about are in the same section (let's say `blog/`), you could mark it as transparent and get the first/last 3 pages of the index section.

**Comment by yacoob** [comment]
OK, so my options are either `transparent = true` to hoist the pages up high enough or explicit enumeration. I think I'll go with the latter, as it'll only happen in one place, and it'll save on the amount of data being punted around.

Thanks for the clarification!

**Comment by alexpetros** [comment]
Although I would _love_ access to that pages variable in my `index.html` (maybe behind a config, if there are performance concerns?), I was able to fudge this using [Tera's concat feature](https://keats.github.io/tera/docs/#concat).

```jinja
{% set blog_section = get_section(path="blog/_index.md") %}
{% set talks_section = get_section(path="talks/_index.md") %}
{% set pages = blog_section.pages | concat(with=talks_section.pages) %}
```
