### ISSUE TITLE
Release notes / What's new in x release

### ISSUE THREAD

**Issue by j1mc** [getzola/zola#721]
# Documentation issue

## Summary
When a new release is tagged on Github, there is no easy way to identify what is new / what has changed with a release. I think it's important for the project to identify such things, as new releases spark interest in a project, but if people can't tell what is new, then it gives them less incentive to explore the new features. If they can see what is new, though, it may give them reason to check out those features and further explore the project.

## Proposed solution
I think we should integrate [changelong](https://docs.rs/git-changelog/0.3.1/changelog/) into the project to make it easier to track what has changed from one release to another. This will make it easier to identify new changes without adding too much administrative overhead to the project.

**Comment by Keats** [comment]
What's the difference with https://github.com/getzola/zola/blob/master/CHANGELOG.md ?

**Comment by iEverX** [comment]
@Keats would you please add a link to the change log when release a new version? Didn't find there's a change log before

**Comment by j1mc** [comment]
Hi @Keats --- Thanks, even linking to the changelog from the github release would suffice.

I use an RSS feed reader to track github releases, and having any kind of link from the release to your changelog would help people like me.

**Comment by Keats** [comment]
I have added a link to the Release on GitHub, I will try to remember about it for the next releases.

**Comment by j1mc** [comment]
Thanks!
