### ISSUE TITLE
sitexmap produce wrong url

### ISSUE THREAD

**Issue by iEverX** [getzola/zola#722]
# Bug Report

## Environment

Zola version: 0.8.0

## Expected Behavior
site map should work well

## Current Behavior
```
<url>
    <loc>http%3A//127.0.0.1%3A1111/</loc>
</url>
<url>
    <loc>http%3A//127.0.0.1%3A1111/archive/</loc>
</url>
```

Currently, generating a url in simemap use following code

```
{{ sitemap_entry.permalink | urlencode | safe }}
```
Seeing the commit, 3513846, I think this is what you expected. However, this sitemap.xml is not recognized by google console.

**Comment by Keats** [comment]
Hmm I think the google console is complaining about the port no? But yeah encoding is a bit too aggressive still...

**Comment by iEverX** [comment]
@Keats this is an example. the real sitemap.xml has no port. 

And, another problem is "namespace is not correct", about urlset

**Comment by Keats** [comment]
https://support.google.com/webmasters/answer/183668?hl=en#sitemapformat for the Google reference on sitemap format

Is there a public validator or do I need to add a property to check the validation?

**Comment by iEverX** [comment]
In google console, you must have a domain to add a sitemap. And I found some validators, also should submit with a url. These validators told that the sitemap (the version removed urlencode from template) has no error, though google console complains.

For the second problem about namespace, I change the xmlns to `http://www.sitemaps.org/schemas/sitemap/0.9`, then google gives no error.
Changes are 
1. https to http
2. remove /sitemap.xsd from url.

I didn't try the changes one by one, so i have no idea whether both changes are needed.

**Comment by Keats** [comment]
I've pushed a fix to use the correct namespace on the `next` branch.
