### ISSUE TITLE
`zola check` should output some numbers because it's incredibly fast ... 

### ISSUE THREAD

**Issue by ralfbiedert** [getzola/zola#726]
# Bug Report

## Environment

Zola version: 0.8.0

## Expected Behavior
The first few times I was running `zola check` on my existing page it was terminating so fast that I didn't believe it actually checked external links ...

First of all, this is totally amazing and a great improvement over 0.7 ❤️

To avoid confusion, it would be nice if `zola check` could output some "positive" information, e.g., statistics on the nature and number of checks it performed, for example:

```
Check results:
Pages processed: 5.
External links checked: 43 (43 good).
Internal links checked: 11 (11 good).
...
```

Such a list would also let people know what is being part of a `check` run.

**Comment by Keats** [comment]
Good idea!
