### ISSUE TITLE
`anchor-link.html` overrides anchor completely 

### ISSUE THREAD

**Issue by ralfbiedert** [getzola/zola#727]
# Bug Report

## Environment

Zola version: 0.8.0

## Problem
Ok, I'm not 100% if this is really a bug or if I'm missing the intent, but apparently having an `anchor-link.html` overrides the whole `a class...` target, not just the content of that `a`.

For example, when I don't set anchor links, the following default HTML is produced:

`<a class="zola-anchor" href="#organizing-code" aria-label="Anchor link for: organizing-code">🔗</a>`

However, when I do set an `anchor-link.html` with the content `<sup>#</sup>`, I would expect my anchors to look like this:

`<a class="zola-anchor" href="#organizing-code" aria-label="Anchor link for: organizing-code"><sup>#</sup></a>`.

Instead, they are produced like this:

`<sup>#</sup>`

The problem with the current behavior is that I (seemingly) lose the ability to reproduce the `href="#organizing-code"` part.

**Comment by Keats** [comment]
There should be a `id` variable available in the template but it doesn't seem documented.
