### ISSUE TITLE
Cross Compilation fails with sass-rs

### ISSUE THREAD

**Issue by jbz-dev** [getzola/zola#728]
# Bug Report
  - Cross compiling from x86 PC to armv7-unknown-linux-gnueabihf fails with
```
  = note: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: /tmp/rustcxoW2Uy/libsass_sys-9d9ae0eb621c9a95.rlib: error adding symbols: file format not recognized
          collect2: error: ld returned 1 exit status
```

## Environment
  - Fedora 30 x86_64
  - Rustup with armv7-unknown-linux-gnueabihf target
  - Rust v1.35

I do not understand why, I tried to build a simple Rust hellow world bin with sass-rs and it works.

**Comment by jbz-dev** [comment]
For those wanting to use zola on ARMv7 devices but are failing to get it compile, there is a fedora package [here](https://koji.fedoraproject.org/koji/buildinfo?buildID=1295398).

You can extract it with `rpm2cpio <package> | cpio -id`.

Fully working on Raspbian Buster.

**Comment by Keats** [comment]
Might be related to the version of sass-rs used? Zola does not have a custom build so if a sass-rs sample works it should work.

**Comment by jbz-dev** [comment]
Found the solution.

`cmake` must be installed on the host OS. Not really obvious (at least for me).

Building is working and binary is OK.
