### ISSUE TITLE
Built-in Sass support

### ISSUE THREAD

**Issue by Keats** [getzola/zola#73]
That's the only reason I still need npm/yarn to build a theme

Unresolved questions:

- no postcss support?

**Comment by max-bertinetti** [comment]
You can use also npm/yarn for minify css / javascript / image / html and using critical for the above the fold css. Doing so you can reach 100/100 in google test for mobile and desktop speed...wich is good doing sites for customers

**Comment by Keats** [comment]
I agree that it can be useful to have a pipeline setup but for a large chunk of cases, just having scss is enough. I don't minify HTML or JS (if I have any JS) for my static sites, I compress images manually when I add them so for my own cases just having Sass built-in will allow me to not worry about npm/yarn at all. 

Ideally gutenberg could have a complete pipeline built-in but I'm a bit afraid of how much it would bloat it

**Comment by max-bertinetti** [comment]
So I can simply build a grunt script for automatically doing this in codeship before deploy.

**Comment by Keats** [comment]
Yep you're still free to have your own pipeline, I just want my usecase to not require node anymore :p

There are bindings at https://github.com/compass-rs but it doesn't seem updated/finished so it would need checking it what's needed for those crates to be usable (if something is needed).

**Comment by Keats** [comment]
I updated sass-sys and sass-rs to the latest version (wip at https://github.com/Keats/sass-rs/tree/merge-sys) but it doesn't work on Windows. My only access to Windows is appveyor (https://ci.appveyor.com/project/Keats/sass-rs) so it is very frustrating to debug, not to mention I don't know anything about Windows.

If anyone is on Windows and can help debugging the branch above, that'd be great.

**Comment by Keats** [comment]
Note that the last commit on https://github.com/Keats/sass-rs/tree/merge-sys can be reverted, I was just trying to use mingw instead of VS to see if that would work

**Comment by Keats** [comment]
For the latest update: https://github.com/compass-rs/sass-rs/pull/11

cc @reillysiemens since you are interested in that feature

**Comment by JabZuda** [comment]
Could something like [rsass](https://github.com/kaj/rsass), as used in [ructe's static-sass example](https://github.com/kaj/ructe/tree/master/examples/static-sass) work here?

**Comment by Keats** [comment]
Whoa didn't see ructe or rsass. I think rsass if it catches up to libsass will definitely be used in the future but it seems like it's not complete enough right now.

**Comment by pkgw** [comment]
You can download short-term but full-featured Windows VMs from Microsoft [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). I've found them great for working on Windows problems — I've had the same experience of going nuts trying to figure things out via a painfully slow Appveyor debugging cycle.

**Comment by Keats** [comment]
Yeah I've done that before but the process was still painful on my old laptop. Thanks for the comment though!

Sass support seems to work for OSX and Linux now looking at the `next` branch but there are still issues with OSX and Windows: https://github.com/compass-rs/sass-rs/issues/12
