### ISSUE TITLE
404.html doesn't get rerendered during zola serve when its parent template chagnes

### ISSUE THREAD

**Issue by yacoob** [getzola/zola#731]
# Bug Report
Looks like the part of zola that decides what to rebuild ignores `404.html` template during `zola serve`.

## Environment

Zola version: 0.8.0 under OSX

## Expected Behavior
Create two simple templates:

`base.html`:
```jinja
<html><body>
{% block main %}{% endblock main %}
<hr />
<pre>
{{ __tera_context | escape}}
</pre>
</body></html>
```
and
`404.html`:
```jinja
{%- extends 'base.html' %}
{%- block main %}
We're lost!
{%- endblock main %}
```

`404.html` should be re-rendered when `base.html` gets updated during `zola serve`.

## Current Behavior
If you start `zola serve` and change `base.html`, `404.html` opened in the browser doesn't reload. In fact it doesn't get rebuilt at all - if you reload the page, old version of `base.html` is shown.

## Step to reproduce
Start `zola serve` with two templates as above. Change `base.html` (eg. add another `<hr />`). Wait for zola to pick up the change. Visit `http://127.0.0.1:1111/404.html`. The change you've made is not visible on the page. Restart `zola serve`. Reload the page. The change is now visible.

**Comment by yacoob** [comment]
Same behaviour discovered with `rss.xml` that includes `macros.html`; run `zola serve`, modify `macros.html`, no change in rendered `rss.xml` until you restart zola.

**Comment by awulkan** [comment]
Edit: Nvm, I think it's another issue. 
___
Idk if my problem is the same, but I'm trying to override a template from a theme, without success. If I change a part in the theme, it is instantly reflected in the served site, but if I Ctrl + Z and save it again, the server just keeps on loading, with a blank screen. I have to restart the server again to get it working.

**Comment by Keats** [comment]
CTRL + Z will continue running zola in the background. If you want to stop it, do CTRL+C. Not sure if that will help this issue but at least you won't have hidden processes using ports.

**Comment by awulkan** [comment]
@Keats That's not what I meant. I meant that if I reversed a change in a template file (that is used for overriding a theme template) and then save the file again, the whole site goes blank and the browser ends up in a never ending loading state.

**Comment by Keats** [comment]
@awulkan do you have a reproduction? I've never seen that. Which browser?

**Comment by awulkan** [comment]
@Keats I don't have a way to reproduce it right now, so just disregard it for now.

I used Crome, but it's possible that it was because of me using Windows Subsystem for Linux, which I also had some other problems with until I switched to poweshell. 

All I did was to download a theme, then I tried to override a template.
