### ISSUE TITLE
subsections when using paginate_by

### ISSUE THREAD

**Issue by ranfdev** [getzola/zola#733]
# Documentation issue

## Summary
When using paginate_by, the ```section.subsections``` array is always empty.
The documentation doesn't say anything about this.

## Proposed solution
Explicitly say that when using pagination, you can't list subsections

**Comment by Keats** [comment]
It was removed a while back, we can probably add it back now.

**Comment by Keats** [comment]
It's back in the `next` branch.

**Comment by ranfdev** [comment]
Thank you!
