### ISSUE TITLE
Add jsonfeed to zola

### ISSUE THREAD

**Issue by uwearzt** [getzola/zola#737]
Add https://jsonfeed.org/ to zola. That looks much nicer than the RSS format.

**Comment by Keats** [comment]
I've never used it, is that actually adding something that normal RSS can't do or is it just another format?

**Comment by uwearzt** [comment]
Basically contains the same information, but is much nicer to parse. At the moment podcasts and podcast apps start to adopt it. See also the description and some examples in the spec https://jsonfeed.org/version/1 .

If you are willing to merge, i will give it a shot in the next time (maybe in August).

**Comment by Keats** [comment]
We have both RSS and atom now, I don't think jsonfeed is very popular so it's not going to be built in. It should be possible to generate one through `feed_filename` now though.

**Comment by Leon0824** [comment]
I would like to make a JSON feed template. If so, should I make a pull  request to merging into this repository?

**Comment by uwearzt** [comment]
@Leon0824 yes, you can create a pull request for that. I will help @Keats with a review and test om my website.
