### ISSUE TITLE
Template function to fetch remote file

### ISSUE THREAD

**Issue by timvisee** [getzola/zola#738]
I'd like to see a function to use in templates which fetches a remote file.

In my case, I would like to fetch remote thumbnails for YouTube videos. But I can imagine that this is useful as well for other cases

### Semantics
This function could look like this:

```tera
fetch_raw(url="...") -> Url
```

- This is similar to `load_data`, in the sense that it fetches remote data
- This is similar to `resize_image`, in the sense that the command returns an URL for the locally stored file (to `static/processed_images`) in this case.

Modifying the existing `resize_image` function to support a remote `url` would be an option for me as well.

What are the thoughts on this? Could this be implemented?

**Comment by swiftcoder** [comment]
I'd love to see not just the ability to fetch a remote file, but to perform arbitrary API requests. That would let us do things like fetch comments from a database at build time (which would in turn allow integration with things like webmentions.io).

**Comment by Keats** [comment]
load_data can do arbitrary requests

**Comment by averyvigolo** [comment]
I'd like to support this feature request. I can't find docs for a similar feature in Hugo or Jekyll, but here's the use case I want it for:

- I want my website to have icons from an icon set
- I don't want to...
  - serve them through a CDN
  - load them with JavaScript
  - manually download each one and check them into my version control

Ideally my content would simply reference the icons I want, and Zola would download the ones I need and serve them under `public/`.  
E.g. something like:

```htmldjango
<img src="{{ download_url(url="https://example.com/img.svg", path="icons/") }}" />
```

Would download that file and save it as `public/icons/img.svg`. I could then make a Tera macro or shortcode to make it even easier to declare what remote content I want to serve on my own site.
Having `load_data`'s caching would also be great.

**Comment by Keats** [comment]
if you can hardcode things in the template, why not download it first manually and put it in static?

**Comment by averyvigolo** [comment]
> if you can hardcode things in the template, why not download it first manually and put it in static?

With a template these downloads could be automated, and be done on-demand as my site contents allows it. I'd like to minimise the amount of stuff in the source for my website if possible
