### ISSUE TITLE
Rendering a section may create an unnecessary empty directory

### ISSUE THREAD

**Issue by reillysiemens** [getzola/zola#74]
I have a site with the following layout
```
content
├── pages
│   ├── about.md
│   ├── projects.md
│   └── resume.md
└── posts
    ├── git-filter-wat
    │   ├── git-filter-wat.png
    │   ├── index.md
    │   ├── messed-up-git-graph.png
    │   ├── oh-but-it-does.png
    │   ├── signature-doesnt-match-committer.png
    │   └── verified-commits.png
    ├── hexo-init-blog.md
    └── _index.md
```
Organizing my content this way makes a lot of sense to me. I have a collection of `pages` that I want to render normally and then I have `posts` as a logical section. Each of my posts defines a date-formatted URL like
```toml
url = "2015/04/24/hexo-init-blog"
```
Currently rendering these posts leads to a directory structure in `public` like this
```
public
├── 2015
│   └── 04
│       └── 24
│           └── hexo-init-blog
│               └── index.html
├── 2016
│   └── 04
│       └── 07
│           └── git-filter-wat
│               ├── git-filter-wat.png
│               ├── index.html
│               ├── messed-up-git-graph.png
│               ├── oh-but-it-does.png
│               ├── signature-doesnt-match-committer.png
│               └── verified-commits.png
├── about
│   └── index.html
├── index.html
├── keybase.txt
├── main.css
├── posts
├── projects
│   └── index.html
├── resume
│   └── index.html
├── robots.txt
├── rss.xml
└── sitemap.xml
```
This is _almost exactly_ what I want, but because of the way `site.render_section` is currently written the `section.components` may be created even if no `page.path` depends on them (the empty `posts` directory in this case)
```rust
let mut output_path = public.to_path_buf();
for component in &section.components {
    output_path.push(component);

    if !output_path.exists() {
        create_directory(&output_path)?;
    }
}

if render_pages {
    for page in &section.pages {
        self.render_page(page)?;
    }
}
```
I'd be more than happy to take a stab at fixing this if you consider it an issue, but I wanted to check that this is a change you'd be open to before creating a PR.

If there's another way to achieve the same effect sans the `posts` directory that's more in keeping with the current section/page generation I'm also happy to adjust my project  accordingly. 😄

**Comment by Keats** [comment]
If you want the `posts` section to not be rendered, you can put `render = false` in its front matter and it should only render the pages (https://github.com/Keats/gutenberg/blob/master/src/site.rs#L581 in 0.0.5)

If that doesn't fix it, I would wait a bit for the PR, I will land https://github.com/Keats/gutenberg/pull/68 very soon

Unrelated but I *think* dates in URLs are not that great for SEO currently (ie if google sees an old date, it would rank it lower than other content even if the content is valid)

**Comment by Keats** [comment]
Ah I think I missed the point, you already use `render = false` right?
You can do a PR for that on my PR I linked in the previous post if you have time!

**Comment by reillysiemens** [comment]
Yes, I'm already using `render = false` in `content/posts/_index.md`.

It's late here, so I may not get to looking at it until tomorrow. Please don't slow down v0.0.6 on my account. I figure I'll try to establish whether the `section.components` are in any of its child `page.path`s and only create the directory if it isn't.

As for the SEO, that's something I hadn't considered before. I may have to revise my naming scheme. Thanks for the heads up!

**Comment by reillysiemens** [comment]
@Keats: I finally sat down to do this, but decided to grapple with my own naming scheme first on account of your SEO recommendation. I determined that having a date in my URL isn't necessary or even particularly helpful, so I'll probably just use sections normally.

As such, this isn't an issue for me any more. If you think it's still worth doing then I'll give it a shot, but I'd also be just as happy to forget about this altogether. Your call. 😀

**Comment by Keats** [comment]
I think it makes sense to not create empty folders, I'd welcome a patch on the `next` branch when you have time!

**Comment by Keats** [comment]
@reillysiemens are you working on that?

**Comment by reillysiemens** [comment]
@Keats: My apologies. No, I haven't been. Ran into a real busy streak, but I should have time to take a look at this soon. 😅

**Comment by Keats** [comment]
No owrries, it's not urgent at all

**Comment by reillysiemens** [comment]
@Keats: I really owe you an apology. I haven't had time to take a look at this at all and unfortunately I don't think I'll be likely to find it in the near future.

I'll check back on this at a later point, but if anyone else picks it up in the meantime that'll be fine.

**Comment by Keats** [comment]
Don't worry, I'm busy as well so I understand!

**Comment by Keats** [comment]
Now that the rendering is done in parallel, this is kinda hard to fix - it would have to happen once the build is done. I guess walking through the public directory and deleting empty folders but it might mess up some people workflow if they have a script copying stuff later.
Not sure what to do

**Comment by reillysiemens** [comment]
I honestly don't know much about `rayon`, so I'm not confident on what's to be done here either, but unless I'm mistaken you still parse all the front matter for all pages/sections before launching into parallel Markdown rendering, right?

If that's true then you should be able to know all of the directories you'll need to create before you actually go create them (which you could still do in parallel). If you had a directory serving as a logical container for documents (as in my example above) then it wouldn't be present in any of the `path`s and you should be able to remove it from the set of directories ahead of time.

Does that assessment seem wrong to you?

**Comment by Keats** [comment]
>  you still parse all the front matter for all pages/sections before launching into parallel Markdown rendering, right?

Yes

I believe it would work, but need to check it's not too bad in terms of performance

**Comment by Keats** [comment]
No movement on this and this isn't a big deal. 
Closing this for now
