### ISSUE TITLE
“Smart” typographic punctuation

### ISSUE THREAD

**Issue by wezm** [getzola/zola#740]
This is a feature request for support for proper typographic quotes, apostrophes, en and em dashes, and ellipsis. It would be great if Zola had the ability to (optionally) filter Markdown through a process akin to [Smarty Pants](https://daringfireball.net/projects/smartypants/) to turn plain text quotes, etc. into the proper typographic form.

The transformations that Smarty Pants performs are:

- Straight quotes ( " and ' ) into “curly” quote HTML entities
- Backticks-style quotes (``like this'') into “curly” quote HTML entities
- Dashes (“--” and “---”) into en- and em-dash entities
- Three consecutive dots (“...”) into an ellipsis entity

**Comment by Keats** [comment]
This should probably go into pulldown-cmark though, there is a related issue for it there: https://github.com/raphlinus/pulldown-cmark/issues/119

**Comment by Keats** [comment]
Going to close this as, if this goes in, it will be in pulldown-cmark

**Comment by nixberg** [comment]
With [`v0.8.0`](https://github.com/raphlinus/pulldown-cmark/releases/tag/v0.8.0), `pulldown-cmark` supports [smart punctuation](https://github.com/commonmark/cmark/blob/master/test/smart_punct.txt).

**Comment by Keats** [comment]
Yep I will enable it in 0.12 if I have time but otherwise in 0.13

**Comment by Keats** [comment]
Re-opening. I'm updating pulldown-cmark to 0.8 in 0.12 but will write the code to add smart ponctuation for 0.13 since I want to make it an option and will add maybe a few more options in the next version.

**Comment by dertuxmalwieder** [comment]
One of the problems I can see with this is that this partially breaks full i18n support. For example, „German quotation“ is not quite the same thing as “U.S. quotation”.

**Comment by ErichDonGubler** [comment]
> One of the problems I can see with this is that this partially breaks full i18n support. For example, „German quotation“ is not quite the same thing as “U.S. quotation”.

@dertuxmalwieder: I'm confused. The suggested changes here include a processing step to convert `"text"` into `“text”`, but AFAICT the only flow currently available for getting the German punctuation you reference via Gutenberg is just using `„text”` in your content source directly. This means that the German punctuation flow shouldn't change. Am I misunderstanding something?

**Comment by dertuxmalwieder** [comment]
Well, either all languages must be supported or Zola needs to skip all non-English content files - or else the punctuation will be wrong.

**Comment by ErichDonGubler** [comment]
> Well, either all languages must be supported or Zola needs to skip all non-English content files - or else the punctuation will be wrong.

You're making this same assertion that something will break, and that's what I'm trying to dive into/validate -- is this an abstract concern for you, or do you have specific cases in mind where content may be broken?

**Comment by dertuxmalwieder** [comment]
“Broken” is the wrong word here. It would cause wrong punctuation in most languages, that’s all.

**Comment by ErichDonGubler** [comment]
> “Broken” is the wrong word here. It would cause wrong punctuation in most languages, that’s all.

I guess I use "breakage" in this context because the behavior in question (how content is generated/processed) seems fundamental enough to the function of an SSG that it can/should be considered part of its correctness.

I'm going to assume your concern is abstract (which is fine!). I think it's valid, and I hope it doesn't seem like the validity of your concern is in question. That said, getting concrete cases where smart punctuation might adversely affect users will likely be very beneficial in the discussion you were trying to motivate in how smart punctuation should be integrated, and that's why I wanted to drive the elaboration of those cases.

**Comment by Keats** [comment]
This is enabled in the `next` branch
