### ISSUE TITLE
Netlify instructions broken

### ISSUE THREAD

**Issue by vegai** [getzola/zola#745]
I set up Netlify according to the instructions in https://www.getzola.org/documentation/deployment/netlify/ -- this was the result:

```
10:04:33 AM: Executing user command: ZOLA_VERSION=0.8.0 zola build
10:04:33 AM: /usr/local/bin/build: line 34: zola: command not found
```

**Comment by vegai** [comment]
This was fixed by providing the default netlify.toml, though. So perhaps the first part of the Automatic Deploys documentation should be just removed?

**Comment by Keats** [comment]
I've updated the instructions in the commit above, let me know if that works for you

**Comment by vegai** [comment]
It does! Thank you.

**Comment by niklaas** [comment]
Uff, took me some time to realize that my site was using the old build image. I had to switch to the new one in the admin interface. Unfortunately, I found no way to specify the build image in `netlify.toml`. It seems, the old image does not support `zola`.

**Comment by Keats** [comment]
The old image only supports old version of Gutenberg and is not updated.
