### ISSUE TITLE
How to use subsections in templates

### ISSUE THREAD

**Issue by manu-cyber** [getzola/zola#746]
# Documentation issue

## Summary

I’m having a hard time figuring out how to use subsections, and the documentations of zola and tera don’t help me much. Also the non-existent `get_section` function is still referenced in some places.

## Detail

I’m trying to build a website with one tree-like, hierarchical section, similar to a wiki for example.

```
$ tree content/
content/
├── _index.md
├── [...]
├── weblog
│   └── […]
└── wiki
    ├── _index.md
    └── software
        └── _index.md
```

In order to navigate through them, I need to make use of the `subsections` array in my `section.html` template.  
The Zola documentation on sections in themes says this:

```
[...]
// Direct subsections to this section, sorted by subsections weight
// This only contains the path to use in the `get_section` Tera function to get
// the actual section object if you need it
subsections: Array<String>;
[...]
```

The `get_section` function doesn’t exist in Tera, and I guess it has been replaced by the `get` function which is documented like this:

```
get
Access a value from an object when the key is not a Tera identifier. Example: {{ sections | get(key="posts/content") }}
```

Now in my `section.html` I would like to have the url and names of a section’s subsections. Those should be associated with the objects I have to get. I try to achieve that like this:

```
{% for subsection in section.subsections %}
  {{ section | get(key=subsection) }<br>
  <a href="{{ subsection | safe }}">some label</a><!-- this doesn't work of course -->
{% endfor %}
```

The build fails with the following error:

```
Failed to build the site
Error: Failed to render section '/home/mgr/create/web/manuelgross.de/content/wiki/_index.md'
Reason: Failed to render 'section.html'
Reason: Filter `get` tried to get key `wiki/software/_index.md` but it wasn't found
```

From the `__tera_context` I can’t see which object I need to call `get` on, and from the available documentations I’m fairly uncertain if I’m using it correctly in the first place.

If someone can confirm to me how it’s supposed to be used or how I otherwise achieve the desired tree-like structure, I’m happy to provide pull-requests for the documentation myself.

## Proposed solution

Add a quick example on how to use subsections and especially how to get the object from the keys in the `subsections` array.  
Or just let me know how it’s meant to be used and I’ll try to improve the documentation myself via pull-requests :)

**Comment by Keats** [comment]
Zola defines a few additional Tera functions like get_section: https://www.getzola.org/documentation/templates/overview/#get-section

The docs definitely need to be improved though

**Comment by manu-cyber** [comment]
Thanks for the super quick response. I completely overlooked this function in the documentation. I’ll think about how to improve that part so impatient people like me have a better chance of finding it. I’ll close this now and send some proposals once I got everything working. Cheers!

**Comment by segeljakt** [comment]
Was there any solution to this? I'm getting:

```
Error: Failed to build the site
Error: Failed to render section '/Users/klasseg/Workspace/zola-websites/juice/content/_index.md'
Error: Reason: Failed to render 'index.html'
Error: Reason: Function call 'get_section' failed
Error: Reason: Page `mysection/_index.md` not found.
```
