### ISSUE TITLE
xmpp URL generation breaks

### ISSUE THREAD

**Issue by ghost** [getzola/zola#747]
given
```
[foo@bar.tld](xmpp:foo@bar.tld)
```
the following is generated:
```
<a href="http://127.0.0.1:1111/xmpp:foo@bar.tld">foo@bar.tld</a>
```

Is this intended Markdown behavior or can this parsing of URIs be improved?

Expected result was an xmpp:... in the href.

**Comment by Keats** [comment]
Which version of Zola? Sounds like a bug

**Comment by Keats** [comment]
I've added a test for it in the `next` branch but it seems to be doing the right thing there: `<p><a href="xmpp:foo@bar.tld">foo@bar.tld</a></p>`

**Comment by ghost** [comment]
This is on df720a5bafd1c4c408e2a136713aad40e01149d1, I'm trying a new build soon to see if it is fixed.

Thanks.

**Comment by Keats** [comment]
Is it working for you?

**Comment by ghost** [comment]
I can try this weekend if I can schedule some time for this.

**Comment by ghost** [comment]
Okay, we can probably close this. I'm wrapping up packaging the 0.8 release for pkgsrc-wip today and will test a newer commit for my personal checkout. I'm fairly positive that your test is alright, I'll reopen this if I run into the issue again.

Thanks!
