### ISSUE TITLE
v.0.0.5 rendering of articles in category page is random

### ISSUE THREAD

**Issue by max-bertinetti** [getzola/zola#75]
I don't find a way to order by date this page. Every compilation give different order

**Comment by Keats** [comment]
Yes, it's a known issue - also in 0.0.6: https://github.com/Keats/gutenberg/blob/master/src/content/taxonomies.rs#L112-L115

I wasn't sure whether there are usecases where categories/tags are used other than blog posts but I can't think of any. I'll add that or welcome a PR for 0.0.7
