### ISSUE TITLE
crash within the ctrlc handler

### ISSUE THREAD

**Issue by southerntofu** [getzola/zola#752]
# Bug Report

## Environment

Zola version: next branch

## Expected Behavior
When i hit ^C, zola serve should end.

## Current Behavior
If the output folder is missing for some reason, the program never quits and in my case did not even respond to SIGTERM. It output:
```
thread 'ctrl-c' panicked at 'Failed to delete output directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Not providing a backtrace because the problem/fix is obvious.

## Step to reproduce
Mistakenly run a second `zola serve` from the same folder. Quit the second zola using ^C. Output folder is deleted. Attempt to quit the first zola. Panic.

## Fix

```
src/cmd/serve.rs
-        remove_dir_all(&output_path).expect("Failed to delete output directory");
+        if remove_dir_all(&output_path).is_err() {
+            console::warn("Failed to delete output directory");
+        }
```

**Comment by Keats** [comment]
Thanks, it's fixed in `next`

**Comment by southerntofu** [comment]
Thanks
