### ISSUE TITLE
Unexpected behaviour: `zola init .`

### ISSUE THREAD

**Issue by matthiasbeyer** [getzola/zola#754]
# Bug Report

## Environment

Zola version: 0.8.0

## Expected Behavior

Zola initializes the current directory with a new site.

## Current Behavior

```
Failed to create the project
Error: Folder `.` already exists
```

## Step to reproduce

`mkdir test && cd test && zola init .`

**Comment by wucke13** [comment]
Can confirm this.

**Comment by Keats** [comment]
Duplicate of https://github.com/getzola/zola/issues/406
Still looking for someone willing to implement it

**Comment by matthiasbeyer** [comment]
Closing in favour of #406
