### ISSUE TITLE
Search index generation fails

### ISSUE THREAD

**Issue by jeskew** [getzola/zola#756]
# Bug Report

## Environment

Zola version: 0.8.0 (installed via snap on Ubuntu 19.04)

## Expected Behavior

Setting `build_search_index` to `true` in `config.toml` should cause a search index to be generated when running `zola build` or `zola serve`.

## Current Behavior

Setting `build_search_index` to `true` in `config.toml` causes both `zola build` and `zola serve` to fail with the following output:

```
$ RUST_BACKTRACE=1 zola build
Building site...
-> Creating 43 pages (0 orphan), 1 sections, and processing 0 images
Failed to build the site
Error: Failed to create "public/search_index.en.js"
Reason: No such file or directory (os error 2)
$
```

## Step to reproduce

Run a build with a copy of zola installed via snap. I assume I must be missing a dependency but can't figure out how to fix it.

**Comment by Keats** [comment]
> Run a build with a copy of zola installed via snap. I assume I must be missing a dependency but can't figure out how to fix it.

No, the error is IO related. I am guessing you are not using the Sass support? Either way I think I've located the issue and it will be fixed in the next version.

**Comment by jeskew** [comment]
You're correct; I was not using the Sass compilation feature. Enabling that let me build a search index without issues. Thanks for the quick fix on this!
