### ISSUE TITLE
Caching issue when auto-rebuilding changes in zola serve

### ISSUE THREAD

**Issue by timotheos-firestone** [getzola/zola#757]
# Presumed caching issue with `get_section()` content in `zola serve`

## Environment

Linux Mint
Zola version: 0.8.0

## Expected Behavior
When `zola serve` detects changes, it should always rebuild the site as if from a fresh `zola serve` run.

## Current Behavior
`zola serve` detected changes and rebuilt, but didn't actually rebuild the content correctly (used old section data).

## Step to reproduce
I am using this code in my `section.html` to generate my navigation section.

When I change one of the target subsections (e.g. edit the title), this block isn't regenerated automatically when `zola serve` rebuilds based on the file change. I have to Control+C to exit the `zola serve` and run the command again for it to work.

```
{% block navigation %}
<div id="navigation">
	{% set index_section = get_section(path="_index.md") %}
	{% if index_section %}
	<ul>
	{% for nav_path in index_section.subsections %}
		{% set nav_section = get_section(path=nav_path) %}
		{% if nav_section %}
		<li><a href="{{ nav_section.permalink }}">{{ nav_section.title }}</a></li>
		{% endif %}
	{% endfor %}
	</ul>
	{% endif %}
</div>
```

I presume this is caused by a caching issue.

Not sure if it's related to #719.

**Comment by Keats** [comment]
> When zola serve detects changes, it should always rebuild the site as if from a fresh zola serve run.

Ideally yes, but in practice it would be too slow for big sites :( Eg if you're working with 1000+ pages that would be a change from a few ms on content change vs a few seconds. It does suck when working with templates though

**Comment by Keats** [comment]
> When zola serve detects changes, it should always rebuild the site as if from a fresh zola serve run.

It's now doing exactly that!
