### ISSUE TITLE
Add ability to emit warnings from theme template code

### ISSUE THREAD

**Issue by timotheos-firestone** [getzola/zola#758]
## Environment

Zola version: 0.8.0

## Suggested behavior

Add something like a `{% warning("message") %}` directive (or, if it exists, document it somewhere clearer).

### Example usage 

```
{% if page.date %}
{{ page.date }}
{% else %}
{% emit_warning(var=page, message="The page does not have a date, but this theme is designed to use it! The rendered page may look sub-par.") %}
{% endif %}
```

## Current Behavior
I am currently designing a theme around very drafty pages, and I don't want to have to update all my pages to test out a particular look. I also want the theme to be robust to be able to handle other people's content, which might not have all the recommended data.

I'd imagine it's a very common use case for someone new to Zola to try existing themes before they build their own. That's what I did, and all the themes broke because all my drafty pages didn't have required data (e.g. `page.date`).

I've added checks for `null` values in my theme, but then that silently masks that the content lacks the recommended data.

Adding the ability for a theme maintainer to check for `null` but also emit a warning to remind the content maintainer to complete the recommended values would be ideal.

It would be much more helpful to have `zola` spit out 100 warnings so the content maintainer can fix them all in one pass, rather than the repetitive cycle of "fix one error, run the terminal command again, fix the next error..." 100 times.

`zola` could also take a `treat_warnings_as_errors` parameter to keep the old behaviour, if the user really wants to break their build if the content isn't fully conformant to the theme's expectations.

I'd also recommend upgrading the existing off-the-shelf themes to use this, because I was almost driven away from Zola in the frustration of having no off-the-shelf theme that would work for all my preexisting Markdown files.

**Comment by Keats** [comment]
Tera already has the `throw` function that will make the template rendering error. I don't think a warning makes sense though, depending on the theme you NEED to adapt your markdown to it, eg a themes that uses pagination will need to have all the pagination setup. In theory a theme should indicate what it needs to be setup and it should have an example site.

**Comment by timotheos-firestone** [comment]
I'm sure some themes would NEED certain Markdown adaptations, but the example usage of `page.date` is more relevant to what I'm talking about than pagination. It doesn't _really_ matter if a page is rendered without a date, it's just that the theme prefers it and it would make all the pages consistent. Navigation shouldn't be fundamentally broken because a page's optional post date isn't shown - it just seems like arbitrary inflexibility.

Another potential option would be to have _that page_ error and then it wouldn't include _that page_ in the final build output, but would continue to build other pages; however, that functionality should be a different consideration to the warning feature, which I still want to make my theme more robust.

Having to update all pre-existing (especially non-Zola) Markdown files to a theme can be a huge overhead, especially if the theme might not even fit, and beginner Zola users don't really know enough to know what's wrong. Again, having hundreds of files but having them only fail one-at-a-time can be very frustrating and I think it's important to improve usability for these cases.

**Comment by Keats** [comment]
The main issue with warnings is what if the user doesn't want to actually have a `page.date`? They will have `n` warning printed everytime and the fix would be to edit the theme to delete that.

> Again, having hundreds of files but having them only fail one-at-a-time can be very frustrating and I think it's important to improve usability for these cases.

They would get hundreds of lines in the console instead, which isn't much better.

I do think this is best resolved by the theme documentation than with a feature.

**Comment by timotheos-firestone** [comment]
They will have a warning printed in the console but it's not going to stop them develop their site. That's the main thing: the current behaviour is to break and not even build the site.
Hundreds of lines in the console _is_ much better, because, as I said, it allows all the problem pages to be identified in one sweep (allowing for batch fixes) and also doesn't stop development of the site. Importantly, it allows the theme user to estimate the time cost involved in porting their content to fit the theme's ideals, whereas the current error-on-problem approach means the theme user won't have any idea how many more errors might come up, so will be more likely to give up on the theme or Zola.

Also, the user could have a switch to turn off warnings, or it's much easier to edit a theme to delete a warning than to edit a theme to add an `if`-check to fix (one or multiple) errors (because the error messages are not very clear to new users exactly what is erroring.

The main issue is that a user downloads Zola, downloads a theme, tries it with simplistic Markdown (which most likely will contain very minimal front-matter) and it breaks. The average user will blame Zola, not even realising it was a theme problem (that's certainly what I thought the first many times I tried it, and almost gave up). 

A self-documenting, discoverable user interface is better than documentation. Personally, speaking generally, I think the "rtfm" attitude in open source is a problematic culture that inhibits adoption, and so I think focussing on usability concerns like this one, especially new user stories, is actually highly important :)

**Comment by Keats** [comment]
No one else requested that or supported it, closing.
