### ISSUE TITLE
zola serve does not work on snap install (other os error) - Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by gwelr** [getzola/zola#761]
# Bug Report
Just installed zola using `sudo snap install --edge zola`. I have created a project with `zola init <projectname>`.  Going into the project, I launch `zola build`which is working fine. Then I start `zola serve` but this tell me it could not find the content directory
## Environment
Ubuntu 18.04.01 LTS
Zola version: 0.8.0 (edge)

## Expected Behavior
zola serve is able to look for the content directory and watch it. 

## Current Behavior
```sh
laptop:~/Projects$ zola init test-zola
Welcome to Zola!
> What is the URL of your site? (https://example.com): http://i-logs.com   
> Do you want to enable Sass compilation? [Y/n]: n
> Do you want to enable syntax highlighting? [y/N]: n
> Do you want to build a search index of the content? [y/N]: n

Done! Your site was created in "/home/ani/Projects/test-zola"

Get started by moving into the directory and using the built-in server: `zola serve`
Visit https://www.getzola.org for the full documentation.
laptop:~/Projects$ cd test-zola/
laptop:~/Projects/test-zola$ zola serve
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
Done in 17ms.

Error: Can't watch the `content` folder. Does it exist?
Reason: other os error
laptop:~/Projects/test-zola$
```
## Step to reproduce
1. Install zola using snap on ubuntu 18.04.1 LTS 
2. init a new project 
3. go into that project 
4. start zola build (ok) 
5. start zola serve (Failed with error `Can't watch the `content` folder. `)

## Additional information
1. I did install and use zola successfully on a Ubuntu 16.04 LTS. the 
2. I've also seen an error saying zola could not find the config.toml file but could not catch it
3. I've also tried to run zola serve/build on an existing project (fetched with git) but without success.

**Comment by Keats** [comment]
Hmm that's weird, can anyone on ubuntu try building it using the snap config in the repo? It might be some missing permissions

**Comment by gwelr** [comment]
Ok, after a bit of investigation we have found the issue. Neither is it  directly related to Zola, nor is it a bug in the underlying inotify subsystem but rather a inotify configuration issue. 

On ubuntu, there is a soft limit to the number of files and directories which can be monitored for change by inotify. By default,  inotify limit is set to 8192 on ubuntu (which is surprisingly rather low). If you hit this value while trying to watch more files and directories, you'll get an error (`Failed with error Can\'t watch the content folder` as far as Zola is concerned).

What we did to fix the issue: 
1. change the limit on the running system: 
   ```sh
   echo 16384 > /proc/sys/fs/inotify/max_user_watches
   ```
2. make this change permanent (and safe for reboot): 
   ```sh
   sudo echo "fs.inotify.max_user_watches=16384" >> /etc/sysctl.conf
   ```

Please note that 16384 is a convenient value on our system but you might need some higher value. You can check the current value by running `cat /proc/sys/fs/inotify/max_user_watches` . 

Hope this help someone.
