### ISSUE TITLE
Link to RSS feed breaks in linkchecker

### ISSUE THREAD

**Issue by manu-cyber** [getzola/zola#764]
I want to include a link to my RSS feed on my website and created a shortcode that’s doing this: `get_url(path="rss.xml", trailing_slash=false) | safe`

It basically works, but the linkchecker in `zola serve` of course doesn’t find the URL (since it’s only about to be hosted) and aborts the build. Any other option I’m aware of would also end up just inserting a link to `$base_url/rss.xml` into the page.

Is this a bug, or am I doing it wrong (again)?

**Comment by Keats** [comment]
Ah that's an interesting issue...
I guess the link checker could ignore links to the own site that are rss/sitemaps?
What do you mean by the link checker in `zola serve` though? There should only be internal link checking at that time.

**Comment by manu-cyber** [comment]
I mean when running `zola serve` it seems to be checking for `https://127.0.0.1/rss.xml`, which oviously doesn't exist, since the server isn't running yet. That's because my shortcode includes the base URL. I think leaving it out would also result in a build error though.

When the base URL is a website that has already been deployed, and an RSS feed is generated with that website, the build itself works (running `zola build` instead of `zola serve`).

**Comment by Keats** [comment]
Looking at the code again, links in HTML content are not checked so that's even weirder. I can't reproduce it either :/

**Comment by manu-cyber** [comment]
Hm, now it works for me too, I can’t reproduce it anymore. Weird.
