### ISSUE TITLE
Publish github @ gh-page branch.

### ISSUE THREAD

**Issue by shirshak55** [getzola/zola#765]
Currently I am trying to publish but there is some problem . It would be useful if we can write a docs about it too.

I want to use gh-pages branch as it seems cleaner approach than changing public directory to docs.

After running `zola build` we will see a public directory.

So what we do is publish content inside public directory to gh-pages branch. 

For that I need to add public to gitignore file

```
echo "public" >> .gitignore
```

After that we will initiliaze orphan branch
```
git checkout --orphan gh-pages
git reset --hard
git commit --allow-empty -m "Initializing gh-pages branch"
git push origin gh-pages
git checkout master
```

After this we will use git worktree feature
```
rm -rf public
git worktree add -B gh-pages public origin/gh-pages
```

After this we will build and publish it
```
zola build
cd public && git add --all && git commit -m "Publishing to gh-pages" && cd ..
```

But the thing is I don't see files inside public uploaded to github. Can anybody help me to do it? I am not git guru so I am expecting some help.

After this go to Settings → GitHub Pages and select gh-page branch.

**Comment by shirshak55** [comment]
I found it zola delete the publish folder so it removes the .git file which is required for github workdir. So I think its the bug of zola as it should not delete .git file inside work dir.  

Hugo don't have problem like this :) >>

By the way thanks for providing Rust Alternative to Hugo :)

**Comment by Keats** [comment]
If you don't delete `public`, how do you not end up with bad files in there? Eg if you delete a post it would still be in the public directory or does Hugo just does not delete `.git`?
I'm not using github for hosting so if someone wants to investigate, feel free!

**Comment by shirshak55** [comment]
Hmm I wonder how hugo is solving this problem. Yea I am now using travis and its fine but for this I need to use python pip bla bla bla which I don't like actually.

**Comment by shirshak55** [comment]
You are also correct that if we don't delete public useless file may start to collect and ... I wonder how are we supposed to solve this issue.

**Comment by therealprof** [comment]
Just ran into the same problem. Are you using a `user` or `org` GH pages repo by chance? If so you can only publish custom HTML pages from the `master` branch: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

I'm currently figuring out which changes are needed to get the zola code out of `master` and make the Travis job publish there instead.

**Comment by therealprof** [comment]
Got it. So here's what I did:

1. The zola sources where moved to a new branch code (which I also made the default branch in GitHub)
2. The example code for the Travis CI script was adjusted as follows:
```
after_success: |
  [ $TRAVIS_BRANCH = code ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  zola build &&
  sudo pip install ghp-import &&
  ghp-import -n public -b master &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
```

So basically I changed the branch check from `master` to `code`. Then I had to tell `ghp-import` to use the `master` branch instead of the default `gh-pages` and last but not least the `git push` also changed from `gh-pages` to `master`.

After this hour long detour I can now finally start working at the content, after finishing up a few chores...

**Comment by Keats** [comment]
Can that be summarised in some docs in the documentation?

**Comment by shirshak55** [comment]
its written at last part of docs

**Comment by therealprof** [comment]
@shirshak55 Sorry, I don't follow. The problem is that the documented approach does not work in the vast majority of cases since GitHub doesn't serve custom built HTML from gh-pages anymore so zola can't be used as documented.

@Keats I'll look into creating a PR probably later today.

**Comment by shirshak55** [comment]
it works for me. cheeck shirshak.dev and its repo at github is at
shirshak55/shirshak.dev

**Comment by therealprof** [comment]
@shirshak55 

That's because you're using a custom domain. It would not work if you were publishing to e.g. shirshak55.github.io .

**Comment by shirshak55** [comment]
hmm i added custom domain later.

**Comment by shirshak55** [comment]
Alright I get it . Lets discuss remaining stuff in PR https://github.com/getzola/zola/pull/780
