### ISSUE TITLE
Can't Compile Zola on Windows 10

### ISSUE THREAD

**Issue by jrsmith17** [getzola/zola#767]
# Bug Report

## Environment
Windows 10

Zola version: 0.8.0

## Expected Behavior
cargo build should compile the zola project without errors

## Current Behavior
It first asked for me to install the Windows 8.1 SDK (for not sass). Which is odd because I have a more up to date SDK, but I guess it's looking for that specific version. Installing that then popped up the error message(s) (for sass) that it couldn't find `stddef.h`. I went digging through the target folder from the error message (pasted below). I found where the vcxproj file thinks it's including from, but that's definitely not where stddef.h lives.

I started to think about how to approach this issue. But since it's a fairly complex dependency chain, I thought I should reach out to see if you've encountered this particular issue before proceeding any further.

         d:\projects\zola\target\debug\build\sass-sys-17c2460a1ed38ad0\out\build\include\sass\base.h(26): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory [D:\Projects\zola\target\debug\build\sass-sys-17c2460a1ed38ad0\out\build\win\libsass.vcxproj]

## Step to reproduce
Clean git clone. Attempt to run cargo build. I already have Visual Studio 2017 installed. I later added Windows 8.1 SDK to my machine.

**Comment by Keats** [comment]
Can you try https://github.com/compass-rs/sass-rs#building-windows ?

**Comment by jrsmith17** [comment]
That error message refers to a different issue that I wasn't getting on my local machine. That said, I clicked through to their referenced MS documentation to see if setting the different environment variables they referred to would make a difference. No such luck.

I'll poke at this issue for a few more evenings to see if it's worth pursuing or if I decide to give up and just use my Macbook.

**Comment by Keats** [comment]
Let's close that issue and open it on sass-rs repo instead, it really is a pain to build on Windows :/

**Comment by jrsmith17** [comment]
Hey, sorry. I meant to circle back and say this could be closed. I was instead taking notes on the things I was building but weren't explained fully in the docs. I'll reach out on discourse once I have a more finished thought ready to share.
