### ISSUE TITLE
Support get_image_metadata for SVG

### ISSUE THREAD

**Issue by mre** [getzola/zola#769]
# Bug Report

My blog mostly uses SVG as an image format. This way, images are crisp while still being small. @killercup and me recently noticed that posts get redrawn when an image gets loaded on the page. [Here is an example](https://matthias-endler.de/2019/maybe-you-dont-need-kubernetes/). Although a minor annoyance, it's not very visually pleasing.

One idea was to set the width and height of the image and there is the handy `get_image_metadata` builtin, but it does not support SVG yet.

## Environment

Zola version: 0.8.0

## Expected Behavior

The following shortcode should work for SVG:

```
{% set meta = get_image_metadata(path=page.path~src) %}
<img src="{{ src }}" height="{{ meta.height }}" width="{{ meta.width }}" />
```

## Current Behavior

Error: Failed to render content of snippet.
Reason: The Decoder does not support the image format `Image format image/"svg" is not supported.`

## Suggestion

For the case where the SVG file has a `viewBox` attribute set, we could use that extract the width and height from it. In case the attribute is not set, we could throw and error with a hint about the missing `viewBox`.

## Alternative approach

Previously I used [lqip](https://matthias-endler.de/2017/image-previews/) on my blog, but I did not port it when I moved from [cobalt.rs](https://github.com/cobalt-org/cobalt.rs) to zola.
I could dig that up again, but I was hoping to avoid that if possible and rather go with a more general solution.

**Comment by Keats** [comment]
All the image processing currently relies on https://crates.io/crates/image
Since SVGs are a different beast, it would need to pull a different crate. I am not sure whether it makes sense to add SVG support to the resize_image function either?

**Comment by mre** [comment]
That's true and I did not find any crate, which allows for reading the `viewBox`. If nobody knows of such a crate, I could write one. Would adding support for that have a chance to be merged?

`resize_image` is related, but in my book it would be fine if it only supported a subset of the formats of `get_image_metadata`. Also, I'm not sure how SVG resizing should behave: would it rasterize the image a la [resvg](https://github.com/RazrFalcon/resvg) or simply adjust the `viewBox`? So I'd not leave that out for now.

**Comment by Keats** [comment]
I'm not sure how SVG resizing should behave either :p
I think it would make sense to add support to SVG for `get_image_metadata` if there is a crate for it

**Comment by mre** [comment]
>  ...if there is a crate for it

[Well, now there is.](https://github.com/mre/svg-metadata) 😆 

It's not much, but I think it provides the functionality that we need. Maybe you can have a look and tell me what you think. We could then go ahead and create a PR for zola, which uses the crate.

**Comment by Keats** [comment]
Could you add tests for a few dozens of random SVGs to ensure it works correctly?

**Comment by mre** [comment]
Good idea, will do.

**Comment by mre** [comment]
Added some test data from public sources now. Parsing works for all of those, so we should be good. If I can do anything else, please let me know. 😃

**Comment by Keats** [comment]
Can you do a PR to add it to Zola?

**Comment by Keats** [comment]
@mre ping

**Comment by mre** [comment]
Whoops. Thanks for the ping. See #792.

**Comment by Keats** [comment]
@mre if you have time for a new PR, I'll take it.
