### ISSUE TITLE
Valid dates get stripped out of filenames during build

### ISSUE THREAD

**Issue by flowerornament** [getzola/zola#770]
# Bug Report

## Environment

Zola version: 0.8

## Expected Behavior

A file named `2017-11-14-update.md` should render to `/2017-11-14-update/`.

## Current Behavior

A file named `2017-11-14-update.md` renders to `./update/`.

Example: https://github.com/urbit/urbit.org/tree/master/content/posts

**Comment by Keats** [comment]
That's not a bug, that's a feature. It extracts the date from the filename so you can have your files sorted by dates in a folder. It's basically interpreted as `date-slug`. If you want to keep the date in the slug, you will need to define the `slug` attribute in the front-matter

**Comment by flowerornament** [comment]
@Keats gotcha, thanks!
