### ISSUE TITLE
Complicated questions on initial init

### ISSUE THREAD

**Issue by PriceChild** [getzola/zola#773]
# Bug Report
```
$ zola init pricey-blog
Welcome to Zola!
> What is the URL of your site? (https://example.com): https://blog.example.com
> Do you want to enable Sass compilation? [Y/n]:
```
I'm immediately wondering...
* What is Sass compilation?"
* Is Sass compilation important?
* Can I change my mind later?
* Why isn't it mentioned [in the instructions](https://www.getzola.org/documentation/getting-started/cli-usage/#init)?

## Environment

Zola version: 0.8.0

## Expected Behavior
Less questions or more advice.

## Current Behavior
See above.

## Step to reproduce
```
zola init
```

**Comment by Keats** [comment]
Thanks, I've added some text on zola init.
I'm not going to explain what Sass is in the command itself though as there is https://www.getzola.org/documentation/content/sass/

**Comment by JoePricey** [comment]
@Keats Brilliant thanks!

I managed to completely miss that bit of documentation too earlier so that's really useful thank you.
