### ISSUE TITLE
number_pagers typo?

### ISSUE THREAD

**Issue by spl** [getzola/zola#775]
I noticed that `number_pagers` is used throughout. For example, in the documentation:

```rust
// How many pagers in this paginator
number_pagers: Number;
```

Should this be `number_pages` (minus the second `r`) instead? Thus, the comment above would read “How many **pages** in this paginator.”

Renaming the variable is a breaking change, but I just wanted to make you aware of it.

**Comment by spl** [comment]
Just for context, at 1cc0295637a32a88a7db03e40c6ae8c8d317f3f2:

```
$ git grep number_pagers
components/library/src/pagination/mod.rs:        paginator.insert("number_pagers", to_value(&self.pagers.len()).unwrap());
components/site/src/sitemap.rs:        let number_pagers =
components/site/src/sitemap.rs:        for i in 1..=number_pagers {
components/site/src/sitemap.rs:                let number_pagers = (item.pages.len() as f64
components/site/src/sitemap.rs:                for i in 1..=number_pagers {
docs/content/documentation/templates/pagination.md:number_pagers: Number;
test_site/templates/index_paginated.html:                Num pages: {{ paginator.number_pagers }}
test_site/templates/section_paginated.html:    Num pagers: {{ paginator.number_pagers }}
test_site/templates/tags/single.html:    Num pagers: {{ paginator.number_pagers }}
test_site_i18n/templates/auteurs/single.html:    Num pagers: {{ paginator.number_pagers }}
test_site_i18n/templates/authors/single.html:    Num pagers: {{ paginator.number_pagers }}
```

**Comment by spl** [comment]
I found this comment in `components/library/src/pagination/mod.rs`:

```rust
/// Pages split in chunks of `paginate_by`
pub pagers: Vec<Pager<'a>>,
```

So, I can accept that `number_pagers` may not be typo. However, in my ignorance and my defense, I have never seen the word “pager” used in this fashion, and <https://www.getzola.org/documentation/templates/pagination/> does not define it.

I can imagine that it might be hard to find the right word to use here, since you're paginating into multiple pages but “page” already has a precise technical meaning in Zola. Still, it would help to add a few words explaining “pager” and/or `Pager` in the documentation.

**Comment by Keats** [comment]
The term is taken from Hugo.
I can't think of a better term :/ but I can add some explanations

**Comment by spl** [comment]
Got it. I think that's the best practical solution. Thanks!
