### ISSUE TITLE
[Feature Request] Autoprefixer

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [getzola/zola#779]
Autoprefixers parse CSS and adds vendor prefixes. This creates consistency so that a developer on Firefox creates the same webpage on Chrome, Opera, and Edge as they have on their own browser. 

I have found [this](https://github.com/lemonrock/css-autoprefix) but it hasn't been touched in two years and is incomplete. Is this something this project would be interested in?

**Comment by Keats** [comment]
It would be somewhat interesting but that adds a lot of complexity to Zola configuration:

-  we need something equivalent to https://github.com/browserslist/browserslist in Rust as well so you can do `last 2 versions`
- autoprefixer has a lot of options: https://github.com/postcss/autoprefixer#options, if we want to be compatible that would mean basically doubling the number of config fields in config.toml. Even if they are in an `[autoprefixer]` block, we still need to document them on the zola site.

I think for now it's a no but if there is a mature & actively maintained equivalent for both browserlist and autoprefixer, it would certainly make sense.

**Comment by Keats** [comment]
I've created https://zola.discourse.group/t/add-autoprefixer/176/2 so it's not forgotten

**Comment by psnszsn** [comment]
I think the right path would be to add PostCSS support. This would allow the use of [autoprefixer](https://github.com/postcss/autoprefixer), but also other PostCSS plugins, like [Tailwind CSS](https://github.com/tailwindcss/tailwindcss). It should work like sass (add files to the `postcss` dir and the output appears in `public`). The `postcss.config.js` file should probably also be in the `postcss` dir, so no extra config fields in `config.toml` needed.
That would mean running the postcss executable form rust. Is that a no-go? (this is also the way Hugo does it)

**Comment by Keats** [comment]
> That would mean running the postcss executable form rust. Is that a no-go? (this is also the way Hugo does it)

I'm not super interested in that approach, the main draw to Zola for me is that it is a single binary. Having to install node + npm install some libraries is not a great workflow imo. If you wanted to do that, you don't need to go through zola imo you can just write a small make file for it.

**Comment by Tazeg** [comment]
I'd like to use Tailwind CSS with Zola. 
With "Hugo" this can be done : https://gohugo.io/hugo-pipes/postcss/ like this : 

```bash
cd my-project
yarn global add autoprefixer postcss-cli
yarn add tailwindcss @fullhuman/postcss-purgecss --dev
hugo serve
```

**Comment by Keats** [comment]
yeah, might as well use npm/yarn scripts at this point so you can call exactly what you need.

**Comment by Tazeg** [comment]
But then "zola serve" might have some tasks to do with it, that I can't explain.

**Comment by martinmcwhorter** [comment]
@Keats It looks like there are two crates that may solve some of this: 

https://docs.rs/css-autoprefix/0.0.5/css_autoprefix/
https://docs.rs/css-purify/0.0.15/css_purify/

If I made a PRs that integrate these optionally into Zola would you consider this?

**Comment by Keats** [comment]
(I've replied on the forum thread)

**Comment by austinbutler** [comment]
> (I've replied on the forum thread)

Don't think it's linked here, but this appears to be the thread: https://zola.discourse.group/t/add-postcss-support/556
