### ISSUE TITLE
[Feature Request] Automatic Summary

### ISSUE THREAD

**Issue by ghost** [getzola/zola#783]
So right now we have to use `<!-- more -->` to control what page.summary outputs, but I was thinking it would be easy to implement a way for zola to automatically produce a summary that is the first *n* characters for example. 

The use case is for a page that has a list of all the  blog posts, including a snippet of the first *n* characters of the post content. Maybe not a summary in the strictest sense, more like a preview?

**Comment by Keats** [comment]
You can do something like `{{ page | truncate(length=100) }}` in the template

**Comment by ghost** [comment]
Just tried `{{ page.content | truncate(length=200) | safe }}`, it seems like that's pretty much what I was looking for.
