### ISSUE TITLE
`render_image()` param update don't trigger image processing

### ISSUE THREAD

**Issue by zdenek-crha** [getzola/zola#790]
# Bug Report

## Environment

Zola version:

## Site setup

* shortcode using `resize_image()`
* Tera template using `resize_image()`

[resize_image_dont_create_image_on_update.zip](https://github.com/getzola/zola/files/3556403/resize_image_dont_create_image_on_update.zip)

## Step to reproduce

* start `zola serve`
* open in browser
  * new tab with page using `render_image()` through shortcode
  * new tab with Tera template using `render_image() directly
* update `render_image()` parameters (`height, width, fit`)

_Note: Similar issue is triggered by adding **new** instance of shortcode using `render_image()` into page (ie to add image to page content)._

## Expected Behavior

After reload preview images rendered by `render_image()` are displayed with updated dimensions/fit.

## Current Behavior

After reload tab uses uri of processed image with updated dimensions, but the image itself does not exist yet. Browser shows 'broken image' placeholder graphics.

If shorcode with new image was added, its html is rendered, but only broken image placeholder is shown.

_Note: I have got name of new processed image through web developer tools and tried to find it on disk and it **was not** present. It appeared only after I have restarted `zola serve`.

## Workaround

Start and stop `zola serve` to trigger processed image rebuild, then reload.

**Comment by Keats** [comment]
Thanks, that's now fixed in the `next` branch.
