### ISSUE TITLE
Any way to remove the anchor icon?

### ISSUE THREAD

**Issue by ghost** [getzola/zola#795]
# Bug Report

When using anchor links there is an ugly link icon next to the section heading. IS there anyway to deactivate this? I'm trying to find the chunk of css I'd need to change but don't see it

**Comment by Keats** [comment]
There is no CSS associated, that's the unicode character.
You can override the template itself by creating a `anchor-link.html` template in the templates directory and put whatever you want in it. The templates gets a single variable: `id`
