### ISSUE TITLE
image 0.22

### ISSUE THREAD

**Issue by igor-raits** [getzola/zola#798]
Hello,

maintainer of Zola in Fedora here. It would be great if you could update image dependency to 0.22.x :)

Thanks in advance!

**Comment by samford** [comment]
The image dependency was updated to 0.22 in [a commit about a month ago](https://github.com/getzola/zola/commit/e74dab535d4df617f6362d1d33b70b5f4ab6030e), so this is currently in the `next` branch and will be merged into `master` with the next release.

**Comment by igor-raits** [comment]
I see, what is the ETA for new release?

**Comment by Keats** [comment]
No specific ETA apart from https://github.com/getzola/zola/issues/768 being done since it's a big breaking change that needs to be done all in one go.
