### ISSUE TITLE
Post template won't load [extra] TOML data

### ISSUE THREAD

**Issue by bryanlehrer** [getzola/zola#809]
# Bug Report

## Environment

Zola version: 0.8.0

## Expected Behavior
I am working with two templates and attempting to insert [extra] data defined in a given page's markdown file.

The insertion in both instances is identical:

1)
`  {% set section = get_section(path="workshops/_index.md") %}
  {% for page in section.pages %}
    <div class="project">
      <div class="project-inner-container">
        <div class="project-title">{{page.title}}</div>
        <div class="workshop-leader-small">Lead by {{page.extra.leader}}</div>
        <div class="project-description">{{page.description}}</div>
        <a target="_self" class="project-link internal-link" href="/workshops/{{page.title}}">More Info →</a>
      </div>
      <div><img class="project-image" src="{{page.title}}.png"></div>
    </div>
  {% endfor %}`

2
`<div class="workshop-leader-large">Lead by {{page.extra.leader}}</div>`

## Current Behavior
When I delete the first instance the site builds fine. When included I get get build error:
`Failed to build the site
Error: Failed to render section '/Users/bryanlehrer/Documents/GitHub/otherinternet-research/content/workshops/_index.md'
Reason: Failed to render 'workshops.html'
Reason: Variable `page.extra.leader` not found in context while rendering 'workshops.html'`

**Comment by Keats** [comment]
Extra is always loaded and passed as is. Are you sure every page has a `leader` in extra? No typos/missing?

**Comment by bryanlehrer** [comment]
Yep this one was on me, apologies.

Did not have the `leader` in every page.  

Thanks for the help - zola is great!

**Comment by Graywolf9** [comment]
I just came to comment that it was to hard to found that the own extra var use like this `{{page.extra.leader}}` XD
