### ISSUE TITLE
Should have LICENSE file for livereload.js or hide serve cmd behind a feature

### ISSUE THREAD

**Issue by kanru** [getzola/zola#81]
Hi! I just noticed this project today and was poking around the source code. I found the serve command embeds a livereload.js file in the final binary. Nowhere in the source mentions that where is the origin of livereload.js and its license.

I believe it's released under MIT license so there is no problem at all to distribute it with gutenberg.
However, in order to ease the packaging work in the future (Arch, Ubuntu, etc.) and for paranoid minds, the source repository should at least include the license and pointing to the upstream location. Bonus point to also include non-uglifyed source.

**Comment by Keats** [comment]
Good point, I've added the license in the `serve.rs` file https://github.com/Keats/gutenberg/pull/77/commits/0037f743cdad0622f7e0470f2333d8f216e287da
