### ISSUE TITLE
`zola init` fails in existing empty directory 

### ISSUE THREAD

**Issue by demurgos** [getzola/zola#814]
# Bug Report

## Environment

Zola version: Github master branch
OS: Linux

## Expected Behavior
> Tell us what should have happened.

Running `zola init` in an empty directory should initialize the directory.

## Current Behavior
> Tell us what happens instead of the expected behavior. If you are seeing an
> error, please include the full error message and stack trace. You can get the
> stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.

Example run:
```
$ RUST_BACKTRACE=1 ../zola/target/debug/zola init
Welcome to Zola!
Please answer a few questions to get started quickly.
Any choices made can be changed by modifying the `config.toml` file later.
> What is the URL of your site? (https://example.com): 
> Do you want to enable Sass compilation? [Y/n]: 
> Do you want to enable syntax highlighting? [y/N]: 
> Do you want to build a search index of the content? [y/N]: 
Failed to create the project
Error: File exists (os error 17)
```
As you see, the initialization fails with a "File exists" error. The error message could be improved to mention which file exists: it took some digging in the issues to figure out why it failed. (Running `zola init mydir` works, it's initializing the current empty dir that fails).

## Step to reproduce
> Please provide the steps to reproduce the issue.
> If the issue is hard to reproduce, please provide a sample repository or sample
> that triggers the bug.

Create an empty directory, go inside and run `zola init`.

## Related issues

- https://github.com/getzola/zola/pull/406
- https://github.com/getzola/zola/pull/777

**Comment by Keats** [comment]
I should have tried that before releasing 🤦‍♂ 
In theory a very simple bugfix if anyone wants to try

**Comment by Keats** [comment]
@riginding fixed it in the `next` branch 🎊

**Comment by Jumanjii** [comment]
Awesome!
@Keats Do you know when will be the next release for newcomers to not meet this issue when launching Zola for the first time? :smiley:

**Comment by Keats** [comment]
No timeline yet, I want to have the non slugification for paths (on phone,
can't find the issue) in before releasing. I'll try to work on that next
week.

**Comment by ebkalderon** [comment]
@Keats Would it be possible to have this fix released sooner? Without it, the out-of-the-box user experience for new users looking to initialize a new Zola project inside an existing Git repo is very poor. Thanks for all the effort in creating and maintaining this project!

**Comment by Keats** [comment]
There's a WIP feature in the `next` branch (the slugification), as soon as it gets finished it will be released. The basic version is already in there, it just needs to be polished

**Comment by ebkalderon** [comment]
@Keats Awesome! Can't wait to try it out. Once the initial project directory is created, the rest of the user experience is much better. I'll gladly try out that branch and see how the slugification feature is faring.

**Comment by sbrl** [comment]
I'm getting this error too compiling from `master`. I guess it hasn't been merged in from `next` yet?

**Comment by Keats** [comment]
It has been merged in `next`, not released yet. Try building the `next` branch

**Comment by sbrl** [comment]
I see. Thanks @Keats!

I did manage to get it working by guessing the CLI argument structure (documentation? what documentation?), but haven't really found _Zola_ to be suitable for my use-case - hence I'm currently exploring alternatives.

For reference I want to build a simple static site for an open-source project of mine.

**Comment by Keats** [comment]
> I did manage to get it working by guessing the CLI argument structure (documentation? what documentation?)

Is https://www.getzola.org/documentation/getting-started/cli-usage/#init not detailed enough? There are some improvements already in the `next` branch for that page: https://github.com/getzola/zola/blob/next/docs/content/documentation/getting-started/cli-usage.md

**Comment by sbrl** [comment]
Ah, I see! I must have missed that.
