### ISSUE TITLE
tel: links get erroneously absolutized

### ISSUE THREAD

**Issue by eamsden** [getzola/zola#816]
# Bug Report

When Zola renders a Markdown file with `tel:` links e.g.

    [(123) 456-7890](tel:+11234567890)

It incorrectly prepends the absolute path to the directory containing the page containing the link.

So instead of e.g.

    <a href="tel:+11234567890">(123) 456-7890</a>

It generates

    <a href="https://mysite.com/mydir/tel:+11234567890">(123) 456-7890</a>

## Environment

Zola version: zola 0.6.0

## Expected Behavior
Zola should generate HTML links with the verbatim URL from markdown links with `tel:` prefixes

## Current Behavior
Zola generates HTML links with the path to directory containing the the page containing the link prefixing `tel:` urls.

## Step to reproduce
Create a markdown file in a Zola site containing a link to a `tel:` URL.

**Comment by zaeleus** [comment]
I can work on this. I'll likely generalize it for all schema-like patterns, as only `mailto:` is handled right now.

#747 is related.
