### ISSUE TITLE
404 cannot be translated

### ISSUE THREAD

**Issue by fyang93** [getzola/zola#821]
I'm now trying to translate my site into a multilingual one. But it seems like the 404 error page cannot be translated into multiple languages.
I tried to create files like `404.md`, `404.jp.md` under `content` directory, but it only generates `example.com/404` instead of the expected `example.com/404.html`. Also, if I rename those files to `404.html.md` and `404.html.jp.md`, then `html.jp` will be recognized as a language code.
If there is some other way that I don't know please give me some hints. If not, I wish this function could be implemented someday :)

**Comment by Keats** [comment]
That's currently missing.
The main issue with that is a 404 is global: it doesn't even know what is the current URL, even less what is the current language. 
I'm not sure how to go about it since I think it would also require some kind of server/rewriting of urls to map to the right 404 template?

**Comment by fyang93** [comment]
@Keats Thanks for your quick response. It's totally understandable that 404 is not considered to be globalized during early development. I don't think it deserves high priority too.
IMHO, the key point is to allow the 404 page to know which language the last page was using.
I will stay tuned on this issue with patience. Best.

**Comment by kellpossible** [comment]
Perhaps it could be done using cookies and a script?

**Comment by Keats** [comment]
That would likely be done in JS.

**Comment by Luni-4** [comment]
> That would likely be done in JS.

Sorry for the necropost, but I didn’t think it was a good idea to open a new issue just for a question. Has anyone, by any chance, found a solution to this problem? Thank you!

**Comment by Luni-4** [comment]
I was able to resolve the translation issue on my website by implementing the following solution

This is the `404.html` page.

<img width="1920" height="934" alt="Image" src="https://github.com/user-attachments/assets/5babca6a-1c2e-4f15-9f21-8f6770ffe08f" />

When the `English Version` button is clicked, an info box appears with the following information.

<img width="1920" height="934" alt="Image" src="https://github.com/user-attachments/assets/e8e34beb-e10d-41e9-a1af-e4e40dca9e15" />

When the `Versione Italiana` button is clicked, the same info box appears, but with the Italian information.

<img width="1920" height="934" alt="Image" src="https://github.com/user-attachments/assets/aeb06163-2649-478d-993f-ce4e28cf8350" />

This is the `html` file. I have excluded the `CSS` file because it is not relevant in this case. 

```html
<main>
    <section class="error-section">
        <div class="container">
            <h1 class="error-title">404</h1>
            <div class="button-container">
                <button class="button button-primary button-medium-large modal"
                        data-description="The requested page does not exist."
                        data-index="/"
                        data-button="Back Home">
                    English Version
                </button>
                <button class="button button-primary button-medium-large modal"
                        data-description="La pagina richiesta non esiste."
                        data-index="/it"
                        data-button="Torna alla Home">
                    Versione Italiana
                </button>
            </div>
            <div class="info-box" data-id=0>
                <p></p>
                <a class="button button-primary button-same-width"></a>
            </div>
        </div>
    </section>
</main>

<script type="module">
    const modals = document.querySelectorAll(".modal");
    modals.forEach((modal, modalIndex) => {
        modal.addEventListener("click", () => {
            const id = String(modalIndex);

            const description = modal.dataset.description;
            const index = modal.dataset.index;
            const button = modal.dataset.button;

            const infoBox = modal.parentElement.parentElement.querySelector('.info-box');
            const isVisible = infoBox.classList.contains('show');

            const p = infoBox.querySelector('p');
            const link = infoBox.querySelector('a');

            p.textContent = description;

            link.href = index;
            link.textContent = button;

            if (!isVisible) {
                infoBox.classList.add('show');
            }

            if (isVisible && infoBox.dataset.id === id) {
                infoBox.classList.remove('show');
            } else {
                infoBox.dataset.id = id;
            }
        });
    });
</script>
```

This is a part of the `tera` template for the `404.html` file.

```html
<main>
    <section class="error-section">
        <div class="container">
            <h1 class="error-title">404</h1>
            <div class="button-container">
                {%- for language in config.extra.404_languages %}
                <button class="button button-primary button-medium-large modal"
                        data-description="{{ language.description}}"
                        data-index="{{ language.index | safe }}"
                        data-button="{{ language.to_index_button }}">
                    {{ language.button }}
                </button>
                {%- endfor %}
            </div>
            <div class="info-box" data-id=0>
                <p></p>
                <a class="button button-primary button-same-width"></a>
            </div>
        </div>
    </section>
  </main>
```

This is a part of the `config.toml` file.

```toml
# Data in different languages for the 404 page
404_languages = [
   { index = "/", button = "English Version", description = "The requested page does not exist.", to_index_button = "Back Home" },
   { index = "/it", button = "Versione Italiana", description = "La pagina richiesta non esiste.",  to_index_button = "Torna alla Home" },
]
```

I hope this solution might be helpful to someone 😃

**Comment by Keats** [comment]
You can try to select the language from JS as well

**Comment by Luni-4** [comment]
I have updated my comment with the `tera` template and the `config.toml` file. 

Sure, I could detect the user’s preferred language at runtime using the `window.navigator.language` from JS, but that would be a client-side solution. I decided to use `Zola` to define, at build time, which languages are supported and to manage their exact translations.

**Comment by Keats** [comment]
Yes, it was just in case you wanted to default to one of the languages defined in the config based on the browser language

**Comment by Luni-4** [comment]
Yep, that could be another alternative, thank you!
