### ISSUE TITLE
Using datasets in templates

### ISSUE THREAD

**Issue by fbnlsr** [getzola/zola#826]
It would be nice to be able to use datasets (from yml, TOML or json files for instance) inside templates in Zola.

Jekyll uses [Data Files](https://jekyllrb.com/docs/datafiles/), Hugo uses the [Data Folder](https://gohugo.io/templates/data-templates/#the-data-folder). Zola should have something similar.

**Comment by Keats** [comment]
Is https://www.getzola.org/documentation/templates/overview/#load-data not enough?

**Comment by fbnlsr** [comment]
That might be what I'm looking for indeed. 🤔 

Is there a way to use multiple data sources? More precisely, is it possible to browse several folders? In my particular case, I'm using a collection of multiple `yml` files spread across several folders and I need to loop through them to get the data I need.

**Comment by Keats** [comment]
You can just use `set` to store all the data loaded in a variable as many times as you want, they just need to be in the `content` directory.

**Comment by fbnlsr** [comment]
I get that, but is Zola able to discover and loop through several folders? I have a bunch of auto-generated folders that I scrape to build the comment section of my blog. The structure looks like this: https://github.com/fbnlsr/primative.net/tree/master/data/comments

**Comment by Keats** [comment]
Ah if they are auto-generated then it's not going to be possible :/

**Comment by epsilonhalbe** [comment]
this is a feature that I'd be interested as well, I'd be willing to implement it if there's no objections.
