### ISSUE TITLE
Was not able to create folder public (os error 5)

### ISSUE THREAD

**Issue by Geobert** [getzola/zola#831]
# Bug Report

## Environment
Windows 10

Zola version: 0.10.0

## Expected Behavior
Building or serving the site without weird error

## Current Behavior
I have this error quite often:
```
Failed to build the site
Error: Was not able to create folder public
Reason: Access is denied. (os error 5)
```
Either while building or serving.

## Step to reproduce
I've done some tests:
```
blog at 🕙[19:45:52] on  zola [»!?]
❯ ..\zola\target\debug\zola.exe build
Building site...
-> Creating 133 pages (0 orphan), 4 sections, and processing 0 images
Done in 1.9s.


blog at 🕙[19:46:44] on  zola [»!?] took 2s
❯ ..\zola\target\debug\zola.exe build
Building site...
-> Creating 133 pages (0 orphan), 4 sections, and processing 0 images
Failed to build the site
Error: Couldn't delete output directory
Reason: The directory is not empty. (os error 145)

blog at 🕙[19:46:46] on  zola [»!?]
❯ ..\zola\target\debug\zola.exe build
Building site...
-> Creating 133 pages (0 orphan), 4 sections, and processing 0 images
Failed to build the site
Error: Was not able to create folder public
Reason: Access is denied. (os error 5)

blog at 🕙[19:46:56] on  zola [»!?]
❯ ..\zola\target\debug\zola.exe build
Building site...
-> Creating 133 pages (0 orphan), 4 sections, and processing 0 images
Done in 1.7s.
```

(look at the timestamps)

It looks like Windows is taking some time to perform the requested actions (deleting or creating `public`)

**Comment by Keats** [comment]
Hmm that's weird, this is a direct call to Rust std. Do you actually have enough permissions to write  in that folder?

**Comment by Geobert** [comment]
Yes, I'm at home and no particular permissions are set. And we can see that it passes, sometime, sometime not. Very weird. I recall you don't have a Windows box, I'll try to figure it out once I got some time :) 

Just opening this to track and maybe have some input from somebody that have encounter this before :)

**Comment by robotmay** [comment]
I'm also now getting this, on Ubuntu 20.04. The only difference I've made since the last time was to add a root `assets` directory, which if removed seems to solve the issue.

```
❯ zola build                                                                                                                                                                        12:22:51
Building site...
-> Creating 918 pages (0 orphan), 1 sections, and processing 0 images
Failed to build the site
Error: Couldn't delete output directory
Reason: Directory not empty (os error 39)
```

**Comment by robotmay** [comment]
Correction: moving that folder is unrelated. I am running on ZFS which is a slower filesystem, but it is on an NVMe SSD so it should be quick, still.

I've managed to bypass this by doing the following in my build script:

```
mv public public_old
rm -rf public_old
```

Edit: This also doesn't work :\
Edit edit: Ignore me, I was running `zola serve` in another terminal and I totally forgot about it :see_no_evil:

**Comment by Keats** [comment]
Looks like it's an issue with duplicate `zola serve` running then?

**Comment by victe** [comment]
I had this related problem with `zola serve`, but no other processes were running.

    16:11:00 ➜ zola serve
    Building site...
    -> Creating 81 pages (0 orphan), 3 sections, and processing 22 images
    Error: Permission denied (os error 13)

Finally `zola serve` started the local server after `mv public/ public_old`.
Since last time this was working (Friday 20) I updated several Ubuntu packages with `apt` and also I had update rust to 1.48.
