### ISSUE TITLE
How do you use enviroment varriables

### ISSUE THREAD

**Issue by dark0dave** [getzola/zola#833]
How would I go about using an environment variable, in a template. 

For example:

`
{% set response = load_data(url="https://api.github.com/repos/getzola/zola?apiKey=${SUPERSECRET}", format="json") %}
`

I can't seem to find any way of doing so. Is this a possible improvement?

**Comment by Keats** [comment]
No way currently. There could be a global function to get something like that though. I think it might be better in Tera directly though? Not sure.

**Comment by dark0dave** [comment]
@Keats , I have a work around currently but its crap. Thanks for your answer. I just wanted some confirmation.

**Comment by Keats** [comment]
Let's keep it open for now

**Comment by jsonmaur** [comment]
I'd love to see this feature as well.

**Comment by jsonmaur** [comment]
Another potential solution would be to set `extra` config values as CLI arguments? Though environment variables would be more elegant. Essentially we just need a way to pass in values for different build environments without hard-coding separate config files.

**Comment by Keats** [comment]
I'll add a env variable function in Tera next week, unless someone beats me to it.

**Comment by jsonmaur** [comment]
Great! Zola is a fantastic piece of software, by the way. A breath of fresh air compared to all the over-complicated generators out there. Thanks for all the hard work you put into it.

**Comment by Keats** [comment]
Thanks!

I've created https://github.com/Keats/tera/issues/464 to track that so I'll close this issue.
