### ISSUE TITLE
Make accessing `section.pages` an error when pagination is being used

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#834]
Zola version: 0.10

I spent a bunch of time trying to debug why using transparent sections wasn't working only to track it down to `section.pages` being empty due to pagination being turned on. My fault for changing too many things at once, but it would have been avoided if accessing `section.pages` when pagination is turned on resulted in an error (with a helpful message pointing the user to `paginator.pages`). :)

**Comment by Keats** [comment]
That's currently not possible, short of duplicating all of the section serialisation :/

**Comment by jwatt** [comment]
Ah, that's a shame. :/

I guess feel free to close this issue from my perspective then.
