### ISSUE TITLE
Consider deprecating `paginator.current_index` in favor of `paginator.current_page_number`

### ISSUE THREAD

**Issue by jwatt** [getzola/zola#835]
Given the word "index" in its name, I expected `paginator.current_index` to be zero based. It might be better to have a `paginator.current_page_number` and deprecate use of `paginator.current_index`.

**Comment by Keats** [comment]
All the wording around pagination is confusing. `current_index` is the index of the pager, eg the number of pagers in the pagination which is obviously not 0 based. `current_page_number` could be interpreted as referring to the section pages.

**Comment by jwatt** [comment]
Ah, yes, indeed. I should have said `current_pager_number`.

**Comment by Keats** [comment]
Ended up mentioning it's 1 indexed in the docs, changing it is probably not worth the effort.
