### ISSUE TITLE
{% raw %} ignored by shortcodes

### ISSUE THREAD

**Issue by Geobert** [getzola/zola#839]
# Bug Report

## Environment

Zola version: 0.9.0

## Expected Behavior
No expansion should happen inside a `{% raw %}` block.

## Current Behavior
Shortcode `youtube` get expanded.

## Step to reproduce
```
{% raw %}
` ` `liquid
{{ youtube(id="some_id") }}
` ` `
{% endraw %}
```

(triple backquote separated by spaces to avoid formatting issue)

**Comment by Keats** [comment]
Shortcode have a different syntax for being ignored: https://www.getzola.org/documentation/content/shortcodes/#shortcodes-without-body and https://www.getzola.org/documentation/content/shortcodes/#shortcodes-with-body the last paragraph of each.

**Comment by Geobert** [comment]
Oh, my bad! Thank you!
