### ISSUE TITLE
How to change URL of section page?

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#84]
Putting `url = "some-url"` in the `_index.md` does not seem to work

**Comment by Keats** [comment]
Hmm I didn't think this would be needed. I was expecting people to use folders for the section path. Is it no possible in your case?

**Comment by phil-opp** [comment]
I have section that is used internally only. All posts have custom URLs directly under the page root (e.g. "/post1", "/post2"). Now I want a custom URL for the section page, too (e.g. "/extra" instead of "/parent-category/extra-content").

**Comment by Keats** [comment]
if all the URLs are custom, what's preventing you from putting it directly in `extra` in the filesystem? Not against it, just trying to figure out if it's possible to avoid adding it

**Comment by phil-opp** [comment]
It's just a bit cleaner, I think. I have the main posts in a `posts` section and extra posts in an `extra` section. A few of these extra posts build on each other, so I put them in a subsection with manual ordering. These posts have custom URLs for historical reasons (they were part of the main posts once), so the additional directories for the section page seem strange. Moving them out of `extra` is certainly possible, but it feels like a workaround and would clutter the `content` folder.

**Comment by phil-opp** [comment]
To be clear, this is not a large problem for me, just a nice-to-have feature :).

**Comment by Keats** [comment]
I'll think about it

**Comment by tcurdt** [comment]
I am currently investigating gutenberg and ran into the same question I guess. I don't really want a 1:1 relationship of the sections name and the output. Ideally I would want to turn posts like this:

```
content/posts/2017-some-topic
```
or
```
content/posts/2017/some-topic
```
into `/2017/some-topic`.

Am I correct that this is currently not possible?

**Comment by Keats** [comment]
This isn't currently possible no. Any reason you don't/can't put your files into `content/2017`?

**Comment by tcurdt** [comment]
@Keats then I would have sections called `2017` and `2016` and so on ...and I would not be able to iterate through all posts in templates, no?

**Comment by onelson** [comment]
I think the usage @tcurdt is looking for is exactly what brought me to this thread. `content/posts/date-prefixed-file.md` becoming `/date/based/path/slug.html` is precisely what I'd need to have to convert a jekyll blog to use gutenberg instead :confetti_ball:

I haven't tried this yet, but I wonder if the components (year, month, day) could be used as replacements in the path for a given page. That should get me most of the way there. I suppose I could also just hard-code the date into the path, even without the replacements...

**Comment by Keats** [comment]
Sorry I forgot to reply initially.
You can use `get_section` to grab each year pages one by one but there wouldn't be a way to grab all of them in one call.

> `content/posts/date-prefixed-file.md` becoming `/date/based/path/slug.html` is precisely what I'd need to have to convert a jekyll blog to use gutenberg instead

I am not planning to add that feature (or the :year/:month/:day/:title kind of URL scheme) anytime soon.

**Comment by Keats** [comment]
Closing this as I'm not planning to add a way to change the URL of a section right now
