### ISSUE TITLE
Include "blur up" lazy image loading in image processing tools

### ISSUE THREAD

**Issue by trosel** [getzola/zola#843]
Similar to Gatsby https://using-gatsby-image.gatsbyjs.org/blur-up/

It should work with regular image elements _as well as_ background-images that are loaded via CSS (often times these are the largest files).

This would be a huge differentiator for Zola compared to other static gen engines.

**Comment by Keats** [comment]
I believe that requires manipulating the DOM with JS to accomplish no? If so it doesn't seem likely to be built in.
