### ISSUE TITLE
page.translations contains unrelated pages

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#854]
# Bug Report

I tried getting the translated versions of a page through:

```
{% for translation in page.translations %}
    {{ translation.title }} {{ translation.lang }}<br>
{% endfor %}
```

Even though the page has only a single translation, the array contains also contains completely unrelated (untranslated) pages. This makes it impossible to find the correct translation.

## Environment

Zola version: 0.9.0

## Expected Behavior
The `translations` array only has a single entry: The translated page. (Alternatively, it could also contain the default untranslated page for the default language.)

**Comment by phil-opp** [comment]
I think this issue is related to this line:

https://github.com/getzola/zola/blob/5ee8afa1059b4b1bd02c09abbb3b3c59c23e346f/components/library/src/library.rs#L307

**Comment by Keats** [comment]
The line above should ensure that it only refers to the same path https://github.com/getzola/zola/blob/5ee8afa1059b4b1bd02c09abbb3b3c59c23e346f/components/library/src/library.rs#L302

That's pretty weird. I'm guessing there is an issue when computing the `canonical` field?

**Comment by phil-opp** [comment]
I'll try to investigate.

**Comment by phil-opp** [comment]
I think the problem is this part:

https://github.com/getzola/zola/blob/5ee8afa1059b4b1bd02c09abbb3b3c59c23e346f/components/library/src/content/file_info.rs#L67-L74

This turns paths like `…/content/first-edition/posts/04-printing-to-screen/index.md` into `…/content/first-edition/posts/index`, with the result that all posts from the section have the same `canonical` path.

I'm not sure about the purpose of this code, so I don't know how to fix it. Maybe you have an idea?

**Comment by Keats** [comment]
In theory it should turn`…/content/first-edition/posts/04-printing-to-screen/index.md` into `…/content/first-edition/posts/04-printing-to-screen` but to be fair this whole has pretty confusing logic and probably not enough tests :/

**Comment by phil-opp** [comment]
I found the problem:  `…/content/first-edition/posts/04-printing-to-screen/index.md` should be treated just like `…/content/first-edition/posts/04-printing-to-screen`, therefore we adjust the parent to `…/content/first-edition/posts/`. However, at the end of the function we calculate a canonical path using the adjusted parent:

https://github.com/getzola/zola/blob/5ee8afa1059b4b1bd02c09abbb3b3c59c23e346f/components/library/src/content/file_info.rs#L81

Thus, we join `…/content/first-edition/posts/` and `index`, which results in a non-unique path. The solution is to calculate the canonical path before adjusting `parent`. I submitted a pull request for this at https://github.com/getzola/zola/pull/856.

**Comment by zaynetro** [comment]
This seems to be working now. Can it be closed?
