### ISSUE TITLE
How to access fields of translated pages from section?

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#859]
I have a section page that prints the `summary` for each page. When translating the section, I want to print the translated summaries. However, the `TranslatedContent` structure as documented [here](https://www.getzola.org/documentation/templates/pages-sections/#translated-content) only gives access to the translated title, not any other fields of the translated page such as the summary. Is there a way to access these fields for translated pages?

**Comment by Keats** [comment]
No way currently. It should probably get the path as well so you can use get_url if needed.

Side note: you might be interested in https://github.com/getzola/zola/issues/768 depending on the other languages you want to support. This is the biggest blocker for 0.10 and I just need to carve some time to finish it but the more feedback the better!

**Comment by phil-opp** [comment]
> It should probably get the path as well so you can use get_url if needed.

Sounds like a good idea!



> Side note: you might be interested in #768 depending on the other languages you want to support. This is the biggest blocker for 0.10 and I just need to carve some time to finish it but the more feedback the better!

I will take a look.

**Comment by Keats** [comment]
I meant get_page, not get_url but I think you understood it that way as well :p

> I will take a look.

Thanks!
