### ISSUE TITLE
How to use {{ lang }} in base template?

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#860]
I have a base template that sets the language tag on the `html` tag: `<html lang="{{ lang }}">`. This works fine for all pages except for the 404 page where the global `{{ lang }}` variable is not available. How can I override it with the `config.default_language`?

Here are the things I tried:

- Do a `{% set lang = config.default_language %}` before the `extends`: Causes an error.
- Create a block around the language definition that defaults to `{{ lang }}`:
  
  ```
  <html lang={% block lang_decl %}{{ lang }}{% endblock lang_decl %}>
  ```
  
  This results in an empty language: `<html lang="">`. No error occurs.
- Create a block that defaults to `config.default_language` and adjust all other templates: This works, but is very cumbersome. Strangely, it doesn't work if I try to create a common parent template that overrides the `lang_decl` block with `{{ lang }}` (results in `lang=""` again).

**Comment by Keats** [comment]
404 is a special case https://github.com/getzola/zola/issues/821 which I don't know how to handle.

You can use the default filter: https://deploy-preview-353--tera.netlify.com/docs/#default so something like `{{ lang | default (value=config.default_language) }}` should work.

(This URL is a temporary netlify preview URL so it will disappear at the next push on the Tera v1 branch I think).

**Comment by phil-opp** [comment]
Thanks a lot! It seems like a normal `{% if lang %}{{ lang }}{% else %}{{ config.default_language }}{% endif %}` works too.

**Comment by Keats** [comment]
Yep, the if/else is the longer version of the | default filter.

**Comment by phil-opp** [comment]
Ah, I just saw that the `default` filter is already in the released version of tera: https://tera.netlify.com/docs/templates/#default

I assumed it would be an upcoming feature because you posted a preview URL. Thanks again for the quick reply!
