### ISSUE TITLE
Issue building 0.9.0 with Travis

### ISSUE THREAD

**Issue by sternj** [getzola/zola#861]
# Bug Report

When building with Travis and recommended .travis.yml, error occurs when attempting to get libssl.so

## Environment

Zola version: 0.9.0
https://pastebin.com/kAs3H5G5

## Expected Behavior
zola build should have executed with error code 0

## Current Behavior
zola build fails, citing `zola: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

## Step to reproduce
Run a travis build using the .travis.yml at https://github.com/sternj/samstern.me/tree/fc98ceb4164ef4e963ead3d465b7e7a1ac6bbed7 (which is directly copied from https://www.getzola.org/documentation/deployment/github-pages/ on 27 November 2019)

Entire log of travis run located at https://pastebin.com/kAs3H5G5

**Comment by Keats** [comment]
I guess it's reqwest needing openssl? I need to work around that, see https://zola.discourse.group/t/remove-dependency-on-preinstalled-openssl/221

**Comment by keikreutler** [comment]
Was a workaround ever implemented? I'm getting the same error.

**Comment by zhenkyle** [comment]
Add the line: `dist: bionic` into `.travis.yml` seems like a workaround of this issue.

**Comment by ebkalderon** [comment]
@zhenkyle This worked for me! Ideally, the dependency situation with `reqwest` should be resolved, but if your suggested workaround becomes official, the documentation for GitHub Pages on the official website should be updated.

**Comment by Keats** [comment]
None implemented yet, if someone wants to try a PR with `default-tls-vendored` mentioned in https://zola.discourse.group/t/remove-dependency-on-preinstalled-openssl/221 please do it!

**Comment by Keats** [comment]
It shouldn't be an issue anymore
