### ISSUE TITLE
Syntax updates upstream

### ISSUE THREAD

**Issue by jrappen** [getzola/zola#862]
Please update the syntaxes via `./.gitmodules`.

**Comment by Keats** [comment]
It can't be done currently for the official ones: https://github.com/trishume/syntect/issues/271

**Comment by jrappen** [comment]
@Keats FYI, if you look at https://github.com/sublimehq/Packages/tree/st3 you'll see the `st3` branch is 16 commits behind master currently and you could use sublimehq/Packages@207cf86 until syntect has been updated by @trishume. If you'd like to follow the sublime beta, discussions are happening at [![SublimeHQ Discord](https://img.shields.io/discord/280102180189634562?label=SublimeHQ%20Discord&logo=discord)](https://discord.gg/D43Pecu) where @trishume is hanging out, too.
