### ISSUE TITLE
markdown math expression support

### ISSUE THREAD

**Issue by chlxt** [getzola/zola#868]
inline or displayed math expressions in markdown file are messed up when zola builds it. how to let zola keep math expression not touched?

e.g., zola(pulldown-cmark) transforms
```
$a_i + b_j = c$
```
to
```html
a<em>i + b</em>j = c
```
which isn't what I want. Besides, there exists many similar cases when inputs math expressions.

**Comment by Keats** [comment]
CommonMark does not have a math extension afaik. You will need to use katex or something similar.

**Comment by chlxt** [comment]
I use katex for client side rendering, but zola messed up inline math expression mentioned above, how can I force zola/pulldown-cmark to keep inline math not been escaped?

**Comment by Keats** [comment]
Ah I see. You can probably wrap the math expressions in some kind of HTML to ensure pulldown-cmark doesn't try to process it as markdown?

**Comment by chlxt** [comment]
Currently I use html `<p>` tag for protecting, and does work. I had some md files with math created using VSCode/Typora, for publishing those files with zola I have to modify every md file and it's cumbersome and boring, I'm wondering if there exists any better options I can choose from?

**Comment by Keats** [comment]
I don't think so, until CommonMark supports a math extension there are no easy ways. You could use a shortcode but you would still need to modify the md file manually.

**Comment by chlxt** [comment]
after digging part of zola source code, do you think is it accepted to add a pre-filter option in [markdown.rs](https://github.com/getzola/zola/blob/master/components/rendering/src/markdown.rs):[markdown_to_html()](https://github.com/getzola/zola/blob/f4b6f63d3cc934dbc215e4fe0f4295fd2b9e2f57/components/rendering/src/markdown.rs#L147) which first filters out math expressions from `Event::Text(text)` before rendering, then concatenates the output and raw math expressions? If do so zola can bypass restrictions from pull-cmark.

**Comment by Keats** [comment]
That would turn the markdown parser into some non-compliant CommonMark. It would be better to move this conversation in pulldown-cmark.

**Comment by chlxt** [comment]
OK, and thanks for your help
