### ISSUE TITLE
Make it possible to customize the pages shown in RSS feed

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#87]
It is possible to override the `rss.xml` template, but the list of pages is hardcoded to “all pages with a date”. While this is a reasonable default, it would be nice if one could decide to exclude some pages. One way to achieve this could be to expose the same set of variables as for the `index.html`  (`sections`, etc.).

**Comment by Keats** [comment]
Can you not override the template and just add an `extra` attribute to the pages you don't want to display and check for that?

**Comment by Keats** [comment]
@phil-opp Is my workaround working or is it not enough?

**Comment by phil-opp** [comment]
I don't remember why I needed this. At the moment, I'm just using the default rss template and have no issues with it. So I think we can close this issue. Thanks for asking!
