### ISSUE TITLE
zola should warn/error on empty links

### ISSUE THREAD

**Issue by Keats** [getzola/zola#871]
When writing a post about something that isn't live yet, I typically write something like `[this site]()` and forget to fill the link 100% of the time.

This kind of link is pretty much never wanted so it is likely it should be an error, even in `zola build`. This forces people to actually put something (even `TODO`) that gets picked up by `zola check`.

It could also be only a warning but we do not really have this kind of content warning right now. Is there anyone using `[..]()` by choice?

**Comment by zbrox** [comment]
I quickly looked into this. I wasn't sure what the preferred approach would be or how to return a warning per se. 

Would something like this be ok?

https://github.com/zbrox/zola/commit/e17bfff10a8941be6a4d0b09c39a3a0de58199e8

**Comment by aslowwriter** [comment]
I see there is a merged PR for this issue, should it still be open? if so what still needs work?

**Comment by Keats** [comment]
That should be fixed yes
