### ISSUE TITLE
Error while creating generic picture gallery

### ISSUE THREAD

**Issue by wmacmil** [getzola/zola#880]
In the "Creating Picture Galleries" section of the image-processing documentation, they present a gallery.html shortcode.  I'm not able to get it to render, instead, I get output as below in a section that resembles a code snippet:

<a href="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;markdown_overview&#x2F;DSC_9085.jpg">
  <img src="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;processed_images&#x2F;35a365167858dd8d00.jpg" />
</a>
&ensp;
<a href="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;markdown_overview&#x2F;DSC_9897.jpg">
  <img src="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;processed_images&#x2F;9d4ba36461a824a600.jpg" />
</a>
&ensp;
<a href="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;markdown_overview&#x2F;DSC_9466.jpg">
  <img src="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;processed_images&#x2F;505e35a6de0b97d200.jpg" />
</a>
&ensp;
<a href="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;markdown_overview&#x2F;_DSC5435.jpg">
  <img src="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;processed_images&#x2F;65f473b25e89388000.jpg" />
</a>
&ensp;
<a href="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;markdown_overview&#x2F;_DSC5418.jpg">
  <img src="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;processed_images&#x2F;571668d98a509bf200.jpg" />
</a>
&ensp;
<a href="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;markdown_overview&#x2F;DSC_9942.jpg">
  <img src="http:&#x2F;&#x2F;127.0.0.1:1111&#x2F;processed_images&#x2F;0ef929114148244f00.jpg" />
</a>
&ensp;

I'm specifically confused how to the post.assets variable is working, and why the output isnot coming out.  When i check the public/ directory the images are being compressed.Here is the tree for my file
 [warrick@warrick-pc content]$ tree
.
├── first_post.md
├── _index.md
├── markdown_overview
│   ├── _DSC5418.jpg
│   ├── _DSC5435.jpg
│   ├── DSC_9085.jpg
│   ├── DSC_9466.jpg
│   ├── DSC_9897.jpg
│   ├── DSC_9909.jpg
│   ├── DSC_9942.jpg
│   └── index.md
├── markdown_overview-two.md
├── pages
│   ├── about.md
│   └── _index.md
├── some-article.md
├── some-other-article.md
└── Theme_Overview.md
Sorry if this ins't appropriate as an issue, but for someone not too familiar with frontend stuff, I do think the documentation could do a better job of indicating exactly how the directories should be structured to allow for easy asset colocation.  Additionally, are there any resources for completed webistes (not just templates) that do a good job of revealing this asset colocation structure?

**Comment by wmacmil** [comment]
here's a screenshot if the text doesn't render (https://user-images.githubusercontent.com/6887392/70871766-c6482000-1fa2-11ea-99d2-31d018105af3.png)

**Comment by Keats** [comment]
Which version of zola are you using? The docs are getting a revamp as we speak.
I do use some colocated assets on my site (https://github.com/Keats/vincentprouillet/tree/master/content/blog) but no resize going on

**Comment by wmacmil** [comment]
zola 0.9.0

Do you mind elaborating what the post.assets variable refers to (or better yet, where I can find documentation about this syntax)?  Like, I couldn't find the 'post' keyword anywhere in the documentation.   

It's clearly recognizing and using the resize function, but instead of rendering the images I'm just seeing the raw html syntax.  Is this a user error or an actual bug?

**Comment by Keats** [comment]
Make the variable as `| safe` to avoid the escaped output. Where do you see `post`? It's not part of zola so probably coming from a macro or some allocated variable in a template.

**Comment by wmacmil** [comment]
I meant page, not post.

{% for asset in page.assets %}
  {% if asset is matching("[.](jpg|png)$") %}
    <a href="{{ get_url(path=asset) }}">
      <img src="{{ resize_image(path=asset, width=240, height=180, op="fill") }}" />
    </a>
    &ensp;
  {% endif %}
{% endfor %}

This I copied verbatim into a shortcode from the documentation.

**Comment by wmacmil** [comment]
It treats the a element as an actual element and so won't paste the html in the comment like it should.  Erggg

**Comment by wmacmil** [comment]
Here a link to the actual website, you can see the code via my profile.

https://wmacmil.gitlab.io/markdown-overview/

**Comment by Keats** [comment]
Did you add `| safe` like in https://github.com/getzola/zola/blob/master/docs/templates/shortcodes/gallery.html#L3-L4 ?

**Comment by wmacmil** [comment]
`{% for asset in page.assets | safe %}
`
after which variable?

**Comment by Keats** [comment]
Look at the link in my comment above.
