### ISSUE TITLE
Any plans to support Dynamic content through API calls

### ISSUE THREAD

**Issue by kawpii** [getzola/zola#881]
Zola is cool! It will become much more cooler if we could build dynamic websites using Zola like in JAMStack. ex: https://www.gatsbyjs.org/blog/2018-11-07-gatsby-for-apps/

Any plans to support dynamic content through JavaScript API calls?

**Comment by Keats** [comment]
Making it work with remote data (as the frontend for data in WordPress for example) is an interesting idea: https://github.com/getzola/zola/issues/401

Making apps on the other hand is not going to happen, I'm pretty sure it's not even happening for Gatsby at a noticeable scale and users already have to write JS to use it.

**Comment by kawpii** [comment]
IMHO things like [JAMstack](https://jamstack.org/) have their benefits, opposed to server side rendered apps.

Allowing users to write JS will enable dynamic content, but using JS framework/library would make things easy. [Svelte](https://svelte.dev/) is light weight alternative which is gaining traction, something that you may consider if you are hoping to add a JS framework/library to Zola to enable dynamic content.

Edit: Svelte is a language according to [this](https://gist.github.com/Rich-Harris/0f910048478c2a6505d1c32185b61934)

**Comment by Keats** [comment]
It's very unlikely a JS framework will be added to Zola anytime soon as there are still a lot of features to add to Zola first. Once everything is there (full i18n, translations etc), we can have a look but that's a huge undertaking and very likely won't even happen in 2020.
