### ISSUE TITLE
Allow processed images directory to be configurable

### ISSUE THREAD

**Issue by muhuk** [getzola/zola#887]
Currently resized images are put under [a hardcoded directory](https://github.com/getzola/zola/blob/5ee8afa1059b4b1bd02c09abbb3b3c59c23e346f/components/imageproc/src/lib.rs#L26) under `static/`.  It would be nice to make this configurable.

**Comment by muhuk** [comment]
I would like give the implementation a try.

**Comment by Keats** [comment]
What's the usecase to make it configurable?

**Comment by muhuk** [comment]
I can live with the hard-coded value.  But other people might want to set it to something more descriptive like `thumbnails` (if they only use resizing for thumbnails).

Come to think of it, it might also be a good idea to place the resized image on the same directory as the source image. (I understand this might be tricky in cases where the source image is under `content/`)

**Comment by Keats** [comment]
I don't think it's that useful overall. If we do that, people might want to customise per section or the generated filename as well and that makes the code more complex for some urls only seen in the network tab.

**Comment by muhuk** [comment]
Makes sense to me.  Closing.
