### ISSUE TITLE
section.pages is empty

### ISSUE THREAD

**Issue by patrickelectric** [getzola/zola#890]
# Bug Report
Version: 0.9.0

I have a content folder full of files
![image](https://user-images.githubusercontent.com/1215497/71301996-e56cf600-2384-11ea-86eb-754f3804b25c.png)

But when generating the website with zola build or zola server, the output of the `section.pages` is empty.
Template:
![image](https://user-images.githubusercontent.com/1215497/71302020-1d743900-2385-11ea-9657-4aeb9b0453fb.png)

Generated: 
![image](https://user-images.githubusercontent.com/1215497/71302010-0df4f000-2385-11ea-93e5-013cac0e3b8a.png)

Is there any way to debug it ?

**Comment by patrickelectric** [comment]
It appears be something related to the orphan pages, since there is no _index.md in this subfolders.
Is it possible to use this kind of structure without moving all my files under the same folder ?

**Comment by Keats** [comment]
Which section is that the rendering of? You don't need to put a _index.md but blog/ for example doesn't have any pages in it, just a few sections which themselves have pages.
If you want to sort by date though, you will need to add a _index.md in each year folder

**Comment by patrickelectric** [comment]
The template and output is from the main index.html page.
Is is not possible to iterate over all markdowns recursively ?
I did put a _index.md but the template is still not working, I need to deal with each category individually ? There is no parameter or loop to iterate over everything ?

**Comment by patrickelectric** [comment]
It appears be possible from this comment
```rust
/// Used to create a default index section if there is no _index.md in the root content directory
impl Default for Section {
```

**Comment by patrickelectric** [comment]
I did create a `content.orphan_pages` to access all orphan pages, will send a PR soon.

**Comment by patrickelectric** [comment]
I did the changes here to access all the pages and it's working as expected from my part.
I did create a post here https://zola.discourse.group/t/add-orphan-pages-in-content/289 before creating the PR.

**Comment by Keats** [comment]
If you want to access pages from nested sections, you need to mark the nested ones as `transparent`.

**Comment by patrickelectric** [comment]
Great, thanks
