### ISSUE TITLE
serve stop is awkward with Windows

### ISSUE THREAD

**Issue by ghost** [getzola/zola#893]
Serve says this:

~~~
Press Ctrl+C to stop
~~~

but if you press that, it doesnt stop. You have to press it 3 times, or hold it.
Then it does this:

~~~
Encountered an error: other os error
Enable a logger to see more information.
~~~

**Comment by Keats** [comment]
hmm we are using https://github.com/Detegr/rust-ctrlc to handle that. Is that happening with all command line on Windows (the default one and powershell)?

**Comment by cup** [comment]
https://github.com/Detegr/rust-ctrlc/issues/61

**Comment by cup** [comment]
@Keats goodness, cant Rust standard library do anything? Is signal handling really something that has to be done with a package?

**Comment by ghost** [comment]
@Keats did some more testing and it looks like `rust-ctrlc` works fine on its own, so its possibly a Zola specific issue

**Comment by cup** [comment]
https://github.com/cobalt-org/cobalt.rs/issues/699

**Comment by 17cupsofcoffee** [comment]
I've also noticed this issue using Powershell Core 6 on Windows (in ConEmu, if that makes a difference). Might be able to test it with some other terminals later.

**Comment by Keats** [comment]
Can someone try the next branch? It changed from actix to hyper so the behaviour might have changed.

**Comment by 17cupsofcoffee** [comment]
I compiled both `master` and `next` locally - I was able to replicate the issue on `master`, but it seems to be fixed on `next`! 🎉 

So it does seem like this was an oddity with the old server implementation.

**Comment by ghost** [comment]
@17cupsofcoffee did you run into this?

https://github.com/compass-rs/sass-rs/issues/63

at any rate, I built my own server until a new Zola build is available:

https://github.com/cup/sunday/blob/master/file-server/serve.go

**Comment by 17cupsofcoffee** [comment]
@cup It was https://github.com/compass-rs/sass-rs/pull/58 that ended up being the issue for me (as well as just trying to find the right VS2019 command prompt to build it in). I ended up having to make the change to `sass-rs` locally and pointed the Zola build at that folder instead of Crates.io.
