### ISSUE TITLE
Unable to use asset colocation with subfolders

### ISSUE THREAD

**Issue by xSke** [getzola/zola#894]
# Bug Report
I'm attempting to use asset colocation on my blog to keep all the relevant images and such in the same directory as the post itself. However, it seems like I can't have a subdirectory inside that post folder, and have it still work.

Running Arch Linux, Zola version: 0.9.0

Example folder structure:

```
content/
- blog/
  - my_post/
    - index.md
    - images/
      - myimage.png
      - otherimage.png
```

Referring to an image inside `index.md` with `![My alt-text](images/myimage.png)` instead makes an absolute path reference to `/images/myimage.png` rather than the expected relative referance to `/blog/my_post/images/myimage.png`. Moving the images into `my_post/` and just referring to them as `myimage.png` in the markdown file works as expected.

**Comment by Keats** [comment]
Asset colocation doesn't support creating folders in it.

**Comment by xSke** [comment]
Okay. May I suggest it as a feature?

**Comment by Keats** [comment]
Sure, I don't think there is anytthing blocking that.

**Comment by shumvgolove** [comment]
I would really appreciate if we have this feature, because doing this:
```
└── content
    ├──something_cool
    │    └── index.md
    │    └── my_precious_things
    │         └── 1.jpg
    │         └── 2.jpg
    │         └── 3.jpg
    │    └── my_most_precious_things
    │         └── 1.jpg
    │         └── 2.jpg
    │         └── 3.jpg
```
is a lot more consistent than doing this:
```
└── content
    ├──something_not_cool
    │    └── index.md
    │    └── 1_01.jpg
    │    └── 1_02.jpg
    │    └── 1_03.jpg
    │    └── 2_01.jpg
    │    └── 2_02.jpg
    │    └── 2_03.jpg
```
when using shortcodes like galleries (and maybe other use cases).

**Comment by damccull** [comment]
I would also like to see subfolders enabled for asset co-location. Either that, or make explicit reference that this isn't supported in the documentation/tutorials. I had to google and find this issue to figure that out. :/

**Comment by Keats** [comment]
Anyone willing to implement that?
