### ISSUE TITLE
Allow specifying the root directory in the CLI arguments

### ISSUE THREAD

**Issue by sandhose** [getzola/zola#899]
It would be great to be able to set the root directory of the site when building it, e.g `zola build --root my_website/`.
A use case of this would be in scripts & some build systems. I tried to make [Bazel](https://bazel.build) to run Zola, but I had to write a wrapper that `cd` into the site directory before building it.

To do this, Zola should:

 - introduce a new (global?) argument, defaulting to the current working directory (in [src/cli.rs](https://github.com/getzola/zola/blob/1bafec430946da0590122a48d49b1e484154141a/src/cli.rs#L9))
 - use it where `current_dir` is used
   - [in the `check` command](https://github.com/getzola/zola/blob/5ee8afa1059b4b1bd02c09abbb3b3c59c23e346f/src/cmd/check.rs#L15)
   - [in the `build` command](https://github.com/getzola/zola/blob/5ee8afa1059b4b1bd02c09abbb3b3c59c23e346f/src/cmd/build.rs#L14)
   - [in the `serve` command](<https://github.com/getzola/zola/blob/5ee8afa1059b4b1bd02c09abbb3b3c59c23e346f/src/cmd/serve.rs#L123>)

**Comment by Keats** [comment]
Anyone wants to pick that up?
