### ISSUE TITLE
Deleting a section causes panic

### ISSUE THREAD

**Issue by eigan** [getzola/zola#902]
# Bug Report

## Environment

Zola version: 0.9.0

## Expected Behavior
Delete a section should not crash zola.

## Current Behavior
Delete a section crashes zola with a Panic.

Backtrace: 
https://gist.github.com/eigan/c763aa134671e60b64df380b496bdf0d
_Note: I deleted the `/content/txt/teknisk/data` directory._

## Step to reproduce
_(Note: These are not the same steps as in backtrace)_
Constant reproduce by doing the following:
1. Create directory
2. Create _index.md with content:
```
+++
+++
```
3. Delete the directory

**Comment by Keats** [comment]
:(
The whole rebuilding is too complicated and still miss tons of things.
A full rewrite is warranted imo, especially now that there are way more features than when it was initially built.
