### ISSUE TITLE
[feature request] Data Templates

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [getzola/zola#906]
## [Hugo Data Templates](https://gohugo.io/templates/data-templates/#readout_)

In addition to Hugo's built-in variables, you can specify your own custom data in templates or shortcodes that pull from both local and dynamic sources.

Hugo supports loading data from YAML, JSON, and TOML files located in the data directory in the root of your Hugo project.

It would be convenient if parse files in a `data/` folder like you do for config.toml.

**Comment by Keats** [comment]
Zola has https://www.getzola.org/documentation/templates/overview/#load-data is it not enough for your usecase?

**Comment by Th3Whit3Wolf** [comment]
That should do it. I missed the most important page in the documentation. Thank you @Keats!

**Comment by Th3Whit3Wolf** [comment]
Are if statements not available inside a for loop that uses data from load_data?
