### ISSUE TITLE
discuss: org-mode support

### ISSUE THREAD

**Issue by PoiScript** [getzola/zola#909]
It would be nice to bring org-mode support to Zola. And actually I'm already started working on it (by using orgize, a org-mode parser I wrote).

But Zola not only converts raw markdown into simple html string but also applies some features like deep linking and table of content. So I think we should first discuss about how to address such features on org-mode before we can finally implements it in Zola.

**Comment by PoiScript** [comment]
Some ideas: 

#### Custom anchor id
```
* title
:PROPERTIES:
:ID: title
:END:
```

#### Internal links
```
[[@/about.org][about page]]
```

Also, org-mode have [link abbreviation](https://www.gnu.org/software/emacs/manual/html_node/org/Link-abbreviations.html). So we can consider add some builtin abbreviations, like `blog`, so above can be rewrote as

```
[[blog:about.org][about]]
```

#### Shortcodes

The closest alternative to shortcodes in org-mode seems to be [macros](https://orgmode.org/manual/Macro-replacement.html).

```
{{{youtube(id="dQw4w9WgXcQ")}}}
```

#### Front-matter
```
#+TITLE: title
#+DESCRIPTION: desc
#+WEIGHT: 0
```

**Comment by petr-tik** [comment]
Just a fan of org-mode and a user of Hugo, who would be willing to move to zola, if it supported org-mode files. 

It would be great to mix and match .md and .org files in the same website. 

To maximise reach and make migrations easy, please consider following the same practices/properties that Hugo supports. 

Thanks again for suggesting this

**Comment by Keats** [comment]
org-mode is very very (very) low in terms of priority as I have never used it myself, not planning to (https://zola.discourse.group/t/alternative-input-formats/76) and not convinced it has enough users to be worth it.

All the work would have to come from contributors and have feature parity with the Markdown renderer.

I don't know what practice/properties Hugo is following there so it would be useful to list them to see if they are useful/make sense in the context of Zola.

**Comment by petr-tik** [comment]
> org-mode is very very (very) low in terms of priority as I have never used it myself, not planning to (https://zola.discourse.group/t/alternative-input-formats/76) and not convinced it has enough users to be worth it.

Your desire to keep the rendering logic as lean as possible makes perfect sense. A smaller surface area will enable you to move faster and I hope your hard work on zola and tera is recognised. 

> All the work would have to come from contributors and have feature parity with the Markdown renderer.

I would like to help. I cannot promise committing a lot of time right now - have prior commitments already. Later in the year looks better for me.  

> I don't know what practice/properties Hugo is following there so it would be useful to list them to see if they are useful/make sense in the context of Zola.

Below is some links that @PoiScript and anyone else might find useful in the future. 

## Most recent user overview of hugo + org-mode
https://willschenk.com/articles/2019/using_org_mode_in_hugo/

## Org mode parser used by hugo
https://github.com/niklasfasching/go-org

@Keats Do I understand it correctly that proving feature parity means implementing similar functionality as found in `components/rendering/*`, including full test coverage and benchmarks showing similar performance. Are there any other requirements for the markdown parser? 


> It would be nice to bring org-mode support to Zola. And actually I'm already started working on it (by using orgize, a org-mode parser I wrote).

@PoiScript From my lurking in your code, it looks as good as feature-complete. Were you thinking about implementing a custom `HtmlHandler` for the `Org::wirte_html_custom` function?

**Comment by PoiScript** [comment]
Soooo sorry for keeping you guys waiting. My schedule is too hectic to go through every mails in my inbox.

I dig a little bit into zola source code and find out it's actually harder than I thought. Zola relied heavily on the structure of the markdown. For example, Zola insert [shortcodes as html](https://github.com/getzola/zola/blob/21b45aff108ce8fbaf50706458fb7244f67f4221/components/rendering/src/lib.rs#L37-L45) right before parsing it. But it's not the same with org-mode, org-mode doesn't support raw html.

So, instead of bringing org-mode support "into" Zola, why not convert them into markdown and let Zola handle the rest? In that way, we don't need to change much, just recognize the input file by its extension and choice the applicable converter.

@Keats @petr-tik how do you think about this solution, it is acceptable?

**Comment by zoranzaric** [comment]
@PoiScript isn't this what [ox-hugo](https://ox-hugo.scripter.co/) does?

I guess a new ox-zola might be the way to go.

**Comment by kaushalmodi** [comment]
Yes, `ox-hugo` basically converts all the Org syntax I can think of to the closest Markdown that Hugo can parse (right now the exported Markdown is compatible with both Blackfriday and Goldmark (CommonMark) Markdown parsers). On top of that, typical Org constructs (e.g. tags, properties) get converted to yaml/toml front-matter that Hugo understands.

See if you can reuses bits and pieces from ox-hugo and we can collaborate on moving those pieces to a separate library.

**Comment by jansc** [comment]
I was able to use `ox-hugo` to create a zola-site. The syntax of the generated markdown is basically the same for both hugo and zola, so it just works. However, I have one problem with ox-hugo: shortcodes use a different syntax. In hugo, shortcodes look like this: `{{% youtube(id="yPYZpwSpKmA") %}}`, but zola uses `{{ youtube(id="yPYZpwSpKmA") %}}`. That means also, that I can't have inline images in my org-files.

So I see three alternatives:
 - Fork ` ox-hugo`  to create zola-shortcuts
 - Fork zola to accept hugo-compatible shortcuts
 - Do some kind of post-processing of the created markdown-files. Edit: maybe zola could support some kind of preprocessing hook. Maybe a reference to a pre-processing script in the front-matter?

Not sure what to do here.

**Comment by kaushalmodi** [comment]
@jansc Another option is to just create a new Org exporter backend that extends from ox-hugo and you override only the handful functions you need to.. in this case, may be just `org-hugo-special-block`.

**Comment by Keats** [comment]
That's not going to be built-in.
