### ISSUE TITLE
page.ancestors: _index.md instead of index.<code>.md

### ISSUE THREAD

**Issue by pandark** [getzola/zola#916]
# Bug Report

## Environment

Zola version: 0.9.0

I've added to `config.toml` :
``` toml
default_language = "fr"
languages = [
    {code = "fr", rss = true, search = false},
]
```
I've also renamed all files in `content/` from `.md` to `.fr.md` and updated links accordingly.

## Expected Behavior
In template files, `page.ancestors` should have `…/_index.fr.md` as section indexes.

## Current Behavior

In template files, `page.ancestors` ignores the language and has `…/_index.md` as section indexes instead of `…/_index.fr.md`.

## Step to reproduce
To test, in `templates/page.html`:
```
  {% if page.ancestors %}
    {% for ancestor_path in page.ancestors %}
      {% set ancestor = get_section(path=ancestor_path) %}
      <p>{{ancestor.relative_path}}</p>
    {% endfor %}
  {%endif%}
```
or in `templates/section.html`:
```
  {% if section.ancestors %}
    {% for ancestor_path in page.ancestors %}
      {% set ancestor = get_section(path=ancestor_path) %}
      <p>{{ancestor.relative_path}}</p>
    {% endfor %}
  {%endif%}
```

**Comment by pandark** [comment]
Actually, I think it's not a template issue but a wider one…

**Comment by Keats** [comment]
I think there some changes on that on the `next` branch, can you give it a try?

**Comment by pandark** [comment]
I thought the index files for the default language were expected to be `_index.fr.md`, but apparently, they'er expected to be `_index.md`.
The naming is not consistent between pages and sections, but that's not a big problem.

The remaining issue is that the _home page_ is rendered using `_index.fr.md` but in the `ancestors` array, it's `_index.md`.

**Comment by pandark** [comment]
@Keats I tried the _next_ branch, but I get an error :confused: 
```
Failed to build the site
Error: Found path collisions:
- `/` from files ["somedir/somefile.fr.md", "somedir/someotherfile.fr.md"]
- `somedir/` from files ["somedir/yetanotherfile.fr.md", "…/…/somedir/subdir/index.fr.md"]
```

**Comment by Keats** [comment]
are their paths actually colliding? That's a new check to ensure no pages/sections overlap

**Comment by pandark** [comment]
No. I deleted the files to see what would happen, and think it's doing it for every single page.

**Comment by pandark** [comment]
@Keats https://github.com/pandark/asn-website/tree/i18n

**Comment by Keats** [comment]
@pandark that branch doesn't exist anymore, do you have another one?

**Comment by pandark** [comment]
Sorry, I merged it in [master](https://github.com/pandark/asn-website/tree/master) and removed the branch without thinking about this :sweat_smile:

**Comment by Keats** [comment]
Was it still an issue?

**Comment by Keats** [comment]
ping @pandark
