### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by ghost** [getzola/zola#918]
Current release is (Sep 2019):

https://github.com/getzola/zola/releases/tag/v0.9.0

I noticed that automated builds are being run:

https://dev.azure.com/getzola/zola

but no artifacts are being generated. This means users need to set up their own
Rust environment and build, which can be difficult as some native crates are
required (`miniz-sys`). It might be worthwhile to have artifacts produced with
the automated builds to allow for easier testing of fixes.

**Comment by cup** [comment]
https://github.com/compass-rs/sass-rs/issues/63
