### ISSUE TITLE
Markdown strikethrough is not rendered.

### ISSUE THREAD

**Issue by zoosky** [getzola/zola#921]
# Bug Report

Markdown ~~striketrough~~ does not work.

Maybe an update of pulldown-cmark from 0.6 to 0.6.1 fixes the issue.

See https://github.com/raphlinus/pulldown-cmark/commit/b24ac87ea7d1e92d3cc2f4d34d0ca4660b710bb7

## Environment
MacOS

Zola version: 0.9

## Expected Behavior

HTML should render text als strikedthroug.

## Step to reproduce
Add ~~this text should be striked through~~ to a Markdown document. If you see the tilde character instead of a characters striked through, you look at the bug.

**Comment by Keats** [comment]
It just needs to enable the strikethrough extension `components/rendering/src/markdown.rs`. A one line change if someone wants to try!
