### ISSUE TITLE
publish setting not respected

### ISSUE THREAD

**Issue by ghost** [getzola/zola#925]
I prefer to push my own built site, not to use any CI. Also I am hosting on
GitHub. I currently use Hugo, and all I have to do is change my `config.toml`:

~~~toml
publishDir = "docs"
~~~

https://gohugo.io/hosting-and-deployment/hosting-on-github#deployment-of-project-pages-from-docs-folder-on-master-branch

I am trying to mimic this with Zola, but I dont know what option to set, if any
even exists. I saw this:

~~~toml
[build]
base    = "docs"
publish = "docs/public"
~~~

https://getzola.org/documentation/deployment/netlify

but I dont think its right as `zola build` just goes ahead and dumps the output
to `public` still. Help?

**Comment by Keats** [comment]
The example in Netlify is for Netlify itself, not Zola.
It looks like the option is not present in the web documentation but there is a `-o` option to specify where to build the site.

**Comment by ghost** [comment]
Just to be clear, does that mean a configuration is not available and the commandline flag needs to be passed every time?

**Comment by Keats** [comment]
Yes

**Comment by ghost** [comment]
Should I open a new issue for that, or can this issue be used for that as well

**Comment by Keats** [comment]
There won't be a field for config.toml for that, config.toml is for configuring the site itself not the output.

**Comment by cup** [comment]
Every static site generator I have ever used has had a file configuration option to control the output, and I have used at least 10.
