### ISSUE TITLE
Sections can’t be drafted

### ISSUE THREAD

**Issue by manu-cyber** [getzola/zola#927]
Sections don’t have the `draft` variable, so setting `draft = true` still builds them and includes them in the output.
Would it be a desirable feature to be able to save sections as drafts?

**Comment by Keats** [comment]
What would a draft section mean?

**Comment by manu-cyber** [comment]
One that wouldn’t be rendered/built with the `build` command. Would that make sense?

**Comment by Keats** [comment]
I get that, but I meant more what's a usecase for a draft section? Would that draft status apply to all pages/sections below it?

**Comment by manu-cyber** [comment]
I guess it would have to, for it to make sense.
I use sections to organise my notes in a hierarchical, tree-like manner. Doing so, I can add sub-sections everywhere I like, or just add "regular" content just as I would for pages.
It could also make sense if one was to extend a website by a whole section, e.g. "projects", but would want to wait until every page in that section, i.e. every project, has a description one is happy with.

**Comment by Keats** [comment]
Makes sense. It's a bit tricky to implement though since section processing is done without any specific order so we might end up adding a child section of a draft section before seeing that it shouldn't have been added.
If someone has a good idea, feel free to work on it!

**Comment by jasikpark** [comment]
In my opinion, simply making the drafts variable a single page flag and adding a warning to the output letting you know that your draft section has non-draft pages beneath it, explaining why that’s not a good idea, seems best. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasikpark** [comment]
or defining the drafts variable a recursive search upwards until you reach the root for *every* page + seems like an inefficient but simple and correct way to do it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by florianb** [comment]
We built single-page sites and missed something like a section-based `render`-flag.

I don't know the mechanisms behind the scenes yet, but wouldn't it be possible to simply derive these flags?

**Comment by Keats** [comment]
Zola doesn't want to assume too many things, and assuming that a section is a draft because all pages are a draft is not something wanted: the section could have a "Coming soon" page for example.

**Comment by aslowwriter** [comment]
I have a working implementation for this I just need some time to clean up the PR
