### ISSUE TITLE
Disable Sass at build time

### ISSUE THREAD

**Issue by ghost** [getzola/zola#930]
Other projects offer "base" build and "extended" build, where extended includes
Sass:

https://github.com/gohugoio/hugo/releases

It would be preferable is Zola had an option to disable Sass at build time.
Firstly because some users may have no need for it, and secondly because
building Sass for Rust can be impossible in some situations.

**Comment by cup** [comment]
https://github.com/compass-rs/sass-rs/issues/63

**Comment by Keats** [comment]
Note that the releases will always include Sass. The only thing a sass feature would do is allow an individual to build zola locally without it if disabled. The default would be enabled.

**Comment by nu8** [comment]
https://github.com/compass-rs/sass-rs/issues/74

**Comment by aslowwriter** [comment]
Could this just be achieved by changing the `compile_sass` config option at build time depending on a flag, or am I missing something?

**Comment by a8nJ** [comment]
@dvente thats a runtime option...

**Comment by aslowwriter** [comment]
oh right sorry, I misunderstood the question
