### ISSUE TITLE
balthek/zola docker image is not updated

### ISSUE THREAD

**Issue by nrjais** [getzola/zola#938]
# Bug Report
The image in the balthek/zola repository is 7 months old with version 0.7.0

## Expected Behavior
Updated docker image with version 0.9.0

**Comment by rask** [comment]
The Docker Hub page states that the image source repository is in fact this repository, but I see no official mention anywhere regarding the Docker image?

**Comment by nrjais** [comment]
Yes the source repository is this repository but there is only one image available which is 7 months old for zola version 0.7.0 which is marked as latest.
I think it is not rebuilding the image whenever there is a new release of zola.

**Comment by rask** [comment]
Yeah, I see no reference to image building in the Azure Pipelines definition.

**Comment by nrjais** [comment]
I think you can also enable docker automated build to automatically build and publish images as soon as a version is released on github.

Below configuration can be used to use the Github release tag as the image tag for every release of zola
<img width="1151" alt="Screenshot 2020-01-28 at 7 23 12 PM" src="https://user-images.githubusercontent.com/20153307/73269983-d723bc80-4203-11ea-89b2-b087de660586.png">

**Comment by rask** [comment]
That screenshot is from Docker Hub?

**Comment by nrjais** [comment]
@rask Yes from automatic build configuration

**Comment by Keats** [comment]
Looks like a bug in the pipeline: 

```
Step 6/11 : RUN curl -L https://github.com/getzola/zola/releases/download/$DOCKER_TAG/zola-$DOCKER_TAG-x86_64-unknown-linux-gnu.tar.gz | tar xz
---> Running in 4e65b0453f54
[91m % Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0[0m
[91m 100 9 0 9 0 0 64 0 --:--:-- --:--:-- --:--:-- 64
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[0m
```
It seems the DOCKER_TAG variable is not there or something?

**Comment by nrjais** [comment]
@Keats The existing Dockerfile will not work as it uses hardcoded version number.
I can raise a PR with the updated Dockerfile where version is not hardcoded.

**Comment by Keats** [comment]
Please do!

**Comment by nrjais** [comment]
@Keats I have raised a pull with the updated dockerfile can try building again with these changes.

**Comment by thomasetter** [comment]
Should this issue still be open?

https://hub.docker.com/r/balthek/zola/builds shows last updated as "a year ago".
![image](https://user-images.githubusercontent.com/422775/84137630-3fee3180-aa4d-11ea-905b-fbc5060b061d.png)

**Comment by Keats** [comment]
I think there was a typo in the auto-build :/ it should be ok in the next tag
