### ISSUE TITLE
Section `doc` not found.

### ISSUE THREAD

**Issue by pka** [getzola/zola#94]
My section:
```
content/doc/_index.md
content/doc/setup.md
content/doc/configuration.md
content/doc/generate.md
content/doc/serve.md
```

When I add 
`{% set doc = get_section(path="doc") %}`
in `page.html` I get 
```
Failed to build the site
Error: Failed to render page '/opt/pi/code/web/t-rex-website/content/doc/generate.md'
Reason: Failed to render 'page.html'
Reason: Section `doc` not found.
```
Same with '/doc/', '/doc' or 'doc/'.

**Comment by Keats** [comment]
You need the path to the file currently so that would be `{% set doc = get_section(path="doc/_index.md") %}`. Might be worth changing to use the parent folder path instead of the file path though

**Comment by pka** [comment]
Working, thanks!
