### ISSUE TITLE
[security] update to http >= 0.1.20

### ISSUE THREAD

**Issue by lukehsiao** [getzola/zola#942]
# Bug Report
This is recommendation to update the http dependency as recommended by the Rust security advisories.

## Environment
Ubuntu 18.04, Rust 1.41.0

Zola version:
master branch (https://github.com/getzola/zola/commit/ffb4ebb245abc5502a4fd7572e8631b1e6e497de)

## Expected Behavior
We should use http >= 0.1.20

## Current Behavior
With http 0.1.18, we have two open rust security advisories to consider:

1. [HeaderMap::Drain API is unsound](https://rustsec.org/advisories/RUSTSEC-2019-0034)
2. [Integer Overflow in HeaderMap::reserve() can cause Denial of Service](https://rustsec.org/advisories/RUSTSEC-2019-0033)

As a static site generator, these are unlikely to cause any problems. But, given that it should be a simple dependency update, filing this ticket regardless.

## Step to reproduce
The full report from [cargo-audit](https://github.com/RustSec/cargo-audit) is below with links to the advisories.
```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 71 security advisories (from /home/user/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (336 crate dependencies)
error: Vulnerable crates found!

ID:       RUSTSEC-2019-0034
Crate:    http
Version:  0.1.18
Date:     2019-11-16
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0034
Title:    HeaderMap::Drain API is unsound
Solution:  upgrade to >= 0.1.20
Dependency tree:
http 0.1.18
├── reqwest 0.9.20
│   ├── templates 0.1.0
│   │   ├── site 0.1.0
│   │   │   ├── zola 0.9.0
│   │   │   └── rebuild 0.1.0
│   │   │       └── zola 0.9.0
│   │   └── rendering 0.1.0
│   │       └── library 0.1.0
│   │           ├── templates 0.1.0
│   │           ├── site 0.1.0
│   │           ├── search 0.1.0
│   │           │   └── site 0.1.0
│   │           └── rebuild 0.1.0
│   └── link_checker 0.1.0
│       ├── site 0.1.0
│       └── rendering 0.1.0
├── hyper 0.12.35
│   ├── reqwest 0.9.20
│   └── hyper-tls 0.3.2
│       └── reqwest 0.9.20
├── http-body 0.1.0
│   └── hyper 0.12.35
├── h2 0.1.26
│   ├── hyper 0.12.35
│   └── actix-http 0.2.10
│       ├── actix-web 1.0.7
│       │   ├── zola 0.9.0
│       │   └── actix-files 0.1.4
│       │       └── zola 0.9.0
│       └── actix-files 0.1.4
├── actix-router 0.1.5
│   └── actix-web 1.0.7
├── actix-http 0.2.10
└── actix-connect 0.2.5
    └── actix-http 0.2.10

ID:       RUSTSEC-2019-0033
Crate:    http
Version:  0.1.18
Date:     2019-11-16
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0033
Title:    Integer Overflow in HeaderMap::reserve() can cause Denial of Service
Solution:  upgrade to >= 0.1.20
```

**Comment by Keats** [comment]
It's already updated in the `next` which should be released soonish. Either way the http server is only used locally so this isn't a pressing security issue.

Thanks for the report though!
