### ISSUE TITLE
How to use zola Docker container

### ISSUE THREAD

**Issue by mikehwang** [getzola/zola#944]
I'm having trouble using zola in a Docker container because of difficulty pointing zola to the correct directory/volume.

I was able to create a project and have it write to the host machine's `/tmp/test` directory as I wanted.

```
$ docker run -it --rm -v /tmp/test:/workdir zola init /workdir/foo
```

But I can't serve that newly created project.  I tried all the following:

```
# Invalid usage.  No way to specify the path.
$ docker run -it --rm -v /tmp/test:/workdir zola serve /workdir/foo
$ docker run -it --rm -v /tmp/test:/workdir zola serve foo

# "Are you in the right directory?" error
$ docker run -it --rm -v /tmp/test:/workdir zola serve

# These were the most promising tries
$ docker run -it --rm -v /tmp/test/foo:/workdir zola serve
$ docker run -it --rm -v /tmp/test/foo:/workdir zola --config /workdir/config.toml serve
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
Done in 23ms.

Error: Can't watch the `content` folder. Does it exist?
Reason: entity not found
```

I'm stuck because I can't point `zola serve` to the project.

Before I start locally modifying my Dockerfile, I thought I'd ask here on the intended usage of zola in Docker container.  Snap is probably the better way to go but not an option for me right now.

Thank you

**Comment by Keats** [comment]
I don't use Zola in Docker so hopefully someone that does can chime in!

**Comment by stanistan** [comment]
From looking at it, the produced docker image doesn't have a workday, and possibly you have to be running `zola` from within that directory. If that's the issue you should be able to run this:

```sh
docker run -it --rm -v /tmp/test:/workdir -w workdir zola serve
```

I think you'll still need to do some port-mapping to make sure that you can access what's being served, but that at least might fix that directory error.

Relevant docker docs: https://docs.docker.com/engine/reference/run/#workdir

**Comment by mikehwang** [comment]
@stanistan thanks the `-w` arg works!  I had specified the workdir in the Dockerfile instead but your suggestion is way better.

So using Zola in Docker container looks like:

```
# Create a new Zola project called "foo"
$ docker run -it --rm -v /tmp/test:/workdir -w workdir zola init foo

# Serve up the new project called "foo".  NOTE the volume mount change
$ docker run -it --rm -v /tmp/test/foo:/workdir -p 2000:2000 -w /workdir \
    zola serve --interface 0.0.0.0 --port 2000 --base-url <host machine domain name>
```

I want to stress the volume mount change when serving up the project.  I think it would be slicker to keep the volume mount arg the same and have the Zola cli take `foo` as a positional arg like the `init` subcommand.  Something like:

```
$ docker run -it --rm -v /tmp/test:/workdir -p 2000:2000 -w /workdir \
    zola serve --interface 0.0.0.0 --port 2000 --base-url <host machine domain name> foo
```

I also want to point out that Zola in Docker container experience is essentially running zola as the command-line tool.  However, Docker containers are not great for command-line tools.  This is where Snap makes a lot of sense (which I know Zola project has but I can't take advantage of).  Maybe the the Zola in Docker container experience should be different and should be more of a service.  It could immediately serve up a specified project as the default behavior.  The cli args can be provided as environment variables.

**Comment by Rinkana** [comment]
What might also be of use is my current zola docker setup. I use this in combination with gitlab CD so every change will also be deployed. 

**Dockerfile:**
```
FROM debian:latest as zola-base
RUN apt-get update && apt-get install -y wget
RUN wget -c https://github.com/getzola/zola/releases/download/v0.10.0/zola-v0.10.0-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xz
RUN mv zola /usr/bin
RUN mkdir /site
WORKDIR /site

FROM zola-base as builder
COPY . /site
RUN zola build

FROM nginx:stable-alpine
RUN mv /usr/share/nginx/html/index.html /usr/share/nginx/html/old-index.html
COPY --from=builder /site/public/ /usr/share/nginx/html/
EXPOSE 80
```

**docker-compose.yml:**
```version: '3.6'
services:
    zola: 
        build:
            context: .
            target: zola-base
        command: zola serve --interface 0.0.0.0
        volumes:
            - .:/site
        ports:
            - '1111:1111'
```

This way the docker-compose is used for development purposes. And when running `docker build` it will build the complete setup.

**Comment by Keats** [comment]
Closing as this is a question that would be more suited to the forum: https://zola.discourse.group/
