### ISSUE TITLE
Some tags do escape while some others not

### ISSUE THREAD

**Issue by oovm** [getzola/zola#946]
## Environment

Zola version: 0.9

### Input

html in markdown

```html
<div> \left\{2\right\} </div>

<p> \left\{2\right\} </p>

<span> \left\{2\right\} </span>
```

### Output

So `span` do the escape while `div`/`p` not

![image](https://user-images.githubusercontent.com/17541209/74587048-ba232200-5028-11ea-866f-8665547ddbb2.png)

And how should I use span tags and avoid escaping?

**Comment by Keats** [comment]
Looking at https://spec.commonmark.org/dingus/ that seems to be the expected behaviour of CommonMark. Why, I don't know.
