### ISSUE TITLE
Page sort order with sort_by = "order"

### ISSUE THREAD

**Issue by pka** [getzola/zola#95]
Same section as in #94 with following order entry in the front matter:
```
_index.md:sort_by = "order"
setup.md:order = 1
serve.md:order = 2
generate.md:order = 3
configuration.md:order = 4
```

`section.pages` returns the pages in order 4, 3, 2, 1, but `page.previous` of page 2 is 1 and `page.next` of page 2 is 3. Looking at the commend of the order field I read:
> Integer to use to order content. Lowest is at the bottom, highest first

I would expect that lowest is first and highest is last, which matches previous and next. For now I have to filter the pages with `reverse` to emit a section toc.

**Comment by Keats** [comment]
You want sorting by weight, i've added it in https://github.com/Keats/gutenberg/pull/88/commits/c7bea0bc54629d45127d253e0b8fb2781c36b694 and it will be there in 0.0.8

**Comment by pka** [comment]
Great, thanks!
