### ISSUE TITLE
regression in even theme: source code not readable

### ISSUE THREAD

**Issue by getreu** [getzola/zola#955]
# Bug Report

## Environment

Zola version:  0.10.0
I updated the even theme on my blog with
`git submodule update --recursive --remote`.

## Expected Behavior
Layout should stay readable.

## Current Behavior

Source code is rendered dark blue on black background.

## Step to reproduce

See sample on [myblog](https://blog.getreu.net/20190822-enable-sound-in-torbrowswer-in-debian10-blog/)

**Comment by Keats** [comment]
I can't reproduce it on even master :/

**Comment by getreu** [comment]
I checked again. Now it is like it was before and the source code is readable again.
No idea what happened. Sorry. Nevertheless, thank you anyway.
