### ISSUE TITLE
The structure of the object returned by get_taxonomy() isn't documented

### ISSUE THREAD

**Issue by michaellenaghan** [getzola/zola#956]
# Documentation issue

## Summary
The `get_taxonomy()` function documented [here](https://www.getzola.org/documentation/templates/overview/#get-taxonomy) and implemented [here](https://github.com/getzola/zola/blob/1972e58823417a58eb1cc646ee346e7c3b04addb/components/templates/src/global_fns/mod.rs#L317) isn't documented.

From the tests [here](https://github.com/getzola/zola/blob/1972e58823417a58eb1cc646ee346e7c3b04addb/components/templates/src/global_fns/mod.rs#L424) I can see that the resulting object has a `kind` attribute and an `items` attribute; nothing on the Templates | Taxonomies page [here](https://www.getzola.org/documentation/templates/taxonomies/) has such attributes.

## Proposed solution
Document the properties [here](https://www.getzola.org/documentation/templates/taxonomies/), and link to that documentation from [here](https://www.getzola.org/documentation/templates/overview/#get-taxonomy).

**Comment by Keats** [comment]
Good point!
