### ISSUE TITLE
Two articles in blog link to each other as `page.earlier`, only with zola serve

### ISSUE THREAD

**Issue by jplatte** [getzola/zola#957]
# Bug Report

## Environment

Zola version: 0.10.0

## Expected Behavior

The older article should link to the newer one as `page.later`. This is working when the site is built with `zola build`.

## Current Behavior

With `zola serve`, the older article links to the newer one as `page.earlier`. The newer one also links to the older one as `page.earlier`, as expected.

## Step to reproduce

I noticed this when working on my blog (blog.turbo.fish). The page template can be found [here](https://git.sr.ht/~jplatte/blog.turbo.fish/tree/master/templates/page.html). I encountered this issue while writing a new article that I will probably release early next month. I added `date = 2020-03-04` to the frontmatter because of that. Not sure what else might be relevant; if this proves hard to reproduce I will try to create a minimal example.

**Comment by Keats** [comment]
This is odd, zola serve and zola build are the same things minus the webserver. Can you make a small repro?

**Comment by jplatte** [comment]
Well, after a restart this problem has disappeared..

**Comment by Keats** [comment]
It looks like it is yet another bug on the rebuild :(
