### ISSUE TITLE
Search index only includes title, not description.

### ISSUE THREAD

**Issue by thedodd** [getzola/zola#958]
# Bug Report

## Environment

Zola version: 0.10.0 & 0.9

## Expected Behavior
Being able to search based on a documents title is nice, however it seems far more often that users will need to search based on content keywords. It appears as though none of the content of a documents `description` is being indexed. Only the `title`.

## Current Behavior
It appears as though none of the content of a documents `description` is being indexed. Only the `title`.

## Step to reproduce
Build any site where the `+++` header section of the various pages have a populated `title` & `description` field. Only the contents of the `title` will be added to the generated search index.

Perhaps there are some other actions which I need to take, but as far as what is documented here (https://www.getzola.org/documentation/content/search/) I have taken all of the necessary steps.

If this is expected behavior, and only titles are being indexed on purpose, then I am happy to change this issue over to be a feature request.

**Comment by Keats** [comment]
Search currently includes title & content (https://github.com/getzola/zola/blob/master/components/search/src/lib.rs#L57-L80). The main issue with indexing `description` is that it is usually used for HTML tags and not present in the output of a page.

**Comment by thedodd** [comment]
@Keats ok, good to know. Perhaps I should have been more general in my statement, but basically nothing is being indexed at all other than the title (I assumed it would only index the description & title). 

Is there anything else I need to do to ensure that content is also indexed? 

Hmmm, actually ... because I am using this system to programmatically generate sites, all of the content actually comes in as `[extra]` variables which are rendered by the templates. Sounds like I need to dump that as raw content into the body of the page in order for it to be indexed, and then perhaps just exclude it from being rendered on the page template. 

That sounds about right?

**Comment by Keats** [comment]
Yep, as you can see in the link below the search content is taken from title (in the front matter) and the content after the front-matter. If your content is in extra that would explain why you don't get anything.

**Comment by thedodd** [comment]
Thanks @Keats that resolves my issue then. I'll close this issue.
