### ISSUE TITLE
Drafts are built during `zola serve`, second run onwards

### ISSUE THREAD

**Issue by ApoorvaJ** [getzola/zola#962]
# Bug Report

## Environment

Zola version: 0.10.0

## Expected Behavior
Draft page shouldn't be rendered.

## Current Behavior
Draft page is rendered, and also is added to the iterator `section.pages`.

## Step to reproduce

1. Create a draft markdown file `draft.md`, with `draft = true` in the frontmatter.
2. Run `zola serve`. As expected, draft is not rendered.
3. Touch `draft.md` to trigger an automatic rebuild.
4. Now check the rebuilt website. The draft will have been rendered.

**Comment by Keats** [comment]
Ah yet another bug with the rebuild... I really need to rewrite it from scratch
