### ISSUE TITLE
Variable "lang" not found in context

### ISSUE THREAD

**Issue by fyang93** [getzola/zola#963]
# Bug Report

Variable "lang" is sometimes unavailable.

## Environment

ArchLinux

Zola version: 0.10.0

## Expected Behavior

First, I have a `templates/index.html` file where a title block `<title>{% block title %}{% endblock title %}</title>` is defined in the header.

Another file `templates/tags/list.html` extends `index.html` and overwrite the title block with `{% block title %}{{ config.extra.tags[lang] }}{% endblock title %}`.

Hopefully, the title will be adjusted to the current language.

## Current Behavior

Failed to build the site
Error: Failed to render a list of tags page.
Reason: Failed to render 'tags/list.html'
Reason: Variable config.extra.tags[lang] can not be evaluated because: Variable `lang` not found in context while rendering 'tags/list.html'

## Step to reproduce

Please refer to the _Expected Behavior_ part.
And I have the following config in my `config.toml` file.
```
[extra.tags]
en="Tags"
zh="标签"
jp="タグ"
```
If you find it is hard to reproduce I could provide a minimal example later.

**Comment by Keats** [comment]
Looks like the taxonomy list template doesn't get lang like it should
