### ISSUE TITLE
Creating _index.md in Content directory causes endless redirect

### ISSUE THREAD

**Issue by kriskeillor** [getzola/zola#964]
# Bug Report
I can't create an `_index.md` file in my root content directory. I need it for essentially a 'splash page'. 

## Environment
Windows 7, Firefox 70, Zola 0.10.0

## Expected Behavior
According to the [Section documentation](https://www.getzola.org/documentation/content/section/):

> The index page (i.e., the page displayed when a user browses to your base_url) is a section, which is created whether or not you add an _index.md file at the root of your content directory. If you do not create an _index.md file in your content directory, this main content section will not have any content or metadata. If you would like to add content or metadata, you can add an _index.md file at the root of the content directory and edit it just as you would edit any other _index.md file; your index.html template will then have access to that content and metadata.

## Current Behavior
Creating a `\content\_index.md` file causes endless redirecting when I navigate to the root site address.

**Comment by Keats** [comment]
Can you make a reproduction? It does work fine for me

**Comment by kriskeillor** [comment]
[Here's a gif](https://imgur.com/a/bs2Btr3) of what happens when I rename my `content/index.md` to `content/_index.md`. Instantly causes endless looping at my root address. 

[Here is the zola branch](https://github.com/krisradio/krisradio.github.io/tree/zola) of my site. I don't have any custom templates and I'm using the [Hyde](https://zola-hyde.netlify.com/) theme.

Edit: I've been rethinking my site organization and it's probably fine that I can't make an `_index.md` file (though it's still a bug). I don't need it. But I have a question -- right now I have three directories that are all globbed onto my landing page. They are organized internally by date, but the three directories follow each other in weight/alphabetical order (not sure which). Is there a way to make all three of the sections interlace their pages by date? 

**Edit**: Nevermind, [found a solution through the Zola docs](https://tera.netlify.com/docs/#built-in-filters): 
`{% for page in section.pages | sort(attribute="date") | reverse %}`

**Comment by kriskeillor** [comment]
This issue was caused by typing the following in my frontmatter: 
```
redirect_to = ""
```
My bad for not understanding that would redirect to my root, but commenting "defaults to not used" above a field set to an empty string was mighty confusing. That's a very different issue though so I'm closing this one.

**Comment by Keats** [comment]
I'll update the docs!
