### ISSUE TITLE
Images are not regenerated during serve

### ISSUE THREAD

**Issue by Rinkana** [getzola/zola#965]
# Bug Report

## Environment

Zola version: 0.10.0

## Expected Behavior
Images should be regenerated when they change.

## Current Behavior
Currently it seems that images are only processed once. So when you add an image, rename or change the ``{{resize_image}}`` settings they won't show up. Only after restarting `zola serve` will the images come back

## Step to reproduce
- Add an asset image
- Loop assets and call `{{resize_image}}`
- Rename image after `zola serve` boot

This issue might be related to #962

**Comment by Keats** [comment]
Another serve issue :(

**Comment by florianb** [comment]
@keats why not adding a `--full-build` for `serve` flag to address the first pressure?

**Comment by Keats** [comment]
Yes that's planned for the next next version.
