### ISSUE TITLE
Default feed template conflates rss 2.0 and Atom

### ISSUE THREAD

**Issue by jplatte** [getzola/zola#967]
# Bug Report

## Environment

Zola version: 0.10.0

## Current Behavior

Zola (with `generate_rss = true`) generates a feed with an `rss` root tag with an attribute `xmlns:atom="http://www.w3.org/2005/Atom"` and `version="2.0"`. This seems like a bug. It should either be `<rss version="2.0">` or `<feed xmlns:atom="http://www.w3.org/2005/Atom">`. This is just from my cursory look at the two formats though, maybe I'm wrong.

Also, [FeedReader](https://jangernert.github.io/FeedReader/) fails to parse the feed. I will investigate whether that is related or not soon, and split that into a new issue if it has a different cause.

**Comment by Keats** [comment]
If anyone wants to pick that up. I think the intent is to support Atom.

**Comment by raindev** [comment]
I have created #969 to fix the bug in the RSS template. Supporting Atom is a good idea but probably requires some upfront discussion.

**Comment by Keats** [comment]
Looking at the Hugo one, they do the same thing: https://github.com/gohugoio/hugo/blob/d73e37387ca0012bd58bd3f36a0477854b41ab6e/tpl/tplimpl/embedded/templates/_default/rss.xml with atom namespace.
I'm going to temporarily revert your commit @raindev as I want to release a new version today while we figure out if that's the issue or whether it's something else.

**Comment by raindev** [comment]
Okay, mystery solved.

From [RSS Best Practices](http://www.rssboard.org/rss-profile#namespace-elements-atom-link):

> Recommendations

> An RSS feed can identify its own URL using the atom:link element within a channel. The link must have the rel attribute "self", an href attribute containing the feed's URL and may have a type attribute of "application/rss+xml":
> <atom:link href="http://dallas.example.com/rss.xml" rel="self" type="application/rss+xml" />

> There's no means to do this with RSS elements defined in the specification. Identifying a feed's URL within the feed makes it more portable, self-contained, and easier to cache. For these reasons, a feed should contain an atom:link used for this purpose.

> The other uses of atom:link are closely analogous to the channel link element and the item enclosure, link and source elements.

> When a namespace element duplicates the functionality of an element defined in RSS, the core element should be used.

[RSS specification](https://cyber.harvard.edu/rss/rss.html#extendingRss) indeed allows this kind of extension:
> RSS originated in 1999, and has strived to be a simple, easy to understand format, with relatively modest goals. After it became a popular format, developers wanted to extend it using modules defined in namespaces, as specified by the W3C.

> RSS 2.0 adds that capability, following a simple rule. A RSS feed may contain elements not described on this page, only if those elements are defined in a namespace.

> The elements defined in this document are not themselves members of a namespace, so that RSS 2.0 can remain compatible with previous versions in the following sense -- a version 0.91 or 0.92 file is also a valid 2.0 file. If the elements of RSS 2.0 were in a namespace, this constraint would break, a version 0.9x file would not be a valid 2.0 file. 

The W3C feed validator has [a rule](https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html) for it as well.

**Comment by jplatte** [comment]
Alright, my TinyTiny RSS / FeedReader setup also fixed itself, might have just been that adding new feeds didn't work properly before another database upgrade.

**Comment by Keats** [comment]
Perfect, thanks!
