### ISSUE TITLE
Adding a post with a tag not already seen causes error about url not found.

### ISSUE THREAD

**Issue by michael-conrad** [getzola/zola#972]
# Bug Report
```
Failed to build the site
Error: Failed to render page '.../git/CherokeeLessons.com/content/apps/bound-pronouns.md'
Reason: Failed to render 'page.html' (error happened in 'Zulma/templates/page.html').
Reason: `get_taxonomy_url`: couldn't find `Grammar` in `tags` taxonomy
```
## Environment

zola --version
zola 0.10.0

## Expected Behavior
The site should have been built.

## Current Behavior
Site fails to build as URL can not be determined for new tag.

## Step to reproduce
start zola serve
add a new post/page with a tag value which has not been previously seen.

**Comment by betoissues** [comment]
To narrow down the issue, to me it only seemed to happen when using `zola serve` where using `zola build` didn't trigger this error.

Been reading some of the source for it but the codebase is still new to me.

**Comment by Keats** [comment]
Aah `zola serve`... the whole thing needs to be rebuilt, it has too many bugs.
