### ISSUE TITLE
Feature Request: Preserve timestamps of files copied in.

### ISSUE THREAD

**Issue by michael-conrad** [getzola/zola#974]
I use rsync to deploy my site, which has some very large mp4 files.

As the timestamps are not preserved when creating the contents of the public folder for copied files and folders, rsync has to do a checksum check on each and every file to see if it really needs transferring.

**Comment by Keats** [comment]
That would be a nice feature.

**Comment by michael-conrad** [comment]
I also see where this might help with bandwidth usage some on static sites when clients send if-modified-since requests when they already have a cached copy of the content.
