### ISSUE TITLE
How does one adjust the indexing method for content to include text from all languages?

### ISSUE THREAD

**Issue by michael-conrad** [getzola/zola#975]
# Documentation issue

## Summary
How does one adjust the indexing method for content to include text from all languages in a non-filtered way?

## Proposed solution
Please indicate how to index all content, not just English.

## Why?
I run a multi-lingual site for Cherokee Language learners, they really need the ability to search by both English and Cherokee.

**Comment by Keats** [comment]
For the search you mean? Or in a template?

**Comment by michael-conrad** [comment]
For the search index js for sitewide search results. Not as part of a
template.

See <https://www.cherokeelessons.com/>

**Comment by Keats** [comment]
Ok let's add it to https://github.com/getzola/zola/issues/961 to not have too many issues about search improvements.
