### ISSUE TITLE
Netlify build errors

### ISSUE THREAD

**Issue by sirodoht** [getzola/zola#979]
# Bug Report

## Environment

Zola version: 0.9.0+

## Expected Behavior

Netlify should have run the binary successfully.

## Current Behavior

Netlify errored because of missing libraries:
```
12:36:49 PM: ./zola: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./zola)
12:36:49 PM: ./zola: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./zola)
12:36:49 PM: ./zola: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./zola)
```

## Step to reproduce

Add a `netlify.toml` like this:
```
[build]
    publish = "public"
    command = "curl -sL https://github.com/getzola/zola/releases/download/v0.10.0/zola-v0.10.0-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./zola build"

[context.deploy-preview]
    command = "curl -sL https://github.com/getzola/zola/releases/download/v0.10.0/zola-v0.10.0-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./zola build --base-url $DEPLOY_PRIME_URL"
```

Also, following the docs and using
```
[build.environment]
ZOLA_VERSION = "0.10.1"
```
doesn't seem to work as I get:
```
2:01:59 AM: Executing user command: zola build
2:01:59 AM: /usr/local/bin/build: line 34: zola: command not found
```

**Comment by Keats** [comment]
No need for the curl commands, netlify has zola built-in.

**Comment by sirodoht** [comment]
I can't find any docs for that on Netlify, and as mentioned on the last section of the issue above, following the docs and relying on Netlify to install zola didn't seem to work as I got binary not found error.

**Comment by Keats** [comment]
Which docs are you following? https://www.getzola.org/documentation/deployment/netlify/ doesn't mention curl. You need to make sure it's using the `Ubuntu Xenial 16.04 (default)` image and then it's just https://github.com/getzola/zola/blob/master/netlify.toml

**Comment by sirodoht** [comment]
Ah got it. Ubuntu 14.04 was selected as legacy by default for me.
