### ISSUE TITLE
Page summary has `<p>` tags in text

### ISSUE THREAD

**Issue by camelid** [getzola/zola#980]
# Bug Report

## Environment

Zola version: 0.10.1
Browser: Safari & Google Chrome

## Expected Behavior
An index page that shows a brief version of another page which is a post. The brief version includes the post's summary. I thought the post's summary would render like this:
```
Lorem ipsum dolor sit amet.
```

## Current Behavior
But instead the summary renders like this:
```
<p>Lorem ipsum dolor sit amet.</p>
```

## Step to reproduce
1. Install the Hyde theme and set the theme key in `config.toml`
2. Override the `index.html` template like so:
```html
{% extends "hyde/templates/index.html" %}

{% block content %}
    <div class="posts">
        {% for page in section.pages | reverse %}
          <div class="post">
            <h1 class="post-title">
              <a href="{{ page.permalink }}">
                {{ page.title }}
              </a>
            </h1>

            <span class="post-date">{{ page.date | date(format="%Y-%m-%d") }}</span>

            <p class="post-desc">{{ page.summary }}</p>
          </div>
        {% endfor %}
    </div>
{% endblock content %}
```
3. Create an `_index.md` in the root of the content folder:
```md
+++
title = "List of blog posts"
sort_by = "date"
template = "index.html"
page_template = "page.html"
+++
```
4. Create another page in the content folder (I named it `post.md`):
```md
+++
title = "My cool post"
date = 2020-03-30
+++

Lorem ipsum dolor sit amet.

<!-- more -->

Duis aute irure dolor.
```
5. Run `zola serve`

The index page will look like this:
```
My cool post
March 30, 2020
<p>Lorem ipsum dolor sit amet.</p>
```

I wonder if the problem occurs somewhere near here:
https://github.com/getzola/zola/blob/4242723e4da0c22b9961d6c18105003a8dd66d2d/components/library/src/content/page.rs#L275

Thanks for reviewing my issue!

**Comment by Keats** [comment]
That's the normal CommonMark behaviour and it's very unlikely to change. Change it to `<p class="post-desc">{{ page.summary | safe }}</p>` to render it correctly.

**Comment by camelid** [comment]
Oh, okay, thank you! Great project by the way.

**Comment by Frzk** [comment]
Hi,

I'm currently struggling with the same issue. I tried @Keats suggestion but it doesn't work as expected.
It renders like this:
```html
<p class="post-desc"></p>
<p>Actual post summary</p>
```

The only way I get it to work is:
```html
<p class="post-desc">{{ post.summary | trim_start_matches(pat="<p>") | safe }}
```
Notice there is no `</p>`, which makes the template look kind of weird or broken :-/
So, following the same logic, I tried:
```html
<p class="post-desc">{{ post.summary | trim_start_matches(pat="<p>") | trim_end_matches(pat="</p>") | safe }}</p>
```
But it doesn't render as expected:
```html
<p class="post-desc">Actual post summary</p>
<p></p>
```

**I understand that it follows the CommonMark spec so it won't change.**

I'm still asking : would there be a way to add a filter that would remove the wrapping markup ? Something that would allow us to write:
```html
<p class="post-desc">{{ post.summary | unwrap | safe }}</p>
```

**Comment by Frzk** [comment]
Just discovered that one can write the following to get the desired result:

```html
<p class="post-desc">{{ post.summary | markdown(inline=true) | safe }}</p>
```

**Comment by Jieiku** [comment]
@Frzk THANK YOU!!!!

```html
<p class="post-desc">{{ page.summary | markdown(inline=true) | safe }} <a href="{{ page.permalink }}">...more</a></p>
```
