### ISSUE TITLE
How to get a list of all languages for a page?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [getzola/zola#984]
Is it possible to get a list of all languages for a given page? I am designing a wiki and I'd like to have a simple way to give visitors the ability to switch to a different language if they land on the wrong (i.e. not the default one). I'd like to make a dropdown with a for loop that can output all of the languages, but I didn't see anything in the documentation that mentions this. (Note I can not guarantee all pages will have all of the languages in the taxonomy).

**Comment by Keats** [comment]
Pages have a `translations` field for that: https://www.getzola.org/documentation/templates/pages-sections/

**Comment by Th3Whit3Wolf** [comment]
Here is what I have tried so far.

```html
{% block lang %}
{% if lang %}{% set now_lang = lang | default (value=config.default_language) %}{% endif %}

<div class="dropdown">
    <div class="dropdown-trigger">
        <button class="button is-rounded" aria-haspopup="true" aria-controls="dropdown-menu">
            {% if now_lang == "en" %}
            English
            {% endif %}
        </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
        <div class="dropdown-content">
            {% for lang in translations %}
            <a href="#" class="dropdown-item">
                {{ lang }}
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock lang %}
```

but I get this

```sh
Building site...
-> Creating 11 pages (9 orphan), 1 sections, and processing 0 images
Error: Failed to render page '/home/doc/Code/Wiki/content/Pages/example.md'
Reason: Failed to render 'page.html'
Reason: Variable `translations` not found in context while rendering 'page.html'
```

**Comment by Keats** [comment]
`{% for lang in page.translations %}`

**Comment by Th3Whit3Wolf** [comment]
Okay so I have two files `example.md` and `example.fr.md` is there anything else that must be done for  to populate Array<TranslatedContent>?

**Comment by Keats** [comment]
If you have the language set up in the config you don't need to do anything in theory.

**Comment by Th3Whit3Wolf** [comment]
This should work right?
```toml
# config.toml

languages = [
    {code = "en"},
    {code = "fr"},
    {code = "eo"}
]
```

But all i get is

`[object]`

**Comment by Keats** [comment]
the object you're iterating on in page.translations is not a string: https://www.getzola.org/documentation/templates/pages-sections/#translated-content

**Comment by Th3Whit3Wolf** [comment]
What should I do to get a string?

**Comment by Keats** [comment]
That depends what you want to display...? Have a look at the link below and pick the appropriate field

**Comment by Th3Whit3Wolf** [comment]
The language. 

I thought that would be the result of this

```html
{% for lang in page.translations %}
    <a href="#" class="dropdown-item">
        {{ lang }}
    </a>
{% endfor %}
```

**Comment by Th3Whit3Wolf** [comment]
Whoops I see what I did wrong so sorry for bothering you.

**Comment by Th3Whit3Wolf** [comment]
This is what I was looking for

```html
{% for translation in page.translations %}
    <a href="{{ translation.permalink }}" class="dropdown-item">
        {{ translation.lang }}
    </a>
{% endfor %}
```
