### ISSUE TITLE
More power over url name

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [getzola/zola#985]
This issue is similiar to [840](https://github.com/getzola/zola/issues/840) with a couple additions.
I'd like to be able to make a site `/foo` instead of `/foo/index.html` I don't like having a directory that's only meant to contain a single item. I'd also like more control over how zola creates names for urls. 

For example I'd like to do something like this.

```
.
└── content
    ├── content
    │   └── First_Item.md // -> https://mywebsite.com/content/First_Item
    ├── blog
    │   ├── cli:usage.md // -> https://mywebsite.com/blog/cli:usage
    │   ├── Configuration.md // -> https://mywebsite.com/blog/Configuration/
    │   ├── directory_structure.md // -> https://mywebsite.com/blog/directory_structure
    │   ├── _index.md // -> https://mywebsite.com/blog/
    │   └── installation.md // -> https://mywebsite.com/blog/installation
```

**Comment by betoissues** [comment]
Ain't this what the `path` option is for or am I missing something?

**Comment by Keats** [comment]
I think it means @Th3Whit3Wolf wants what Hugo calls ugly urls, eg /foo.html ?

**Comment by Th3Whit3Wolf** [comment]
Yes @Keats that is what I mean

**Comment by Keats** [comment]
I don't think it will be added to Zola, in the last 3 years only 2 people including @Th3Whit3Wolf  asked for it and the other ended up preferring URLs without .html...
