### ISSUE TITLE
Feature Request: "post pinning"

### ISSUE THREAD

**Issue by michael-conrad** [getzola/zola#988]
Add an option in a posts header to permit "pinning" the post as "first" in it's own section.

The goal would be to allow sort_by="date" to get sort by when published, except for any posts marked as "pinned" which get moved to the "top" of the list.

**Comment by Keats** [comment]
You can build that easily, putting a slug in the section extra for the current pinned post and fetching it with get_page, no need for a built-in feature.

**Comment by michael-conrad** [comment]
Please elucidate for those of us not that familiar with template building.

**Comment by stanistan** [comment]
Code example:

In the section front matter:

```
[extra]
pinned_post = “some-slug.md”
```

Then in the section template:

```
{% set pinned_post = get_page(path=section.extra.pinned_post) %}
```

**Comment by Keats** [comment]
Exactly. You might need to have the full path in `pinned_post` for `get_page` to work well but that's what I had in mind.
