### ISSUE TITLE
Tell people not to use the markdown filter on page or section content

### ISSUE THREAD

**Issue by TeFiLeDo** [getzola/zola#989]
# Documentation issue

## Summary
On the `Templates/Overview` page, the documentation mentions a `markdown` filter, that turns markdown content into HTML. On the `Templates/Sections and Pages` page, it also explains that both pages and sections get a `content` variable.

However, as far as I know, it isn't mentioned anywhere, that the `content` variable already contains HTML. This lead me to use the filter in my template and write `{{ page.content | markdown | safe }}` instead of `{{ page.content | safe }}`.

While this might not seem like a problem (since markdown can contain HTML), it causes a problem in code block, where any indentation is removed after an empty line. There might also be other problems I didn't notice.

## Proposed solution
Either tell users that the `content` variable contains HTML on the `Templates/Sections and Pages` page or tell them to not use the `markdown` filter on the `content` variable on the `Templates/Overview` page.

I personally think the first one is the better solution because otherwise, this would feel like a special case for the `content` variable, while it actually affects every HTML input.

**Comment by Keats** [comment]
Good point!

**Comment by Keats** [comment]
I've updated the docs in the `next` branch.

**Comment by TeFiLeDo** [comment]
Thank you very much!
