### ISSUE TITLE
Creating the root index.html as a regular page

### ISSUE THREAD

**Issue by mneumann** [getzola/zola#99]
I want the root index.html to be a regular page. Right now, what I have to do is to name it ```content/_index.md``` and have a special template that iterates over all pages of that section and filters out the page I want to show as root page. 

Is there an easier way to accomplish that? I assume, for regular (non-blog) home pages, it is a very common case to have a landing page which is special and not only serves as an index showing a list of blog posts.

**Comment by Keats** [comment]
All `_index.md` files can also have a body just like pages so you can have your content there, for example https://github.com/Keats/tera/blob/master/docs/content/docs/_index.md

**Comment by mneumann** [comment]
Thanks! That works!
