### ISSUE TITLE
Taxonomy pages aren't built if taxonomy isn't used

### ISSUE THREAD

**Issue by TeFiLeDo** [getzola/zola#992]
# Documentation issue

## Summary
If you define a taxonomy in your `config.toml` but never use it, the taxonomy pages (the folder in `public` containing the HTML files for the taxonomy) are not created. As far as I know, this behaviour isn't documented anywhere.

Documenting this is relevant to inform users that they don't have to handle the case that a taxonomy doesn't contain any terms.

## Proposed solution
Tell users in `Templates/Taxonomies` and `Content/Taxonomies` that taxonomies don't exist in the output if they don't contain any terms.

## Personal note
Honestly, I'm not sure whether this is a documentation issue or a bug. While the HTML files aren't created, you can still find the taxonomy in the `config.taxonomies` variable.

Furthermore, if the pages were created even for empty taxonomies, you could show the visitors of your website that the taxonomy exists but is empty for the time being. Currently, they'd only get a 404 error.

**Comment by Keats** [comment]
Right now it's intentional, taxonomies are only created if there is at least one item. It could be changed though.
