### ISSUE TITLE
Small output inconsistency depending on whether content/_index.md exists

### ISSUE THREAD

**Issue by pkgw** [getzola/zola#995]
# Bug Report

## Environment

Zola version: 0.10.1

## Expected Behavior

When processing the site index, the `current_path` variable should always be "/". Unless it should always be "".

## Current Behavior

If `content/_index.md` exists, when the `index.html` template is processed the value of `current_path` will be "/". If `content/_index.md` does not exist, `current_path` is the empty string.

## Step to reproduce

- Create a site
- Write an `index.html` template that exposes the value of `current_path`
- Examine the HTML generated depending on whether `content/_index.md` exists

## Notes

I would expect that `current_path` should be the same regardless. But maybe there is a good reason that it's not?

**Comment by Keats** [comment]
It's an oversight, that will be fixed in the next release. Thanks for that!
