### ISSUE TITLE
Update docs on output paths (i18n + slugification)

### ISSUE THREAD

**Issue by southerntofu** [getzola/zola#998]
# Documentation issue

## Summary
Docs on [page output paths](https://www.getzola.org/documentation/content/page/#output-paths) and [taxonomy output paths](https://www.getzola.org/documentation/content/taxonomies/#output-paths) are out of dates. Section docs do not current mention slugification.

## Proposed solution
Now that there's a bunch of different global settings (translations, slugify) that affect output paths, it would make sense to create a unified content/output-paths.pd, with page, section, taxonomy and multilingual docs linking there.

I'm willing to submit a PR for that if such modifications are desired.

**Comment by Keats** [comment]
There is some docs at the bottom of https://www.getzola.org/documentation/getting-started/configuration/ and a few more changes in the `next` branch. Let me merge https://github.com/getzola/zola/pull/994 and we can have a look where the docs are still missing.

**Comment by southerntofu** [comment]
Nice, `slugify_paths` has been indeed removed from docs with #994 

What do you think about a unified page for output paths? I think that would come in handy when browsing the docs to have in one place:

- config's "slugification strategies"
- multilingual's "output"
- page/section/taxonomy specific info

Simply looking at this page you would be able to understand how any file/setting will generate URLs for your site.

**Comment by Keats** [comment]
It would be a good idea.

**Comment by Keats** [comment]
@southerntofu do you have time to work on that?
