### ISSUE TITLE
How to use markdown in shortcodes

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [getzola/zola#999]
Hi there, shortcodes don't seem to work as I would expect them to in regards to markdown. (using zola v10)

Here is my shortcode for notes

```html
<article class="message is-link">
    <div class="message-body">
    <strong>{{ head }}</strong><br/>
    {{ body }}
    </div>
</article>
```

Here is my markdown for notes

```md
{% note(head="Note:") %}

* item 1
* **item bold**
* *item italic*

{% end %}
```

What gets rendered

```html
</span></pre><article class="message is-link">
    <div class="message-body">
    <strong>Note:</strong><br/>
    * item 1
* **item bold**
* *item italic*
    </div>
</article>
```

Reading through the doucmentation I thought maybe if I add the markdown filter It will fix it.

New Shortcode

```html
<article class="message is-link">
    <div class="message-body">
    <strong>{{ head }}</strong><br/>
    {{ body | markdown(inline=true)  }}
    </div>
</article>
```

But now this gets rendered

```html
</span></pre><article class="message is-link">
    <div class="message-body">
    <strong>Note:</strong><br/>
    &lt;ul&gt;
&lt;li&gt;item 1&lt;&#x2F;li&gt;
&lt;li&gt;&lt;strong&gt;item bold&lt;&#x2F;strong&gt;&lt;&#x2F;li&gt;
&lt;li&gt;&lt;em&gt;item italic&lt;&#x2F;em&gt;&lt;&#x2F;li&gt;
&lt;&#x2F;ul&gt;
    </div>
</article>
```

How do I get markdown to go through the shortcode properly

**Comment by Keats** [comment]
You were very close: `{{ body | markdown(inline=true) | safe }}`

**Comment by Th3Whit3Wolf** [comment]
Thank you @Keats! You are always so quick to respond. Code fences don't do syntax when rendered through short codes. Is there anyway around this?

**Comment by Keats** [comment]
you mean they don't do syntax highlighting? That's an issue with the current markdown filter which needs to be fixed.

**Comment by Th3Whit3Wolf** [comment]
Yeah that's what I mean. Is this issue with pulldown-cmark or zola internally?

**Comment by Keats** [comment]
Zola. For the content we do write our own custom pulldown-cmark renderer and we should re-use it in the filter but we don't right now.

**Comment by Th3Whit3Wolf** [comment]
Oh okay. Thanks for the information!
